### ISSUE TITLE
ValueError: Not able to find installed Package in latest version

### ISSUE THREAD

**Issue by hash3liZer** [pyinstaller/pyinstaller#6833] opened 2022-05-18 17:25 UTC
I recently updated my pyinstaller to latest version from `4.9` to `5.1` on **Windows 10 x64** But now i am getting that a specific package was not found. I am importing `soundfile` in my file. And i simply compiled: 

```bash
$ pyinstaller file.py
```

But now, i am getting the following error that `raise ValueError(f"Package '{package}' does not exist or is not a package!")`. This is not the case with `4.9` or previous. Just something in the latest version. The complete stack trace of the error is: 

```python
266 INFO: PyInstaller: 5.1
266 INFO: Python: 3.9.12
275 INFO: Platform: Windows-10-10.0.20348-SP0
276 INFO: wrote D:\a\212-agent\212-agent\agent.spec
280 INFO: UPX is not available.
280 INFO: Removing temporary files and cleaning cache in C:\Users\runneradmin\AppData\Local\pyinstaller
281 INFO: Extending PYTHONPATH with paths
['D:\\a\\212-agent\\212-agent']
702 INFO: checking Analysis
702 INFO: Building Analysis because Analysis-00.toc is non existent
702 INFO: Initializing module dependency graph...
704 INFO: Caching module graph hooks...
719 INFO: Analyzing base_library.zip ...
5341 INFO: Processing pre-find module path hook distutils from 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
5341 INFO: distutils: retargeting to non-venv dir 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib'
12172 INFO: Caching module dependency graph...
12367 INFO: running Analysis Analysis-00.toc
12395 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\hostedtoolcache\windows\Python\3.9.12\x64\python.exe
13761 INFO: Analyzing D:\a\212-agent\212-agent\agent.py
15683 INFO: Processing pre-find module path hook site from 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
15684 INFO: site: retargeting to fake-dir 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\PyInstaller\\fake-modules'
23304 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
27124 INFO: Processing module hooks...
27125 INFO: Loading module hook 'hook-certifi.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
27130 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
27687 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
27688 INFO: Loading module hook 'hook-sounddevice.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.9.12\\x64\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\building\build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\building\build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "D:\a\212-agent\212-agent\agent.spec", line 7, in <module>
    a = Analysis(
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\building\build_main.py", line 319, in __init__
    self.__postinit__()
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\building\build_main.py", line 487, in assemble
    self.graph.process_post_graph_hooks(self)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\depend\analysis.py", line 326, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\depend\imphook.py", line 398, in post_graph
    self._load_hook_module()
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\depend\imphook.py", line 361, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\compat.py", line 620, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-sounddevice.py", line 24, in <module>
    sfp = get_package_paths("sounddevice")
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 582, in get_package_paths
    raise ValueError(f"Package '{package}' does not exist or is not a package!")
ValueError: Package 'sounddevice' does not exist or is not a package!
```

**Comment by rokm** [comment] 2022-05-18 17:31
Duplicate of https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/432 (both `sounddevice` and `soundfile` hooks have the same problem).

**Closed as completed by rokm** 2022-05-18 17:31 UTC
Labels: solution:duplicate
