### ISSUE TITLE
Default Windows exe icon

### ISSUE THREAD

**Issue by StnadardUsre** [pyinstaller/pyinstaller#3591] opened 2018-06-24 12:34 UTC
Is there a way to create an exe on Windows without any icon? I mean - it should have default exe icon, depending on Windows version. Thanks.

**Comment by htgoebel** [comment] 2018-06-26 07:52
You could
a) use Windows development tools to remove the icon resource
b) implement #870 plus some `icon=NOICON` special case.

Duplicate of #870

**Closed by htgoebel** 2018-06-26 07:52 UTC
