### ISSUE TITLE
How do I package pyinstaller as an exe using pyinstaller or other tools?

### ISSUE THREAD

**Issue by NewRoad123** [pyinstaller/pyinstaller#8578] opened 2024-06-03 09:07 UTC
I want to package pyinstaller as an exe, when i run the exe, a lot of threads are spawned, so i have to enter 'ctrl+c',  then some error raise.

Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 92, in <module>
  File "<frozen genericpath>", line 42, in isdir
KeyboardInterrupt
[15452] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
Traceback (most recent call last):
  File "PyInstaller\isolated\_parent.py", line 389, in call
  File "PyInstaller\isolated\_parent.py", line 304, in call
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller\__main__.py", line 232, in <module>
  File "PyInstaller\__main__.py", line 170, in run
  File "PyInstaller\__main__.py", line 136, in generate_parser
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\build_main.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\api.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\splash.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\utils\hooks\tcl_tk.py", line 66, in <module>
  File "PyInstaller\isolated\_parent.py", line 420, in wrapped
  File "PyInstaller\isolated\_parent.py", line 388, in call
  File "PyInstaller\isolated\_parent.py", line 257, in __exit__
OSError: [Errno 22] Invalid argument

**Comment by rokm** [comment] 2024-06-03 09:25
> I want to package pyinstaller as an exe,

Duplicate of #6462. In short, you can't.

**Closed as not planned by rokm** 2024-06-03 09:25 UTC

**Comment by NewRoad123** [comment] 2024-06-03 09:58
@rokm Thank you very much!
