### ISSUE TITLE
Matplotlib 1.3.0 and mpl_tookit

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#769] opened 2014-10-18 14:43 UTC
**Original date**: 2013/09/13
**Original reporter**: *michkapopoff AND gmail DOT  COOM *

Hi

I just tested the latest development version of pyinstaller with matplotlib 1.3.0. I get the following error when I launch the created app : ImportError: No module named mpl_toolkits

I had no problem with mpl 1.2.X

To reproduce the error, juste try to create an app starting with: 
```python
from mpl_toolkits import axes_grid1
```

So something has changed in 1.3.0. Perhaps there is only the need to add a hook pro mpl_toolkits, but my knowledge is quite limited for those things. There seem to be the same problem with py2exe (http://stackoverflow.com/questions/18596410/importerror-no-module-named-mpl-toolkits-with-maptlotlib-1-3-0-and-py2exe), so I think the problem is due to the changes in matplotlib 1.3.0.

**Comment by matysek** [comment] 2015-09-04 19:59
This should be fixed. I was not able to reproduce it with matplotlib 1.4.3. I added a test for this.

**Closed by matysek** 2015-09-04 19:59 UTC
Labels: develop, PY3

**Comment by matysek** [comment] 2015-09-04 20:03
According to http://stackoverflow.com/questions/18596410/importerror-no-module-named-mpl-toolkits-with-maptlotlib-1-3-0-and-py2exe it looks like this was related to #502.

**Comment by htgoebel** [comment] 2015-09-05 15:56
ACK. The code there shows it is using `pkg_resources.declare_namespace()`, which PyInstaller supports (see https://github.com/pyinstaller/pyinstaller/issues/502#issuecomment-129922052).
