### ISSUE TITLE
sklearn/joblib spawns multiple copies when frozen on macOS

### ISSUE THREAD

**Issue by CliffMitchell** [pyinstaller/pyinstaller#4110] opened 2019-03-08 21:26 UTC
I am running Python 3.7.2 with PyInstaller 3.4 and PyQT5 5.12, on macOS Mojave 10.14.3.

Running a 1-line script:
`import sklearn`
frozen with PyInstaller causes an infinite loop - the app spawns multiple copies of itself. Adding an exclusion to the PyInstaller .spec file:
`excludes=['sklearn.externals.joblib']`
fixes the problem. The underlying problem is that freezing an app that calls joblib causes an infinite loop. You can prove this by freezing a 1-line script
import joblib
and you will see that this causes an infinite loop.
My app does NOT call joblib directly, but uses the machine learning features in sklearn. Unfortunately, sklearn calls joblib and this is what is causing my app to loop when frozen. This appears to be a bug in PyInstaller?

**Comment by theArtechnology** [comment] 2019-03-10 19:47
I am having the similar issue ! But could not resolve it the same way, how did you come to this solution? Like knowing exactly that it was the joblib so that I will make a similar test to find my issue ! Thanks

**Comment by CliffMitchell** [comment] 2019-03-10 19:51
@theArtechnology Take a look at the last few entries in this thread: https://github.com/pyinstaller/pyinstaller/issues/4067

**Comment by BLKSerene** [comment] 2019-03-19 11:25
I could confirm that this issue also appears on Linux.

**Comment by stravassac** [comment] 2019-03-28 10:18
same issue on Linux python 3.6.7 with joblib

**Comment by tbsexton** [comment] 2019-05-03 17:38
same problem packaging [this app](https://github.com/usnistgov/nestor) on Ubuntu. All data files have been added correctly, and app script starts up fine, but proceeds to spawn infinitely. 

I understand the joblib backend has been switched to `lokey`? And that the sklearn devs are [un-vendoring joblib](https://github.com/scikit-learn/scikit-learn/pull/13531)? Not sure this will have any effect, though. I do know that the `multiprocessing.freeze_support()` suggestion from other threads is not working. removing joblib with `excludes` is also not working, obviously.

**Comment by tbsexton** [comment] 2019-05-17 14:39
@letalvoj seems to have [found a fix](https://github.com/pyinstaller/pyinstaller/issues/4067#issuecomment-493456359), by enforcing 

```
scikit-learn==0.21.1
joblib==0.11
``` 

Strange, and definitely not a long-term fix, but something with the new sklearn/joblib stack is incompatible, for sure.

**Comment by hossam26644** [comment] 2019-06-26 10:03
Experienced the same issue without using scikit-learn, the current joblib version seems to be root cause, fixed by using joblib==0.11

**Comment by htgoebel** [comment] 2019-08-10 12:04
>Adding an exclusion to the PyInstaller .spec file:
`excludes=['sklearn.externals.joblib']`
fixes the problem.

I suggest putting this into a hook for `sklearn.externals` or `sklearn`. Would this imposs unexpected
side-effects?

We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by BLKSerene** [comment] 2019-11-09 14:40
This issue could be closed now, as `joblib` 0.14.0 has fixed this problem.

**Closed** 2019-11-16 14:32 UTC
Labels: good first issue, hooks, pull-request wanted

**Comment by jsl303** [comment] 2020-07-29 05:25
I don't use sklearn nor joblib, and the built app keeps launching itself over and over.
I'm using multiprocessing.Process and Value.
Pyinstaller: 3.6
Python: 3.8.5
MacOS: 10.14.6
WXPython: 4.1.0

**Comment by Hyun-Woo-Jo** [comment] 2021-11-09 08:33
I think most of you hesitate to modify or not use joblib (I did) because it is interlinked to many other libraries.
I have solve the problem in a following method. 
`root.protocol("WM_DELETE_WINDOW", lambda: [sys.exit()])`

In case of you are using tkinter, the code forces the exe to quit when you quit pyinstaller.
However, it does not work when the tkinter is not run on exe, so I made a variable at the top of my script.

`stand_alone = False`
and use it as follows:
`if stand_alone: root.protocol("WM_DELETE_WINDOW", lambda: [sys.exit()])`

All you need to do is change 'stand alone' to True before using pyinstaller.
I hope it helps.
