### ISSUE TITLE
Mac .app double click not run！Executable runs fine

### ISSUE THREAD

**Issue by 18237634625** [pyinstaller/pyinstaller#6956] opened 2022-07-18 07:01 UTC
### pyinstaller 3.9.10

1、pyinstaller success!

```
(py3_9_10) ➜  test pyinstaller -F -w test.py
121 INFO: PyInstaller: 5.2
121 INFO: Python: 3.9.10
140 INFO: Platform: macOS-12.3.1-x86_64-i386-64bit
141 INFO: wrote /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/test.spec
150 INFO: UPX is not available.
151 INFO: Extending PYTHONPATH with paths
['/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test']
321 INFO: checking Analysis
321 INFO: Building Analysis because Analysis-00.toc is non existent
321 INFO: Initializing module dependency graph...
323 INFO: Caching module graph hooks...
338 INFO: Analyzing base_library.zip ...
2492 INFO: Processing pre-find module path hook distutils from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2499 INFO: distutils: retargeting to non-venv dir '/Users/admin/.pyenv/versions/3.9.10/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9'
4991 INFO: Caching module dependency graph...
5113 INFO: running Analysis Analysis-00.toc
5126 INFO: Analyzing /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/test.py
5127 INFO: Processing module hooks...
5128 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5129 INFO: Loading module hook 'hook-lib2to3.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5183 INFO: Loading module hook 'hook-_tkinter.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5186 INFO: Not collecting Tcl/Tk data - either python is using macOS' system Tcl/Tk framework, or Tcl/Tk data directories could not be found.
5186 INFO: Loading module hook 'hook-encodings.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5332 INFO: Loading module hook 'hook-distutils.util.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5336 INFO: Loading module hook 'hook-platform.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5337 INFO: Loading module hook 'hook-pickle.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5339 INFO: Loading module hook 'hook-heapq.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5342 INFO: Loading module hook 'hook-difflib.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5344 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5346 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5358 INFO: Loading module hook 'hook-xml.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5403 INFO: Loading module hook 'hook-distutils.py' from '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks'...
5415 INFO: Looking for ctypes DLLs
5434 INFO: Analyzing run-time hooks ...
5436 INFO: Including run-time hook '/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
5441 INFO: Looking for dynamic libraries
5713 INFO: Looking for eggs
5713 INFO: Using Python library /Users/admin/.pyenv/versions/3.9.10/Library/Frameworks/Python.framework/Versions/3.9/Python
5718 INFO: Warnings written to /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/build/test/warn-test.txt
5738 INFO: Graph cross-reference written to /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/build/test/xref-test.html
5746 INFO: checking PYZ
5746 INFO: Building PYZ because PYZ-00.toc is non existent
5746 INFO: Building PYZ (ZlibArchive) /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/build/test/PYZ-00.pyz
5917 INFO: Building PYZ (ZlibArchive) /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/build/test/PYZ-00.pyz completed successfully.
5920 INFO: EXE target arch: x86_64
5920 INFO: Code signing identity: None
5920 INFO: checking PKG
5920 INFO: Building PKG because PKG-00.toc is non existent
5920 INFO: Building PKG (CArchive) test.pkg
8034 INFO: Building PKG (CArchive) test.pkg completed successfully.
8036 INFO: Bootloader /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/lib/python3.9/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
8036 INFO: checking EXE
8036 INFO: Building EXE because EXE-00.toc is non existent
8036 INFO: Building EXE from EXE-00.toc
8036 INFO: Copying bootloader EXE to /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/dist/test
8038 INFO: Converting EXE to target arch (x86_64)
8065 INFO: Removing signature(s) from EXE
8091 INFO: Appending PKG archive to EXE
8096 INFO: Fixing EXE headers for code signing
8107 INFO: Re-signing the EXE
8155 INFO: Building EXE from EXE-00.toc completed successfully.
8159 INFO: checking BUNDLE
8159 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
8159 INFO: Building BUNDLE BUNDLE-00.toc
8164 INFO: Moving BUNDLE data files to Resource directory
8164 INFO: Signing the BUNDLE...
8215 INFO: Building BUNDLE BUNDLE-00.toc completed successfully.
(py3_9_10) ➜  test 

```

2、My python code, just print('Hello Word')

```
print ('Hello Word')
```
I simply run pyintaller to package test.py. I can't figure out what's wrong! ! !

I tried the same packing operation with python2.7.18 + pyinstaler3.6. But the result is still the same, exec file Can run through terminal, .app can't run by double clicking

Click dist - exec to run the result

```
Last login: Fri Jul 15 15:03:02 on ttys004
/Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/dist/test ; exit;
➜  ~ /Users/admin/.pyenv/versions/3.9.10/envs/py3_9_10/test/dist/test ; exit;
Hello Word

Saving session...completed.

[进程已完成]
```

I did nothing but just executed `pyinstaller --onefile --windowed test.py`

**Comment by rokm** [comment] 2022-07-18 08:36
Duplicate of #6941. If you want an .app bundle that opens a console, you need to replace the executable with a script wrapper that opens the console and runs the (renamed) executable in it. See #5154, especially https://github.com/pyinstaller/pyinstaller/issues/5154#issuecomment-690646012.

**Closed as completed by rokm** 2022-07-18 08:36 UTC
Labels: solution:invalid
