### ISSUE TITLE
FileNotFoundError about paddle

### ISSUE THREAD

**Issue by itues** [pyinstaller/pyinstaller#5976] opened 2021-07-06 09:49 UTC
* Output of `pyinstaller --version`: 4.3
* Version of Python: 3.8.10
* Platform: win10
My code runs normally, but after encapsulation, it will report  an error ,  Because the error is prompted to the folder, I don't know which file is missing at all. In fact, I have copied the Lib file under this file. But it still can't be solved. Please have a look. thank you.
![image](https://user-images.githubusercontent.com/86935392/124578717-09b5f800-de81-11eb-948c-5a3650b4bbdd.png)

**Comment by bwoodsend** [comment] 2021-07-06 10:19
@itues This is an issue tracker - not a support forum. If you have a bug to report then fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by rokm** [comment] 2021-07-06 13:46
This error is caused by `paddle` calling `add_dll_directory` with a path that does not exist in the frozen application bundle (i.e., `paddle\libs`.

Either PyInstaller did not collect anything from that directory, or all files that it collected were shared libraries and those were collected into application bundle's top directory instead (which is due to how PyInstaller works...). And because PyInstaller does not collect/re-create empty directories, `paddle\libs` is missing from the application bundle.

You can either manually collect a single file from `paddle\libs` (e.g., using `--add-data` command-line argument), which will ensure that the directory exists in the frozen application bundle.

Or you can patch your paddle installation to catch and swallow the exception when calling `add_dll_directory` (in `paddle\fluid\core`, line 49). (Or check if it exists and only then call `add_dll_directory`).

**Comment by rokm** [comment] 2021-07-20 19:08
I'm closing this because at this point, there's nothing we can do about it - it's the way PyInstaller operates (i.e., the shared libraries are collected into top-level directory, and empty directories are not collected/re-created, so `paddle\libs` directory ends up missing).

**Closed by rokm** 2021-07-20 19:08 UTC
