### ISSUE TITLE
Getting tkinter to work

### ISSUE THREAD

**Issue by rutheferd** [pyinstaller/pyinstaller#1779] opened 2016-01-18 23:48 UTC
Hey,

I am having trouble getting tkinter to work with pyinstaller! 
Here is the code for my test script:
    
    #! /usr/bin/env python3

    #Hello World

    import os
    import openpyxl
    from tkinter import *

    root = Tk()

    print('Hello World')

    root.mainloop()

This is what I ran to build the app: 
**pyinstaller --hidden-import tkinter hello.py**

(I had to do the hidden-import to have tkinter even so up!)

This is my console reading after trying to run the built app:

`  File "<string>", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "tkinter/__init__.py", line 35, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/Users/adrianruth/Documents/Projects/dist/hello/_tkinter.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /Users/adrianruth/Documents/Projects/dist/hello/_tkinter.cpython-35m-darwin.so
  Reason: no suitable image found.  Did find:
	/Users/adrianruth/Documents/Projects/dist/hello/Tcl: not a file
	/Users/adrianruth/Documents/Projects/dist/hello/Tcl: not a file
hello returned -1
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

Thanks!!

I am using OS X El Capitan, python 3.5, pyinstaller 3.1

[Terminal Readout.txt](https://github.com/pyinstaller/pyinstaller/files/95138/Terminal.Readout.txt)

**Comment by htgoebel** [comment] 2016-01-19 11:59
Duplicate of #1737

**Closed by htgoebel** 2016-01-19 11:59 UTC

**Comment by makar-y** [comment] 2018-11-24 05:44
How is that a duplicate if it's a completely different error message? I have this error, but it has nothing to do with the one the duplicate comment redirects to

**Comment by htgoebel** [comment] 2018-12-06 12:09
Because both are cause by an incomplete tcl
