### ISSUE TITLE
executable built on appveyor does not seem to respect --noconsole

### ISSUE THREAD

**Issue by BjornFJohansson** [pyinstaller/pyinstaller#1611] opened 2015-10-17 08:56 UTC
Hi all,

I have a small wxpython [app](https://github.com/BjornFJohansson/seguid_calculator) for which I build windows executables using Appveyor.

They are built using:

    pyinstaller --noconsole --icon=calc.ico --onefile seguid.py --name seguid_calculator

The build depends on pywin32 and wxpython which is the new phoenix version.

see [appveyor.yml](https://github.com/BjornFJohansson/seguid_calculator/blob/master/appveyor.yml)

the problem is that although I have specified the --noconsole switch, windows [executables](https://ci.appveyor.com/project/BjornFJohansson/seguid-calculator/build/1.0.80/job/8symw83lraslji4j/artifacts)
still open an empty window upon starting the application. Otherwise it works as expected.

This does not happen for linux executables built in the same way.
I use PyInstaller 3.1.dev0-199cbd7

grateful for help. 

/bjorn

**Comment by matysek** [comment] 2015-10-17 20:43
> This does not happen for linux executables built in the same way.
> I use PyInstaller 3.1.dev0-199cbd7

* On Linux this is expected since console window is a Windows only feature.
* I'm able to reproduce it.

**Comment by matysek** [comment] 2015-10-17 20:45
@BjornFJohansson It should be fixed. Please try the referenced version and reopen if it does not work. Thanks for reporting.

**Closed by matysek** 2015-10-17 20:45 UTC
Labels: develop, Windows

**Comment by BjornFJohansson** [comment] 2015-10-18 06:42
works! thank you very much!
