### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by adammenges** [pyinstaller/pyinstaller#1567] opened 2015-10-01 17:46 UTC
Hello there, I'm back again. :smile: 

This time I thought I'd make it dead simple to reproduce the error I'm seeing. The simpleapp repo can be found here: https://github.com/adammenges/simpleapp. Basically I just import a bunch of things from sklearn and nltk.

This was run with the latest in develop. Here's stdout:

```bash
adammenges@Wolfsberg:~/Development/simpleapp|master
⇒  python app.py
hello
adammenges@Wolfsberg:~/Development/simpleapp|master
⇒  pyinstaller app.py
15 INFO: PyInstaller: 3.0.dev8+0f0f63d.mod
15 INFO: Python: 2.7.10
19 INFO: Platform: Darwin-14.5.0-x86_64-i386-64bit
20 INFO: wrote /Users/adammenges/Development/simpleapp/app.spec
20 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/local/opt/python/bin/python2.7

1027 INFO: UPX is not available.
1028 INFO: Extending PYTHONPATH with /Users/adammenges/Development/simpleapp
1028 INFO: checking Analysis
1028 INFO: Building Analysis because out00-Analysis.toc is non existent
1028 INFO: Initializing module dependency graph...
1029 INFO: Initializing module graph hooks...
1066 INFO: running Analysis out00-Analysis.toc
1071 INFO: Analyzing /Users/adammenges/Development/simpleapp/app.py
5321 INFO: Processing pre-find module path hook   distutils
7608 INFO: Processing pre-find module path hook   site
7608 INFO: site: retargeting to fake-dir '/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/fake-modules'
10840 INFO: Processing pre-safe import module hook   six.moves
20934 INFO: Looking for import hooks ...
20935 INFO: Processing hook   hook-distutils.py
20936 INFO: Processing hook   hook-sysconfig.py
20936 INFO: Processing hook   hook-xml.py
20937 INFO: Processing hook   hook-scipy.sparse.csgraph.py
20939 INFO: Processing hook   hook-scipy.io.matlab.py
20940 INFO: Processing hook   hook-httplib.py
20940 INFO: Processing hook   hook-pydoc.py
20940 INFO: Excluding import 'Tkinter'
20940 INFO: Processing hook   hook-encodings.py
21285 INFO: Processing hook   hook-_tkinter.py
21288 INFO: checking Tree
21288 INFO: Building Tree because out00-Tree.toc is non existent
21288 INFO: Building Tree out00-Tree.toc
21333 INFO: checking Tree
21333 INFO: Building Tree because out01-Tree.toc is non existent
21333 INFO: Building Tree out01-Tree.toc
21352 INFO: Processing hook   hook-matplotlib.backends.py
21615 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
21818 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
21947 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named gtk
22177 INFO:   Matplotlib backend "MacOSX": added
22383 INFO:   Matplotlib backend "Qt4Agg": ignored
    Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.
22587 INFO:   Matplotlib backend "Qt5Agg": ignored
    Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.
22803 INFO:   Matplotlib backend "TkAgg": added
23002 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
23203 INFO:   Matplotlib backend "WXAgg": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
23333 INFO:   Matplotlib backend "CocoaAgg": ignored
    The CococaAgg backend required PyObjC to be installed!
23463 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
23662 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
/usr/local/lib/python2.7/site-packages/IPython/kernel/__init__.py:10: UserWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated. "
23989 INFO:   Matplotlib backend "WebAgg": ignored
    No module named ipykernel
/usr/local/lib/python2.7/site-packages/IPython/kernel/__init__.py:10: UserWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated. "
24218 INFO:   Matplotlib backend "nbAgg": ignored
    No module named ipykernel
24418 INFO:   Matplotlib backend "agg": added
24551 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
24680 INFO:   Matplotlib backend "emf": ignored
    No module named backend_emf
24810 INFO:   Matplotlib backend "gdk": ignored
    No module named gobject
25012 INFO:   Matplotlib backend "pdf": added
/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_pgf.py:54: UserWarning: error getting fonts from fc-list
  warnings.warn('error getting fonts from fc-list', UserWarning)
25221 INFO:   Matplotlib backend "pgf": added
25433 INFO:   Matplotlib backend "ps": added
25642 INFO:   Matplotlib backend "svg": added
25850 INFO:   Matplotlib backend "template": added
26088 INFO: Processing hook   hook-matplotlib.py
26212 INFO: Processing hook   hook-xml.dom.domreg.py
26213 INFO: Processing hook   hook-requests.py
26215 INFO: Processing hook   hook-IPython.py
39595 INFO: Processing hook   hook-certifi.py
39596 INFO: Processing hook   hook-pytz.py
39613 INFO: Processing hook   hook-setuptools.py
39615 INFO: Processing hook   hook-xml.sax.py
39615 INFO: Processing hook   hook-xml.etree.cElementTree.py
39615 INFO: Processing hook   hook-babel.py
39635 INFO: Processing hook   hook-patsy.py
39636 INFO: Processing hook   hook-sqlite3.py
39639 INFO: Processing hook   hook-scipy.special._ufuncs.py
39640 INFO: Processing hook   hook-xml.dom.py
39643 INFO: Processing hook   hook-sphinx.py
40753 INFO: Processing hook   hook-idlelib.py
40757 INFO: Processing hook   hook-jinja2.py
40774 INFO: Processing hook   hook-docutils.py
41108 INFO: Processing hook   hook-pygments.py
42514 INFO: checking Tree
42514 INFO: Building Tree because out02-Tree.toc is non existent
42514 INFO: Building Tree out02-Tree.toc
42529 INFO: Looking for ctypes DLLs
42535 WARNING: library rpcrt4.dll required via ctypes not found
42557 WARNING: library user32.dll required via ctypes not found
42557 WARNING: library user32.dll required via ctypes not found
42557 WARNING: library user32.dll required via ctypes not found
42558 WARNING: library user32.dll required via ctypes not found
42558 WARNING: library user32.dll required via ctypes not found
42559 WARNING: library msvcrt.dll required via ctypes not found
42559 WARNING: library msvcrt.dll required via ctypes not found
42559 WARNING: library user32.dll required via ctypes not found
42560 WARNING: library user32.dll required via ctypes not found
42566 WARNING: library shell32.dll required via ctypes not found
42569 WARNING: library shell32.dll required via ctypes not found
42569 INFO: Analyzing run-time hooks ...
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "pandas/lib.pyx", line 1, in init pandas.lib (pandas/lib.c:79755)
  File "/usr/local/lib/python2.7/site-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: lib not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (/private/var/folders/4q/x8_gx_5909q29094m3nvsvgm0000gn/T/pip-iAk4DY-build/sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
43025 INFO: Including run-time hook 'pyi_rth_pkgres.py'
43028 INFO: Including run-time hook 'pyi_rth__tkinter.py'
43031 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
43031 INFO: Including run-time hook 'pyi_rth_mpldata.py'
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "pandas/lib.pyx", line 1, in init pandas.lib (pandas/lib.c:79755)
  File "/usr/local/lib/python2.7/site-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: lib not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (/private/var/folders/4q/x8_gx_5909q29094m3nvsvgm0000gn/T/pip-iAk4DY-build/sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "pandas/lib.pyx", line 1, in init pandas.lib (pandas/lib.c:79755)
  File "/usr/local/lib/python2.7/site-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: lib not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (/private/var/folders/4q/x8_gx_5909q29094m3nvsvgm0000gn/T/pip-iAk4DY-build/sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
43953 INFO: Looking for dynamic libraries
44231 INFO: Looking for eggs
44231 INFO: Using Python library /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Python
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "pandas/lib.pyx", line 1, in init pandas.lib (pandas/lib.c:79755)
  File "/usr/local/lib/python2.7/site-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: lib not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (/private/var/folders/4q/x8_gx_5909q29094m3nvsvgm0000gn/T/pip-iAk4DY-build/sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
44747 INFO: Warnings written to /Users/adammenges/Development/simpleapp/build/app/warnapp.txt
44769 INFO: checking PYZ
44769 INFO: Building PYZ because out00-PYZ.toc is non existent
44769 INFO: Building PYZ (ZlibArchive) /Users/adammenges/Development/simpleapp/build/app/out00-PYZ.pyz
46440 INFO: checking PKG
46440 INFO: Building PKG because out00-PKG.toc is non existent
46440 INFO: Building PKG (CArchive) out00-PKG.pkg
46500 INFO: Bootloader /usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/bootloader/Darwin-64bit/run
46500 INFO: checking EXE
46500 INFO: Building EXE because out00-EXE.toc is non existent
46500 INFO: Building EXE from out00-EXE.toc
46508 INFO: Appending archive to EXE /Users/adammenges/Development/simpleapp/build/app/app
46575 INFO: Fixing EXE for code signing /Users/adammenges/Development/simpleapp/build/app/app
46622 INFO: checking COLLECT
46622 INFO: Building COLLECT because out00-COLLECT.toc is non existent
46622 INFO: Building COLLECT out00-COLLECT.toc
adammenges@Wolfsberg:~/Development/simpleapp|master
⇒  ./dist/app/app
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/nltk/__init__.py", line 129, in <module>
    from nltk.chunk import *
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/nltk/parse/__init__.py", line 79, in <module>
    from nltk.parse.transitionparser import TransitionParser
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/nltk/parse/transitionparser.py", line 21, in <module>
    from sklearn.datasets import load_svmlight_file
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/sklearn/datasets/__init__.py", line 7, in <module>
    from .base import load_diabetes
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/sklearn/datasets/base.py", line 24, in <module>
    from ..utils import check_random_state
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.0.dev8+0f0f63d.mod-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 517, in load_module
    module = imp.load_module(fullname, fp, filename, ext_tuple)
  File "numpy.pxd", line 155, in init sklearn.utils.murmurhash (/private/var/folders/4q/x8_gx_5909q29094m3nvsvgm0000gn/T/pip-iAk4DY-build/sklearn/utils/murmurhash.c:5029)
ValueError: numpy.dtype has the wrong size, try recompiling
app returned -1
```

**Comment by codewarrior0** [comment] 2015-10-02 03:38
```
ValueError: numpy.dtype has the wrong size, try recompiling
```

For what it's worth, I've seen this problem before: I compiled a Cython file against numpy 1.9, and then upgraded to numpy 1.10, then whenever the Cython file is imported it raises this error. So it's a version mismatch of some kind.

Did you try `pyinstaller --clean --force` too?

**Comment by adammenges** [comment] 2015-10-02 17:03
```
adammenges@Wolfsberg:~/Development/simpleapp|master
⇒  pyinstaller --clean --force app.py
Usage: pyinstaller [opts] <scriptname> [ <scriptname> ...] | <specfile>

pyinstaller: error: no such option: --force

adammenges@Wolfsberg:~/Development/simpleapp|master
⇒  pyinstaller --version
3.0.dev8+0f0f63d.mod
```

**Comment by codewarrior0** [comment] 2015-10-02 21:43
My bad, it's just `pyinstaller --clean`. Clean means the same thing as force. I'm wondering if there are stale files in the bincache.

**Comment by adammenges** [comment] 2015-10-07 18:09
Seems to be, I tried with a `rm -rf dist build app.spec` beforehand with the same result.

Did you have any luck with reproducing it?

**Comment by adammenges** [comment] 2015-10-07 18:12
FWIW: If someone needs to install scikit-learn and company, I've found [fonnesbeck/ScipySuperpack](https://github.com/fonnesbeck/ScipySuperpack) to be nice and easy.

**Comment by codewarrior0** [comment] 2015-10-08 02:32
I haven't tried reproducing this yet (and I doubt I'd be able to). Did you also remove `~/Library/Application Support/pyinstaller`? That is another cache folder the `--clean` argument is supposed to remove.

**Comment by jhrf** [comment] 2015-10-30 18:37
Seeing this problem on two separate Mac OSX machines. I've just upgraded PyInstaller to 3.0 from a dev build of 2.1.1. This build was working in the previous version of pyinstaller. 

I have tried using the `pyinstaller --clean` option and deleting ~/Library/Application Support/pyinstaller folder. Neither of these suggestions fixed the problem.

Pyinstaller output pasted below:


27 INFO: PyInstaller: 3.0
27 INFO: Python: 2.7.5
33 INFO: Platform: Darwin-13.4.0-x86_64-i386-64bit
33 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /Users/username01/.testenv/bin/python

1040 INFO: UPX is not available.
1040 INFO: Removing temporary files and cleaning cache in /Users/username01/Library/Application Support/pyinstaller
1061 INFO: Extending PYTHONPATH with /Users/username01/proj/my_package
1061 INFO: checking Analysis
1061 INFO: Building Analysis because out00-Analysis.toc is non existent
1061 INFO: Initializing module dependency graph...
1063 INFO: Initializing module graph hooks...
1064 INFO: Analyzing hidden import 'my_package'
3048 INFO: Processing pre-find module path hook   distutils
3055 INFO: distutils: retargeting to non-venv dir '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils'
8827 INFO: Processing pre-find module path hook   site
8827 INFO: site: retargeting to fake-dir '/Users/username01/.testenv/lib/python2.7/site-packages/PyInstaller/fake-modules'
15564 INFO: Analyzing hidden import 'pysam.TabProxies'
15564 INFO: Analyzing hidden import 'scipy.linalg.cython_blas'
15565 INFO: Analyzing hidden import 'scipy.linalg.cython_lapack'
15565 INFO: Analyzing hidden import 'sklearn.utils.lgamma'
15566 INFO: Analyzing hidden import 'sklearn.neighbors.typedefs'
15566 INFO: Analyzing hidden import 'sklearn.utils.sparsetools._graph_validation'
15571 INFO: Analyzing hidden import 'sklearn.utils.weight_vector'
15572 INFO: running Analysis out00-Analysis.toc
15579 INFO: Analyzing /Users/username01/proj/my_package/my_package/bin/my_package
15603 INFO: Looking for import hooks ...
15606 INFO: Processing hook   hook-distutils.py
15607 INFO: Processing hook   hook-sysconfig.py
15608 INFO: Processing hook   hook-xml.py
15679 INFO: Processing hook   hook-scipy.sparse.csgraph.py
15684 INFO: Processing hook   hook-httplib.py
15684 INFO: Processing hook   hook-pydoc.py
15684 INFO: Excluding import 'Tkinter'
15685 INFO: Processing hook   hook-encodings.py
16205 INFO: Processing hook   hook-_tkinter.py
16213 INFO: checking Tree
16213 INFO: Building Tree because out00-Tree.toc is non existent
16213 INFO: Building Tree out00-Tree.toc
16296 INFO: checking Tree
16296 INFO: Building Tree because out01-Tree.toc is non existent
16296 INFO: Building Tree out01-Tree.toc
16328 INFO: Processing hook   hook-setuptools.py
16330 INFO: Processing hook   hook-xml.sax.py
16331 INFO: Processing hook   hook-scipy.special._ufuncs.py
16383 INFO: checking Tree
16383 INFO: Building Tree because out02-Tree.toc is non existent
16383 INFO: Building Tree out02-Tree.toc
16411 INFO: checking Tree
16411 INFO: Building Tree because out03-Tree.toc is non existent
16412 INFO: Building Tree out03-Tree.toc
16414 INFO: Looking for ctypes DLLs
16433 INFO: Analyzing run-time hooks ...
-c:5: RuntimeWarning: Parent module 'pysam' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
16882 INFO: Including run-time hook 'pyi_rth_pkgres.py'
16887 INFO: Including run-time hook 'pyi_rth__tkinter.py'
-c:5: RuntimeWarning: Parent module 'pysam' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
-c:5: RuntimeWarning: Parent module 'pysam' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
17784 INFO: Looking for dynamic libraries
18422 INFO: Looking for eggs
18422 INFO: Python library not in binary depedencies. Doing additional searching...
18425 INFO: Using Python library /Users/username01/.testenv/bin/../.Python
-c:5: RuntimeWarning: Parent module 'pysam' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
-c:5: RuntimeWarning: Parent module 'sklearn.svm' not found while handling absolute import
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "sklearn/svm/libsvm_sparse.pyx", line 5, in init sklearn.svm.libsvm_sparse (sklearn/svm/libsvm_sparse.c:7612)
SystemError: Parent module 'sklearn' not loaded, cannot perform relative import
18902 INFO: Warnings written to /Users/username01/builds/scipy-test/build/tmpeje5fL/warntmpeje5fL.txt
18911 INFO: checking Tree
18911 INFO: Building Tree because out04-Tree.toc is non existent
18911 INFO: Building Tree out04-Tree.toc
18927 INFO: checking Tree
18927 INFO: Building Tree because out05-Tree.toc is non existent
18927 INFO: Building Tree out05-Tree.toc
18934 INFO: checking PYZ
18934 INFO: Building PYZ because out00-PYZ.toc is non existent
18934 INFO: Building PYZ (ZlibArchive) /Users/username01/builds/scipy-test/build/tmpeje5fL/out00-PYZ.pyz
19565 INFO: checking PKG
19565 INFO: Building PKG because out00-PKG.toc is non existent
19565 INFO: Building PKG (CArchive) out00-PKG.pkg
40281 INFO: Bootloader /Users/username01/.testenv/lib/python2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
40282 INFO: checking EXE
40282 INFO: Building EXE because out00-EXE.toc is non existent
40282 INFO: Building EXE from out00-EXE.toc
40371 INFO: Appending archive to EXE ./my_package
40697 INFO: Fixing EXE for code signing ./my_package

**Comment by adammenges** [comment] 2015-10-30 21:21
@codewarrior0 Yep, `~/Library/Application Support/pyinstaller` was removed too.

**Comment by jhrf** [comment] 2015-10-31 15:27
Using the most recent version of pyinstaller from the developer branch on github fixed the problem for me.

**Comment by adammenges** [comment] 2015-10-31 23:25
Thanks, that's good to know. I'll go try it.

**Comment by htgoebel** [comment] 2015-11-18 22:30
@adammenges Solved`

**Comment by htgoebel** [comment] 2016-01-25 18:36
Got no further info since two month now. Closing.

**Closed by htgoebel** 2016-01-25 18:36 UTC
Labels: need info, OS X, PY2, support
