### ISSUE TITLE
Support hidden import hints

### ISSUE THREAD

**Issue by avylove** [pyinstaller/pyinstaller#4876] opened 2020-05-15 16:11 UTC
**Is your feature request related to a problem? Please describe.**
I maintain a package that loads different modules depending on the environment. Periodically, I receive bug reports about the package not working when using pyinstaller. The root issue is there are modules that are loaded depending on the environment encountered and the user did not include them as hidden imports.

**Describe the solution you'd like**
I would like to be able to specify metadata within the source code that will hint to pyinstaller about hidden imports. Something like:
`# pyinstaller: hiddenimports=jinxed.terminfo.vtwin10,jinxed.terminfo.ansicon`

**Describe alternatives you've considered**
The alternative is to list this in the faq on this project and dependent projects, but that's not really maintainable because people don't usually even know they are using my package because it's a dependency of a dependency.

**Additional context**
Here is an [example](https://stackoverflow.com/questions/59021200/blessed-curses-controls-dont-work-with-pyinstaller-missing-vtwin10). The imports in question are loaded with importlib.

**Comment by Legorooj** [comment] 2020-05-16 00:30
Write a hook. A hook file provides a way to tell PyInstaller what to collect into the final executable.

See https://pyinstaller.rtfd.io/en/latest/hooks.html for details on the hook API, https://pyinstaller-sample-hook.rtfd.io for an example of how to include hooks in a package - make it part of jinxed - so PyInstaller automatically finds them.

If you don't want to include the hooks in jinxed itself, please submit a PR to https://github.com/pyinstaller/pyinstaller-hooks-contrib/ in a few days once I've finished writing the documentation.

**Comment by avylove** [comment] 2020-05-16 01:27
I think you closed this prematurely. The request is for hidden import hints. While you provided an alternative, you haven't implemented the feature requested or given a reason why it shouldn't be implemented.

**Comment by Legorooj** [comment] 2020-05-16 02:48
> The request is for hidden import hints. While you provided an alternative, you haven't implemented the feature requested or given a reason why it shouldn't be implemented.

I'll explain why it shouldn't be implemented:

1. The hook API is stable, and was designed for this and similar problems.
2. Something like a comment to specify hiddenimports is practically impossible without a huge amount of extra code going into pyinstaller. PyInstaller doens't analyze source code; it analyzes compiled bytecode and AST objects, and neither object has comments included; they're stripped from the code. This is a complex enough process without doing dynamic text analysis.

**Comment by avylove** [comment] 2020-05-16 04:22
The AST part makes sense. The documentation and example for the hooks is not very clear. It seems like this requires the user to pass --additional-hooks-dir, which makes that solution not really workable. The example had a __pyinstaller directory, is that checked for hooks?

I want you to consider this from my standpoint and see if you might come up with a better solution. I don't use pyinstaller. The only interest I have in it is that multiple users of my packages have had issues with hidden imports. As a package maintainer, if I have to spend more than a few minutes implementing something, it's probably not worth it to me, but if it's something simple like adding `__pyinstaller_hidden_imports = ['jinxed.terminfo.vtwin10', 'jinxed.terminfo.ansicon']` to the top of an existing file, I'm happy to do that. If I have to learn how pyinstaller hooks work and add new directories and files to my package, I'm much less likely to do it. If the goal is to make it easier on end users, making it easy for package maintainers would go a long way.

**Comment by bjones1** [comment] 2020-05-17 01:01
@avylove, thanks for your comments. This is a great place where a bit of collaboration would help solve the problem easily: as a PyInstaller maintainer, I can provide expertise in how to specify hidden imports. As the package author, you can indicate what those hidden import are and probably provide a basic test script to ensure your package works correctly when frozen. Would you be willing to work on that?

**Comment by Legorooj** [comment] 2020-05-17 01:19
@avylove can I have a list of the imports? I'll write up a diff for you that will provide the hooks. (Or just provide a link to the source code repo and I'll provide a PR)

> The AST part makes sense. The documentation and example for the hooks is not very clear. It seems like this requires the user to pass --additional-hooks-dir, which makes that solution not really workable. The example had a __pyinstaller directory, is that checked for hooks?

The documentation does need cleaning up. The `__pyinstaller` directory is checked for hooks because it is registered via entry points in `setup.py`.

**Comment by avylove** [comment] 2020-05-17 21:47
The source code is here: https://github.com/Rockhopper-Technologies/jinxed

I have been telling people to specify `jinxed.terminfo.vtwin10` and `jinxed.terminfo.ansicon` as hidden imports. That seems to pull in anything those depend on. Alternatively, I suggested if they are using a spec file for pyinstaller, a more future proof option would be to put something like this in their spec file.
```
import pkgutil
import jinxed.terminfo
hiddenimports = [mod.name for mod in pkgutil.iter_modules(jinxed.terminfo.__path__, 'jinxed.terminfo.')
```

As far as a test, something like this would ensure the hidden imports were available

```
import jinxed

jinxed.setupterm('xterm')
assert jinxed._terminal.TERM.terminfo is jinxed.terminfo.xterm
```

**Comment by Legorooj** [comment] 2020-05-18 00:32
@avylove I'll have a play and get back to you.

**Comment by bwoodsend** [comment] 2020-07-23 12:21
@avylove If you're determined to put hidden import hints directly into the code you can put either of the following in instead of a special comment:

```python
if False:
    import jinxed.terminfo.vtwin10, jinxed.terminfo.ansicon
```
Or:
```python
def i_will_never_be_called():
        import jinxed.terminfo.vtwin10, jinxed.terminfo.ansicon
```

**Comment by Legorooj** [comment] 2020-07-23 22:51
Forgot to close this. Hooks for jinxed have been added to contrib.

**Closed by Legorooj** 2020-07-23 22:51 UTC
Labels: feature
