### ISSUE TITLE
packaging TypeError: bindepend.get_python_library_path(sys.executable) returns None 

### ISSUE THREAD

**Issue by bremme** [pyinstaller/pyinstaller#2985] opened 2017-11-09 14:47 UTC
* What is the exact problem?
  * Does the error occur when bundling the application or when running it?
    * **The error does occur during bundling of the application**
* Software versions you are using.
  * **Python version 3.6.2 and 3.6.3 from Miniconda/Anaconda**
  * **Tested both PyInstaller 3.3 from the conda-forge anaconda channel as well as the latest development release**
  * **Tested without any additional packages, except the ones that get installed by `conda install python`**
* What platform and which version you are working on (Windows, Linux, OS X).
  * **The errors occur on a Debian 9.1 system**
* A minimal example program which shows the error. Ideally this is a one-liner :-)

Trying to build even the most basic application fails:

```python
print("Hello PyInstaller")

```

This can be reproduced by:

```shell
$ conda create -n pytest python=3.6.2 pip
$ source activate pytest
$ pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
$ touch main.py
$ echo 'print("hello PyInstaller")' > main.py
$ pyinstaller main.py
```

I looked a bit into the get_python_library_path method. It seems it uses `ldd` somewhere under the hood. Next I had a look at the `ldd` output for different Python versions, 3.6.1, 3.6.2 and 3.6.3. Below the output:

**ldd conda Python 3.6.1**
```shell
$ ldd /home/user/miniconda3/envs/test/bin/python

    linux-vdso.so.1 (0x00007ffdcbb5f000)
    libpython3.6m.so.1.0 => /home/user/miniconda3/envs/test/bin/../lib/libpython3.6m.so.1.0 (0x00007f3ba65b7000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3ba639a000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3ba6196000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f3ba5f93000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3ba5d8b000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3ba5a87000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3ba56e8000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f3ba6abe000)
```

**ldd conda Python 3.6.2**
```shell
$ ldd /home/user/miniconda3/envs/test/bin/python

    linux-vdso.so.1 (0x00007fff2dbf1000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f12788cd000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f127852e000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f127832a000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f1278127000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1277f1f000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1277c1b000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f127903e000)
```

**ldd conda Python 3.6.3**
```shell
$ ldd /home/user/miniconda3/envs/test/bin/python

    linux-vdso.so.1 (0x00007ffccc790000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f63db356000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f63dafb7000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f63dadb3000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f63dabb0000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f63da9a8000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f63da6a4000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f63dbac8000)
```

The line: `libpython3.6m.so.1.0 => /home/user/miniconda3/envs/test/bin/../lib/libpython3.6m.so.1.0 (0x00007f3ba65b7000)` is missing for both 3.6.2 as well as 3.6.3.

Finally I had a look at the content of the `/home/user/miniconda3/envs/test/lib` directory. The content of this directory of both the 3.6.2 as well as the 3.6.3 directory is missing the `libpython3.6m.so.1` link to `libpython3.6m.so.1.0`.

**content of lib directory for 3.6.1**
```shell
$ ls -l libpy*
libpython3.6m.a
libpython3.6m.so -> libpython3.6m.so.1.0
libpython3.6m.so.1 -> libpython3.6m.so.1.0
libpython3.6m.so.1.0
```

**content of lib directory for 3.6.2 and 3.6.3**
```shell
libpython3.6m.so -> libpython3.6m.so.1.0
libpython3.6m.so.1.0
libpython3.so
```

I guess this is essentially a bug in the latest Python versions of Anaconda, but perhaps there is a way to fix this in PyInstaller as well. I have to read a bit more about hooks, but I guess this could be solved by a hook. The only thing that needs to be done is to add the link if its missing:

`ln -s libpython3.6m.so.1.0 libpython3.6m.so.1`

Let me know if there is anything else I can do to help fix this.

For completeness, this is the traceback I got for my complete application:

```shell
20424 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/home/bremme/miniconda3/envs/data-analysis/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+133d18156', 'console_scripts', 'pyinstaller')()
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 95, in <module>
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/building/api.py", line 411, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/building/api.py", line 196, in __init__
    self.__postinit__()
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/site-packages/PyInstaller/building/api.py", line 273, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "/home/bremme/miniconda3/envs/data-analysis/lib/python3.6/posixpath.py", line 144, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
For the minimal example, the traceback was:

```
Traceback (most recent call last):
  File "/home/bremme/miniconda3/envs/pytest/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+133d18156', 'console_scripts', 'pyinstaller')()
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 545, in assemble
    self._check_python_library(self.binaries)
  File "/home/bremme/miniconda3/envs/pytest/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 629, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: libpython3.6m.so.1.0, libpython3.6.so.1.0, libpython3.6mu.so.1.0
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

**Comment by htgoebel** [comment] 2017-11-09 15:46
Thanks for this detailed bug-report.

Indeed `get_python_library_path()` is using `ldd` to find the required pythonlib shared lib. It tried to match it with an entry in `PyInstaller.compat.PYDYLIB_NAMES`.

>The line: libpython3.6m.so.1.0 => /home/user/miniconda3/envs/test/bin/../lib/libpython3.6m.so.1.0 (0x00007f3ba65b7000) is missing for both 3.6.2 as well as 3.6.3.

This means these Python interpreters are statically linked with pythonlib. PyInstaller does not support this (see the manual and #420 ), sorry. 

Adding a symlink would not solve this problem, since PyInstaller relies on the output of `ldd`. So for solving this issue you either need to build conda using a shared library or provide a pull-request for #420.

**Comment by htgoebel** [comment] 2017-11-09 15:46
Duplicate of #420

**Closed by htgoebel** 2017-11-09 15:46 UTC

**Comment by bremme** [comment] 2017-11-09 19:42
Thanks for you fast reply. I tried so many things while figuring out what was going on I probably made a mistake. It's indeed not solved by a simple symlink unfortunately.

From what I've found and understand it has indeed to do with the way Python in de minconda/anaconda distribution is build. I found a couple threads/issues that it's probably the `--enable-shared ` flag. For example this issue on Anaconda seems/might be related: https://github.com/ContinuumIO/anaconda-issues/issues/6401.

I don't know the number, but I guess quite a lot of people use the minconda/anaconda distributions. At this point it sort of means they can't use PyInstaller anymore which is a shame since its probably the best Python packaging tool.

I will look into the issue you mentioned and see if I'm able to come up with a solution.

**update:**

I just had looked into a possible solution, maybe the problem is more complicated then I understand at the moment. But since the libpythonX.Y.m.so.1.0 are actually there, the main problem is finding them. For as far as I can tell they will always be in `../lib/` relative to the python executable location obtained by `sys.executable`. If I add a couple lines of code to `depend.bindepend` at about line 875:

```python
    # Python library NOT found. Resume searching using alternative methods.
    # Applies only to non Windows platforms.
    if is_unix:
        for name in PYDYLIB_NAMES:
            python_libname = findLibrary(name)
            if python_libname:
                return python_libname
        # alternative method for Miniconda/Anaconda installs
        anaconda_lib_path = os.path.abspath(os.path.join(
            os.path.dirname(sys.executable), os.path.pardir, "lib"
        ))
        anaconda_dlls = glob(
            "{}{}libpython*".format(anaconda_lib_path, os.path.sep)
        )

        for filename in anaconda_dlls:
            if os.path.basename(filename) in PYDYLIB_NAMES:
                return filename
```

Would this be a possible solution? Let me know if you want a PR for this option or if we can come up with a better solution.

**Comment by htgoebel** [comment] 2017-11-12 20:34
@bremme Thanks for suggesting a solution. A pull-request is very welcome so we can solve this long-standing issue.

Some remarks for the code already:
- Comment should read something like "Search libpython relative to the executable. Fallback for statically linked executables (e.g. Miniconda/Anaconda installs"
- Use `compat.base_prefix`
- Use same code as for darwin instead of glob?
- Use `os.path.join()` to append the glob-pattern, not `format()`
- Please also test your code in a virtual environment

Thanks

**Comment by bremme** [comment] 2017-11-13 21:27
Thanks for you suggestions. If I understand you correctly you suggest something like this:

```python
    # Python library NOT found. Resume searching using alternative methods.
    # Applies only to non Windows platforms.

    if is_unix:
        # Anaconda places the Python library in the lib directory, so
        # we search this one as well.
        prefix = os.path.join(compat.base_prefix, 'lib')
        for name in PYDYLIB_NAMES:
            python_libname = findLibrary(name)
            if python_libname:
                return python_libname
            # Search libpython relative to prefix
            # Fallback for statically linked executables (e.g. Miniconda/Anaconda)
            full_path = os.path.join(prefix, name)
            if os.path.exists(full_path):
                return full_path

    elif is_darwin:
        # On MacPython, Analysis.assemble is able to find the libpython with
        # no additional help, asking for sys.executable dependencies.
        # However, this fails on system python, because the shared library
        # is not listed as a dependency of the binary (most probably it's
        # opened at runtime using some dlopen trickery).
        # This happens on Mac OS X when Python is compiled as Framework.

        # Python compiled as Framework contains same values in sys.prefix
        # and exec_prefix. That's why we can use just sys.prefix.
        # In virtualenv PyInstaller is not able to find Python library.
        # We need special care for this case.
        # Anaconda places the python library in the lib directory, so
        # we search this one as well.
        prefixes = [compat.base_prefix, os.path.join(compat.base_prefix, 'lib')]
        for prefix in prefixes:
            for name in PYDYLIB_NAMES:
                full_path = os.path.join(prefix, name)
                if os.path.exists(full_path):
                    return full_path
```

Would you prefer to continue the discussion here, or should we discuss this further at a PR?

**Comment by htgoebel** [comment] 2017-11-16 12:15
I'd prefer a Pull-request, since diffs are easier to spot there.

Regarding your proposal: The fallback for statically links should be processed after *all* PYDYLIB_NAMES have been search dynamically.

**Comment by bremme** [comment] 2017-11-16 13:25
Perfect, and your suggestion about PYDYLIB_NAMES makes sense. I will try to make a PR as soon as possible, probably later tonight.

**Comment by htgoebel** [comment] 2018-03-05 21:38
@bemme Pinging :-)

**Comment by bremme** [comment] 2018-03-08 21:23
@htgoebel Sorry that I did not made the pull-request yet. I guess you still want it, I have to put this on my (long) too do list. Have some more github issues to solve, hopefully I will find some time this weekend. If not it is gonna take some more time, since I will be on holiday after next week.

**Comment by bremme** [comment] 2018-03-10 12:44
@htgoebel Sorry that I did not made the pull-request yet. I guess you still want it, I have to put this on my (long) too do list. Have some more github issues to solve, hopefully I will find some time this weekend. If not it is gonna take some more time, since I will be on holiday after next week.

**Comment by htgoebel** [comment] 2018-03-10 17:46
@bremme Of course I still want the pull-request :-)

**Comment by ValentinTrinque** [comment] 2018-06-22 13:51
Any news about this?

**Comment by htgoebel** [comment] 2018-06-26 09:05
ell, one needs to provide a pull-request - or did I miss it?

**Comment by ValentinTrinque** [comment] 2018-06-26 09:08
@htgoebel, no, you're right. @bremme, are you still willing to provide a pull request ?

**Comment by bremme** [comment] 2018-06-26 09:12
I'm sorry. It would be nice if I can still do this I guess. Its just that it will take me a couple hours probably to figure out what is going on. I just have not found that amount of time. You guys know pyinstaller a lot better and can probably fix it in minutes? But if I'm wrong and you still like me to have a look and don't mind if it will take some more time I will have a look at my agenda and see if I can squeeze it in somewhere the coming days.

**Comment by slewt** [comment] 2018-07-11 17:09
PR is submitted - CI integration tests seem very arbitrary and non-consistent - Addition of spaces in a comment cause different results. Don't have time to try and bang head on trying to get the integration tests to work when a comment causes differences, and timeouts on Travis-ci lint tests cause errors.

**Comment by nitrocode** [comment] 2018-07-17 22:41
@slewt Thank you for the PR. From the console output on [appveyor it looks like it failed to import the nspkg package](https://ci.appveyor.com/project/matysek/pyinstaller/build/3463/job/kfw0qqjse0pspu0f#L2343) but your [PR does not even contain that](https://github.com/pyinstaller/pyinstaller/pull/3625/files).

@bremme I noticed that this PR https://github.com/pyinstaller/pyinstaller/pull/3638 also failed both travis and appveyor tests and all it's only updating the README... perhaps something is wrong with the tests?

**Comment by nitrocode** [comment] 2018-07-18 17:54
@slewt Thanks, that makes sense.

@bjones1 ok then that sounds like @slewt's PR is probably good to go then. 😄
