### ISSUE TITLE
start .app fails: LSOpenURLsWithRole() failed with error -10810

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#871] opened 2014-10-18 14:54 UTC
**Original date**: 2014/03/07
**Original reporter**: *j DOT kossick AND gmail DOT  COOM *

Hey, I'm trying to create an .app. After compiling I'm tying to run the .app but I get following error message:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Users/jonathan/path/to/example.app.
```

My Spec file:

```
# -*- mode: python -*-
a = Analysis(['example.py'],
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None
       		 )  
             
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='example',
          debug=False,
          strip=None,
          upx=True,
          console=True )
          
dict_tree # Tree('.', prefix'.')
print dict_tree
          
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               dict_tree,
               strip=None,
               upx=True,
               name='example')
               
app = BUNDLE(coll,
        name=os.path.join('dist', 'example.app'),
        appname="Example App",
        version = '0.1'
        )
```

Is this problem known?

**Comment by matysek** [comment] 2015-09-23 13:00
Closing, don't know how to reproduce it.

**Closed by matysek** 2015-09-23 13:00 UTC
Labels: invalid, v2.1

**Comment by apatrushev** [comment] 2016-10-27 16:15
The problem is really easy to reproduce:
```bash
user@local ~/workspace $ venv/bin/pyinstaller --version
3.3.dev0+b78bfe5
```
spec file created with:
```bash
venv/bin/pyinstaller -n QuteEditor -w main.py
```

main.py
```python
import sys
from PyQt5.QtWidgets import (
    QApplication,
    QMainWindow,
    QPlainTextEdit,
    QVBoxLayout,
    QWidget
)


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.resize(320, 240)
        self.setWindowTitle('Qute Text Editor')
        self.setCentralWidget(QWidget())
        self.centralWidget().setLayout(QVBoxLayout())
        self.editor = QPlainTextEdit(self.centralWidget())
        self.centralWidget().layout().addWidget(self.editor)


def app_main(args):
    app = QApplication(sys.argv)
    win = MainWindow()
    win.show()
    return app.exec_()


if __name__ == '__main__':
    sys.exit(app_main(sys.argv))
```

QuteSpec.spec:
```python
# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['/Users/user/workspace'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='QuteEditor',
          debug=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='QuteEditor')
app = BUNDLE(coll,
             name='QuteEditor.app',
             icon=None,
             bundle_identifier=None)
```

Application started with:
```bash
user@local ~/workspace $ open dist/QuteEditor.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/user/workspace/dist/QuteEditor.app.
```

[editor.zip](https://github.com/pyinstaller/pyinstaller/files/556410/editor.zip)

**Comment by Terrabits** [comment] 2019-03-17 19:02
I'm having the same issue.

@apatrushev,

I know this is old, but any chance you solved this issue and happen to remember how?

**Comment by apatrushev** [comment] 2019-03-17 20:42
> I know this is old, but any chance you solved this issue and happen to remember how?

I customized bootloader at the end.

**Comment by tlambert03** [comment] 2020-01-10 19:21
as of pyinstaller 3.6, I'm also having this problem when running the bundled app:
`LSOpenURLsWithRole() failed with error -10810 for the file...`
pyinstaller 3.4 and 3.5 both worked fine. 
Currently using OSX 10.13.6 (will try again later on more updated systems).  Don't have a minimal working example for you to try at the moment, but will update if I can create one (or try the one above).

**Comment by theguymeyer** [comment] 2020-08-11 18:50
I've been experiencing the same issue when running my bundled application on High Sierra. 

`$ open mainwindow.app/
LSOpenURLsWithRole() failed with error -10810 for the file /Users/<username>/Downloads/mainwindow.app`

When double-clicking the app it crashes immediately (appears and disappears in the dock quickly), same with right-click >> Open.

Using pyinstaller I've built a simple hello world PyQt5 app on MacOS 10.15.5 Catalina. Using pyenv for virtual environments and this command to produce the bundled app..
`python3 -m PyInstaller --onefile --noconfirm --clean mainwindow.spec`

I then codesign with this command...
`codesign -s "Apple Development: Name (Cert Code)" -v dist/mainwindow.app --deep`

**mainwindow.py**:
`# https://pythonprogramminglanguage.com/pyqt5-hello-world/
import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel, QGridLayout, QWidget
from PyQt5.QtCore import QSize    

class HelloWindow(QMainWindow):
    def __init__(self):
        print("hello world")
        QMainWindow.__init__(self)

        self.setMinimumSize(QSize(640, 480))    
        self.setWindowTitle("Hello world - pythonprogramminglanguage.com") 

        centralWidget = QWidget(self)          
        self.setCentralWidget(centralWidget)   

        gridLayout = QGridLayout(self)     
        centralWidget.setLayout(gridLayout)  

        title = QLabel("Hello World from PyQt", self) 
        title.setAlignment(QtCore.Qt.AlignCenter) 
        gridLayout.addWidget(title, 0, 0)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWin = HelloWindow()
    mainWin.show()
    sys.exit( app.exec_() )
`

**mainwindow.spec**:
`# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

import plistlib

with open('./Info.plist', 'rb') as fp:
    pl = plistlib.load(fp)

a = Analysis(['./mainwindow.py'],
             pathex=['.'],
             binaries=[],
             datas=[
                ('./README.md', '.'), 
                ('./res/mac_fireball.jpg', 'res'), 
                ('./res/McSCert_Logo.png', 'res'), 
                ('./res/pixel-heart.icns', 'res')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          [],
          exclude_binaries=True,
          name='mainwindow',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True,
          icon='./res/pixel-heart.icns' )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               name='mainwindow')
app = BUNDLE(coll,
            name='mainwindow.app',
            icon='./res/pixel-heart.icns',
            bundle_identifier='com.guymeyer.mainwindow.ui',
            info_plist=pl)`


Also note that my `pip3 freeze` includes all the necessary libraries for the application. 

I tried following this (https://apple.stackexchange.com/questions/181026/lsopenurlswithrole-failed-with-error-10810-cant-open-install-os-x-yosemite) to troubleshoot by changing permissions with `chmod`, and ensuring that the app and exe names are the same but nothing seems to work. 

If anyone could shed some light on this issue it would be greatly appreciated!

PS. 
found this (https://github.com/pyinstaller/pyinstaller/issues/3418) which indicated that there is no backward compatibility with macOS applications. My next step is to bundle the app in High Sierra and see if it will run in Catalina...

**Comment by jeremysanders** [comment] 2020-11-15 16:40
I had this problem. Trying to run the executable indicated that there was something wrong with the signing of the Python framework. I think MacOS doesn't like embedding a signed Python within a different app.

I fixed the problem by building my own Python from source (using the same version as the one which failed from the python.org website).
