### ISSUE TITLE
ModuleNotFoundError: No module named '_sounddevice_data'

### ISSUE THREAD

**Issue by Doruk-Dilmen** [pyinstaller/pyinstaller#7065] opened 2022-09-04 17:19 UTC
Hi everyone, 

I am using anaconda so, I created the environment and run code which I wrote. Then, in the environment I created exe file using pyinstaller. It's working when I use the environment .There is no problem like below

![tempsnip2](https://user-images.githubusercontent.com/91119666/188325350-aeeea9d7-fba4-4a31-af97-33df417c9038.png)

but in the base this exe doesn't work. Like below
![tempsnip](https://user-images.githubusercontent.com/91119666/188325173-c9586a82-b36c-458b-9c9e-b94b86407907.png)

And I just used the this library in my code
![image](https://user-images.githubusercontent.com/91119666/188325488-235891ea-55b9-4654-a57d-d3657730f886.png)

How can I fix this problem? I tried lots of things but Ican't. Can you help me please?

**Comment by rokm** [comment] 2022-09-04 18:33
Getting `conda` version of `soundfile` with PyInstaller is going to be a bit of hassle:

1) You need to ensure that the `portaudio.dll` is collected. For example, add the following to your PyInstaller command:
```
--add-binary c:\Users\[user-name]\anaconda3\envs\[env-name]\Library\bin\portaudio.dll;.
```
That should collect `portaudio.dll` into application's top-level directory ( `sys._MEIPASS`).

2) You will also need to ensure that in frozen codepath, `sys._MEIPASS` is in `PATH`, because that's what [this `ctypes.util.find_library` call](https://github.com/spatialaudio/python-sounddevice/blob/841e0a1b2ea2367476248e5f0fc6878154949417/sounddevice.py#L67) uses on Windows to search the library. Add something like this at the top of your program (before trying to import `sounddevice`):

```python
# Ensure sys._MEIPASS is in PATH, so ctypes.find_library can search it
import os
import sys
if getattr(sys, 'frozen', False) and sys.platform == 'win32':
    _path = os.environ.get('PATH')
    _path = _path.split(os.pathsep) if _path else []
    _path += [sys._MEIPASS]
    os.environ['PATH'] = os.pathsep.join(_path)
    del _path
```

---

To deal with this on our side:

Our [`sounddevice` hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sounddevice.py) should be extended to collect that DLL automatically when in a conda environment.

We should either start automatically adding `sys._MEIPASS` to `PATH`, or we should override `ctypes.util.find_library` with a version that falls back to searching `sys._MEIPASS` if it cannot find the library on Windows. I'm rather surprised that this is not causing more problems...

**Comment by Doruk-Dilmen** [comment] 2022-09-04 20:10
Hi,

I am trying your suggestion. I added your piece of code but I taked this error

![image](https://user-images.githubusercontent.com/91119666/188331926-ba194458-f0d0-4869-a06c-5ae4e60e921a.png)

Am I missing something?

**Comment by rokm** [comment] 2022-09-04 20:30
> Am I missing something?

Yes, the semi-colon and period after the filename, as per [documentation](https://pyinstaller.org/en/stable/usage.html#cmdoption-add-binary); i.e., `--add-binary c:\Users\doruk\anaconda3\envs\gui_comm\Library\bin\portaudio.dll;.`

**Comment by Doruk-Dilmen** [comment] 2022-09-05 13:43
Hi,

Thanks for help. It's worked.

**Comment by bwoodsend** [comment] 2022-09-05 16:49
> We should either start automatically adding sys._MEIPASS to PATH, or we should override ctypes.util.find_library with a version that falls back to searching sys._MEIPASS if it cannot find the library on Windows. I'm rather surprised that this is not causing more problems...

That's exactly what [this](https://github.com/pyinstaller/pyinstaller/blob/a54d89e161c555837113dc399421f59111b8b654/PyInstaller/loader/pyimod03_ctypes.py#L36-L38) is, right?

---

Given that this is both a pain to fix and Conda only, I'd rather we just closed this as _won't fix_.

**Comment by rokm** [comment] 2022-09-05 17:06
> > We should either start automatically adding sys._MEIPASS to PATH, or we should override ctypes.util.find_library with a version that falls back to searching sys._MEIPASS if it cannot find the library on Windows. I'm rather surprised that this is not causing more problems...
> 
> That's exactly what [this](https://github.com/pyinstaller/pyinstaller/blob/a54d89e161c555837113dc399421f59111b8b654/PyInstaller/loader/pyimod03_ctypes.py#L36-L38) is, right?

Not quite. That is applied only to `ctypes.CDLL` / `ctypes.PyDLL` / `ctypes.WinDLL` / `ctypes.OleDLL` which we do override there, and are therefore capable of picking up stuff in `sys._MEIPASS`. But we do not override `ctypes.util.find_library`, which therefore cannot find DLLs in `sys._MEIPASS`. So this part of the problem is not conda-specific...

**Comment by rokm** [comment] 2022-09-05 17:09
Plus, this is relatively tame compared to some of the things I've been dealing with lately, so I wouldn't mind fixing it once I find some time...

**Comment by rokm** [comment] 2022-09-20 21:19
This should be fixed with next release of `PyInstaller` and next release of `pyinstaller-hooks-contrib`.

**Closed as completed by rokm** 2022-09-20 21:19 UTC
