### ISSUE TITLE
Wrong font configuration for QT5 application on Ubuntu

### ISSUE THREAD

**Issue by Rolf-Hempel** [pyinstaller/pyinstaller#3438] opened 2018-04-02 15:33 UTC
I use PyInstaller to package my Python application into a single directory. On Windows everything works fine. On Ubuntu 16.04 LTS the "dist" directory is built successfully. This is the PyInstaller info at the beginning of processing:
```shell
605 INFO: PyInstaller: 3.3.1
606 INFO: Python: 3.4.5
607 INFO: Platform: Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid
````

I'm using a Miniconda environment with Python 3.4.5. If I start the executable on the computer where I had run PyInstaller, it works correctly. If I move the "dist" directory to a computer with a fresh Ubuntu 16.04 LTS installation and start the executable there, the following error message is printed to StdErr several times:
```shell
Fontconfig error: Cannot load default config file
````
The fonts in the QT5 windows launched by my application are replaced with some standard font. Otherwise the application works correctly. I checked on the web what to do with the error message and found the advice to enter:
```shell
export FONTCONFIG_PATH=/etc/fonts
````
I did this on both computers, but the problem remained. If I run the program (on the second computer) with "strace", the protocol contains the following lines:
```shell
[pid  1960] 16:31:39.388921 access("/home/rolf/miniconda3/envs/P34/etc/fonts/fonts.conf", R_OK) = -1 ENOENT (No such file or directory)
[pid  1960] 16:31:39.389004 write(2, "Fontconfig error: ", 18Fontconfig error: ) = 18
[pid  1960] 16:31:39.389059 write(2, "Cannot load default config file", 31Cannot load default config file) = 31
[pid  1960] 16:31:39.389125 write(2, "\n", 1
) = 1
[pid  1960] 16:31:39.389203 stat("/usr/share/fonts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  1960] 16:31:39.389274 openat(AT_FDCWD, "/usr/share/fonts", O_RDONLY) = 3
````
I noticed that the absolute path "/home/rolf/minoconda..." (from the computer where I ran PyInstaller) is used there. Obviously it does not exist on the computer where I run the application.

After this, there are several protocol blocks like this one:
```shell
[pid  1960] 16:31:39.389511 openat(AT_FDCWD, "/home/rolf/miniconda3/envs/P34/var/cache/fontconfig//3830d5c3ddfd5cd38a049b759396e72e-le64.cache-7", O_RDONLY) = 3
[pid  1960] 16:31:39.389593 fstat(3, {st_mode=S_IFREG|0644, st_size=312, ...}) = 0
[pid  1960] 16:31:39.389681 fstatfs(3, {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=7201768, f_bfree=5197231, f_bavail=4825635, f_files=1839600, f_ffree=1625281, f_fsid={val=[3907222128, 1904321632]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
[pid  1960] 16:31:39.389744 read(3, "\4\374\2\374\7\0\0\0008\1\0\0\0\0\0\0@\0\0\0\0\0\0\0X\0\0\0\0\0\0\0"..., 312) = 312
[pid  1960] 16:31:39.389806 close(3)    = 0
[pid  1960] 16:31:39.389880 stat("/usr/share/fonts/X11", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  1960] 16:31:39.389942 openat(AT_FDCWD, "/usr/share/fonts/X11", O_RDONLY) = 3
[pid  1960] 16:31:39.390005 fstatfs(3, {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=7201768, f_bfree=5197231, f_bavail=4825635, f_files=1839600, f_ffree=1625281, f_fsid={val=[3907222128, 1904321632]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
[pid  1960] 16:31:39.390070 close(3)    = 0
````
I do not understand the details, but it seems to me that the application looks for several fonts, again using the path which does not exist.

Is there any way I can tell PyInstaller not to use the absolute font configuration path? Or is there any other solution to this problem?

Best Regards,
 Rolf

**Comment by Rolf-Hempel** [comment] 2018-04-04 11:58
No idea what caused the problem? I try it once again with a simpler application code.

Meanwhile I could reproduce the problem with a minimal QT5 application. Here is the main Python code:
```
# -*- coding: utf-8 -*-
import sys
from PyQt5 import QtWidgets
from main_window import Ui_MainWindow

class StartQT5(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        print("Gui started")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    myapp = StartQT5()
    myapp.show()
    sys.exit(app.exec_())
```
and this is the generated GUI code (generated py pyuic5) in module "main_window.py":
````
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(269, 144)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 269, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "This is just an example"))

````
That's the whole code.  The main program opens a QT5 main window with just one label in the middle.

This is the .spec file pyinstaller created for this application:
````
# -*- mode: python -*-

block_cipher = None


a = Analysis(['start.py'],
             pathex=['/home/rolf/Pycharm-Projects/Test_Programs_Python3/Start'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='start',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='start')

````
I ran pyinstaller on the Ubuntu 16.04 LTS system where my miniconda environment is available in this location:
````
/home/rolf/minconda3/envs/P34
````
Then I moved the "dist" directory again to the other Linux where I do not have the miniconda environment. It's just a fresh Ubuntu 16.04 LTS. When I start the program, the same error message comes up:
````
Fontconfig error: Cannot load default config file
````
and again the text in the QT5 window has the wrong font. Exactly the same problem as with my larger application code before. Here is a snippet from the strace output:
````
[pid  2138] 12:51:55.972170 access("/home/rolf/miniconda3/envs/P34/etc/fonts/fonts.conf", R_OK) = -1 ENOENT (No such file or directory)

[pid  2138] 12:51:55.972502 write(2, "Fontconfig error: ", 18Fontconfig error: ) = 18

[pid  2138] 12:51:55.972706 write(2, "Cannot load default config file", 31Cannot load default config file) = 31
[pid  2138] 12:51:55.972896 write(2, "\n", 1
) = 1

````
Obviously the program tries to access the fonts at the location where they were stored on the other system.

How can I resolve the issue? Can I package the fonts with the application? I spent hours reading the pyinstaller docu to find how I coulld do it, but was not successful.

Any help would be very much appreciated!

Best Regards,
 Rolf

**Comment by bjones1** [comment] 2018-04-04 15:04
I don't do anything explicitly about PyQt5 fonts, but #3439 might help via improved packaging of PyQt5.

**Comment by Rolf-Hempel** [comment] 2018-04-04 19:00
Hi Bryan,

I checked [#3439](https://github.com/pyinstaller/pyinstaller/pull/3439) but I do not know exactly what I can do with it. I ran the above example with the latest development version (PyInstaller-3.4.dev0+956066103), but the result is the same.

Is there any other version I can test to see if the problem is resolved somewhere?

Best Regards,
 Rolf

**Comment by bjones1** [comment] 2018-04-04 21:52
I expect this PR to be merged soon -- just wait for that, then see if it helps.

**Comment by jxltom** [comment] 2018-04-09 02:33
It happens to me with pyqt4 and conda's python version 3.4-3.6

**Comment by Rolf-Hempel** [comment] 2018-06-09 14:11
After several months today I tried if the problem still persists. I updated PyInstaller to the latest development version (3.4.dev0+dc49e4a31) and re-ran the test with the minimal Python 3.4/QT5 code listed above. The result was the same as two months ago. Since the example code is really minimal, I claim that this problem must occur with any application code.

I can't believe that nobody else is using Python 3.4 with QT5 on Linux. Is there any chance that the problem can be fixed?

**Comment by tallforasmurf** [comment] 2018-06-09 19:05
duckduckgo of the string `+Fontconfig error Cannot load default config file` turns up many, many hits all centering on not finding `/etc/fonts/fonts.conf` or perhaps not looking for it.

Just for intellectual curiosity, does that file exist on your source and on your target systems?

However, the issue appears to be that instead of looking for the font config in that standard location, your copy of Qt is looking for one local to your dev user id, at `/home/rolf/miniconda3/envs/P34/etc/fonts/fonts.conf`.

This path would not be set up by PyInstaller, which knows nothing about fonts. I suspect it must be baked into some module of Qt, probably QWidgets. That sort of dependency embedding might happen if you built a Qt installation by downloading the Qt installer and doing the whole Qt build and install process.

It would probably not happen if you just installed the PyQt5 wheel, which brings along its own copies of the Qt dlls and does not require the presence of a Qt install.

**Comment by bjones1** [comment] 2018-06-09 19:46
I agree with @tallforasmurf. I've seen packaging issues in Anaconda's PyQt5, so I also suspect that miniconda's PyQt5 package is broken in some way. @Siecje has been running Python 3.4 + PyQt5 on Linux, as I recall; perhaps he could comment. If possible, upgrade to Python 3.5 and install from the official PyQt5 wheel.

**Comment by Rolf-Hempel** [comment] 2018-06-09 19:48
The file /etc/fonts/fonts.conf is present in both the source and target systems.

How do I find out if the absolute path to the miniconda font location is "baked" into some QT module? And more important: How can I avoid that?

I certainly did nothing special in setting up pyqt and QT5. They were installed using miniconda. Version numbers are 5.6.0 for pyqt and 5.6.2 for qt.

Any idea?

**Comment by bjones1** [comment] 2018-06-09 19:54
As a quick sanity check, can you install Python 3.5, pip install PyQt5 (NOT the Anaconda flavor) and re-test? If that works, then Miniconda's PyQt5 is mostly likely the culprit. I don't know how font paths are baked, but there seems to be a lot of hits in Googling for it.

**Comment by bjones1** [comment] 2018-06-09 19:59
Also, what does Python 3.4 report from

``` Python
from PyQt5.QtCore import QLibraryInfo
print(QLibraryInfo.location(QLibraryInfo.LibrariesPath))
```

This is the "baked" path for fonts, I think.

**Comment by Rolf-Hempel** [comment] 2018-06-09 20:12
Hi Bryan,

I ran the test you suggested:

>>> from PyQt5.QtCore import QLibraryInfo
>>> print(QLibraryInfo.location(QLibraryInfo.LibrariesPath))
/home/rolf/miniconda3/envs/P34/lib
 
So, it seems the absolute path is indeed baked into the module.

Is it necessary to start with a fresh Python environment, or would it be sufficient to replace the pyqt / qt5 stuff? To get my application running I had been struggling for quite a while with many libraries, until everything worked without internal conflicts. As far as I remember, some libraries needed Python 3.4.

**Comment by bjones1** [comment] 2018-06-09 20:19
More importantly, does this path change in a frozen version? If not, your paths are baked. This is typical for Conda -- I wish someone would fix it, since it keeps showing up with confused PyInstaller users.

**Comment by tallforasmurf** [comment] 2018-06-09 21:47
> What do you mean with "change in a frozen version"?

Add the QLibraryInfo() call and printout to your minimal example. I *think* it can go right at the start before creating the QApplication. (If not, just after that.) Bundle the app, test the bundled app on the source and then on the failing destination machine.

**Comment by bjones1** [comment] 2018-06-10 03:14
@Rolf-Hempel, that's a good test and what I had in mind -- verifying that the "baked" path appears on another machine. The pip-installed version is much better...but it (or at least, its dependency sip) requires Python 3.5.

An alternative: I think that by adding the correct `qt.conf` to Miniconda (and to the resulting `dist/` directory of your application), you might be able to fix this. Even better, if your fix was included in Anaconda/miniconda's PyQt5 package, you'd solve the problems for many others.

On Windows, the `qt.conf` is located in `PyQt5/Qt/bin` with contents of

```
[Paths]
Prefix = ..
```

I don't have a Linux PC handy to look at, but I'd expect something similar.

**Comment by Rolf-Hempel** [comment] 2018-06-10 08:09
I didn't know which info to print out with QLibraryInfo(), so I printed several entries:

LibrariesPath: /home/rolf/miniconda3/envs/P34/lib
BinariesPath: /home/rolf/miniconda3/envs/P34/bin
DataPath: /home/rolf/miniconda3/envs/P34
ImportsPath: /home/rolf/miniconda3/envs/P34/imports
SettingsPath: /home/rolf/miniconda3/envs/P34/etc/xdg

On both the source and target systems the paths came out the same. I don't know if this info helps.

I will now try to install pyqt with pip in an Anaconda 3.6 environment. I hope that the qt paths will not be hardwired.

**Comment by Rolf-Hempel** [comment] 2018-06-10 15:34
Today I started with a fresh Python 3.5 installation (without using Anaconda). I installed pyqt and processed the simple application with pyinstaller. It worked! There were no font problems, neither on the source system, nor on the target. So, you were right in assuming this was an Anaconda issue.

The hard work was installing all other libraries again for my real application. I still struggle with a library, but this is not a PyInstalller issue. Everything else seems to work properly also for the large application code. Very nice!

So, I will close this issue now. Many thanks for your good suggestions!

**Comment by joe-habel** [comment] 2019-05-22 04:13
I hate to stir up an almost year old issue, but I ran into this same issue today, and while this behavior looks to be fixed in the latest pyinstaller with PyQt5, this was the first thread that came up when I searched the error, so I figured I'd share what I learned.

I'm sitting on a legacy PyQt4 with Python 2.7 installation via Anaconda, that gave me the same Fontconfig error. I was able to get rid of this error by placing 

```
import os
os.environ['FONTCONFIG_FILE'] = 'etc/fonts/font.conf'
os.environ['FONTCONFIG_PATH'] = 'etc/fonts/'
```

above any other calls in my PyQt GUI script.

However, @bjones1 pointed out that conda packaged PyQts have "baked" in paths. This was the first place I went looking to clear up this issue, and while it didn't fix it, clearing up these baked in Anaconda paths, did take care of a styling issue I was having with the QSplitter Widget in PyQt not styling well when changing host machines.

Turns out, changing any Anaconda qt.conf, baking in a qt.conf into the resource file, or leaving a qt.conf in the dist directory doesn't seem to work with getting rid of these baked in paths (at least with PyQt4). With PyQt4, the paths are baked in directly into the libQtCore.so files, and from my experience, didn't even match the qt.conf files generated by Anaconda upon install. 

If you are looking for a way to change the Qt Library paths without having to completely scrap the convenience of Anaconda, I was able to find a work-around.

First, I built PyQt4 from source outside of Anaconda.

Second, I dumped all the Library paths from this installation of PyQt4:

```
from PyQt4.QtCore import QLibraryInfo

def dumpCorrectQtPaths():
    qPath = QLibraryInfo.location
    with open('qtPaths.txt', 'w') as paths:
        paths.write('[Paths]\n')
        paths.write('Prefix = %s\n'%str(qPath(QLibraryInfo.PrefixPath)))
        paths.write('Binaries = %s\n'%str(qPath(QLibraryInfo.BinariesPath)))
        paths.write('Libraries = %s\n'%str(qPath(QLibraryInfo.LibrariesPath)))
        paths.write('Headers = %s\n'%str(qPath(QLibraryInfo.HeadersPath)))
        paths.write('Plugins = %s\n'%str(qPath(QLibraryInfo.PluginsPath)))
        paths.write('Imports = %s\n'%str(qPath(QLibraryInfo.ImportsPath)))
        paths.write('Data = %s\n'%str(qPath(QLibraryInfo.DataPath)))
        paths.write('Translations = %s\n'%str(qPath(QLibraryInfo.TranslationsPath)))
        paths.write('Settings = %s\n'%str(qPath(QLibraryInfo.SettingsPath)))
        paths.write('Examples = %s\n'%str(qPath(QLibraryInfo.ExamplesPath)))
        paths.write('Demos = %s\n'%str(qPath(QLibraryInfo.DemosPath)))
        paths.write('Documentation = %s\n'%str(qPath(QLibraryInfo.DocumentationPath)))

dumpCorrectQtPaths()
```

Then, what I did, is I ran pyinstaller as I would, but I intercepted the Anaconda built QtCore library in the dist directory. If you do want to try doing this, I highly recommend you only try this on the .so file in your dist directory, and not in your Anaconda installation.

```
def fixCondaBinary(condaBinary, qtPathDump):

    binaryName = {'Headers' : 'qt_hdrspath',
                  'Libraries' : 'qt_libspath',
                  'Prefix' : 'qt_prfxpath',
                  'Documentation' : 'qt_docspath',
                  'Binaries' : 'qt_binspath',
                  'Plugins' : 'qt_plugpath',
                  'Imports' : 'qt_impspath',
                  'Data' : 'qt_datapath',
                  'Translations' : 'qt_trnspath',
                  'Examples' : 'qt_xmplpath',
                  'Demos' : 'qt_demopath'}

    with open(condaBinary, 'rb') as f:
        data = f.read()
    data_arr = list(data)
    desired_paths = readQtPathDump(qtPathDump)

    for name, bin_name in binaryName.iteritems():
        path = bytes(bin_name)
        pos = data.find(path)
        eq = pos + len(bin_name)
        i = 1
        new_path = desired_paths[name]
        while data_arr[eq + i] != '\x00':
            data_arr[eq + i] = '\x00'
            i += 1
        data_arr[eq+1 : eq + 1 + len(new_path)] = new_path
    with open(condaBinary, 'wb') as f:
        f.write(''.join(data_arr))

def readQtPathDump(qtPathDump):
    paths = ['Prefix', 'Binaries', 'Libraries', 'Headers', 'Plugins', 'Imports', 'Data', 'Translations',
             'Settings' , 'Examples', 'Demos', 'Documentation']

    desired_paths = {}
    with open(qtPathDump, 'r') as f:
        paths_str = f.readlines()

    for i, line in enumerate(paths_str[1:]):
        eq = line.find('=')
        desired_paths[paths[i]] = line[eq+1:].strip()

    return desired_paths

fixCondaBinary('dist/libQtCore.so', 'qtPaths.txt')
```
From there, taking a peek at my paths after frozen, they were now pointing to the paths specified in 'qtPaths.txt'.

I'm sure this could be extended to dynamically reference the proper qt paths, but right now, I was able to at least point it to the default installation directory.

**Comment by bpteague** [comment] 2021-01-12 05:17
I've been bitten by this as well -- it's a `fontconfig` problem, not a `PyQt5` problem, when using Anaconda. The issue is that Anaconda actually updates their version of the `fontconfig.so` library to point at Anaconda's fonts, not the system fonts -- and then `PyInstaller` pulls in the Anaconda `fontconfig` library, but not the fonts -- and even if you packaged the fonts, the packaged `fontconfig` library doesn't look in the right directory.

You can verify that this is the case by specifying BOTH the `FONTCONFIG_FILE` and `FONTCONFIG_PATH` environment variables when launching your one-click binary:
```
FONTCONFIG_PATH=/etc/fonts FONTCONFIG_FILE=/etc/fonts/fonts.conf $BINARY
```
(replacing `$BINARY` with the name of your one-click binary, obviously.) This should use the system fonts.

Here's the workaround I came up with -- remove the `fontconfig` and `libuuid` libraries from the one-click, which makes it go looking for the system version instead. In my `.spec` file, between `a = Analysis(....)` and `pyz = PYZ(....)`, add the following:
```python
remove_strs = ["fontconfig", "libuuid"]

lol = [ [x for x in a.binaries if x[0].find(y) >= 0] for y in remove_strs]
remove_items = [item for sublist in lol for item in sublist]
a.binaries -= remove_items
```

**Comment by bwoodsend** [comment] 2021-01-12 18:27
@bpteague I take it then that you'd rather remove fontconfig and rely on system fonts than include Anaconda's fonts? I certainly would if it were me.

**Comment by bpteague** [comment] 2021-01-12 19:20
Hi @bwoodsend! I'm not sure this bug needs to be re-opened -- I more wanted to document the issue in more detail and include a workaround.

And I was wrong above -- sorry, it was late! -- what the Anaconda-shipped version of `fontconfig` does is go looking for that environment's *configuration*, the stuff that's usually in `/etc/fonts` but is instead in `$CONDA_PREFIX/etc/fonts`. Anaconda doesn't actually ship fonts -- you're right, that would be silly.

The reason Anaconda's `fontconfig` behaves like this is because of the way that Anaconda handles binary reloaction: it builds binaries with a "dummy" prefix at build time, then does a search-and-replace on binary files when the package is installed in a particular prefix. (More details at https://docs.conda.io/projects/conda-build/en/latest/resources/make-relocatable.html and https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#binary-relocation). So, when you install the `qt` Anaconda package, it depends on `fontconfig`, which gets updated to look for its configuration files in `$CONDA_PREFIX`.

I'm not sure what the best way forward is here. Re-patching `fontconfig` is out, because we don't know `_MEIPASS` until runtime. Perhaps patch `utils.hooks.qt.add_qt5_dependencies` to exclude `fontconfig` from `imports` if it shows up (and we're building for Linux)? Can we depend on all modern Linux machines to have a compatible `fontconfig`?

Another reason to hesitate is because "fix PyInstaller it so it works with Anaconda" is a maddening path, and we may not want to set that precedent.

One final thought -- Anaconda's packages actually track which files were updated. It might make sense to consider asking "are we building with Anaconda? If so, which files might not be relocatable?" and warning the user about them.

Thoughts?

**Comment by bpteague** [comment] 2021-01-12 20:15
....I just saw faee2a99deae6c9f8e1e67606a5f43af974e3fd4 (: Seems like there's some infrastructure to build on if we want to take the "find possibly non-reloacatable files and warn about them" path.

**Comment by bwoodsend** [comment] 2021-01-13 13:06
> Another reason to hesitate is because "fix PyInstaller it so it works with Anaconda" is a maddening path, and we may not want to set that precedent.

No, I agree. I'm happy to have this Conda issue open but I certainly wouldn't go out of my way to fix it. 

> Can we depend on all modern Linux machines to have a compatible fontconfig?

It's not present on the manylinux1 or manylinux2014 docker images, which are designed to be a lowest common denominator of Linux distributions, so presumably something somewhere doesn't have it. I'm not sure how good an indicator this is though. 

> what the Anaconda-shipped version of fontconfig does is go looking for that environment's *configuration*

So, if I understand correctly, there is a configuration file we could copy and put where it's expected to be? And this could be generalised to anything in Conda's list of path-patched files?

**Comment by bpteague** [comment] 2021-01-13 18:31
> > Can we depend on all modern Linux machines to have a compatible fontconfig?
> 
> It's not present on the manylinux1 or manylinux2014 docker images, which are designed to be a lowest common denominator of Linux distributions, so presumably something somewhere doesn't have it. I'm not sure how good an indicator this is though.

I've not used Docker. I would only expect to find `fontconfig` on machines that are running X11 (fine, or Wayland) -- client machines with graphical displays. For sure, these are the systems that programs that use Qt are meant to run on.

> 
> > what the Anaconda-shipped version of fontconfig does is go looking for that environment's _configuration_
> 
> So, if I understand correctly, there is a configuration file we could copy and put where it's expected to be? And this could be generalised to anything in Conda's list of path-patched files?

No, unfortunately just collecting and distributing the configuration file won't work. If I have an Anaconda environment in `/home/brian/test_environment`, then when `fontconfig.so` is installed in that environment it is patched to look for its configuration in `/home/brian/test_environment/etc/fonts`. If you send that `fontconfig.so` file to anyone else, it still goes looking for its configuration in `/home/brian/test_environment/fonts`, which obviously doesn't exist on their machine!

Sometimes that's okay -- for example, the Qt libraries are similarly patched, but you can override the paths that Qt looks for its resources with a `qt.conf` file (this is what I do in my project, generating a `qt.conf` file at runtime with a runtime hook). Similarly, you can override `fontconfig`'s behavior with the `FONTCONFIG_PATH` and `FONTCONFIG_FILE` environment variables. I suppose you might even be able to collect the configuration files with a build hook, then set those environment variables with a runtime hook. Again, maybe not something I would want to add to `PyInstaller` and then commit to maintaining...

A generalized Anaconda-wide approach would probably be something like:
- Realize that we're running in an Anaconda environment
- Inspect the packages to see which files were patched (they're recorded in package metadata)
- Figure out what the patched string was
- Record the patched files (and perhaps the location of the patched locations)
- Re-patch them *at runtime* because you don't know at build-time what their eventual directory will be.

I am not signing up to implement that, especially the last part (;

**Comment by bpteague** [comment] 2021-01-13 18:33
(If you have the power to do so, you might consider renaming this issue -- or you/I/we could open another one about relocating Anaconda's patched files and take the conversation there.)

**Comment by bwoodsend** [comment] 2021-01-13 19:04
Yeah, open a new one would be better.

**Closed by bwoodsend** 2021-01-13 19:04 UTC
Labels: area:hooks/PyQt5, bug, platform:conda

**Comment by enji-ahn** [comment] 2021-07-20 07:27
> Here's the workaround I came up with -- remove the `fontconfig` and `libuuid` libraries from the one-click, which makes it go looking for the system version instead. In my `.spec` file, between `a = Analysis(....)` and `pyz = PYZ(....)`, add the following:
> 
> ```python
> remove_strs = ["libfontconfig", "libuuid"]
> 
> lol = [ [x for x in a.binaries if x[0].find(y) >= 0] for y in remove_strs]
> remove_items = [item for sublist in lol for item in sublist]
> a.binaries -= remove_items
> ```

In my case. above code not work properly. (I don't know why and how to debug either.)
So, I rewrite code my own (logic is same)

```py
import os

a = Analysis(...)

a.binaries = [x for x in a.binaries if not os.path.basename(x[1]).startswith(("libfontconfig", "libuuid"))]

pyz = PYZ(...)
```
