### ISSUE TITLE
When executing an application bundled with PyInstaller on Windows, subprocess DLL load order is altered to include the PyInstaller'd application directory before %SystemRoot%

### ISSUE THREAD

**Issue by matthchr** [pyinstaller/pyinstaller#3795] opened 2018-10-10 00:55 UTC
PyInstaller version: 3.4
Operating system(s): Tested on Win2012R2 and Win2016

### Quick summary
It looks like PyInstaller uses an [activation context](https://docs.microsoft.com/en-us/windows/desktop/sbscs/activation-contexts) on Windows. Activation contexts _seem_ to be inherited by sub-processes by default, which ends up changing the sub-process assembly load order, which can possibly break the sub-process (depending on what the sub-process expects).

#### my_subprocess.exe
is a native executable which has a dependency on some native `dlls` (it's not really important which ones but mine was VRUNTIME140D.DLL)

The executable doesn't really have to do anything other than force a load of a native assembly so that we can watch the load order. As a matter of fact you could use `notepad.exe` here I think.

#### Launcher.py
This is a simple python script which launches a subprocess. Something like this
```
import subprocess

path = r'my_subprocess\my_subprocess.exe'
subprocess.run(path, cwd='my_subprocess')
```

#### ProcMon
I used [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) set to watch `my_subprocess.exe` to view how the sub-process executable was loading assemblies.

First, if you run the `launcher` application without bundling with PyInstaller while procmon is running you'll observe that it loads assemblies as described in the [standard Windows DLL discovery process](https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications), which basically boils down to*:
1. The directory the sub-process is in
2. Various Windows directories (`%SystemRoot%` and some others) 
3. The directories that are listed in the `PATH` environment variable

If you then bundle the `launcher` application with PyInstaller and run it again, while procmon is running, you'll observe that now the load order is different and now looks like*:
1. The directory the sub-process is in
2. **The directory of the `launcher`**
3. Various Windows directories (`%SystemRoot%` and some others) 
4. The directories that are listed in the `PATH` environment variable

*Note in both of the above examples you might not see the full set of paths used because once the assembly has been found it stops looking further.

It's likely that this inheritance is "intended" by Windows -- but it seems somewhat awkward for PyInstaller'ed applications because it assumes that every process launched by the PyInstaller application wants the PyInstaller SxS view of the world and not the standard picture on that machine. _Most of the time_ things seem to work even though the assembly load order is different, but that's not a guarantee and I've see things break due to it.

I guess my questions are:
1. Is there a way to configure PyInstaller to not have its activation context inherited by sub-processes?
2. Is there a way in code before spawning a sub-process to say "Hey don't use the activation context of the current process because it doesn't apply to you?" For example using the win32 [activation context API](https://docs.microsoft.com/en-us/windows/desktop/sbscs/activation-context-reference)?
3. Is the fact that the DLL assembly load order is different something that "shouldn't matter"? it seems like it does given that PyInstaller bundles various operating system files such as the `api-ms-win-core` files, which I thought varied by Windows version.

My net end goal is for processes spawned by my PyInstaller'ed application to be spawned "normally" - but given all of the above it's not clear how to actually achieve that.

**Comment by bjones1** [comment] 2018-10-10 15:51
Is the approach a bad thing? I would think that PyInstaller should create an executable that prefers binaries from the launcher directory, to keep odd things from happening. For example, if the packaged executable relies on `foo.dll`, the current approach would first look for this in the PyInstaller base directory; otherwise, a `foo.dll` from some other application would be loaded, causing your program to crash.

**Comment by matthchr** [comment] 2018-10-10 15:55
For the PyInstallered application the approach of course makes sense.

The issue is that the application being launched as a subprocess is not necessarily a PyInstaller'ed app. And changing the sub-process applications DLL discovery order can break non-pyinstallered applications, as they may be expecting to find the system version of `foo.dll` and not the one that the PyInstaller'ed application bundled with itself.

**Comment by matthchr** [comment] 2018-10-10 19:56
For the sake of my education, do you have an understanding of why PyInstaller needs to be a SxS application with a manifest + activation context?

The activation context obviously adds some directories to the path, but at least in my applications case, the directory added to the path is the same directory as [the directory from which the application was loaded](https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications) which according to Windows is always searched first anyway. So at least in my applications use-case I'm pretty sure this extra path is getting me nothing since it's already the first directory checked.

_But_ I assume there are some use-cases where it is useful - do you by chance know what those are?

**Comment by bjones1** [comment] 2018-10-11 14:48
Unfortunately, no. I don't remember the history, and I wasn't involved in its development. I know it was discussed in various issues and PRs, but don't remember which ones. Sorry I can't be more helpful.

**Comment by matthchr** [comment] 2018-10-18 20:50
I finally was able to figure out how to work around this. It turns out that Python itself already unloads/caches the activation context and only uses it when it is going to discover native assemblies (you can see that [here](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Python/dynload_win.c#L216)). That means that you cannot use the win32 activation context APIs in your application to unset the context (as it's already been unset). But that's okay because actually that's not the real root cause of the issue.

The real issue is that the activation context set the `DllDirectory` for the process, and it turns out that the `DllDirectory` is [inherited by subprocesses](https://pretentiousname.com/setdlldirectory_inheritance/index.html) (Note I can't actually find concrete official documentation that says this is inherited, but it definitely is).

The fix to clear the existing `DllDirectory` using the `SetDllDirectory` win32 API after your application starts.
You can do this using PyWin32:
```
win32api.SetDllDirectory(None)
```

**With that said**, the more I dug into this the more I became convinced that PyInstaller doesn't need to be doing any of this activation context/DllDirectory stuff on Windows. As long as your application is being run from the same directory as all of its dependencies everything should work without a custom DllDirectory, and it seems to me to cause more trouble than it's worth for as far as I can tell no benefit...

**Comment by bjones1** [comment] 2018-10-18 21:49
According to 6c1a02c7a3aafd925c3831c3e45688aeeabe6159, "Windows: Add extraction folder to DLL search path

This solves a problem where custom ctypes DLLs included into a onefile build cannot be found because they are loaded with a bare filename."

Thoughts/comments?

**Comment by matthchr** [comment] 2018-10-20 01:33
Nice to see the actual code in question -- it looks like my whole activation context investigation was wrong -- PyInstaller just calls `SetDllDirectory` directly (as per the change you linked).

I *think* I see why you're doing this, correct me if I'm wrong.

In onefile mode, the PyInstaller bootloader first must extract all of the required files to a temporary directory, it does so and then launches itself again (as a subprocess). Doing this it is still running from its original location (the bootloader file itself has not moved). In this scenario what you end up with is the "users code" running entirely outside of the directory with their dependencies, in which case yes, loads won't find anything they want.

Given that calling `SetDllDirectory` pollutes all child processes though (not just the one you're running) I'm not sure that it's the best option available to you... I see a few alternatives (you can let me know what you think):

1. Copy the bootloader into the extracted folder and run it from there when it's a subprocesses. Depending on how big the bootloader is this may or may not be a bad idea.
2. Set the current working directory of the bootloader-subprocess to be the temp directory. If `SafeDllSearchMode` is disabled that's checked second (after the application dir). If `SafeDllSearchMode` is enabled it's checked 5th (after various windows directories). (See [here](https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order) for more details). I am actually pretty surprised you're not doing this already -- can't users package non-binary content into application? And if they do doesn't that content get dropped in the temp folder and not beside the OneFile bootloader? If so then today how do they know where they can find that non-binary data? (It seems like it's in a temp directory which their application has no idea where it is?) I see that when you call `CreateProcessW` you pass `NULL` for the `lpCurrentDirectory` -- it probably makes more sense for that to be the temp dir? The only real risk here is if you're looking for a binary that's actually in system32 (or another system directory that's searched early), you'll still discover it there first rather than in the temp dir since the temp dir won;t be searched till 5th when `SafeDllSearchMode` is enabled.
3. Edit the bootloader-subprocess PATH to include the extracted folder. This I think achieves much the same thing -- the only risk here would be that PATH loads happen _after_ looking in System32, etc, which may or may not be a problem
4. Only perform the `SetDllDirectory` shenanigans in OneFile mode. If you're not in OneFile you definitely don't need `SetDllDirectory` and then you wouldn't be polluting subprocesses either (at least in that mode).

At the very least item 4 above seems safe. I am also pretty sure that item 2 is a good idea as well... but maybe I am just missing where you already do something which accomplishes that but in a different way).

**Comment by bjones1** [comment] 2018-10-20 03:08
Since this isn't my code, I can only guess that your assumptions are correct. I'm certainly open to a PR, **but** I'd like to ensure it doesn't break something. In particular, would you:

1. Identify a failing case when the bootloader call to `SetDllDirectory` is removed (perhaps the current test suite would fail? It's worth a try.)
2. Provide a PR that fixes this and also includes a test of a call to subprocess that fails without your changes.

Feedback on your ideas:

1. In one-file mode, the bootloader is the whole file, so the copy is expensive.
2. This would probably cause unexpected side-effects. `my_app data.txt` would now fail, since `data.txt` is no longer in the current directory.
3. Sound hard to implement, since you need to ensure all the Python extensions/DLL loads/etc. also see this.
4. This makes the most sense to me.

**Comment by matthchr** [comment] 2018-10-20 05:31
> This would probably cause unexpected side-effects. my_app data.txt would now fail, since data.txt is no longer in the current directory.

Ah, that's a good point. But for folks who bundled non-binary files with their application (i.e. `data` in the spec file), aren't they dumped into some random and "unknown" directory (since they're actually in the exe and then extracted to the tmpdir?) How do customers find those files currently (since presumably those files folks would also expect to be able to do: `my_app my_bundled_data.txt` on too)?

As for a PR -- doing item 4 shouldn't be that hard, but it might take me a bit to come up with a good set of test cases (the one I have is pretty convoluted/complicated)

**Comment by bjones1** [comment] 2018-12-27 04:10
@zehome, would you mind adding a sub-heading to https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess and documenting this, along with your workaround? This is important for Windows developers. Please point back to this issue so an interested reader can learn more.

**Comment by zehome** [comment] 2018-12-27 09:54
@bjones1 done, thanks for pointing to to the wiki

**Comment by bjones1** [comment] 2018-12-27 14:21
Thanks! I'm closing this for now, but would welcome a PR with the fix mentioned in this issue.

**Closed by bjones1** 2018-12-27 14:21 UTC
Labels: Windows

**Comment by almarklein** [comment] 2019-03-27 10:30
Hi, I've just spend about six hours digging into a problem caused by PyInstaller setting `DllDirectory` until I finally stumbled into this issue. @zehome's solution fixed it for me.

The use-case: I'm the author of the [Pyzo IDE](https://github.com/pyzo/pyzo), which is build with Qt. Recently we switched to PyInstaller (we'd been using cx_freeze for years). Being an IDE, Pyzo spawns subprocesses: the kernels that run the user's code. These subprocesses can also integrate with gui toolkits (e.g. PyQT5) to e.g. show interactive figures. However, in the latest release (build with PyInstaller) the integration with all the Qt-based libs failed on some systems, killing the kernel process. I was able to narrow down that even though the correct PyQt5 library was being loaded, it was loading the QT dll's from the frozen Pyzo application (how weird is that!). So, next, I did all I could to not leak any info about the application location to the subprocess. I checked all environment variables, made sure the subprocess was started elsewhere, etc. Yet still, the kernel was loading Pyzo's Qt dll's and not the proper one's  installed on the users system. So now I know why; I would never have found out if not for this thread.

I comfort myself that I've learned something new today, but `DllDirectory` being an unknown feature, and knowing the pain it can cause, I would be in favor of removing its use if possible ...

**Comment by bjones1** [comment] 2019-03-27 13:31
Ouch. That is painful. I can't think of a workaround that satisfies all use cases, however: either (a) subprocesses won't work as expected when loading DLLs or (b) ctypes DLLs won't work as expected. I don't know how to achieve both without sacrificing one or the other. Currently, Pyinstaller selects (a) by default.

**Comment by almarklein** [comment] 2019-03-27 13:44
At least the fix is simple once you know it :P

**Comment by Sup3rGeo** [comment] 2019-10-12 20:05
I am glad to have found this, so it explains the behaviour I was having.

I had a python editor written in pyqt and bundled with PyInstaller that would spawn some process executing user's python. Weirdly dlls on the current working directory would not be found when running from the IDE, but would then running exactly the same thing from `cmd`.

I was able to debug with Process Monitor and see that the IDE process was looking at the bundled exe directory but not on the current directory anymore. And now reading the documentation for `SetDllDirectoryA` it says `... the call removes the current directory from the default DLL search order.`

Isn't there a way that PyInstaller would just add the bundle directory without necessarily removing the current directory from the search paths? Of course, providing such functionality is available in the windows api.

**Comment by 20iahazban** [comment] 2020-01-29 09:35
Thank you very much @zehome !!!

**Comment by BenBarker** [comment] 2020-04-08 22:53
Thank you for this @zehome and @matthchr
