### ISSUE TITLE
AttributeError: 'module' object has no attribute '_MEIPASS' on Windows 8

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#801] opened 2014-10-18 14:47 UTC
**Original date**: 2013/10/17
**Original reporter**: *wettenhj*

Thanks very much for providing PyInstaller - it has been extremely useful to us!

We build a 32-bit stand-alone Windows executable of our wxPython application on a Windows XP virtual machine using PyInstaller 2.1.  We have successfully deployed this build to many Windows XP machines and Windows 7 machines and to a couple of Windows Vista and Windows 8 machines.

However, one of our Windows 8 users reported that the executable didn't run at all (no error message), so we gave them a special build, using PyInstaller 2.1's --debug argument, which generated the following output:

```
C:\Program Files (x86)\MASSIVE Launcher>launcher.exe
LOADER: executable is C:\PROGRA~2\MASSIV~1\launcher.exe 
LOADER: homepath is C:\PROGRA~2\MASSIV~1 
LOADER: _MEIPASS2 is NULL 
LOADER: archivename is C:\PROGRA~2\MASSIV~1\launcher.exe 
LOADER: C:\PROGRA~2\MASSIV~1\launcher.exe does not contain an embedded package 
LOADER: C:\PROGRA~2\MASSIV~1\launcher.exe contains a digital signature 
LOADER: package found skipping digital signature in 
C:\PROGRA~2\MASSIV~1\launcher.exe 
LOADER: No need to extract files to run; setting extractionpath to homepath 
LOADER: Already in the child - running user's code. 
LOADER: manifestpath: C:\PROGRA~2\MASSIV~1\launcher.exe.manifest 
LOADER: Activation context created 
LOADER: Activation context activated 
LOADER: Python library: C:\PROGRA~2\MASSIV~1\python27.dll 
LOADER: Manipulating evironment 
LOADER: PYTHONPATH=C:\PROGRA~2\MASSIV~1 
LOADER: PYTHONHOME=C:\PROGRA~2\MASSIV~1 
LOADER: Manipulating Python's sys.path 
LOADER: importing modules from CArchive 
LOADER: extracted struct 
LOADER: extracted pyi_os_path 
LOADER: extracted pyi_archive 
LOADER: extracted pyi_importers 
LOADER: Installing import hooks 
LOADER: out00-PYZ.pyz 
LOADER: Running scripts 
Traceback (most recent call last): 
  File "<string>", line 35, in <module> 
AttributeError: 'module' object has no attribute '_MEIPASS' 
LOADER: RC: -1 from _pyi_egg_install.py 
LOADER: OK. 
LOADER: Deactivating activation context 
LOADER: Releasing activation context 
LOADER: Done 
LOADER: Cleaning up Python interpreter. 
```

**Comment by htgoebel** [comment] 2015-07-04 09:52
@wettenhj: Are you the original poster of this issue?

**Comment by wettenhj** [comment] 2015-07-06 00:59
Yes, sorry for not following up.  I experienced this problem on Windows 8, but then I couldn't reproduce it after upgrading to Windows 8.1  Feel free to close it.

**Closed** 2015-07-06 09:31 UTC
Labels: @high, @low, v2.1

**Comment by johnstile** [comment] 2015-11-14 00:53
sys._MEIPASS is missing from my Windows 8.1 system, using Python 2.7.10.
Changing PyInstaller-3.0\PyInstaller\loader\rthooks\pyi_rth_qt4plugins.py
to: 
  d = os.path.join(os.path.dirname(sys.executable), d)
fixed my issue.

**Comment by matysek** [comment] 2015-11-26 20:38
@johnstile Please test the 'develo' version and either create a new issue or create a pull request.
