### ISSUE TITLE
Using custom hook

### ISSUE THREAD

**Issue by qiray** [pyinstaller/pyinstaller#4465] opened 2019-10-08 13:27 UTC
Is there any possibility to use custom hook instead of built-in one?

I had a problem building my app with PyInstaller:
```
Unable to find "/usr/nltk_data" when adding binary and data files.
```
I found that there are some fixes for hook-nltk.py file (for example https://github.com/pyinstaller/pyinstaller/pull/3973). So now I can make my project work replacing PyInstaller's hook file with this one. 

But I want to create my own hook file and use it instead of built-in one. Copying correct hook-nltk.py to project folder and running with "--additional-hooks-dir=." doesn't work and I don't know how to fix it. I've also read https://pythonhosted.org/PyInstaller/hooks.html and didn't find any info.

Command:

``` bash
pyinstaller --onefile main.py --additional-hooks-dir=.
```

## System info: 
PyInstaller: 3.5
Python: 3.7.4
Platform: Linux-5.2.17-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine

**Comment by danyeaw** [comment] 2019-10-21 01:28
Duplicate of #1835.

**Comment by Legorooj** [comment] 2020-02-08 08:08
Please see the docs.

**Closed by Legorooj** 2020-02-08 08:08 UTC
