### ISSUE TITLE
Error on default cachedir with windows user name containing (non-english) non-latin characters

### ISSUE THREAD

**Issue by mindapocalypse** [pyinstaller/pyinstaller#1954] opened 2016-04-20 10:41 UTC
When using on windows with not English username (for example cyrillic) 
PyInstaller/building/utils.py  168 line [link to code](https://github.com/pyinstaller/pyinstaller/blob/4ff51ce28ff09a518344813381e75a0091a7125d/PyInstaller/building/utils.py#L168) fais with "UnicodeDecodeError: 'ascii' codec can't decode ..."

Workaround: Manually add system variable "PYINSTALLER_CONFIG_DIR" with only latin characters

**Comment by htgoebel** [comment] 2016-04-24 10:23
@codewarrior0 This is one for you :-)

**Comment by codewarrior0** [comment] 2016-04-24 10:44
@mindapocalypse Which Python version is that?

**Comment by htgoebel** [comment] 2017-09-25 19:34
No info since 1 1/2 year. Closing.

**Closed by htgoebel** 2017-09-25 19:34 UTC
Labels: Unicode

**Comment by mrdimfox** [comment] 2018-07-27 11:01
I can confirm this bug. It is really annoying.
Cache folder on Windows, by default, is located into **"\\Users\\%USERNAME%\\AppData\\Roaming\\pyinstaller\\"** folder. 
So if there are any utf-8 symbols in %USERNAME% we get UnicodeDecodeError exeption.
For example in my case:

`
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda\envs\mtuta\Scripts\pyinstaller-script.py", line 5, in <module>
    sys.exit(PyInstaller.__main__.run())
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\building\build_main.py", line 792, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\building\build_main.py", line 738, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\building\api.py", line 411, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\building\api.py", line 196, in __init__
    self.__postinit__()
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\building\api.py", line 259, in assemble
    dist_nm=inm)
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\site-packages\PyInstaller\building\utils.py", line 198, in checkCache
    cachedfile = os.path.join(cachedir, basenm)
  File "D:\ProgramData\Anaconda\envs\mtuta\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 7: ordinal not in range(128)
`
