### ISSUE TITLE
'Looking for dynamic libraries' step takes a long time

### ISSUE THREAD

**Issue by HyperBaton** [pyinstaller/pyinstaller#2022] opened 2016-06-02 10:01 UTC
I'm a new user to pyinstaller but loving it so far, it does all the things I need it to do!

My Windows build of a simple Python app with pyinstaller runs succesfully. However, it takes a long long time when performing the step 'Looking for dynamic libraries'. About 5 minutes I would say... When it's done with that step, it continues the Windows build just fine and the executable works.

The only import I do in my application is wxpython.

Is there any way to speed up this step? I have no idea if this is normal behaviour. I'm not a real developer and just trying to make a quick one purpose GUI application. Speeding up the build process would help me a great deal. Any hints?

**Comment by codewarrior0** [comment] 2016-06-02 10:12
Essentially a duplicate of #1920 - see discussion. Run PyInstaller from a source checkout until the new release is out.

**Closed by codewarrior0** 2016-06-02 10:12 UTC

**Comment by HyperBaton** [comment] 2016-06-02 11:35
Thanks very much for the quick response.
