### ISSUE TITLE
Error loading Python DLL on Windows when executing .exe from non-ascii path

### ISSUE THREAD

**Issue by m1lhaus** [pyinstaller/pyinstaller#1224] opened 2015-03-24 16:05 UTC
Yesterday I have discovered very strange behavior of built dist (.exe files) of my program when I tried to open the program from path which contains non-ascii characters and the program was located out of my primary hardisk (on another physical disk). I was able to reproduce the issue on another computer even with simple "Hello world" application. The key thing is to try to launch built application from another drive (even external USB drive) from path which contains non-ascii characters. With only ascii characters everything works fine. 

**How to reproduce:**

My setup:
OS: Windows 8.1 x64 Pro
HDD: 1. hdd (C:\ drive), 2. hdd (D:\ drive), ...
Python 2.7.9 x32
PyInstaller 2.1 (also I've tried latest dev) + all latest versions of dependencies 

Build some dist. i.e. simply Hello word by `pyinstaller hello.py`. Following is my output:

```
D:\_pyinstaller>pyinstaller hello.py --clean
0 INFO: wrote D:\_pyinstaller\hello.spec
14 INFO: Testing for ability to set icons, version resources...
14 INFO: ... resource update available
31 INFO: UPX is not available.
44 INFO: Processing hook hook-os
110 INFO: Processing hook hook-time
118 INFO: Processing hook hook-cPickle
161 INFO: Processing hook hook-_sre
236 INFO: Processing hook hook-cStringIO
284 INFO: Processing hook hook-encodings
299 INFO: Processing hook hook-codecs
549 INFO: Processing hook hook-httplib
549 INFO: Processing hook hook-email
612 INFO: Processing hook hook-email.message
753 WARNING: library python%s%s required via ctypes not found
846 INFO: Removing temporary files and cleaning cache in C:\Users\Milhaus\AppData\Roaming\pyinstaller
846 INFO: Extending PYTHONPATH with D:\_pyinstaller
846 INFO: checking Analysis
846 INFO: building Analysis because out00-Analysis.toc non existent
846 INFO: running Analysis out00-Analysis.toc
846 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
945 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
945 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91.manifest
947 INFO: Searching for file msvcr90.dll
947 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcr90.dll
947 INFO: Searching for file msvcp90.dll
947 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcp90.dll
947 INFO: Searching for file msvcm90.dll
947 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcm90.dll
998 INFO: Analyzing C:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\loader\_pyi_bootstrap.py
1006 INFO: Processing hook hook-os
1014 INFO: Processing hook hook-site
1026 INFO: Processing hook hook-encodings
1087 INFO: Processing hook hook-time
1095 INFO: Processing hook hook-cPickle
1141 INFO: Processing hook hook-_sre
1217 INFO: Processing hook hook-cStringIO
1270 INFO: Processing hook hook-codecs
1534 INFO: Processing hook hook-httplib
1537 INFO: Processing hook hook-email
1602 INFO: Processing hook hook-email.message
1743 WARNING: library python%s%s required via ctypes not found
1852 INFO: Processing hook hook-pydoc
1898 INFO: Analyzing C:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\loader\pyi_importers.py
1945 INFO: Analyzing C:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\loader\pyi_archive.py
2008 INFO: Analyzing C:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\loader\pyi_carchive.py
2070 INFO: Analyzing C:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\loader\pyi_os_path.py
2070 INFO: Analyzing hello.py
2070 INFO: Hidden import 'codecs' has been found otherwise
2070 INFO: Hidden import 'encodings' has been found otherwise
2070 INFO: Looking for run-time hooks
2211 WARNING: lib not found: api-ms-win-core-kernel32-private-l1-1-1.dll dependency of C:\Windows\system32\user32.dll
2243 WARNING: lib not found: api-ms-win-core-privateprofile-l1-1-1.dll dependency of C:\Windows\system32\user32.dll
2465 INFO: Using Python library C:\Windows\system32\python27.dll
2500 INFO: Warnings written to D:\_pyinstaller\build\hello\warnhello.txt
2503 INFO: checking PYZ
2503 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
2503 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
3103 INFO: checking PKG
3103 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
3103 INFO: building PKG (CArchive) out00-PKG.pkg
3123 INFO: checking EXE
3125 INFO: rebuilding out00-EXE.toc because hello.exe missing
3125 INFO: building EXE from out00-EXE.toc
3131 INFO: Appending archive to EXE D:\_pyinstaller\build\hello\hello.exe
3131 INFO: checking COLLECT
WARNING: The output directory "D:\_pyinstaller\dist\hello" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
5306 INFO: Removing dir D:\_pyinstaller\dist\hello
5306 INFO: building COLLECT out00-COLLECT.toc
``` 

Then move built dist to external hdd drive, meaning another physical drive (drive, not flash drives, etc.). Rename the folder where your dist is to some crazy non-ascii name like `hello_world_ěščřžýáíé` and then launch the exe. Following error will pop out:

```
Error loading Python DLL: D:\hello_world_─Ť┼í─Ź┼Ö┼ż├Ż├í├ş├ę\python27.dll (error code 126)
```

But when you move this non-ascii dir to main C:\ drive, it will launch. Maybe I am missing something all the time I have been using PyInstaller, but for now I am in dead end. 

Thanks in advance for investigating the problem.

**Comment by codewarrior0** [comment] 2015-05-05 19:40
In `bootloader/common/pyi_utils.c`:

```
    /* Use unicode version of function to load  dll file. */
	//return LoadLibraryExW(stb_to_utf8(buff, dllpath, sizeof(buff)), NULL,
            //LOAD_WITH_ALTERED_SEARCH_PATH);
	return LoadLibraryEx(dllpath, NULL, LOAD_WITH_ALTERED_SEARCH_PATH);
```

`dllpath` has previously been encoded to UTF-8. However, LoadLibraryExW expects the filename to be encoded as UTF-16. And since pyinstaller doesn't define UNICODE, it is actually calling LoadLibraryExA which expects it to be encoded as whichever ANSI codepage is set in the Control Panel under "Language For Non-Unicode Programs"!

**Comment by htgoebel** [comment] 2015-05-19 19:29
@codewarrior0 THanks for this input. Anything we can change to fix the at the root cause and hopefully *everywhere*.

**Comment by codewarrior0** [comment] 2015-05-20 02:15
I looked into this briefly about a week ago, and I ran into a completely different problem which I wasn't able to solve: when I put the built app into a folder called `hello_world_ěščřžýáíé`, it loads the Python DLL, but `sys.executable` has the wrong path: I believe it was something like `hello_world_ěšcrzyáíé` with only *some* of the characters accented.

Reading the original report again, I caught on that the problem only happens on D:\ and not C:\, and I was only running from C:\. I remember that the debug output from the bootloader actually displayed MS-DOS "8.3"-style pathnames (where long or non-ASCII paths are replaced with `~1`( for the python DLL and the archive path. I read somewhere that "8.3"-style pathnames are only supported by some filesystems, so that might be relevant.

Some of my users have reported problems like this one. I'll look into this issue again sometime.

**Comment by codewarrior0** [comment] 2015-06-05 01:57
The fix for this might be to convert the bootloader over to use wide-character APIs everywhere instead of ShortFileNames, since SFNs aren't guaranteed to be supported on all filesystems (they can actually be disabled on a system-wide or per-filesystem basis!). This is a rather big change - I noticed TODOs everywhere about changing to the unicode APIs.

One aspect of the change is that `sys._MEIPASS` is currently an SFN and a `bytes` type. It would be a bad idea to change that. For a complete fix, we would need to have `_MEIPASS` available as a `unicode` type, so I propose as part of the unicode fix, adding a new `sys._MEIPASSU` attribute which returns the app folder as a `unicode` type. (Maybe even add `sys.executableu` too, as a convenience for Windows users such as #1282 who are getting snagged by `sys.executable` being an SFN.)

All of the TODOs jumped out at me while I was looking into my proposed fix for the secondary issue in #1106. I've been getting reports from Japanese users getting hangs and crashes during the "Extracting binaries" step of the bootloader, so if this bothers me enough I might attack the unicode fix too.

**Comment by codewarrior0** [comment] 2015-08-15 17:26
This is almost certainly fixed in the `python3` branch. ShortPathNames are no longer used internally by the bootloader, and only used when initializing Python 2.7.

Still thinking about `sys._MEIPASSU` and `sys.executableu` as a convenience for users who want to use `unicode` filenames on Python 2.7 for Windows.

**Closed by codewarrior0** 2015-08-15 17:26 UTC
Labels: develop, Windows

**Comment by TejuJ** [comment] 2016-08-18 06:44
Use -F option 
pyinstaller -F hello.py

**Comment by ModalSeoul** [comment] 2016-10-23 19:55
The -F flag did *not* solve this for one of my users.

**Comment by ArneBachmannDLR** [comment] 2019-10-17 07:52
Any news? I experience the same problem (some machines, in a path `C:\vvf`)

**Comment by nragan34** [comment] 2019-12-31 23:20
This should fix your problem... 

In your project directory create a virtual environment... 
`python3 -m venv venv`
Activate that virtual environment` . /venv/bin/activate (linux)  venv\bin\activate.bat (windows)`
Install pyinstaller -->` pip3 install pyinstaller`

run pyinstaller on your script
`pyinstaller -F <your_script>`


This will run pyinstaller off the virtual environment instead of your machine. Leaving less room for error.
