### ISSUE TITLE
Can't delete exe even with another exe

### ISSUE THREAD

**Issue by FkinGuy** [pyinstaller/pyinstaller#1899] opened 2016-03-26 05:59 UTC
Hello,

I have been using pyinstaller for quite some time. I have run into a few issues but here is one for which I really can't find a solution.

I am trying to auto-uninstall an executable on Windows. Because I know I can't delete an exe on disk if it is running, I download and launch another executable in a temp folder, with the mission to suppress the original executable.

No matter what way I use to launch the second executable, deleting the first one allways raises a WindowsError 32, Can't delete file because it is used by another processus 'test_execl.exe'.

Here is a sample of my tries. Use the spec files to generate the same exes as me.
[Archive.zip](https://github.com/pyinstaller/pyinstaller/files/190366/Archive.zip)

I tried using subprocess.Popen, os.execl, and a few others, to no avail.

When I look at the %temp% folder, I can see the _MEIxxx created for the first executable, then being replaced by the _MEI for the second executable.
I use taskmanager or process explorer to verify there is no test_execl.exe process. Even if i do a "taskkill /im test_execl.exe /f" I get confirmation that the process doesn't exist.

I have also tried something like that:
import subprocess
CREATE_NEW_CONSOLE = 0x00000010
pid = subprocess.Popen(commande, creationflags=CREATE_NEW_CONSOLE).pid

On the other hand, when I do exactly the same thing in pure python (without using pyinstaller to generate exes) it does work, I have no problem deleting the first python script.

Am I doing something wrong ? Any help would be apreciated.

Guy

**Comment by htgoebel** [comment] 2016-03-26 14:41
- From your description I assume you are using onefile-mode. Is this correct?
- Did you ensure the first process terminated *completly* prior you try to install the new executable? Try freezing the app with `--debug` to see the output and add print-statements to your code.
- Do get ensure the correct paths, have a look at http://pythonhosted.org/PyInstaller/#id49 may be of help.

With your Python script, this work since the script is read by the Python interpreter and no lock on the file is kept.

**Comment by FkinGuy** [comment] 2016-03-26 17:30
Thank you for your prompt reply.
Yes, I use one-file mode

I recreated the exes with option --debug and here is the output. As you can see, the second executable starts after the other is finished. I triple checked that it is really finished, as it is not visible in taskmanager and "taskkill /im test_execl.exe /f" says it doesnt exist. The _MEIxxx folder disapears, too.

There are also several 10-seconds time.sleep() inside the second exe (see the code inside the zip) to ensure the first exe settles down. 
I write the error into a file:
try:
    os.remove("test_execl.exe")
except Exception as e:
    log_file.write(repr(e))

I get this in the file:
WindowsError(32, 'Le processus ne peut pas acc\xe9der au fichier car ce fichier est utilis\xe9 par un autre processus')

as soon as the second exe is finished, i can suppress the first one.

It is just as if the second exe's process would "inherit" the lock on the first exe.


D:\dist>test_execl.exe
LOADER: executable is D:\dist\test_execl.exe
LOADER: homepath is D:\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is D:\dist\test_execl.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
LOADER: executable is D:\dist\test_execl.exe
LOADER: homepath is D:\dist
LOADER: _MEIPASS2 is C:\Users\myname\AppData\Local\Temp\_MEI124682
LOADER: archivename is D:\dist\test_execl.exe
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\myname\AppData\Local\Temp\_MEI124682\test_execl.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\myname\AppData\Local\Temp\_MEI124682\python27.dll
LOADER: Manipulating evironment
LOADER: PYTHONPATH=C:\Users\myname\AppData\Local\Temp\_MEI124682
LOADER: PYTHONHOME=C:\Users\myname\AppData\Local\Temp\_MEI124682
LOADER: Manipulating Python's sys.path
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: extracted pyi_os_path
LOADER: extracted pyi_archive
LOADER: extracted pyi_importers
LOADER: Installing import hooks
LOADER: out00-PYZ.pyz
LOADER: Running scripts
LOADER: OK.
LOADER: Deactivating activation context
LOADER: Releasing activation context
LOADER: Done
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent
LOADER: Doing cleanup
LOADER: Freeing archive status for D:\dist\test_execl.exe

D:\dist>LOADER: executable is d:\dist\truc_lance.exe
LOADER: homepath is d:\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is d:\dist\truc_lance.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
LOADER: executable is d:\dist\truc_lance.exe
LOADER: homepath is d:\dist
LOADER: _MEIPASS2 is C:\Users\myname\AppData\Local\Temp\_MEI142042
LOADER: archivename is d:\dist\truc_lance.exe
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\myname\AppData\Local\Temp\_MEI142042\truc_lance.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\myname\AppData\Local\Temp\_MEI142042\python27.dll
LOADER: Manipulating evironment
LOADER: PYTHONPATH=C:\Users\myname\AppData\Local\Temp\_MEI142042
LOADER: PYTHONHOME=C:\Users\myname\AppData\Local\Temp\_MEI142042
LOADER: Manipulating Python's sys.path
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: extracted pyi_os_path
LOADER: extracted pyi_archive
LOADER: extracted pyi_importers
LOADER: Installing import hooks
LOADER: out00-PYZ.pyz
LOADER: Running scripts
LOADER: OK.
LOADER: Deactivating activation context
LOADER: Releasing activation context
LOADER: Done
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent
LOADER: Doing cleanup
LOADER: Freeing archive status for d:\dist\truc_lance.exe

**Comment by FkinGuy** [comment] 2016-03-26 17:47
Mmh, looks like I got an evidence that the second exe is keeping the lock of the first one.

I used the lock file search function of sysinternal's process explorer . the exe test_execl.exe is finished, and yet there are locks hold by truc_lance.exe:
![image](https://cloud.githubusercontent.com/assets/2120880/14061559/2aad28b0-f383-11e5-94bf-2856fab07d03.png)

looks like the second exe keeps the pid of the first...
Is there any way to get rid of this first pid ?

**Comment by htgoebel** [comment] 2016-03-26 18:20
> Is there any way to get rid of this first pid ?

I'm afraid, I can not help you on this. I'm not a windows guy.

**Comment by codewarrior0** [comment] 2016-03-28 07:23
By default, the subprocess launched by `Popen` inherits open filehandles from the parent, and it seems this includes the filehandle opened for the parent's own executable file. Can you try passing `close_fds=True` to your `subprocess.Popen` call and see if anything changes?

That option will prevent you from communicating with the subprocess via stdio, but judging by your use case, you won't need to.

**Comment by FkinGuy** [comment] 2016-03-28 21:28
My hopes were high when I saw your message Codewarrior, but this option close_fds=True doesn't help either :( 
I suppose it is because the Popen call is already finished when pyinstaller does its cleanup. 
Perhaps the solution would be to have an option in the .spec to tell pyinstaller to remove all locks to the exe when doing the cleanup ?

I found a workaround for now, though : I bundle [Lockhunter](http://lockhunter.com/) into the second program and use the following command to unlock the file before deleting it:
`os.system(os.path.join(pyinstaller_path, "lockhunter.exe") +" D:\\dist\\test_execl.exe /unlock /silent")`

here is the .spec for the packaging of lockhunter: [truc_lance.zip](https://github.com/pyinstaller/pyinstaller/files/192499/truc_lance.zip)

I use this trick to find the path to the packaged lockhunter files from the python script:
```
pyinstaller_path = ""
if hasattr(sys, '_MEIPASS'):
    # PyInstaller >= 1.6
    os.chdir(sys._MEIPASS)
    pyinstaller_path = sys._MEIPASS
elif '_MEIPASS2' in os.environ:
    # PyInstaller < 1.6 (tested on 1.5 only)
    os.chdir(os.environ['_MEIPASS2'])
    pyinstaller_path = os.environ['_MEIPASS2']
else:
    os.chdir(os.path.dirname(sys.argv[0]))
    pyinstaller_path = os.path.dirname(sys.argv[0])
```

**Comment by codewarrior0** [comment] 2016-03-29 09:12
I cannot reproduce this. Even without `close_fds=True`, the second script is able to remove the first one after it is finished.

> looks like the second exe keeps the pid of the first...

This should only happen when calling `execl`, which you generally shouldn't do on Windows because it doesn't have a `fork` function, so the standard fork/exec combo won't work as expected. 

Were you able to identify which process was holding a lock on the original exe when calling the second one using `subprocess.Popen`?

**Comment by FkinGuy** [comment] 2016-04-02 04:57
I rebooted my computer and retried, with `close_fds=True` as the only option to subprocess.Popen and it did work !
Perhaps it had to do with the other options that I had left (CREATE_NEW_CONSOLE...) or because there was a lingering lock from a previous test...

For posterity, the solution that worked for me is this:
`subprocess.Popen("myexecutable.exe", close_fds=True)`

Thank you very much for the help :)

**Comment by tallforasmurf** [comment] 2016-04-02 15:21
Should this be added to [recipe Subprocess](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess)? It already covers some issues with subprocess on Windows...

**Comment by FkinGuy** [comment] 2016-04-02 20:37
I think it should be added, for sure.

**Comment by tallforasmurf** [comment] 2016-04-04 18:17
I would update the Wiki for recipe Subprocess, except that I still don't grasp the use case. Could you spell out in general terms what is going on? (I thought I understood, but then realized it looks like you are trying to delete the temp folder and, what's the point, or how does that equate to "uninstall"?)

**Comment by htgoebel** [comment] 2017-08-25 10:11
@FkinGuy I would appreciate if you would update the recipe Subprocess with the insight from this ticket. Like tallforasmurf I don't know how to describe the use case. I'm closing this thicket, sicne there is nothing left to do for the developers.

**Closed by htgoebel** 2017-08-25 10:11 UTC
Labels: support, Windows
