### ISSUE TITLE
pyinstall error

### ISSUE THREAD

**Issue by cqray1990** [pyinstaller/pyinstaller#5047] opened 2020-08-03 09:12 UTC
when packed my code it raise the errors:
 File "/home/wb/.local/lib/python3.6/site-packages/PyInstaller/archive/writers.py", line 266, in tobinary
    flag, ord(typcd), nm + pad))
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by bwoodsend** [comment] 2020-08-03 10:40
@cqray1990 Please fill in the issue template so we can have any hope of working out what the problem is. Closing now as an issue without said information is just clutter. Will re-open if/when you do provide those details.

**Closed by bwoodsend** 2020-08-03 10:40 UTC
