### ISSUE TITLE
Regression in scipy 1.9.1 -> 1.9.2

### ISSUE THREAD

**Issue by pwuertz** [pyinstaller/pyinstaller#7168] opened 2022-10-17 10:32 UTC
Although being described as just a bug fix release, an upgrade of `scipy` from `1.9.1` to `1.9.2` (via pip) breaks bundled applications.

With scipy 1.9.2 the bundled application is trying to look up a non-existent directory named "./scipy.libs", but the scipy DLLs were copied to "./scipy/_lib/".

With scipy 1.9.1 PyInstaller copies the scipy DLLs to "./scipy/.libs/", which the application successfully imports.

**Error:**
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "scipy\__init__.py", line 76, in <module>
  File "scipy\__init__.py", line 67, in _delvewheel_init_patch_1_0_1
  File "os.py", line 1111, in add_dll_directory
FileNotFoundError: [WinError 2] The system cannot find the file specified: '<path_to_dist>\\scipy.libs'
```

**Minimal example:**
```python
import scipy
print(f"Scipy: {scipy}")
```

**Environment:**
 - OS: Windows
 - Python Version: 3.9
 - Version of `pyinstaller-hooks-contrib`: 2022.10
 - Version of PyInstaller 5.5

**Comment by rokm** [comment] 2022-10-17 20:22
Moving this to main repository, since that's where the hooks for `scipy` reside. 

The problem is that 1.9.2 switched to `delvewheel`, which brings its shared libs directory outside of the package directory (`site-packages/scipy.libs` as opposed to former `site-packages/scipy/.libs`), which means it is now out of our sight and out of our mind.

**Comment by rokm** [comment] 2022-10-18 12:49
The fun part is that our `scipy` tests suceeded in spite of using 1.9.2 - that's because in those, at least one `scipy` extension is imported, and therefore binary dependency analysis picks up the DLLs in the external .libs directory. It would have broken down on python 3.7 due to the load order file not being collected, but we have older version pinned there due to lack of wheels for newer version...

In a way, not collecting the DLLs for basic `import scipy` could be considered correct behavior, as nothing is collected that really requires them. Perhaps we could ask @adang1345 to modify `delvewheel` init/patch script so that it checks whether the .libs directory exists before trying to pass the path to `os.add_dll_directory` (same for the load order file)?

**Closed as completed** 2022-10-19 19:06 UTC
Labels: bug
