### ISSUE TITLE
Error while using camelot-py (Related to ModuleNotFoundError: No module named 'cv2' #6372)

### ISSUE THREAD

**Issue by LuizMosciaro** [pyinstaller/pyinstaller#6907] opened 2022-06-22 18:22 UTC
## Description of the issue
Suppose i'm trying to turn this snnipet into a .exe:

**import camelot

file2 = r'C:\Users\supor\Documents\DB\foo.pdf'
df2 = camelot.read_pdf(file2)
print(len(df2))**

I always get the error when execute the new .exe:
**ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.**

I've tried to reinstall everything and even pass the path of cv2 as the [issue](https://github.com/pyinstaller/pyinstaller/issues/6372) recommends but it just dont work 

Command used:
**pyinstaller --onefile Teste.py**
also tried among others commands:
**pyinstaller --onedir --console --paths="C:/Users/supor/AppData/Local/Programs/Python/Python310/Lib/site-packages/cv2" --paths="C:/Users/supor/AppData/Local/Programs/Python/Python310/Lib/site-packages/camelot" Teste.py**
But none seems to work

### Context information (for bug reports)
pip version 22.1.2
opencv-python Version: 4.6.0.66
camelot-py Version: 0.10.1
pyinstaller Version: 5.1
python 3.10.3 and 3.9.10 64bit > downloaded from https://www.python.org/downloads/
OS Win10

**Comment by rokm** [comment] 2022-06-22 18:40
Duplicate of #6889. For now, you'll need to dowgrade your opencv to 4.5.5.64.

**Closed as completed by rokm** 2022-06-22 18:40 UTC
Labels: solution:duplicate

**Comment by LuizMosciaro** [comment] 2022-06-22 19:42
Thank you very much, this solved my problem when i also created a new virtual environment.
Cheers from Manaus city.
