### ISSUE TITLE
Bootloader still not properly extracting VCRUNTIME140.dll in pysintaller 5.13.2

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [pyinstaller/pyinstaller#7935] opened 2023-09-13 15:39 UTC
### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.13.2 as loaded from https://files.pythonhosted.org/packages/1a/74/c65be869ae47649b98a928b3122c27d72fe372138aab4dc6cdd42e217d8a/pyinstaller-5.13.2-py3-none-win_amd64.whl.metadata
* Version of Python: 3.11
* Platform: Windows
* How you installed Python: Github action for python 3.11
* Did you also try this on another platform? Does it work there? Yes it does work under windows and when I copy the `VCRUNTIME140.dll` file into the same directory the onefile-exe resides in

I'm packaging the application as --onefile using `pyinstaller --clean --log-level DEBUG --name "sph_uploader" --add-data "conf;conf" --add-data "ui/*.ui;ui" --add-data "../art/icon.png;art" --splash ../art/splash.png --specpath src --icon ../art/icon.png --onefile --debug bootloader src/main.py`  in this workflow: https://github.com/tmolitor-stud-tu/sph_uploader/blob/master/.github/workflows/pyinstaller-all.yaml

**When I watch the __splash directory when the error dialog box pops up, the dll file is not extracted there, like in #6284**

**Comment by rokm** [comment] 2023-09-13 16:17
>``` 
>23516 DEBUG: Use Tcl Library from ('tcl86t.dll', 'C:\\hostedtoolcache\\windows\\Python\\3.11.5\\x64\\DLLs\\tcl86t.dll') and Tk From ('tk86t.dll', 'C:\\hostedtoolcache\\windows\\Python\\3.11.5\\x64\\DLLs\\tk86t.dll')
>23516 INFO: Collect tcl/tk binaries for the splash screen
>23548 INFO: checking Tree
>23548 INFO: Building Tree because Tree-00.toc is non existent
>23548 INFO: Building Tree Tree-00.toc
>27082 INFO: checking Tree
>27082 INFO: Building Tree because Tree-01.toc is non existent
>27082 INFO: Building Tree Tree-01.toc
>27410 INFO: checking Tree
>27410 INFO: Building Tree because Tree-02.toc is non existent
>27410 INFO: Building Tree Tree-02.toc
>27441 DEBUG: Analyzing C:\hostedtoolcache\windows\Python\3.11.5\x64\DLLs\tcl86t.dll
>27457 DEBUG: Adding api-ms-win-crt-utility-l1-1-0.dll dependency of tcl86t.dll from C:\Program Files\PowerShell\7\api-ms-win-crt-utility-l1-1-0.dll
>27457 DEBUG: Skipping ADVAPI32.dll dependency of tcl86t.dll
>27457 DEBUG: Skipping USERENV.dll dependency of tcl86t.dll
>27457 DEBUG: Skipping NETAPI32.dll dependency of tcl86t.dll
>27457 DEBUG: Skipping KERNEL32.dll dependency of tcl86t.dll
>27457 DEBUG: Skipping USER32.dll dependency of tcl86t.dll
>27457 DEBUG: Skipping WS2_32.dll dependency of tcl86t.dll
>27457 DEBUG: Analyzing C:\hostedtoolcache\windows\Python\3.11.5\x64\DLLs\tk86t.dll
>27457 DEBUG: Dependent assemblies of C:\hostedtoolcache\windows\Python\3.11.5\x64\DLLs\tk86t.dll:
>27457 DEBUG: AMD64_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
>27457 DEBUG: Skipping assembly AMD64_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
>27504 DEBUG: Skipping ADVAPI32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping GDI32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping SHELL32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping COMDLG32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping KERNEL32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping USER32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping COMCTL32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping IMM32.dll dependency of tk86t.dll
>27520 DEBUG: Skipping ole32.dll dependency of tk86t.dll
>27520 DEBUG: Analyzing C:\Program Files\PowerShell\7\api-ms-win-crt-utility-l1-1-0.dll
>27520 DEBUG: Splash Requirements: {'api-ms-win-crt-utility-l1-1-0.dll', 'tk\\ttk\\fonts.tcl', 'tk\\ttk\\ttk.tcl', 'tk86t.dll', 'tk\\text.tcl', 'tk\\ttk\\cursors.tcl', 'tcl86t.dll', 'tk\\license.terms', 'tk\\tk.tcl', 'tk\\ttk\\utils.tcl'}
>``` 

Looks like the binary dependency analysis ran by splash fails to pick up `vcruntime140.dll` as dependency of Tcl and Tk shared libraries - presumably because it is already in `bindepend.seen` set at that point (from the binary dependency analysis in the main analysis part). 

So this is a regression introduced in #7679 (5.12), but it is already fixed in `develop` (v6) where `bindepend.seen`  has been removed.

**Comment by tmolitor-stud-tu** [comment] 2023-09-13 17:51
I'm not familiar with the codebase, but shouldn't it at least log something about skipping `vcruntime140.dll` then?

If you want, I can create a pull request fixing this in the `5.13` line as `5.13.3`.
I'd just copy over the old fixed addition of `vcruntime140.dll` as it was before the complete dependency analysis.

**Comment by tmolitor-stud-tu** [comment] 2023-09-13 17:52
Ah, forget it, I see you already fixed it in 395fde45d6da8d1b24b3813c83cf65b1c3409cae, great! :)

**Comment by tmolitor-stud-tu** [comment] 2023-09-13 17:53
Do you plan to release a 5.13.3 containing this fix in the next couple of days?

**Closed as completed** 2023-09-28 19:35 UTC
Labels: bug
