### ISSUE TITLE
Request not a issue -Pyinstaller on directory bundle - parent directory should have exe and a sub directory of rest of the resources

### ISSUE THREAD

**Issue by rajeshkumargp** [pyinstaller/pyinstaller#4014] opened 2019-01-25 17:11 UTC
This is a request and not a issue. 

I want the result of pysinstaller one directory option to be having binary and rest of the resources iin sub directory. 

Parent Directory -APPLICATION DIRECTORY
 1. executable binary
 2. sub directory having rest of the resources 

instead of having execuatble, list of files,and other resources.
ie. only 2 levels should be below the APPLICATION DIRECTORY

How to build like as above?
Is any configuration option for the above. 

Can you please guide ..

**Comment by htgoebel** [comment] 2019-01-28 20:23
This is not to be implemented easily and would require considerable changes to the bootloader.
See #3606 and #2702.

Duplicate of #2702

**Closed by htgoebel** 2019-01-28 20:23 UTC
