### ISSUE TITLE
Failure on stable when bundling Flask

### ISSUE THREAD

**Issue by amyipdev** [pyinstaller/pyinstaller#5661] opened 2021-03-22 03:28 UTC
## Description of the issue

Building an application that contains Flask fails.

## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.2
* Version of Python: 3.9.2
* Platform: GNU/Linux (Arch Linux)
* Did you also try this on another platform? Does it work there? Not tried on another platform.

* Latest dev version works

### A minimal example program which shows the error

https://github.com/amyipdev/statdis/blob/main/server/basic-flask/main.py

### Stacktrace / full error message

```py
(venv) amy@amyip:~/Development/statdis(main⚡) » pyinstaller -w -F server/basic-flask/main.py                                                                                                                                             2 ↵
18 INFO: PyInstaller: 4.2
18 INFO: Python: 3.9.2
19 INFO: Platform: Linux-5.11.7-arch1-1-x86_64-with-glibc2.33
20 INFO: wrote /home/amy/Development/statdis/main.spec
21 INFO: UPX is not available.
22 INFO: Extending PYTHONPATH with paths
['/home/amy/Development/statdis/server/basic-flask',
 '/home/amy/Development/statdis']
24 INFO: checking Analysis
26 INFO: Building because inputs changed
26 INFO: Initializing module dependency graph...
27 INFO: Caching module graph hooks...
29 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
29 INFO: Analyzing base_library.zip ...
1214 INFO: Processing pre-find module path hook distutils from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1215 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.9'
2210 INFO: Caching module dependency graph...
2255 INFO: running Analysis Analysis-00.toc
2273 INFO: Analyzing /home/amy/Development/statdis/server/basic-flask/main.py
3207 INFO: Processing module hooks...
3207 INFO: Loading module hook 'hook-jinja2.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
3216 INFO: Loading module hook 'hook-difflib.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3216 INFO: Excluding import of doctest from module difflib
3216 INFO: Loading module hook 'hook-distutils.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3217 INFO: Loading module hook 'hook-encodings.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3245 INFO: Loading module hook 'hook-heapq.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3246 INFO: Excluding import of doctest from module heapq
3246 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3247 INFO: Excluding import of test from module multiprocessing.util
3247 INFO: Loading module hook 'hook-pickle.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3247 INFO: Excluding import of argparse from module pickle
3247 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3496 INFO: Processing pre-safe import module hook win32com from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
3536 WARNING: Hidden import "pkg_resources.py2_warn" not found!
3536 WARNING: Hidden import "pkg_resources.markers" not found!
3537 INFO: Excluding import of __main__ from module pkg_resources
3537 INFO: Loading module hook 'hook-sysconfig.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3541 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3541 INFO: Loading module hook 'hook-xml.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3562 INFO: Loading module hook 'hook-distutils.util.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3563 INFO: Excluding import of lib2to3.refactor from module distutils.util
3563 INFO: Loading module hook 'hook-lib2to3.py' from '/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
3579 INFO: Looking for ctypes DLLs
Traceback (most recent call last):
  File "/home/amy/Development/statdis/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "/home/amy/Development/statdis/main.spec", line 6, in <module>
    a = Analysis(['server/basic-flask/main.py'],
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 242, in __init__
    self.__postinit__()
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 438, in assemble
    ctypes_binaries = scan_code_for_ctypes(co)
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 145, in scan_code_for_ctypes
    binaries = _resolveCtypesImports(binaries)
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 319, in _resolveCtypesImports
    load_ldconfig_cache()
  File "/home/amy/Development/statdis/venv/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 402, in load_ldconfig_cache
    path = m.groups()[-1]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by rokm** [comment] 2021-03-22 08:45
Duplicate of #5540, which was fixed by #5547. So until new release is made, you'll have to use `develop` branch.

**Closed by rokm** 2021-03-22 08:45 UTC
