### ISSUE TITLE
Some dependency package using PBR seem to lack some mandatory metadata

### ISSUE THREAD

**Issue by gsemet** [pyinstaller/pyinstaller#3617] opened 2018-07-03 16:14 UTC
Hi.

On some package that use [PBR](https://docs.openstack.org/pbr/latest/), I get this error at runtime:
```
  File "/home/user/myproject/.venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/mydependency/__init__.py", line 24, in <module>
  File "site-packages/pbr/version.py", line 457, in release_string
  File "site-packages/pbr/version.py", line 462, in semantic_version
  File "site-packages/pbr/version.py", line 449, in _get_version_from_pkg_resources
  File "site-packages/pbr/packaging.py", line 824, in get_version

Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git 
repository. It's also possible that there is a mismatch between the package name in setup.cfg and the 
argument given to pbr.version.VersionInfo. Project name nestor_gitlab was given, but was not able to
be found.
```
This is a classic error when PBR cannot find:
- the metadatafile in the site-package folder (`PKG-INFO` or `METADATA`), from which extract the `Version` key
- the git history (mainly used for dev).

Does pyinstaller bundles the complete wheel/distribution package in the executable? Can it also bundle one or both of theses file as long as the .py files?

Thanks

**Comment by gsemet** [comment] 2018-07-03 16:16
My workaround is to define in a hook the environment variable `PBR_VERSION` that force PBR to always return a given version. It will work until one package define an incompatible constrain in `install_requires` in its `setup.py` for this dependency.

**Comment by htgoebel** [comment] 2018-07-03 19:23
This basically is a Duplicate of #2717. Maybe you want so work on that one?

**Closed by htgoebel** 2018-07-03 19:23 UTC

**Comment by gsemet** [comment] 2018-07-03 19:39
Would love to, not sure if i can
