### ISSUE TITLE
hookutils.get_package_paths returns only first path of package

### ISSUE THREAD

**Issue by thorsant** [pyinstaller/pyinstaller#1285] opened 2015-06-01 11:34 UTC
Hi

The hookutils.get_package_paths only returns the first path of a module, not all in the case a modules path is extended. collect_submodules only handles the case where hookutils returns one single path.

Is this the way it is meant to be?

**Comment by htgoebel** [comment] 2015-06-01 13:40
What do you mean with "in the case a modules path is extended"? To my knowledge, a module has exactly *one* path.

NB: Please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by htgoebel** [comment] 2015-06-01 13:45
I assume this is related to #1283.

**Comment by matysek** [comment] 2015-09-22 11:54
Closing. It is duplicate of #1283

**Closed by matysek** 2015-09-22 11:54 UTC
