### ISSUE TITLE
Remove full paths from .pyc/.pyo files

### ISSUE THREAD

**Issue by rasky** [pyinstaller/pyinstaller#1059] opened 2014-10-18 15:17 UTC
**Original date**: 2010/02/26

PyInstaller bundles .pyc/.pyo files as found in the build system. Those files contain the fully-qualified paths of the original source code files, and those paths are shown for instance in tracebacks.

It would be better if PyInstaller stripped those paths, though not completely. For instance, the following path:

```
/Users/FooBar/series60-
remote/trunk/pc/build/pyi.darwin/series60_remote.darwin/outPYZ1.pyz/lib.device
```

should probably become something like:

```
series60_remote.darwin/outPYZ1.pyz/lib.device
```

To do this, probably it is necessary to:

 1. Unmarshal each .pyc into a live data structure
 1. Go through the code data structure, finding all occurrences of the paths and replacing them.
 1. Marshal the .pyc file again into a binary stream

**Comment by jeremydw** [comment] 2015-06-05 02:12
Hi folks, any update here? If not, we'll likely move our builds to work directories that we are OK exposing to users, such as something like `/build/<appname>/` since it is not OK to expose our usernames on our build machines to users in tracebacks. Wondering if other folks have been taking the same strategy. Cheers!

**Comment by codewarrior0** [comment] 2015-06-05 02:18
+1 for privacy and for more readable tracebacks.

>PyInstaller bundles .pyc/.pyo files as found in the build system. Those files contain the fully-qualified paths of the original source code files, and those paths are shown for instance in tracebacks.

Oh, so THAT'S where they are coming from. I thought they were coming from the archive instead. Okay, that makes sense. It seems like a good way to strip the paths is to go to each path stored in a pyco, and strip off any leading component that matches any path in `sys.path`.

**Comment by jeremydw** [comment] 2015-06-08 16:58
Has this been fixed (either in some new version of PyInstaller or perhaps it has always been there) through the use of the `name` argument to the PYZ command in spec files? I added `name='growsdk'` to my PYZ command, so it now looks like:

```
pyz = PYZ(a.pure,
          name='growsdk')
```

Now tracebacks displayed by the frozen executable look like the following snippet:

```
Traceback (most recent call last):
[...]
  File "growsdk/dulwich.client", line 937, in _discover_references
  File "growsdk/dulwich.client", line 927, in _http_request
dulwich.errors.GitProtocolError: unexpected http response 401
```

Whereas before, without the `name` argument provided, users would see the build system's path, e.g. in the following snippet.

```
Traceback (most recent call last):
[...]
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/grow.commands", line 186, in Run
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/grow.server.manager", line 53, in start
AttributeError: 'module' object has no attribute 'create_dev_server_observer'
```

Note this dumps an extra file into your current working directory, but I just `.gitignore`ed it. There might be another config option to specify where this file goes but since I got everything working with minimal changes I didn't really care.

@codewarrior0 perhaps try adding the `name` argument to the PYZ command in your spec file and seeing if you can verify the fix? I've verified it for my project on both Mac and Ubuntu. Our corresponding [issue was here](https://github.com/grow/pygrow/issues/45) and [the fix here](https://github.com/grow/pygrow/commit/0a2a9bfe5f953f5edfb42a8466d7d27f4ff6cad1#diff-cece9af4a2907a2d3c78e5b3ad72d2b6R59).

**Comment by codewarrior0** [comment] 2015-06-08 17:37
Yep, adding `name` seems to fix it, but I found out what it's actually doing. `name` specifies the output filename for the PYZ build step, and that is what's putting the extra file in your working directory. Without `name` it uses a file under `build/`, whose name is given by an absolute path. This absolute path is given to the builtin `compile()` (as the effective filename to use, since it is passing the file's contents to `compile`) when compiling the `.py` files while adding them to the PYZ archive in [`pyi_archive.py:358`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyi_archive.py#L358)

So, this is where the path stripping needs to happen.

**Comment by codewarrior0** [comment] 2015-06-09 03:02
In fact, why is the archive path even being added to the effective filename? PyInstaller already fools around with the code object's `__file__` attribute in the pyi_importer, so the original description is slightly incorrect: It's not embedding the original path of the source files themselves, what it's embedding is the original path of the PYZ file that was output by the PYZ build step!

So there's no need to touch any code objects directly. It seems like all we need to do is use `basename(self.name)` instead of `self.name` in the call to `compile()`.

**Comment by LevN0** [comment] 2015-10-16 17:56
The workaround proposed here does not seem to work on Linux. Moreover if you put the same name for the PYZ file as your application output file then the created binary does not start (exits without error immediately upon launch) and if it's different then traceback outputs full paths as before.

**Comment by codewarrior0** [comment] 2015-12-15 11:11
Now a duplicate of #1724

**Closed by codewarrior0** 2015-12-15 11:11 UTC
Labels: @low, feature
