### ISSUE TITLE
Pyinstaller cant hook cv2 module

### ISSUE THREAD

**Issue by newpronik** [pyinstaller/pyinstaller#6889] opened 2022-06-14 05:28 UTC
Pyinstaller cant hook new version of opencv-python-headless==4.6.0.66

no any problem with previous version opencv-python-headless==4.5.5.64

PyInstaller Version : 5.1
Python Version: 3.10.4
Platform: PopOs 22.04

**Comment by rokm** [comment] 2022-06-14 12:25
This is technically a duplicate of pyinstaller/pyinstaller-hooks-contrib#110, but I'm going to leave it open here as well. 

If we want to support the module swap (passing `cv2.cv2` as `cv2`) that OpenCV's loader tries to perform, we'll need to modify the PyInstaller's `FrozenImporter`'s behavior, i.e., have it check `sys.path` for any additional paths pointing into `sys._MEIPASS` *and* check if the module happens to be an extension module in that location; in which case, we should hand it off to the next loader instead of trying to load (possibly eponymous) module from the PYZ.

Although on the other hand, as OpenCV loader expects at least some of its .py files to be present on the disk, we might as well try to modify the hooks to prevent any module collection to PYZ and instead just collect everything in its source form. This would also let us bypass the recursion problem due to ignored `sys.path` modification (but we need to ensure that none of `cv2` modules end up in PYZ).

**Comment by bwoodsend** [comment] 2022-06-14 20:55
I just don't see how any of this is feasibly going to happen.

**Comment by rokm** [comment] 2022-06-14 21:08
Maybe it's time to start looking into adding `collect_as_source` as an additional hook output - if set, then all pure-python modules from this node and its child nodes are collected as .py source files (and placed into `data` TOC) instead of as .pyc files that are placed into `pure` TOC and collected into the PYZ. 

I imagine this would be the cleanest approach to the problem of packages that require source files for whatever reason; because in that case, collecting .pyc modules either leads to trouble (as in the case of `cv2`) or at the very least unnecessary collection of both .pyc module and its .py source.

**Comment by bwoodsend** [comment] 2022-06-14 21:26
Actually that `collect_distribution()` function I wrote but forgot to submit to replace `collect_all()` had an option to collect `.py` files - that would have done half of it. We'd still need to dream up something ugly to ensure that the `.pyc` files are excluded.

**Comment by rokm** [comment] 2022-06-14 21:49
Yeah, but if you think about it, collecting .py files via `datas` in hooks is not ideal, because they don't undergo import analysis that (hidden)imports undergo. Currently, this is not (so much of) a problem because the analysis is done on the modules that end up collected as .pyc files. 

But being able to decide whether a module is to be collected as a .pyc in PYZ or a .py in datas at the TOC generation time (at the end of analysis) would ensure that all modules undergo proper analysis and that there are no PYZ entries where we want source .py files.

**Comment by Sclafus** [comment] 2022-06-16 08:53
Having the exact same issue in Linux Mint 20.3 and Windows 10 21H2 (19044.1766).
Rolling back works just fine, but it's not ideal.

**Comment by rokm** [comment] 2022-07-24 14:52
This will be fixed once both next version of `PyInstaller` (presumably v5.3) and next version of `pyinstaller-hooks-contrib` (presumably v2022.9) are released.

In the meantime, you can install from their `develop` and `master` branches, respectively, but you need a working C compiler to recompile the bootloader:

```
PYINSTALLER_COMPILE_BOOTLOADER=1 pip install git+https://github.com/pyinstaller/pyinstaller.git@develop
pip install git+https://github.com/pyinstaller/pyinstaller-hooks-contrib.git@master
```

**Closed as completed** 2022-07-24 14:52 UTC
