### ISSUE TITLE
Hook for `osgeo` libraries

### ISSUE THREAD

**Issue by giumas** [pyinstaller/pyinstaller#1522] opened 2015-09-24 23:13 UTC
I am attempting to put together a hook file for `osgeo` libraries (i.e., `gdal`, `ogr`, `osr`, ) that is required to be a bit flexible to adapt at different possible installation flavors.

As first step, I am attempting to manage these two configurations on `Python 2.7.10 32bit`:
- classic `cpython` (using the `gdal` wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal with `1.11.3`)
- `miniconda` (thus the `gdal` conda package `1.11.2`)

This latter is a bit more complicated, since the auxiliary data (and the `proj4` library) are stored separately from the python package. Given that, I wrote:

```
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.misc import is_win

import os
import sys

# osgeo.gdal requires auxiliary data and may have hidden dependencies
# hook was tested with gdal (v.1.11.2 and 1.11.3) on Win7 64bit

is_conda = False

# auxiliary data
# - general case
datas = collect_data_files('osgeo', subdir='data/gdal')

if len(datas) == 0:

    # - conda-specific
    tgt_gdal_data = os.path.join('Library', 'data')
    src_gdal_data = os.path.join(os.path.dirname(sys.executable), 'Library', 'data')
    if os.path.exists(src_gdal_data):
        is_conda = True
        files = os.listdir(src_gdal_data)
        for f in files:
            src_abs_path = os.path.join(src_gdal_data, f)
            datas.append((src_abs_path, tgt_gdal_data))

if is_conda:
    if is_win:
        proj_dll = os.path.join(os.path.dirname(sys.executable), 'proj.dll')
        binaries = [(proj_dll, ""), ]
```

Such a hook seems to work for these 2 specific configurations. However, I am not sure that I am following the "best practices" on doing this.

Which of the existing hook files do you suggest to follow as template? 
Do you have directions on how to better manage the `osgeo` hook given the several possible configurations?

**Comment by matysek** [comment] 2015-09-25 10:09
Some notes:
* use import `from PyInstaller.compat import is_win`
* add more comments about what is conda and where it stores data files
* `sys.executable` won't work in virtualenv. To obtain data dir, rather use `sys.real_prefix`.
* put there  a `TODO` that it should be tested on other platforms.
* You could replace this whole code 
```python
        files = os.listdir(src_gdal_data)
        for f in files:
            src_abs_path = os.path.join(src_gdal_data, f)
            datas.append((src_abs_path, tgt_gdal_data))
```
with just
```python
datas.append((src_gdal_data, tgt_gdal_data))
```

**Comment by giumas** [comment] 2015-09-26 00:25
Using `gdal 2.0.0`, it freezes but I get an error when I run the application. This is the full trace:

    PyInstaller Bootloader 3.x
    LOADER: executable is C:\zzzz\test_data\gdal\dist\minimal\minimal.exe
    LOADER: homepath is C:\zzzz\test_data\gdal\dist\minimal
    LOADER: _MEIPASS2 is NULL
    LOADER: archivename is C:\zzzz\test_data\gdal\dist\minimal\minimal.exe
    LOADER: No need to extract files to run; setting extractionpath to homepath
    LOADER: SetDllDirectory(C:\zzzz\test_data\gdal\dist\minimal)
    LOADER: Already in the child - running user's code.
    LOADER: Python library: C:\zzzz\test_data\gdal\dist\minimal\python27.dll
    LOADER: Loaded functions from Python library.
    LOADER: Manipulating environment (sys.path, sys.prefix)
    LOADER: sys.prefix is C:\zzzz\test_data\gdal\dist\minimal
    LOADER: Setting runtime options
    LOADER: Initializing python
    LOADER: Overriding Python's sys.path
    LOADER: Post-init sys.path is C:\zzzz\test_data\gdal\dist\minimal
    LOADER: Setting sys.argv
    LOADER: setting sys._MEIPASS
    LOADER: importing modules from CArchive
    LOADER: extracted struct
    LOADER: callfunction returned...
    LOADER: extracted pyimod01_os_path
    LOADER: callfunction returned...
    LOADER: extracted pyimod02_archive
    LOADER: callfunction returned...
    LOADER: extracted pyimod03_importers
    LOADER: callfunction returned...
    LOADER: Installing PYZ archive with Python modules.
    LOADER: PYZ archive: out00-PYZ.pyz
    LOADER: Running pyiboot01_bootstrap.py
    LOADER: Running pyiboot02_egg_install.py
    LOADER: Running pyi_rth__tkinter.py
    LOADER: Running pyi_rth_win32comgenpy.py
    LOADER: Running pyi_rth_pkgres.py
    LOADER: Running minimal.py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xxxx\appdata\local\yyyy\py2\lib\site-packages\PyInstaller-3.0.dev6+b7954b3-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "C:\Users\xxxx\AppData\Local\yyyy\py2\lib\site-packages\osr.py", line 2, in <module>
        from osgeo.gdal import deprecation_warn
      File "c:\users\xxxx\appdata\local\yyyy\py2\lib\site-packages\PyInstaller-3.0.dev6+b7954b3-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "C:\Users\xxxx\AppData\Local\yyyy\py2\lib\site-packages\osgeo\gdal.py", line 427, in <module>
        import ogr
      File "c:\users\xxxx\appdata\local\yyyy\py2\lib\site-packages\PyInstaller-3.0.dev6+b7954b3-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 313, in load_module
        exec(bytecode, module.__dict__)
      File "C:\Users\xxxx\AppData\Local\yyyy\py2\lib\site-packages\osgeo\ogr.py", line 251, in <module>
        _MyHelper(_Module())
      File "C:\Users\xxxx\AppData\Local\yyyy\py2\lib\site-packages\osgeo\ogr.py", line 219, in __init__
        self.original_help = help
    NameError: global name 'help' is not defined
    minimal returned -1
    LOADER: OK.
    LOADER: Cleaning up Python interpreter.

The code snippet causing the exception is the SWIG-generated `ogr.py`:


    # Custom help() replacement to display the help of the original module
    # instead of the one of our instance object
    class _MyHelper(object):
    
        def __init__(self, module):
            self.module = module
            self.original_help = help
    
            # Replace builtin help by ours
            try:
                import __builtin__ as builtins # Python 2
            except ImportError:
                import builtins # Python 3
            builtins.help = self

**Comment by giumas** [comment] 2015-09-26 02:54
So far, this is where I am with the `gdal` hook for vanilla and Anaconda `cpython` (tested also on Yosemite and Ubuntu):

    from PyInstaller.utils.hooks import collect_data_files
    from PyInstaller.compat import is_win, is_darwin
    
    import os
    import sys
    
    # The osgeo libraries require auxiliary data and may have hidden dependencies.
    # There are several possible configurations on how these libraries can be 
    # deployed.
    # This hook evaluates the cases when:
    # - the `data` folder is present "in-source" (sharing the same namespace folder
    #   as the code libraries)
    # - the `data` folder is present "out-source" (for instance, on Anaconda for 
    #   Windows, in PYTHONHOME/Library/data)
    # In this latter case, the hook also checks for the presence of `proj` library 
    # (e.g., on Windows in PYTHONHOME) for being added to the bundle.
    #
    # This hook has been tested with gdal (v.1.11.2 and 1.11.3) on:
    # - Win7 64bit
    # - Ubuntu 15.04 64bit
    # - Mac OS X Yosemite 10.10
    #
    # TODO: Fix for gdal>=2.0: 'NameError: global name 'help' is not defined'
    
    # flag used to identify an Anaconda environment
    is_conda = False
    
    # Auxiliary data:
    #
    # - general case (data in 'osgeo/data/gdal'):
    datas = collect_data_files('osgeo', subdir='data/gdal')
    
    # check if the data has been effectively found in 'osgeo/data/gdal'
    if len(datas) == 0:
    
        if hasattr(sys, 'real_prefix'):  # check if in a virtual environment
            root_path = sys.real_prefix
        else:
            root_path = sys.prefix
    
        # - conda-specific
        if is_win:
            tgt_gdal_data = os.path.join('Library', 'data')
            src_gdal_data = os.path.join(root_path, 'Library', 'data')
        else:  # both linux and darwin
            tgt_gdal_data = os.path.join('share', 'gdal')
            src_gdal_data = os.path.join(root_path, 'share', 'gdal')
            # TODO: need to add to the bundle something like:
            # "import os; os.environ['GDAL_DATA']='%s/share/gdal' % sys._MEIPASS"
            
        if os.path.exists(src_gdal_data):
            is_conda = True
            datas.append((src_gdal_data, tgt_gdal_data))
    
    # Hidden dependencies
    if is_conda:
        # if `proj.4` is present, it provides additional functionalities
        if is_win:
            proj4_lib = os.path.join(root_path, 'proj.dll')
        elif is_darwin:
            proj4_lib = os.path.join(root_path, 'lib', 'libproj.dylib')
        else:  # assumed linux-like settings
            proj4_lib = os.path.join(root_path, 'lib', 'libproj.so')
            
        if os.path.exists(proj4_lib):
            binaries = [(proj4_lib, ""), ]

@matysek: I have added another `TODO`. This is because I don't know how to add the creation of an os environ from the hook (`GDAL_DATA`). Is this currently possible without modifying the user code?

**Comment by matysek** [comment] 2015-09-26 07:59
> I have added another TODO. This is because I don't know how to add the creation of an os environ from the hook (GDAL_DATA). Is this currently possible without modifying the user code?

Yes, for this purpose there are runtime hooks. See:
* PyInstaller/loader/rthooks
* PyInstaller/loader/rthooks.dat

For example the matplotlib rthook does it too.

**Comment by giumas** [comment] 2015-09-26 20:33
> Using gdal 2.0.0, it freezes but I get an error when I run the application. 

@matysek , do you prefer to keep open this ticket for this issue related to `osgeo >=2.0` or to close it for opening an issue-specific ticket?

**Comment by matysek** [comment] 2015-09-26 20:41
@giumas let's this ticket open eve for >=2.0.

**Comment by giumas** [comment] 2016-01-11 04:22
I have just attempted to run a minimal file (``from osgeo import ogr``) with the current stable release (``3.1``), but I got the same issue:

```
PyInstaller Bootloader 3.x
LOADER: executable is C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal\minimal.exe
LOADER: homepath is C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal\minimal.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal\python34.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal\base_library.zip;C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal
LOADER: sys.prefix is C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal\base_library.zip;C:\_yyyyyy\zzz_test\gdal_freeze\dist\minimal
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_osgeo.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running minimal.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\users\xxxxx\appdata\local\hyo\py3\x64\envs\gdal20\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\ogr.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\users\xxxxx\appdata\local\hyo\py3\x64\envs\gdal20\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\osgeo\gdal.py", line 427, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\users\xxxxx\appdata\local\hyo\py3\x64\envs\gdal20\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\osgeo\ogr.py", line 251, in <module>
  File "site-packages\osgeo\ogr.py", line 219, in __init__
NameError: name 'help' is not defined
minimal returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.
```

Googling around, I have found this post from @rouault: http://erouault.blogspot.com/2014/11/hacking-python-module-constants.html that explains what was the reason to introduce the trick that is giving troubles to ``PyInstaller``.

Unluckily, the problem is not going to go away with more recent ``gdal`` release since this part of ``ogr.py`` is currently the same: https://github.com/OSGeo/gdal/blob/trunk/gdal/swig/python/osgeo/ogr.py#L222

Do you have any idea on why the frozen application fails stating that the builtin ``help`` is not defined?

**Comment by zhangliye** [comment] 2016-02-21 07:50
I have got the same issue:  "global name 'help' is not defined"
I use pyinstaller 3.1.1

**Comment by Guts** [comment] 2016-02-24 13:52
I've got the same issue working on my [DicoGIS](https://github.com/Guts/DicoGIS) project.
I reported it in the OSGeo tracker: https://trac.osgeo.org/gdal/ticket/6364

**Comment by giumas** [comment] 2016-02-24 16:33
This should be finally fixed with the release of GDAL 2.0.3: https://trac.osgeo.org/gdal/ticket/6364

**Comment by VeroL** [comment] 2016-07-26 16:49
Using GDAL 2.1.1 , pyinstaller 3.2 , Python 3.5.2 :: Anaconda 4.1.1 (64-bit) , windows 7

I get an import error when running .exe files bundled from scripts that import gdal.

Testing from the following 1 line script:
`from osgeo import gdal`

Then compiling: 
`pyinstaller.exe --onefile  --debug softest6.py`

Then when running the resulting softest6.exe running  get this error:

`Traceback (most recent call last):`
  `File "site-packages\osgeo\__init__.py", line 15, in swig_import_helper`
  `File "imp.py", line 296, in find_module`
`ImportError: No module named '_gdal'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
  `File "softest6.py", line 8, in <module>`
  `File "c:\users\v\appdata\local\continuum\anaconda3\lib\site-packages\Py
Installer\loader\pyimod03_importers.py", line 389, in load_module`
   `exec(bytecode, module.__dict__)`
  `File "site-packages\osgeo\__init__.py", line 25, in <module>`
  `File "site-packages\osgeo\__init__.py", line 17, in swig_import_helper`
`ImportError: No module named '_gdal'`
`Failed to execute script softest6`






But there is a file '_gdal.py' in folder site-packages\osgeo\

Any idea why this is happening and if it is fixable?
I have installed gdal like this:
`conda install -c conda-forge gdal=2.1.1`

thanks

**Comment by htgoebel** [comment] 2016-07-27 08:48
Look like you need to update the hook for osgeo to include `_gdal`. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about how to implement hooks.

**Comment by VeroL** [comment] 2016-07-27 21:22
Thanks for your reply.

The problem is with the file `__init__.py` , stored in `Anaconda3\Lib\site-packages\osgeo`
The 2 operations of this code are to grab the gdal version then make the osgeo version the same.

`__init__.py` imports `_gdal.py` which then accesses `_gdal.cp35-win_amd64.pyd`, and both files are stored in `Anaconda3\Lib\site-packages\osgeo`

if i comment out these operations in `__init__.py` and instead write
`__version__ = '1.11.4'`
and recompile, the resulting executable (using several gdal functions) runs just fine.

but i couldn't get it to work by importing _gdal in my code or using hidden imports.

also I've noticed that the hook-osgeo.py adds `/Library/data` to the path for anaconda windows, but i don't have a `data` folder in my `Anaconda3\Library` folder.

Please let me know if you have any ideas, I'm happy to try and fix this if it can help others, 
Otherwise since the problem seems to only come from grabbing the gdal version it doesn't bother me to just hardcode it in osgeo for now.

[today using GDAL 1.11.4, pyinstaller 3.2 , Python 3.5.1 :: Anaconda 4.0.0 (64-bit), win10]

**Comment by giumas** [comment] 2016-07-28 01:39
@VeroL I contributed to the current `gdal` hook, and I am interested in helping you to update the hook (if required).

> also I've noticed that the hook-osgeo.py adds /Library/data to the path for anaconda windows, but i don't have a data folder in my Anaconda3\Library folder.

This is due to the fact that the various Anaconda packagers put these files in different locations. Which Anaconda channel are you using? Correct me if I am wrong, but `gdal` is not listed in the official repo (for Python 3.5): https://anaconda.org/anaconda/gdal/files

BTW, I can re-create what you describe mimicking similar settings as yours (with the `data` folder is in `Library\share\gdal`) using the wheel from the `IOOS` channel. But, with Python 3.4 and 2.7, I have the data files in `Library\data`. This part of the problem should be easy to fix (we can just test about the existence of one of the two paths). 

The other issue is finding the shared library (*.pyd). If you are using the above `IOOS` custom package, the shared library is named `_gdal.cp35-win_amd64.pyd` (not `_gdal` as it was in the other installations). This filename is hard-coded in the `_gdal.py`: 

````
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources, imp
    __file__ = pkg_resources.resource_filename(__name__, '_gdal.cp35-win_amd64.pyd')
    __loader__ = None; del __bootstrap__, __loader__
    imp.load_dynamic(__name__,__file__)
__bootstrap__()
```

As you can see, there is very little here to blame `PyInstaller` for not being able to find all the required components, since they are not standard.

@htgoebel : do you have any suggesting on how to fix the second issue? I don't think that hard coding all the possible naming combinations is the best way to go.

**Comment by codewarrior0** [comment] 2016-07-28 01:45
> I don't think that hard coding all the possible naming combinations is the best way to go.

Isn't the tagged .pyd suffix available from `imp.get_suffixes()`?

```
>>> imp.get_suffixes()
[('.cp35-win_amd64.pyd', 'rb', 3), ('.pyd', 'rb', 3), ('.py', 'r', 1), ('.pyw', 'r', 1), ('.pyc', 'rb', 2)]
```

**Comment by giumas** [comment] 2016-07-28 02:49
> Isn't the tagged .pyd suffix available from imp.get_suffixes()?

Yes, it is. I was not aware of that! 

Are you suggesting to use the `C_EXTENSION` to look at the possible names of the `.pyd`?

**Comment by VeroL** [comment] 2016-07-28 20:36
Thanks @giumas for your help, greatly appreciated!
I work on 2 machines (attempting to compile/package my code that uses gdal on both machines):

Machine 1: windows 7 |  Python 3.5.2 :: Anaconda 4.1.1 (64-bit) | PyInstaller 3.2
Using GDAL 2.1.1 ,  installed by running
`conda install -c conda-forge gdal=2.1.1 `
https://anaconda.org/conda-forge/gdal (newest version I could find 2 days ago)

Machine 2: windows 10 | Python 3.5.1 :: Anaconda 4.0.0 (64-bit)  | PyInstaller 3.2
Using GDAL 1.11.4 , probably installed when I installed geopandas like this:
`conda install -c ioos geopandas`
(or `fiona`, not sure sorry)

I get the same runtime error on both machines: 
`ImportError: No module named '_gdal'`
On both machines the files `__init__.py`, `_gdal.py` and `_gdal.cp35-win_amd64.pyd` seem identical and are located in `Anaconda3\Lib\site-packages\osgeo`
And both machines have a `Library\share\gdal` folder 


Hope this helps, I absolutely understand that pyinstaller cannot be blamed for this, and I'm happy to help testing if required, 
thank you for your efforts.

**Comment by giumas** [comment] 2016-07-29 01:42
> I'm happy to help testing if required, 

@VeroL : I am afraid that you quite misunderstood my words! I wrote that "I am interested in helping you to update the hook". Actually, I don't currently need to freeze GDAL on Anaconda's Python 3.5. 
To be more clear, if **you** prepare the PR and the minimal example, **I** will be glad to test the updated hook in the configurations that I am currently using.

**Comment by VeroL** [comment] 2016-07-29 16:03
@giumas, I'm sorry, I did misunderstand, my apologies. I am trying to fix this, but I don't know much about compiling and I am very new to python (<2months).

The minimal example I am using is:
`from osgeo import gdal`
(just this line).

I recompiled it using the --onedir option, and the file  `_gdal.cp35-win_amd64.pyd` is there alongside the .exe in the directory created by pyinstaller. However the ImportError at runtime still occurs (error copied in my first post). So pyinstaller copies the file but then the executable cannot use it?

I also tested with another configuration: Python 3.4.5 |Anaconda  4.0.0
I installed python 3.4.5 as a conda environment, and reinstalled all modules including pyinstaller and gdal in this python 3.4 environment. 
gdal was installed like this:
`conda install -c ioos gdal=1.11.4`

With this configuration there is a `_gdal.pyd` in `site-packages\osgeo`, and no `_gdal.py` or `_gdal.cp35-win_amd64.pyd` (but there is a `gdal.py` for both configurations). 
However the same ImportError for `__init__.py` occurs (error copied in my first post), and in the executable folder there is no `_gdal.pyd`.
I was wondering if it could be related to this issue: https://github.com/pyinstaller/pyinstaller/issues/1919
Where a module imports a sub module from itself. (except i tried adding `from osgeo import _gal` or `import osgeo._gdal` in the test code but it does not help)

Also, still no `data` folder in `Library` for this configuration (Python 3.4.5 |Anaconda  4.0.0), but 'Library\share\gdal` as with Python 3.5.1. -but not sure if this is a problem.

-- I will try to modify the hook, please let me know if you have anymore tips or ideas of things to test. Thanks!
[in the meantime, commenting out `osgeo/__init__.py` works]

**Comment by minorsecond** [comment] 2016-08-08 23:48
@VeroL you said 

> [in the meantime, commenting out osgeo/__init__.py works]

Is that all you did? I've been trying to figure this out for days. I just want to get this straight. You went to the __init__.py file and commented out all of the lines?

**Comment by VeroL** [comment] 2016-08-09 11:06
@minorsecond 
yes, the file `site-packages\osgeo\__init__.py` only sets the version of the osgeo package to be the same as the gdal version (see my 2nd comment in this thread).
The problem when compiling is the way `__init__.py` accesses/reads the gdal version (and i still don't understand why).
So i commented out everything in `site-packages\osgeo\__init__.py` and replaced by `__version__ = 'my_gdal_version_number'`, e.g. `__version__ = '1.11.4'` (after checking my gdal version number in python, although this may not matter).

`__init__.py` triggered the runtime error `ImportError: No module named '_gdal'` in all 3 following configurations for me, and its modification got rid of the error in all 3 configurations:
GDAL 2.1.1 , pyinstaller 3.2 , Python 3.5.2 :: Anaconda 4.1.1 (64-bit) , windows 7
GDAL 1.11.4, pyinstaller 3.2 , Python 3.5.1 :: Anaconda 4.0.0 (64-bit), windows 10
GDAL 1.11.4, pyinstaller 3.2 , Python 3.4.5 |Anaconda 4.0.0 (virutal env.), windows 10

still no real fix, but hope this helps!

**Comment by Guts** [comment] 2016-08-25 17:18
Found out this blog post which could help: https://umrysh.com/getting-gdal-2-to-play-nice-with-python-on-windows/

**Comment by davidh-ssec** [comment] 2016-09-23 17:22
So I've been playing around with this with Anaconda, python 3.4, and gdal/libgdal 2.0.0. I did what @VeroL suggested with modifying the `__version__` stuff in `__init__.py`. I still got the error for missing `_gdal.so` so I copied the `osgeo/_gdal.cpython-34m.so` file to `dist/<proj>/` and made a link `_gdal.so -> _gdal.cpython-34m.so`. I then got the `help` error message. So I modified `osgeo/ogr.py` and commented out the line here `#_MyHelper(_Module())`. After rebuilding with pyinstaller, doing the `_gdal.so` copy and linking (yes this could be one step probably) I get a working executable.

So I'd say this is the next step in the ugliest work around pyinstaller has had in a while.

**Comment by davidh-ssec** [comment] 2016-09-23 17:31
I think the main `help` issue is that I'm guessing pyinstallers bootloader removes the `help` builtin somehow? Anyone know more on this?

**Comment by davidh-ssec** [comment] 2016-09-23 20:00
I have done some research and I guess `help` is only used in the interactive sense. I'll see if I can find a pyinstaller way around this.

**Comment by giumas** [comment] 2016-09-26 02:44
@davidh-ssec the `help` issue should be fixed after gdal 2.03 as I wrote here: https://github.com/pyinstaller/pyinstaller/issues/1522#issuecomment-188341551

**Comment by giumas** [comment] 2017-04-02 01:53
On Python 3.6 and Win10, using the latest development (https://github.com/pyinstaller/pyinstaller/commit/483dfdebad65679ded59476514c9a5528c4ba3b6), the frozen app misses '_gdal.pyd', but it has all the other required pyd (e.g., '_gdal_array.pyd') and DLLs. 

If I manually copy that pyd, it works fine. Any hint on what is going on? (GDAL is Swig based)

**Comment by davidh-ssec** [comment] 2017-04-05 00:40
@giumas It's been a while since I've looked at this, but I'm guessing this would be the same library problem (_gdal.so) that this issue addresses, but with the Windows version of what the gdal library produces (_gdal.pyd). What version of GDAL are you trying to freeze?

**Comment by giumas** [comment] 2017-04-05 01:17
@davidh-ssec the current latest conda-forge package: 2.1.3

**Comment by giumas** [comment] 2017-04-05 01:24
@codewarrior0 I believe that I understood when this issue happens. It is when there is a *,py and a *.pyd file with the same basename (_gdal.py and _gdal.cp36-win_amd64.pyd). I am not sure whether having this situation is bad practice, and what is the import priority between py and pyd files. 

However, I have followed your suggestion, and if I modify the osgeo hook, it works (the hack is at the end):

```
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.compat import is_win, is_darwin

import os
import sys

# flag used to identify an Anaconda environment
is_conda = False

# Auxiliary data:
#
# - general case (data in 'osgeo/data/gdal'):
datas = collect_data_files('osgeo', subdir=os.path.join('data', 'gdal'))

# check if the data has been effectively found in 'osgeo/data/gdal'
if len(datas) == 0:

    if hasattr(sys, 'real_prefix'):  # check if in a virtual environment
        root_path = sys.real_prefix
    else:
        root_path = sys.prefix

    # - conda-specific
    if is_win:
        tgt_gdal_data = os.path.join('Library', 'share', 'gdal')
        src_gdal_data = os.path.join(root_path, 'Library', 'share', 'gdal')
        if not os.path.exists(src_gdal_data):
            tgt_gdal_data = os.path.join('Library', 'data')
            src_gdal_data = os.path.join(root_path, 'Library', 'data')

    else:  # both linux and darwin
        tgt_gdal_data = os.path.join('share', 'gdal')
        src_gdal_data = os.path.join(root_path, 'share', 'gdal')

    if os.path.exists(src_gdal_data):
        is_conda = True
        datas.append((src_gdal_data, tgt_gdal_data))
        # a real-time hook takes case to define the path for `GDAL_DATA`

# Hidden dependencies
if is_conda:

    # if `proj.4` is present, it provides additional functionalities
    if is_win:
        proj4_lib = os.path.join(root_path, 'proj.dll')
    elif is_darwin:
        proj4_lib = os.path.join(root_path, 'lib', 'libproj.dylib')
    else:  # assumed linux-like settings
        proj4_lib = os.path.join(root_path, 'lib', 'libproj.so')

    if os.path.exists(proj4_lib):
        binaries = [(proj4_lib, ""), ]

    # hack if `_gdal.py` and '_gdal.xxx.pyd' are both present  |||| <<---------------[[
    from osgeo import gdal
    from imp import get_suffixes
    gdal_folder = os.path.abspath(os.path.dirname(gdal.__file__))
    for suffix in get_suffixes():
        if suffix[2] == 3:  # C_EXTENSION
            gdal_pyd_path = os.path.join(gdal_folder, '_gdal%s' % suffix[0])
            if os.path.exists(gdal_pyd_path):
                binaries = [(gdal_pyd_path, ""), ]
```

I am not sure that this is the right. For instance, it does not prune the 'cp36-win_amd64' part from the pyd filename as it happens to the other pyd files.

Let me know what you think about!

**Comment by davidh-ssec** [comment] 2017-04-05 01:36
@giumas iirc the `cp36-win_amd64` part is just for documentation and is generally ignored by shared library importers...I think.

**Comment by giumas** [comment] 2017-04-05 01:48
@davidh-ssec The above hack checks for the existence of all possible C extensions for `_gdal`. So it should be safe from this point of view. The issue is what happen if PyInstaller starts to detect again the pyd file and we end up with duplicated pyd file with different names?

I believe that the real issue to investigate is the reason of this behavior. The content of the `py` files is almost identical in `_gdal.py` and, for instance, `_ogr.py` (but this latter is correctly packaged by PyInstaller):

![notepad _2017-04-04_21-46-35](https://cloud.githubusercontent.com/assets/2849257/24686180/28e354ea-1980-11e7-945d-d7cef8e023ab.png)

![notepad _2017-04-04_21-46-42](https://cloud.githubusercontent.com/assets/2849257/24686183/2ba203e8-1980-11e7-8cab-1e1264eaecc7.png)

**Comment by giumas** [comment] 2017-04-05 01:54
BTW, the minimal example to reproduce the issue is just:

```
from osgeo import gdal
```

**Comment by davidh-ssec** [comment] 2017-04-26 02:15
@giumas I've looked in to this a little more, specifically why does `_gdal_array.so` work fine, but `_gdal.so` not. I haven't found a way to fix it beyond your above hack but one thing I did fine was:

https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/modulegraph.py#L2297

This handles SWIG generated modules specially including renaming things like `osgeo._gdal_array.so` to `_gdal_array.so`. You will find the "automatically generated by SWIG" in the `osgeo/gdal_array.py` but *not* in the `osgeo/__init__.py` module. I think this is the main reason why the `_gdal` import is not handled correctly, but I don't see an easy solution to this besides special casing the `_gdal.so` in the hook.

**Comment by davidh-ssec** [comment] 2017-04-26 14:48
@giumas and others Ok now I actually figured it out, but I'm still not sure the best way to fix it. Test file `test.py`:

    from osgeo import gdal

Run with `pyinstaller -y -d --clean test.py` will perform the following operations:

1. Find the `from osgeo import gdal`
2. Try to import `osgeo` which is actually `osgeo/__init__.py`
3. Find the `import _gdal` import and try to import it.
4. Fail (ImportError) and get to this line: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/modulegraph.py#L2275
5. Due to the import being from `osgeo/__init__.py` and not `osgeo/gdal.py` the above mentioned line of code doesn't resolve to `True` so the `_gdal` module not seen as a SWIG generated module. This results in a `MissingModule` node being added to the import graph here: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/modulegraph.py#L2321
6. As import analysis continues we get to `osgeo/gdal.py`.
7. Find `import _gdal` import and try to import it.
8. See that we've already tried to import `_gdal` and failed so we don't raise an ImportError, we just have the `MissingModule` node. No ImportError means never falling in to the "check if this is SWIG" check so the module never gets included.

My hacky fix for this specific use and test was to add the following at line 2321:

    if target_module_partname == "_gdal" and target_modules is None:
        target_modules = [None]
    elif target_modules is None:

This works but is obviously not flexible or generic in any way.

**Closed** 2017-09-07 10:04 UTC
Labels: @low, hooks, Windows

**Comment by awa5114** [comment] 2019-10-10 14:45
Has this been implemented? I still get errors like:

> ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
> Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
> 

When running my executable.

**Comment by djhoese** [comment] 2019-10-10 20:26
@awa5114 This is a pretty old issue that has been closed for a while. I would suggest making a new issue (you can even tag me if you'd like) and include your operating system, what version of GDAL you have, what version of pyinstaller, what type of python environment you are using (conda, system python, etc), what version of python, etc.

I would assume that newer versions of GDAL do not have these issues. As far as I know GDAL is going away from separate EPSG CSV files. Otherwise, as a last resort, you may need to submit a pull request to fix your issue or specify the `GDAL_DATA` environment variable yourself in your python script that you are bundling.
