### ISSUE TITLE
GTK3 msys2 ModuleNotFoundError: No module named '_struct'

### ISSUE THREAD

**Issue by jrezai** [pyinstaller/pyinstaller#4125] opened 2019-03-14 18:46 UTC
The official way to install GTK3 on Windows is to use msys2  ([www.msys2.org](url)).
I followed the instructions on [gtk.org](https://www.gtk.org/download/windows.php) which explains how to install GTK3 using msys2.

I managed to install and configure msys2 successfully and my Python script runs successfully using msys2 - on Windows 10 64-bit.

Now I want to package my Python script, so I can send it to others:
I've used PyInstaller to generate an .exe (on Windows 10 64-bit), using the msys2 terminal, but when I attempt to run my program's .exe (generated by PyInstaller), I get the following error, and my program doesn't run:

```
[8476] mod is NULL - structTraceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.7/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
[8476] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.7/site-packages/pyinstaller-3.5.dev0+8c27d2668-py3.7.egg/PyInstaller/loader/pyimod02_archive.py", line 28, in <module>
    import struct
ModuleNotFoundError: No module named 'struct'
[8476] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.7/site-packages/pyinstaller-3.5.dev0+8c27d2668-py3.7.egg/PyInstaller/loader/pyimod03_importers.py", line 24, in <module>
    from pyimod02_archive import ArchiveReadError, ZlibArchiveReader
ModuleNotFoundError: No module named 'pyimod02_archive'
Traceback (most recent call last):
  File "site-packages/pyinstaller-3.5.dev0+8c27d2668-py3.7.egg/PyInstaller/loader/pyiboot01_bootstrap.py", line 15, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[8476] Failed to execute script pyiboot01_bootstrap
```

Any ideas?

Thank you.

**Comment by PippoGC** [comment] 2019-03-23 09:32
Hi there,

I am facing the same problem using the same environment; currently running python 3.7.2 with Eclipse 4.9. I have also tried to isolate the problem by removing all references to GTK3 by creating a simple python script that just prints a string.  Here the results:
1/ with the option --onefile, it works
2/ with the option --onedir does not work and generate the above traceback.

BTW, this traceback is same as the one reported in https://github.com/pyinstaller/pyinstaller/issues/4027 [ModuleNotFoundError: No module named '_struct'] ; Not sure why this thread is set as closed since I cannot find how it was addressed

Thank you !

**Comment by jrezai** [comment] 2019-03-27 00:18
I ended up using both PyInstaller and cx_Freeze to make my program work. I haven't done full testing yet, but my script runs with the generated .exe that cx_Freeze made.

I used PyInstaller to find the dependencies that my Python script needed, and then I used cx_Freeze to generate the final .exe. It would be easier if PyInstaller could be used alone to generate the final .exe package (without the _struct traceback), instead of using two separate tools.

**Comment by sirDeniel** [comment] 2019-04-26 19:06
@jrezai @PippoGC I would like to make some "documentation" of the steps you made to get that executable. I got some kind of distributable and published it on this [repository](https://bitbucket.org/sirdeniel/deploy-python-gtk3-apps-for-windows/src) but I don't consider as a real solution. We can create some repo with examples and anyone can join to add experience. Greetings.

**Comment by mitras2** [comment] 2019-04-29 15:34
I can confirm this is a problem.
I can give logs and files on request.

It would be great if this issue could be solved, becaus it basically breaks building GTK3 applications im Windows (MSYS)

**Comment by gpraceman** [comment] 2019-05-16 23:20
I am facing the same error.  Python 3.7.3 x86 environment on MSYS2 and on Windows 10 x64.

**Comment by gpraceman** [comment] 2019-06-05 15:47
I even tried using the latest dev package (as of yesterday) and still get this same error on two fresh Windows 10 x64 and Python 3.7 environments.

An unusual thing I see in the dist folder is a "_struct-cpython-37m" folder, which contains a single DLL file, named "dllruct-cpython-37m.dll".  If I change the name of that file to "_struct-cpython-37m.dll" and copy it to the root dist folder, I no longer get the "No module named '_struct'" error.  Now I get a "No module named 'zlib'" error.  Then I notice that there is a "zlib-cpython-37m" folder with a single file named "dllb-cpython-37m.dll" in it.  So, I change its name to "zlib-cpython-37m.dll" and copy it to the root dist folder.  No more zlib error.  Now I get a "zlib.error: Error -3 while decompressing data: incorrect header check".

Hopefully, this information will help.  It sure seems that something is fouled up with how things are getting packaged.

**Comment by gpraceman** [comment] 2019-06-18 21:24
I implemented the proposed changes from @springermac, along with the proposed edits by @htgoebel and that resolved that error for me.  I was now able to get my Gtk3+ app packaged up.

However, when running the app, I ended up with a "No module named 'packaging.specifiers'" error.  To fix that, I edited the site-packages/pkg_resources/__init__.py file, lines 89-92, and changed the __import__()'s to regular import statements.  Now my Gtk3 app will run.  Huge relief.

**Comment by danyeaw** [comment] 2019-08-10 01:08
So using the latest version of the develop branch, I am still getting this error when using msys2 with mingw64 and import pkg_resources. I do not get these errors when testing with the offical Python in Windows 10. To fix this in msys2, I can run `pyinstaller --hidden-import _struct`. Is this an appropriate fix for this, to add the hidden import for pkg_resources using a hook?

**Comment by gpraceman** [comment] 2019-08-10 22:27
@danyeaw This is not yet implemented into the Dev branch.  I couldn't wait, so I downloaded the source code and implemented the proposed changes.  That fixed my packaging issue with MSYS2.

**Comment by danyeaw** [comment] 2019-08-11 11:35
@gpraceman Your changes in #4240 don't work for me when applied to the develop branch.

**Comment by gpraceman** [comment] 2019-08-12 01:28
@danyeaw Technically, they aren't my changes.  I just took the changes that @springermac proposed, along with the proposed edits by @htgoebel and applied those to the dev code.

**Comment by danyeaw** [comment] 2019-08-12 02:37
@gpraceman Sorry I wasn't trying to blame you that it wasn't working. 😀 I appreciate that you made a PR with the suggested changes of others, I am just trying to figure out a working fix we can get in the develop branch now.

**Comment by kakyoism** [comment] 2019-08-21 10:51
@danyeaw Do you still have this issue with the latest pyinstaller? I downloaded and built the latest package for msys2, and the _struct error is still there.

**Comment by kakyoism** [comment] 2019-08-21 12:35
I now have a better idea what might be the cause: PyInstaller was installed to the `mingw64/bin/python` instead of `/usr/bin/python`. When I tried to install pyinstaller for msys2, I got an error:

```
$ pip install pyinstaller
Your platform is not yet supported. Please define constant PYDYLIB_NAMES for your platform.
```
Then I followed [this post](https://stackoverflow.com/questions/54728231/how-to-fix-pyinstaller-in-msys2-mingw-your-platform-is-not-yet-supported) to build through setuptool.

Then it still failed:
```
$ /usr/bin/python setup.py install
Your platform is not yet supported. Please define constant PYDYLIB_NAMES for your platform.

```
It could only succeed when you use

```
$ /mingw64/bin/python setup.py install
```

The official pygobject guide says we install GTK+ this way:
```
pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-gobject
```

So all the packages that the app uses are in a different python world. 
I don't understand why msys organizes things this way, but it's a mess for pyinstaller to work.

The correct way is probably fix the installer for pyinstaller for msys /usr/lib/python.

**Comment by danyeaw** [comment] 2019-08-22 00:26
@kakyoism Yes, I still have this issue when using pkg_resources

**Comment by danyeaw** [comment] 2019-09-05 01:43
My previous issues I had with #4240 were caused with a separate issue with my pathex in my spec. Sorry for the confusion. Thanks to the efforts from @springermac and @gpraceman for trying to resolve this, and for @jrezai for reporting the initial issue. I have created #4417 to hopefully get resolving this issue over the finish line. 👍

**Closed** 2019-11-08 16:36 UTC
