### ISSUE TITLE
RunTimeError <path> is not a valid CArchive file in pyi-archive_viewer

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1272] opened 2015-05-15 18:38 UTC
Encountered this on windows after patching the issue #1270.

pyi_carchive.py #161: `MAGIC = b'MEI\014\013\012\013\016'
pyi_carchive.py #252ff,

        (magic, totallen, tocpos, toclen, pyvers, pylib_name) = struct.unpack(
                self._cookie_format, self.lib.read(self._cookie_size))
        if magic != self.MAGIC:
            raise RuntimeError("%s is not a valid %s archive file" %
                    (self.path, self.__class__.__name__))

Tracing this, I see that on the initial open of APPNAME.exe, the returned value is the expected one. However the next time it is called, in the course of executing `o out00-PYZ.pyz`, the comparison is to `b'\000\000\218\008\117\110\105\116'`, not the same at all. So not a byte/str problem, but some issue unpacking a nested archive.

Note I verify this occurs on both Windows and Mac OS.

**Comment by tallforasmurf** [comment] 2015-05-15 18:50
I observe the following code at pyi_archive.py line 87,

            if sys.version_info[1] <= 3:
                # We cannot use at this bootstrap stage importlib directly
                # but its frozen variant.
                self.pymagic = _frozen_importlib._MAGIC_BYTES
            else:
                self.pymagic = _frozen_importlib.MAGIC_NUMBER

The "else" would only be executed in Python 3.4 and up. I am running 3.4. This might explain why I am seeing this issue and nobody else has reported it.

**Comment by htgoebel** [comment] 2015-05-19 16:56
I did some work in this area. Now I have the same error in the development branch, so I assume, this has a different reason.

**Comment by htgoebel** [comment] 2015-05-19 19:07
This should now be fixed, see 32478d98. I assume this was caused by the same thing which I fixed in ae556b9 in develop: The fall-back did not work correctly. (Although in python3-branch there was no change before. Strange, but don't mind any longer.)

**Closed by htgoebel** 2015-05-19 19:07 UTC
