### ISSUE TITLE
time.sleep() is not working correctly

### ISSUE THREAD

**Issue by MothScientist** [pyinstaller/pyinstaller#8104] opened 2023-11-14 09:27 UTC
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.1.0```
* Version of Python: ```3.9.0```
* Platform: ```Windows (RU)```
* How you installed Python: ```python.org/downloads```
* Did you also try this on another platform? ```No```

### A minimal example program which shows the error

```
import time

def main_sleep_test_example():
    print("Sleep test example")
    while True:
        print("Sleeping...")
        time.sleep(3)
        print("Wake up!")


if __name__ == '__main__':
    main_sleep_test_example()
```

```pyinstaller --noconfirm --onefile --console "path/to/file.py"```

### Stacktrace / full error message

When running an application through a Python file (.py), the time.sleep(x) command works fine, but after compiling through pyinstaller, it happens that no time.sleep(x) is triggered and the program runs straight through without the necessary stops

**Comment by rokm** [comment] 2023-11-14 10:59
Hmmm, indeed. But only with python 3.9.0 - they seem to have fixed it in 3.9.1.

It's likely this issue: https://bugs.python.org/issue41686

I'd close this as not-our-bug, but the problem is that it seems to work with PyInstaller 5.13.2 + python 3.9.0, so this is also likely related to our transition to the new python config & initialization API.

**Closed as completed** 2023-11-14 18:38 UTC
Labels: bug
