### ISSUE TITLE
Pyomo packaging issue

### ISSUE THREAD

**Issue by 4d4tt4** [pyinstaller/pyinstaller#3672] opened 2018-08-06 17:09 UTC
C:\>program.exe
Traceback (most recent call last):
  File "program.py", line 8, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\pyomo\pysp\__init__.py", line 25, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\pyomo\pysp\scenariotree\__init__.py", line 12, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\pyomo\pysp\scenariotree\tree_structure_model.py", line 18, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\networkx\__init__.py", line 114, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\networkx\generators\__init__.py", line 13, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\networkx\generators\geometric.py", line 27, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\scipy\spatial\__init__.py", line 96, in <module>
  File "c:\users\userABC~1\appdata\local\temp\pip-install-twllio\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 687, in load_module
  File "qhull.pyx", line 230, in init scipy.spatial.qhull
AttributeError: type object 'scipy.spatial.qhull._Qhull' has no attribute '__reduce_cython__'
[1316] Failed to execute script program

Hi, I am getting above error when packaging pyomo based application with pyinstaller,
earlier i was getting error because of hidden imports but then i manually imported every package hidden in __init__ pyomo environment 
please have a look.

**Comment by htgoebel** [comment] 2018-08-07 10:42
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.
Also fix the markup in your comment. Thanks

**Comment by htgoebel** [comment] 2019-01-23 09:23
No new infos since several months, closing.

**Closed by htgoebel** 2019-01-23 09:23 UTC
Labels: need info
