### ISSUE TITLE
print() in a --nowindow with Python 3.7.3 and 3.7.4 results in TypeError in tempfile.py

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#4437] opened 2019-09-18 17:56 UTC
Traceback (most recent call last):
  File "brokerw.py", line 2583, in run
  File "brokerw.py", line 547, in _ensure_wcomm_connected
  File "c:\python37\lib\tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

made using latest pyinstaller dev version
pyinstaller --onefile --nowindow brokerw.py

On py 2.7 it would at least output to a temporary buffer and lock up once that was full. Here we just get a crash we can't catch or do anything about.

**Comment by LipillaiDave** [comment] 2019-09-18 17:56
The line in question is

print('yo')

**Comment by amifunny** [comment] 2020-08-17 15:11
@ghost Could not reproduce your error and not much info is provided. Closing the issue. Reopen if you still face the issue.

**Closed by amifunny** 2020-08-17 15:11 UTC
Labels: state:need info
