### ISSUE TITLE
Error Loading Python DLL when using 2.1.1dev-32bbb95 and --onefile for Windows .exe

### ISSUE THREAD

**Issue by mgeorgy** [pyinstaller/pyinstaller#1291] opened 2015-06-06 20:51 UTC
I'm not sure if perhaps something has changed with the --onefile option, but I recently cloned the latest report (2.1.1dev-32bbb95) and realized that all .exe's created reported: 

Error loading Python DLL: C:\Users\USER\AppData\Local\Temp\_MEI16922\python2
7.dll (error code 14001)

I used a previous version of pyinstaller (2.1.1dev-67610f2) and am no longer seeing the error.  Nothing else was changed.

**Comment by codewarrior0** [comment] 2015-06-07 02:54
This might be my fault. Error code 14001 is "side-by-side configuration is incorrect".

Could you do the following to get info about what the side-by-side loader is doing?

- Open an administrator command prompt
- Run the command `sxstrace trace -logfile:trace.out` to begin tracing.
- Launch the pyinstaller created .exe
- Press ENTER in the command prompt
- Run the command `sxstrace parse -logfile:trace.out -outfile:trace.txt && start trace.txt`
- trace.txt should open up. Paste it here or on gist so I can look at it.

**Comment by codewarrior0** [comment] 2015-06-07 02:58
Also, could you run pyinstaller with the `-d` option to generate the exe? That will make the exe output some debug info which could be useful.

**Comment by psi29a** [comment] 2015-07-09 11:46
I had the same problem, I solved it by going back to the 67610f2 revision.

**Comment by psi29a** [comment] 2015-07-09 12:37
I checkout the tip of the develop branch, I created the binary the same way. The output doesn't give us much:
<snip>
LOADER: _MEIPASS2 is NULL
<snip>
LOADER: _MEIPASS2 is C:/Users/Blah/AppData/Local/Temp\_MEI58602\
LOADER: archivename is c:\WORKSP~1\WORLDE~1\dist\worldengine.exe
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:/Users/Blah/AppData/Local/Temp\_MEI58602\worldengine.exe.manifestpath
LOADER: Error activating the context
LOADER: Pythin library: C:/Users/Blah/AppData/Local/Temp\_MEI58602\python27.dll
Error loading Python DLL: C:/Users/Blah/AppData/Local/Temp\_MEI58602\python27.dll (error code 14001)
LOADER: Deactivating activation context
LOADER: Releasing activation context
LOADER: Done
LOADER: Back to parent
LOADER: Doing cleanup
LOADER: Freeing archive status for c:\WORKSP~1\WORLDE~1\dist\worldengine.exe

**Comment by matysek** [comment] 2015-08-03 15:44
@psi29a Do you have any code example to reproduce this issue?

**Comment by psi29a** [comment] 2015-08-03 15:53
Certainly: https://github.com/Mindwerks/worldengine  :D

**Comment by matysek** [comment] 2015-08-03 16:03
Any shorter piece of code?

**Comment by codewarrior0** [comment] 2015-08-15 17:25
Can you provide the Side-By-Side error information [as described here?](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#errors-specific-to-windows)

**Comment by xulai1001** [comment] 2015-09-06 03:42
confirmed when using current HEAD (July 29, 9d0e0ad ), still got error 14001 with 64-bit os & python
(I was packaging a tiny django site)
When I rollback to 67610f2 revision, however, the #1067 problem ( cannot merge list with str) occured.

**Comment by codewarrior0** [comment] 2015-09-06 03:47
Python version? Side-By-Side error information?

**Comment by codewarrior0** [comment] 2015-09-13 01:28
Try again with the latest `python3` branch. I've just fixed a lot of problems related to assembly versions and manifest dependencies. I'm still waiting for more detailed info about the SxS error: [this wiki page](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#errors-specific-to-windows) describes how to get that info.

**Comment by codewarrior0** [comment] 2015-09-13 01:30
@psi29a I noticed you're using GDAL. A SxS error related to GDAL was reported in #1376, and I'm confident that error is fixed now.

**Comment by psi29a** [comment] 2015-09-13 06:29
GDAL was only recently added (in master/trunk, not yet tagged and released), my problem with pyinstaller on windows was months before this (in our 0.18 release).

**Comment by jonnojohnson** [comment] 2015-09-15 21:21
I'm having the same issue using 2.1.1.dev0 checked out today.
I'm using Python 2.7.10 (64) via Anaconda on a WIn7 platform. I get this error when running the .exe on the same platform.

I followed the instructions above to get the trace.txt and get:
````
=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\marnj\AppData\Local\Temp\_MEI179242\InfiniiumPhaseNoise.exe.manifest
	AssemblyDirectory = C:\Users\marnj\AppData\Local\Temp\_MEI179242\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\marnj\AppData\Local\Temp\_MEI179242\InfiniiumPhaseNoise.exe.manifest.
	INFO: Manifest Definition Identity is InfiniiumPhaseNoise,processorArchitecture="amd64",type="win32",version="1.0.0.0".
	INFO: Reference: Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8"
	INFO: Reference: Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="amd64",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.0.0"
	INFO: Reference: Microsoft.VC90.MFC,processorArchitecture="amd64",type="win32",version="9.0.21022.8"
INFO: Resolving reference Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT.MANIFEST.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT\Microsoft.VC90.CRT.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8".
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\marnj\AppData\Local\Temp\_MEI179242\python27.dll
	AssemblyDirectory = C:\Users\marnj\AppData\Local\Temp\_MEI179242\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\marnj\AppData\Local\Temp\_MEI179242\python27.dll.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8"
INFO: Resolving reference Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT.MANIFEST.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI179242\Microsoft.VC90.CRT\Microsoft.VC90.CRT.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8".
ERROR: Activation Context generation failed.
End Activation Context Generation.

````

**Comment by htgoebel** [comment] 2015-09-15 21:27
@jonnojohnson PyInstaller 2.1 is far outdated. Please try the current `python3` branch head or the preview release from PyPI and **report back here**. Thanks.

**Comment by jonnojohnson** [comment] 2015-09-15 21:29
@htgoebel I have tried using the Python3 branch but it won't build at all. I get a max recursion depth exceeded issue there.

**Comment by jonnojohnson** [comment] 2015-09-29 15:34
Just re-tried with today's python3 dev branch after the max recursion depth issue was fixed but I'm still getting this error.
Trace output:
````
=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\marnj\AppData\Local\Temp\_MEI472842\InfiniiumPhaseNoise.exe.manifest
	AssemblyDirectory = C:\Users\marnj\AppData\Local\Temp\_MEI472842\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\marnj\AppData\Local\Temp\_MEI472842\InfiniiumPhaseNoise.exe.manifest.
	INFO: Manifest Definition Identity is InfiniiumPhaseNoise,processorArchitecture="amd64",type="win32",version="1.0.0.0".
	INFO: Reference: Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.6161"
INFO: Resolving reference Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.6161".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: Find publisher policy at C:\windows\WinSxS\manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
				INFO: Publisher Policy redirected assembly version.
				INFO: Post policy assembly identity is Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.6161".
			INFO: Begin assembly probing.
				INFO: Attempt to probe manifest at C:\windows\WinSxS\manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251.manifest.
				INFO: Manifest found at C:\windows\WinSxS\manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251.manifest.
			INFO: End assembly probing.
INFO: Resolving reference Microsoft.VC90.CRT.mui,language="&#x2a;",processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.6161".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\windows\assembly\GAC_64\Microsoft.VC90.CRT.mui\9.0.30729.6161_en-US_1fc8b3b9a1e18e3b\Microsoft.VC90.CRT.mui.DLL.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\windows\assembly\GAC_64\Microsoft.VC90.CRT.mui\9.0.30729.6161_en_1fc8b3b9a1e18e3b\Microsoft.VC90.CRT.mui.DLL.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
INFO: Parsing Manifest File C:\windows\WinSxS\manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251.manifest.
	INFO: Manifest Definition Identity is Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.6161".
INFO: Activation Context generation succeeded.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\marnj\AppData\Local\Temp\_MEI472842\python27.dll
	AssemblyDirectory = C:\Users\marnj\AppData\Local\Temp\_MEI472842\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\marnj\AppData\Local\Temp\_MEI472842\python27.dll.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8"
INFO: Resolving reference Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI472842\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Users\marnj\AppData\Local\Temp\_MEI472842\Microsoft.VC90.CRT.MANIFEST.
				INFO: Manifest found at C:\Users\marnj\AppData\Local\Temp\_MEI472842\Microsoft.VC90.CRT.MANIFEST.
			INFO: End assembly probing.
INFO: Resolving reference Microsoft.VC90.CRT.mui,language="&#x2a;",processorArchitecture="amd64",type="win32",version="9.0.21022.8".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
INFO: Parsing Manifest File C:\Users\marnj\AppData\Local\Temp\_MEI472842\Microsoft.VC90.CRT.MANIFEST.
	INFO: Manifest Definition Identity is Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.6161".
	ERROR: Component identity found in manifest does not match the identity of the component requested. Reference is Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8". Definition is Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.6161".
ERROR: Activation Context generation failed.
End Activation Context Generation.
````

**Comment by codewarrior0** [comment] 2015-09-29 20:03
Could you try building with `pyinstaller --clean` and see if that still happens?

**Comment by jonnojohnson** [comment] 2015-09-29 20:27
Running the .exe after building with -F --clean I get:
````
Traceback (most recent call last):
  File "<string>", line 72, in <module>
  File "C:\Anaconda\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 363, in load_module
    exec(bytecode, module.__dict__)
  File "c:\anaconda\lib\site-packages\visa.py", line 16, in <module>
    from pyvisa import logger, __version__, log_to_screen, constants
  File "C:\Anaconda\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 363, in load_module
    exec(bytecode, module.__dict__)
  File "c:\anaconda\lib\site-packages\pyvisa\__init__.py", line 18, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
InfiniiumPhaseNoise returned -1
````

**Comment by jonnojohnson** [comment] 2015-09-29 20:33
I got something similar when trying to use py2exe last year.
PyVISA is here: https://github.com/hgrecco/pyvisa
Was told some of the suggestions here might help: http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
But don't really understand what's going on.

**Comment by codewarrior0** [comment] 2015-09-29 21:04
For the record, Anaconda includes pkg_resources as part of the setuptools egg:

```
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import pkg_resources
>>> pkg_resources.__file__
'c:\\Anaconda-27-64\\lib\\site-packages\\setuptools-17.1.1-py2.7.egg\\pkg_resources\\__init__.py'
```

Whereas regular Python includes it as a plain package inside `site-packages`:

```
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.__file__
'c:\\python27-64\\lib\\site-packages\\pkg_resources\\__init__.pyc'
```

So it might be related to the way PyInstaller includes eggs? I'm not sure at this point.

**Comment by Repiklis** [comment] 2015-10-08 13:47
Hi all,

I got the same problem with win 7 and python 2.7.10, but with pyinstaller 3.0. I don't have Anaconda and build in a directory (not onefile). Used to work with the development version I got, which was a couple of months old.
The message I get now is: "Error loading Python DLL: C:\PathToExe\python27.dll (error code 14001)
Here is the trace output. As fas as I can tell, it is pretty similar to the one by jonnojohnson. Hope it helps. :) 

	=================
	Begin Activation Context Generation.
	Input Parameter:
		Flags = 0
		ProcessorArchitecture = AMD64
		CultureFallBacks = en-US;en
		ManifestPath = C:\PathToExe\python27.dll
		AssemblyDirectory = C:\PathToExe\
		Application Config File = 
	-----------------
	INFO: Parsing Manifest File C:\PathToExe\python27.dll.
		INFO: Manifest Definition Identity is (null).
		INFO: Reference: Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8"
	INFO: Resolving reference Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8".
		INFO: Resolving reference for ProcessorArchitecture amd64.
			INFO: Resolving reference for culture Neutral.
				INFO: Applying Binding Policy.
					INFO: No binding policy redirect found.
				INFO: Begin assembly probing.
					INFO: Did not find the assembly in WinSxS.
					INFO: Attempt to probe manifest at C:\PathToExe\Microsoft.VC90.CRT.DLL.
					INFO: Attempt to probe manifest at C:\PathToExe\Microsoft.VC90.CRT.MANIFEST.
					INFO: Manifest found at C:\PathToExe\Microsoft.VC90.CRT.MANIFEST.
				INFO: End assembly probing.
	INFO: Resolving reference Microsoft.VC90.CRT.mui,language="&#x2a;",processorArchitecture="amd64",type="win32",version="9.0.21022.8".
		INFO: Resolving reference for ProcessorArchitecture amd64.
			INFO: Resolving reference for culture en-US.
				INFO: Applying Binding Policy.
					INFO: No binding policy redirect found.
				INFO: Begin assembly probing.
					INFO: Did not find the assembly in WinSxS.
					INFO: Did not find manifest for culture en-US.
				INFO: End assembly probing.
			INFO: Resolving reference for culture en.
				INFO: Applying Binding Policy.
					INFO: No binding policy redirect found.
				INFO: Begin assembly probing.
					INFO: Did not find the assembly in WinSxS.
					INFO: Did not find manifest for culture en.
				INFO: End assembly probing.
	INFO: Parsing Manifest File C:\PathToExe\Microsoft.VC90.CRT.MANIFEST.
		INFO: Manifest Definition Identity is Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.4940".
		ERROR: Component identity found in manifest does not match the identity of the component requested. Reference is Microsoft.VC90.CRT,processorArchitecture="amd64",type="win32",version="9.0.21022.8". Definition is Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.30729.4940".
	ERROR: Activation Context generation failed.
	End Activation Context Generation.

**Comment by codewarrior0** [comment] 2015-10-08 13:49
Could you try again with `pyinstaller --clean` and see if that still happens?

**Comment by Repiklis** [comment] 2015-10-08 14:09
The --clean option seems to have resolved the issue.

**Comment by codewarrior0** [comment] 2015-10-08 14:11
All right, I think I see what's happening now. The bincache stores cached versions of files that are modified while being collected, and if our modifications change, it will still use the cached version that has the old modifications. I think the solution is to add a "version" key to the cache.dat file in the bincache folder, and compare that with a version constant that gets updated whenever the modifications (the ones done in `checkCache()`) are changed.

In this case, it's because manifests are modified differently in the version you previously had, versus version 3.0.

**Comment by diegoherranz** [comment] 2015-11-16 11:49
`--clean` also worked for me with a recent (few days old) development version.

**Comment by matysek** [comment] 2015-11-26 20:10
@codewarrior0 could this be closed?

**Comment by codewarrior0** [comment] 2015-11-26 22:26
Sure. I opened a new issue for the bincache thing.

**Closed by codewarrior0** 2015-11-26 22:26 UTC
Labels: develop, Windows

**Comment by Sakthivishnu** [comment] 2015-12-07 12:36
Thanks a lot your idea helped me a lot :+1: :-)

**Comment by ochawkeye** [comment] 2016-01-15 18:11
This is exactly what I was looking for!  I regularly create a 32-bit and a 64-bit version of my .exes and could not figure out why occasionally both would work without issue and at other times I'd be hit with the `Error loading Python DLL` problem.  

`--clean` appears to have solved my troubles.
