### ISSUE TITLE
Pyinstaller build with PyQt6 not working on M1 Mac (M1 Pro)

### ISSUE THREAD

**Issue by hardik-infocusp** [pyinstaller/pyinstaller#7805] opened 2023-07-31 06:01 UTC
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.13.0```
* Version of Python: Python 3.9.6 (also tried with python 3.10)
* Platform: Mac OS (Monterey 12.6)
* How you installed Python: brew
* Did you also try this on another platform? Does it work there? - Yes, it works on windows

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [Done] start with clean installation
  * [Done] use the latest development version
  * [Done] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [Done] Package your program in **--onedir mode**
  * [Done] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [Done] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
from PyQt6 import QtWidgets


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()

        self.setWindowTitle("Hello World")
        l = QtWidgets.QLabel("My simple app.")
        l.setMargin(10)
        self.setCentralWidget(l)
        self.show()

if __name__ == '__main__':
    app = QtWidgets.QApplication([])
    w = MainWindow()
    app.exec()
```

### Stacktrace / full error message
Pyinstaller builds the package successfully, but when we click on the executable it crashes and we get following information in bug report:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               app [67237]
Path:                  /Users/USER/*/app.app/Contents/MacOS/app
Identifier:            app
Version:               0.0.0 (???)
Code Type:             ARM-64 (Native)
Parent Process:        app [67235]
Responsible:           app [67235]
User ID:               501

Date/Time:             2023-07-31 11:29:19.1321 +0530
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        66C79FA4-2A9D-9A18-2D16-F0C2A731CD71

Sleep/Wake UUID:       003A6A7A-ADAE-4ECE-89C0-9E840652191C

Time Awake Since Boot: 320000 seconds
Time Since Wake:       2885 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [67237]
```

**Comment by rokm** [comment] 2023-07-31 09:29
Duplicate of #7789.

**Closed as not planned by rokm** 2023-07-31 09:29 UTC
Labels: solution:duplicate
