### ISSUE TITLE
Cannot invoke command using symbolic link

### ISSUE THREAD

**Issue by KenKundert** [pyinstaller/pyinstaller#5308] opened 2020-11-04 19:57 UTC
I have noticed that as of PyInstaller 3.6 I can no longer invoke a command packaged with PyInstaller using a symbolic link on Linux.  To see the problem, change into an empty directory and run the following:
```
echo 'print("Hey now!")' > hello.py
pyinstaller hello.py
ln -s dist/hello/hello .
./hello
```
If you do so, you should get a message similar to the following:
```
[960925] Error loading Python lib '/home/ken/tmp/pyinstaller/libpython3.8.so.1.0': dlopen: /home/ken/tmp/pyinstaller/libpython3.8.so.1.0: cannot open shared object file: No such file or directory
Exit 255
```
It is possible to work around this issue by using the --onefile option.

**Comment by rokm** [comment] 2020-11-04 20:02
Duplicate of #5179, with in-progress fix in PR #5232. You can give that a try, if you want (you'll need to rebuild the bootloader).

**Closed** 2020-11-05 17:31 UTC
