### ISSUE TITLE
Centos 7.5 with python 3.8 failure with v4.6 to compile on missing dependency

### ISSUE THREAD

**Issue by erbeone** [pyinstaller/pyinstaller#6344] opened 2021-11-04 12:43 UTC
I am able to run without issues with version 4.5.1 but it fails with 4.6 with the following output.

/usr/bin/scl enable rh-python38 'pyinstaller -F main.py --distpath Binaries --noconfirm'
45 INFO: PyInstaller: 4.6
45 INFO: Python: 3.8.11
47 INFO: Platform: Linux-3.10.0-957.1.3.rt56.913.el7.x86_64-x86_64-with-glibc2.2.5
47 INFO: wrote /var/bf/12044/main.spec
50 INFO: UPX is not available.
51 INFO: Extending PYTHONPATH with paths
['/var/bf/12044']
225 INFO: checking Analysis
225 INFO: Building Analysis because Analysis-00.toc is non existent
225 INFO: Initializing module dependency graph...
226 INFO: Caching module graph hooks...
233 INFO: Analyzing base_library.zip ...
2654 INFO: Processing pre-find module path hook distutils from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2655 INFO: distutils: retargeting to non-venv dir '/opt/rh/rh-python38/root/usr/lib64/python3.8'
4067 INFO: Caching module dependency graph...
4201 INFO: running Analysis Analysis-00.toc
4232 INFO: Analyzing /var/bf/12044/main.py
4423 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
/var/bf/12044/setenv/DockerHelper.py:73: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif match_version is not "latest" and match_version < image_of_docker[1]:
7313 INFO: Processing module hooks...
7313 INFO: Loading module hook 'hook-bcrypt.py' from '/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7314 INFO: Loading module hook 'hook-certifi.py' from '/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7317 INFO: Loading module hook 'hook-cryptography.py' from '/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7547 INFO: Loading module hook 'hook-nacl.py' from '/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7555 INFO: Loading module hook 'hook-difflib.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7558 INFO: Loading module hook 'hook-distutils.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7566 INFO: Loading module hook 'hook-distutils.util.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7569 INFO: Loading module hook 'hook-encodings.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7624 INFO: Loading module hook 'hook-heapq.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7628 INFO: Loading module hook 'hook-lib2to3.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7666 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7670 INFO: Loading module hook 'hook-pickle.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7673 INFO: Loading module hook 'hook-sysconfig.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7673 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7674 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7674 INFO: Loading module hook 'hook-xml.py' from '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks'...
7707 INFO: Looking for ctypes DLLs
7716 INFO: Analyzing run-time hooks ...
7722 INFO: Including run-time hook '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
7725 INFO: Including run-time hook '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
7728 INFO: Including run-time hook '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
7729 INFO: Including run-time hook '/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_certifi.py'
7739 INFO: Looking for dynamic libraries
8335 INFO: Looking for eggs
8335 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/building/build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/building/build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "/var/bf/12044/main.spec", line 7, in <module>
    a = Analysis(['main.py'],
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/building/build_main.py", line 277, in __init__
    self.__postinit__()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/building/build_main.py", line 501, in assemble
    self._check_python_library(self.binaries)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/building/build_main.py", line 605, in _check_python_library
    python_lib = bindepend.get_python_library_path()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 897, in get_python_library_path
    python_libname = findLibrary(name)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 775, in findLibrary
    lib = _which_library(name, paths)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 806, in _which_library
    for _path in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/x86_64-linux-gnu'

**Comment by rokm** [comment] 2021-11-04 13:56
Duplicate of #6331.

**Closed as completed by rokm** 2021-11-04 13:56 UTC
Labels: solution:duplicate
