### ISSUE TITLE
AttributeError: 'str' object has no attribute '_MEIPASS'

### ISSUE THREAD

**Issue by aliada77** [pyinstaller/pyinstaller#5797] opened 2021-05-03 14:30 UTC
## Description of the issue
I've used pyinstaller to convert my py to exe. App is working fine, all of the features are working ok except "pyperclip.copy". 
Even I have no issue with "pyperclip.paste", only copying to clipboard.
 

## Context information (for bug reports)
Whenever I use the command "pyperclip.copy(copy_clipboard)" to copy string to clipboard, it doesn't work instead I get following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1884, in __call__
  File "xxxxx.py", line 5107, in ctrl_c
  File "pyperclip\__init__.py", line 658, in lazy_load_stub_copy
  File "pyperclip\__init__.py", line 541, in determine_clipboard
  File "pyperclip\__init__.py", line 371, in init_windows_clipboard
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 142, in __init__
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 128, in _frozen_name
AttributeError: 'str' object has no attribute '_MEIPASS'

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.9.1
* Platform: Windows 10
* Did you also try this on another platform? No 

* try the latest development version, using the following command: I've tried but it failed to create exe file.

I've tried all suggested workarounds but couldn't fix this issue. I'm not an advanced programmer so it might be silly issue although I appreciate any help in this regard. Thanks!

**Comment by rokm** [comment] 2021-05-03 14:47
This looks like the `sys` module is being shadowed by a string variable...

Are you assigning a string to a variable called `sys` anywhere in your code?

This seems to be reproducer and it seems to affect only frozen application:

```python
# sys='whatever'  # uncomment to reproduce the problem
import pyperclip
pyperclip.copy('The text to be copied to the clipboard.')
print(pyperclip.paste())
```

**Comment by aliada77** [comment] 2021-05-03 22:07
@rokm Thanks mate! 
I changed sys variable to system_info afterwards it's working without any issue 🙏

**Comment by bwoodsend** [comment] 2021-05-19 21:00
This is still a bug? That `sys = "string"` is somehow finding its way into:
https://github.com/pyinstaller/pyinstaller/blob/7e27898af80f7d05f583f978285860673184ce22/PyInstaller/loader/pyiboot01_bootstrap.py#L128
... where it certainly doesn't belong.

**Comment by rokm** [comment] 2021-05-19 21:19
Yeah, this specific problem (overwriting `sys` or `os` with custom variable in global namespace) should be fixed  if/when we move those ctypes classes and functions from pyboot01_bootstrap.py into a separate module (where the bound names of imported `os` and `sys˙ modules are module-scoped, and cannot be affected by global namespace variables).

The bootstrap script should be just a script, without any functions or classes that can be called or instantiated after the script itself has finished.

**Closed** 2021-05-22 23:15 UTC
Labels: bug
