### ISSUE TITLE
Installing PyInstaller on Mac OS X broke existing code via "future" dependency

### ISSUE THREAD

**Issue by kjcole** [pyinstaller/pyinstaller#2869] opened 2017-09-25 21:09 UTC
I'm working with the native Python2.7 on Mac OS X 10.12.6 (Sierra)

```
$ pip install PyInstaller
Collecting PyInstaller
Requirement already satisfied: macholib>=1.8 in /Users/.../.virtualenvs/venv1/lib/python2.7/site-packages (from PyInstaller)
Collecting pefile>=2017.8.1 (from PyInstaller)
Requirement already satisfied: setuptools in /Users/.../.virtualenvs/venv1/lib/python2.7/site-packages (from PyInstaller)
Collecting dis3 (from PyInstaller)
  Using cached dis3-0.1.1-py2-none-any.whl
Requirement already satisfied: altgraph>=0.13 in /Users/.../.virtualenvs/venv1/lib/python2.7/site-packages (from macholib>=1.8->PyInstaller)
Collecting future (from pefile>=2017.8.1->PyInstaller)
Installing collected packages: future, pefile, dis3, PyInstaller
Successfully installed PyInstaller-3.3 dis3-0.1.1 future-0.16.0 pefile-2017.9.3
```
Without actually using PyInstaller, after installing it, code which has been working for two years started failing, because the installed future module overrode the builtin future module.

```
(venv1)$ ./Localization.py 
Traceback (most recent call last):
  File "/Users/.../SessionInfo.py", line 195, in launch
    vcs = self.main_ui(initValues)
  File "./Localization.py", line 235, in __init__
    msg = msg.build()
  File "/Users/.../.virtualenvs/venv1/lib/python2.7/site-packages/pythonosc/osc_message_builder.py", line 103, in build
    arg_types = "".join([arg[0] for arg in self._args])
TypeError: sequence item 0: expected string, NoneType found
```
Removing future:

```
$ rm -rf ~/.virtualenvs/venv1/lib/python2.7/site-packages/future*
```
took out `future/` and `future-0.16.0.dist-info/` and now my code works again.

The only time I use future in my code is:

```
from __future__ import print_function, absolute_import
```

**Comment by htgoebel** [comment] 2017-09-26 08:44
Thanks for your report. Obviously `future` has side-effects on `pythonosc`. You can prove this by using a fresh virtual env and installing both you application anf `future` there (but not PyInstaller). So I suggest opening a bug report for `pythonosc` at their issue-tracker.

Maybe this is not an issue with `pythonosc`, but caused by your application. I suggest looking into this since it might be a sign of your application (or pythonosc) not being future-proof.

BTW: The correct way to uninstall packages is using e.g. `pip uninstall future`. So there is no need to delete files.

I'm closing this now. If you find there is more to to on PyInstallers side, please add a comment and I'll reopen.

**Closed by htgoebel** 2017-09-26 08:44 UTC

**Comment by kjcole** [comment] 2017-09-26 19:20
While I understood that future was the cause, I felt that name collision caused by PyInstaller depending upon a module that overrides a module shipped with Python was unexpected and problematic. I intend to poke around in both pythonosc and future to determine the specific issue.

**Comment by htgoebel** [comment] 2017-09-27 08:27
I agree. There is/was already an ticket about such issues #2764
