### ISSUE TITLE
an't perform this operation for unregistered loader type

### ISSUE THREAD

**Issue by dat8866** [pyinstaller/pyinstaller#3112] opened 2017-12-14 10:54 UTC
I'm using bokeh for data visualization, and trying to make an executable but it shows an error message of "can't perform this operation for unregistered loader type"

I have tried as a solution of init.py to the directory (+subdir) of my script.py, but it's not work.

PS. Win10, Python 3.6.3, pyinstaller 3.4, bokeh 0.12.13

Code:
from bokeh.plotting import figure, show

p = figure(width=800, height=400, title="Money")
p.title.text_color = "green"
p.title.text_font_size = "18pt"
p.xaxis.axis_label = "Time"
p.xaxis.axis_label_text_color = "violet"
p.yaxis.axis_label = "Money"
p.yaxis.axis_label_text_color = "violet"
dashs = [12, 4]
listx1 = [1,5,7,9,13,16]
listy1 = [15,50,80,40,70,50]
p.line(listx1, listy1, line_width=4, line_color="red", line_alpha=0.3, line_dash=dashs, legend="Idle")

show(p)

Error message:
![default](https://user-images.githubusercontent.com/34075957/33988718-27e1ff0e-e100-11e7-986b-fb2bc5a4811d.jpg)

Thx in advance for your help

**Comment by htgoebel** [comment] 2017-12-14 11:05
1) PyInstaller 3.4 is not yet released, how can you have it?
2) Don't post picutures but text.
3) This looks like being related to jinja2. Please have a log at what jinaj2 is doing in loaders.py 234 and 113.
4) Try *newest* jinja2
5) Please try to build a even smaller example showing the error, which does not include bokeh.

HTH

**Comment by DominicAntonacci** [comment] 2018-03-05 16:09
This is a duplicate of https://github.com/pyinstaller/pyinstaller/issues/1898.

There are bokeh workarounds there and the problem might get fixed in bokeh soon.

**Comment by htgoebel** [comment] 2018-03-05 21:44
Taking this as solved :-)

**Closed by htgoebel** 2018-03-05 21:44 UTC
Labels: support
