### ISSUE TITLE
5.0.1 '--name blah --onefile --dist .' throws dynamic library error

### ISSUE THREAD

**Issue by shouldsee** [pyinstaller/pyinstaller#6980] opened 2022-07-26 10:23 UTC
## Description of the issue

When I build onefile binary with a name, it wont start, throwing a dynamic library load error. 

if I instead compile without renaming, it works fine.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.1```
* Version of Python: 3.7
* Platform: GNU/Linux (Ubuntu 18.04.1 LTS)
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?: No

### A minimal example program which shows the error

This is hard to reproduce. The following script DOES NOT reproduce this error

```bash
 echo "print(123)" >hello.py
pyinstaller hello.py --onefile --name blah --dist .
./blah
```

### Stacktrace / full error message

```
[15155] Error loading Python lib '/tmp/_MEIF30AOq/libpython3.7m.so': dlopen: /tmp/_MEIF30AOq/libpython3.7m.so: cannot open shared object file: No such file or directory
```

**Comment by rokm** [comment] 2022-07-26 10:31
Sounds like a duplicate of #6831 that affects linux & conda combination. Try PyInstaller 5.2, which should fix that problem.

**Closed as completed** 2022-07-26 10:31 UTC
Labels: solution:duplicate, solution:already-fixed

**Comment by shouldsee** [comment] 2022-07-26 11:05
@rokm  Many thanks for your blazing-fast reply!

Unfortunately I found out this was not the same as #6831. I tried to play with the random seed, but keep
getting deterministic outputs...  Finally I arrived this reproducible script, which is problematic possibly because the ./build directory is not properly cleaned?


```bash
# tested on pyinstaller 5.0.1. 
# Always throws [8804] Error loading Python lib '/tmp/_MEImhcayX/libpython3.7m.so': dlopen: /tmp/_MEImhcayX/libpython3.7m.so: cannot open shared object file: No such file or directory
echo "print(123)" >hello.py
pyinstaller hello.py 
pyinstaller hello.py --onefile  --dist .
./hello
```

But in any case, upgrading to 5.2 fixed my problem. Thanks for maintaining this repo!
