### ISSUE TITLE
Program is not working on target computers

### ISSUE THREAD

**Issue by lino10** [pyinstaller/pyinstaller#1993] opened 2016-05-17 03:40 UTC
Hi, I'm building a small program using PyQt5 and Python 3.5.
I packaged the program using Pyinstaller 3.2, it's working fine on the dev computer but on the target computers it's not working.

Dev Computer is Windows 10x64, target computers are Windows 7x64.

With both 'onefolder' and 'onefile' option I got this error
![Image](http://i.imgur.com/7xe6quY.jpg)

With  'onefile' option, after the first error above, I got this error
![Image](http://i.imgur.com/Ac0Fhgj.jpg)
When I checked the temp folder, the python dll is already there.

**Edit**
After doing some searching, I found out that Python 3.5 is having problems with Microsoft DLLs. So I downgraded to 3.4, repackage the program, and now I can open the program without error.

**Comment by lino10** [comment] 2016-05-17 06:00
Should I close this or not? I'm not sure if this is Python bug or Pyinstaller bug

**Comment by stephenrauch** [comment] 2016-05-25 14:03
Is this a dupe of #1566?

**Comment by weyou** [comment] 2016-06-05 03:32
I got the exact same errors with Python2.5/PyQt5.6

**Comment by bjones1** [comment] 2016-06-05 03:40
Yes, this looks like a dupe. Closing, since a better discussion is already there. @stephenrauch, thanks for the pointer!

**Closed by bjones1** 2016-06-05 03:40 UTC
