### ISSUE TITLE
multiple py files

### ISSUE THREAD

**Issue by dominhtri1995** [pyinstaller/pyinstaller#2532] opened 2017-03-29 23:00 UTC
Hi,

Pyinstaller has been working fine when I have only vndirectPyQt.py file. However when I start to `import userdata`  from userdata.py to vndirectPyQt.py at line 17 ,  my executable file starts to crash. 

I have 2 file vndirectPyqt.py and userdata.py in the same directory. I have tried hooks and --path option but no luck. Please help. Thanks

Both .py file are in /Users/TriDo/General_Code/vndirect. 
I'm on Mac OS 10.12

Here is my spec files:
```
a = Analysis(['vndirectPyQt.py'],
             pathex=['/Users/TriDo/General_Code/vndirect'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
a.datas+= [('chromedriver','/Users/TriDo/General_Code/chromedriver', 'DATA')]
a.datas +=[('testDB.db','/Users/TriDo/General_Code/vndirect/testDB.db','DATA')]             
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          Tree('./image',prefix ='image'),
          a.zipfiles,
          a.datas,
          name='vndirectPyQt',
          debug=False,
          strip=False,
          upx=True,
          console=False )
app = BUNDLE(exe,
             name='vndirectPyQt.app',
             icon='logo.icns',
             bundle_identifier=None)
```
Here is the bug when I try to execute the file with console:

```
Traceback (most recent call last):
  File "vndirectPyQt.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "userdata.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/pyrebase/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/pyrebase/pyrebase.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/oauth2client/service_account.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/oauth2client/client.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/oauth2client/crypt.py", line 55, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/oauth2client/_pycrypto_crypt.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/Crypto/PublicKey/RSA.py", line 79, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/Crypto/IO/PKCS8.py", line 73, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/Crypto/IO/_PBES.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/Crypto/Cipher/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/Crypto/Cipher/_mode_ecb.py", line 46, in <module>
  File "site-packages/Crypto/Util/_raw_api.py", line 168, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'
Failed to execute script vndirectPyQt
```

**Comment by ChenghaoQ** [comment] 2017-03-30 01:37
Please upload your code.

**Comment by tallforasmurf** [comment] 2017-03-30 02:10
You will get no help when you show us no sign that you have read this:

https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

especially beginning at

https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug

you give us none of that whatever.

**Comment by dominhtri1995** [comment] 2017-03-30 19:46
Sorry for the lack of information in the previous post. I was expecting some sort of one line to add for it to work. I edited the original post. Thanks

**Comment by tallforasmurf** [comment] 2017-03-30 20:59
OK now I can see the specific error, `OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'` and a quick google tells me this is a duplicate of

https://github.com/pyinstaller/pyinstaller/issues/1983

https://github.com/pyinstaller/pyinstaller/issues/2125

I note that @htgoebel closed #1983 with the note "pycrypto is officially dead and seriously buggy. Please move forward to an alternative. We ought not spend time fixing support for dead software."

Nevertheless #2125 got a lot of discussion from @chrisnorman7 and @stephenrauch -- it is still open and I don't see any firm conclusion. Maybe one of those guys would like to comment?

In any case, @htgoebel close this is a dup, or close as wontfix?

**Closed** 2017-03-31 08:07 UTC
Labels: duplicate
