### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'co_code'

### ISSUE THREAD

**Issue by jpakkane** [pyinstaller/pyinstaller#6929] opened 2022-07-03 20:10 UTC
A possible duplicate of #6396 (that one has been closed, though).

The issue only affects Windows.

## Description of the issue

Trying to run the package creator of [Meson](github.com/mesonbuild/meson/) fails with the error in bug title.

To replicate run the full setup Windows run these commands from the VS 64 bit dev tools prompt. You also need Wix and MSM redistributables installed.

```
git clone https://github.com/mesonbuild/meson
cd meson
git checkout 0.63.0
python packaging\createmsi.py
```

The Pyinstaller command it runs is the following:

    pyinstaller --clean --additional-hooks-dir=packaging --distpath tmpdir meson.py

The same error happens if you use Meson version 0.62.0 too. However that used to build fine (we have the .msi for that available for download). This would seem to indicate that something outside our code has changed.

### Context information (for bug reports)

This only happens on Windows. I used a fresh VM install of Windows with nothing but the immediate deps installed. Python is the latest (3.10.5) and Pyinstaller & co are installed via Pip.

The latest development version has the same error.

### Stacktrace / full error message

```
Requirement already satisfied: pyinstaller in c:\python\lib\site-packages (5.1)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\python\lib\site-packages (from pyinstaller) (0.2.0)
Requirement already satisfied: pefile>=2017.8.1 in c:\python\lib\site-packages (from pyinstaller) (2022.5.30)
Requirement already satisfied: setuptools in c:\python\lib\site-packages (from pyinstaller) (58.1.0)
Requirement already satisfied: altgraph in c:\python\lib\site-packages (from pyinstaller) (0.17.2)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\python\lib\site-packages (from pyinstaller) (2022.7)
Requirement already satisfied: future in c:\python\lib\site-packages (from pefile>=2017.8.1->pyinstaller) (0.18.2)
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\python\python.exe -m pip install --upgrade pip' command.
61 INFO: PyInstaller: 5.1
61 INFO: Python: 3.10.5
69 INFO: Platform: Windows-10-10.0.17763-SP0
69 INFO: wrote C:\Users\IEUser\meson\meson.spec
69 INFO: UPX is not available.
69 INFO: Removing temporary files and cleaning cache in C:\Users\IEUser\AppData\Local\pyinstaller
69 INFO: Extending PYTHONPATH with paths
['C:\\Users\\IEUser\\meson']
270 INFO: checking Analysis
270 INFO: Building Analysis because Analysis-00.toc is non existent
270 INFO: Initializing module dependency graph...
270 INFO: Caching module graph hooks...
270 INFO: Analyzing base_library.zip ...
3354 INFO: Caching module dependency graph...
3464 INFO: running Analysis Analysis-00.toc
3464 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\python\python.exe
3565 INFO: Analyzing C:\Users\IEUser\meson\meson.py
6410 INFO: Processing pre-find module path hook site from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
6410 INFO: site: retargeting to fake-dir 'C:\\python\\lib\\site-packages\\PyInstaller\\fake-modules'
6852 INFO: Processing pre-find module path hook distutils from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
6852 INFO: distutils: retargeting to non-venv dir 'C:\\python\\lib'
7317 INFO: Processing module hooks...
7317 INFO: Loading module hook 'hook-mesonbuild.py' from 'C:\\Users\\IEUser\\meson\\packaging'...
8873 WARNING: Hidden import "mesonbuild.scripts.cmd_or_ps" not found!
9208 INFO: Loading module hook 'hook-difflib.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9208 INFO: Loading module hook 'hook-distutils.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9215 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9215 INFO: Loading module hook 'hook-encodings.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9262 INFO: Loading module hook 'hook-heapq.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9277 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9347 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9347 INFO: Loading module hook 'hook-pickle.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9347 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
9916 INFO: Processing pre-safe import module hook win32com from 'C:\\python\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
10114 WARNING: Hidden import "pkg_resources.py2_warn" not found!
10133 WARNING: Hidden import "pkg_resources.markers" not found!
10133 INFO: Loading module hook 'hook-platform.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
10133 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
10148 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
10353 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
10353 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
10353 INFO: Loading module hook 'hook-xml.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
10364 INFO: Loading module hook 'hook-packaging.py' from 'C:\\python\\lib\\site-packages\\PyInstaller\\hooks'...
10379 INFO: Looking for ctypes DLLs
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\python\Scripts\pyinstaller.EXE\__main__.py", line 7, in <module>
  File "C:\python\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\python\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\python\lib\site-packages\PyInstaller\building\build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\python\lib\site-packages\PyInstaller\building\build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "C:\Users\IEUser\meson\meson.spec", line 7, in <module>
    a = Analysis(
  File "C:\python\lib\site-packages\PyInstaller\building\build_main.py", line 319, in __init__
    self.__postinit__()
  File "C:\python\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\python\lib\site-packages\PyInstaller\building\build_main.py", line 512, in assemble
    for (dest, source) in format_binaries_and_datas(self.graph.metadata_required()))
  File "C:\python\lib\site-packages\PyInstaller\depend\analysis.py", line 676, in metadata_required
    out |= self._metadata_from(
  File "C:\python\lib\site-packages\PyInstaller\depend\analysis.py", line 728, in _metadata_from
    for calls in bytecode.recursive_function_calls(code).values():
  File "C:\python\lib\site-packages\PyInstaller\depend\bytecode.py", line 225, in recursive_function_calls
    return search_recursively(function_calls, code)
  File "C:\python\lib\site-packages\PyInstaller\depend\bytecode.py", line 213, in search_recursively
    _memo[code] = search(code)
  File "C:\python\lib\site-packages\PyInstaller\depend\bytecode.py", line 172, in function_calls
    for match in finditer(_call_function_bytecode, code.co_code):
AttributeError: 'NoneType' object has no attribute 'co_code'
Traceback (most recent call last):
  File "C:\Users\IEUser\meson\packaging\createmsi.py", line 334, in <module>
    p.build_dist()
  File "C:\Users\IEUser\meson\packaging\createmsi.py", line 141, in build_dist
    subprocess.check_call(pyinst_cmd)
  File "C:\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\python\\Scripts\\pyinstaller.EXE', '--clean', '--additional-hooks-dir=packaging', '--distpath', 'pyinst-tmp', 'meson.py']' returned non-zero exit status 1.
```

**Comment by rokm** [comment] 2022-07-03 22:54
This actually looks like duplicate of #6873 (and is, likewise, caused by existence of a `packaging` directory next to entry-point script), and should be already taken care of by #6875. I did a quick test and while 5.1 fails as described, `develop` works as expected.

**Comment by Dragon31337** [comment] 2022-07-11 21:52
should the develop be used to make an MSI for the latest versions? There is no recent windows installer.

**Comment by bwoodsend** [comment] 2022-07-11 22:00
> should the develop be used to make an MSI for the latest versions? There is no recent windows installer.

Uhm, what are you talking about? PyInstaller has nothing to do with MSIs.

I'm closing this since the fix is there and already released (as of two days ago).

**Closed as completed by bwoodsend** 2022-07-11 22:00 UTC
Labels: solution:duplicate, solution:already-fixed

**Comment by eli-schwartz** [comment] 2022-07-11 22:07
I assume what @Dragon31337 is referring to is the createmsi.py script mentioned in the original issue report, that script (the package creator for Meson) being the reproducer test case that prompted the issue to be opened.

So, reworded:

> should the develop be used by the Meson project to make an MSI for the latest Meson versions? There is no recent windows installer for Meson, and they cannot make one because making it requires to first successfully run pyinstaller to create the binaries which then get Wix'ed into an MSI.


And as far as that goes:
> I'm closing this since the fix is there ***and already released (as of two days ago)***.

Excellent. :) We will try to get a new Meson release binary out now that the fix is released.
