### ISSUE TITLE
pyinstaller *.exe: The *.exe is not consistent with the source code *.py functionally

### ISSUE THREAD

**Issue by lin-name** [pyinstaller/pyinstaller#6657] opened 2022-03-08 01:38 UTC
Hello!
Sorry to interrupt you!
but i  faced debug. here is the example.py:

![捕获](https://user-images.githubusercontent.com/65641960/157148008-2b76b304-d016-4c67-a02c-9d92432fdd7c.PNG)

And i can run the example.py well in python environments when i input:
$ python example.py -i c:\11 -t d:\22 -m T
and it get the right outputs.

but after i  get the example.exe via Pyinstaller, and the input is the same as before,
$ example.exe -i c:\11 -t d:\22 -m T
however, it get the error:

![捕获2](https://user-images.githubusercontent.com/65641960/157017764-b867ea6e-1022-4639-9fa4-78c83c374144.PNG)

The argument -m T can run in .py, why it is unrecognized in the *.exe?
Why does it happen? and how  can i solve this error?

Looking forward for your reply.

**Comment by imggion** [comment] 2022-03-08 01:56
Hello,
Have you tried with sys.argv[] instead of argparse?

**Comment by bwoodsend** [comment] 2022-03-08 06:11
Duplicate of #6656

**Closed as completed** 2022-03-08 06:10 UTC
Labels: spam
