### ISSUE TITLE
python .dll not found in virtual environment

### ISSUE THREAD

**Issue by isseykun** [pyinstaller/pyinstaller#3942] opened 2018-12-24 16:15 UTC
pyinstaller fails with the following error
```shell
(venv) C:\Users\eth0\Desktop\py>pyinstaller -F dict.py
64 INFO: PyInstaller: 3.5.dev0+5edb4f7de
64 INFO: Python: 3.7.2
64 INFO: Platform: Windows-10-10.0.17763-SP0
64 INFO: wrote C:\Users\eth0\Desktop\py\dict.spec
64 INFO: UPX is not available.
81 INFO: Extending PYTHONPATH with paths
['C:\\Users\\eth0\\Desktop\\py', 'C:\\Users\\eth0\\Desktop\\py']
81 INFO: checking Analysis
82 INFO: Building Analysis because Analysis-00.toc is non existent
84 INFO: Initializing module dependency graph...
87 INFO: Initializing module graph hooks...
90 INFO: Analyzing base_library.zip ...
3887 INFO: running Analysis Analysis-00.toc
3887 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\eth0\desktop\py\venv\scripts\python.exe
3918 INFO: Caching module hooks...
3931 INFO: Analyzing C:\Users\eth0\Desktop\py\dict.py
3936 INFO: Loading module hooks...
3937 INFO: Loading module hook "hook-encodings.py"...
4046 INFO: Loading module hook "hook-pydoc.py"...
4046 INFO: Loading module hook "hook-xml.py"...
4341 INFO: Looking for ctypes DLLs
4341 INFO: Analyzing run-time hooks ...
4357 INFO: Looking for dynamic libraries
4404 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_ssl.pyd
4446 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_ssl.pyd
4489 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4520 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4551 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4582 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4614 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4667 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_hashlib.pyd
4714 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_lzma.pyd
4745 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_lzma.pyd
4792 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_socket.pyd
4839 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4875 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4908 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4940 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4985 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
5019 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\unicodedata.pyd
5050 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\unicodedata.pyd
5095 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\unicodedata.pyd
5126 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\select.pyd
5189 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5232 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5263 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5289 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5321 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5352 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5399 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5430 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5462 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
6440 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6471 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6502 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6541 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6572 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6603 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6650 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6688 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6720 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6751 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6947 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
6976 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7008 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7039 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7077 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7112 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7148 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7165 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7196 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7243 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7270 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7301 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7301 INFO: Looking for eggs
7301 INFO: Using Python library C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7301 INFO: Found binding redirects:
[]
7317 INFO: Warnings written to C:\Users\eth0\Desktop\py\build\dict\warn-dict.txt
7371 INFO: Graph cross-reference written to C:\Users\eth0\Desktop\py\build\dict\xref-dict.html
7402 INFO: checking PYZ
7402 INFO: Building PYZ because PYZ-00.toc is non existent
7402 INFO: Building PYZ (ZlibArchive) C:\Users\eth0\Desktop\py\build\dict\PYZ-00.pyz
8177 INFO: Building PYZ (ZlibArchive) C:\Users\eth0\Desktop\py\build\dict\PYZ-00.pyz completed successfully.
8208 INFO: checking PKG
8209 INFO: Building PKG because PKG-00.toc is non existent
8210 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "C:\Users\eth0\Desktop\py\venv\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5.dev0+5edb4f7de', 'console_scripts', 'pyinstaller')()
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\eth0\Desktop\py\dict.spec", line 32, in <module>
    console=True )
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\api.py", line 424, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\api.py", line 196, in __init__
    self.__postinit__()
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\api.py", line 273, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
I have been trying to get this work on windows10 running Python 3.7.2 (x32)

The following are the packages installed
```shell
Package        Version
-------------- ------------------
altgraph       0.16.1
certifi        2018.11.29
chardet        3.0.4
future         0.17.1
idna           2.8
macholib       1.11
pefile         2018.8.8
pip            18.1
PyInstaller    3.5.dev0+5edb4f7de
pypiwin32      223
pywin32        224
pywin32-ctypes 0.2.0
requests       2.21.0
setuptools     40.6.2
urllib3        1.24.1
```

**Comment by isseykun** [comment] 2018-12-25 06:18
It turns out the fail happens while inside the venv. It works once venv is deactivated. If so, how to get this working inside the venv? I do have my PATHS (python scripts and python root folder) defined as well but that doesn't seems to help inside venv.

**Comment by everttrollip** [comment] 2018-12-28 07:50
I am having the same issues, with Python 3.7. The following packages are installed in my virtual env: 

```
altgraph==0.16.1
certifi==2018.11.29
chardet==3.0.4
docopt==0.6.2
future==0.17.1
idna==2.8
macholib==1.11
pefile==2018.8.8
PyInstaller==3.4
pywin32-ctypes==0.2.0
requests==2.21.0
urllib3==1.24.1
xmltodict==0.11.0
yarg==0.1.9
```

**Comment by isseykun** [comment] 2018-12-29 11:14
@everttrollip the only way I figured out to built the single executable was to exit out of the virtual environment and the attempt to compile. That means you must have pyinstaller installed in your python install. After that just cd into the app folder and attempt to create the executable. don't enable the vevn. let me know if that helps.

**Comment by everttrollip** [comment] 2018-12-29 11:16
@isseykun I did exactly that and it worked fine. Just doesn't sound right that it won't work inside of a virtual environment.

**Comment by isseykun** [comment] 2018-12-29 11:38
@everttrollip I couldn't figure out as to why it won't work within the env. must be due to some PATH issues that pyinstaller is unable to locate. I tried setting the variables and didn't help. Even installed the python into C:\python and didn't help either. I'm hoping the maintainers would be able to shed some light as to why. As for me, out of env, it seems to work perfectly and gets the job done. half happy :sweat_smile:

**Comment by Loran425** [comment] 2018-12-30 12:12
Same issue here,

After a good deal of digging it appears to be caused by a change in the cpython implementation of virtual environments. Prior to version 3.7 the `python.exe` in virtual environments had a reference to the base `pythonXY.dll` in its PE Header that appears to have been replaced with a reference to `VERSION.dll`. I'm working on a hacky looking patch for the moment but i'm still checking to see if the hack breaks anything else or if there is a better way to reference back to the original dll.

**Comment by isseykun** [comment] 2018-12-30 16:20
@Loran425 awesome find 👍 Do share your results. It seems we won't be the only ones with the issue when working with py version 3.7

**Comment by htgoebel** [comment] 2019-01-02 13:07
@Loran425 Thansk for tracking this down:-)

**Comment by Senpos** [comment] 2019-01-19 08:53
@Wooble 
Experienced the same problem with venv created by `poetry`. But I am not sure what implementation of venv it uses exactly.

**Comment by Wooble** [comment] 2019-01-19 15:40
@senpos poetry does use venv instead of virtualenv in Python 3, so that would be consistent with what I'm seeing.

**Comment by robert914** [comment] 2019-01-25 05:13
I just ran into this exact problem on my Windows 10 system using Python 3.7.2 and Pyinstaller 3.4. I can get my application to build properly if I install all the packages in my main Python install, but it errors out with the above mentioned error when using a venv created with "python -m venv". Hope there is a fix soon for this, as I don't want to pollute my system install with packages (i.e. reason to use venv in the first place :) )

**Comment by Loran425** [comment] 2019-01-25 14:35
@robert914 I'd give the virtualenv method mentioned above by @wobble a shot for now as it appears to work without any extra work. If that doesn't work for you there is a PR in this thread that I wrote and it fixed the issue for me if you don't mind tweaking your local install.

**Comment by robert914** [comment] 2019-01-25 17:11
@Loran425 I missed that there was a PR fix for this. I may give that a try until the upstream gets officially fixed. Thanks!

As a side note, I found that when I create a new venv and upgrade PIP to 19.0.0.1, then pyinstaller no longer installs. I have to leave PIP at 18.1 and it installs fine (this is all on Windows 10). So something in PIP has broken the pyinstaller as well. Anyone else seeing this recently? I probably should open another ticket, but wasn't sure if it was a PIP problem, or a pyinstaller problem. :/

**Comment by robert914** [comment] 2019-01-25 22:38
@Loran425 I can confirm, your patch of the PyInstaller/depend/bindepend.py file worked for me! I can deal with this minor fix since it only lives in my venv for the time being. Thanks again!

**Comment by htgoebel** [comment] 2019-01-30 23:20
@robert914 Thanks for confirming.

**Comment by hyatt-e** [comment] 2019-02-06 16:05
I'm having this issue even when using pyinstaller inside a virtualenv, as well as venv.
Python 3.7.1, virtualenv 16.1, PyInstaller 3.4

**Comment by hyatt-e** [comment] 2019-02-06 16:16
Added @Loran425 patch but it did not solve the issue

**Comment by lstolcman** [comment] 2019-04-01 10:52
@htgoebel The patch submitted by @Loran425 is working for me too (win10, build 1903). Please merge

**Closed** 2019-05-12 05:23 UTC
Labels: PY3.7, Windows

**Comment by janheindejong** [comment] 2019-06-03 12:30
Hi all, 

Any idea when the a new version will be released. This PR made my life a lot easier, and being able to install PyInstaller from PyPi.org again would be awesome!

**Comment by logan-pugh** [comment] 2019-06-04 20:20
I've not seen it mentioned in this thread, but the workaround of using `virtualenv` instead of `venv` only works if you specifically install version `16.1.0` into your global Python site packages due to https://github.com/pyinstaller/pyinstaller/issues/4064.

Here's also hoping for a new release soon!

**Comment by saadkmustafa** [comment] 2020-07-17 08:34
I am getting the same error using cx_Freeze, any suggestions?
