### ISSUE TITLE
Cross Building the Bootloader for MIPS

### ISSUE THREAD

**Issue by andy121090** [pyinstaller/pyinstaller#7552] opened 2023-04-08 21:10 UTC
## Description of the issue

According to the [docs](https://pyinstaller.org/en/stable/bootloader-building.html) it is possible to cross-build the bootloader for other architectures like MIPS.
Following the referenced [Dockerfile](https://github.com/pyinstaller/pyinstaller/blob/v5.9.0/bootloader/Dockerfile) first I get the error about the missing `zlib`, although it is installed `apt-get install zlib1g-dev`:

```
root@ubuntu-pyinstaller:~/home/pyinstaller# docker run -v "$PWD:/io" -t bob-the-build-image
'all' finished successfully (0.000s)
'distclean' finished successfully (0.002s)
Setting top to                           : /io/bootloader 
Setting out to                           : /io/bootloader/build 
Python Version                           : 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] 
Checking for 'gcc' (C compiler)          : /usr/xcc/mips-unknown-linux-gnu/bin/mips-unknown-linux-gnu-gcc 
Checking size of pointer                 : 4 
Platform                                 : Linux-32bit-mips detected based on compiler 
Checking for compiler flags -m32         : no 
Checking for linker flags -m32           : no 
Checking for library dl                  : yes 
Checking for library pthread             : yes 
Checking for library m                   : yes 
Checking for library z                   : no 
The zlib development package is either missing or the shared library cannot be linked against. For security (and marginally better filesize), you should install the zlib-dev or zlib-devel packages with your system package manager, and try again. If you cannot do this (for example, distributions such as OpenWRT use sstrip on libraries, making linking impossible), then either use the --static-zlib option or set the PYI_STATIC_ZLIB=1 environment variable. If you are installing directly with pip, then use the environment variable.
(complete log in /io/bootloader/build/config.log)
```

Since my goal is to use this in OpenWRT, I set `PYI_STATIC_ZLIB=1` and then the error is:

```
root@ubuntu-pyinstaller:~/home/pyinstaller# docker run -v "$PWD:/io" -e PYI_STATIC_ZLIB=1 -t bob-the-build-image
'all' finished successfully (0.000s)
'distclean' finished successfully (0.002s)
Setting top to                           : /io/bootloader 
Setting out to                           : /io/bootloader/build 
Python Version                           : 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] 
Checking for 'gcc' (C compiler)          : /usr/xcc/mips-unknown-linux-gnu/bin/mips-unknown-linux-gnu-gcc 
Checking size of pointer                 : 4 
Platform                                 : Linux-32bit-mips detected based on compiler 
Checking for compiler flags -m32         : no 
Checking for linker flags -m32           : no 
Checking for library dl                  : yes 
Checking for library pthread             : yes 
Checking for library m                   : yes 
Build tests                              : disabled 
Checking for function unsetenv           : yes 
Checking for function mkdtemp            : yes 
Checking for function dirname            : yes 
Checking for function basename           : yes 
Checking for function strndup            : yes 
Checking for function strnlen            : yes 
Checking for compiler flags -Wl,--as-needed : yes 
Checking for program 'strip'                : /usr/bin/strip 
Checking for program 'strip'                : /usr/bin/strip 
'configure' finished successfully (0.548s)
'make_all' finished successfully (0.004s)
Waf: Entering directory `/io/bootloader/build/debug'
[ 1/22] Compiling zlib/zutil.c
[ 2/22] Compiling zlib/inffast.c
[ 3/22] Compiling zlib/adler32.c
[ 4/22] Compiling zlib/inftrees.c
[ 5/22] Compiling zlib/inflate.c
[ 6/22] Compiling zlib/crc32.c
[ 7/22] Compiling src/pyi_exception_dialog.c
[ 8/22] Compiling src/pyi_main.c
[ 9/22] Compiling src/pyi_global.c
[10/22] Compiling src/pyi_path.c
[11/22] Compiling src/pyi_archive.c
[12/22] Compiling src/pyi_splashlib.c
[13/22] Compiling src/pyi_win32_utils.c
[14/22] Compiling src/pyi_launch.c
[15/22] Compiling src/pyi_utils.c
[16/22] Compiling src/pyi_python.c
[17/22] Compiling src/pyi_apple_events.c
[18/22] Compiling src/pyi_pythonlib.c
[19/22] Compiling src/pyi_splash.c
[20/22] Compiling src/main.c
[21/22] Linking build/debug/run_d
[22/22] Processing build/debug/run_d
/usr/bin/strip: Unable to recognise the format of the input file `run_d'

Waf: Leaving directory `/io/bootloader/build/debug'
Build failed
 -> task in 'run_d' failed with exit status 1 (run with -v to display more information)
```

Any suggestions to resolve this issue?

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.9.0```
* Version of Python: 3.10.6
* Platform:  Ubuntu 22.04 (LTS) x64
* Also tried on macOS 11.7.2, same error.

**Comment by bwoodsend** [comment] 2023-04-08 21:17
`apt-get install` isn't going to help you here because you need zlib installed into the cross compiler's prefix rather than the system wide one. The problem is that that prefix changes often. Which base image are you using? (i.e. what did you set `--build-arg BASE=...` to?)

**Comment by andy121090** [comment] 2023-04-08 21:20
I used the base image `dockcross/linux-mips`. The full command was: 
```
docker build --build-arg BASE=dockcross/linux-mips -t bob-the-build-image ./bootloader
```

How could I link the zlib to the cross compiles's prefix?

**Comment by bwoodsend** [comment] 2023-04-08 21:32
`linux-mips` is a Debian image using glibc whereas OpenWRT uses musl so anything you build on that image will not run on OpenWRT. You'll need to pick a musl variant (of which dockcross doesn't appear to have any).

That said, what do you intend to build your application on once you have a working bootloader? Whatever it is, it'll most likely be a lot easier to build the bootloader on that than to cross compile.

**Comment by andy121090** [comment] 2023-04-08 21:58
Actually, I tried to build the application on the image `openwrtorg/rootfs:mips_24kc` as described here: https://github.com/pyinstaller/pyinstaller/issues/4766
However, no container can be started from this image. So now I try to cross-compile the bootloader and then the application following the OpenWRT guide (https://openwrt.org/docs/guide-developer/toolchain/crosscompile).

**Comment by bwoodsend** [comment] 2023-04-08 22:38
`openwrtorg/rootfs:mips_24kc` works well for me. Do you have qemu set up for docker?

**Comment by bwoodsend** [comment] 2023-04-08 22:44
Although it's impossible to build the bootloader on it after all due to OpenWRT's sstrip policy... :roll_eyes:

**Comment by andy121090** [comment] 2023-04-08 22:48
> `openwrtorg/rootfs:mips_24kc` works well for me. Do you have qemu set up for docker?

No, how could this be done?

**Comment by bwoodsend** [comment] 2023-04-08 22:51
Install whatever package provides `/usr/bin/qemu-mips-static` on Ubuntu then run
```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
```

**Comment by bwoodsend** [comment] 2023-04-08 22:52
If you're using docker desktop on macOS, that should have qemu set up already.

**Comment by bwoodsend** [comment] 2023-04-08 23:00
I'm having a go at building the bootloader on `openwrtorg/sdk:mips_24kc-openwrt-22.03`. I'll get back to you in about 10 years once it's finished downloading...

**Comment by bwoodsend** [comment] 2023-04-09 14:23
Yeah, that's worked. I've put it all together into a dockerfile. It compiled a PyInstaller wheel in `openwrtorg/sdk` then installs PyInstaller into a MIPS `openwrtorg/rootfs` container. I did need to patch PyInstaller's build setup since I see its *build a non standard wheel* path it broken so it's pulling PyInstaller from a custom GitHub branch instead of a real release.

```dockerfile
# Dockerfile
FROM openwrtorg/sdk:mips_24kc-openwrt-22.03 AS wheel_builder

WORKDIR /home/build/pyinstaller
RUN curl -L https://github.com/bwoodsend/pyinstaller/archive/refs/heads/mips.tar.gz | tar xz --strip-components=1
RUN rm -r PyInstaller/bootloader/*
RUN ln /home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-strip /home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/strip
RUN CC=/home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-gcc PYI_STATIC_ZLIB=1 python3 setup.py bdist_wheel

FROM openwrtorg/rootfs:mips_24kc

RUN mkdir -p /var/lock
RUN opkg update && opkg install python3-pip binutils
RUN mkdir /io
WORKDIR /io
CMD ash
COPY --from=wheel_builder /home/build/pyinstaller/dist/ /wheels
RUN pip install /wheels/pyinstaller-*.whl
```

Dump that Dockerfile into the root of whichever project you want to build, then run from the root of that project:
```bash
docker build -t openwrt-mips .
docker run -v "$PWD:/io" -it openwrt-mips
pyinstaller your-code.py
```

**Comment by andy121090** [comment] 2023-04-10 07:31
> Install whatever package provides `/usr/bin/qemu-mips-static` on Ubuntu then run
> 
> ```
> docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
> ```

After I ran this, the error changed to:

```
$ docker run -it --rm openwrtorg/rootfs:mips_24kc
qemu-mipsn32-static: /sbin/init: Invalid ELF image for this architecture
```

It seems that I still did not manage to set up qemu correctly. Also running the Dockerfile, returns an error:

```
$ docker build -t openwrt-mips .
[+] Building 0.6s (9/17)                                                                                                
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 869B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/openwrtorg/rootfs:mips_24kc                                             0.0s
 => [internal] load metadata for docker.io/openwrtorg/sdk:mips_24kc-openwrt-22.03                                  0.0s
 => [stage-1 1/7] FROM docker.io/openwrtorg/rootfs:mips_24kc                                                       0.0s
 => [wheel_builder 1/6] FROM docker.io/openwrtorg/sdk:mips_24kc-openwrt-22.03                                      0.2s
 => ERROR [stage-1 2/7] RUN mkdir -p /var/lock                                                                     0.3s
 => [wheel_builder 2/6] WORKDIR /home/build/pyinstaller                                                            0.1s
 => CANCELED [wheel_builder 3/6] RUN curl -L https://github.com/bwoodsend/pyinstaller/archive/refs/heads/mips.tar  0.3s
------
 > [stage-1 2/7] RUN mkdir -p /var/lock:
#5 0.311 exec /bin/sh: exec format error
------
executor failed running [/bin/sh -c mkdir -p /var/lock]: exit code: 1
```

It seems that Docker with QEMU uses the wrong image: `qemu-mipsn32-static`. Which image is used in your case?

**Comment by bwoodsend** [comment] 2023-04-10 21:51
> exec /bin/sh: exec format error

That's the *qemu isn't set up properly* error message. I don't know which goat you need to sacrifice on Ubuntu to setup qemu right. Mine appears to be using `qemu-mips-static`.

**Comment by bwoodsend** [comment] 2023-04-10 21:51
> exec /bin/sh: exec format error

That's the *qemu isn't set up properly* error message. I don't know which goat you need to sacrifice on Ubuntu to setup qemu right. Mine appears to be using `qemu-mips-static`.

**Comment by andy121090** [comment] 2023-04-12 16:12
I tried on a different machine and I get the same error:

```
# apt-get update
# apt-get install qemu-user-static
# apt-get install binfmt-support
# ls /usr/bin/ | grep -i qemu-mips-static
qemu-mips-static
# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
# docker run -it --rm openwrtorg/rootfs:mips_24kc
qemu-mipsn32-static: /sbin/init: Invalid ELF image for this architecture
failed to resize tty, using default size
```

Somehow it tries to use `qemu-mipsn32-static` instead of `qemu-mips-static`. Are you using the latest Docker images?

**Comment by bwoodsend** [comment] 2023-04-12 18:55
```bash
$ docker images | grep -E 'multiarch/qemu-user-static|openwrtorg/rootfs|openwrtorg/sdk'
openwrtorg/rootfs                    mips_24kc                 c5369bccd27f   5 days ago      12.4MB
openwrtorg/sdk                       mips_24kc-openwrt-22.03   ee466503f8ef   9 days ago      2.01GB
multiarch/qemu-user-static           latest                    3539aaa87393   2 months ago    305MB
```

**Comment by bwoodsend** [comment] 2023-04-12 18:56
Oh hello. Now I'm getting that error too.

**Comment by andy121090** [comment] 2023-04-13 16:17
Any idea what has changed? Did you pull the newest images or reinstall qemu?

**Comment by bwoodsend** [comment] 2023-04-22 15:46
I think it's actually docker itself that's changed. Every Docker image has to declare its architecture somewhere in its metadata. Those `openwrt/rootfs` are misconfigured.
```bash
$ docker image inspect openwrtorg/rootfs:mips_24kc | jq '.[].Architecture'
"amd64"  # <-- Should say mips
```
It used to be that Docker only half hardheartedly enforced this (not sure if it was by design or a bug). If you ran `docker pull --platform=aarch64 alpine` then `docker run --platform=x86_64 alpine`, the run command would still create an `aarch64` container. That all changed about a or two week ago and I'm guessing that the ability to pretend that this `amd64` labelled `mips_24kc` image is indeed a `mips_24kc` image went with it.

I'll see if I can find where to report to openwrt that they need to declare their `mips_24kc` images as such.

**Comment by andy121090** [comment] 2023-04-29 12:11
Assuming that the `mips_24kc` image was labelled wrong, I changed the metadata of the image from `amd64` to `mips`. However, I get still the same error:

```
$ docker image inspect openwrtorg/rootfs:mips_24kc | jq '.[].Architecture'
"amd64"
$ docker save openwrtorg/rootfs:mips_24kc > rootfs_mips.tar
$ tar -xvf rootfs_mips.tar
$ rm -rf rootfs_mips.tar
$ vi 7be0*/json  # <-- changed amd64 to mips
$ vi 7b56*.json  # <-- changed amd64 to mips
$ tar -cvf /home/rootfs_mips.tar .
$ cat /home/rootfs_mips.tar | docker load
$ docker image inspect openwrtorg/rootfs:mips_24kc | jq '.[].Architecture'
"mips"
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
$ docker run -it --rm openwrtorg/rootfs:mips_24kc
qemu-mipsn32-static: /sbin/init: Invalid ELF image for this architecture
```

I could not find any hints in the changelog of Docker. Also there seem to be no images on DockerHub that are labelled as "mips".

**Comment by bwoodsend** [comment] 2023-04-29 12:28
Sorry, I should have posted back here. See https://github.com/openwrt/docker/issues/112#issuecomment-1519099490. tl;dr is that even with the platform set properly, mips specifically has other issues that the rest of the architectures don't.

**Comment by andy121090** [comment] 2023-05-10 09:11
Finally, this workaround did it:

1. Build PyInstaller wheel according to https://github.com/pyinstaller/pyinstaller/issues/7552#issuecomment-1501140863  in a Docker container
```
$ docker run -it --name wheelbuilder openwrtorg/sdk:mips_24kc-openwrt-22.03
# cd
# mkdir pyinstaller
# cd pyinstaller/
# curl -L https://github.com/bwoodsend/pyinstaller/archive/refs/heads/mips.tar.gz | tar xz --strip-components=1
# rm -r PyInstaller/bootloader/*
# ln /home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-strip /home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/strip
# CC=/home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-gcc PYI_STATIC_ZLIB=1 python3 setup.py bdist_wheel
# ls dist/
pyinstaller-5.9.0-py3-none-any.whl
```
2. Download and start OpenWrt MIPS image with QEMU (and set up network connection)
```
$ wget https://downloads.openwrt.org/releases/22.03.3/targets/malta/be/openwrt-22.03.3-malta-be-vmlinux-initramfs.elf
$ qemu-system-mips -kernel openwrt-22.03.3-malta-be-vmlinux-initramfs.elf -nographic -m 2048
# ip route add default via 10.0.2.2 dev br-lan onlink
# ip link del br-lan
# udhcpc -i eth0
# echo nameserver 10.0.2.3 > /etc/resolv.conf
```
3. Copy PyInstaller wheel to QEMU guest
4. Install PyInstaller
```
# opkg update
# opkg install python3-pip binutils
# pip -V
pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)
# pip install pyinstaller-5.9.0-py3-none-any.whl
```
5. Test
```
# echo 'print("hello")' > test.py
# pyinstaller -F test.py
# ./dist/test
hello
```

**Comment by bwoodsend** [comment] 2023-05-11 21:40
That's quite a neat way of doing it. I didn't realise qemu could run an initramfs.

**Comment by bwoodsend** [comment] 2023-05-17 18:30
Apparently on Debian/Ubuntu, running [this](https://github.com/openwrt/docker/pull/113/files#diff-19560c84548a42e84d08fea824c8d1aff05ede2f21a9cb0c5a18ca93791469feR286-R288) should let you run MIPS in Docker. On any other Linux distribution, [it's more complicated](https://github.com/openwrt/docker/pull/113#issuecomment-1548667952).

**Comment by bwoodsend** [comment] 2023-06-19 22:59
> I did need to patch PyInstaller's build setup since I see its build a non standard wheel path it broken so it's pulling PyInstaller from a custom GitHub branch instead of a real release.

I was wrong here. The correct setuptools configuration is there but the *collect all bootloaders by default* logic is in the `setup.cfg` file rather than `setup.py` and the ancient version of setuptools on `openwrtorg/sdk:mips_24kc-openwrt-22.03` predates support for the `setup.cfg` file so anything in it gets ignored. The easiest fix is to replace usin `setup.py bdist_wheel` with `pip wheel` which automatically runs the build in a virtualenv with latest versions of build dependencies.

So in your wheel building stage, some change like this will get you back onto mainstream released PyInstaller:

```diff
- curl -L https://github.com/bwoodsend/pyinstaller/archive/refs/heads/mips.tar.gz | tar xz --strip-components=1
+ pip download --no-binary=:all: --no-deps --no-build-isolation pyinstaller
+ tar xf pyinstaller-*.tar.gz --strip-components=1
...
- CC=/home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-gcc PYI_STATIC_ZLIB=1 python3 setup.py bdist_wheel 
+ CC=/home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-gcc PYI_STATIC_ZLIB=1 pip wheel -w dist --no-deps .
```

**Comment by phpaiva** [comment] 2024-10-08 04:47
> Finally, this workaround did it:
> 
> 1. Build PyInstaller wheel according to [Cross Building the Bootloader for MIPS #7552 (comment)](https://github.com/pyinstaller/pyinstaller/issues/7552#issuecomment-1501140863)  in a Docker container
> 
> ```
> $ docker run -it --name wheelbuilder openwrtorg/sdk:mips_24kc-openwrt-22.03
> # cd
> # mkdir pyinstaller
> # cd pyinstaller/
> # curl -L https://github.com/bwoodsend/pyinstaller/archive/refs/heads/mips.tar.gz | tar xz --strip-components=1
> # rm -r PyInstaller/bootloader/*
> # ln /home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-strip /home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/strip
> # CC=/home/build/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/bin/mips-openwrt-linux-gcc PYI_STATIC_ZLIB=1 python3 setup.py bdist_wheel
> # ls dist/
> pyinstaller-5.9.0-py3-none-any.whl
> ```
> 
> 2. Download and start OpenWrt MIPS image with QEMU (and set up network connection)
> 
> ```
> $ wget https://downloads.openwrt.org/releases/22.03.3/targets/malta/be/openwrt-22.03.3-malta-be-vmlinux-initramfs.elf
> $ qemu-system-mips -kernel openwrt-22.03.3-malta-be-vmlinux-initramfs.elf -nographic -m 2048
> # ip route add default via 10.0.2.2 dev br-lan onlink
> # ip link del br-lan
> # udhcpc -i eth0
> # echo nameserver 10.0.2.3 > /etc/resolv.conf
> ```
> 
> 3. Copy PyInstaller wheel to QEMU guest
> 4. Install PyInstaller
> 
> ```
> # opkg update
> # opkg install python3-pip binutils
> # pip -V
> pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)
> # pip install pyinstaller-5.9.0-py3-none-any.whl
> ```
> 
> 5. Test
> 
> ```
> # echo 'print("hello")' > test.py
> # pyinstaller -F test.py
> # ./dist/test
> hello
> ```

I don't understand the first step, why do I need Docker when I can run a VM using QEMU. And also don't get what are you doing there anyway and how the .whl is being generated.

**Comment by bwoodsend** [comment] 2024-10-08 12:04
I think now you should be able to just run `PYI_STATIC_ZLIB=1 pip install pyinstaller` in the qemu image and skip the Docker container.

**Comment by phpaiva** [comment] 2024-10-08 12:42
> I think now you should be able to just run `PYI_STATIC_ZLIB=1 pip install pyinstaller` in the qemu image and skip the Docker container.

Thanks for you answer @bwoodsend , but I get the same:

```
root@OpenWrt:/# PYI_STATIC_ZLIB=1 pip3 install pyinstaller
Collecting pyinstaller
  Downloading pyinstaller-6.10.0.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 869.4 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting setuptools>=42.0.0 (from pyinstaller)
  Obtaining dependency information for setuptools>=42.0.0 from https://files.pythonhosted.org/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl.metadata
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Collecting altgraph (from pyinstaller)
  Obtaining dependency information for altgraph from https://files.pythonhosted.org/packages/4d/3f/3bc3f1d83f6e4a7fcb834d3720544ca597590425be5ba9db032b2bf322a2/altgraph-0.17.4-py2.py3-none-any.whl.metadata
  Downloading altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting pyinstaller-hooks-contrib>=2024.8 (from pyinstaller)
  Obtaining dependency information for pyinstaller-hooks-contrib>=2024.8 from https://files.pythonhosted.org/packages/a0/8f/a7eb7b85ea2015d1c9a8c1686eaeb61f3ce35e1047fc03c0ac71d22d68f2/pyinstaller_hooks_contrib-2024.8-py3-none-any.whl.metadata
  Downloading pyinstaller_hooks_contrib-2024.8-py3-none-any.whl.metadata (16 kB)
Collecting packaging>=22.0 (from pyinstaller)
  Obtaining dependency information for packaging>=22.0 from https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl.metadata
  Downloading packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Downloading packaging-24.1-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 kB 348.6 kB/s eta 0:00:00
Downloading pyinstaller_hooks_contrib-2024.8-py3-none-any.whl (322 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.8/322.8 kB 229.5 kB/s eta 0:00:00
Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
Downloading altgraph-0.17.4-py2.py3-none-any.whl (21 kB)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyinstaller (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_bootloader
      No precompiled bootloader found or compile forced. Trying to compile the bootloader for you ...
      Setting top to                           : /tmp/pip-install-7697ulpx/pyinstaller_ac00d0fe5ba14f58b15b20eb8916ecc4/bootloader
      Setting out to                           : /tmp/pip-install-7697ulpx/pyinstaller_ac00d0fe5ba14f58b15b20eb8916ecc4/bootloader/build
      Python Version                           : 3.11.7 (main, Sep 28 2024, 16:33:21) [GCC 12.3.0]
      MSVC target(s)                           : not found
      Checking for 'gcc' (C compiler)          : /usr/bin/gcc
      Checking size of pointer                 : 4
      Platform                                 : Linux-32bit-mips detected based on compiler
      Checking for compiler flags -m32         : no
      Checking for linker flags -m32           : no
      Checking for compiler flags -Wno-error=unused-but-set-variable : yes
      Checking for library dl                                        : not found
      The configuration failed
      (complete log in /tmp/pip-install-7697ulpx/pyinstaller_ac00d0fe5ba14f58b15b20eb8916ecc4/bootloader/build/config.log)
      ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyinstaller
Failed to build pyinstaller
ERROR: Could not build wheels for pyinstaller, which is required to install pyproject.toml-based projects
```

**Comment by bwoodsend** [comment] 2024-10-08 15:55
Hmm, I had it in my head that `libm` and `libdl` were baked into `libc` on musl based distributions, with symlinks to make it look like they still exist. I'll try and remember to take a look tonight...

**Comment by phpaiva** [comment] 2024-10-08 16:01
> Hmm, I had it in my head that `libm` and `libdl` were baked into `libc` on musl based distributions, with symlinks to make it look like they still exist. I'll try and remember to take a look tonight...

Building a Malta with glibc instead musl could do the trick?

**Comment by rokm** [comment] 2024-10-08 16:43
> Hmm, I had it in my head that `libm` and `libdl` were baked into `libc` on musl based distributions, with symlinks to make it look like they still exist.

I think both glibc and musl have moved `dlopen`, `dlsym`, etc. into base libc, and keep around empty archives (e.g., `libdl.a`) to conform to POSIX standard that mandates linking against `-ldl`.

@phpaiva can you compile a basic program that uses `dlopen` on that system?

```c
// dlopen_example.c
#include <stdio.h>
#include <dlfcn.h>

int main (int argc, char** argv)
{
    void *handle;

    if (argc != 2) {
        fprintf(stderr, "Usage: %s <lib_name>\n", argv[0]);
        return -1;
    }

    handle = dlopen(argv[1], RTLD_NOW);
    fprintf(stderr, "Library handle: %p\n", handle);
    dlclose(handle);

    return 0;
}
```

```shell
gcc -o dlopen_example dlopen_example.c
```

If this works, then `-ldl` is not necessary.

If the following fails, then the `libdl.a` is likely missing from the system (I suppose it might not even be packaged by openwrt):

```shell
gcc -o dlopen_example dlopen_example.c -ldl
```

I guess we could rework the `waf` check to see if `-ldl` is necessary at all, and if not, omit it.

**Comment by rokm** [comment] 2024-10-08 16:58
As a work-around, you could also try creating empty `libdl.a` archive yourself:

These are contents of the file in alpine container (where it is available):
```
# hexdump -X /usr/lib/libdl.a 
0000000  21  3c  61  72  63  68  3e  0a                                
0000008
```

One way to create empty archive:
```
# touch empty

# ar r empty.a empty
/usr/bin/ar: creating empty.a

# ar t empty.a
empty

# ar d empty.a empty

# ar t empty.a

# hexdump -X empty.a 
0000000  21  3c  61  72  63  68  3e  0a                                
0000008
```

Then try renaming `empty.a` to `libdl.a` and moving it to `/lib` or  `/usr/lib`.

**Comment by phpaiva** [comment] 2024-10-08 17:06
Thanks @rokm , I will be trying all of this and come back with news.

**Comment by phpaiva** [comment] 2024-10-08 21:10
Well, now it started to work, this is a brief of all that has been done:

**As indicated**

```
touch empty
ar r empty.a empty
ar t empty.a
ar d empty.a empty
ar t empty.a
mv empty.a libdl.a
cp libdl.a /lib/
cp libdl.a /usr/lib/
```

Well... if there is an issue also finding this "pthread", why not this again?

```
touch empty
ar r empty.a empty
ar t empty.a
ar d empty.a empty
ar t empty.a
mv empty.a libpthread.a
cp libpthread.a /lib/
cp libpthread.a /usr/lib/
```

Also an issue of "not found" with "zlib" but this time zlib can be installed, the error is different:

```
      Checking for library z                                         : no
      The zlib development package is either missing or the shared library cannot be linked against. For security (and marginally better filesize), you should install the zlib-dev or zlib-devel packages with your system package manager, and try again. If you cannot do this (for example, distributions such as OpenWRT use sstrip on libraries, making linking impossible), then either use the --static-zlib option or set the PYI_STATIC_ZLIB=1 environment variable. If you are installing directly with pip, then use the environment variable.
      (complete log in /tmp/pip-install-_zr25lo9/pyinstaller_184e34b3746f4ee0b800b617b466914d/bootloader/build/config.log)
      ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py
```


So...

`opkg install zlib-dev`

Well, still having an issue with that, the error and message is the same. So I tried...

`PYI_STATIC_ZLIB=1 python3 -m pip install pyinstaller`

Now seems to be working, pyinstaller started to work but I need to test deeply. (**EDIT: tested and works really well**)

Thanks both for you contribution, you are saving me yearlifes.

**Comment by bwoodsend** [comment] 2024-10-08 23:44
The `zlib` issue is expected. OpenWRT use `sstrip` on their packages which not only removes the debugging symbols (akin to regular `strip`) but also takes away whatever the linker needs to link dynamically. The `PYI_STATIC_ZLIB` was added in response a previous iteration of this *building on OpenWRT* issue.

**Comment by bwoodsend** [comment] 2024-10-09 00:33
Got it all fired back up again. The libdl stuff is indeed all in libc.

```python
>>> import ctypes
>>> ctypes.CDLL(None).dlopen
<_FuncPtr object at 0x2bc3bf10>
```

It looks like just relaxing [the libdl check](https://github.com/pyinstaller/pyinstaller/blob/0c55c31ad9f3f9958d48ffc3be5c0fc8bb029d8b/bootloader/wscript#L617) is the right thing to do. Perhaps make it not mandatory but make pthread mandatory if libdl is found?

**Comment by rokm** [comment] 2024-10-09 18:55
> It looks like just relaxing [the libdl check](https://github.com/pyinstaller/pyinstaller/blob/0c55c31ad9f3f9958d48ffc3be5c0fc8bb029d8b/bootloader/wscript#L617) is the right thing to do. Perhaps make it not mandatory but make pthread mandatory if libdl is found?

Yeah, let's go with that. I'm also fine with making both checks independently optional, since I imagine that either both are available (in one form or another) or both are missing (the OpenWRT case).

**Comment by bwoodsend** [comment] 2024-10-17 23:24
In the latest release, the libdl issue is gone so now you just need:
```bash
opkg install gcc python3-pip binutils
PYI_STATIC_ZLIB=1 pip install pyinstaller
```
in either a `--platform=linux/mips_24kc openwrt/rootfs:mips_24kc` Docker container or one of these `openwrt-22.03.3-malta-be-vmlinux-initramfs.elf` qemu systems.

I think that's as good as we're going to get so I'm going to call this one done.

**Closed as completed by bwoodsend** 2024-10-17 23:24 UTC
Labels: triage
