### ISSUE TITLE
mmrotate

### ISSUE THREAD

**Issue by wcyy0123** [pyinstaller/pyinstaller#7059] opened 2022-09-02 08:40 UTC
When I try pyinstaller mmrotate,this problem occurs:
How can I solve it?
`
(open-mmlab1) 
[75084] WARNING: file already exists but should not: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI750842\torch\_C.cp38-win_amd64.pyd
Traceback (most recent call last):
  File "huge_image_demo.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmdet\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\fileio\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\fileio\file_client.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\__init__.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\env.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\parrots_wrapper.py", line 101, in <module>
  File "mmcv\utils\parrots_wrapper.py", line 71, in _get_extension
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "torch\utils\cpp_extension.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "setuptools\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "_distutils_hack\override.py", line 1, in <module>
  File "_distutils_hack\__init__.py", line 77, in do_override
  File "_distutils_hack\__init__.py", line 64, in ensure_local_distutils
AssertionError: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI750842\distutils\core.pyc
[125408] Failed to execute script 'huge_image_demo' due to unhandled exception!
`

**Comment by wcyy0123** [comment] 2022-09-02 08:45
`(open-mmlab1) D:\master\code\car_detection\mmrotate-main0\mmrotate-main\demo\dist>huge_image_demo.exe
[75084] WARNING: file already exists but should not: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI750842\torch\_C.cp38-win_amd64.pyd

Traceback (most recent call last):

  File "huge_image_demo.py", line 16, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "mmdet\__init__.py", line 2, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "mmcv\__init__.py", line 4, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "mmcv\fileio\__init__.py", line 2, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "mmcv\fileio\file_client.py", line 15, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "mmcv\utils\__init__.py", line 41, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "mmcv\utils\env.py", line 13, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "mmcv\utils\parrots_wrapper.py", line 101, in <module>

  File "mmcv\utils\parrots_wrapper.py", line 71, in _get_extension

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "torch\utils\cpp_extension.py", line 7, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "setuptools\__init__.py", line 8, in <module>

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module

  File "_distutils_hack\override.py", line 1, in <module>

  File "_distutils_hack\__init__.py", line 77, in do_override

  File "_distutils_hack\__init__.py", line 64, in ensure_local_distutils

AssertionError: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI750842\distutils\core.pyc
[125408] Failed to execute script 'huge_image_demo' due to unhandled exception!`

**Comment by wcyy0123** [comment] 2022-09-02 08:45
`
123
123
`

**Comment by wcyy0123** [comment] 2022-09-02 08:46
`
 23
 23
`

**Comment by wcyy0123** [comment] 2022-09-02 08:46
`
23

23
`

**Comment by wcyy0123** [comment] 2022-09-02 08:47
```
io
io
```

**Comment by wcyy0123** [comment] 2022-09-02 08:48
```
(open-mmlab1) D:\master\code\car_detection\mmrotate-main0\mmrotate-main\demo\dist>huge_image_demo.exe
[75084] WARNING: file already exists but should not: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI750842\torch\_C.cp38-win_amd64.pyd
Traceback (most recent call last):
  File "huge_image_demo.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmdet\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\fileio\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\fileio\file_client.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\__init__.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\env.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\parrots_wrapper.py", line 101, in <module>
  File "mmcv\utils\parrots_wrapper.py", line 71, in _get_extension
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "torch\utils\cpp_extension.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "setuptools\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "_distutils_hack\override.py", line 1, in <module>
  File "_distutils_hack\__init__.py", line 77, in do_override
  File "_distutils_hack\__init__.py", line 64, in ensure_local_distutils
AssertionError: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI750842\distutils\core.pyc
[125408] Failed to execute script 'huge_image_demo' due to unhandled exception!
```

**Comment by wcyy0123** [comment] 2022-09-02 08:49
pip list
```
Package                   Version
------------------------- ------------
addict                    2.4.0
altgraph                  0.17.2
certifi                   2022.6.15
charset-normalizer        2.1.1
click                     8.1.3
colorama                  0.4.5
commonmark                0.9.1
cycler                    0.11.0
e2cnn                     0.2.2
fonttools                 4.37.1
future                    0.18.2
idna                      3.3
importlib-metadata        4.12.0
kiwisolver                1.4.4
Markdown                  3.4.1
matplotlib                3.5.3
mmcv-full                 1.6.0
mmdet                     2.25.1
mmrotate                  0.3.2
model-index               0.1.11
mpmath                    1.2.1
numpy                     1.23.2
opencv-python             4.6.0.66
openmim                   0.3.0
ordered-set               4.1.0
packaging                 21.3
pandas                    1.4.4
pefile                    2022.5.30
Pillow                    9.2.0
pip                       22.1.2
pycocotools               2.0.4
Pygments                  2.13.0
pyinstaller               5.3
pyinstaller-hooks-contrib 2022.10
pyparsing                 3.0.9
python-dateutil           2.8.2
pytz                      2022.2.1
pywin32-ctypes            0.2.0
PyYAML                    6.0
regex                     2022.8.17
requests                  2.28.1
rich                      12.5.1
scipy                     1.9.1
setuptools                63.4.1
six                       1.16.0
sympy                     1.11.1
tabulate                  0.8.10
terminaltables            3.1.10
torch                     1.11.0+cu113
torchaudio                0.11.0+cu113
torchvision               0.12.0+cu113
typing_extensions         4.3.0
urllib3                   1.26.12
wheel                     0.37.1
wincertstore              0.2
yapf                      0.32.0
zipp                      3.8.1
```

**Comment by rokm** [comment] 2022-09-02 09:18
Duplicate of #6911. For now, you need to set `SETUPTOOLS_USE_DISTUTILS=stdlib` environment variable before `setuptools` is imported (or whatever is importing `setuptools` - in your case, `torch` that ends up imported via `mmcv`).

For example, add the following at the top of your program:
```python
import os
os.environ['SETUPTOOLS_USE_DISTUTILS'] = 'stdlib'

...
```

**Closed as not planned by rokm** 2022-09-02 09:18 UTC
Labels: solution:duplicate

**Comment by wcyy0123** [comment] 2022-09-02 09:27
I try it. But the problem has not been solved
The code:
```
if __name__ == '__main__':
    os.environ['SETUPTOOLS_USE_DISTUTILS'] = 'stdlib'
```
error:
```
[117864] WARNING: file already exists but should not: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI1178642\torch\_C.cp38-win_amd64.pyd
Traceback (most recent call last):
  File "huge_image_demo.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmdet\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\fileio\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\fileio\file_client.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\__init__.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\env.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\utils\parrots_wrapper.py", line 101, in <module>
  File "mmcv\utils\parrots_wrapper.py", line 71, in _get_extension
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "torch\utils\cpp_extension.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "setuptools\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "_distutils_hack\override.py", line 1, in <module>
  File "_distutils_hack\__init__.py", line 77, in do_override
  File "_distutils_hack\__init__.py", line 64, in ensure_local_distutils
AssertionError: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI1178642\distutils\core.pyc
[116292] Failed to execute script 'huge_image_demo' due to unhandled exception!
```

**Comment by wcyy0123** [comment] 2022-09-02 09:46
After I use
```
import os
os.environ['SETUPTOOLS_USE_DISTUTILS'] = 'stdlib'
```
Another problem occurs. How can I solve it? 
The correct package is mmcv_full. When the package installed is mmcv, the problem occurs:
But when I install mmcv_full and use pyinstaller to pack my code, the problem also occurs:
```
[123000] WARNING: file already exists but should not: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI1230002\torch\_C.cp38-win_amd64.pyd
Traceback (most recent call last):
  File "huge_image_demo.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmdet\apis\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmdet\apis\inference.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\ops\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "mmcv\ops\active_rotated_filter.py", line 10, in <module>
  File "mmcv\utils\ext_loader.py", line 13, in load_ext
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'mmcv._ext'
[115904] Failed to execute script 'huge_image_demo' due to unhandled exception!
```

**Comment by rokm** [comment] 2022-09-02 09:49
> I try it. But the problem has not been solved The code:
> 
> ```
> if __name__ == '__main__':
>     os.environ['SETUPTOOLS_USE_DISTUTILS'] = 'stdlib'
> ```

You need to set the environment variable *before* you import packages that end up importing `torch`. So before line 16 in your `huge_image_demo.py`.

**Comment by rokm** [comment] 2022-09-02 09:52
> The correct package is mmcv_full. When the package installed is mmcv, the problem occurs: But when I install mmcv_full and use pyinstaller to pack my code, the problem also occurs:
> 
> ```
> [123000] WARNING: file already exists but should not: C:\Users\ADMINI~1.DES\AppData\Local\Temp\_MEI1230002\torch\_C.cp38-win_amd64.pyd
> Traceback (most recent call last):
>   File "huge_image_demo.py", line 18, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
>   File "mmdet\apis\__init__.py", line 2, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
>   File "mmdet\apis\inference.py", line 8, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
>   File "mmcv\ops\__init__.py", line 2, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
>   File "mmcv\ops\active_rotated_filter.py", line 10, in <module>
>   File "mmcv\utils\ext_loader.py", line 13, in load_ext
>   File "importlib\__init__.py", line 127, in import_module
> ModuleNotFoundError: No module named 'mmcv._ext'
> [115904] Failed to execute script 'huge_image_demo' due to unhandled exception!
> ```

Use [`--hiddenimport`](https://pyinstaller.org/en/stable/usage.html#cmdoption-hidden-import) to ensure that `mmcv._ext` is collected. I.e., add `--hiddenimport mmcv._ext` to your PyInstaller command.

**Comment by wcyy0123** [comment] 2022-09-02 10:24
Thanks! All the problems have been solved!!!
