### ISSUE TITLE
some programs which maked with pyinstaller open excess console window

### ISSUE THREAD

**Issue by Megido6** [pyinstaller/pyinstaller#1202] opened 2015-03-06 10:06 UTC
I do not know regularity
just one program launch window and others do not
all programs without GUI
they launch a console window !!!
all programs have the same spec filles, except that the names

please look video for understand
https://www.youtube.com/watch?v=sIYGWdmBiys&feature=youtu.be
******************************
run.bat need for save output  after programm close
it contains:

program.exe
pause

********************************

how to remove this window?

**Comment by htgoebel** [comment] 2015-03-09 12:47
Am 06.03.2015 um 11:06 schrieb Megido6:
> all programs have the same spec fillets, except that the names

Please double-check this. Then remove both the build and the dist
directory for a clean rebuild using the latest development snapshot.

If this does not help, I assume the cause of this issue not within
PyInstaller.

-- 
Schönen Gruß
Hartmut Goebel
Dipl.-Informatiker (univ), CISSP, CSSLP
Information Security Management, Security Governance, Secure Software
Development

Goebel Consult, Landshut
http://www.goebel-consult.de

Blog:
http://www.goebel-consult.de/blog/liberario-als-alternative-zum-db-navigator-und-zu-offi

Kolumne:
http://www.cissp-gefluester.de/2011-02-fleisige-datensammler-fur-lukratives-geschaeftsmodell-gesucht

**Comment by htgoebel** [comment] 2015-06-24 11:03
No further comment since three month. closing.
@Megido6 If you have further information, please comment and we'll reopen the ticket.

**Closed by htgoebel** 2015-06-24 11:03 UTC
