### ISSUE TITLE
Encountered "Python library not in binary dependencies" in pyenv environment

### ISSUE THREAD

**Issue by tbhaxor** [pyinstaller/pyinstaller#4643] opened 2020-01-24 06:36 UTC
## Description of the issue
Unable to build the application using in pyenv environment

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0+555c5e8163```
* Version of Python:  3.7.5
* Platform: Manjaro
* Did you also try this on another platform? Does it work there? Yes, it works on my platform too, but with system binaries of python, not with pyenv's python environment. Same steps in fresh docker of arch Linux works...

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
8943 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/home/terabyte/.pyenv/versions/3.7.5/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 729, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 676, in build
    exec(code, spec_namespace)
  File "/home/terabyte/Programs/python/linkedin-ss/app.spec", line 17, in <module>
    noarchive=False)
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 474, in assemble
    self._check_python_library(self.binaries)
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 563, in _check_python_library
    python_lib = bindepend.get_python_library_path()
  File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/depend/bindepend.py", line 948, in get_python_library_path
    raise IOError(msg)
OSError: Python library not found: libpython3.7mu.so.1.0, libpython3.7m.so.1.0, libpython3.7m.so, libpython3.7.so.1.0
    This would mean your Python installation doesn't come with proper library files.
    This usually happens by missing development package, or unsuitable build parameters of Python installation.

    * On Debian/Ubuntu, you would need to install Python development packages
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by jpmn** [comment] 2020-02-04 21:46
I am experiencing the exact same behaviour on python `3.6.8` using `pyenv`, also on Manjaro.

**Comment by tbhaxor** [comment] 2020-02-06 12:57
I also tried [this](https://stackoverflow.com/a/59053725/10362396) method of installation, Still its not working

**Comment by Legorooj** [comment] 2020-02-07 01:00
Please follow the instructions in the traceback:

> * On Debian/Ubuntu, you would need to install Python development packages
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)

**Comment by jpmn** [comment] 2020-02-07 03:08
I will try this from `pyenv` documentation: https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared

**Comment by Legorooj** [comment] 2020-02-07 03:59
@jpmn please let us know about the results. This is looking like a system generated error, nothing PyInstaller can fix.

**Comment by Legorooj** [comment] 2020-02-07 04:03
@tbhaxor did you? Hmm. Is it exactly the same error?

**Comment by tbhaxor** [comment] 2020-02-08 09:54
I had tried all (listed in this issue, from pyenv issues, and stackoverflow's), still same error

**Comment by Legorooj** [comment] 2020-02-08 09:56
> @tbhaxor did you? Hmm. Is it exactly the same error?

How does that comment answer this?

**Comment by tbhaxor** [comment] 2020-02-08 20:31
> > @tbhaxor did you? Hmm. Is it exactly the same error?
> 
> How does that comment answer this? We don't know if this is a PyInstaller error yet, or a `pyenv` one.

Yes I am getting same error :laughing:

**Comment by tbhaxor** [comment] 2020-02-08 20:34
@Legorooj 
With `--enable-shared` the issue still persists, and `--enable-framework` is not working

```
→ env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.7.5
pyenv: /home/terabyte/.pyenv/versions/3.7.5 already exists
continue with installation? (y/N) y
python-build: framework installation is not supported.
```

**Comment by Legorooj** [comment] 2020-02-08 22:09
Thanks. Let me try an reproduce this on my machines. Unfortunately my manjaro one isn't accessable right now :-(

**Comment by tbhaxor** [comment] 2020-02-09 16:10
Try with pyenv and choose the version `3.7.5`

**Comment by Legorooj** [comment] 2020-02-09 22:58
Thanks!

**Comment by tbhaxor** [comment] 2020-02-13 11:14
any updates? i have to use docker for it....

**Comment by Legorooj** [comment] 2020-02-13 22:31
@tbhaxor couple more days...

**Comment by tbhaxor** [comment] 2020-02-14 17:07
@Legorooj  You can use https://github.com/pyenv/pyenv/issues/1504 issue to coordinate with pyenv team if required

**Comment by bjones1** [comment] 2020-02-14 18:12
I'm closing this -- the PyInstaller team lacks the funding and time to support non-standard platforms such as pyenv. However, we would be happy to consider a PR.

**Closed by bjones1** 2020-02-14 18:12 UTC
Labels: @medium, platform:Linux, state:verify

**Comment by umangrajpara99** [comment] 2021-02-15 20:25
solution provided by @Legorooj  worker for me!

**Comment by whisper-a** [comment] 2021-07-08 09:09
> Please follow the instructions in the traceback:
> 
> * On Debian/Ubuntu, you would need to install Python development packages
>   * apt-get install python3-dev
>   * apt-get install python-dev
> * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)

it works for me, thank you very much.

**Comment by StepanGavrilov** [comment] 2021-07-09 10:12
> > Please follow the instructions in the traceback:
> > 
> > * On Debian/Ubuntu, you would need to install Python development packages
> >   
> >   * apt-get install python3-dev
> >   * apt-get install python-dev
> > * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
> 
> it works for me, thank you very much.

you just ./configure --enable-shared?

**Comment by bwoodsend** [comment] 2021-07-09 10:16
Well this issue is specifically about pyenv so [jpmn's answer](https://github.com/pyinstaller/pyinstaller/issues/4643#issuecomment-583213294) is the correct one.

**Comment by StepanGavrilov** [comment] 2021-07-09 10:26
@bwoodsend 

I tryied this

`./configure --enable-optimizations
make -j 2
sudo make altinstall
`

`
./configure --enable-shared
make -j 2
sudo make altinstall
`

but now works for me, I use Debian OS

**Comment by bwoodsend** [comment] 2021-07-09 10:51
Yes but that's not pyenv. You're just building Python from source manually.

**Comment by jpmn** [comment] 2021-07-09 16:51
> @jpmn please let us know about the results. This is looking like a system generated error, nothing PyInstaller can fix.

Sorry I didn't come back to share my results, the birth of my child and WFH because of the pandemic made me switch computer and now I am on Windows and do not experience this issue with pyenv.
