### ISSUE TITLE
Pyinstaller lock exe file while running on windows

### ISSUE THREAD

**Issue by GameproxyYL** [pyinstaller/pyinstaller#1145] opened 2015-01-08 09:52 UTC
Version of python: 2.7 32bit
Version of pyinstall: download from git

How to reproduce:
1: create 1.py, content:

```
import time
time.sleep(99999)
```

2: pack 1.py to 1.exe, run

```
pyinstaller.py 1.py
```

3: execute 1.exe

Then 1.exe cannot be rename while running.

I test py2exe and cx_Freeze they don't have this problem.
I think it's because pyinstaller didn't close file handle of exe after read it needs.

Pyinstaller use fopen not CreateFile so it has the default behavior.
other problem is pyinstaller will inhert file handles to child process but it's not necessarily,
I already test change py_utils.c:520 to FALSE is ok,
but problem still not resolved.

http://en.wikipedia.org/wiki/File_locking
http://msdn.microsoft.com/en-us/library/windows/desktop/aa363858%28v=vs.85%29.aspx
http://msdn.microsoft.com/en-us/library/windows/desktop/ms682425%28v=vs.85%29.aspx

If you still have problem to read this please contact me instead of close, otherwise I will open other again.

**Comment by matysek** [comment] 2015-01-08 10:30
@YueLunGames thanks for detailed report.

**Comment by matysek** [comment] 2015-01-08 14:00
I was able to reproduced this behavior. How it should be fixed?
* just replace fopen calls by CreateFile?

**Comment by YueLunGames** [comment] 2015-01-08 15:30
Resolved.
Here is the patch, but I will not create the pull request because it's dirty fix.
It may decrease performance but will not hold the file handle for long.

```
--- a/bootloader/common/pyi_archive.c.orig
+++ b/bootloader/common/pyi_archive.c
@@ -107,6 +107,15 @@ unsigned char *pyi_arch_extract(ARCHIVE_STATUS *status, TOC *ptoc)
 	unsigned char *data;
 	unsigned char *tmp;
 
+	/* Reopen file handler if need */
+	if (status->fp == NULL) {
+		status->fp = stb_fopen(status->archivename, "rb");
+		if (status->fp == NULL) {
+			VS("LOADER: Cannot open archive: %s\n", status->archivename);
+			return NULL;
+		}
+	}
+
 	fseek(status->fp, status->pkgstart + ntohl(ptoc->pos), SEEK_SET);
 	data = (unsigned char *)malloc(ntohl(ptoc->len));
 	if (data == NULL) {
@@ -127,6 +136,10 @@ unsigned char *pyi_arch_extract(ARCHIVE_STATUS *status, TOC *ptoc)
 			return NULL;
 		}
 	}
+	
+	/* close file handler to avoid locking */
+	fclose(status->fp);
+	status->fp = NULL;
 	return data;
 }
 
@@ -353,6 +366,10 @@ int pyi_arch_open(ARCHIVE_STATUS *status)
 		FATALERROR("Error on file");
 		return -1;
 	}
+	
+	/* Close file handle to avoid locking */
+	fclose(status->fp);
+	status->fp = NULL;
 	return 0;
 }
 
@@ -433,6 +450,11 @@ void pyi_arch_status_free_memory(ARCHIVE_STATUS *archive_status)
         if (archive_status->tocbuff != NULL) {
             free(archive_status->tocbuff);
         }
+        /* Free file handler */
+        if (archive_status->fp != NULL) {
+            fclose(archive_status->fp);
+            archive_status->fp = NULL;
+        }
         free(archive_status);
     }
 }
--- a/PyInstaller/loader/pyi_archive.py.orig
+++ b/PyInstaller/loader/pyi_archive.py
@@ -88,7 +88,9 @@ class Archive(object):
         import imp
         self.pymagic = imp.get_magic()
         if path is not None:
-            self.lib = open(self.path, 'rb')
+            from cStringIO import StringIO
+            with open(self.path, 'rb') as fp:
+                self.lib = StringIO(fp.read())
             self.checkmagic()
             self.loadtoc()
 
@@ -121,7 +123,7 @@ class Archive(object):
         self.lib.seek(self.start + self.TOCPOS)
         (offset,) = struct.unpack('!i', self.lib.read(4))
         self.lib.seek(self.start + offset)
-        self.toc = marshal.load(self.lib)
+        self.toc = marshal.loads(self.lib.read())
 
     ######## This is what is called by FuncImporter #######
     ## Since an Archive is flat, we ignore parent and modname.
```
```

**Comment by matysek** [comment] 2015-01-09 12:02
@YueLunGames Thanks for investigation.

**Comment by htgoebel** [comment] 2015-01-09 14:06
I think, the performance impact is negligible.
I'm more concerned about reading the whole archive into memory and keeping it there for the whole runtime of the program.

**Comment by YueLunGames** [comment] 2015-01-10 03:30
In fact the file pointer should not be the member of a long living class.
File object lifetime should be managed as short as they can.

you can do 
with self.openfile() as lib:
    self.checkmagic(lib)
    self.loadtoc(lib)

and
with archive.openfile() as lib:
    archive.extract(lib, name)

**Comment by htgoebel** [comment] 2015-01-13 11:06
@YueLunGames Could you please submit a pull-request with out changes. You can even fork on github, "edit" the files online (paste your changed file in) and submit the pull-request.Thanks.

**Comment by YueLunGames** [comment] 2015-01-15 16:56
ok, I will try to create an clean fix in next few days.

**Comment by matysek** [comment] 2015-01-15 17:14
Thanks.

**Comment by htgoebel** [comment] 2015-06-24 13:21
Since there is a related pull-request, I'm closing the issue.

**Closed by htgoebel** 2015-06-24 13:21 UTC
Labels: Windows
