### ISSUE TITLE
Pulp error occurs on executable when running PyInstaller with console option False and onefile

### ISSUE THREAD

**Issue by LBeghini** [pyinstaller/pyinstaller#6359] opened 2021-11-08 19:35 UTC
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python:  3.9.7
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No, I only tried on Windows

Cannot use PyInstaller with another version because I wasn't able to generate the installer of my program to MacOS. I described the problem I was having on [this issue](https://github.com/GraphFilter/GraphFilter/issues/114), and I only managed to create the executable to Mac with the version 4.5.1.

## Description of the issue

I was having a problem where pulp library was giving me an error:

```error
'NoneType' object has no attribute 'actualSolve'
```
I searched how to fix this and I found [this answer](https://stackoverflow.com/questions/60926887/py-project-works-but-pyinstaller-gives-error-related-to-pulp) on StackOverflow.

It worked with the following spec file
```spec
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

def get_pulp_path():
    import pulp
    return pulp.__path__[0]

a = Analysis(['app.py'],
             pathex=['D:\\Documentos\\GitHub\\GraphFilter.py'],
             binaries=[],
             datas=[('.\\resources\\data', 'resources\\data'), ('.\\resources\\icons', 'resources\\icons')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

a.datas += Tree(get_pulp_path(), prefix='pulp', excludes=["*.pyc"])

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='GraphFilter-2.0.1-win',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='resources\\icons\\hexagon.ico')

```

However, I want to generate the executable without the console option. Then, I changed the spec file to

```spec
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

def get_pulp_path():
    import pulp
    return pulp.__path__[0]

a = Analysis(['app.py'],
             pathex=['D:\\Documentos\\GitHub\\GraphFilter.py'],
             binaries=[],
             datas=[('.\\resources\\data', 'resources\\data'), ('.\\resources\\icons', 'resources\\icons')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

a.datas += Tree(get_pulp_path(), prefix='pulp', excludes=["*.pyc"])

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='GraphFilter-2.0.1-win',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
#         turned the console to false
          console=False, 
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='resources\\icons\\hexagon.ico')

```
and the problem from the beginning returns, giving me a

```error
'NoneType' object has no attribute 'actualSolve'
```

Opening the build files of the console equals True, I found a Tree-03.toc file with the following content:

```toc
[...]
 ('pulp\\solverdir\\cbc\\win\\64\\cbc.exe',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\64\\cbc.exe',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\64\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\64\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\64\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\64\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\32\\cbc.exe',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\32\\cbc.exe',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\32\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\32\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\32\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\32\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\osx\\64\\cbc',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\osx\\64\\cbc',
   'DATA'),
  ('pulp\\solverdir\\cbc\\osx\\64\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\osx\\64\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\osx\\64\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\osx\\64\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\64\\cbc',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\64\\cbc',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\64\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\64\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\64\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\64\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\32\\cbc',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\32\\cbc',
   'DATA'),
[...]
```

Inside the same file Tree-03.toc I found the same structure:
```toc
[...]
('pulp\\solverdir\\cbc\\win\\64\\cbc.exe',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\64\\cbc.exe',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\64\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\64\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\64\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\64\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\32\\cbc.exe',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\32\\cbc.exe',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\32\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\32\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\win\\32\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\win\\32\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\osx\\64\\cbc',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\osx\\64\\cbc',
   'DATA'),
  ('pulp\\solverdir\\cbc\\osx\\64\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\osx\\64\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\osx\\64\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\osx\\64\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\64\\cbc',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\64\\cbc',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\64\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\64\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\64\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\64\\__init__.py',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\32\\cbc',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\32\\cbc',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\32\\coin-license.txt',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\32\\coin-license.txt',
   'DATA'),
  ('pulp\\solverdir\\cbc\\linux\\32\\__init__.py',
   'D:\\Documentos\\GitHub\\GraphFilter.py\\venv\\lib\\site-packages\\pulp\\solverdir\\cbc\\linux\\32\\__init__.py',
   'DATA'),
[...]
```
But it won't work, the same error appears.

Generating without the onefile option, it works, and I am able to see the missing cbc file on the dist folder. I don't understand why I can't generate it with onefile option without the console.

You can check my source code on [GitHub](https://github.com/GraphFilter/GraphFilter) and the [Issue](https://github.com/GraphFilter/GraphFilter/issues/116) describing the problem. Altso, [here](https://stackoverflow.com/questions/69868023/pulp-error-occurs-on-executable-when-running-pyinstaller-with-console-option-fal) is the question on StackOverflow.

**Comment by bwoodsend** [comment] 2021-11-09 08:19
Does your program work in regular Python using windowed mode? i.e. `pythonw app.py` instead of `python app.py`?

P.S. Adding files to `pathex` (instead of folders) does nothing.

**Comment by LBeghini** [comment] 2021-11-09 15:08
Yes, the program does work with ```pythonw app.py```.

> I didn't understand what you said about ```pathex```

**Comment by bwoodsend** [comment] 2021-11-09 19:07
Hmm ok, I'll have a look when I get home. Failing with `console=False` normally means that either stdout, sterr or stdin in a `subprocess.Popen()` is inheriting its corresponding pipe from its parent which is invalid because, in windowed mode, there is not stdout/stdin/stderr. But a brief grepping around your code doesn't reveal any of those.


---

This line does nothing:
```python
     pathex=['D:\\Documentos\\GitHub\\GraphFilter.py'],
```
It should be `pathex=['D:\\Documentos\\GitHub'],` but you obviously don't need it or you'd be getting errors saying it can't import `GraphFilter`.

**Comment by rokm** [comment] 2021-11-09 20:15
Taking the sample PuLP code from:
https://projects.coin-or.org/PuLP/browser/trunk/examples/WhiskasModel1.py?format=txt

Building with console in onedir:

```
pyinstaller --clean --noconfirm program.py
```

The resulting program errors out, with the same error you are getting:
```
>dist\program\program.exe
Traceback (most recent call last):
  File "program.py", line 29, in <module>
    prob.solve()
  File "pulp\pulp.py", line 1877, in solve
AttributeError: 'NoneType' object has no attribute 'actualSolve'
[4708] Failed to execute script 'program' due to unhandled exception!
```

which is due to missing solver executables, and consequently default solver object being `None`.

So collect the data from `pulp` package (you can also use `collect_data_files` in spec directly, no need for the round-about way from the stackoverflow):

```
pyinstaller --clean --noconfirm --collect-data pulp program.py
```

The program works now.

----

Switching to console onefile mode:

```
pyinstaller --clean --noconfirm --onefile --collect-data pulp program.py
```

The program also works.

---

Switching to noconsole onedir mode:

```
pyinstaller --clean --noconfirm --windowed --collect-data pulp program.py
```

The program works. Somewhat against expectations, but I'm starting to suspect that some of our invalid inherited handle problems are limited only to onefile+noconsole mode. Which would explain why the program is reported to work under windowed interpreter (`pythonw`).

---

As for noconsole onefile mode:

```
pyinstaller --clean --noconfirm --windowed --onefile --collect-data pulp program.py
```

This one crashes, but the error is different than before:

```
Traceback (most recent call last):
  File "program.py", line 29, in <module>
    prob.solve()
  File "pulp\pulp.py", line 1877, in solve
  File "pulp\apis\coin_api.py", line 137, in actualSolve
  File "pulp\apis\coin_api.py", line 194, in solve_CBC
  File "subprocess.py", line 825, in __init__
  File "subprocess.py", line 1266, in _get_handles
OSError: [WinError 6] The handle is invalid
```

which is due to invalid inherited stdout and stderr in [this Popen call](https://github.com/coin-or/pulp/blob/68c70ec33a03e0fadeab50d69b0da106edaa345f/pulp/apis/coin_api.py#L179-L194). They do redirect `stdin`, but `stdout` and `stderr` end up being `None`, which means inherited.

Forcing them to `devnull` fixes the problem.

I imagine other solvers in that package have similar issues.

**Comment by rokm** [comment] 2021-11-09 20:47
And if GraphFilter's code is modified to display exception information (i.e., [here](https://github.com/GraphFilter/GraphFilter/blob/d54db747f0f4ecbff9f89954608efa51f77395b6/source/domain/equation.py#L44-L45)), the problem is indeed `[WinError 6] The handle is invalid`. So the problem can be solved by patching local `pulp` installation to force `stdout` and `stderr` of [this `Popen` call](https://github.com/coin-or/pulp/blob/68c70ec33a03e0fadeab50d69b0da106edaa345f/pulp/apis/coin_api.py#L194) to `devnull`.

But we might want to take a closer look at why the inherited handles are problematic only for `onefile+noconsole` and not for `onedir+noconsole`...

**Comment by LBeghini** [comment] 2021-11-10 21:01
So, to make it work, I would need to alter the `Peopen` file inside the library? Would you suggest for me to open an issue on their GitHub repository?

**Comment by rokm** [comment] 2021-11-10 21:51
> So, to make it work, I would need to alter the `Peopen` file inside the library?

If you can influence how that PuLP solver is instantiated, you could also try setting its [msg](https://github.com/coin-or/pulp/blob/68c70ec33a03e0fadeab50d69b0da106edaa345f/pulp/apis/coin_api.py#L49) argument in constructor to `False`, which will also properly redirect `stdout` and `stderr` to `devnull`. But you'll likely need to instantiate it explicitly instead of using the default instantiated solver. That said, you don't seem to be using `pulp` directly, so you'll have to traverse the call chain to see if you can use custom instance of the solver.

But yes, otherwise you'll need to patch the copy of `PuLP` you use.

> Would you suggest for me to open an issue on their GitHub repository?

In this case, I would not, because this does not look like an outright bug, but rather an unfortunate corner use case (onefile+noconsole in PyInstaller-frozen application) that the default instantiation of the solver is not compatible with (due to having logging to inherited stdout/stderr handles enabled by default).

**Comment by bwoodsend** [comment] 2021-11-16 09:28
@LBeghini Can you try:
```
pip install https://github.com/bwoodsend/pyinstaller/archive/refs/heads/subprocess_runtime_hook.zip
```
Then:
```
pyinstaller --clean --noconfirm --windowed --collect-data pulp program.py
```
And tell me if it works?

**Comment by LBeghini** [comment] 2021-11-17 03:17
The exact command wouldn't work because I needed my dependencies.

At first I tried:
```bash
pyinstaller --icon .\resources\icons\hexagon.ico --add-data ".\resources\data;resources\data" --add-data ".\resources\icons;resources\icons" --clean --noconfirm
 --collect-data pulp --name GraphFilter app.py
```
and it worked.

Then, to generate one file, I ran:
```bash
pyinstaller --icon .\resources\icons\hexagon.ico --add-data ".\resources\data;resources\data" --add-data ".\resources\icons;resources\icons" --clean --noconfirm
 --collect-data pulp --name GraphFilter app.py
```
however it was opening the console, which is not ideal to my application.

At last, I ran:
```bash
pyinstaller --icon .\resources\icons\hexagon.ico --add-data ".\resources\data;resources\data" --add-data ".\resources\icons;resources\icons" --clean --noconfirm
 --collect-data pulp --name GraphFilter --onefile --noconsole app.py
```
and it worked perfectly.

**Comment by rokm** [comment] 2021-11-18 20:31
Closing this as #6364 has been merged.

**Closed as completed by rokm** 2021-11-18 20:31 UTC
