### ISSUE TITLE
problem with windows 10 

### ISSUE THREAD

**Issue by dibifirst** [pyinstaller/pyinstaller#2309] opened 2016-12-12 12:01 UTC
I have windows 10 env with 3.5.2 python that perfectly running under py shell. When I make .exe in windows 7 everythink working properly, but if I make exe in windows 10, pyinstaller give some dipendency error of some API*.dlls. The program running anyway but on quit return error saying that application end abnormaly. Can you help me?

**Comment by dibifirst** [comment] 2016-12-12 12:19
yes I read see #1566, but it is not clear if the problem is the same and if the problem is solved. Pls help me !!!!

**Comment by dibifirst** [comment] 2016-12-13 08:47
nobody can help me?

**Comment by htgoebel** [comment] 2016-12-13 10:06
Closing, as there were suggested some workarounds and it is duplicate of #1566.

**Closed by htgoebel** 2016-12-13 10:06 UTC

**Comment by dibifirst** [comment] 2016-12-13 12:45
Sorry but is very easy to close the problem like you have done. I say you that the problem is due thatwhen I running my application and the program perform the self.quit (i have try even with other exit type) windows give me one error saying thta progrm ended abnornamally. This not happen under windows 7. the only strange thing is what i have highlight. Really this replay i very bad form your side and show that you havven't understood nothing..

**Comment by dibifirst** [comment] 2016-12-13 12:46
This is very bad assistance !!!!

**Comment by stephenrauch** [comment] 2016-12-13 19:42
@htgoebel 

FYI: the how to report bugs pages seems to have disappeared...

**Comment by tallforasmurf** [comment] 2016-12-13 19:45
Confirm, https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs comes up "Create New Page".

**Comment by htgoebel** [comment] 2017-01-05 14:51
The how to report bugs was deleted by dibifirst. I restored it.

**Comment by PeskyWabbit** [comment] 2018-08-29 15:39
Wow, this is indeed bad assistance. I read over that post as well and still have not fixed the problem. I'm looking for a fix, not to have to run a VM.
