### ISSUE TITLE
Reproducible Freeze

### ISSUE THREAD

**Issue by phelixbtc** [pyinstaller/pyinstaller#1582] opened 2015-10-05 19:11 UTC
The resulting executable looks like it is ordered differently between builds (not in onefile mode). Everything else is relatively easy to match.  
  
See also https://github.com/pyinstaller/pyinstaller/issues/490  
  
For motivations see: https://media.ccc.de/browse/congress/2014/31c3_-_6240_-_en_-_saal_g_-_201412271400_-_reproducible_builds_-_mike_perry_-_seth_schoen_-_hans_steiner.html#video&t=18

**Comment by matysek** [comment] 2015-10-05 19:48
@phelixbtc Do you think that this could be fixed when files / modules would be ordered for example alphabetically?

**Comment by phelixbtc** [comment] 2015-10-05 21:08
Yes, that might be all that is needed. In any case it should be one of the necessary steps. I would be happy to test.

**Comment by matysek** [comment] 2015-10-06 11:05
@phelixbtc What pyinstaller and python version do you use? Is it the same with Python 2 and Python 3?

**Comment by phelixbtc** [comment] 2015-10-06 12:18
I have tested pyinstaller 2.1 and 3.0dev6. I have only tested with Python 2.7.10 so far. If you can point me to the right place I could try using an ordered dictionary or something and eventually submit a PR.

**Comment by matysek** [comment] 2015-10-06 12:55
@phelixbtc I think you should hack the pyinstaller phases when you get messages like:
```
6868 INFO: Building PYZ (ZlibArchive) 
7093 INFO: Building PKG (CArchive)
```
* If you use archive_viewer you should see output like this:
```
[
# python modules should be sorted when creating this .pyz item (ZlibArchive)
(0, 1397265, 1397265, 0, 'z', 'out00-PYZ.pyz'),
 (1397265, 260, 334, 1, 'm', 'struct'),
 (1397525, 1123, 1960, 1, 'm', 'pyimod01_os_path'),
 (1398648, 3969, 8849, 1, 'm', 'pyimod02_archive'),
 (1402617, 5645, 14802, 1, 'm', 'pyimod03_importers'),
 (1408262, 2453, 6604, 1, 's', 'pyiboot01_bootstrap'),
 # runtime hooks here if any
 (1410715, 49, 48, 1, 's', 'hello_test'),
 # compressed files follows when using onefile mode - this list should be sorted.
]
```
* In function `PyInstaller.depend.analysis:get_bootstrap_modules()` you can see items where the order is really important.'
  * when using 'archive_viewer' after these items then follows:
    1. rthooks
    1. user scripts
    1. compressed files for onefile mode  - you should probably sort these items.
* For more details try to look at methods:
```
PyInstaller.building.api:PYZ.assemble()
PyInstaller.building.api:PKG.assemble()
```

**Comment by phelixbtc** [comment] 2015-10-06 13:11
Thanks. Sounds more complicated than I thought :)  I will try to make time but it may take a while.

**Comment by phelixbtc** [comment] 2015-10-07 09:17
Modifying `datastruct.TOC.extend` like below seems to do the job or at least improve things. Unfortunately this also breaks the executable. Probably some things should not be sorted :)

```
    def extend(self, other):
        if type(other) == set:
            other = list(other)
        try:
            # from operator import itemgetter            
            other.sort(key=itemgetter(0), reverse=False)  # in place sort
        except:
            import traceback
            traceback.print_exc()

        for entry in other:
            self.append(entry)
```

**Comment by matysek** [comment] 2015-10-07 11:17
Try to use `archive_viewer` to examine the order of the items inside the executable.

**Comment by codewarrior0** [comment] 2015-10-07 11:22
See also #490 - one root cause of the non-reproducible freeze is the hash seed randomization in Python 3.3+. This affects the order that modules are read out of a ModuleGraph using `graph.flatten()`, among other things.

Another, which I've just discovered, is that files written to the base_library.zip using `ZipFile.writestr` are given a timestamp of the current time which will of course vary from build to build.

**Comment by matysek** [comment] 2015-10-07 12:13
> Another, which I've just discovered, is that files written to the base_library.zip using ZipFile.writestr are given a timestamp of the current time which will of course vary from build to build.

Should we just somehow write "a constant date" into base_library.zip and override the timestamp?

**Comment by josephbisch** [comment] 2015-10-07 14:37
The Gitian build system for reproducible builds uses faketime for setting a particular date-time to use consistently across builds, so that should handle any timestamp issues that might occur when doing a build with the Gitian system of any software that uses pyinstaller.

Debian's reproducible build project uses their own tools (not Gitian). They have created a standard called SOURCE_DATE_EPOCH. It works by allowing the builder or build system to export an environment variable (called SOURCE_DATE_EPOCH) to override the default timestamp of the current time. Many upstream programs are implementing it. In Debian's case their build system exports SOURCE_DATE_EPOCH based on the current timestamp in the debian/changelog. So a particular version of a Debian package will have the same timestamp across builds.

See the following for information on SOURCE_DATE_EPOCH: https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal.

I recommend implementing SOURCE_DATE_EPOCH if possible. It appears that the ZipFile class supports an optional date-time tuple parameter that specifies the modification timestamp. I'm not sure if that also affects the creation timestamp. Hopefully it does.

Of course faketime can always be used to do the build, so it doesn't seem like a big deal if SOURCE_DATE_EPOCH isn't implemented.

There's also this tool from Debian called diffoscope that allows you to do diffs on binary files: http://diffoscope.org/. It should help identify what causes differences.

**Comment by codewarrior0** [comment] 2015-10-07 14:50
Thanks Joseph. We'll consider supporting SOURCE_DATE_EPOCH.

The ZipFile class does have a date-time parameter, but it is on the ZipInfo helper class, which is not usable directly. We can indirectly pass a timestamp by writing the data to a temporary file and changing its mtime, and then passing that to `ZipFile.write`... but this could get a bit thrashy. Shouldn't be a big deal because zipfiles see very limited use. Alternately, we could monkey-patch `time.localtime` to return a constant value, which we may want to do anyway to support SOURCE_DATE_EPOCH without relying on faketime.

**Comment by codewarrior0** [comment] 2015-10-07 14:56
I'm mildly curious if any distros enable hash-seed randomization for Python 2.7. All it takes to find out is to run this command twice and compare the values; if unequal, the hashes are randomized:

`python2 -c "print(hash('hello world'))"`

**Comment by josephbisch** [comment] 2015-10-07 15:03
I get the same value each time I run that. But I am on Debian Testing (Stretch), not Debian Stable (Jessie), so I don't know about Jessie. So I am using python2.7 version 2.7.10-4 instead of 2.7.9-2.

But I'm guessing if randomization isn't enabled for newer Debian releases, it probably isn't for Jessie either.

**Comment by josephbisch** [comment] 2015-10-07 15:03
Oh, sorry I am using 2.7.10-3.

**Comment by phelixbtc** [comment] 2015-10-08 12:51
@codewarrior0 On Windows Python 2.7.10 your command always gives the same answer (`-1500746465`).  

Oddly enough I did not run into any timestamping issues so far.

**Comment by htgoebel** [comment] 2015-10-08 20:32
Data schould be sorted when creating the output, not in eavh `extend()`

Am 7. Oktober 2015 11:17:15 MESZ, schrieb phelixbtc <notifications@github.com>:
>Modifying `datastruct.TOC.extend` like below seems to do the job or at
>least improve things. Unfortunately this also breaks the executable.
>Probably some things should not be sorted :)
>
>```
>    def extend(self, other):
>        if type(other) == set:
>            other = list(other)
>        try:
>            # from operator import itemgetter            
>          other.sort(key=itemgetter(0), reverse=False)  # in place sort
>        except:
>            import traceback
>            traceback.print_exc()
>
>        for entry in other:
>            self.append(entry)
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pyinstaller/pyinstaller/issues/1582#issuecomment-146128683

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matysek** [comment] 2015-10-08 21:53
> Oddly enough I did not run into any timestamping issues so far.

@phelixbtc Is this because you are still testing only onedir mode?

**Comment by phelixbtc** [comment] 2015-10-08 21:57
@htgoebel yeah, that makes more sense. I modified writers.ArchiveWriter._add_from_table_of_contents but the executable still breaks (but it is building reproducibly for me).

**Comment by phelixbtc** [comment] 2015-10-08 21:59
@matysek Yes, I have only been testing onedir mode so far.

**Comment by matysek** [comment] 2015-10-08 21:59
> writers.ArchiveWriter._add_from_table_of_contents but the executable still breaks (but it is building reproducibly for me).

@phelixbtc Could you create a pull request so that we could see your modifications and provide feedback directly to your code?

**Comment by htgoebel** [comment] 2015-10-08 22:04
> Oddly enough I did not run into any timestamping issues so far.

This is simply because PyInstalle does not store any timestamp into the frozen executable – it does not need one.

**Comment by phelixbtc** [comment] 2015-10-09 07:45
@matysek Voilá: https://github.com/pyinstaller/pyinstaller/pull/1590

btw when starting the executable I get three popups:
```
mod is NULL - pyimod02_archive
mod is NULL - pyimod03_importers
freezetest returned -1
```

**Comment by phelixbtc** [comment] 2015-10-09 07:48
@htgoebel It's very handy Pyinstaller does not store timestamps. Exactly the way it should be. :)

**Comment by phelixbtc** [comment] 2015-10-13 08:38
In the code I stumbled across parts that do things differently for older Windows versions. I am a bit ashamed to admit that I was testing against Windows XP. I will try again with win8.1/win8.1. This should also make it easier to get the DLLs right.

**Comment by phelixbtc** [comment] 2015-10-16 14:49
I will have to set up a new machine for proper testing. This will take me a while.

**Comment by htgoebel** [comment] 2015-10-23 20:47
I just pushed a possible solution to my personal repo. If CI tests pass, I'll merge here in the next days.

**Comment by htgoebel** [comment] 2015-10-23 21:17
@phelixbtc Please test with the version I just pushed. If ensures that the content of the PYZ is sorted alphabetically.

This should be okay for onedir build.

For onefile, we still need to sort the CTOC.

**Comment by htgoebel** [comment] 2015-10-23 21:43
Okay. The CTOC is now sorted, too. So except of the filepaths contained in the byte-code (see #1059 and #1302) this should be reproducible now.

**Comment by phelixbtc** [comment] 2015-10-29 13:51
@htgoebel Thank you very much. The executable looks quite good now, there are only a couple of places where it differs.  
I noticed there might be some differences caused by compression as the uncompressed sizes do match while the compressed do not:

```
Files from Machine A
 pos, length, uncompressed, iscompressed, type, name
[(0, 170, 234, 1, 'm', u'struct'),
 (170, 1168, 2753, 1, 'm', u'pyimod01_os_path'),
 (1338, 3932, 11200, 1, 'm', u'pyimod02_archive'),
 (5270, 5671, 18397, 1, 'm', u'pyimod03_importers'),
 (10941, 2468, 6789, 1, 's', u'pyiboot01_bootstrap'),
 (13409, 522, 1180, 1, 's', u'pyi_rth__tkinter'),
 (13931, 344, 656, 1, 's', u'nmcontrolwin'),
 (14275, 1222991, 1222991, 0, 'z', u'out00-PYZ.pyz')]
?
Exception KeyboardInterrupt in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored

Files from Machine B
 pos, length, uncompressed, iscompressed, type, name
[(0, 170, 234, 1, 'm', u'struct'),
 (170, 1168, 2753, 1, 'm', u'pyimod01_os_path'),
 (1338, 3933, 11200, 1, 'm', u'pyimod02_archive'),
 (5271, 5673, 18397, 1, 'm', u'pyimod03_importers'),
 (10944, 2468, 6789, 1, 's', u'pyiboot01_bootstrap'),
 (13412, 522, 1180, 1, 's', u'pyi_rth__tkinter'),
 (13934, 344, 656, 1, 's', u'nmcontrolwin'),
 (14278, 1094913, 1094913, 0, 'z', u'out00-PYZ.pyz')]
?

```

Also there still was a different version of pywin32 in use which I for some odd reason could only fix half way but will do and report back. Maybe this is the reason some stuff is "missing" from machine B. Also one machine was seemingly using a different json implementation but I hope I got that fixed.

**Comment by htgoebel** [comment] 2015-10-29 17:28
Well, build can only be reproduced, if all relevant components are at the same version.
https://wiki.debian.org/ReproducibleBuilds

**Comment by phelixbtc** [comment] 2015-11-03 13:29
Thanks to your work it seems I am getting closer now. My relatively large project executable now only shows three differences. In `out00-EXE.toc` I noticed there are some pyinstaller .pyc referenced. Two of the remaining differences also occur if I remove all the .pyc files in the pyinstaller folder and then rerun the pyinstaller process on the same machine. Probably I would have to use the same .pyc files or try to have these be built reproducibly, too....

**Comment by htgoebel** [comment] 2015-11-03 16:29
`.pyc` file contain a time-stamp. (Either the mtime of the related `.py` file or the compile time- I'm unsure ATM). So if you have `.pyc` in your EXE, you must ensure they are *not* rebuild between build. And, of course, if you have different machines, you need some external tool to fix the timestamps.

**Comment by matysek** [comment] 2015-11-04 07:52
@phelixbtc Could you please try version from this pull request if it anyhow improves/breaks reproducibility for your project? https://github.com/pyinstaller/pyinstaller/pull/1651

**Comment by phelixbtc** [comment] 2015-11-04 10:09
@matysek Thanks, I will give it a try. A deterministic order of the "output files in the build folder" might make comparing freezes and finding issues easier.

**Comment by htgoebel** [comment] 2015-11-04 17:47
@phelixbtc What exactly do you mean with "output files in the build folder"?

**Comment by phelixbtc** [comment] 2015-11-09 10:46
@htgoebel I meant the contents of e.g. the toc files. That might be affected by @matysek 's patch? In my case the order does match already, though. Unfortunately I did not find the time to test matysek's patch yet.

Rebuilding `.pyc` files does not make a change for me. (Only when I did remove all pyinstaller `.pyc` files on two different machines for the first time the output changed. Maybe some where not yet up to date? Odd.)  

Current status is that there are still some slight differences remaining though the `.toc` files all match (all but `out00-EXE.toc` which has one timestamp and one memory address which both change on rebuild but don't affect the executable file). I am pondering on how to find the modules that are causing the differences in `out00-PKG.pkg` and `out00-PYZ.pyz`. Maybe I will parse the `.toc` files and calculate hashes...

**Comment by htgoebel** [comment] 2015-11-09 20:46
> I meant the contents of e.g. the toc files.

.toc-file are irrelevant, they are just used for caching and help debugging. beside this, .toc-files are expected to be reproducible now.

>  I am pondering on how to find the modules that are causing the differences in out00-PKG.pkg and out00-PYZ.pyz

Archiveviewer is your friend.

I'm closing this issue now, as I see only vague issues. Please open a now ticket when you know what is still missing - and mind providing enough infos :-)

**Closed by htgoebel** 2015-11-09 20:46 UTC
Labels: @medium

**Comment by phelixbtc** [comment] 2015-11-12 13:03
OK. I will investigate further with archiveviewer and create a new issue if necessary or report back here if I get it working.
