### ISSUE TITLE
pyinstaller is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Peroxidelol** [pyinstaller/pyinstaller#6930] opened 2022-07-04 12:34 UTC
pyinstaller is not recognized as an internal or external command

**Comment by rokm** [comment] 2022-07-04 13:20
Duplicate of #5248. Either ensure that your python environment's scripts directory is in `PATH`, or if you cannot do that, use `python -m PyInstaller [...]` instead of `pyinstaller [...]`.

**Closed as completed by rokm** 2022-07-04 13:20 UTC
Labels: solution:invalid
