### ISSUE TITLE
How to add a hook for textblob in pyinstaller

### ISSUE THREAD

**Issue by priyanka22kar** [pyinstaller/pyinstaller#3155] opened 2017-12-28 05:49 UTC
when i create a .exe file using pyinstaller and execute it it is not fetching any result from
`b = TextBlob(ar)

score = b.sentiment.polarity`

it returns proper value when executed on console but return 0 when executed with .exe
your help will be really appreciated .
thank you

**Comment by htgoebel** [comment] 2017-12-28 12:05
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment] 2018-02-12 16:11
No update since 1 1/2 month. closing.

**Closed** 2018-03-13 21:31 UTC
Labels: not enough info, support
