### ISSUE TITLE
When using encryption parameters '--key' ，I want to replace pycrypto with pycryptodomex

### ISSUE THREAD

**Issue by BlueLee** [pyinstaller/pyinstaller#4379] opened 2019-08-15 02:06 UTC
When using encryption parameters '--key', 
the code encryption uses pycrypto by default,
but pycrypto is only updated to version 2.6, and the pip mirror does not include this whl package, why not replace pycrypto with pycryptodomex?

**Comment by elsabz** [comment] 2019-09-06 08:47
Yes this is interesting!
I read that someone wrote that encryption is not necessary for non-commercial applications ... I disagree with this because encryption is for security reasons, for example if I have to distribute an executable that gets information from a database, the Access information to the database must be encrypted! I hope someone can do something, because pyinstaller can work with an encryption system. thank you

**Comment by htgoebel** [comment] 2019-09-07 15:54
Duplicate of #2365

**Closed by htgoebel** 2019-09-07 15:54 UTC
