### ISSUE TITLE
Percolated assertions add extraneous output "Failed to execute script"

### ISSUE THREAD

**Issue by jessesuen** [pyinstaller/pyinstaller#2070] opened 2016-06-28 09:37 UTC
Consider the following script:

assert.py:

```
#!/usr/bin/env python
assert False, "sorry"
```

After packaging the script and executing it, it results in the following extraneous output "Failed to execute script assert":

```
# ./dist/assert/assert
Traceback (most recent call last):
  File "assert.py", line 2, in <module>
    assert False, "sorry"
AssertionError: sorry
Failed to execute script assert
```

It also modifies the return code to 255, when it should have been 1.

I am running with tip of master at the time of writing:

```
# pyinstaller --version
3.3.dev0+g8689a5d.mod
```

This is with the following python versions:
Python 2.7.11
Python 3.5.1

Also tested on ubuntu 14.04 (glibc) and alpine linux 3.4 (musl libc) with the same results.

**Comment by stephenrauch** [comment] 2016-06-28 14:04
This looks to be a duplicate of #1869 & #1978.  Check #1978 for a possible workaround.

**Comment by jessesuen** [comment] 2016-06-28 18:25
@stephenrauch, I saw #1978 before filing this bug, however I believe this to be a different issue (albeit very similar). I had built the bootloader for my platform before running my test.

The following script works correctly when bundled, but the assert script does not.
```
#!/usr/bin/env python

import sys
import os

if __name__ == '__main__':
    print("This is a test, please ignore!")
    sys.exit(0)
```

**Comment by Legorooj** [comment] 2020-02-14 22:31
Closing this because this is expected behaviour.

**Closed by Legorooj** 2020-02-14 22:31 UTC
