### ISSUE TITLE
ldaptor - ImportError: No module named UserList

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4289] opened 2019-06-25 14:28 UTC
I have issues with `ldaptor` module and PyInstaller.

The issue is probably related to the `six` module, this code can reproduce the error:
```
from ldaptor.protocols.ldap import ldapclient
```

When building with PyInstaller I get this error:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from ldaptor.protocols.ldap import ldapclient
  File "/tmp/pip-install-2b0bw0/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/ldaptor/protocols/ldap/ldapclient.py", line 18, in <module>
  File "/tmp/pip-install-2b0bw0/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/ldaptor/protocols/pureldap.py", line 22, in <module>
  File "/tmp/pip-install-2b0bw0/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/ldaptor/protocols/pureber.py", line 296, in <module>
  File "site-packages/six.py", line 92, in __get__
  File "site-packages/six.py", line 160, in _resolve
  File "site-packages/six.py", line 82, in _import_module
ImportError: No module named UserList
[6165] Failed to execute script test
```

As far as I understand, this `hook-six.moves.py` should include all of `six` imports but it is not working in my case, how can I debug this? 

**UPDATE:**
I was able to work around this with this hook:
```
import six

hiddenimports = []
for moved in six._moved_attributes:
    if isinstance(moved, (six.MovedModule, six.MovedAttribute)):
        hiddenimports.append('six.moves.' + moved.name)
```

It is similar to the code in `hook-six.moves.py`, not sure that this is the way to go here but if it is acceptable I can create a PR with this hook.

One thing is that it is generating a bunch of warnings in build time:
```
.
.
10299 INFO: Loading module hook "hook-ldaptor.py"...
10301 WARNING: Hidden import "six.moves.filter" not found!
10301 WARNING: Hidden import "six.moves.filterfalse" not found!
10302 WARNING: Hidden import "six.moves.input" not found!
10303 WARNING: Hidden import "six.moves.intern" not found!
10303 WARNING: Hidden import "six.moves.map" not found!
10303 WARNING: Hidden import "six.moves.getcwd" not found!
10308 WARNING: Hidden import "six.moves.reload_module" not found!
10308 WARNING: Hidden import "six.moves.reduce" not found!
10341 WARNING: Hidden import "six.moves.xrange" not found!
10341 WARNING: Hidden import "six.moves.zip" not found!
.
.
```

Platform: macOS (will probably be the same on Linux and Windows)
PyInstaller: 3.5
Python: 2.7.16

**Comment by htgoebel** [comment] 2019-08-07 14:19
six.moves are very special as they are generated at run-time. This requires a lot of hacking, see `PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py`.

Please try to find out why this is not picking up UserList.

Looking at your hook, maybe this pre_safe_import_module-hook could be simplified or even removed? What do you think?

**Comment by arossert** [comment] 2019-08-08 09:55
@htgoebel I'm not sure what the `pre_safe_import_module` is doing because I'm not familiar with the `api.add_runtime_package` and `api.add_alias_module` functions.

By adding some logs it looks like `real_to_six_module_name` is correct but it is still not working.

```{'cStringIO': 'six.moves.cStringIO', 'copy_reg': 'six.moves.copyreg', 'Tkdnd': 'six.moves.tkinter_dnd', 'CGIHTTPServer': 'six.moves.CGIHTTPServer', 'tkFileDialog': 'six.moves.tkinter_tkfiledialog', '__builtin__': 'six.moves.builtins', 'Tkconstants': 'six.moves.tkinter_constants', 'ttk': 'six.moves.tkinter_ttk', 'FileDialog': 'six.moves.tkinter_filedialog', 'email.MIMEImage': 'six.moves.email_mime_image', 'dummy_thread': 'six.moves._dummy_thread', 'HTMLParser': 'six.moves.html_parser', 'tkSimpleDialog': 'six.moves.tkinter_tksimpledialog', 'BaseHTTPServer': 'six.moves.BaseHTTPServer', 'Tix': 'six.moves.tkinter_tix', 'gdbm': 'six.moves.dbm_gnu', 'email.MIMEBase': 'six.moves.email_mime_base', 'email.MIMEText': 'six.moves.email_mime_text', 'robotparser': 'six.moves.urllib_robotparser', 'tkCommonDialog': 'six.moves.tkinter_commondialog', 'tkFont': 'six.moves.tkinter_font', 'pipes': 'six.moves.shlex_quote', 'SimpleHTTPServer': 'six.moves.SimpleHTTPServer', 'UserList': 'six.moves.UserList', 'Cookie': 'six.moves.http_cookies', 'email.MIMEMultipart': 'six.moves.email_mime_multipart', 'UserString': 'six.moves.UserString', 'email.MIMENonMultipart': 'six.moves.email_mime_nonmultipart', 'six.moves.urllib_parse': 'six.moves.urllib_parse', 'cPickle': 'six.moves.cPickle', 'Tkinter': 'six.moves.tkinter', 'SocketServer': 'six.moves.socketserver', 'UserDict': 'six.moves.UserDict', 'six.moves.urllib': 'six.moves.urllib', 'htmlentitydefs': 'six.moves.html_entities', 'httplib': 'six.moves.http_client', 'repr': 'six.moves.reprlib', 'Queue': 'six.moves.queue', 'Dialog': 'six.moves.tkinter_dialog', 'six.moves.urllib_error': 'six.moves.urllib_error', 'ScrolledText': 'six.moves.tkinter_scrolledtext', 'tkColorChooser': 'six.moves.tkinter_colorchooser', 'cookielib': 'six.moves.http_cookiejar', 'ConfigParser': 'six.moves.configparser', 'commands': 'six.moves.getoutput', 'thread': 'six.moves._thread', 'StringIO': 'six.moves.StringIO', 'xmlrpclib': 'six.moves.xmlrpc_client', 'SimpleDialog': 'six.moves.tkinter_simpledialog', 'itertools': 'six.moves.zip_longest', 'tkMessageBox': 'six.moves.tkinter_messagebox', 'SimpleXMLRPCServer': 'six.moves.xmlrpc_server', 'os': 'six.moves.getcwdb'}
```

If you can give me a lead on what needs to be done I can create a PR

**Comment by htgoebel** [comment] 2019-08-08 12:03
The pre_safe_import_module-hook only adds aliases, which means if one imports six.modes.UserList, this shall be redirected to `UserList`.

Anyway, I can not reproduce this issue. When reading the code of `ldaptor`, this code should reproducible the issue. Please confirm.
```
import six
print(six.moves.UserList)
```

And just see you did not provide all required details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by arossert** [comment] 2019-08-08 14:21
@htgoebel your example also reproduce this issue, I have added some details in the original message.
This only happens on Python2 and not on Python3

**Comment by htgoebel** [comment] 2019-08-08 16:12
Thanks.
So these aare actually 2 issues:
1) The is no `import` for `six.moves.UserList`, thus  PyInstaller is not able to pick this up. The solution for this part is to either use a `hidden-import` or a hook for `ldaptor`.

      Also opening a bug-report at laptor might be a good idea, since all examples in th six doc use a fully qualified import.

2) When adding either a hidden import or a import statement for `six.moves.UserList`, `UserList` gat added to the graph twice: Once as a SourceModule and once as an AliasNode. You can see this in the xref file in the build dir. Now for some reason the SourceModule is not picked up - it is not in the archive and not in Analysis-00.toc

     (When adding `UserList` as a hidden import, it works, but this is far from users expectations.)

So the big question is: Why is the module in the graph, but not in the TOC.

**Comment by htgoebel** [comment] 2019-08-08 16:53
My analysis was wrong, I did not actually look into the archive, but just on the result.

2) When adding either a hidden import or a import statement for `six.moves.UserList`, `UserList`gets added to the archives as expected.

**But `six.moves.UserList` is not a module**, but the class. This is why using a hidden import of `six.moves.UserList` does not work.

Now this code works:
```
import six
from six.moves import UserList
print(six.moves.UserList)
```

I suggest to file a bug report at ldaptor, as `from six.moves import UserList` is the way it is intended to work accoring to the six documentation, see I suggest.

Last open question: Why does it work for Python 3: Since in this case `six.moves.UserList` maps to `collections.UserList` and `collections` is part of the base_library.zip.

I' closing this since I see ne chance to fiy this in PyInstaller, and if there would be, it would be a lot, lot of work while Python 2.7 is EOL in a few month, and there is an acceptable work-around.

**Closed by htgoebel** 2019-08-08 16:53 UTC
Labels: hooks

**Comment by arossert** [comment] 2019-08-09 07:35
@htgoebel Thanks for the explanation, I have opened a PR to `ldaptor` with this small fix.
