### ISSUE TITLE
OSX, bootloader compilation error with clang

### ISSUE THREAD

**Issue by nekopep** [pyinstaller/pyinstaller#1882] opened 2016-03-12 22:27 UTC
Hello,
After trying to resolve bug #1879 I needed to recompile the bootloader under osx. Sadly if failed:
```
[10/13] Compiling src/pyi_utils.c
../../src/pyi_launch.c:368:54: error: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
code = PI_PyMarshal_ReadObjectFromString(data, ntohl(ptoc->ulen));
(relates to data)
1 error generated.
Waf: Leaving directory `/pyinstaller-develop/bootloader/build/debug'
Build failed
-> task in 'run_d' failed (exit status 1):
{task 4403223184: c pyi_launch.c -> pyi_launch.c.1.o}
['/usr/bin/clang', '-arch', 'x86_64', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-mmacosx-version-min=10.7', '-I/pyinstaller-develop/bootloader/build/debug/src', '-I/pyinstaller-develop/bootloader/src', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=600', '-D_REENTRANT', '-D_BSD_SOURCE', '-D_DARWIN_C_SOURCE', '-DHAVE_UNSETENV=1', '-DLAUNCH_DEBUG', '-DNDEBUG', '../../src/pyi_launch.c', '-c', '-o', '/pyinstaller-develop/bootloader/build/debug/src/pyi_launch.c.1.o']
```
I needed to change pyi_launch.c:368 by:
`code = PI_PyMarshal_ReadObjectFromString((const char*)data, ntohl(ptoc->ulen));`

**Comment by htgoebel** [comment] 2016-03-13 19:56
Looks like somebody changed the include file on OS X. The [official one](https://hg.python.org/cpython/file/tip/Include/marshal.h) still used `char * data). Please contact you Python vendor.

**Comment by matysek** [comment] 2016-03-13 22:26
I confirm it. I am able to reproduce with latest PyInstaller version. Just updated the git repo and nothing else.

@htgoebel @codewarrior0 how should we fix this as @nekopep suggests?

**Comment by codewarrior0** [comment] 2016-03-13 23:06
@htgoebel The compiler error is about dropping the "unsigned" qualifier, not the "const". This is because `pyi_arch_extract` returns an unsigned char pointer.

I don't see any problem with the fix @nekopep suggests. The alternative is to change `pyi_arch_extract` to return a non-unsigned char pointer, which is a somewhat larger change.

**Comment by matysek** [comment] 2016-03-14 06:50
@nekopep It should be fixed. Thanks for reporting and to other colleagues for comments.

**Closed by matysek** 2016-03-14 06:50 UTC
Labels: @medium, bootloader, develop, OS X
