### ISSUE TITLE
Hooks for dateparser

### ISSUE THREAD

**Issue by wattwei** [pyinstaller/pyinstaller#3429] opened 2018-03-28 11:40 UTC
very simple program. to make exe with pyinstaller

command: 
pyinstaller.exe **--hidden-import _strptime** main.py

main.py source code:
import _strptime
from binance.client import Client
client = Client('abcdefg', '123456789')
depth = client.get_order_book(symbol='BNBBTC')
print(depth)

when running main.exe, prompt below:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "c:\python36\lib\site-packages\pyinstaller-3.4.dev0+6d91c1655-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "binance\client.py", line 8, in <module>
  File "c:\python36\lib\site-packages\pyinstaller-3.4.dev0+6d91c1655-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "binance\helpers.py", line 3, in <module>
  File "c:\python36\lib\site-packages\pyinstaller-3.4.dev0+6d91c1655-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "dateparser\__init__.py", line 4, in <module>
  File "c:\python36\lib\site-packages\pyinstaller-3.4.dev0+6d91c1655-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "dateparser\date.py", line 13, in <module>
  File "c:\python36\lib\site-packages\pyinstaller-3.4.dev0+6d91c1655-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "dateparser\date_parser.py", line 11, in <module>
  File "c:\python36\lib\site-packages\pyinstaller-3.4.dev0+6d91c1655-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "dateparser\parser.py", line 10, in <module>
  File "c:\python36\lib\site-packages\pyinstaller-3.4.dev0+6d91c1655-py3.6.egg\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "dateparser\utils\strptime.py", line 55, in <module>
  File "dateparser\utils\strptime.py", line 26, in patch_strptime
  File "imp.py", line 297, in find_module
ImportError: No module named '_strptime'
[6936] Failed to execute script main

**Comment by htgoebel** [comment] 2018-03-28 16:43
I guess the missing module is `dateparser.utils._strptime`. Please use the xref-html file in the build directory to learn more about this.

If you mange to solve this, we would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by wattwei** [comment] 2018-03-29 03:19
thanks  reply above, but 'dateparser.utils._strptime' is nonexistent at all

I inspect file  'strptime.py':

def patch_strptime():
    """Monkey patching _strptime to avoid problems related with non-english
    locale changes on the system.

    For example, if system's locale is set to fr_FR. Parser won't recognize
    any date since all languages are translated to english dates.
    """

    _strptime = imp.load_module(
        **'strptime_patched', *imp.find_module('_strptime')**
    )

    _calendar = imp.load_module(
        'calendar_patched', *imp.find_module('_strptime')
    )

    _strptime._getlang = lambda: ('en_US', 'UTF-8')
    _strptime.calendar = _calendar
    _strptime.calendar.day_abbr = [
        'mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'
    ]
    _strptime.calendar.day_name = [
        'monday', 'tuesday', 'wednesday', 'thursday',
        'friday', 'saturday', 'sunday'
    ]
    _strptime.calendar.month_abbr = [
        '', 'jan', 'feb', 'mar', 'apr', 'may', 'jun',
        'jul', 'aug', 'sep', 'oct', 'nov', 'dec'
    ]
    _strptime.calendar.month_name = [
        '', 'january', 'february', 'march', 'april',
        'may', 'june', 'july', 'august', 'september',
        'october', 'november', 'december'
    ]

    return _strptime._strptime_time


**__strptime = patch_strptime()**

Pyinstaller can't handle the  first bold statement, so i try to modify the second bold statement to walk around it. the modification is ugly,but it can work now . 
**import _strptime
__strptime = _strptime**

Wish better solution if possible

**Comment by htgoebel** [comment] 2018-03-29 08:56
Of course PyInstaller can not handle `imp.find_module('_strptime')`, as [documented in the manual](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html?#listing-hidden-imports]. So to repeat what I've already written: For a proper solution you'll need a hook. To learn which module is needed, please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)..

**Comment by wattwei** [comment] 2018-03-29 16:37
I've found the reason.The function 'find_module' will search module specified via sys.path. The sys.path is different from  packed program  to unpack program, so just throw the specified module '_strptime.py' to the packed program root directory.

spec file is below:
`# -*- mode: python -*-

block_cipher = None

options = [ ('v', None, 'OPTION'), ('W ignore', None, 'OPTION') ]
a = Analysis(['another.py'],
             pathex=['c:\\test'],
             binaries=[],
             datas=[('C:\\Python36\\Lib\\_strptime.py', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
		  options,
          exclude_binaries=True,
          name='another',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='another')`

**Comment by wattwei** [comment] 2018-03-29 16:40
any more suggestion before i close the issue?

**Comment by Paco112** [comment] 2018-04-09 11:41
Here is a hook that works for me :

hook-parser.py

`from PyInstaller.utils.hooks import exec_statement, collect_submodules

strptime_data_file = exec_statement(
    "import inspect; import _strptime; print(inspect.getfile(_strptime))"
)

datas = [ (strptime_data_file, "") ]

hiddenimports = collect_submodules('dateparser')`

**Comment by htgoebel** [comment] 2018-09-01 19:51
Anyone to put the hook posted in https://github.com/pyinstaller/pyinstaller/issues/3429#issuecomment-379723204 into a pull-request?

**Comment by echen805** [comment] 2018-10-04 04:30
Credit goes to @Paco112 , I'm just creating the PR for the community so his work can get in. [#3790](https://github.com/pyinstaller/pyinstaller/pull/3790) @htgoebel

**Comment by CfirTsabari** [comment] 2018-10-31 08:48
@Paco112 thx for the solution but on i got  this error:

`Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.
Caused by 'c:\\python35\\Lib\\_strptime.py'.`

I solved by changing this line( small dot):
`datas = [ (strptime_data_file, ".") ]`

**Comment by htgoebel** [comment] 2018-10-31 11:14
@CfirTsabari I doubt you are using the most current version of this pull-request or PyInstaller. This very line does not occur in either. Please be mode carefull, you are wasting other peoples rare spare time.

**Comment by htgoebel** [comment] 2018-10-31 11:14
Closed by #3790

**Closed by htgoebel** 2018-10-31 11:14 UTC
Labels: good first issue, hooks, pull-request wanted

**Comment by CfirTsabari** [comment] 2018-10-31 12:10
@htgoebel i wast referring to the code that was written by @Paco112 and wanted to make sure that if someone in the future will wonder why this code isn't working for him , he will see my comment.
wasn't referring to the entire pull request just to the specific comment of @Paco112 ,
sorry for your waste of time even though I specifically mention the author of the comment i was referring to,

**Comment by locojay** [comment] 2018-11-23 16:00
I Unfortunately get the same error as above
```
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.5.dev0+g19d8a378-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "dateparser/__init__.py", line 4, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.5.dev0+g19d8a378-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "dateparser/date.py", line 13, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.5.dev0+g19d8a378-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "dateparser/date_parser.py", line 11, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.5.dev0+g19d8a378-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "dateparser/parser.py", line 10, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.5.dev0+g19d8a378-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "dateparser/utils/strptime.py", line 55, in <module>
  File "dateparser/utils/strptime.py", line 26, in patch_strptime
ImportError: No module named _strptime
[69903] Failed to execute script myapp
logout
Saving session...
```
after running
```
pyinstaller --onefile --clean myapp.py
```
using  pyinsaller 3.5.dev0+g19d8a378
which has the above hook installed
the build logs
```
200335 INFO: Loading module hook "hook-dateparser.utils.strptime.py"...
```
Thanks for your help

**Comment by noah10** [comment] 2018-12-06 21:46
Same issue as @locojay - I'm running 3.5.dev0+d619fa7d1, which has the hook in it and the build logs show:

`6811 INFO: Loading module hook "hook-dateparser.utils.strptime.py"...`

...and my app fails with:

`ImportError: No module named '_strptime'`

Here's a simple test case:

```
import moment

print("Hello")
```

Happy to provide more info to help track down the problem - let me know what would be useful.
