### ISSUE TITLE
ImportERROR: No module named apps

### ISSUE THREAD

**Issue by fpereiramosqueira** [pyinstaller/pyinstaller#2250] opened 2016-11-04 10:35 UTC
I have followed your guidelines to create a *.exe and I am still receiving this error (Django App).

X:\ESCAAG\Search_Engine\dist\PDF_mapper>PDF_mapper
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
  File "django\core\management\__init__.py", line 367, in execute_from_command_l
ine
  File "django\core\management\__init__.py", line 341, in execute
  File "django\__init__.py", line 27, in setup
  File "django\apps\registry.py", line 85, in populate
  File "django\apps\config.py", line 116, in create
  File "importlib\__init__.py", line 37, in import_module
ImportError: No module named apps
Failed to execute script manage

I can share with you the code if needed. Thanks a lot for you support!

**Comment by fpereiramosqueira** [comment] 2016-11-04 14:39
I did not mention it but running _'python manage.py runserver'_ works without any problem

**Comment by fpereiramosqueira** [comment] 2016-11-05 12:03
Is it possible that pyinstaller do not support either haystack or whoosh packages? If you could confirm if the packages and version below are supported it would be great.

I am running : 

Django version 1.11
Whoosh-2.7.4
haystack __version__ = (2, 5, 0)

**Comment by stevievb** [comment] 2016-11-14 20:23
I am having the same issue. I am running:
django=1.10.2=py27_0
python=2.7.12
djangorestframework==3.5.2

**Comment by stevievb** [comment] 2016-11-16 18:27
I noticed I was getting the following traceback when running pyinstaller:

Traceback (most recent call last):
  File "c:\#\#\#\#\#\lib\site-packages\PyInstaller\utils\hooks\subproc\django_import_finder.py", line 37, in <module>
    list(settings.TEMPLATE_LOADERS) + \
  File "c:\#\#\#\#\#\lib\site-packages\django\conf\__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'

In the django_import_finder I changed it from this:

hiddenimports = list(settings.INSTALLED_APPS) + \
                 list(settings.TEMPLATE_CONTEXT_PROCESSORS) + \
                 list(settings.TEMPLATE_LOADERS) + \
                 [settings.ROOT_URLCONF]

to this:

hiddenimports = list(settings.INSTALLED_APPS) + \
                list(settings.TEMPLATES[0]['OPTIONS'].get('context_processors', [])) + \
                list(settings.TEMPLATES[0]['OPTIONS'].get('loaders', [])) + \
                 [settings.ROOT_URLCONF]

It looks like there have been some changes in the settings module since 1.8:
https://docs.djangoproject.com/en/1.8/ref/settings/#template-context-processors

This change got me a little further so now I can runserver but there are still issues with it now working completely. I am getting a lot of warnings when I run pysinstaller:

12407 WARNING: Hidden import "django.contrib.contenttypes.context_processors" not found!
12437 WARNING: Hidden import "api.context_processors" not found!
12625 WARNING: Hidden import "django.contrib.auth.templatetags" not found!
12735 WARNING: Hidden import "django.contrib.contenttypes.templatetags" not found!
12735 WARNING: Hidden import "django.contrib.messages.context_processors.messages" not found!
12735 WARNING: Hidden import "django.template.context_processors.request" not found!
12750 WARNING: Hidden import "django.contrib.admin.context_processors" not found!
12750 WARNING: Hidden import "django.contrib.sessions.context_processors" not found!
12750 WARNING: Hidden import "django.contrib.staticfiles.context_processors" not found!
12750 WARNING: Hidden import "django.contrib.messages.templatetags" not found!
12750 WARNING: Hidden import "api.templatetags" not found!
12860 WARNING: Hidden import "django.contrib.sessions.templatetags" not found!
12860 WARNING: Hidden import "rest_framework.context_processors" not found!
12921 WARNING: Hidden import "django.template.context_processors.debug" not found!
12921 WARNING: Hidden import "django.contrib.auth.context_processors.auth" not found!

**Comment by Boco10** [comment] 2016-11-17 08:09
Same issue on windows. Even with the basic app.

**Comment by RaginiDahihande** [comment] 2017-01-06 07:29
I am also facing same issue on ubuntu
On windows it will work fine but for Ubuntu getting error like ImportError No module apps

**Comment by htgoebel** [comment] 2017-02-21 18:41
Please provide a *minimal* example to reproduce the error.

**Comment by ysicing** [comment] 2017-08-09 02:44
Same issue on Linux.
Failed to execute script console_app
Traceback (most recent call last):
  File "console_app.py", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "my_web/wsgi.py", line 16, in <module>
  File "site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
  File "site-packages/django/__init__.py", line 18, in setup
  File "site-packages/django/apps/registry.py", line 85, in populate
  File "site-packages/django/apps/config.py", line 112, in create
  File "importlib/__init__.py", line 37, in import_module
ImportError: No module named apps

**Comment by htgoebel** [comment] 2017-08-09 08:29
This is still jsut a trace-back not a *minimal* example.

**Comment by misaghkord** [comment] 2017-10-11 09:00
@htgoebel i teseted a empty django project nd got the same error. but when changed my django version from 1.11 to 1.9 the problem was resolved. i think it is a compability issue with new django version. i hope it will be fixed soon.

**Comment by htgoebel** [comment] 2017-10-12 08:33
Duplicate of #2281

**Closed by htgoebel** 2017-10-12 08:33 UTC

**Comment by htgoebel** [comment] 2017-10-12 08:34
@misaghkord We are invited to provide a pull-request solving this issue :-) (Or if you have a company, fund the fixing.)
