### ISSUE TITLE
"No such file" when copying file from bincache

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#1129] opened 2014-12-27 13:01 UTC
Firstly, I am using the `develop` branch at d0b4e2239e7ebf65d61c4ab384380d4456321d20. The error is not present in release v2.1.

When building an application which imports IPython the following error results:

```
Traceback (most recent call last):
  File "c:\python27-64\scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller===2.1.1dev-d0b4e22', 'console_scripts', 'pyinstaller')()
  File "C:\Python27-64\lib\site-packages\PyInstaller\main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\Python27-64\lib\site-packages\PyInstaller\main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\Python27-64\lib\site-packages\PyInstaller\build.py", line 1966, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27-64\lib\site-packages\PyInstaller\build.py", line 1915, in build
    execfile(spec)
  File "mcedit2.spec", line 42, in <module>
    icon="mcediticon.ico")
  File "C:\Python27-64\lib\site-packages\PyInstaller\build.py", line 1150, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "C:\Python27-64\lib\site-packages\PyInstaller\build.py", line 988, in __init__
    self.__postinit__()
  File "C:\Python27-64\lib\site-packages\PyInstaller\build.py", line 320, in __postinit__
    self.assemble()
  File "C:\Python27-64\lib\site-packages\PyInstaller\build.py", line 1030, in assemble
    dist_nm=inm)
  File "C:\Python27-64\lib\site-packages\PyInstaller\build.py", line 857, in checkCache
    shutil.copy2(fnm, cachedfile)
  File "C:\Python27-64\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27-64\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Rio\\AppData\\Roaming\\pyinstaller\\bincache00_py27\\zmq\\libz
mq.pyd'
```

Investigating with `git bisect` using `pyinstaller mcedit2.spec --clean` reveals commit b813174a3067baf15af02c63ae82946dc446187b introduces the error. Reading the source of `checkCache` tells me that `basenm` may be a path with directory components, resulting in a `cachedfile` which points to a file in a subfolder of the bincache (as is required to prevent the name collisions noted in that commit.)

When the file is copied from the module folder to the bincache using `shutil.copy2(fnm, cachedfile)`, the directories containing `cachedfile` are not created and the copy fails. The fix should create the dir using `path.dirname`,`path.exists`,`os.makedirs` before calling `shutil.copy2`

**Comment by matysek** [comment] 2015-01-02 12:50
I'm experiencing this issue too while working on fix for something else.

**Comment by htgoebel** [comment] 2015-01-02 13:01
@matysek It looks like this is a duplicate to #1132 , where I already proposed a patch for, see https://github.com/pyinstaller/pyinstaller/issues/1132#issuecomment-68445161

**Comment by codewarrior0** [comment] 2015-01-02 18:29
That fix works for me. I spent some time making sure this wasn't a problem with my setup and then I just forgot about sending a PR, whoops!

**Comment by matysek** [comment] 2015-01-02 23:33
The fix also works for me. Closing as duplicate of  #1132.

**Closed by matysek** 2015-01-02 23:33 UTC
Labels: Windows
