### ISSUE TITLE
ARM64 chroot

### ISSUE THREAD

**Issue by ixty** [pyinstaller/pyinstaller#2884] opened 2017-09-29 10:47 UTC
Hello,

I have a problem with pyinstaller in the following scenario:
- pyinstaller version 3.4.dev0+g3c87c135 (as of today the latest on branch develop)
- base OS: linux 64 bits (debian stretch)
- target OS: arm64 (aarch64) debian in a chroot, running with qemu-user-static
- i manually built the bootloader with waf all before running setup.py install (and i could see that the aarch64 bootloader was built sucessfully)

When im inside the chroot and i try to build a binary with pyinstaller, i get the following error:
`File "/home/me/venv/lib/python2.7/site-packages/PyInstaller-3.4.dev0+g3c87c135-py2.7.egg/PyInstaller/building/api.py", line 581, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: /usr/bin/objcopy: Unable to recognise the format of the input file '/home/me/dist/mybin'
`

There are 2 wierd things happening, the first early on pyinstaller run is the detected platform:
`244 INFO: Platform: Linux-4.9.0-3-amd64-aarch64-with-debian-9.1`

When i run file on /home/me/dist/mybin im also surprised by the arch, which should be aarch64.
`dist/mybin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=fdb92fd0de3892fc2176220c6694f8eee61d4fa3, stripped
`

On a side note, the same build system, in an ARM32 chroot works perfectly.
Any ideas?

**Comment by htgoebel** [comment] 2017-09-29 10:52
This is a bug on aarch64.
Duplicate of #2873. Duplicate of #2849.

**Closed by htgoebel** 2017-09-29 10:52 UTC
