### ISSUE TITLE
Main application file is not encrypted with --key option

### ISSUE THREAD

**Issue by ionic81** [pyinstaller/pyinstaller#3176] opened 2018-01-03 20:14 UTC
For who that wants to encrypt the source code with --key options:
the main file, let's say the "launcher", of the application won't be encrypted.

This is a know issue (#3160) but developer don't want to fix this if you don't pay for that.

Write a launcher without "critical" code ;-)

#3160

**Comment by htgoebel** [comment] 2018-01-03 22:05
Duplicate of #3160

**Comment by htgoebel** [comment] 2018-01-03 22:06
Stop trolling. This is a issue tracker, not a forum.

**Closed by htgoebel** 2018-01-03 22:05 UTC
