### ISSUE TITLE
Python Application Not Opening Anymore(For Mac)!?

### ISSUE THREAD

**Issue by emejia01** [pyinstaller/pyinstaller#4424] opened 2019-09-12 00:10 UTC
I'm just posting because I wanted to know if anyone else was having this problem. I recently made a python desktop application (Simple using Tkinter) and it was working fine about 1 month ago. However, now when I try to open the executable file on my computer (MacBook Pro, Mojave 10.14.6) an error occurs. The terminal opens for a split second, and then I am logged out of my MacBook user account. The application fails to open at all on my system. I also created the same executable for Windows OS's and it still works fine. Does anyone else have this problem/fix ??

**Comment by lkollar** [comment] 2019-09-16 14:16
Do you get any output when you start the application from the shell (e.g. using Terminal.app)?

**Comment by emejia01** [comment] 2019-09-17 00:42
> Do you get any output when you start the application from the shell (e.g. using Terminal.app)?

Yes, right before I am logged out the terminal window opens up and there IS about 2 lines of output before logout happens, but it's only for a few milliseconds and I can't read it. Sorry I can't be more help.

**Comment by lkollar** [comment] 2019-09-17 11:13
Just to make sure we are on the same page, can you try to open up Terminal.app, navigate to your PyInstaller packaged application and run it with `open Example.app`? The terminal window should not close and you should see the logs.

**Comment by BoboTiG** [comment] 2019-10-09 13:24
The only revelant issue I am aware of is not related to PyInstaller but Py2App: https://bitbucket.org/ronaldoussoren/py2app/issues/267/when-run-the-app-os-will-restart-on-macos

You should post your scripts to help investigating.

**Comment by nicozanf** [comment] 2019-10-13 21:46
It seems a duplicate of #4334  ...

**Comment by htgoebel** [comment] 2019-11-16 12:25
Given this few information there is no chance to even help tracking this down. So I'm closing this issue.

**Closed by htgoebel** 2019-11-16 12:25 UTC
Labels: need info, support
