### ISSUE TITLE
Bundled One-File Executable Uses system ucrtbase.dll instead of bundled ucrtbase.dll

### ISSUE THREAD

**Issue by StephenNorCalControls** [pyinstaller/pyinstaller#6326] opened 2021-10-29 20:22 UTC
## Description of the issue
The title pretty much explains it, when bundling with --one-file or a spec file, I see that ucrtbase.dll is correctly found and added per the below:
`11460 DEBUG: Adding ucrtbase.dll dependency of api-ms-win-crt-stdio-l1-1-0.dll from C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64\ucrtbase.dll`

but when running the application, eventually it crashes with this error in the event viewer:

Faulting application name: Hidden.exe, version: 1.0.0.1, time stamp: 0x5ffec13d
Faulting module name: ucrtbase.dll, version: 10.0.17763.1490, time stamp: 0x48ac8393
Exception code: 0xc0000409
Fault offset: 0x000000000006e77e
Faulting process id: 0x1a00
Faulting application start time: 0x01d7ccf5cdc10954
Faulting application path: C:\Program Files\Hidden\Hidden.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: eda9c1dc-e59b-4d6d-bf05-c907d2765466
Faulting package full name: 
Faulting package-relative application ID: 

which references a different version of ucrtbase.dll, the one available in the system at System32. I tried using PyInstaller 4.0,4.1,4.2,4.3,4.4,4.5, and 4.6 will similar results.

**Comment by rokm** [comment] 2021-10-29 21:25
In `onefile` mode, the DLLs that are required by the bootloader executable (direct dependencies are "just" `kernel32.dll` and `advapi32.dll`, but those depend on `api-ms-*` and probably end up requiring `ucrtbase.dll`) are inherently loaded from the system, because at that point, the embedded archive is not unpacked yet...

**Comment by StephenNorCalControls** [comment] 2021-10-29 22:08
So is this just an issue where the system I'm installing on needs to be updated or can I actually use these components that I've bundled?

**Comment by rokm** [comment] 2021-10-29 22:23
Either update the target system, or use `onedir` instead of `onefile`.

**Comment by bwoodsend** [comment] 2021-10-29 22:34
Could building the bootloaders with an older toolchain solve this? Possibly using gcc which links against `msvcrt.dll` rather than the `api-ms-*.dll`?

**Comment by rokm** [comment] 2021-10-29 22:39
> Could building the bootloaders with an older toolchain solve this? Possibly using gcc which links against `msvcrt.dll` rather than the `api-ms-*.dll`?

I dobut it - on PyInstaller 4.0, the toolchain was probably MSVC2015. Also, I think `msvcrt.dll` still ends up using system DLLs that eventually bring us to `api-ms-*` and `ucrtbase.dll`...

**Comment by StephenNorCalControls** [comment] 2021-10-29 22:42
So the system's I'm deploying on are prohibitively hard to update, and the build system I'm using would not be trivial to re-tool into using `onedir` instead of `onefile`, is there any way to change the order of operations where the archived is unpacked before loading those dependencies?

**Comment by rokm** [comment] 2021-10-29 22:45
> is there any way to change the order of operations where the archived is unpacked before loading those dependencies?

To unpack the embedded archive, the executable needs to be run - there's no way around that. But you could try to copy the `ucrtbase.dll` from `C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64\ucrtbase.dll` next to your `onefile` executable and distribute both to the target system.

**Comment by StephenNorCalControls** [comment] 2021-10-29 23:06
I tried adding ucrtbase.dll to the directory but it seems like the system32 located dll is still being used, according to event viewer.

**Comment by rokm** [comment] 2021-10-29 23:10
> I tried adding ucrtbase.dll to the directory but it seems like the system32 located dll is still being used, according to event viewer.

Can you check the full dependency chain? Is there an intermediate dependency (e.g., an `api-ms-*` DLL) that's also loaded from system32 and ends up loading system32 version of `ucrtbase.dll` (perhaps because it requires that old version)?

**Comment by rokm** [comment] 2021-10-29 23:13
Also, what Windows version is your target system?

**Comment by StephenNorCalControls** [comment] 2021-10-29 23:13
Is there a good way for me to do that on the target system? Or is it something I can only see during the PyInstaller build process? For reference, I'm building on one machine and re-distributing it to others with potentially different versions of Windows (Windows Server 2016, 2019, etc., and Windows 10 )

**Comment by StephenNorCalControls** [comment] 2021-10-29 23:14
> Also, what Windows version is your target system?

This particular one is Windows Server 2019 Version 1809 (OS Build 17763.2237)

**Comment by rokm** [comment] 2021-10-29 23:23
Hmm, I think it would be helpful to first establish a baseline w.r.t. what works and what does not. Does this error occur only with your application, or also if you build a simple hello-world program in `onefile` mode? Does the same hello-world program work in `onedir` mode? Are `api-ms-*` files also bundled in these builds (if so, from where)?

**Comment by rokm** [comment] 2021-10-29 23:27
> Is there a good way for me to do that on the target system?

I was thinking about running Dependency Walker against the application executable on the target system. However, as `onefile` has two processes (the parent that unpacks the embedded archive, and a child that actually runs), my previous assumptions about what DLLs are loaded and why might not hold anymore. In particular, it would help if you could determine which of the two processes crashes with the `ucrtbase.dll` error. 

That's why I'd like to know how both `onefile` and `onedir` builds of a hello-world application (if your actual application is too complicated to build in both modes) behave on the target system.

**Comment by StephenNorCalControls** [comment] 2021-10-29 23:29
Unfortunately this error only seems to be presenting itself when my application has run for ~45 minutes. It runs continuously as a windows service using pywin32, and there are other systems where it does work as intended. I think the likely cause is the fact that we're using the system ucrtbase.dll, and it's odd because I believe I originally began bundling those DLL's specifically because some systems didn't have them. I'm surprised that this issue is suddenly presenting itself because as far as I can tell, these bundled DLL's were previously being used by the application (I guess I can't say this for sure, but they would have to use them on system's that don't inherently have VC++ redist/wincrt installed).

**Comment by StephenNorCalControls** [comment] 2021-10-29 23:50
The second spawned process, the one that actually runs the code, is the one that appears to be crashing.

> In particular, it would help if you could determine which of the two processes crashes with the ucrtbase.dll error.

**Comment by rokm** [comment] 2021-10-30 00:02
> Unfortunately this error only seems to be presenting itself when my application has run for ~45 minutes. It runs continuously as a windows service using pywin32, and there are other systems where it does work as intended.

And just to make sure, this is not caused by temporary directory being removed (or attempted to be removed, resulting in at least partial removal of files) while the service is running?

**Comment by StephenNorCalControls** [comment] 2021-10-30 00:07
If you're talking about the temporary directory created when a bundled app first starts, I don't believe I do any kind of editing of the contents of those directories, so it wouldn't be caused by me, but I don't know if there are potentially other applications on the system that might be deleting it. I want to say that this isn't the case though, because one important functionality of the application is that it makes a lot of REST Api requests using the `requests` library, and always fails on the same request. I don't notice anything odd about the individual requests, and the only difference between each of the ~40000 calls is some slightly different json content.

**Comment by eric15342335** [comment] 2021-10-30 10:19
Maybe do not package the .dll for example remove `C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64\` in the path?

**Comment by StephenNorCalControls** [comment] 2021-11-01 16:02
> Maybe do not package the .dll for example remove `C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64\ in the path?`

Why would I do this? I'm not trying to be adversarial but I don't see a way that this would help. Are you saying it might use all the system dll's, instead of some from the system and some bundled, which might prevent a crash?

**Comment by rokm** [comment] 2021-11-01 17:33
Hmm... well, for what is worth, if `psutil` is to be believed, system `ucrtbase.dll` is used even for `onedir` builds even if it is collected:

```python
import psutil
import os

p = psutil.Process(os.getpid())
print("Process: %r" % (p))
print("Loaded DLLs:")

for dll in p.memory_maps():
  print(dll.path)
```
And `C:\Windows\System32\ucrtbase.dll` is also used when that script is run unfrozen in python:
* python.org python in environment where PATH is modified so that a custom version has highest priority:
```
> where ucrtbase.dll
C:\Program Files (x86)\Windows Kits\10\Redist\10.0.17763.0\ucrt\DLLs\x64\ucrtbase.dll
C:\Windows\System32\ucrtbase.dll
```
* anaconda python, which ships its own copy of `ms-api-*` DLLs and `ucrtbase.dll` so:
```
> where ucrtbase.dll
C:\Users\Rok\anaconda3\envs\pyi-dll-test\ucrtbase.dll
C:\Users\Rok\anaconda3\envs\pyi-dll-test\Library\bin\ucrtbase.dll
C:\Windows\System32\ucrtbase.dll
```

So I guess the question is, do we have any evidence that Windows even allows overriding of such DLLs? (And if it does not, we should probably stop collecting them...)

**Comment by bwoodsend** [comment] 2021-11-01 19:23
> So I guess the question is, do we have any evidence that Windows even allows overriding of such DLLs? (And if it does not, we should probably stop collecting them...)

I'm fairly certain that it doesn't but I can't remember where I read that.

**Comment by bwoodsend** [comment] 2021-11-01 19:26
I suppose one way to test would be to compile a shared library called `ucrtbase.dll` containing some made up functions, temporarily prepend it to `PATH` then load it with `ctypes.CDLL("ucrtbase.dll")` and see if it contains the made up functions or the ones that are supposed to be there?

**Comment by StephenNorCalControls** [comment] 2021-11-01 19:52
I looked through some of the Windows docs and found the following:

> Search Order for Desktop Applications
> Desktop applications can control the location from which a DLL is loaded by specifying a full path, using DLL redirection, or by using a manifest. If none of these methods are used, the system searches for the DLL at load time as described in this section.
> 
> Before the system searches for a DLL, it checks the following:
> 
> If a DLL with the same module name is already loaded in memory, the system uses the loaded DLL, no matter which directory it is in. The system does not search for the DLL.
> If the DLL is on the list of known DLLs for the version of Windows on which the application is running, the system uses its copy of the known DLL (and the known DLL's dependent DLLs, if any). The system does not search for the DLL. For a list of known DLLs on the current system, see the following registry key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\KnownDLLs.
> If a DLL has dependencies, the system searches for the dependent DLLs as if they were loaded with just their module names. This is true even if the first DLL was loaded by specifying a full path.

https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

And using `taslklist /m` on my deployed system reveals that `ucrtbase.dll` is loaded by several system executables by the time my application starts as a service, and so just by merit of the system starting up, it appears that it will use the system `ucrtbase.dll`. This means that unfortunately I think my only course is upgrading the system itself.

**Comment by rokm** [comment] 2021-11-01 21:08
Aha, [this](https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=msvc-160#local-deployment) explains things a bit better:  "Local deployment of the Universal CRT is supported..." but "There are two restrictions on local deployment to be aware of: On Windows 10 and Windows 11, the Universal CRT in the system directory is always used, even if an application includes an application-local copy of the Universal CRT. It's true even when the local copy is newer, because the Universal CRT is a core operating system component on Windows 10 and later."

So I think we should yank the "api-ms-win*.dll" and "ucrtbase.dll" off the allowed DLLs list, unless we want to support earlier Windows versions...

**Comment by bwoodsend** [comment] 2021-11-01 21:48
> So I think we should yank the "api-ms-win*.dll" and "ucrtbase.dll" off the allowed DLLs list, unless we want to support earlier Windows versions...

I'm still pretty firm on wanting to maintain support for Windows 7. [It's got about <sup>1</sup>/<sub>5</sub> of Windows users](https://www.netmarketshare.com/operating-system-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Custom%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22platformVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22platformsDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222021-01%22%2C%22dateEnd%22%3A%222021-10%22%2C%22segments%22%3A%22-1000%22%7D) using it.

**Comment by rokm** [comment] 2021-11-01 21:58
> > So I think we should yank the "api-ms-win*.dll" and "ucrtbase.dll" off the allowed DLLs list, unless we want to support earlier Windows versions...
> 
> I'm still pretty firm on wanting to maintain support for Windows 7. [It's got about 1/5 of Windows users](https://www.netmarketshare.com/operating-system-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Custom%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22platformVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22platformsDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222021-01%22%2C%22dateEnd%22%3A%222021-10%22%2C%22segments%22%3A%22-1000%22%7D) using it.

Fair enough.

**Comment by rokm** [comment] 2021-11-04 21:06
Closing the issue as the system copy of Universal CRT is always used on Windows 10 and 11 by Microsoft's design, as described [here](https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=msvc-160#local-deployment).

**Closed as completed by rokm** 2021-11-04 21:06 UTC
Labels: triage
