### ISSUE TITLE
Problems on Windows 10 when execute script

### ISSUE THREAD

**Issue by prsolucoes** [pyinstaller/pyinstaller#4049] opened 2019-02-06 02:54 UTC
Hi,

Im my last problem with PyInstaller on Windows 10 here to make it more organised.

Im using develop branch, on Windows 10 with latest Python (3.7.2) download from official site.

```
C:\Users\michelle\Developer\workspaces\python\qt5-app-win>pyinstaller --name="TestApp" --onefile --windowed --noconsole MyTestApp.spec
125 INFO: PyInstaller: 3.5.dev0
125 INFO: Python: 3.7.2
140 INFO: Platform: Windows-10-10.0.16299-SP0
140 INFO: UPX is not available.
140 INFO: Extending PYTHONPATH with paths
['C:\\Users\\michelle\\Developer\\workspaces\\python\\qt5-app-win',
 'C:\\Users\\michelle\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\site-packages\\PySide2',
 'C:\\Users\\michelle\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\site-packages\\shiboken2',
 'C:\\Users\\michelle\\Developer\\workspaces\\python\\qt5-app-win\\ucrt\\DLLs\\x86',
 'C:\\Users\\michelle\\Developer\\workspaces\\python\\qt5-app-win']
140 INFO: checking Analysis
140 INFO: Building Analysis because Analysis-00.toc is non existent
140 INFO: Initializing module dependency graph...
156 INFO: Initializing module graph hooks...
156 INFO: Analyzing base_library.zip ...
3531 INFO: running Analysis Analysis-00.toc
3546 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\python.exe
4807 INFO: Caching module hooks...
4807 INFO: Analyzing main.py
4838 INFO: Loading module hooks...
4838 INFO: Loading module hook "hook-encodings.py"...
4963 INFO: Loading module hook "hook-pydoc.py"...
4963 INFO: Loading module hook "hook-PySide2.py"...
5495 INFO: Processing pre-find module path hook   distutils
6672 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
7190 INFO: Processing pre-find module path hook   site
7190 INFO: site: retargeting to fake-dir 'C:\\Users\\michelle\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pyinstaller-3.5.dev0-py3.7.egg\\PyInstaller\\fake-modules'
9876 INFO: Loading module hook "hook-PySide2.QtCore.py"...
10003 INFO: Loading module hook "hook-PySide2.QtGui.py"...
10902 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
11027 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
11027 INFO: Loading module hook "hook-setuptools.py"...
11746 INFO: Loading module hook "hook-sysconfig.py"...
11746 INFO: Loading module hook "hook-xml.py"...
11809 INFO: Loading module hook "hook-distutils.py"...
11809 INFO: Loading module hook "hook-lib2to3.py"...
11824 INFO: Loading module hook "hook-numpy.core.py"...
11939 INFO: Loading module hook "hook-numpy.py"...
11939 INFO: Loading module hook "hook-pkg_resources.py"...
12502 INFO: Processing pre-safe import module hook   win32com
12595 INFO: Loading module hook "hook-pythoncom.py"...
12910 INFO: Loading module hook "hook-pywintypes.py"...
13238 INFO: Loading module hook "hook-win32com.py"...
13747 INFO: checking Tree
13841 INFO: Looking for ctypes DLLs
13888 INFO: Analyzing run-time hooks ...
13888 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
13904 INFO: Including run-time hook 'pyi_rth_pkgres.py'
13904 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
13904 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
13919 INFO: Looking for dynamic libraries
28200 INFO: Looking for eggs
28200 INFO: Using Python library C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\python37.dll
28200 INFO: Found binding redirects:
[]
28215 INFO: Warnings written to C:\Users\michelle\Developer\workspaces\python\qt5-app-win\build\MyTestApp\warn-MyTestApp.txt
28356 INFO: Graph cross-reference written to C:\Users\michelle\Developer\workspaces\python\qt5-app-win\build\MyTestApp\xref-MyTestApp.html
28403 INFO: checking PYZ
28403 INFO: Building PYZ because PYZ-00.toc is non existent
28403 INFO: Building PYZ (ZlibArchive) C:\Users\michelle\Developer\workspaces\python\qt5-app-win\build\MyTestApp\PYZ-00.pyz
30651 INFO: Building PYZ (ZlibArchive) C:\Users\michelle\Developer\workspaces\python\qt5-app-win\build\MyTestApp\PYZ-00.pyz completed successfully.
30682 INFO: checking PKG
30682 INFO: Building PKG because PKG-00.toc is non existent
30682 INFO: Building PKG (CArchive) PKG-00.pkg
42421 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
42421 INFO: Bootloader C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyinstaller-3.5.dev0-py3.7.egg\PyInstaller\bootloader\Windows-32bit\runw.exe
42437 INFO: checking EXE
42437 INFO: Building EXE because EXE-00.toc is non existent
42437 INFO: Building EXE from EXE-00.toc
42437 INFO: Appending archive to EXE C:\Users\michelle\Developer\workspaces\python\qt5-app-win\dist\TestApp.exe
42468 INFO: Building EXE from EXE-00.toc completed successfully.
```

But when i execute the EXE i still get the error:

![image](https://user-images.githubusercontent.com/395096/52252694-05213a00-28eb-11e9-92ed-b85e4065a760.png)

When i execute from terminal i got error:

```
$ ./TestApp.exe
Exception: [Errno 2] No such file or directory: 'C:\\support\\signature\\loader.py'
Traceback (most recent call last):
  File "pyscript", line 23, in bootstrap
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\support\\signature\\loader.py'
AttributeError: module 'signature_loader' has no attribute 'pyside_type_init'
SystemError: could not initialize part 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "site-packages\pyinstaller-3.5.dev0-py3.7.egg\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyinstaller-3.5.dev0-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyinstaller-3.5.dev0-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "platform.py", line 116, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyinstaller-3.5.dev0-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "subprocess.py", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyinstaller-3.5.dev0-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "signal.py", line 45, in <module>
  File "C:\Users\michelle\AppData\Local\Programs\Python\Python37-32\lib\functools.py", line 54, in update_wrapper
    value = getattr(wrapped, attr)
SystemError: <method-wrapper '__get__' of getset_descriptor object at 0x050CEE90> returned a result with an error set
```

Can anyone help me?

**Comment by nrhead** [comment] 2019-02-07 22:15
Im having the same issue

**Comment by philipbel** [comment] 2019-02-08 12:19
I am seeing this on Windows 7 with PyInstaller 3.4 and PySide2 5.12.1

**Comment by acasta69** [comment] 2019-02-09 17:51
Same is happening here on a Windows 10 Home machine, PyInstaller 3.4 and PySide2 5.12.1.
The same thing works fine when built on a Windows 7 Professional machine, with same Python and PyInstaller version but PySide2 5.12.0.

**Comment by kingmo888** [comment] 2019-02-11 08:49
Im having the same issue.

btw, It's has an error when I build it. ——'
4656 INFO: Processing pre-safe import module hook   six.moves
6138 INFO: Loading module hooks...
6139 INFO: Loading module hook "hook-certifi.py"...
6140 INFO: Loading module hook "hook-Crypto.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'Crypto.Math'
6246 INFO: Loading module hook "hook-cryptography.py"...
6672 INFO: Loading module hook "hook-encodings.py"...
6811 INFO: Loading module hook "hook-pydoc.py"...
6812 INFO: Loading module hook "hook-PySide2.py"...
6814 WARNING: Hidden import "numpy.core.multiarray" not found!
6814 INFO: Loading module hook "hook-PySide2.QtCore.py"...
6972 INFO: Loading module hook "hook-PySide2.QtGui.py"...
8021 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
8166 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
'

PySide2 5.1.2
73 INFO: PyInstaller: 3.4
73 INFO: Python: 3.7.2
74 INFO: Platform: Windows-7-6.1.7601-SP1

**Comment by htgoebel** [comment] 2019-02-13 09:35
Duplicate of #4040

**Closed by htgoebel** 2019-02-13 09:35 UTC
