### ISSUE TITLE
Bootloader in 3.0 Fails on Linux-32bit-arm

### ISSUE THREAD

**Issue by aclewis182** [pyinstaller/pyinstaller#1619] opened 2015-10-20 15:24 UTC
I've been using PyInstaller 2.1 for months using a boot loader built from the WAF on an ARM A9 processor.  I recently attempted to switch to PyInstaller 3.0, however when running the WAF to generate the boot loader (via the --no-lsb option) it fails to locate the DL library.

PyInstaller 2.0 works fine finding the library, but 3.0 doesn't.  I have attempted to set the LD_LIBRARY_PATH and the PRELOAD library pointing directly to the file.

**Comment by aclewis182** [comment] 2015-10-20 16:02
System Information: Debian running on an ARM A9 Cortex (Beagle Bone Black revC)
Python Version:  2.7.3

Using command `./waf distclean --no-lsb all` from the current develop branch it fails.  Below is the output from the config.log.  Really not sure where to go from here.

```
'distclean' finished successfully (0.001s)
'all' finished successfully (0.001s)
'distclean' finished successfully (0.001s)
Setting top to                           : /home/debian/installers/pyinstaller/bootloader 
Setting out to                           : /home/debian/installers/pyinstaller/bootloader/build 
Platform                                 : Linux-32bit detected 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for flags -m32                  : yes 
Checking for program 'strip'             : ['/usr/bin/strip'] 
Checking for library dl                  : not found 
The configuration failed
(complete log in /home/debian/installers/pyinstaller/bootloader/build/config.log)
debian@ceeweb-builder:~/installers/pyinstaller/bootloader$ cat build/config.log 
# project  configured on Tue Oct 20 15:57:52 2015 by
# waf 1.8.0 (abi 98, python 20703f0 on linux2)
# using ./waf distclean --no-lsb all
#
----------------------------------------
Setting top to
/home/debian/installers/pyinstaller/bootloader
----------------------------------------
Setting out to
/home/debian/installers/pyinstaller/bootloader/build
----------------------------------------
Platform
Linux-32bit detected
----------------------------------------
Checking for 'gcc' (C compiler)
find program=['gcc', 'cc'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/local/games', '/usr/games'] var='CC' -> ['/usr/bin/gcc']
find program=['ar'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/local/games', '/usr/games'] var='AR' -> ['/usr/bin/ar']
/usr/bin/gcc
----------------------------------------
Checking for flags -m32
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] c: build/.conf_check_07b992e65007614ad6cf90991797494c/test.c -> build/.conf_check_07b992e65007614ad6cf90991797494c/testbuild/test.c.1.o

['/usr/bin/gcc', '../test.c', '-c', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_07b992e65007614ad6cf90991797494c/testbuild/test.c.1.o']
[2/2] cprogram: build/.conf_check_07b992e65007614ad6cf90991797494c/testbuild/test.c.1.o -> build/.conf_check_07b992e65007614ad6cf90991797494c/testbuild/testprog

['/usr/bin/gcc', 'test.c.1.o', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_07b992e65007614ad6cf90991797494c/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic']
yes
----------------------------------------
Checking for program 'strip'
['/usr/bin/strip']
find program=['strip'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/local/games', '/usr/games'] var='STRIP' -> ['/usr/bin/strip']
----------------------------------------
Checking for library dl
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] c: build/.conf_check_20c8bbbb67026ac6d2616030e7ab854f/test.c -> build/.conf_check_20c8bbbb67026ac6d2616030e7ab854f/testbuild/test.c.1.o

['/usr/bin/gcc', '-m32', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=600', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_20c8bbbb67026ac6d2616030e7ab854f/testbuild/test.c.1.o']
err: cc1: error: unrecognized command line option ‘-m32’

from /home/debian/installers/pyinstaller/bootloader: Test does not build: Traceback (most recent call last):
  File "/home/debian/installers/pyinstaller/bootloader/.waf-1.8.0-415cfa9b7aa8bc4ccf25d068d876ef79/waflib/Tools/c_config.py", line 476, in run_c_code
    bld.compile()
  File "/home/debian/installers/pyinstaller/bootloader/.waf-1.8.0-415cfa9b7aa8bc4ccf25d068d876ef79/waflib/Build.py", line 182, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1): 
	{task 4446544: c test.c -> test.c.1.o}
['/usr/bin/gcc', '-m32', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=600', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_20c8bbbb67026ac6d2616030e7ab854f/testbuild/test.c.1.o']

not found
from /home/debian/installers/pyinstaller/bootloader: The configuration failed
```

**Comment by matysek** [comment] 2015-10-20 17:47
@aclewis182 Could you try a new version of the `waf` file if that fixes arm detection? https://waf.io/waf-1.8.15

**Comment by aclewis182** [comment] 2015-10-20 17:58
Replaced `waf`with the version you linked too.  Still shows as non-arm

```
debian@ceeweb-builder:~/installers/pyinstaller/bootloader$ sudo python waf --no-lsb configure build install
Setting top to                           : /home/debian/installers/pyinstaller/bootloader 
Setting out to                           : /home/debian/installers/pyinstaller/bootloader/build 
Platform                                 : Linux-32bit detected 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for flags -m32                  : yes 
Checking for program 'strip'             : /usr/bin/strip 
Checking for library dl                  : not found 
The configuration failed
(complete log in /home/debian/installers/pyinstaller/bootloader/build/config.log)
debian@ceeweb-builder:~/installers/pyinstaller/bootloader$ cat build/config.log 
# project  configured on Tue Oct 20 17:56:27 2015 by
# waf 1.8.15 (abi 98, python 20703f0 on linux2)
# using waf --no-lsb configure build install
#
----------------------------------------
Setting top to
/home/debian/installers/pyinstaller/bootloader
----------------------------------------
Setting out to
/home/debian/installers/pyinstaller/bootloader/build
----------------------------------------
Platform
Linux-32bit detected
----------------------------------------
Checking for 'gcc' (C compiler)
find program=['gcc', 'cc'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin'] var='CC' -> ['/usr/bin/gcc']
['/usr/bin/gcc', '-dM', '-E', '-']
out: #define __DBL_MIN_EXP__ (-1021)
#define __UINT_LEAST16_MAX__ 65535
#define __FLT_MIN__ 1.1754943508222875e-38F
#define __UINT_LEAST8_TYPE__ unsigned char
#define __INTMAX_C(c) c ## LL
#define __CHAR_BIT__ 8
#define __UINT8_MAX__ 255
#define __WINT_MAX__ 4294967295U
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __SIZE_MAX__ 4294967295U
#define __WCHAR_MAX__ 4294967295U
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
#define __DBL_DENORM_MIN__ ((double)4.9406564584124654e-324L)
#define __FLT_EVAL_METHOD__ 0
#define __unix__ 1
#define __UINT_FAST64_MAX__ 18446744073709551615ULL
#define __SIG_ATOMIC_TYPE__ int
#define __DBL_MIN_10_EXP__ (-307)
#define __FINITE_MATH_ONLY__ 0
#define __ARMEL__ 1
#define __GNUC_PATCHLEVEL__ 3
#define __UINT_FAST8_MAX__ 255
#define __DEC64_MAX_EXP__ 385
#define __INT8_C(c) c
#define __UINT_LEAST64_MAX__ 18446744073709551615ULL
#define __SHRT_MAX__ 32767
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __thumb2__ 1
#define __UINT_LEAST8_MAX__ 255
#define __GXX_TYPEINFO_EQUALITY_INLINE 0
#define __UINTMAX_TYPE__ long long unsigned int
#define __linux 1
#define __DEC32_EPSILON__ 1E-6DF
#define __CHAR_UNSIGNED__ 1
#define __UINT32_MAX__ 4294967295U
#define __LDBL_MAX_EXP__ 1024
#define __WINT_MIN__ 0U
#define __linux__ 1
#define __SCHAR_MAX__ 127
#define __WCHAR_MIN__ 0U
#define __INT64_C(c) c ## LL
#define __DBL_DIG__ 15
#define __SIZEOF_INT__ 4
#define __SIZEOF_POINTER__ 4
#define __USER_LABEL_PREFIX__ 
#define __STDC_HOSTED__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __FLT_EPSILON__ 1.1920928955078125e-7F
#define __APCS_32__ 1
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __DEC32_MAX__ 9.999999E96DF
#define __INT32_MAX__ 2147483647
#define __SIZEOF_LONG__ 4
#define __UINT16_C(c) c
#define __DECIMAL_DIG__ 17
#define __gnu_linux__ 1
#define __ARM_PCS_VFP 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __GNUC__ 4
#define __FLT_HAS_DENORM__ 1
#define __SIZEOF_LONG_DOUBLE__ 8
#define __BIGGEST_ALIGNMENT__ 8
#define __DBL_MAX__ ((double)1.7976931348623157e+308L)
#define __INT_FAST32_MAX__ 2147483647
#define __DBL_HAS_INFINITY__ 1
#define __DEC32_MIN_EXP__ (-94)
#define __THUMB_INTERWORK__ 1
#define __INT_FAST16_TYPE__ int
#define __LDBL_HAS_DENORM__ 1
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __INT_LEAST32_MAX__ 2147483647
#define __DEC32_MIN__ 1E-95DF
#define __DBL_MAX_EXP__ 1024
#define __DEC128_EPSILON__ 1E-33DL
#define __PTRDIFF_MAX__ 2147483647
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __SIZEOF_SIZE_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __GXX_ABI_VERSION 1002
#define __FLT_MIN_EXP__ (-125)
#define __INT_FAST64_TYPE__ long long int
#define __DBL_MIN__ ((double)2.2250738585072014e-308L)
#define __DEC128_MIN__ 1E-6143DL
#define __REGISTER_PREFIX__ 
#define __UINT16_MAX__ 65535
#define __DBL_HAS_DENORM__ 1
#define __UINT8_TYPE__ unsigned char
#define __NO_INLINE__ 1
#define __FLT_MANT_DIG__ 24
#define __VERSION__ "4.6.3"
#define __UINT64_C(c) c ## ULL
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __INT32_C(c) c
#define __DEC64_EPSILON__ 1E-15DD
#define __ORDER_PDP_ENDIAN__ 3412
#define __DEC128_MIN_EXP__ (-6142)
#define __INT_FAST32_TYPE__ int
#define __UINT_LEAST16_TYPE__ short unsigned int
#define unix 1
#define __INT16_MAX__ 32767
#define __SIZE_TYPE__ unsigned int
#define __UINT64_MAX__ 18446744073709551615ULL
#define __INT8_TYPE__ signed char
#define __thumb__ 1
#define __ELF__ 1
#define __FLT_RADIX__ 2
#define __INT_LEAST16_TYPE__ short int
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __UINTMAX_C(c) c ## ULL
#define __SIG_ATOMIC_MAX__ 2147483647
#define __VFP_FP__ 1
#define __SIZEOF_PTRDIFF_T__ 4
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define __INT_FAST16_MAX__ 2147483647
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_LEAST64_TYPE__ long long unsigned int
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MAX_10_EXP__ 38
#define __LONG_MAX__ 2147483647L
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __FLT_HAS_INFINITY__ 1
#define __unix 1
#define __UINT_FAST16_TYPE__ unsigned int
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __CHAR16_TYPE__ short unsigned int
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __INT_LEAST16_MAX__ 32767
#define __DEC64_MANT_DIG__ 16
#define __INT64_MAX__ 9223372036854775807LL
#define __UINT_LEAST32_MAX__ 4294967295U
#define __INT_LEAST64_TYPE__ long long int
#define __INT16_TYPE__ short int
#define __INT_LEAST8_TYPE__ signed char
#define __DEC32_MAX_EXP__ 97
#define __INT_FAST8_MAX__ 127
#define __INTPTR_MAX__ 2147483647
#define linux 1
#define __LDBL_MANT_DIG__ 53
#define __DBL_HAS_QUIET_NAN__ 1
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __INTPTR_TYPE__ int
#define __UINT16_TYPE__ short unsigned int
#define __WCHAR_TYPE__ unsigned int
#define __SIZEOF_FLOAT__ 4
#define __THUMBEL__ 1
#define __UINTPTR_MAX__ 4294967295U
#define __DEC64_MIN_EXP__ (-382)
#define __INT_FAST64_MAX__ 9223372036854775807LL
#define __FLT_DIG__ 6
#define __UINT_FAST64_TYPE__ long long unsigned int
#define __INT_MAX__ 2147483647
#define __INT64_TYPE__ long long int
#define __FLT_MAX_EXP__ 128
#define __DBL_MANT_DIG__ 53
#define __INT_LEAST64_MAX__ 9223372036854775807LL
#define __DEC64_MIN__ 1E-383DD
#define __WINT_TYPE__ unsigned int
#define __UINT_LEAST32_TYPE__ unsigned int
#define __SIZEOF_SHORT__ 2
#define __LDBL_MIN_EXP__ (-1021)
#define __arm__ 1
#define __INT_LEAST8_MAX__ 127
#define __ARM_ARCH_7A__ 1
#define __LDBL_MAX_10_EXP__ 308
#define __DBL_EPSILON__ ((double)2.2204460492503131e-16L)
#define __UINT8_C(c) c
#define __INT_LEAST32_TYPE__ int
#define __SIZEOF_WCHAR_T__ 4
#define __UINT64_TYPE__ long long unsigned int
#define __INT_FAST8_TYPE__ signed char
#define __DBL_DECIMAL_DIG__ 17
#define __DEC_EVAL_METHOD__ 2
#define __ORDER_BIG_ENDIAN__ 4321
#define __UINT32_C(c) c ## U
#define __INTMAX_MAX__ 9223372036854775807LL
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLT_DENORM_MIN__ 1.4012984643248171e-45F
#define __INT8_MAX__ 127
#define __UINT_FAST32_TYPE__ unsigned int
#define __CHAR32_TYPE__ unsigned int
#define __FLT_MAX__ 3.4028234663852886e+38F
#define __INT32_TYPE__ int
#define __SIZEOF_DOUBLE__ 8
#define __FLT_MIN_10_EXP__ (-37)
#define __INTMAX_TYPE__ long long int
#define __DEC128_MAX_EXP__ 6145
#define __GNUC_MINOR__ 6
#define __UINTMAX_MAX__ 18446744073709551615ULL
#define __DEC32_MANT_DIG__ 7
#define __DBL_MAX_10_EXP__ 308
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __INT16_C(c) c
#define __STDC__ 1
#define __PTRDIFF_TYPE__ int
#define __UINT32_TYPE__ unsigned int
#define __UINTPTR_TYPE__ unsigned int
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __ARM_EABI__ 1
#define __DEC128_MANT_DIG__ 34
#define __LDBL_MIN_10_EXP__ (-307)
#define __SIZEOF_LONG_LONG__ 8
#define __LDBL_DIG__ 15
#define __FLT_DECIMAL_DIG__ 9
#define __UINT_FAST16_MAX__ 4294967295U
#define __GNUC_GNU_INLINE__ 1
#define __UINT_FAST8_TYPE__ unsigned char
#define __ARM_FEATURE_DSP 1

find program=['ar'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin'] var='AR' -> ['/usr/bin/ar']
/usr/bin/gcc
----------------------------------------
Checking for flags -m32
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling build/.conf_check_098a8bce595f8d3c18a4eaf8f238036f/test.c

['/usr/bin/gcc', '../test.c', '-c', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_098a8bce595f8d3c18a4eaf8f238036f/testbuild/test.c.1.o']
[2/2] Linking build/.conf_check_098a8bce595f8d3c18a4eaf8f238036f/testbuild/testprog

['/usr/bin/gcc', 'test.c.1.o', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_098a8bce595f8d3c18a4eaf8f238036f/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic']
yes
----------------------------------------
Checking for program 'strip'
/usr/bin/strip
find program=['strip'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin'] var='STRIP' -> ['/usr/bin/strip']
----------------------------------------
Checking for library dl
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling build/.conf_check_9aa7e8606a3449eaeb892be823c3881e/test.c

['/usr/bin/gcc', '-m32', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=600', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_9aa7e8606a3449eaeb892be823c3881e/testbuild/test.c.1.o']
err: cc1: error: unrecognized command line option ‘-m32’

from /home/debian/installers/pyinstaller/bootloader: Test does not build: Traceback (most recent call last):
  File "/home/debian/installers/pyinstaller/bootloader/.waf-1.8.15-197e3a39328a9fe5ab63f655760c3695/waflib/Configure.py", line 334, in run_build
    bld.compile()
  File "/home/debian/installers/pyinstaller/bootloader/.waf-1.8.15-197e3a39328a9fe5ab63f655760c3695/waflib/Build.py", line 185, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1): 
	{task 4856208: c test.c -> test.c.1.o}
['/usr/bin/gcc', '-m32', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=600', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_9aa7e8606a3449eaeb892be823c3881e/testbuild/test.c.1.o']

not found
from /home/debian/installers/pyinstaller/bootloader: The configuration failed
```

**Comment by matysek** [comment] 2015-10-20 18:16
> ['/usr/bin/gcc', '-m32', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=600', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', '/home/debian/installers/pyinstaller/bootloader/build/.conf_check_9aa7e8606a3449eaeb892be823c3881e/testbuild/test.c.1.o']
> err: cc1: error: unrecognized command line option ‘-m32’

This is probably the cause of the failure. Try remove '-m32' from the wscript file.

**Comment by aclewis182** [comment] 2015-10-20 18:23
That compiled!  I'll test out the output from the boot loader and update this.  Thank you for the quick responses.

**Comment by matysek** [comment] 2015-10-20 18:28
@aclewis182 What is your linux distribution and Python version? Is this all what needs to be done to fix this?
* use latest `waf`
* ignore -m32 option when 32bit arm linux is detected?

**Comment by aclewis182** [comment] 2015-10-20 18:31
In order to compile the boot loader - what you have listed is all I had done from the develop branch.  Still testing the boot loader itself tho.  ATM having a hard time finding the run/runw output..

PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

Python 2.7.3

**Comment by aclewis182** [comment] 2015-10-20 18:41
Confirmed.  It's complied and installed the boot loader properly under `Linux-32bit-arm` and building the one file output works thus far on two different machines.

**Comment by matysek** [comment] 2015-10-20 22:37
@aclewis182 it should be fixed. Could you verify that?

**Closed by matysek** 2015-10-20 22:37 UTC
Labels: bootloader, Linux

**Comment by aclewis182** [comment] 2015-10-21 14:40
6d65e7c Seems to compile the boot loader properly on the Beagle Bone.  Thank you for the swift response and support!

**Comment by jtrexr2** [comment] 2016-01-06 22:01
Hello, I'm having a similar issue of using PyInstaller on a BeagleBone Black (revC, ARM A9). I downloaded PyInstaller-3.0, commented out the relevant lines of the wscript file with the -m32 option, and updated to the latest WAF (1.8.15). Compilation of the bootloader appears to succeed using:
```
./waf-1.8.15 configure --no-lsb all
```
```
debian@arm:/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader$ sudo ./waf-1.8.15 configure --no-lsb all
Setting top to                           : /usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader 
Setting out to                           : /usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build 
Platform                                 : Linux-32bit detected 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for flags -m32                  : yes 
Checking for program 'strip'             : /usr/bin/strip 
Checking for library dl                  : yes 
Checking for library m                   : yes 
Checking for library z                   : yes 
Checking for flags -Wl,--as-needed       : yes 
'configure' finished successfully (2.702s)
'all' finished successfully (0.001s)
'distclean' finished successfully (0.029s)
Setting top to                           : /usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader 
Setting out to                           : /usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build 
Platform                                 : Linux-32bit detected 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for flags -m32                  : yes 
Checking for program 'strip'             : /usr/bin/strip 
Checking for library dl                  : yes 
Checking for library m                   : yes 
Checking for library z                   : yes 
Checking for flags -Wl,--as-needed       : yes 
'configure' finished successfully (2.742s)
Waf: Entering directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/debug'
[ 1/12] Compiling src/main.c
[ 2/12] Compiling src/pyi_archive.c
[ 3/12] Compiling src/pyi_global.c
[ 4/12] Compiling src/pyi_launch.c
[ 5/12] Compiling src/pyi_path.c
[ 6/12] Compiling src/pyi_python.c
[ 7/12] Compiling src/pyi_python27_compat.c
[ 8/12] Compiling src/pyi_pythonlib.c
[ 9/12] Compiling src/pyi_utils.c
[10/12] Compiling src/pyi_win32_utils.c
[11/12] Linking build/debug/run_d
[12/12] Processing build/debug/run_d
Waf: Leaving directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/debug'
'build_debug' finished successfully (7.675s)
Waf: Entering directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/release'
[ 1/12] Compiling src/main.c
[ 2/12] Compiling src/pyi_archive.c
[ 3/12] Compiling src/pyi_global.c
[ 4/12] Compiling src/pyi_launch.c
[ 5/12] Compiling src/pyi_path.c
[ 6/12] Compiling src/pyi_python.c
[ 7/12] Compiling src/pyi_python27_compat.c
[ 8/12] Compiling src/pyi_pythonlib.c
[ 9/12] Compiling src/pyi_utils.c
[10/12] Compiling src/pyi_win32_utils.c
[11/12] Linking build/release/run
[12/12] Processing build/release/run
Waf: Leaving directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/release'
'build_release' finished successfully (7.557s)
Waf: Entering directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/debug'
+ install /usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/PyInstaller/bootloader/Linux-32bit-arm/run_d (from build/debug/run_d)
Waf: Leaving directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/debug'
'install_debug' finished successfully (0.110s)
Waf: Entering directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/release'
+ install /usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/PyInstaller/bootloader/Linux-32bit-arm/run (from build/release/run)
Waf: Leaving directory `/usr/local/lib/python2.7/dist-packages/pyinstaller_appveyor_tunning/pyinstaller-appveyor_tunning/bootloader/build/release'
'install_release' finished successfully (0.105s)
```

However, when I build the executable for my Python 2.7.9 script, I get "RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import errors":

```
debian@arm:~/Screen/src$ pyinstaller -F MultiLab_Screen.py
144 INFO: wrote /home/debian/Screen/src/MultiLab_Screen.spec
178 INFO: UPX is not available.
186 INFO: Extending PYTHONPATH with /home/debian/Screen/src
188 INFO: checking Analysis
190 INFO: Building Analysis because out00-Analysis.toc non existent
204 INFO: Looking for graph hooks ...
215 INFO: running Analysis out00-Analysis.toc
364 INFO: Analyzing MultiLab_Screen.py
40242 INFO: Looking for import hooks ...
40294 INFO: Processing hook   hook-distutils.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-distutils.py:15: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import distutils
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-distutils.py:16: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import os
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-distutils.py:17: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import sys
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-distutils.py:18: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import sysconfig
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-distutils.py:20: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.compat import base_prefix
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-distutils.py:21: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks.hookutils import relpath_to_config_or_make
40348 INFO: Processing hook   hook-xml.py
45725 INFO: Processing hook   hook-wx.lib.pubsub.core.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-wx.lib.pubsub.core.py:11: RuntimeWarning: Parent module 'pyi_hook.wx.lib.pubsub' not found while handling absolute import
  import os
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-wx.lib.pubsub.core.py:12: RuntimeWarning: Parent module 'pyi_hook.wx.lib.pubsub' not found while handling absolute import
  import PyInstaller.utils.hooks.hookutils
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-wx.lib.pubsub.core.py:14: RuntimeWarning: Parent module 'pyi_hook.wx.lib.pubsub' not found while handling absolute import
  from PyInstaller.utils.hooks.hookutils import logger
45742 INFO: wx.lib.pubsub: Adding kwargs protocol path
45743 INFO: Processing hook   hook-encodings.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-encodings.py:11: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks.hookutils import collect_submodules
50366 INFO: Processing hook   hook-xml.sax.py
50374 INFO: Processing hook   hook-httplib.py
50388 INFO: Analyzing run-time hooks ...
50505 INFO: Looking for dynamic libraries
57603 INFO: Looking for eggs - TODO
57605 INFO: Using Python library /usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0
57886 INFO: Warnings written to /home/debian/Screen/src/build/MultiLab_Screen/warnMultiLab_Screen.txt
57897 INFO: checking PYZ
57899 INFO: Rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
57900 INFO: Building PYZ (ZlibArchive) out00-PYZ.toc
58222 INFO: checking PKG
58223 INFO: Rebuilding out00-PKG.toc because out00-PKG.pkg is missing
58225 INFO: Building PKG (CArchive) out00-PKG.pkg
175096 INFO: checking EXE
175098 INFO: Rebuilding out00-EXE.toc because MultiLab_Screen missing
175100 INFO: Building EXE from out00-EXE.toc
175101 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/bootloader/Linux-32bit-arm/run
175106 INFO: Appending archive to EXE /home/debian/Screen/src/dist/MultiLab_Screen
```

Executing the resultant file yields the below error ('no module named _core'). I'm assuming this is due to the import errors:
```
debian@arm:~/Screen/src$ ./dist/MultiLab_Screen 
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/loader/pyimod04_importers.py", line 309, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/loader/pyimod04_importers.py", line 309, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/wx/core.py", line 6, in <module>
    from ._core import *
ImportError: No module named _core

```
Has anyone encountered this? I'm pretty new to using Linux and would appreciate any help.

**Comment by htgoebel** [comment] 2016-01-07 15:20
@jtrexr2 This issue is about "Bootloader in 3.0 fails on Linux-32bit-arm". But obviously your build passes, So your issues do *not* belong into this ticket. Additionally, you freeze fails, so it's absolutely obvious that your frozen application will not run.

Please open a new issue about you freeze failing and provide mor information as described in https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
