### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64'

### ISSUE THREAD

**Issue by sebunger** [pyinstaller/pyinstaller#6331] opened 2021-10-31 22:55 UTC
Hi,

Our automated builds started failing this Monday (1st Nov 2021) in an invocation of pyinstaller with the above message. I have attached a complete log of the creation of the virtual environment and the crash from one of our builds. The last successful build was Friday and the first failing build was Monday. No changes in the relevant parts of our systems or code were made, so the most likely cause was the release of pyinstaller 4.6.

This is running on Ubuntu Bionic.

[tt.txt](https://github.com/pyinstaller/pyinstaller/files/7449902/tt.txt)

**Comment by rokm** [comment] 2021-10-31 23:07
```
Traceback (most recent call last):
  File "LinPy/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/program.spec", line 19, in <module>
    noarchive=False)
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 277, in __init__
    self.__postinit__()
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 501, in assemble
    self._check_python_library(self.binaries)
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 605, in _check_python_library
    python_lib = bindepend.get_python_library_path()
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 897, in get_python_library_path
    python_libname = findLibrary(name)
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 775, in findLibrary
    lib = _which_library(name, paths)
  File "/home/jslave/srecs/workspace/Firmware/RadioApp/pipe-build/bucket-5/bld/RunupApp/LinPy/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 806, in _which_library
    for _path in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64'
```

Yeah, that looks like a regression in 4.6. 4473ea6d53c420890014ced504b3be41ec2463b4 refactored that bit of codepath, but preserved the original behavior due to use of `glob`. Then d50e8093fed6c86cded3f5977450a2f8f8ccd2c2 replaced the `glob` with `os.listdir`, but that requires us to first check whether the path actually exists. 

(And it slipped through our CI because with python installed there, the python shared library's location is inferred from the python executable, and so this codepath is not really tested).

**Comment by Gui-U** [comment] 2021-11-02 14:59
Hi,
I have the same issue on Centos 7 + Python 3.6 with fresh install on docker. I applied the patch #6337 just before Pyinstaller call and it works again :)

Could you release a hotfix version of Pyinstaller to pypi with this patch?

Thanks

**Comment by bwoodsend** [comment] 2021-11-02 20:32
The fix is in the v4 branch. @Legorooj release 4.6.1 when ready...

**Closed as completed** 2021-11-02 20:32 UTC
Labels: bug

**Comment by johnthagen** [comment] 2021-11-15 16:40
PyInstaller 4.7 has been released: https://pypi.org/project/pyinstaller/4.7/
