### ISSUE TITLE
OS X app built with 'LSUIElement': 'True' still appears in dock

### ISSUE THREAD

**Issue by samuelcouch** [pyinstaller/pyinstaller#2075] opened 2016-06-29 18:18 UTC
pyinstaller `3.3.dev0+8689a5d`
Python `3.5.1`

Within my `.spec` I am including 

``` python
info_plist={
        'LSUIElement': 'True'
}
```

and the generated `Info.plist` does have

``` xml
<key>LSUIElement</key>
<string>True</string>
```

However the icon still appears in the doc and it shows up when I press ⌘-Tab and in the Force Quit list. 

I am building with `pyinstaller --clean install/pyinstaller-osx.spec` in OS X 10.11.5

**Comment by cbenhagen** [comment] 2016-09-06 11:02
Duplicate of https://github.com/pyinstaller/pyinstaller/issues/1917

**Comment by tnarik** [comment] 2018-04-29 16:47
This is due to the behaviour of the bootloader, as explained in #1206. I would recommend closing this one.

**Closed** 2018-04-29 17:43 UTC
Labels: OS X, duplicate
