### ISSUE TITLE
Issue with packaging python script with scipy.stats import and numpy v1.22.0

### ISSUE THREAD

**Issue by bwiecek1** [pyinstaller/pyinstaller#6504] opened 2022-01-12 17:33 UTC
On Windows 10 system EXE created using pyinstaller with python script that imports scipy.stats aborts with numpy.distutils not found error. Here's the example script ([ScipyStats_NumpyBug.py.txt](https://github.com/pyinstaller/pyinstaller/files/7856539/ScipyStats_NumpyBug.py.txt) attached):

import numpy
import matplotlib
import scipy.stats

print("Fix worked :)")

EXE was created using command line:
pyinstaller --clean --onefile ScipyStats_NumpyBug.py

versions:
python==3.9.9
pyinstaller==4.7
matplotlib==3.5.1
numpy==1.22.0
scipy==1.7.3

the runtime error ([runtime_error.txt](https://github.com/pyinstaller/pyinstaller/files/7856547/runtime_error.txt) attached):
Traceback (most recent call last):
  File "ScipyStats_NumpyBug.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\__init__.py", line 441, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\stats.py", line 43, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\distributions.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\stats\_distn_infrastructure.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\__init__.py", line 401, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_minimize.py", line 27, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "scipy\optimize\_constraints.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "numpy\testing\__init__.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "numpy\testing\_private\extbuild.py", line 11, in <module>
ModuleNotFoundError: No module named 'numpy.distutils'
[20728] Failed to execute script 'ScipyStats_NumpyBug' due to unhandled exception!

I have attached the output ([pyinstaller_out.txt](https://github.com/pyinstaller/pyinstaller/files/7856548/pyinstaller_out.txt)) of pyinstaller run in windows command prompt as shown:
pyinstaller --debug=all --clean --onefile ScipyStats_NumpyBug.py --log-level=DEBUG > pyinstaller_out.txt 2>&1

NOTE:
Downgrading numpy from 1.22.0 to 1.21.5 fixes the issue and the script runs properly

**Comment by rokm** [comment] 2022-01-12 17:39
Duplicate of #6485.

**Closed as completed by rokm** 2022-01-12 17:39 UTC
Labels: solution:duplicate
