### ISSUE TITLE
CoreFoundation fails to load

### ISSUE THREAD

**Issue by pauloacmartinez** [pyinstaller/pyinstaller#4130] opened 2019-03-18 13:42 UTC
macOS Mojave, python 3.7.2, PyInstaller 3.5.dev0:

I recreated a minimal example of the problem I am having with pyserial loading CoreFoundation at this part:
https://github.com/pyserial/pyserial/blob/v3.4/serial/tools/list_ports_osx.py#L30

foo.py:
```python
import ctypes
import ctypes.util

print(ctypes.util.find_library('CoreFoundation'))
cf = ctypes.cdll.LoadLibrary(ctypes.util.find_library('CoreFoundation'))
```

pyinstaller --onedir --hidden-import CoreFoundation foo.py

Log when executing:
```
/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes/__init__.py", line 356, in __init__
OSError: dlopen(/Users/pacm/workspace/factory/dist/foo/CoreFoundation, 6): no suitable image found.  Did find:
        /Users/pacm/workspace/factory/dist/foo/CoreFoundation: not a file
        /Users/pacm/workspace/factory/dist/foo/CoreFoundation: not a file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 4, in <module>
  File "ctypes/__init__.py", line 434, in LoadLibrary
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll '/Users/pacm/workspace/factory/dist/foo/CoreFoundation'. Most probably this dynlib/dll was not found when the application was frozen.
[9161] Failed to execute script foo
```

There is a `CoreFoundation` folder in the bundle with the files
- `_CoreFoundation.cpython-37m-darwin.so`
- `_inlines.cpython-37m-darwin`

If I remove the folder and rename the .so file to `CoreFoundation.so` in the root directory of the bundle, it is correctly loaded.
I think I need to write a hook which makes the correct symlink, but I don't know where to start.
By the way, the CoreFoundation is already being added in my application without the need of a hidden import.

**Comment by cbenhagen** [comment] 2019-05-20 08:47
I can reproduce this. In your simple example you can just remove the `--hidden-import CoreFoundation` to make it work. In a real project I am unable to do this as I have both `import CoreServices` and `ctypes.cdll.LoadLibrary(ctypes.util.find_library('CoreServices'))` in my code and dependencies.

As this has nothing to do with CoreServices but is an issue with all pyobjc libraries in combination with ctypes.cdd it would make sense to change the title accordingly.

```
PyInstaller: 3.5.dev0+gd7405248
Python: 3.7.3
Platform: Darwin-18.6.0-x86_64-i386-64bit
```

**Comment by cbenhagen** [comment] 2019-05-20 08:56
More information might be found by digging through the changes mentioned in https://github.com/pyinstaller/pyinstaller/issues/1609

**Comment by cbenhagen** [comment] 2019-05-20 09:06
@htgoebel or @matysek can you point me in the right direction to create a test or even a fix for this?

**Comment by bjones1** [comment] 2019-05-28 17:10
Without checking this, add the following to `tests/functional/test_libraries.py`:

``` Python
@pytest.mark.skipif(not is_darwin, reason='Applies only to OS X')
def test_OSX_CoreFoundation(pyi_builder):
    pyi_builder.test_source(
        """
        import ctypes
        import ctypes.util

        print(ctypes.util.find_library('CoreFoundation'))
        cf = ctypes.cdll.LoadLibrary(ctypes.util.find_library('CoreFoundation'))
        """)
```

I don't understand the failing case -- a missing library? So I can't recommend a fix.

**Comment by pacm93** [comment] 2019-05-29 08:30
I will try to build a more complete example next week, but it basically happens when using pyserial and pywebview in the same project.

**Comment by cbenhagen** [comment] 2019-06-04 07:56
@bjones1 this test shows the error:

```python
@pytest.mark.skipif(not is_darwin, reason='Applies only to OS X')
def test_OSX_CoreFoundation(pyi_builder):
    pyi_builder.test_source(
        """
        import CoreFoundation
        import ctypes.util

        cf = ctypes.cdll.LoadLibrary(ctypes.util.find_library('CoreFoundation'))
        """)

```

While this both works:
```python
@pytest.mark.skipif(not is_darwin, reason='Applies only to OS X')
def test_OSX_CoreFoundation(pyi_builder):
    pyi_builder.test_source(
        """
        import CoreFoundation
        """)
```

```python
@pytest.mark.skipif(not is_darwin, reason='Applies only to OS X')
def test_OSX_CoreFoundation(pyi_builder):
    pyi_builder.test_source(
        """
        import ctypes.util

        cf = ctypes.cdll.LoadLibrary(ctypes.util.find_library('CoreFoundation'))
        """)
```

**Comment by pacm93** [comment] 2019-06-04 12:16
Ok now I got a better case to show.
If I generate a simple example with pywebview, like:

- example_pywebview.py
```python
import webview

webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
```
pyinstaller --onefile example_pywebview.py

CoreFoundation is present and correctly loaded.
When I add pyserial to the script:

- example_pywebview_with_serial.py
```python
import serial.tools.list_ports as list_ports
import webview

webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
```
pyinstaller --onefile example_pywebview_with_serial.py

the same error I reported before happens:

```python
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes/__init__.py", line 356, in __init__
OSError: dlopen(/var/folders/c6/4wx35jtj7l37qp_sp2jn605w0000gn/T/_MEIX4u9kR/CoreFoundation, 6): no suitable image found.  Did find:
        /var/folders/c6/4wx35jtj7l37qp_sp2jn605w0000gn/T/_MEIX4u9kR/CoreFoundation: not a file
        /private/var/folders/c6/4wx35jtj7l37qp_sp2jn605w0000gn/T/_MEIX4u9kR/CoreFoundation: not a file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "execs/example_pywebview.py", line 1, in <module>
    import serial.tools.list_ports as list_ports
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/pacm/.local/share/virtualenvs/factory-zzUmKPRP/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/serial/tools/list_ports.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/pacm/.local/share/virtualenvs/factory-zzUmKPRP/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/pacm/.local/share/virtualenvs/factory-zzUmKPRP/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/serial/tools/list_ports_osx.py", line 30, in <module>
  File "ctypes/__init__.py", line 434, in LoadLibrary
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll '/var/folders/c6/4wx35jtj7l37qp_sp2jn605w0000gn/T/_MEIX4u9kR/CoreFoundation'. Most probably this dynlib/dll was not found when the application was frozen.
[4243] Failed to execute script example_pywebview_with_serial
```

My workaround was to delete the CoreFoundation folder and move .so files up to the bundle root:

- example_pywebview_with_serial_workaround.py
```python
import os
import shutil
import sys

core_foundation_dir = os.path.join(sys._MEIPASS, "CoreFoundation")
shutil.move(os.path.join(core_foundation_dir, "_CoreFoundation.cpython-37m-darwin.so"), os.path.join(sys._MEIPASS, "CoreFoundation.so"))
shutil.move(os.path.join(core_foundation_dir, "_inlines.cpython-37m-darwin.so"), os.path.join(core_foundation_dir, "inlines.so"))
shutil.rmtree(core_foundation_dir)

import serial.tools.list_ports as list_ports
import webview

webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
```
pyinstaller --onefile example_pywebview_with_serial_workaround.py

Now I have problems with pywebview,
CoreFoundation seems to be correct but inlines cannot be found:

```python
[pywebview] PyObjC cannot be loaded
Traceback (most recent call last):
  File "site-packages/webview/__init__.py", line 98, in import_cocoa
  File "/Users/pacm/.local/share/virtualenvs/factory-zzUmKPRP/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/webview/cocoa.py", line 15, in <module>
  File "/Users/pacm/.local/share/virtualenvs/factory-zzUmKPRP/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/Foundation/__init__.py", line 9, in <module>
  File "/Users/pacm/.local/share/virtualenvs/factory-zzUmKPRP/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/CoreFoundation/__init__.py", line 11, in <module>
ModuleNotFoundError: No module named 'CoreFoundation._inlines'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "site-packages/webview/__init__.py", line 87, in import_qt
  File "/Users/pacm/.local/share/virtualenvs/factory-zzUmKPRP/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/webview/qt.py", line 28, in <module>
ModuleNotFoundError: No module named 'PyQt5'
Traceback (most recent call last):
  File "execs/example_pywebview.py", line 13, in <module>
    webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
  File "site-packages/webview/__init__.py", line 226, in create_window
  File "site-packages/webview/__init__.py", line 149, in _initialize_imports
Exception: You must have either PyObjC (for Cocoa support) or Qt with Python bindings installed in order to use pywebview.
[4481] Failed to execute script example_pywebview
```

**Comment by cbenhagen** [comment] 2019-06-10 15:01
@bjones1 can you reproduce the issue?

**Comment by bjones1** [comment] 2019-06-11 12:57
I'm out of time to work on this, unfortunately. I'll return when I can.

**Comment by gpraceman** [comment] 2019-08-14 04:45
macOS Sierra, Python 3.6.8, Pyinstaller 3.4

I'm running into the same error.  I am using pyserial, but not pywebview.  Though, I do have PyObjC installed to play audio.  pywebview seems to need PyObjC on macOS .

What gets my goat is that things were working before I installed PyObjC.  Even removing that dependency from my project I still get that error.  I haven't yet tried with Pyinstaller 3.5 or the dev code.

**Comment by gpraceman** [comment] 2019-08-14 19:51
Maybe I didn't do a good enough job earlier of removing the PyObjC related code for audio, as I tried again and was able to get the packaged app to run.  I reverted back to my previous audio code.  Pyserial is working fine, including the listing of installed ports.  What is curious is that there is no CoreFoundation folder and files in the latest packaged app.  So, maybe Pyserial is finding the CoreFoundation from the OS's python in order to list the installed ports?

I have two other apps that are using the PyObjC related code for audio, but not Pyserial.  Those are packaging and running just fine.  That packaging does include the CoreFoundation folder and files.  So, it appears that the combination of Pyserial with anything PyObjC related that seems to be the issue.

At least I can now package and run all of my apps.  Unfortunately, I am under a time crunch to deliver them, so I don't have time to futz with this issue any more.

**Comment by Ragiton** [comment] 2019-10-22 02:24
Thank you for the information you have posted about this problem.  I was able to get my app to work after using the workaround described.

**Comment by xmeow** [comment] 2020-08-24 09:35
Same situation here, after some dig into how pyinstaller's loader sequence. I found that there should be somehow or other a builtin CoreFoundation in the bundled app, or from `/System/Library/Frameworks/CoreFoundation.framework/CoreFoundatio` ,so there is no reason to pack another one. So my workaround would be add 'CoreFoundation' to exclude session in spec file, and turn whoever using the CoreFundation from 
```
import CoreFoundation
```
to
```
if getattr(sys, 'frozen', False):
    import ctypes
    import ctypes.util
    CoreFoundation = ctypes.cdll.LoadLibrary(ctypes.util.find_library('CoreFoundation'))
else:
    import CoreFoundation
```

**Comment by fifofonix** [comment] 2020-11-03 02:25
Still an issue with python 3.8.6, pyinstaller 4.0, pyserial 3.4.

Very similar to @pauloacmartinez's example above, the following also re-creates the problem.

Any workarounds that do not require modifying underlying libraries would be much appreciated.

Working
```python
from pynput.mouse import Controller
MOUSE = Controller()
MOUSE.move(10, 10)
```

Non-working - Generates stack trace (see below) about inability to import CoreFoundation:
```python
from pynput.mouse import Controller
import serial.tools.list_ports
MOUSE = Controller()
MOUSE.move(10, 10)
``` 

Trace:
```
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes/__init__.py", line 373, in __init__
OSError: dlopen(/var/folders/rz/89_3rwrs61zf7_xpv91f78sm0000gp/T/_MEI715VLf/CoreFoundation, 6): no suitable image found.  Did find:
	/var/folders/rz/89_3rwrs61zf7_xpv91f78sm0000gp/T/_MEI715VLf/CoreFoundation: not a file
	/private/var/folders/rz/89_3rwrs61zf7_xpv91f78sm0000gp/T/_MEI715VLf/CoreFoundation: not a file
```

**Comment by rokm** [comment] 2020-11-03 09:44
This issue should already be fixed by #5182. Please try `develop` version until 4.1 is released.

**Comment by fifofonix** [comment] 2020-11-03 13:09
Thanks @rokm I can confirm the current `develop` version resolves the issue for me.  Looking forward to the release.

**Comment by rokm** [comment] 2020-11-04 19:46
Thanks for the feedback, @fifofonix! I'll be closing this issue, then. 

If any further problems with `CoreFoundation` are encountered, please open a new issue with updated details.

**Closed by rokm** 2020-11-04 19:46 UTC

**Comment by irineul** [comment] 2020-11-10 17:43
I was having a similar error with version 4.0, upgrading to the dev version fixed the issue. Thanks a lot @rokm !

**Comment by maksimu** [comment] 2021-02-23 21:47
> I was having a similar error with version 4.0, upgrading to the dev version fixed the issue. Thanks a lot @rokm !

Good one! Worked for me as well. Had issue using `fido2` library
