### ISSUE TITLE
Pyinstaller 

### ISSUE THREAD

**Issue by JoeHelp** [pyinstaller/pyinstaller#3317] opened 2018-02-19 20:53 UTC
Test.py
import encodings
print('Test')

**Sample of Compilations Warning**

    102 INFO: PyInstaller: 3.3.1
    102 INFO: Python: 3.7.0b1
    104 INFO: Platform: Windows-10-10.0.14393-SP0
    2771 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\apps\python\python37\python.exe
    2801 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\apps\python\python37\python.exe

**Error - executing the program** 
Fatal Python error: initfsencoding:
    unable to load the file system codec zipimport.ZipImportError:
    can't find module 'encodings' Current thread 0x0000289c (most recent call first):

**Comment by abravetti** [comment] 2018-03-05 09:24
duplicate of https://github.com/pyinstaller/pyinstaller/issues/3219?

**Comment by htgoebel** [comment] 2018-03-05 21:27
Python 3.7 is not yet supported. Did you read the README, the manual, or at least the website?

**Closed by htgoebel** 2018-03-05 21:27 UTC

**Comment by yun9157** [comment] 2018-08-17 12:56
only reinstall it?  is it have solve other  way?

**Comment by pvanik1** [comment] 2018-08-30 12:31
Even though 3.7 now seems to be supported, I'm still getting the same zipimport encodings error

**Comment by amritkp89** [comment] 2018-09-01 22:01
I am not sure 3.7 is still supported yet!! I got this error now.. :(

**Comment by erotavlas85** [comment] 2018-09-03 13:08
+1

**Comment by htgoebel** [comment] 2018-09-04 15:59
PyInstaller supports Python 3.7 Up to a few minutes ago you have had to build the bootloaders yourself, as already written e.g https://github.com/pyinstaller/pyinstaller/issues/3642#issuecomment-408619680. Bootloaders are now rebuild, so please use the current development head.
