### ISSUE TITLE
QtWebEngine: Missing ANGLE OpenGL DLLs on Windows

### ISSUE THREAD

**Issue by The-Compiler** [pyinstaller/pyinstaller#4322] opened 2019-07-18 14:13 UTC
With these versions:

- PyInstaller 3.5 or develop branch
- Python 3.7.4 (64-bit)
- Windows 10
- PyQt5 5.12.3 (Qt 5.12.4) or 5.13.0 (Qt 5.13.0)
- PyQtWebEngine 5.12.1 or 5.13.0 (matching PyQt above)

When trying to build this example:

```python
# workaround for #4293
import os, sys
if hasattr(sys, '_MEIPASS'):
    os.environ['PATH'] += os.pathsep + sys._MEIPASS

from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView

app = QApplication([])
view = QWebEngineView()
view.show()
app.exec_()
```

I get those errors on the commandline:

```
Failed to load libEGL (The specified module could not be found.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (The specified module could not be found.)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (The specified module could not be found.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (The specified module could not be found.)
Failed to load and resolve WGL/OpenGL functions
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to load libEGL (The specified module could not be found.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (The specified module could not be found.)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (The specified module could not be found.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (The specified module could not be found.)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (The specified module could not be found.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (The specified module could not be found.)
Failed to load and resolve WGL/OpenGL functions
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.
```

This is due to a missing `libEGL.dll` and `d3dcompiler_47.dll` in the `dist` directory. When I copy them over from `site-packages\PyQt5\bin`, everything works fine.

**Comment by bjones1** [comment] 2019-08-02 00:09
@The-Compiler, thanks for finding the root cause. That was a big help in fixing it. I appreciate it. This is fixed in c0f3c9d77444554abb27488d47c0bb3d48abb4e4.

**Closed by bjones1** 2019-08-02 00:09 UTC
