### ISSUE TITLE
Another ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

### ISSUE THREAD

**Issue by keunglh** [pyinstaller/pyinstaller#2021] opened 2016-06-01 17:55 UTC
Recently downloaded pyinstaller v3.2
on Windows 10 64bit
Python 3.5.1 32bit.
Anaconda 4.0.0 32bit

I used pyinstaller --onefile sort.py

created the .exe in the dist folder, moved it into the desired folder and ran it. Ended up with a blank CLI screen for a couple of seconds and then this flashed for another second before exiting out. I read through some of the older issues (January) and they mentioned it was a problem with the setuptools, but since the fix was to downgrade to 19.2 and I am on 20.3, I wanted to ask for help again in whether or not that is still the only fix so far. I'm assuming that with a new version, it should have been fixed. I also added:

    hiddenimports = collect_submodules('pkg_resources._vendor')

As it was mentioned in another issue as a fix. Still no luck.

![image](https://cloud.githubusercontent.com/assets/14348489/15719856/73cf3e5e-27f7-11e6-8d4d-57f128827cf1.png)

White space to remove sensitive information.

**Comment by bjones1** [comment] 2016-06-01 20:26
This looks like a duplicate of #2007. Would you test using my branch to see if that fixes the problem?

**Comment by keunglh** [comment] 2016-06-01 20:51
Thanks for the reply. I installed PyInstaller through pip, so I'm not sure how I could test using your branch. Is it possible to just tell me where I can edit the necessary changes?

Would it be a new line in the .spec file?

**Comment by bjones1** [comment] 2016-06-01 21:30
Go to https://github.com/bjones1/pyinstaller/tree/collect_submodules_rewrite, click the clone or download button, unzip the resulting file, then run python setup.py install.

**Comment by keunglh** [comment] 2016-06-01 21:31
Should I uninstall the existing installation first I'm guessing then? What would be the easiest way for me to uninstall that, since it appears to be in a couple of different locations.

**Comment by bjones1** [comment] 2016-06-01 21:33
No, you don't need to uninstall. Just install this new version.

**Comment by bjones1** [comment] 2016-06-03 20:07
This should be fixed by #2007. Re-open if not.

**Comment by keunglh** [comment] 2016-06-03 21:15
I've tried going to the link above, and it gives me the 404 Error so I think that's a bad link. I went to the #2007 fix but I couldn't find anywhere that I could clone or download the merged files to install.

**Comment by bjones1** [comment] 2016-06-03 21:22
The files are merged, so the link doesn't work any more. Clone/download from https://github.com/pyinstaller/pyinstaller.

**Comment by keunglh** [comment] 2016-06-04 21:50
Unfortunately, the process is now stuck at:
![image](https://cloud.githubusercontent.com/assets/14348489/15802353/4ab2c1ce-2a74-11e6-83fa-c1f92ec0aa02.png)

For about the past 5 minutes. Before it would have never happened.

**Comment by bjones1** [comment] 2016-06-05 03:32
Try running with `--clean` to see if that helps.

**Comment by bjones1** [comment] 2016-06-08 21:43
Since I haven't heard anything, I'm closing this issue.

**Closed by bjones1** 2016-06-08 21:43 UTC
Labels: Windows
