### ISSUE TITLE
Qt 5.14: Missing QtQmlModels for QtWebEngine

### ISSUE THREAD

**Issue by The-Compiler** [pyinstaller/pyinstaller#4631] opened 2020-01-15 14:20 UTC
On macOS, when building a simple QtWebEngine application ([example](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/testbrowser/testbrowser_webengine.py)) with PyQt 5.14, QtWebEngineProcess crashes:

```
dyld: Library not loaded: @rpath/QtQmlModels.framework/Versions/5/QtQmlModels
  Referenced from: .../testbrowser_webengine.app/Contents/MacOS/PyQt5/Qt/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
```

The QtQmlModels library was split off from QtQml in Qt 5.14.

Copying `lib/python3.7/site-packages/PyQt5/Qt/lib/QtQmlModels.framework` from a PyQt installation to `Contents/MacOS/PyQt5/Qt/lib/` in the .app seems to fix the issue. I've taken a look at the different Qt hooks, but couldn't find a way to specify additional libraries there.

This happens with both PyInstaller v3.6 and the development branch (4.0.dev0+g555c5e81), both on Python 3.7.

It only seems to happen on macOS, Windows works fine.

**Comment by bjones1** [comment] 2020-01-16 14:57
Thanks for reporting this. I'm guessing https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/hooks/qt.py#L436 needs updating -- it's a mapping from a Qt library to its dynamic dependencies. Would you mind taking a look at that to see what's missing?

**Comment by bjones1** [comment] 2020-02-05 04:02
This is now fixed in d08a42c612a91cc320c54f9e812fe967b9c8594a. Thanks @The-Compiler for finding the root cause!

**Comment by The-Compiler** [comment] 2020-02-10 14:50
I must've missed your earlier comment in the depths of my mail inbox, so thanks for taking care of it, @bjones1!

I'm guessing this can be closed then?

**Comment by bjones1** [comment] 2020-02-10 15:33
My pleasure. Oops, yes -- closing.

**Closed by bjones1** 2020-02-10 15:33 UTC
