### ISSUE TITLE
[5020] LOADER: Failed to load tcl/tk libraries on some machines

### ISSUE THREAD

**Issue by aliencaocao** [pyinstaller/pyinstaller#6360] opened 2021-11-09 03:20 UTC
## Description of the issue
My packaged app will not run at all, it opens a console and immediately closes with the error message `[5020] LOADER: Failed to load tcl/tk libraries` on some machines. This exact same binary file works perfectly on 3 other windows 10 and 2 other windows 11 PCs and Laptops. The machine that it will not work on is on a fresh install of Windows 10 21H1 and running in Audit mode. This should be caused by splash screen as nothing else was initialized.
### Context information (for bug reports)

* Output of `pyinstaller --version`:  5.0dev0
* Version of Python: 3.9,8
* Platform:  Windows UK english
* How you installed Python:  python.org
* Did you also try this on another platform? Does it work there? More on this later

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
 I don't think its my code issue as I said exactly same binary file (not even exact same code, its exact same exe) works on many other PCs running the same platform

### Stacktrace / full error message

```
[5020] LOADER: Failed to load tcl/tk libraries
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by aliencaocao** [comment] 2021-11-09 04:03
![IMG_20211109_120233.jpg](https://user-images.githubusercontent.com/20109683/140859907-82e513a6-393f-4b5d-b909-498afbed3655.jpg)
Sorry had to use phone as my work PC blocks github, but here is the detailed log in debug mode, without UPX

**Comment by aliencaocao** [comment] 2021-11-09 04:39
Tried on a couple more PCs, and i think windows Audit mode is the reason. Any idea on why is this so? I cant find any online info on this.

**Comment by rokm** [comment] 2021-11-09 08:41
Duplicate of #6284.

**Closed as completed** 2021-11-09 08:43 UTC
Labels: solution:duplicate

**Comment by aliencaocao** [comment] 2021-11-09 09:32
I do not understand. How is missing dll related to my problem with Audit mode? And how do I fix it?

**Comment by rokm** [comment] 2021-11-09 09:48
Onefile + splash screen needs `vcruntime140.dll`; either next to the onefile executable, or installed on the system. I don't think it's the audit mode that's problematic here, it's the lack of `vcruntime140.dll` on that system.

**Comment by aliencaocao** [comment] 2021-11-09 11:10
Placing the dll besides the exe did not work, even after i regsvr32 it.
Only installing the c++ redistributable 2019 worked.
Thanks for the guidance still, I would never have realised its due to missing dll.

**Comment by CraigerCDT** [comment] 2022-02-24 23:27
Placing the DLL either next to the EXE or in \windows\system32 worked here on a Win10x64 system...
