### ISSUE TITLE
app can't run in paths containing GBK (chinese) characters.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#824] opened 2014-10-18 14:49 UTC
**Original date**: 2013/11/15
**Original reporter**: *hanghang3103 AND 163 DOT  COOM *

I'm using PyInstaller-2.1 to build a python 2.7 app in Windows 7 (32bit), the buiding is successful. When I run the app in GBK characters paths, it throws errors as follow:

C:\Users\wangzh\Desktop\测试>mtkanpp.exe
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\PyInstaller\PyInstaller\loader\pyi_importers.py", line 513, in install
    sys.meta_path.append(FrozenImporter())
  File "C:\PyInstaller\PyInstaller\loader\pyi_importers.py", line 157, in __init__
    raise ImportError("Can't load frozen modules.")
ImportError: Can't load frozen modules.

My system's page code is: 936 (ANSI/OEM - Chinese Simpled GBK). I add same debug info in PyInstaller/loader/pyi_importers.py:

        for pyz_filepath in sys.path:
            try:
                print pyz_filepath
                # Unzip zip archive bundled with the executable.
                self._pyz_archive = ZlibArchive(pyz_filepath)
                # Verify the integrity of the zip archive with Python modules.
                self._pyz_archive.checkmagic()
                # End this method since no Exception was raised we can assume
                # ZlibArchive was successfully loaded. Let's remove 'pyz_filepath'
                # from sys.path.
                sys.path.remove(pyz_filepath)
                # Some runtime hook might need access to the list of available
                # frozen module. Let's make them accessible as a set().
                self.toc = set(self._pyz_archive.toc.keys())
                # Return - no error was raised.
                return
            except IOError:
                # Item from sys.path is not ZlibArchive let's try next.
                continue
            except ArchiveReadError:
                # Item from sys.path is not ZlibArchive let's try next.
                continue
        # sys.path does not contain filename of executable with bundled zip archive.
        # Raise import error.
        raise ImportError("Can't load frozen modules.")

When I rebuilder and run the app, same errors report as follow:

C:\Users\wangzh\Desktop\测试>mtkanpp.exe
C:\Users\wangzh\AppData\Local\Temp\_MEI178242
C:\Users\wangzh\Desktop\娴嬭瘯
C:\Users\wangzh\Desktop\娴嬭瘯\mtkanpp.exe?278016
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\PyInstaller\PyInstaller\loader\pyi_importers.py", line 513, in install
    sys.meta_path.append(FrozenImporter())
  File "C:\PyInstaller\PyInstaller\loader\pyi_importers.py", line 157, in __init__
    raise ImportError("Can't load frozen modules.")
ImportError: Can't load frozen modules.

**Comment by matysek** [comment] 2015-07-30 11:59
This is duplicate of #1323

**Closed by matysek** 2015-07-30 11:59 UTC
Labels: @high, PY3, v2.1, Windows
