### ISSUE TITLE
ImportError during runtime when dynamically importing a package with relative import that gets masked by a top-level package 

### ISSUE THREAD

**Issue by ento** [pyinstaller/pyinstaller#4141] opened 2019-03-24 05:43 UTC
..and when the path of the dynamically imported package is shorter than the length of `sys._MEIPASS + 1`. (And even if the dynamically imported path is longer, there still might be import errors if `path[SYS_PREFIXLEN+1:]` consists of existing package name(s)).

* Python: 3.5.3 installed through apt
* PyInstaller: 3.4 (also reproduced on the current `develop` branch's HEAD, which is 8c27d26)
* OS: Debian 9.5 (Pixelbook Crostini)

I faced this error when trying to use a plugin for Anki 2.1, and traced it to path manipulation happening in [FrozenImporter.find_spec](https://github.com/pyinstaller/pyinstaller/blob/8c27d2668cb9dea14302a0cffffb7dd997574ee1/PyInstaller/loader/pyimod03_importers.py#L532-L542). It seems like the code assumes that the module being imported is within the packaged app, but the assumption breaks down when the app wants to import a plugin that lives somewhere outside of the packaged app.

[Here's a minimum example with traceback in the README](https://github.com/ento/pyinstaller-relative-import-mcve). There are two identical "plugin"s inside `p/`. `plugin_0_longer_than_dist_main` gets imported successfully. `plugin_1` fails because `entry_name` in the linked code above ends up being `"app"` when trying to do `from .app import hook` - since `app` is already in the packaged app, it exists in `self.toc` and gets returned but doesn't have the `hook` module.

```
# packaged code
main.py # imports app
app/
  __init__.py

# dynamically imported code
p/
  plugin_0_longer_than_dist_main/
    __init__.py # from .app import hook
    app/
      hook.py
  plugin_1/
    __init__.py  # from .app import hook
    app/
      hook.py
```

I tried to write a runtime hook for this, but I wasn't sure if exporting `hiddenimports` is something supported by runtime hooks. I got a `pkg_resources.DistributionNotFound` error when trying to run the app wit ha runtime hook that imports PyInstaller's helpers for finding modules.

To support dynamic imports, it seems like `p = p[SYS_PREFIXLEN+1:]` should only be done when `p` also starts with `SYS_PREFIX`. I'm not really sure though, since I'm not familiar with PyInstaller's codebase.

Lastly, I'm not sure if relative imports is a necessary condition for this error.

**Comment by ArunAug** [comment] 2019-03-29 03:40
Found kind of issues, fixed by adding _binaries=[(' ', '.')]_ in the spec file generated by pyinstaller.
Also updating _--hidden imports_ will fix the masking of the top-level package.

Then again running _pyinstaller file.spec_ fixes the issues for me. Hope you find something useful.

**Comment by ento** [comment] 2019-03-29 15:31
Setting `binaries` didn't work. For one thing, setting that value fails with

> Unable to find " " when adding binary and data files.

The other thing is: `binaries` is for [non-python modules](https://pyinstaller.readthedocs.io/en/v3.4/spec-files.html#spec-file-operation), and this issue is about importing python modules, so I don't think it applies here.

Also, since this issue is about dynamically importing modules at run time, it's not possible to list module names at build time to specify with `--hidden-import`.

**Comment by dae** [comment] 2019-07-02 23:59
I came here to report this issue only to find someone had already done so. As ento has mentioned, the issue here is for pyinstaller apps that provide an add-on ability, where users can add code after the application has been packaged, so it doesn't appear that changes to the spec file will make any difference. I've added a check that the prefix is the same, and it seems to resolve the issue without causing any regressions that I could notice - I'll send along a pull request.

**Comment by htgoebel** [comment] 2020-01-17 11:21
Thanks for the example repo.

The issue is manifold:
1. While `main.py` extents the path, you are not telling PyInstaller about it (by setting PYTHONPATH). 
2. You are not telling PyInstaller to include modules from `p/...`. You can verify this by opening `build/main/xref-main.html`: there is only `app`, but not a single plugin.
3. Your frozen app is not working at all and the error you are reported are by chance. Proof:
```
$ pyinstaller main.py --yes
$ cd dist
$ main/main
[…]
FileNotFoundError: [Errno 2] No such file or directory: '…/dist/p'
```

If you are using PyInstaller commercially, I suggest you to fund development or at least  This analysis took about 45 minutes, worth 60–80€.

**Comment by dae** [comment] 2020-01-17 21:52
From your reply, I'm afraid I think you may have misinterpreted the problem. The use case here is allowing an already frozen app (which is free and open source by the way) to load Python files from an external path at runtime. The app is frozen with the core functionality and distributed to users, and the users can add extra functionality by placing Python files in a particular path, with each user potentially using different files that are not known at the freezing step. The app imports any files in that folder at runtime, allowing the user to extend the app without needing to install a full Python development environment themselves. This means that PyInstaller will have no knowledge of any files in that path during the build process.

The change in PR #4299 seems to resolve the reported issue with path lengths, and I have not noticed any regressions in the last 10 months - but I don't know enough about the code to know whether it might impact other apps.

**Comment by htgoebel** [comment] 2020-12-28 22:27
Indeed, I did not understand the actual issue. Now the I reviewed your pull-request, I could reproduce it. Please see my comments on the pull-request.

**Closed** 2021-01-11 17:09 UTC
Labels: bug
