### ISSUE TITLE
Python optimization -O -OO in pyinstaller

### ISSUE THREAD

**Issue by ask-kumbar** [pyinstaller/pyinstaller#5637] opened 2021-03-16 08:08 UTC
if I run the command
set PYTHONOPTIMIZE=2 && pyinstaller sample.spec or python -OO -m PyInstaller sample.spec
python version = 3.8.8
pyinstaller version = 4.2
windows 10
the .pyc files which are going inside the output directory are not getting optimized noarchive=True. But optimization is getting reflected in the _pycache_ folder
![Screenshot (38)](https://user-images.githubusercontent.com/48949692/111275361-11485b80-865c-11eb-8ba7-3ebd48a9e498.png)
I want the .pyc files which are going into the exe to be optimized could you please help me

**Comment by bwoodsend** [comment] 2021-03-16 10:13
What makes you think that they're not getting optimized? The `.pyo` suffix has been renamed to just `.pyc` so you can't tell just by looking at the filenames.

**Comment by bwoodsend** [comment] 2021-03-16 10:14
Also even OO rarely saves more than 100KB or so. It's a pretty useless feature.

**Comment by ask-kumbar** [comment] 2021-03-16 12:33
how do we know they are optimized because the source code in the pycache is renamed with .cpython-38.opt-2.pyc

**Comment by ask-kumbar** [comment] 2021-03-16 12:34
how can we check if they are optimized or not.

**Comment by rokm** [comment] 2021-03-16 13:24
> how can we check if they are optimized or not.

If you can't tell the difference, does it really matter then?

---

But you might, in fact, really be ending up with non-optimized version of byte-compiled modules, depending on whether your build environment is clean or not (i.e., if you ran pyinstaller in it before or not). That's due to incomplete transition from `.pyc/.pyo` naming scheme to new `__pycache__/*.pyc` one (which is also causing us not re-use the already-compiled modules __pycache__, and "polluting" the source directory by placing `.pyc`/`.pyo` files next to source `.py` files).

Reproducing steps (on linux):
```python
# program.py: simple test program
import psutil
```

Let's first run the program in python interpreter with and without optimization:
```
python program.py 
PYTHONOPTIMIZE=2 python program.py
```
And check the file sizes in resulting `__pycache__`
```
$ ls -l venv/lib64/python3.9/site-packages/psutil/__pycache__/_common.cpython-39.*
-rw-rw-r--. 1 rok rok 16932 mar 16 13:50 venv/lib64/python3.9/site-packages/psutil/__pycache__/_common.cpython-39.opt-2.pyc
-rw-rw-r--. 1 rok rok 20803 mar 16 13:50 venv/lib64/python3.9/site-packages/psutil/__pycache__/_common.cpython-39.pyc
```
---

Now remove all `.pyc` and `.pyo` files and freeze the program without optimizations: 
```
cd venv; find \( -name "*.pyo" -o -name "*.pyc" \) -delete; cd ..
pyinstaller --clean --noconfirm --distpath dist-noopt-clean --debug noarchive program.py
```

and repeat the same for optimized version:
```
cd venv; find \( -name "*.pyo" -o -name "*.pyc" \) -delete; cd ..
PYTHONOPTIMIZE=2 pyinstaller --clean --noconfirm --distpath dist-opt-clean --debug noarchive program.py
```
Check the sizes:
```
$ ls -l dist-noopt-clean/program/psutil/_common.pyc 
-rw-rw-r--. 1 rok rok 20803 mar 16 14:06 dist-noopt-clean/program/psutil/_common.pyc
$ ls -l dist-opt-clean/program/psutil/_common.pyc 
-rw-rw-r--. 1 rok rok 16932 mar 16 14:06 dist-opt-clean/program/psutil/_common.pyc
```

All good here.

---

Now, let's clean the `venv` only before first build.
```
cd venv; find \( -name "*.pyo" -o -name "*.pyc" \) -delete; cd ..
pyinstaller --clean --noconfirm --distpath dist-noopt-v1 --debug noarchive program.py
PYTHONOPTIMIZE=2 pyinstaller --clean --noconfirm --distpath dist-opt-v1 --debug noarchive program.py
```

Check the sizes:
```
(venv) [rok@alpha pyi-optim]$ ls -l dist-noopt-v1/program/psutil/_common.pyc 
-rw-rw-r--. 1 rok rok 20803 mar 16 14:09 dist-noopt-v1/program/psutil/_common.pyc
(venv) [rok@alpha pyi-optim]$ ls -l dist-opt-v1/program/psutil/_common.pyc 
-rw-rw-r--. 1 rok rok 20803 mar 16 14:09 dist-opt-v1/program/psutil/_common.pyc
```

Ooops, both builds ended up with non-optimized byte-compiled modules.

---

Similarly, if we clean `venv` only once, but reverse the order of builds:
```
cd venv; find \( -name "*.pyo" -o -name "*.pyc" \) -delete; cd ..
PYTHONOPTIMIZE=2 pyinstaller --clean --noconfirm --distpath dist-opt-v2 --debug noarchive program.py
pyinstaller --clean --noconfirm --distpath dist-noopt-v2 --debug noarchive program.py
```

Check the sizes:
```
$ ls -l dist-noopt-v2/program/psutil/_common.pyc 
-rw-rw-r--. 1 rok rok 16932 mar 16 14:22 dist-noopt-v2/program/psutil/_common.pyc
$ ls -l dist-opt-v2/program/psutil/_common.pyc 
-rw-rw-r--. 1 rok rok 16932 mar 16 14:22 dist-opt-v2/program/psutil/_common.pyc
```

So this time both ended up with optimized version.

---

So I'm marking this as a bug, which will hopefully go away once we sort out the module naming and reuse.

**Comment by ask-kumbar** [comment] 2021-03-17 08:44
thank you for demonstrating but need clear pycache everytime we build the package.

**Closed** 2021-03-17 14:09 UTC
Labels: bug
