### ISSUE TITLE
importlib.metadata.PackageNotFoundError with numpy

### ISSUE THREAD

**Issue by mtsamorim** [pyinstaller/pyinstaller#8417] opened 2024-04-18 16:40 UTC
Hi guys, I changed my Python version to 3.10 because of problems with hooks, but now it seems to be giving another error when I run the executable

```
Traceback (most recent call last):
  File "FMDprocessor.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\testing\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\testing\assertions.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\core\duck_array_ops.py", line 36, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\core\dask_array_ops.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\core\nputils.py", line 14, in <module>
  File "xarray\namedarray\utils.py", line 60, in module_available
  File "importlib\metadata\__init__.py", line 996, in version
  File "importlib\metadata\__init__.py", line 969, in distribution
  File "importlib\metadata\__init__.py", line 548, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for numpy
[8336] Failed to execute script 'FMDprocessor' due to unhandled exception!
```

i found the topic importlib.metadata.PackageNotFoundError: regex while building an .exe with pyinstaller #6033 but I didn't understand very well, I even tried modifying the .spec file

```
# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import copy_metadata

datas = []
datas += copy_metadata('numpy')

a = Analysis(
    ['FMDprocessor.py'],
    pathex=[],
    binaries=[],
    datas=[('C:\\Users\\malva\\OneDrive\\Área de Trabalho\\V6\\assets', 'assets')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FMDprocessor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

```
putting
```
from PyInstaller.utils.hooks import copy_metadata

datas = []
datas += copy_metadata('numpy')
```
and I tried to run the executable again but it didn't work

In this case, when I create the executable, on the command line will I have to pass all the libraries that are in the error?
like that `pyinstaller --onefile --copy-metadata numpy --copy-metadata xarray --copy-metadata importlib mycode.py`?

**Comment by rokm** [comment] 2024-04-18 17:30
This is duplicate of #8392; adding `--copy-metadata xarray` to your PyInstaller command should do the trick.

The spec modification did not work for you because you did not pass the created `datas` array to `Analysis` (where you should have merged it with the list that you are already passing via `datas` array).

> In this case, when I create the executable, on the command line will I have to pass all the libraries that are in the error?

Yes, until we add hook for `xarray` to `pyinstaller-hooks-contrib` repository and create a new release.

**Closed as completed** 2024-04-18 21:41 UTC
