### ISSUE TITLE
SystemError("objcopy Failure") - upx corrupts bootloader

### ISSUE THREAD

**Issue by kalikaneko** [pyinstaller/pyinstaller#1863] opened 2016-03-07 22:15 UTC
I'm doing a simple test with an input file that only has a 'print "hello world"' statement.

I'm getting the following error:

```
24 INFO: PyInstaller: 3.2.dev0+g8677d49.mod
24 INFO: Python: 2.7.8
25 INFO: Platform: Linux-4.3.0-1-amd64-x86_64-with-debian-stretch-sid
26 INFO: wrote /home/kali/tmp/pyinst-MERGE/bar.spec
30 INFO: UPX is available.
31 INFO: Extending PYTHONPATH with paths
['/home/kali/tmp/pyinst-MERGE', '/home/kali/tmp/pyinst-MERGE']
31 INFO: checking Analysis
40 INFO: checking PYZ
44 INFO: checking PKG
44 INFO: Building because toc changed
44 INFO: Building PKG (CArchive) out00-PKG.pkg
2382 INFO: Bootloader /home/kali/src/pyinstaller/PyInstaller/bootloader/Linux-64bit/run
2383 INFO: checking EXE
2383 INFO: Building EXE because out00-EXE.toc is non existent
2383 INFO: Building EXE from out00-EXE.toc
2388 INFO: Appending archive to ELF section in EXE /home/kali/tmp/pyinst-MERGE/dist/bar
objcopy --add-section pydata=/home/kali/tmp/pyinst-MERGE/build/bar/out00-PKG.pkg /home/kali/tmp/pyinst-MERGE/dist/bar
RETCODE>>> 1
Traceback (most recent call last):
  File "/home/kali/Virtualenvs/pyinst-multi/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0+g8677d49', 'console_scripts', 'pyinstaller')()
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 756, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 702, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 407, in __init__
    self.__postinit__()
  File "/home/kali/src/pyinstaller/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 565, in assemble
    raise SystemError("objcopy Failure")
SystemError: objcopy Failure
```

the specific objcopy error says:

<code>
objcopy: error: the input file '/home/kali/tmp/pyinst-MERGE/dist/bar' has no sections
</code>

any idea about what's wrong and how to fix it?

**Comment by kalikaneko** [comment] 2016-03-08 03:30
git bisect points commit 85dfef01953 as the one that introduces the error.

**Comment by htgoebel** [comment] 2016-03-08 12:49
There may be some artefacts of an old run hanging around. Please try running pyinstaller with `--clean` once.

**Comment by kalikaneko** [comment] 2016-03-08 15:12
I tried, but still getting the same error.
Any other info that can be useful for debugging?

**Comment by htgoebel** [comment] 2016-03-08 15:16
Are you using MERGE? Merge is broken, see the release notes.

**Comment by kalikaneko** [comment] 2016-03-08 15:30
I was originally testing MERGE in this environment, but this error raises even when building a single script:

```
samsara 戝 ~/tmp 
10746 ◯ : md pyinstaller-single                                                                                                                                                     

samsara 戝 ~/tmp 
10747 ◯ : cd pyinstaller-single                                                                                                                                                     

samsara 戝 ~/tmp/pyinstaller-single 
10748 ◯ : echo "print 'hello world'" > test.py                                                                                                                                      

samsara 戝 ~/tmp/pyinstaller-single 
10749 ◯ : virtualenv ev                                                                                                                                                             
New python executable in /home/kali/tmp/pyinstaller-single/ev/bin/python
Installing setuptools, pip, wheel...done.

samsara 戝 ~/tmp/pyinstaller-single 
10750 ◯ : source ev/bin/activate                                                                                                                                                    
(ev) 
samsara 戝 ~/tmp/pyinstaller-single 
10751 ◯ : cd                                                                                                                                                                        
(ev) 
samsara 戝 ~ 
10752 ◯ : cd src/pyinstaller                                                                                                                                                        
(ev) 
samsara 戝 ~/src/pyinstaller ➤ fd84293|develop⚡
10753 ± : python setup.py develop                                                                                                                                           [2h7m] ✹
running develop
running egg_info
writing requirements to PyInstaller.egg-info/requires.txt
writing PyInstaller.egg-info/PKG-INFO
writing top-level names to PyInstaller.egg-info/top_level.txt
writing dependency_links to PyInstaller.egg-info/dependency_links.txt
writing entry points to PyInstaller.egg-info/entry_points.txt
reading manifest file 'PyInstaller.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'bootloader/build'
no previously-included directories found matching 'bootloader/.waf*'
no previously-included directories found matching 'bootloader/waf3-*'
warning: no previously-included files found matching 'bootloader/.lock-waf*'
no previously-included directories found matching 'old'
no previously-included directories found matching 'scripts'
warning: no previously-included files found matching '.*'
warning: no previously-included files found matching '*.yml'
writing manifest file 'PyInstaller.egg-info/SOURCES.txt'
running build_ext
Creating /home/kali/tmp/pyinstaller-single/ev/lib/python2.7/site-packages/PyInstaller.egg-link (link to .)
Adding PyInstaller 3.2.dev0+gfd84293.mod to easy-install.pth file
Installing pyinstaller script to /home/kali/tmp/pyinstaller-single/ev/bin
Installing pyi-grab_version script to /home/kali/tmp/pyinstaller-single/ev/bin
Installing pyi-archive_viewer script to /home/kali/tmp/pyinstaller-single/ev/bin
Installing pyi-bindepend script to /home/kali/tmp/pyinstaller-single/ev/bin
Installing pyi-set_version script to /home/kali/tmp/pyinstaller-single/ev/bin
Installing pyi-makespec script to /home/kali/tmp/pyinstaller-single/ev/bin

Installed /home/kali/src/pyinstaller
Processing dependencies for PyInstaller==3.2.dev0+gfd84293.mod
Searching for setuptools==20.2.2
Best match: setuptools 20.2.2
Adding setuptools 20.2.2 to easy-install.pth file
Installing easy_install-3.5 script to /home/kali/tmp/pyinstaller-single/ev/bin
Installing easy_install script to /home/kali/tmp/pyinstaller-single/ev/bin

Using /home/kali/tmp/pyinstaller-single/ev/lib/python2.7/site-packages
Finished processing dependencies for PyInstaller==3.2.dev0+gfd84293.mod
(ev) 
samsara 戝 ~/src/pyinstaller ➤ fd84293|develop⚡
10754 ± : cd ~/tmp/pyinstaller-single                                                                                                                                       [2h7m] ✹
(ev) 
samsara 戝 ~/tmp/pyinstaller-single 
10755 ◯ : ls                                                                                                                                                                        
ev  test.py
(ev) 
samsara 戝 ~/tmp/pyinstaller-single 
10756 ◯ : pyinstaller test.py                                                                                                                                                       
32 INFO: PyInstaller: 3.2.dev0+gfd84293.mod
33 INFO: Python: 2.7.11
33 INFO: Platform: Linux-4.3.0-1-amd64-x86_64-with-debian-stretch-sid
34 INFO: wrote /home/kali/tmp/pyinstaller-single/test.spec
39 INFO: UPX is available.
41 INFO: Extending PYTHONPATH with paths
['/home/kali/tmp/pyinstaller-single', '/home/kali/tmp/pyinstaller-single']
41 INFO: checking Analysis
41 INFO: Building Analysis because out00-Analysis.toc is non existent
41 INFO: Initializing module dependency graph...
44 INFO: Initializing module graph hooks...
92 INFO: running Analysis out00-Analysis.toc
121 INFO: Analyzing /home/kali/tmp/pyinstaller-single/test.py
122 INFO: Looking for import hooks ...
127 INFO: Processing hook   hook-encodings.py
1903 INFO: Looking for ctypes DLLs
1903 INFO: Analyzing run-time hooks ...
1913 INFO: Looking for dynamic libraries
2170 INFO: Looking for eggs
2170 INFO: Python library not in binary depedencies. Doing additional searching...
2270 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
2277 INFO: Warnings written to /home/kali/tmp/pyinstaller-single/build/test/warntest.txt
2329 INFO: checking PYZ
2329 INFO: Building PYZ because out00-PYZ.toc is non existent
2330 INFO: Building PYZ (ZlibArchive) /home/kali/tmp/pyinstaller-single/build/test/out00-PYZ.pyz
2597 INFO: checking PKG
2597 INFO: Building PKG because out00-PKG.toc is non existent
2597 INFO: Building PKG (CArchive) out00-PKG.pkg
2657 INFO: Bootloader /home/kali/src/pyinstaller/PyInstaller/bootloader/Linux-64bit/run
2657 INFO: checking EXE
2657 INFO: Building EXE because out00-EXE.toc is non existent
2657 INFO: Building EXE from out00-EXE.toc
2667 INFO: Appending archive to ELF section in EXE /home/kali/tmp/pyinstaller-single/build/test/test
objcopy --add-section pydata=/home/kali/tmp/pyinstaller-single/build/test/out00-PKG.pkg /home/kali/tmp/pyinstaller-single/build/test/test
Traceback (most recent call last):
  File "/home/kali/tmp/pyinstaller-single/ev/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller', 'console_scripts', 'pyinstaller')()
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 756, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 702, in build
    exec(text, spec_namespace)
  File "<string>", line 26, in <module>
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 407, in __init__
    self.__postinit__()
  File "/home/kali/src/pyinstaller/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 564, in assemble
    raise SystemError("objcopy Failure")
SystemError: objcopy Failure
(ev) 
```

**Comment by matysek** [comment] 2016-03-08 22:26
@kalikaneko could you try to recompile the bootloader?

We probably forgot to do that for recent changes in the bootloader.

**Comment by kalikaneko** [comment] 2016-03-09 15:42
@matysek I have recompiled the bootloader, but the problem persists.

**Comment by htgoebel** [comment] 2016-03-10 08:15
This is curious, since *if* there is an error, both the error message and the return code should be printed.
Could you please try three things:
1) run the objcopy (shown just above the traceback) manually and also check the return code.
2) run pyinstaller with --log=DEBUG to get more output, esp. just before the error
2) Check if you have any unicode path related to this objcopy. (I can not spot

**Comment by kalikaneko** [comment] 2016-03-10 13:40
> Could you please try three things:

sure thing

> 1) run the objcopy (shown just above the traceback) manually and also check the return code.

it's shown by a print statement that I added to check.  with today's commit the error message is shown. Return code is 1: 

```
11171 ◯ : pyinstaller --clean test.py⏎
36 INFO: PyInstaller: 3.2.dev0+gb3674f2.mod
37 INFO: Python: 2.7.11+
37 INFO: Platform: Linux-4.4.0-1-amd64-x86_64-with-debian-stretch-sid
38 INFO: wrote /home/kali/tmp/pyinstaller-single/test.spec
42 INFO: UPX is available.
43 INFO: Removing temporary files and cleaning cache in /home/kali/.cache/pyinstaller
45 INFO: Extending PYTHONPATH with paths
['/home/kali/tmp/pyinstaller-single', '/home/kali/tmp/pyinstaller-single']
45 INFO: checking Analysis
45 INFO: Building Analysis because out00-Analysis.toc is non existent
45 INFO: Initializing module dependency graph...
47 INFO: Initializing module graph hooks...
102 INFO: running Analysis out00-Analysis.toc
128 INFO: Analyzing /home/kali/tmp/pyinstaller-single/test.py
130 INFO: Looking for import hooks ...
134 INFO: Processing hook   hook-encodings.py
1934 INFO: Looking for ctypes DLLs
1934 INFO: Analyzing run-time hooks ...
1942 INFO: Looking for dynamic libraries
2191 INFO: Looking for eggs
2192 INFO: Python library not in binary depedencies. Doing additional searching...
2277 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
2286 INFO: Warnings written to /home/kali/tmp/pyinstaller-single/build/test/warntest.txt
2337 INFO: checking PYZ
2337 INFO: Building PYZ because out00-PYZ.toc is non existent
2337 INFO: Building PYZ (ZlibArchive) /home/kali/tmp/pyinstaller-single/build/test/out00-PYZ.pyz
2616 INFO: checking PKG
2617 INFO: Building PKG because out00-PKG.toc is non existent
2617 INFO: Building PKG (CArchive) out00-PKG.pkg
2681 INFO: Bootloader /home/kali/src/pyinstaller/PyInstaller/bootloader/Linux-64bit/run
2682 INFO: checking EXE
2682 INFO: Building EXE because out00-EXE.toc is non existent
2682 INFO: Building EXE from out00-EXE.toc
2690 INFO: Executing - upx --best -q /home/kali/.cache/pyinstaller/bincache01_py27_64bit/run
2726 INFO: Appending archive to ELF section in EXE /home/kali/tmp/pyinstaller-single/build/test/test
DEBUG: objcopy --add-section pydata=/home/kali/tmp/pyinstaller-single/build/test/out00-PKG.pkg /home/kali/tmp/pyinstaller-single/build/test/test
DEBUG: RETCODE 1
Traceback (most recent call last):
  File "/home/kali/tmp/pyinstaller-single/env2/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller', 'console_scripts', 'pyinstaller')()
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 756, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 702, in build
    exec(text, spec_namespace)
  File "<string>", line 26, in <module>
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 407, in __init__
    self.__postinit__()
  File "/home/kali/src/pyinstaller/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 565, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: objcopy: error: the input file '/home/kali/tmp/pyinstaller-single/build/test/test' has no sections

(env2)
samsara 戝 ~/tmp/pyinstaller-single
11175 ◯ : objcopy --add-section pydata=/home/kali/tmp/pyinstaller-single/build/test/out00-PKG.pkg /home/kali/tmp/pyinstaller-single/build/test/test⏎
objcopy: error: the input file '/home/kali/tmp/pyinstaller-single/build/test/test' has no sections
(env2)
samsara 戝 ~/tmp/pyinstaller-single
11176 ◯ : echo  $?⏎
1
```

> 2) run pyinstaller with --log=DEBUG to get more output, esp. just before the error

here it goes:

```
11185 ◯ : pyinstaller --log=DEBUG --clean test.py                                                                                                                                  ⏎
31 INFO: PyInstaller: 3.2.dev0+gb3674f2.mod
31 INFO: Python: 2.7.11+
32 INFO: Platform: Linux-4.4.0-1-amd64-x86_64-with-debian-stretch-sid
32 INFO: wrote /home/kali/tmp/pyinstaller-single/test.spec
32 DEBUG: Testing for UPX ...
37 INFO: UPX is available.
38 INFO: Removing temporary files and cleaning cache in /home/kali/.cache/pyinstaller
40 DEBUG: script: /home/kali/tmp/pyinstaller-single/test.py
40 INFO: Extending PYTHONPATH with paths
['/home/kali/tmp/pyinstaller-single', '/home/kali/tmp/pyinstaller-single']
40 INFO: checking Analysis
40 INFO: Building Analysis because out00-Analysis.toc is non existent
40 INFO: Initializing module dependency graph...
42 INFO: Initializing module graph hooks...
44 DEBUG: Hidden import: codecs
96 DEBUG: Hidden import 'codecs' already found
97 INFO: running Analysis out00-Analysis.toc
97 DEBUG: Analyzing /home/kali/tmp/pyinstaller-single/env2/bin/python
114 DEBUG: Skipping libdl.so.2 dependency of python
115 DEBUG: Skipping libc.so.6 dependency of python
115 DEBUG: Skipping libutil.so.1 dependency of python
115 DEBUG: Skipping libpthread.so.0 dependency of python
115 DEBUG: Skipping libm.so.6 dependency of python
115 DEBUG: Adding libz.so.1 dependency of python from /lib/x86_64-linux-gnu/libz.so.1
115 DEBUG: Analyzing /lib/x86_64-linux-gnu/libz.so.1
128 DEBUG: Skipping libc.so.6 dependency of libz.so.1
128 INFO: Analyzing /home/kali/tmp/pyinstaller-single/test.py
129 INFO: Looking for import hooks ...
132 INFO: Processing hook   hook-encodings.py
132 DEBUG: Collecting submodules for encodings
137 DEBUG: - Found submodules: set(['encodings.cp932', 'encodings.johab', 'encodings.iso2022_jp_ext', 'encodings.iso8859_15', 'encodings.big5', 'encodings.cp1140', 'encodings.cp775', 'encodings.euc_jis_2004', 'encodings.utf_32_le', 'encodings.utf_7', 'encodings.euc_kr', 'encodings.mac_arabic', 'encodings.utf_8', 'encodings.cp037', 'encodings.base64_codec', 'encodings.big5hkscs', 'encodings.shift_jis', 'encodings.iso8859_9', 'encodings.iso8859_8', 'encodings.mac_romanian', 'encodings.iso8859_3', 'encodings.iso8859_2', 'encodings.iso8859_1', 'encodings.iso8859_7', 'encodings.iso8859_6', 'encodings.iso8859_5', 'encodings.iso8859_4', 'encodings.cp857', 'encodings.cp856', 'encodings.cp855', 'encodings.cp852', 'encodings.cp850', 'encodings.cp858', 'encodings', 'encodings.mac_iceland', 'encodings.gbk', 'encodings.shift_jis_2004', 'encodings.mac_greek', 'encodings.palmos', 'encodings.iso2022_jp', 'encodings.utf_8_sig', 'encodings.koi8_r', 'encodings.koi8_u', 'encodings.aliases', 'encodings.mac_farsi', 'encodings.cp1026', 'encodings.undefined', 'encodings.iso2022_jp_1', 'encodings.iso2022_jp_3', 'encodings.iso2022_jp_2', 'encodings.utf_16_le', 'encodings.gb2312', 'encodings.uu_codec', 'encodings.ptcp154', 'encodings.hz', 'encodings.iso2022_jp_2004', 'encodings.zlib_codec', 'encodings.tis_620', 'encodings.cp720', 'encodings.cp875', 'encodings.cp874', 'encodings.rot_13', 'encodings.bz2_codec', 'encodings.unicode_escape', 'encodings.punycode', 'encodings.mac_croatian', 'encodings.mac_centeuro', 'encodings.mac_roman', 'encodings.cp437', 'encodings.utf_16', 'encodings.cp737', 'encodings.utf_16_be', 'encodings.latin_1', 'encodings.utf_32', 'encodings.charmap', 'encodings.hp_roman8', 'encodings.cp1006', 'encodings.iso8859_16', 'encodings.cp424', 'encodings.iso8859_14', 'encodings.iso8859_13', 'encodings.iso8859_11', 'encodings.iso8859_10', 'encodings.cp500', 'encodings.unicode_internal', 'encodings.iso2022_kr', 'encodings.mac_turkish', 'encodings.mac_cyrillic', 'encodings.euc_jisx0213', 'encodings.euc_jp', 'encodings.cp1258', 'encodings.cp1257', 'encodings.cp1256', 'encodings.cp1255', 'encodings.cp1254', 'encodings.cp1253', 'encodings.cp1252', 'encodings.cp1251', 'encodings.cp1250', 'encodings.string_escape', 'encodings.utf_32_be', 'encodings.quopri_codec', 'encodings.cp949', 'encodings.cp950', 'encodings.hex_codec', 'encodings.mac_latin2', 'encodings.cp869', 'encodings.cp866', 'encodings.cp864', 'encodings.cp865', 'encodings.cp862', 'encodings.cp863', 'encodings.cp860', 'encodings.cp861', 'encodings.ascii', 'encodings.shift_jisx0213', 'encodings.gb18030', 'encodings.raw_unicode_escape', 'encodings.mbcs', 'encodings.idna'])
1932 DEBUG: Looking for egg data files...
1932 INFO: Looking for ctypes DLLs
1932 INFO: Analyzing run-time hooks ...
1945 INFO: Looking for dynamic libraries
1946 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
1965 DEBUG: Skipping libc.so.6 dependency of _hashlib.x86_64-linux-gnu.so
1965 DEBUG: Adding libcrypto.so.1.0.2 dependency of _hashlib.x86_64-linux-gnu.so from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
1965 DEBUG: Adding libssl.so.1.0.2 dependency of _hashlib.x86_64-linux-gnu.so from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
1965 DEBUG: Skipping libdl.so.2 dependency of _hashlib.x86_64-linux-gnu.so
1965 DEBUG: Skipping libpthread.so.0 dependency of _hashlib.x86_64-linux-gnu.so
1965 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
1978 DEBUG: Skipping libc.so.6 dependency of readline.x86_64-linux-gnu.so
1978 DEBUG: Skipping libpthread.so.0 dependency of readline.x86_64-linux-gnu.so
1978 DEBUG: Adding libreadline.so.6 dependency of readline.x86_64-linux-gnu.so from /lib/x86_64-linux-gnu/libreadline.so.6
1978 DEBUG: Adding libtinfo.so.5 dependency of readline.x86_64-linux-gnu.so from /lib/x86_64-linux-gnu/libtinfo.so.5
1978 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/resource.x86_64-linux-gnu.so
1998 DEBUG: Skipping libc.so.6 dependency of resource.x86_64-linux-gnu.so
1998 DEBUG: Skipping libpthread.so.0 dependency of resource.x86_64-linux-gnu.so
1998 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_multibytecodec.x86_64-linux-gnu.so
2011 DEBUG: Skipping libc.so.6 dependency of _multibytecodec.x86_64-linux-gnu.so
2011 DEBUG: Skipping libpthread.so.0 dependency of _multibytecodec.x86_64-linux-gnu.so
2011 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_cn.x86_64-linux-gnu.so
2028 DEBUG: Skipping libc.so.6 dependency of _codecs_cn.x86_64-linux-gnu.so
2028 DEBUG: Skipping libpthread.so.0 dependency of _codecs_cn.x86_64-linux-gnu.so
2028 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_jp.x86_64-linux-gnu.so
2042 DEBUG: Skipping libc.so.6 dependency of _codecs_jp.x86_64-linux-gnu.so
2042 DEBUG: Skipping libpthread.so.0 dependency of _codecs_jp.x86_64-linux-gnu.so
2042 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_tw.x86_64-linux-gnu.so
2059 DEBUG: Skipping libc.so.6 dependency of _codecs_tw.x86_64-linux-gnu.so
2059 DEBUG: Skipping libpthread.so.0 dependency of _codecs_tw.x86_64-linux-gnu.so
2059 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_kr.x86_64-linux-gnu.so
2072 DEBUG: Skipping libc.so.6 dependency of _codecs_kr.x86_64-linux-gnu.so
2072 DEBUG: Skipping libpthread.so.0 dependency of _codecs_kr.x86_64-linux-gnu.so
2072 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_iso2022.x86_64-linux-gnu.so
2099 DEBUG: Skipping libc.so.6 dependency of _codecs_iso2022.x86_64-linux-gnu.so
2099 DEBUG: Skipping libpthread.so.0 dependency of _codecs_iso2022.x86_64-linux-gnu.so
2099 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/bz2.x86_64-linux-gnu.so
2113 DEBUG: Skipping libc.so.6 dependency of bz2.x86_64-linux-gnu.so
2113 DEBUG: Skipping libpthread.so.0 dependency of bz2.x86_64-linux-gnu.so
2114 DEBUG: Adding libbz2.so.1.0 dependency of bz2.x86_64-linux-gnu.so from /lib/x86_64-linux-gnu/libbz2.so.1.0
2114 DEBUG: Analyzing /usr/lib/python2.7/lib-dynload/_codecs_hk.x86_64-linux-gnu.so
2134 DEBUG: Skipping libc.so.6 dependency of _codecs_hk.x86_64-linux-gnu.so
2134 DEBUG: Skipping libpthread.so.0 dependency of _codecs_hk.x86_64-linux-gnu.so
2134 DEBUG: Analyzing /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
2150 DEBUG: Skipping libc.so.6 dependency of libcrypto.so.1.0.2
2150 DEBUG: Skipping libdl.so.2 dependency of libcrypto.so.1.0.2
2151 DEBUG: Analyzing /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
2171 DEBUG: Skipping libc.so.6 dependency of libssl.so.1.0.2
2171 DEBUG: Skipping libdl.so.2 dependency of libssl.so.1.0.2
2171 DEBUG: Analyzing /lib/x86_64-linux-gnu/libreadline.so.6
2185 DEBUG: Skipping libc.so.6 dependency of libreadline.so.6
2186 DEBUG: Analyzing /lib/x86_64-linux-gnu/libtinfo.so.5
2203 DEBUG: Skipping libc.so.6 dependency of libtinfo.so.5
2203 DEBUG: Analyzing /lib/x86_64-linux-gnu/libbz2.so.1.0
2215 DEBUG: Skipping libc.so.6 dependency of libbz2.so.1.0
2216 INFO: Looking for eggs
2216 INFO: Python library not in binary depedencies. Doing additional searching...
2297 DEBUG: Adding Python library to binary dependencies
2297 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
2306 INFO: Warnings written to /home/kali/tmp/pyinstaller-single/build/test/warntest.txt
2322 INFO: Graph drawing written to /home/kali/tmp/pyinstaller-single/build/test/graph-test.dot
2350 INFO: Graph cross-reference written to /home/kali/tmp/pyinstaller-single/build/test/xref-test.html
2398 INFO: checking PYZ
2398 INFO: Building PYZ because out00-PYZ.toc is non existent
2398 INFO: Building PYZ (ZlibArchive) /home/kali/tmp/pyinstaller-single/build/test/out00-PYZ.pyz
2661 INFO: checking PKG
2662 INFO: Building PKG because out00-PKG.toc is non existent
2662 INFO: Building PKG (CArchive) out00-PKG.pkg
2712 DEBUG: Compiling /home/kali/src/pyinstaller/PyInstaller/loader/pyiboot01_bootstrap.py
2712 DEBUG: Compiling /home/kali/src/pyinstaller/PyInstaller/loader/pyiboot01_bootstrap.py
2716 DEBUG: Compiling /home/kali/tmp/pyinstaller-single/test.py
2716 DEBUG: Compiling /home/kali/tmp/pyinstaller-single/test.py
2721 INFO: Bootloader /home/kali/src/pyinstaller/PyInstaller/bootloader/Linux-64bit/run
2721 INFO: checking EXE
2721 INFO: Building EXE because out00-EXE.toc is non existent
2721 INFO: Building EXE from out00-EXE.toc
2728 INFO: Executing - upx --best -q /home/kali/.cache/pyinstaller/bincache01_py27_64bit/run
2769 INFO: Appending archive to ELF section in EXE /home/kali/tmp/pyinstaller-single/build/test/test
DEBUG: objcopy --add-section pydata=/home/kali/tmp/pyinstaller-single/build/test/out00-PKG.pkg /home/kali/tmp/pyinstaller-single/build/test/test
2778 DEBUG: objcopy returned 1
2778 DEBUG:
2778 DEBUG: objcopy: error: the input file '/home/kali/tmp/pyinstaller-single/build/test/test' has no sections

DEBUG: RETCODE 1
Traceback (most recent call last):
  File "/home/kali/tmp/pyinstaller-single/env2/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller', 'console_scripts', 'pyinstaller')()
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/kali/src/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 756, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/kali/src/pyinstaller/PyInstaller/building/build_main.py", line 702, in build
    exec(text, spec_namespace)
  File "<string>", line 26, in <module>
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 407, in __init__
    self.__postinit__()
  File "/home/kali/src/pyinstaller/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/home/kali/src/pyinstaller/PyInstaller/building/api.py", line 565, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: objcopy: error: the input file '/home/kali/tmp/pyinstaller-single/build/test/test' has no sections
```

>  Check if you have any unicode path related to this objcopy.

afaik there's not.

**Comment by kalikaneko** [comment] 2016-03-10 14:07
in case it's useful to debug this:

* using --no-upx lets the process finish, although the final binary is not functional. seems that using upx here results in an elf that confuses objcopy
```
 exe = checkCache(exe, strip=self.strip, upx=self.upx)
```
this binary complains however. I'm not sure if the .pkg it's looking for is the same thing that I copy over, but then it passes to another cryptic error:
```
samsara 戝 ~/tmp/pyinstaller-single 
11270 ◯ : dist/test/test                                                                                                                                                             
Cannot open self /home/kali/tmp/pyinstaller-single/dist/test/test or archive /home/kali/tmp/pyinstaller-single/dist/test/test.pkg
(env2) 
samsara 戝 ~/tmp/pyinstaller-single 
11271 ◯ : cp build/test/out00-PKG.pkg dist/test/test.pkg                                                                                                                           ⏎ 
(env2) 
samsara 戝 ~/tmp/pyinstaller-single 
11272 ◯ : dist/test/test                                                                                                                                                             
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'c' is not defined
pyiboot01_bootstrap returned -1
(env2) 
```

I also tried to force the execution of each of the following surrounding blocks in the conditional, but all of them lead to the same _bootstrap error above.

```
if not self.append_pkg:  
   BLOCK A
elif is_linux:
   BLOCK B
else:
    # Fall back to just append on end of file
    BLOCK C
```

I hope this helps isolating the problem, I wish I could understand more the internals of pyinstaller. Tell me if there's something more that I could try.

(Re. versions, using objcopy 2.26)

**Comment by htgoebel** [comment] 2016-03-11 17:17
I have no good idea. But
- if UPX corrupts the exe, this is not good
- It looks like you missed re-compiling the bootloader for the last test, otherwise the traceback would contain a filenema and not `"<string>"`. But this does not explain the error "NameError: name 'c' is not defined".

What you can try next:
 -Please do not install via `pip` but download the [archive](https://github.com/pyinstaller/pyinstaller/archive/develop.zip) or use git.
- Please check the file `PyInstaller/loader/pyiboot01_bootstrap.py`. It should not contain a `c` in the first line, but a comment.
- Ensure the bootloader is recompiled. 
- Then freeze your program using `--clean --no-upx --debug --log=DEBUG`

I hope this solves the issue.

**Comment by matysek** [comment] 2016-03-12 09:12
I am able to reproduce this issue:
- having just upx installed
- the issue is that `upx` is applied on the bootloader itself before anything is appended to it
- we should not apply upx for the bootloader `run` file in the first place

**Comment by matysek** [comment] 2016-03-12 12:40
Should be fixed.

**Closed by matysek** 2016-03-12 12:40 UTC
Labels: @medium, bootloader, develop, Linux
