### ISSUE TITLE
TypeError when adding a Windows version file 

### ISSUE THREAD

**Issue by EPeterE** [pyinstaller/pyinstaller#2189] opened 2016-09-12 14:01 UTC
Hi
I am trying to add a version file and I get this error. Anybody able to help?

The simple test script "test.py" is

>   import os
>   print(os.getcwd())

and building with

>    pyinstaller --version-file=version.txt "test.py"

The version file is the example provided by https://mborgerson.com/creating-an-executable-from-a-python-script

> VSVersionInfo(
>   ffi=FixedFileInfo(
>     # filevers and prodvers should be always a tuple with four items: (1, 2, 3, 4)
>     # Set not needed items to zero 0.
>     filevers=(96, 12, 19, 1),
>     prodvers=(4, 1, 2, 1),
>     # Contains a bitmask that specifies the valid bits 'flags'
>     mask=0x3f,
>     # Contains a bitmask that specifies the Boolean attributes of the file.
>     flags=0x0,
>     # The operating system for which this file was designed.
>     # 0x4 - NT and there is no need to change it.
>     OS=0x4,
>     # The general type of file.
>     # 0x1 - the file is an application.
>     fileType=0x1,
>     # The function of the file.
>     # 0x0 - the function is not defined for this fileType
>     subtype=0x0,
>     # Creation date and time stamp.
>     date=(0, 0)
>     ),
>   kids=[
>     StringFileInfo(
>       [
>       StringTable(
>         u'040904b0',
>         [StringStruct(u'CompanyName', u'Fuddy Duddies, Inc. 8 Flossie Dr. Arlington, VA 00001'),
>         StringStruct(u'ProductName', u'SILLINESS'),
>         StringStruct(u'ProductVersion', u'2, 0, 3, 0'),
>         StringStruct(u'InternalName', u'SILLINESS'),
>         StringStruct(u'OriginalFilename', u'silliness.exe'),
>         StringStruct(u'FileVersion', u'96, 12, 19, 1'),
>         StringStruct(u'FileDescription', u'Silly stuff'),
>         StringStruct(u'LegalCopyright', u'Copyright 2001 Fuddy Duddies, Inc.'),
>         StringStruct(u'LegalTrademarks', u'SILLINESS is a registered trademark of Fuddy Duddies, Inc.'),])
>       ]),
>     VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
>   ]
> )

The output is 

> 284 INFO: PyInstaller: 3.3.dev0+b78bfe5
> 285 INFO: Python: 3.4.0
> 288 INFO: Platform: Windows-8-6.2.9200
> 291 INFO: wrote C:\Python34\Scripts\test.spec
> 293 INFO: UPX is not available.
> 300 INFO: Extending PYTHONPATH with paths
> ['C:\Python34\Scripts', 'C:\Python34\Scripts']
> 301 INFO: checking Analysis
> 301 INFO: Building Analysis because out00-Analysis.toc is non existent
> 302 INFO: Initializing module dependency graph...
> 307 INFO: Initializing module graph hooks...
> 314 INFO: Analyzing base_library.zip ...
> 6014 INFO: Processing pre-find module path hook   distutils
> 9807 INFO: running Analysis out00-Analysis.toc
> 10042 INFO: Caching module hooks...
> 10073 INFO: Analyzing C:\Python34\Scripts\test.py
> 10073 INFO: Loading module hooks...
> 10073 INFO: Loading module hook "hook-distutils.py"...
> 10089 INFO: Loading module hook "hook-xml.py"...
> 10776 INFO: Loading module hook "hook-encodings.py"...
> 11026 INFO: Loading module hook "hook-pydoc.py"...
> 11089 INFO: Looking for ctypes DLLs
> 11089 INFO: Analyzing run-time hooks ...
> 11104 INFO: Looking for dynamic libraries
> 11526 INFO: Looking for eggs
> 11526 INFO: Using Python library C:\WINDOWS\system32\python34.dll
> 11526 INFO: Found binding redirects:
> []
> 11526 INFO: Warnings written to C:\Python34\Scripts\build\test\warntest.txt
> 11589 INFO: checking PYZ
> 11589 INFO: Building PYZ because out00-PYZ.toc is non existent
> 11589 INFO: Building PYZ (ZlibArchive) C:\Python34\Scripts\build\test\out00-PYZ.pyz
> 14448 INFO: checking PKG
> 14448 INFO: Building PKG because out00-PKG.toc is non existent
> 14448 INFO: Building PKG (CArchive) out00-PKG.pkg
> 14495 INFO: Bootloader C:\Python34\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
> 14495 INFO: checking EXE
> 14495 INFO: Building EXE because out00-EXE.toc is non existent
> 14495 INFO: Building EXE from out00-EXE.toc
> Traceback (most recent call last):
>   File "C:\Python34\Scripts\pyinstaller-script.py", line 11, in <module>
>     load_entry_point('PyInstaller==3.3.dev0+b78bfe5', 'console_scripts', 'pyinstaller')()
>   File "C:\Python34\lib\site-packages\PyInstaller__main__.py", line 90, in run
>     run_build(pyi_config, spec_file, *_vars(args))
>   File "C:\Python34\lib\site-packages\PyInstaller__main__.py", line 46, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, *_kwargs)
>   File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
>     exec(text, spec_namespace)
>   File "<string>", line 26, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\building\api.py", line 407, in **init**
>     self.**postinit**()
>   File "C:\Python34\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in **postinit**
>     self.assemble()
>   File "C:\Python34\lib\site-packages\PyInstaller\building\api.py", line 496, in assemble
>     versioninfo.SetVersion(tmpnm, self.versrsrc)
>   File "C:\Python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 558, in SetVersion
>     win32api.UpdateResource(hdst, pefile.RESOURCE_TYPE['RT_VERSION'], 1, vs.toRaw())
>   File "C:\Python34\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 161, in toRaw
>     nm = pywintypes.Unicode(u'VS_VERSION_INFO')
> TypeError: must be impossible<bad format char>, not str

I do NOT get an error if I do not add a version file.

Any help?
Thanks

**Comment by wssnail** [comment] 2017-01-04 10:00
Did you solve it?i have the same problem.

**Comment by EPeterE** [comment] 2017-01-04 19:23
No, sorry, I never solved it.

**Comment by htgoebel** [comment] 2017-06-02 13:32
1. Which version of pywintypes are are using? Please test a different version.
2. Have you tried using the current stable version of PyInstaller (3.2.1)?
3. Have you tried running this in you python interpreter:
```
import pywintypes
import win32api
pywintypes.Unicode(u'VS_VERSION_INFO')
```

**Comment by htgoebel** [comment] 2017-06-02 13:33
Seems to be a problem in pywintypes: https://sourceforge.net/p/pywin32/bugs/697/

**Comment by xoviat** [comment] 2017-06-02 23:17
This is resolved by #2623. I plan to resolve this issues in xoviat/win32core#23, but have not had the time to finish this yet.

**Comment by xoviat** [comment] 2017-06-02 23:19
Also, pywin32 [doesn't bear complete responsibility](https://github.com/pyinstaller/pyinstaller/pull/2623#issuecomment-303258317):

> https://github.com/pyinstaller/pyinstaller/pull/2623#issuecomment-303258317

**Comment by BoboTiG** [comment] 2021-01-13 18:46
I cannot reproduce with PyInstaller 4.2, moreover the problem is likely Python 2.7-only which is no more supported. Therefore I am closing the issue.

**Closed by BoboTiG** 2021-01-13 18:46 UTC
Labels: platform:Windows
