### ISSUE TITLE
_MEI Folder is not removed from the User's Temp if the program is stopped using Windows Terminal close button

### ISSUE THREAD

**Issue by CoMakar** [pyinstaller/pyinstaller#8700] opened 2024-07-31 08:35 UTC
_MEI Folder is not removed from the User's Temp if the program is stopped when closing the Windows Terminal using the close button 

> Windows Terminal: https://github.com/microsoft/terminal

Python: 3.11
Pyinstaller: 6.9.0
Platform: Windows 10 x64
Python installed from [python.org/downloads](https://python.org/downloads)

Steps to reproduce:
1. Freeze the following script in onefile mode:

```python
while True:
    print("Hello world!")
```

2. Run the frozen script using the Windows terminal.
3. Close the terminal using the close button
4. Created _MEI folder was not be removed.

Expected: _MEI folder is removed from the Temp
Actual: _MEI folder is not removed from the Temp

Default Windows CMD and Powershell work well.

**Comment by rokm** [comment] 2024-07-31 08:37
Duplicate of https://github.com/pyinstaller/pyinstaller/issues/8640.

**Closed as not planned by rokm** 2024-07-31 08:37 UTC
Labels: solution:duplicate
