### ISSUE TITLE
PyCrypto - ImportError with Crypto.Cipher._raw_ecb

### ISSUE THREAD

**Issue by daddywarblocks** [pyinstaller/pyinstaller#1983] opened 2016-05-10 17:12 UTC
**Version**
Windows 7 SP1 x86_64
Python 3.4.4 x86_64
Cryptodome 3.4.2
     [Cryptodome ](https://pycryptodome.readthedocs.io/en/latest/index.html) is a drop in replacement for PyCrypto. Installed precompiled binary using pip.

**test.py**

```
#!/usr/bin/env python

import Crypto.Cipher.AES

if __name__ == '__main__':
    print("run success")
```

**Build Command**
pyinstaller test.py --log-level=DEBUG -d -F

**Output**

```
C:\Users\Misha\Desktop\hasher\pycrypto_test\dist>test.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\Misha\Desktop\hasher\pycrypto_test\dist\test.exe
LOADER: homepath is C:\Users\Misha\Desktop\hasher\pycrypto_test\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\Misha\Desktop\hasher\pycrypto_test\dist\test.exe

LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\Misha\AppData\Local\Temp\_MEI14922
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\Misha\Desktop\hasher\pycrypto_test\dist\test.exe
LOADER: homepath is C:\Users\Misha\Desktop\hasher\pycrypto_test\dist
LOADER: _MEIPASS2 is C:\Users\Misha\AppData\Local\Temp\_MEI14922
LOADER: archivename is C:\Users\Misha\Desktop\hasher\pycrypto_test\dist\test.exe

LOADER: SetDllDirectory(C:\Users\Misha\AppData\Local\Temp\_MEI14922)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\Misha\AppData\Local\Temp\_MEI14922\test.exe.manif
est
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\Misha\AppData\Local\Temp\_MEI14922\python34.dll

LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\Misha\AppData\Local\Temp\_MEI14922\base_li
brary.zip;C:\Users\Misha\AppData\Local\Temp\_MEI14922
LOADER: sys.prefix is C:\Users\Misha\AppData\Local\Temp\_MEI14922
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename test.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\Misha\AppData\Local\Temp\_MEI14922\base_l
ibrary.zip;C:\Users\Misha\AppData\Local\Temp\_MEI14922
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\Crypto\Cipher\__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
  File "site-packages\Crypto\Util\_raw_api.py", line 168, in load_pycryptodome_r
aw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'
Failed to execute script test
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\Users\Misha\Desktop\hasher\pycrypto_test\d
ist\test.exe
```

**Extra Info**
Crypto.Cipher._raw_ecb is available in  C:\Python34\lib\site-packages\Crypto\Cipher\

**Comment by loretoparisi** [comment] 2016-08-01 22:08
This issue could be related to https://github.com/pyinstaller/pyinstaller/issues/2125 on MacOS X platform.

**Comment by zbuttram** [comment] 2016-09-09 23:39
Can confirm this same issue on Windows 10 x64 with Python 3.5.1 x64.

**Comment by arvindsree** [comment] 2016-10-17 19:17
Same issue is present on python 2.7.12 while using pyinstaller 3.2 on Ubuntu 14.04.5

**Comment by stephenrauch** [comment] 2016-10-17 19:44
If this is about CryptoDome, then it is a duplicate of #2125, and there is a fix at  #2226

**Comment by htgoebel** [comment] 2017-02-02 10:05
pycrypto is [officially dead](https://github.com/dlitz/pycrypto/issues/173) and [seriously buggy](http://lists.gnu.org/archive/html/guix-devel/2016-12/msg01007.html). Please move forward to an alternative. We ought not spend time fixing support for dead software.

**Closed by htgoebel** 2017-02-02 10:05 UTC

**Comment by wcraig2012** [comment] 2017-12-04 07:55
Has anyone solved the problem "OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'", but not the CryptoDemo problem?
