### ISSUE TITLE
3.1 does not collect direct import

### ISSUE THREAD

**Issue by dessant** [pyinstaller/pyinstaller#1780] opened 2016-01-19 05:02 UTC
I'm importing redis directly and it does work with 3.0, but fails with 3.1. I was testing with py 3.4.4 on win 10.

This is a list of redis modules collected by 3.0, none of them are there with 3.1:
```
 'redis': (1, 1232665, 618),
 'redis._compat': (0, 1234173, 1697),
 'redis.client': (0, 1255767, 32344),
 'redis.connection': (0, 1239963, 12585),
 'redis.exceptions': (0, 1233283, 890),
 'redis.lock': (0, 1288111, 4073),
 'redis.utils': (0, 1239278, 685),
```

Pachaged module:
```python
from redis import Redis

a = Redis()
```

Spec:
```python
# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['E:\\dev\\prs\\main\\test'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='a',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='a')

```

Runtime error:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'redis'
main returned -1

```

**Comment by dessant** [comment] 2016-01-19 07:04
Adding them to hiddenimports did not help either:
```python
             hiddenimports=['redis',
                            'redis._compat',
                            'redis.client',
                            'redis.connection',
                            'redis.exceptions',
                            'redis.lock',
                            'redis.utils'],
```

**Comment by htgoebel** [comment] 2016-01-19 11:29
Please check which version of setuptools you have installed. There have been problems reporte for setuptools 19.4, while downgrading to 19.2 solves the issue.

**Comment by dessant** [comment] 2016-01-19 13:48
Yes, i've hit that bug too and downgraded, 19.2 was used for this test.

**Comment by syradium** [comment] 2016-01-23 23:13
Had the same problem. Actually ANY module which starts with letters `re` is being totally ignored.
I had a module `resources` which was totally ignored by `pyinstaller`. By cutting module name I came to the conclusion that `re[any_text]` modules are ignored with the certain version of setuptools. That was in setuptools-12.0.5. Hower 19.2 gives the same error. 19.3 and 19.4 return:
```ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.```

But this is another issue.

**Comment by codewarrior0** [comment] 2016-01-23 23:33
This is almost certainly caused by the [regex here](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/depend/analysis.py#L291) matching any module that starts with 're', since `PY3_BASE_MODULES` contains 're'. I'm going to try tightening up the regex to only match module names exactly.

**Comment by syradium** [comment] 2016-01-23 23:38
@codewarrior0 Well, that was my initial guess as well. But naming a module something like `itertoolsz` does not reproduce this problem.

**Comment by codewarrior0** [comment] 2016-01-23 23:41
Hm? I don't see `itertools` in [`PY3_BASE_MODULES`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/compat.py#L506)..

**Comment by syradium** [comment] 2016-01-23 23:45
@codewarrior0 Oh, sorry. Yes. It's not there. My bad.

**Comment by htgoebel** [comment] 2016-01-24 19:17
> This is almost certainly caused by the regex here matching any module that starts with 're', since

The current regex does *not* match e.g. `redis`. This exclusion must be done somewhere else.

**Comment by htgoebel** [comment] 2016-01-24 19:21
Me fool: codewarrior0 just fixed the regexp :-)

**Comment by htgoebel** [comment] 2016-01-26 10:45
@dessant @syradium Does this now work using the current development head?

**Comment by dessant** [comment] 2016-01-26 11:20
@htgoebel yes, redis is now collected. :100: 

I do have a different error with master and the above example though:
```python
$ python ./dist/a/a.exe
  File "./dist/a/a.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file ./dist/a/a.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by syradium** [comment] 2016-01-26 11:53
@htgoebel yeah, with python 3.5.1 everything is fine.

**Comment by htgoebel** [comment] 2016-01-26 12:38
Tanks for the feedback. So I can close this issue.

@dessant Re. the encoding problem: a) this in a different issue and should go into a different ticket. b) the message says it all: The encoding header is missing in your script.

**Closed by htgoebel** 2016-01-26 12:38 UTC
Labels: @high

**Comment by dessant** [comment] 2016-01-26 12:40
@htgoebel i agree, it is a different issue.
