### ISSUE TITLE
lib no found ：api-ms-win-crt-*.dll

### ISSUE THREAD

**Issue by NobugHu** [pyinstaller/pyinstaller#2068] opened 2016-06-27 09:18 UTC

**Comment by NobugHu** [comment] 2016-06-27 09:22
python 3.5 X64
win10 X64
i have setup vcredist  2005\2008\2010\2012\2015
it also can not found api-ms-win-crt
and someone else have this problem ,too
what should i do?

87 INFO: Extending PYTHONPATH with paths
['E:\\pyinstaller-pyinstaller-8689a5d',
 'E:\\pyinstaller-pyinstaller-8689a5d\\guiRev2']
292 INFO: checking Analysis
296 INFO: Building Analysis because out00-Analysis.toc is non existent
300 INFO: Initializing module dependency graph...
308 INFO: Initializing module graph hooks...
312 INFO: Analyzing base_library.zip ...
3736 INFO: running Analysis out00-Analysis.toc
3792 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python.exe
3834 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python.exe
3885 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python.exe
3935 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python.exe
3982 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python.exe
4053 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4095 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4137 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4182 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4225 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4270 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4316 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4364 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4406 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4456 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4500 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4548 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Program Files (x86)\Python\python35.dll
4598 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\VCRUNTIME140.dll
4641 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\VCRUNTIME140.dll
4688 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\VCRUNTIME140.dll
4729 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\VCRUNTIME140.dll
4776 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Program Files (x86)\Python\VCRUNTIME140.dll
4782 INFO: Caching module hooks...
4791 INFO: Analyzing E:\pyinstaller-pyinstaller-8689a5d\guiRev2.py
4991 INFO: Loading module hooks...
4994 INFO: Loading module hook "hook-xml.py"...
5271 INFO: Loading module hook "hook-encodings.py"...
5418 INFO: Loading module hook "hook-pydoc.py"...
5418 INFO: Loading module hook "hook-pyttsx.py"...
5441 WARNING: Hidden import "drivers" not found!
5444 WARNING: Hidden import "drivers.dummy" not found!
5449 WARNING: Hidden import "drivers.espeak" not found!
5449 WARNING: Hidden import "drivers.nsss" not found!
5449 WARNING: Hidden import "drivers.sapi5" not found!
5449 INFO: Loading module hook "hook-_tkinter.py"...
5510 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_tkinter.pyd
5555 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_tkinter.pyd
5607 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_tkinter.pyd
5839 INFO: checking Tree
5839 INFO: Building Tree because out00-Tree.toc is non existent
5839 INFO: Building Tree out00-Tree.toc
5975 INFO: checking Tree
5976 INFO: Building Tree because out01-Tree.toc is non existent
5980 INFO: Building Tree out01-Tree.toc
6059 INFO: checking Tree
6061 INFO: Building Tree because out02-Tree.toc is non existent
6065 INFO: Building Tree out02-Tree.toc
6072 INFO: Looking for ctypes DLLs
6087 INFO: Analyzing run-time hooks ...
6097 INFO: Including run-time hook 'pyi_rth__tkinter.py'
6113 INFO: Looking for dynamic libraries
6163 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6207 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6251 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6293 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6337 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6379 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6432 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6478 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6525 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6580 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ssl.pyd
6633 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\unicodedata.pyd
6687 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\unicodedata.pyd
6729 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\unicodedata.pyd
6778 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ctypes.pyd
6820 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ctypes.pyd
6874 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_ctypes.pyd
6932 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\pyexpat.pyd
6976 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\pyexpat.pyd
7019 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\pyexpat.pyd
7065 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\pyexpat.pyd
7110 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\pyexpat.pyd
7161 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7204 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7249 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7292 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7337 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7389 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7438 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7479 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7527 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_hashlib.pyd
7580 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\select.pyd
7636 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_bz2.pyd
7679 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_bz2.pyd
7720 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_bz2.pyd
7767 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_bz2.pyd
7809 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_bz2.pyd
7857 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_lzma.pyd
7904 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_lzma.pyd
7958 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_socket.pyd
8006 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_socket.pyd
8060 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_tkinter.pyd
8103 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_tkinter.pyd
8156 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\_tkinter.pyd
8241 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8291 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8334 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8391 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8453 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8494 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8537 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8592 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tk86t.dll
8653 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
8696 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
8739 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
8790 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
8832 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
8879 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
8927 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
8971 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
9020 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Program Files (x86)\Python\DLLs\tcl86t.dll
9022 INFO: Looking for eggs
9024 INFO: Using Python library C:\Program Files (x86)\Python\python35.dll
9028 INFO: Found binding redirects:
[]
9047 INFO: Warnings written to E:\pyinstaller-pyinstaller-8689a5d\guiRev2\build\guiRev2\warnguiRev2.txt
9130 INFO: checking PYZ
9131 INFO: Building PYZ because out00-PYZ.toc is non existent
9134 INFO: Building PYZ (ZlibArchive) E:\pyinstaller-pyinstaller-8689a5d\guiRev2\build\guiRev2\out00-PYZ.pyz
10186 INFO: checking PKG
10188 INFO: Building PKG because out00-PKG.toc is non existent
10192 INFO: Building PKG (CArchive) out00-PKG.pkg
10236 INFO: Bootloader E:\pyinstaller-pyinstaller-8689a5d\PyInstaller\bootloader\Windows-64bit\run.exe
10242 INFO: checking EXE
10245 INFO: Building EXE because out00-EXE.toc is non existent
10248 INFO: Building EXE from out00-EXE.toc
10251 INFO: Appending archive to EXE E:\pyinstaller-pyinstaller-8689a5d\guiRev2\build\guiRev2\guiRev2.exe
10267 INFO: checking COLLECT
10270 INFO: Building COLLECT because out00-COLLECT.toc is non existent
10274 INFO: Building COLLECT out00-COLLECT.toc

**Comment by AndCycle** [comment] 2016-06-29 07:58
duplicate of https://github.com/pyinstaller/pyinstaller/issues/1566

**Comment by htgoebel** [comment] 2016-06-30 11:50
@AndCycle Thanks for spotting this as duplicate :-)

**Closed by htgoebel** 2016-06-30 11:50 UTC
Labels: duplicate, Windows
