### ISSUE TITLE
recursionError

### ISSUE THREAD

**Issue by krolaper** [pyinstaller/pyinstaller#7437] opened 2023-02-11 08:47 UTC
the error occurs if the project has `torch` and `torchvision` (no matter what code). My project is large, it is connected with artificial intelligence, there is no point in throwing off all the code. Everything worked before. Or maybe a reaction to a project that is too big.
```
pyinstaller version 5.7.0
pyinstaller-hook-contrib version 2022.15
torch version 1.13.1
torchvision version 0.14.1
```
if you follow the hints on error, the project will be packed, but after starting it, it will not be possible to complete it.

**Comment by rokm** [comment] 2023-02-11 11:23
Duplicate of #7434.

> if you follow the hints on error, the project will be packed, but after starting it, it will not be possible to complete it.

And without any indication what is going on at runtime, we cannot really help you.

**Closed as not planned by rokm** 2023-02-11 11:23 UTC
Labels: solution:duplicate
