### ISSUE TITLE
Can't make namespaces using pkg_resources.declare_namespace(__name__) work.

### ISSUE THREAD

**Issue by mishas** [pyinstaller/pyinstaller#2228] opened 2016-10-18 12:21 UTC
After reviewing all relevant bugs ([#502](https://github.com/pyinstaller/pyinstaller/issues/502) and all related), I was lead to believe the following scenario should work, but it doesn't:

My files:

```
./blah.py  // Contains: "import world.a ; import world.b"
./modules
./modules/bar
./modules/bar/world
./modules/bar/world/__init__.py  // Contains: "import pkg_resources; pkg_resources.declare_namespace(__name__)"
./modules/bar/world/b.py
./modules/foo
./modules/foo/world
./modules/foo/world/__init__.py  // Contains: "import pkg_resources; pkg_resources.declare_namespace(__name__)"
./modules/foo/world/a.py
```

I'm running: `pyinstaller --paths=modules/foo:modules/bar ./blah.py`

When running the executable file, I get:

```
Failed to execute script blah
Traceback (most recent call last):
  File "blah.py", line 7, in <module>
    import world.b
ImportError: No module named 'world.b'
```

I understand from that that it DID import world.a, but not world.b :(.

Interestingly enough, deleting the `__init__.py` files, makes everything work correctly, but in my project, I can not remove those (other tools depend on them).

I tried to change the contents of the `__init__.py` to: `from pkgutil import extend_path; __path__ = extend_path(__path__, __name__)`, but received the same error again :(.

I understood from the ticket above that it should work with both pkgutil and pkg_resources.
Please help.

I'm using PyInstaller 3.2 with python3 (installed using `pip3 install pyinstaller`). Also tried PyInstallers 3.0 and 3.1 -- same errors.

I'm running on Mac (MacOS Sierra), but also tried on Windows 10, with the same result.

**Comment by htgoebel** [comment] 2016-10-18 13:34
We have a test-case for this, please run `py.test tests/functional/test_import.py -k nspkg1` (requires pytest and psutils). If this passes, please check what differs in your code to the code in `tests/functional/modules/nspkg1-pkg/`.

Beside this: using `declare_namespace` is deprecated, Python 3 does not need this any longer, see https://www.python.org/dev/peps/pep-0420/. So If this is your code and its Pytho-3-only, I suggest removing these `__init__` files.

**Comment by mishas** [comment] 2016-10-18 17:46
Thank you Hartmut for the quick response.

As for the tests, I've ran them, and they seem to pass. I've also looked at them and tried to figure out the difference even before opening the ticket...

So, now I dug a bit deeper, and I think I've figured it out:
It works in the tests, because all the imports are EGGs.

I first removed the zipped eggs from the directory and the code (`nspkg1_bbb.egg` and `nspkg1_empty.egg`), the tests still passed.

Then I've renamed the packages (ran `mv tests/functional/modules/nspkg1-pkg/nspkg1_???{.egg,}` where ??? is `aaa` and `ccc`), fixed the code running the tests accordingly, and it started to fail!

Interestingly enough, just that extension does the difference!

(I've also tried to remove the `EGG-INFO` folder without removing the .egg suffix, and it failed with exception: "Missing 'Version:' header and/or PKG-INFO file").

Conclusion: This system only works for eggs.


About `declare_namespace` being deprecated: As mentioned in the previous ticket: "I can not remove those (other tools depend on them)". For example, pylint doesn't support code without any `__init__.py` files (I've opened a bug [here](https://github.com/PyCQA/pylint/issues/842), and it's closed as fixed in the main branch, but it's not released yet).


Thanks again, and thank you for a great product :)

**Comment by htgoebel** [comment] 2016-10-18 20:10
I forgot one point: Did you install the packages causing the error? Even "development mode" (`pip -e` should work, since this created the .egg-info data required.

**Comment by mishas** [comment] 2016-10-18 20:56
No, I haven't. It's not something I can install, it's all internal projects that I bring together using a build system. And - before you ask - I can't put them all in the same dir :(. (For the curious, I'm using bazel.io)

If the .egg-info is what's needed to make it work - I can probably create it for my project, I'm just surprised that it's needed at all - it seems like a weird (and undocumented) requirement. It works fine for all other options (no namespaces, or no `__init__.py` files without .egg-info, so what's the difference here?)

I would, obviously, prefer not to manually generate any .egg-info metadata, so please let me know if it's something you're going to look into (maybe it's somehow an easy fix?), otherwise, I guess I'll have to patch up my code somehow to work.

Thanks again!

**Comment by htgoebel** [comment] 2016-10-18 21:14
Try creating an egg-info using `python setup.py egg_info` in each of these packages' directory.

> I'm just surprised that it's needed at all - it seems like a weird (and undocumented) requirement.

We just assume you are using "installed" packages :-) And in this case a .egg-info is always available when namespace packages using `declare_namespace` are used.

> It works fine for all other options (no namespaces, or no `__init__.py` files without .egg-info, so what's the difference here?)

The difference is the way the namespace is set up. Using `declare_namespace` was (one of) the first approaches, and for PyInstaller there is no deterministic way to detect them. This is why we rely on egg-info here.

**Comment by mishas** [comment] 2016-10-19 07:07
> [...] Using declare_namespace was (one of) the first approaches [...].

Are there other approaches that do work, apart from removing the `__init__.py` file, or adding .egg-info? (as noted above, `pkgutil.extend_path` didn't work for me either).

Suggestion:
I know that complicating flags/configurations is usually a bad idea, but - what about adding an command line argument and/or spec file option for explicitly specifying "hidden" namespaces?

I know it sounds like a niche, but I think having different (internal?) projects of the form "company_name.projX" is more common than it seems...

**Comment by htgoebel** [comment] 2016-10-19 07:35
> Are there other approaches that do work, apart from removing the __init__.py file, or adding .egg-info? (as noted above, pkgutil.extend_path didn't work for me either).

You can try the .pth-file based approach, but I can't tell out ATM how this works. But just yesterday I've seen that PyInstaller/lib/modulegraph/modulegraph.py contains support for this.

But removing `the __init__` file is the way to go :-)

> I know that complicating flags/configurations is usually a bad idea, but - what about adding an command line argument and/or spec file option for explicitly specifying "hidden" namespaces?

I do not think we need this. You should always be able to "install" your packages somewhere: in an virtual environment, or using `--root` or by running `setup.py egg_info`. So there is a simple work-around without adding more code to PyInstaller.

**Comment by htgoebel** [comment] 2017-01-20 12:43
@mishas Is this still an issue with the new PyInstaller 3.2.1 release?

**Comment by mishas** [comment] 2017-01-22 23:41
The basic use case (described in the first message of this ticket) still doesn't work with version 3.2.1.

**Comment by htgoebel** [comment] 2017-02-02 14:58
Could you please submit a pull-request with a test-case in our test-suite which raises the error. This would help reproducing the problem and we'll need this test anyway. Thanks.

- The test-case should go into `tests/functional/test_import.py`, below the other namespace related tests. Suggested test-name: `test_nspkg4`.
- The file you listed in the first commend go into `tests/functional/modules/NAME-OF-TEST/foo` resp. `tests/functional/modules/NAME-OF-TEST/bar`
- Code like this (look at the otehr examples in that file):
```
    pathex = glob.glob(os.path.join(_MODULES_DIR, 'NAME-OF-TEST', '{foo,bar}'))
    pyi_builder.test_source(
        "import world.a ; import world.b",
        pyi_args=['--paths', os.pathsep.join(pathex)])
```

**Comment by htgoebel** [comment] 2017-08-25 10:16
Did I miss the pull-request with the test-case? Anyway, I'mm closing this now now, since without a test-case working in this is not feasible..

**Closed by htgoebel** 2017-08-25 10:16 UTC
Labels: modulegraph, support
