### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by rolfdstoll** [pyinstaller/pyinstaller#2194] opened 2016-09-15 16:31 UTC
Hello,
I am working with winpython-32bit and 64bit as well (3.5.2.1)
pyinstaller.exe --onefile --windowed C: \ ...\ sm.py gives me an error:
**RecursionError: maximum recursion depth exceeded.**

The script sm.py is using matplotlib (1.5.2). 
It works fine, when starting from Python (Spyder)

When compiling with pyinstaller (3.2) the aboth mentioned error occurs.

The critical code is the use of the plot-routine of matplotlib.

**import pylab as p**
 ... 
**p.plot(t, pss, 'g', t, a,'r', t, b,'b',linewidth=1)**
...

several other users have reported a similar error. Is there a solution on this?   

Thanks a lot

**Comment by rolfdstoll** [comment] 2016-09-20 18:37
this ist a simpified test-script which produces the aboth error:

import pylab as p
x = p.linspace(0, 20, 1000)  # 100 evenly-spaced values from 0 to 50
y = p.sin(x)
p.plot(x, y)
p.savefig("test" + '.png',dpi=300)

#======================================
script works without problems in python console
python is winpython 32-bit 3.5.2.1
list of installed modules is attached:
[list.txt](https://github.com/pyinstaller/pyinstaller/files/483361/list.txt)

Python-Version:  3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18)
attempt to compile the test-file to one exe with pyinstaller:
pyinstaller.exe --onefile --windowed C:\Users\...\sintest.py
causes RecursionError: maximum recursion depth exceeded
pyinstaller is latest development version: Pyinstaller-3.3.dev0+b78bfe5
from: https://github.com/pyinstaller/pyinstaller/archive/develop.zip

is there any help for this error?
=========================================#

**Comment by rolfdstoll** [comment] 2016-09-21 16:05
So I think pyinstaller has a big, unsolved problem with matplotlib.
But what is Python without matplotlib?

**Comment by xoviat** [comment] 2017-03-19 01:03
Duplicate #2194.

**Comment by htgoebel** [comment] 2017-11-12 10:39
As xoviat wrote: duplicate of #2426 :-)

As a work-around please add `import sys; sys.setrecursionlimit(10000)` near the top of your .spec-file.

**Closed by htgoebel** 2017-11-12 10:39 UTC
