### ISSUE TITLE
Access violation when running .exe in Windows (Data Execution Prevention)

### ISSUE THREAD

**Issue by zamora18** [pyinstaller/pyinstaller#3576] opened 2018-06-14 23:26 UTC
Hello, 

I have created a GUI (using PyQt4) that uses a 3rd party library [pylink](https://github.com/square/pylink). This library allows me to flash firmware onto an STM micro-controller using a [J-Link Programmer](https://www.segger.com/products/debug-probes/j-link/models/j-link-plus/) connected through USB to my computer. The program works great when developing in my IDE (PyCharm), but after bundling the GUI in an executable (using pyinstaller) I get this error (with varying locations 0x00____ ):

`WindowsError: exception: access violation writing 0x000000CE00000000`

This is the full error output:
```
Traceback (most recent call last):
  File "main_gui.py", line 87, in run
  File "main_gui.py", line 57, in _flash_binary
  File "build\bdist.win-amd64\egg\pylink\jlink.py", line 172, in wrapper
  File "build\bdist.win-amd64\egg\pylink\jlink.py", line 2021, in flash_file
WindowsError: exception: access violation writing 0x000000CE00000000
```
I have no problem accessing the 3rd party library, so I am fairly confident that I packaged the executable correctly and that the dll was loaded successfully. 

After having done some research I believe that the problem is that it is being denied access to memory because the bundled .exe has DEP ([Data Execution Prevention](https://support.microsoft.com/en-us/help/875352/a-detailed-description-of-the-data-execution-prevention-dep-feature-in)) protection. (See [this article](https://www.veil-framework.com/dep-pyinstaller/)).

I searched the pyinstaller FAQ and email list but did not find anything that helped me in regards to disabling DEP from pyinstaller. I also attempted to [turn off DEP in Windows](https://windowsreport.com/exception-access-violation-windows-10/) for my specific application, but I [cannot set DEP on 64-bit executables](https://www.kapilarya.com/you-can-not-set-dep-attributes-on-64-bit-executables). 

I have done a fair amount of [testing and review,](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) and when debugging I do not receive any relevant debug messages in the console when the code is executed.

More information on my setup:
* Software versions I am using:
  * python 2.7.14 Anaconda 64-bit
  * pyinstaller 3.3.1
  * pylink 0.0.10
* Platform and version
  * Windows 10 64-bit
* Minimal Example program:
  ```python
  jlink.flash_file('stm32f446re_led_blink_fast.bin', 0x0)
  ```

Thank you for your help.

**Comment by wxd9199** [comment] 2018-06-22 09:02
i have the same problem.....
at last.....
when is happened i execute 'os.system("start cmd /c JLinkSTM32.exe -SetDeviceFamily 2")'
i know this is not a good way to connect the device...

**Comment by htgoebel** [comment] 2018-06-26 09:18
For me this looks like an implementation issue in the JLink-Programmer interface. There should be no need to execute data for communicating via USB-port. Esp. the example @wxd9199 posted shows that this is caused by JLink.

I can not tell you why it works in PyCharm but not hen bundled. But I can not see how this is releated to PyInstaller. Thus I'm closing this.

**Closed by htgoebel** 2018-06-26 09:18 UTC

**Comment by zamora18** [comment] 2018-08-08 16:01
@wxd9199 I have tried your "fix" but it is still not working for me. What determines the `SetDeviceFamily` parameter? I am using a J-Link Plus programmer. Are you executing this after the exception is caught? It works in a bundled GUI?

**Comment by wl496928838** [comment] 2018-08-18 17:48
How do I solve it?

There seems to be no problem in using py2exe.
