### ISSUE TITLE
PyQt5 RHEL Compilation results in not loaded resources

### ISSUE THREAD

**Issue by jiri-otoupal** [pyinstaller/pyinstaller#5600] opened 2021-03-03 15:08 UTC
While running pyinstaller with these options i had these errors only on RHEL machine:

`pyinstaller --noconsole --onefile --icon=icon.ico --noconfirm --hidden-import=clipboard --hidden-import=pycrosskit main.py`

Errors:
```
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so)
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so)
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-emu-integration.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-emu-integration.so)
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-x11-integration.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-x11-integration.so)
```

But the main problem is that images and qml files are not loaded. Window is opened with gray pattern without anything else on it. I tried most of the things that i found on google but nothing seem to help.
The reason im trying to compile on RHEL is because there is older glibc version.

**Comment by rokm** [comment] 2021-03-03 17:05
Are you specifying paths to those resources (images and qmls) [as absolute paths, tied to sys._MEIPASS](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html?ld-library-path-libpath-considerations#using-file)?

Otherwise, please provide a minimal self-contained example that exhibits the problem.

**Comment by jiri-otoupal** [comment] 2021-03-03 18:16
Images and qmls are all in QRC and that qrc is converted to python file, so there are no absolute paths except qrc:/image.png

**Comment by jiri-otoupal** [comment] 2021-03-03 18:56
Here is the example:

Source trying to compile:

main.py


```

import sys
import PyQt5.QtQuick
import res
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import QGuiApplication
from PyQt5.QtQml import QQmlApplicationEngine


if __name__ == "__main__":
    app = QGuiApplication(sys.argv)
    engine = QQmlApplicationEngine()
    context = engine.rootContext()
    engine.load(QUrl("qrc:/main.qml"))
    if not engine.rootObjects():
        sys.exit(-1)
    sys.exit(app.exec_())
```

main.qml
```


import QtQuick 2.13
import QtQuick.Dialogs 1.0
import QtQuick.Window 2.13
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.11
import QtGraphicalEffects 1.0
import QtQuick.Timeline 1.0



Window {
    id: window
    width: 800
    height: 480
    visible: true
    color: "#0c226f"
    property int installProgress: 0
    title: qsTr("Hello World")
    maximumHeight: height
    maximumWidth: width

    minimumHeight: height
    minimumWidth: width
}
```

main.qrc
```

<RCC>
    <qresource>
        <file>main.qml</file>
    </qresource>
</RCC>
```

**Comment by rokm** [comment] 2021-03-04 12:54
I can't seem to reproduce this. Neither on RHEL7 nor RHEL8, both with manually compiled python 3.9, PyInstaller 4.2 and PyQt5 from pip (tested with 5.15.3 and 5.15.2). On both systems, the unfrozen and frozen applications display blue window with white "Some Text".

On RHEL7 I get the same error messages about `/lib64/libQt5EglFSDeviceIntegration.so.5` missing `Qt_5_PRIVATE_API`. This is caused by PyQt5 package not shipping `libQt5EglFSDeviceIntegration.so.5`, against which `egldeviceintegrations` plugins are linked, and so the system version is used. Which, on RHEL7, is too old (5.9.7). But these plugins are likely not used in your case, anyway (otherwise you'd be seeing runtime errors about them in both unfrozen and frozen version).

There is a slight chance that pulling in system `libQt5EglFSDeviceIntegration` is causing some other system Qt libraries being pulled in, which in turn causes the problem. I think the easiest way to test that is to temporarily remove `egldeviceintegrations` plugin directory from your PyQt5 installation. But I imagine I'd be seeing the same problem if that was the issue...

Therefore, can you please:
* rebuild the application with `pyinstaller --log-level DEBUG [...]` and attach the build log
* attach the `build/main/PKG-00.toc` file
* do (preferably a one-dir) build of the above test example, and upload the result somewhere so I can take a look at it.

**Comment by jiri-otoupal** [comment] 2021-03-04 18:02
Thank you for reply 

Here are the files and log:

`39 INFO: PyInstaller: 4.2
40 INFO: Python: 3.9.2
44 INFO: Platform: Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17
44 INFO: wrote /home/admin/Compilations/__In_progres__/uptimai_installer/uptim.spec/UptimAI_Installer.spec
46 INFO: UPX is not available.
47 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
161 INFO: Extending PYTHONPATH with paths
['/home/admin/Compilations/Installer',
 '/home/admin/Compilations/__In_progres__/uptimai_installer/uptim.spec']
164 INFO: checking Analysis
164 INFO: Building Analysis because Analysis-00.toc is non existent
164 INFO: Initializing module dependency graph...
165 INFO: Caching module graph hooks...
171 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
175 INFO: Analyzing base_library.zip ...
2764 INFO: Processing pre-find module path hook distutils from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2764 INFO: distutils: retargeting to non-venv dir '/usr/local/lib/python3.9'
6128 INFO: Caching module dependency graph...
6254 INFO: running Analysis Analysis-00.toc
6282 INFO: Analyzing /home/admin/Compilations/Installer/main.py
6331 INFO: Processing pre-safe import module hook win32com from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
22042 INFO: Processing module hooks...
22043 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22156 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22224 INFO: Loading module hook 'hook-PyQt5.QtQml.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22416 INFO: Loading module hook 'hook-PyQt5.QtQuick.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22604 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22747 INFO: Loading module hook 'hook-PyQt5.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22765 WARNING: Hidden import "sip" not found!
22765 INFO: Loading module hook 'hook-difflib.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22767 INFO: Excluding import of doctest from module difflib
22767 INFO: Loading module hook 'hook-distutils.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22769 INFO: Loading module hook 'hook-distutils.util.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22770 INFO: Excluding import of lib2to3.refactor from module distutils.util
22770 INFO: Loading module hook 'hook-encodings.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22837 INFO: Loading module hook 'hook-heapq.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22839 INFO: Excluding import of doctest from module heapq
22839 INFO: Loading module hook 'hook-lib2to3.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22865 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22866 INFO: Excluding import of test from module multiprocessing.util
22866 INFO: Excluding import of test.support from module multiprocessing.util
22866 INFO: Loading module hook 'hook-pickle.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22867 INFO: Excluding import of argparse from module pickle
22867 INFO: Loading module hook 'hook-sysconfig.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22876 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22877 INFO: Loading module hook 'hook-xml.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
22923 INFO: Loading module hook 'hook-PyQt5.QtNetwork.py' from '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks'...
23017 INFO: Looking for ctypes DLLs
23161 WARNING: library msvcrt required via ctypes not found
23161 INFO: Analyzing run-time hooks ...
23168 INFO: Including run-time hook '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
23173 INFO: Including run-time hook '/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
23179 INFO: Looking for dynamic libraries
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so)
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-emu-integration.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-emu-integration.so)
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-x11-integration.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-x11-integration.so)
/home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so: /lib64/libQt5EglFSDeviceIntegration.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyQt5/Qt/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so)
28888 INFO: Looking for eggs
28889 INFO: Using Python library /usr/local/lib/libpython3.9.so.1.0
28895 INFO: Warnings written to /home/admin/Compilations/__In_progres__/uptimai_installer/build/UptimAI_Installer/warn-UptimAI_Installer.txt
28928 INFO: Graph cross-reference written to /home/admin/Compilations/__In_progres__/uptimai_installer/build/UptimAI_Installer/xref-UptimAI_Installer.html
28988 INFO: checking PYZ
28988 INFO: Building PYZ because PYZ-00.toc is non existent
28988 INFO: Building PYZ (ZlibArchive) /home/admin/Compilations/__In_progres__/uptimai_installer/build/UptimAI_Installer/PYZ-00.pyz
40652 INFO: Building PYZ (ZlibArchive) /home/admin/Compilations/__In_progres__/uptimai_installer/build/UptimAI_Installer/PYZ-00.pyz completed successfully.
40659 INFO: checking PKG
40659 INFO: Building PKG because PKG-00.toc is non existent
40659 INFO: Building PKG (CArchive) PKG-00.pkg
77626 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
77679 INFO: Bootloader /home/admin/VENVS/Linux/UI/QT-Venv/lib/python3.9/site-packages/PyInstaller/bootloader/Linux-64bit/run
77679 INFO: checking EXE
77680 INFO: Building EXE because EXE-00.toc is non existent
77680 INFO: Building EXE from EXE-00.toc
77680 INFO: Appending archive to ELF section in EXE /home/admin/Compilations/__In_progres__/uptimai_installer/dist/UptimAI_Installer
78105 INFO: Building EXE from EXE-00.toc completed successfully.`
[files.zip](https://github.com/pyinstaller/pyinstaller/files/6085716/files.zip)

**Comment by rokm** [comment] 2021-03-04 18:20
Can you also upload `build/main/COLLECT-00.toc` and `build/main/Analysis-00.toc`, please?

**Comment by jiri-otoupal** [comment] 2021-03-04 18:34
I run the command again just to be sure there are all the requested files.

[files.zip](https://github.com/pyinstaller/pyinstaller/files/6085848/files.zip)

**Comment by rokm** [comment] 2021-03-04 19:19
Thanks! Those .tocs look alright to me - the Qt libraries are collected from PyQt5 directory instead of `/lib64` (except for `libQt5EglFsKmsSupport.so.5` and `libQt5EglFSDeviceIntegration.so.5` that are missing from `PyQt5`), so that's not the problem.

So I'm out of ideas right now. Perhaps you can turn on Qt's debug messages (e.g., for plugin loading, for qml imports, etc.) to see if you can find any hints in there? 

But you can also freeze the `main.py` example you posted above using your environment (in one-dir mode) and upload the whole resulting dist directory (you'll probably have to upload it somewhere else than github) so I can try running it on my machine and see if it behaves differently from the version frozen in my test environment.

**Comment by jiri-otoupal** [comment] 2021-03-04 20:23
Here are the [files](https://easyupload.io/zjj782) including environment.

Thank you for your time

**Comment by rokm** [comment] 2021-03-04 21:02
Hmmm... the frozen application in `dist` does not appear to be frozen on RHEL:
* its `libpython3.9.so.1.0` requires `GLIBC_2.25`, which rules out RHEL7 (with glibc 2.17), but it can be made to work in RHEL8
* the bundled GdkPixbuf is looking for loader files in `/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache`; the `/usr/lib/x86_64-linux-gnu` path scheme can be found on Debian/Ubuntu but not RHEL

So it seems to me this was build on Debian or Ubuntu or their derivative. But it runs correctly on RHEL8, once you remove bundled `libfontconfig.so.1`, `libfreetype.so.6` and `libgdk_pixbuf-2.0.so.0` - it displays blue window, with "It works" white text and the green check mark image.

Also, the QML is not being loaded from qrc (but the image is), so it needs to be copied to application's dir:
```python
engine.load(QUrl("main.qml"))
``

**Comment by jiri-otoupal** [comment] 2021-03-05 00:54
I had compiled it on ubuntu 18.04 so far it has the same problem with not showing anything as a RHEL 7, i can compile it on rhel 7 as well but this system has the same problem.
[Here](https://gofile.io/d/FfxYDE) are the files with repaired loading of qml file but it does the same.
I removed the files you said that caused it working on RHEL 8 but it does not work on Ubuntu 18.04 neither RHEL 7 i need to use older glibc for compatibility to older systems.

**Comment by rokm** [comment] 2021-03-09 17:56
> I had compiled it on ubuntu 18.04 so far it has the same problem with not showing anything as a RHEL 7, i can compile it on rhel 7 as well but this system has the same problem.

So is this issue about resources not loading when running on the same kind of the system as the one you're freezing on, or not loading when you move to a different system? 

Because when you move to a different distribution (or even different version of the same distribution), you quickly hit on different limitations w.r.t. versions of system libraries. One such problem is `glibc` being too old on the target system (and thus bundled `libpython` not loading), but you can just as easily hit the reverse problem, where the bundled `libstdc++.so` is too old and prevents the system's DRI drivers to load. So you end up without valid OpenGL context, which which may crash Qt/QML applications, but can probably also result in other inconsistent behavior as well.

For the reference, here are the results of my tests with Ubuntu 18.04, RHEL7 and RHEL8 (all done in VirtualBox, so `vmwgfx_dri.so` DRI driver is used. If you use a non-virtual system with binary NVIDIA driver, the issue with DRI drivers not loading might not pop up).

# 1. Freezing on Ubuntu 18.04 (Bionic Beaver)

## 1.1 Running on Ubuntu 18.04

Works OK.

## 1.2 Running on RHEL7

Doesn't work due to system glibc being too old, and lacking symbols required by bundled `libpython` (`GLIBC_2.25` symbol)

## 1.3 Running on RHEL8

Crashes at startup, can be fixed:

Force system's `fontconfig` and `freetype` via LD_PRELOAD (or by removing bundled versions).

There's also a warning about `gdk-pixbuf` due to distribution-specific behavior (search paths):
```
(main:63106): GdkPixbuf-WARNING **: 18:17:15.848: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
```
which is also silenced by forcing system version via `LD_PRELOAD`.

So the final command-line is:
`LD_PRELOAD=/usr/lib64/libfontconfig.so.1:/usr/lib64/libfreetype.so.6:/usr/lib64/libgdk_pixbuf-2.0.so.0 ./main`

# 2. Freezing on RHEL7

(Using manually compiled python 3.9.2 to avoid complications with RH SCL python 3.6)

## 2.1 Running on Ubuntu 18.04

Crashes at startup as it cannot load DRI driver and fails to get OpenGL context.

This is because bundled `libstdc++.so.6` from RHEL7 is too old, and lacks symbols required by DRI drivers, so it prevents them from loading.

Solved by forcing system version:
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./main`

There's a warning about `gdk-pixbuf` that's symmetric to the one we've seen under 1.3, and is solved in the same way:
```
(main:8024): GdkPixbuf-WARNING **: 18:33:32.424: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
```

So the final command-line is:
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 ./main`

## 2.2 Running on RHEL7

Works OK.

## 2.3 Running on RHEL8

Crashes at startup as it cannot load DRI driver and fails to get OpenGL context.

This is because bundled `libstdc++.so.6` from RHEL7 is too old, and it prevents the DRI driver from loading.

Solved by system version:
`LD_PRELOAD=/usr/lib64/libstdc++.so.6 ./main`

# 3. Freezing on RHEL8

## 3.1 Running on Ubuntu 18.04

Doesn't work due to system glibc being too old, and lacking symbols required by bundled `libpython` (`GLIBC_2.28` symbol)

## 3.2 Running on RHEL7

Doesn't work due to system glibc being too old, and lacking symbols required by bundled `libpython` (`GLIBC_2.28` symbol)

## 3.3 Running on RHEL8

Works OK.

**Comment by bwoodsend** [comment] 2021-03-09 21:36
Would the solution not then be to run PyInstaller on something really old then delete the `dist/main/libstdc++.so.6` so that the system one will be loaded? I believe any Linux distro should have its own copy and that it should always be preferred. I've manged to do this by building on a Centos 7 docker image.

**Comment by rokm** [comment] 2021-04-18 11:55
I'm going to close this, because as indicated above, I cannot reproduce this issue for any combination of the distributions that came up during discussion. If you have any other details that might help reproducing the problem and thus finding its cause, feel free to post them here, and we'll revisit the issue.

**Closed by rokm** 2021-04-18 11:55 UTC
