### ISSUE TITLE
[1969296] Error loading Python lib '/tmp/_MEIruWkD7/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIruWkD7/libpython3.9.so.1.0)

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [pyinstaller/pyinstaller#7542] opened 2023-04-05 16:17 UTC
[1969296] Error loading Python lib '/tmp/_MEIruWkD7/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIruWkD7/libpython3.9.so.1.0)

I want to use Github Action to publish my Python program, which uses pyinstaller for packaging. But I found that it cannot run on other Linux machines. What should I do to make it run properly. Here is the yml file content for my github action

name: Build and Package

on:

push:

branches:

main
jobs:

build:

runs-on: ubuntu-latest

steps:

name: Checkout code
uses: actions/checkout

name: Set up Python
uses: actions/setup-python

with:

python-version: '3.9'

name: Install dependencies
run: |

python -m pip install --upgrade pip

pip3 install -r requirements.txt

name: Build package
run: |

pyinstaller iotd.py --hidden-import tendo --hidden-import yaml --hidden-import paramiko --hidden-import prettytable --hidden-import ruamel.yaml --hidden-import rich --hidden-import rich.progress --hidden-import logzero --hidden-import tqdm --add-data 'cluster/:cluster' --add-data 'tools/:tools' --add-data 'exception/*:exception' --onefile --runtime-tmpdir /tmp

name: Copy files to iotd/sbin and iotd/config
run: |

mkdir -p iotd/sbin

mkdir -p iotd/config

cp -r dist/* iotd/sbin/

cp -r config/* iotd/

name: Upload artifacts
uses: actions/upload-artifact

with:

name: iotd

path: ./ iotd

**Comment by rokm** [comment] 2023-04-05 16:21
Duplicate of #7541.

**Closed as not planned by rokm** 2023-04-05 16:21 UTC
Labels: solution:duplicate
