### ISSUE TITLE
ImportError: DLL load failed while importing _ssl: 找不到指定的模块。

### ISSUE THREAD

**Issue by kingmo888** [pyinstaller/pyinstaller#7510] opened 2023-03-21 12:53 UTC
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(5.9.0 and 5.6.1)```
* Version of Python: Python3.10
* Platform: Win10
* How you installed Python: miniconda3（version 2023.03 base python3.10）
* Did you also try this on another platform? Does it work there?
* python3.7+5.6.1  or python3.11+5.6.1，When using pyinstaller to compile exe, it is completely normal.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [y ] start with clean installation
  * [y ] use the latest development version
  * [y ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
Traceback (most recent call last):
  File "core2.py", line 30, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "rqdatac\__init__.py", line 21, in <module>
    __go()
  File "rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "importlib\__init__.py", line 126, in import_module
  File "D:\新建文件夹\run\dist\ui\rqdatac\services\live_md_client.py", line 4, in <module>
    import ssl
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "ssl.py", line 99, in <module>
ImportError: DLL load failed while importing _ssl: 找不到指定的模块。

```

In a feedback environment, there is no problem running Python scripts directly.
"I tried to import ssl in the script or hide imports=['ssl '] in the spec file, but the problem couldn't be resolved.".
Also found in the root directory of the compiled dist folder_ Ssl.pyd file.
As mentioned earlier, there is no problem with both py37 and py311, and no changes have been made. There is no problem running python scripts directly in a minimal installation environment of python 3.10, but compiling an exe using pyinstaller cannot be executed.

**Comment by bwoodsend** [comment] 2023-03-21 14:07
Sounds like a duplicate of #7484.

**Comment by kingmo888** [comment] 2023-03-21 14:18
> Sounds like a duplicate of #7484.

I have searched for all scenarios using the keyword "DLL load failed while importing _ssl".
dissimilarity,
His final solution was to include fastapi.
This one is not applicable to me (I have tried it before, and I have no problems with py37/py311. The spec scripts are the same.)

**Comment by bwoodsend** [comment] 2023-03-21 14:21
The fastapi bit was a separate issue. The fix for the `_ssl` issue was to not use unsupported anaconda.

**Comment by kingmo888** [comment] 2023-03-21 14:51
> The fastapi bit was a separate issue. The fix for the `_ssl` issue was to not use unsupported anaconda.

Yes, fastapi has nothing to do with this issue.
The miniconda3 I used was just released on 3.20, and I don't know if it is supported.
In addition, when I used the same operation on miniconda3 (py37)/and the original python 3.11.1, there was no problem.

**Comment by bwoodsend** [comment] 2023-03-21 15:39
No version of anaconda or miniconda is supported by PyInstaller. They're all a ridiculous amount of trouble for PyInstaller to support and invariably create bloated and untestable applications.

**Comment by rokm** [comment] 2023-03-21 16:53
>  Also found in the root directory of the compiled dist folder_ Ssl.pyd file.

It is not the `_ssl.pyd` extension per-se that is problematic, but rather one of its dependencies (`python310.dll`, `vcruntime140.dll`, `libcrypto-1_1-x64.dll`, `libssl-1_1-x64.dll`). Can you check if these are all collected? You can also use Dependency Walker or a similar tool to check if all imports of a particular shared library/extension are available. 

You can also check `build/<name>/Analysis-00.toc` file to see where these files are collected from - are they collected from the correct conda environment or from somewhere else?

That said, I cannot reproduce this. What version of python 3.10 are you using? 

If the problem can be reproduced with the following simple program
```python
import ssl
print(ssl)
```
can you make a onedir build and upload it somewhere, so I can take a look at what libraries are collected (please include both the resulting  `build` and `dist` directory in the archive).

**Closed as completed** 2023-03-22 02:11 UTC
Labels: triage
