### ISSUE TITLE
Bundling module "waitress" which is inside a virtual environment

### ISSUE THREAD

**Issue by rushendranadh** [pyinstaller/pyinstaller#3570] opened 2018-06-12 05:41 UTC
Module "waitress" is not getting bundled with my application when installed the module inside virtual environment.
Same thing is working fine when I install the module globally.

**Comment by htgoebel** [comment] 2018-06-12 06:55
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

I'm closing this for now, since we have lot of issues with hat too less information. I'll reopen if you provide enough details.

**Closed by htgoebel** 2018-06-12 06:55 UTC

**Comment by rushendranadh** [comment] 2018-06-12 07:46
This is the spec file which I am using to generate an exe.
Using command "pyinstaller --onefile --clean <spec_file>"
[pyinstaller_local.txt](https://github.com/pyinstaller/pyinstaller/files/2093018/pyinstaller_local.txt)

My run.py looks something like this

`from waitress import serve`
`def main(debug, host, port, use_reloader=False):
    initialize_app(app)
    log.info('>>>>> Starting server at http://{} <<<<<'.format(app.config['HOST_NAME']))
    webbrowser.open('http://%s'%app.config['HOST_NAME'], new=0, autoraise=True) 
    serve(app, listen=host+':'+str(port))`

**Comment by rushendranadh** [comment] 2018-06-13 13:05
@htgoebel When I run(double click) the application it is closing the application with "import error" saying "No module found: waitress"

**Comment by tallforasmurf** [comment] 2018-06-13 16:01
This looks as if that module is simply not being found by PyInstaller. When you run PyInstaller there are a lot of messages. Do any of them mention "module not found: waitress"? (Or, look in the file build/run/warnrun.txt for all warnings.)

**Comment by htgoebel** [comment] 2018-06-13 16:33
Since "waitress" is a top-level import of your top-level script, this looks like your environment is not set up correctly. Please check that you are running the pyinstaller installed into the same virtual environment you used for testing and make sure waitress is installed there, too.
