### ISSUE TITLE
Python3 no longer supports MERGE?

### ISSUE THREAD

**Issue by synapse211** [pyinstaller/pyinstaller#1344] opened 2015-07-22 13:26 UTC
Hey,

I have been testing the python3 branch with Kivy, all is well except for when I try to use MERGE:

name 'MERGE' is not defined

Probably this is intentional, I searched for news regarding it's removal but I couldn't find anything. If it is indeed getting removed what can I do to produce multiple-executable builds? Can I just merge the two builds or is there some other magic that I need to do?

Absolutely love the py3 support by the way.

Gergely

**Comment by matysek** [comment] 2015-07-22 20:53
Hey, MERGE should be still supported.

This issue is related to a recent change where we defined a dict() with names for .spec file. MERGE was probably not added to that dict().

**Comment by matysek** [comment] 2015-07-23 20:51
The message you were getting should be fixed.

**Comment by htgoebel** [comment] 2015-07-24 07:09
I'm closing the issue. @synapse211 If the issue is not solved in the latest python3 HEAD, please reopen the ticket.

**Closed by htgoebel** 2015-07-24 07:09 UTC
Labels: @high, PY3
