### ISSUE TITLE
byte-compiled scripts

### ISSUE THREAD

**Issue by rgacote** [pyinstaller/pyinstaller#1847] opened 2016-02-29 15:54 UTC
Python 3.5.1 on OS X (not yet tried other environments). 
Pyinstaller version 3.1.1
Set logging formatter as such:

```python:
    formatter = logging.Formatter(
        "%(asctime)s %(levelname)s %(filename)s %(funcName)s:%(lineno)d "
        "%(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
```
%(filename)s could also be %(module)s)

When run from source, the filename (or module), function name, and line number all log
When run from Pyinstaller build, the filename (or module) logs as `<string>`.

--Ray

**Comment by htgoebel** [comment] 2016-02-29 16:35
I tries reproducing this. For me this happens if the message is logged in the main script. Messages logged from some imported module are okay. Can you verify this?

**Comment by htgoebel** [comment] 2016-02-29 17:51
Okay, I tracked this down:
- We use `PyRun_SimpleString` to run the script
- `PyRun_SimpleString` is just a thin wrapper for `PyRun_StringFlags`, which *hardcoded* uses the filename `<string>`, see https://hg.python.org/releases/2.7.11/file/tip/Python/pythonrun.c#l884
- Thus setting `__main__.__file__` is of no use here.

What others do:
- py2exe stores a list of marshalled code-objects and uses `PyEval_EvalCode` each of them (see `run_script` at the end of https://sourceforge.net/p/py2exe/svn/HEAD/tree/trunk/py2exe/source/start.c)
- cx_freeze uses an importer (`zipimport`) to get the code and then also `PyEval_EvalCode` (see https://sourceforge.net/p/py2exe/svn/HEAD/tree/trunk/py2exe/source/start.c)
- bb_freeze does the same (except the logic is implemented in Python). (Source is hidden in an archive at https://pypi.python.org/pypi/bbfreeze-loader/.
- py2app seams to not use an archive: it uses `PyRun_SimpleFile` on a normal file (opened with `fopen()` (see https://bitbucket.org/ronaldoussoren/py2app/src/79e351a5f029f80a2505ed2e2ff7a57a896a1a8f/py2app/apptemplate/src/main.c?at=default&fileviewer=file-view-default#main.c-1048)

Side-note: cx_freeze's trick of using `zipimport` is quite interesting. But we can not use it since `zipimport` needs the name of a zipfile, while we a) have our own format and b) have the data embedded into the executable.

Assigneing to @codewarrior0 since this requires lager changes to the bootloader.

**Comment by codewarrior0** [comment] 2016-03-01 11:12
Roger that. The `PyEval_EvalCode` approach used by py2exe looks like the best fit.

I will need to:

- Change the startup code in `pyi_launch.c` to call `PyEval_EvalCode` instead of `PyRun_SimpleString`
- Change `CArchiveWriter` to compile any `PYSOURCE` entries to bytecode and write that to the archive (the same way `ZLibArchiveWriter` does, also stripping paths from the compiled bytecode).

This will make `PYSOURCE` kind of a misnomer, but I'm in no hurry to rename it since it's part of the public TOC API.

**Comment by htgoebel** [comment] 2016-03-01 15:22
I renamed this issue :-)
@codewarrior0 
- py2exe collects all scripts in one python lists, which is marshalled and unmarshalled as one object. IMHO this is a good idea.
- The python3 code is in https://sourceforge.net/p/py2exe/svn/HEAD/tree/trunk/py2exe-3/source/start.c. On a first glance the `run_script()` function  it looks the same.
- Do you want me to take care of the CArchiveWriter-part? So you could concentrate on the bootloader part?

**Comment by rgacote** [comment] 2016-03-02 19:27
I appreciate the incredibly quick research and response to this issue.

**Comment by codewarrior0** [comment] 2016-03-03 03:09
> py2exe collects all scripts in one python lists, which is marshalled and unmarshalled as one object. IMHO this is a good idea.

Eh, I don't think changing this is worth the effort. The main reason py2exe does it like this is because their counterpart to our CArchive is a much simpler struct (stored as a Windows resource) with the marshalled list appended to it. Among other things, py2exe's simple struct doesn't supply runtime options like `-v` and `-u` (and I would like to add `-i` for debugging purposes...). Though, after seeing the problem in #1812, storing the CArchive itself as a Windows resource to make it formally part of the executable's structure might be a good idea.

> Do you want me to take care of the CArchiveWriter-part?

No thanks, I think I've got this under control.

**Comment by codewarrior0** [comment] 2016-03-03 06:55
I was a bit alarmed when I saw that the `__main__` module's namespace was being reused for all of the startup scripts. I tried changing that to clear the namespace, but this resulted in even more changes to the Python bootstrap modules and scripts so I decided to split it off into another branch for now. 

The byte-compiled startup scripts work, at least for the simple helloworld test, so now I'm waiting for Travis to give me the all clear.

**Comment by codewarrior0** [comment] 2016-03-03 07:18
The test failures on Travis seem to stem from the fact that some dynamically-generated test sources are written to filenames containing more than one period. This makes them invalid as Python module names. The fix for this should be entirely on the side of the test suite.

**Comment by htgoebel** [comment] 2016-03-03 22:09
@codewarrior0 Thanks for implementing this so quickly :-)
Re. python list of marshalled objects: You are right, your changes are much less invasive than if we'd used a list.

**Closed by htgoebel** 2016-03-03 22:09 UTC
Labels: @medium, bootloader, v3.1.1

**Comment by codewarrior0** [comment] 2016-03-04 01:08
I haven't merged my changes yet. ;)

Last night, I was stuck on a test failure in `test_pandas_extension` that looks suspiciously like the problem in #1848:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/travis/build/codewarrior0/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "pandas/__init__.py", line 13, in <module>
ImportError: C extension: No module named tz not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
test_pandas_extension returned -1
```

Comparing the logs from my failed run and the passing run on `develop` shows that my run is using dateutil-2.5.0, while `develop` is using dateutil-2.4.2 instead.

Since this is the only failing test, I'm going to go ahead and merge my changes, and see if `develop` keeps using the older dateutil and if the test passes in that case.
