### ISSUE TITLE
Segmentation fault (core dumped) in Linux 2.6

### ISSUE THREAD

**Issue by Koushik667** [pyinstaller/pyinstaller#5364] opened 2020-12-04 08:01 UTC
## Description of the issue : 
I am using pyinstaller in RHEL7 and converting the program to exe,the exe runs fine in that machine,But Segmentation fault occurs when i try to run the exe in linux 2.6(where i want it to run actually).

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: e.g. 3.7 : ```3.6.7```
* Platform: e.g GNU/Linux (distribution), Windows (language settings), OS X, conda, FreeBSD - ```Linux 2.6```
* Did you also try this on another platform? Does it work there? ```YES works fine in rhel7 where the exe file is created ```

* try the latest development version, using the following command:

```TRIED NEW VERSION FROM pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip , SAME ISSUE ```

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
print("Hello_world")
from skmultiflow.trees import HATT

```

### Stacktrace / full error message

```
The behaviour is strange,sometimes it runs successfully without faulting and sometimes segmentation fault after the execution of programme,have pasted traces for all these cases below.

First Case:
# code object from '/var/tmp/sample/sysconfig.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f9639007a90>
import 'pkg_resources' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f963cd78320>
[11530] LOADER: Running pyi_rth__tkinter.py
[11530] LOADER: Running pyi_rth_mplconfig.py
[11530] LOADER: Running sample.py
Hello_world
# skmultiflow not found in PYZ
# code object from '/var/tmp/sample/skmultiflow/__init__.pyc'
# skmultiflow.bayes not found in PYZ
# code object from '/var/tmp/sample/skmultiflow/bayes/__init__.pyc'
# skmultiflow.bayes.utils not found in PYZ
# code object from '/var/tmp/sample/skmultiflow/bayes/utils.pyc'
import 'skmultiflow.bayes.utils' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f9638fad518>
# skmultiflow.bayes.naive_bayes not found in PYZ
# code object from '/var/tmp/sample/skmultiflow/bayes/naive_bayes.pyc'
# numpy not found in PYZ
# code object from '/var/tmp/sample/numpy/__init__.pyc'
# numpy._globals not found in PYZ
# code object from '/var/tmp/sample/numpy/_globals.pyc'
import 'numpy._globals' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f9638fb7940>
# numpy.__config__ not found in PYZ
# code object from '/var/tmp/sample/numpy/__config__.pyc'
import 'numpy.__config__' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f9638fb7cc0>
# numpy.version not found in PYZ
# code object from '/var/tmp/sample/numpy/version.pyc'
import 'numpy.version' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f9638fb7e80>
# numpy._distributor_init not found in PYZ
# code object from '/var/tmp/sample/numpy/_distributor_init.pyc'
import 'numpy._distributor_init' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f9638fb7f60>
# numpy.core not found in PYZ
# code object from '/var/tmp/sample/numpy/core/__init__.pyc'
# numpy.core.multiarray not found in PYZ
# code object from '/var/tmp/sample/numpy/core/multiarray.pyc'
# numpy.core.overrides not found in PYZ
# code object from '/var/tmp/sample/numpy/core/overrides.pyc'
# numpy.core._multiarray_umath not found in PYZ
[11529] LOADER: Restoring signal handlers
[11529] LOADER: freeing args
[11529] LOADER: re-raising child signal 11
Segmentation fault (core dumped)

SECOND CASE 

# destroy scipy
# destroy calendar
# destroy email.header
# destroy binascii
# destroy uu
# destroy quopri
# destroy email.utils
# destroy email.errors
# destroy email.charset
# destroy pkg_resources._vendor.six.moves
# destroy platform
# destroy pkg_resources._vendor.six.moves.urllib_parse
# destroy typing
# destroy pandas._libs.json
# destroy signal
# destroy weakref
# destroy argparse
# destroy unittest.loader
# destroy unittest.runner
# destroy urllib
# destroy base64
# destroy bisect
# destroy hashlib
# destroy posixpath
# destroy tempfile
# destroy contextlib
# destroy posix
# destroy locale
# destroy email
# destroy http
# destroy io
# destroy socket
# destroy ssl
# destroy traceback
# destroy math
# destroy _frozen_importlib
[11667] LOADER: Restoring signal handlers
[11667] LOADER: freeing args
[11667] LOADER: re-raising child signal 11
Segmentation fault (core dumped)


THE SUCCESSFUL ONE:

# destroy posix
# destroy locale
# destroy email
# destroy http
# destroy io
# destroy socket
# destroy ssl
# destroy traceback
# destroy math
# destroy _frozen_importlib
[11421] LOADER: Restoring signal handlers
[11421] LOADER: freeing args
[11421] LOADER: returning child exit status 0
[11421] LOADER: Back to parent (RC: 0)
[11421] LOADER: Doing cleanup
[11421] LOADER: Freeing archive status for /var/tmp/sample/sample


```

**Comment by rokm** [comment] 2020-12-04 11:39
So you're building on RHEL7 and trying to run on an even older distribution with kernel 2.6? What's the target distribution, if you don't mind the question?

What is the build environment like? Is this python 3.6.7 coming from RH SCL (`rh-python36` RPM)? And is everything else installed via pip? Or are you building using anaconda environment?

And, can you test if the binary runs on another RHEL7 system that is not the build system? (preferrably without python3 environment installed)

**Comment by Koushik667** [comment] 2020-12-04 15:29
Yes, I am building it in Linux 3.10.0-1062.9.1.el7.x86_64 and my target distribution is kind of customized linux 2.6 64 bit..
I am using virtual env in the build environment in which i have installed the packages from pip.
I dont know from where they installed python from..but as soon as i enter python console i get this
```
Python 3.6.7 (v3.6.7:6ec5cf2, Oct 24 2018, 15:53:56) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
```
I am not using anaconda environment.

Yes binary runs fine on Linux 3.10.0-957.27.2.el7.x86_64,ie another RHEL7 system..I only see python2.7 in this machine(python3 on the terminal gives no output)

**Comment by rokm** [comment] 2020-12-04 19:09
Hmm, well, with no way to reproduce this, I'm afraid you're more or less on your own.

I suppose the next step would be trying to determine if it is really the older kernel that's causing issues, or one of the libraries on your target system (e.g., a library used by one of your python packages but not collected by pyinstaller).

Does the same segfault occur on the target machine if you freeze a simple, hello world python program (i.e., without importing anything from `scikit-*`)? If not, does it occur if you import `numpy`?

**Comment by Koushik667** [comment] 2020-12-05 06:03
I tested with simple hello world program,No fault is seen.
And also the fault occurs(sometimes) if i try to import only numpy.
[a.txt](https://github.com/pyinstaller/pyinstaller/files/5646551/a.txt) is the debug log when the seg fault occurs.

**Comment by rokm** [comment] 2020-12-05 20:17
OK, so I'd say that likely means that `numpy` is causing issues here, either directly or indirectly...

Is this a `onefile` build (messages about re-raising signal from child seem to imply that)? In that case, could you try running in `onedir` mode instead? That might give an additional output to console when the segfault occurs (and will also make it easier to attach the debugger).

You might also want to try different using a different version of numpy...

**Comment by Koushik667** [comment] 2020-12-06 10:15
The logs i had sent are of onedir mode itself...
I was using '1.19.4' of numpy,Tried '1.15.4' as well..same issue..
Tried analysing core file using gdb,but couldnt load the symbols.
Do you think that analysing core file will help?Should i try some other version of numpy/pyinstaller?

**Comment by rokm** [comment] 2020-12-06 20:50
> Do you think that analysing core file will help?

Depends on where the segfault is occurring... if it's in one of the libraries that came from python packages, then you're unlikely to find the correct debug symbols. If it's in one of the libraries that are part of the target system, then you'll need the debug symbols for those. Even so, the backtrace could give you some useful hints.

At this point, I'm running out of the ideas. Do you have an option to set up a python3 environment on the target system? So you could check if numpy works normally there in non-frozen version? And then perhaps try freezing on the target system as well, just to reduce the number of unknown factors...

**Comment by Koushik667** [comment] 2020-12-07 05:29
No..i dont seem to have an option to setup python3 env on target :(

**Comment by Koushik667** [comment] 2020-12-07 06:55
Also for some reason in my target machine both 32 bit and 64 bit gdb is not able to load the core file..i transferred both the core files to some other machine and tried to load one of the corefile there and attach debug symbols..but backtrace still gives " ?? "
I am attaching [gdb_log.txt](https://github.com/pyinstaller/pyinstaller/files/5650897/gdb_log.txt) here..What can i do to get the backtrace?

**Comment by rokm** [comment] 2020-12-07 09:25
> What can i do to get the backtrace?

Sorry, I have no experience with cross-debugging... 

But unless I am mistaken, you need to pass to `gdb` the binary that generated the core dump as well?

> Also for some reason in my target machine both 32 bit and 64 bit gdb is not able to load the core file...

I guess that raises even more questions about your target system, though. You mentioned it is a customized linux version - does that mean it is built completely from scratch, or is it based on a "standard" distribution? In other words, are the core libraries (e.g., `glibc`) built with standard options, or is this a completely custom built with potentially incompatible options? For the reference, what version of `glibc` does the target system use, and what is the kernel's minor revision number (2.6.X?)?

**Comment by Koushik667** [comment] 2020-12-07 09:46
Not sure if it is based on standard distribution..
laas-si-setup:ssi# ldd --version
ldd (GNU libc) 2.17
This is the os i have in my target system 2.6.38-staros-v3-ssi-64.

However kernel release output gives this:
uname - r
BusyBox v1.26.2 (2020-07-16 11:38:15 EDT) multi-call binary.

**Comment by rokm** [comment] 2020-12-07 11:13
> 2.6.38-staros-v3-ssi-64

Ufff, okay, I guess that explains the constraints you mentioned earlier. I was operating under assumption that we were dealing with a run-of-the-mill linux distribution there, but this definitely falls outside my expertise. 

What you're trying to do strikes me as a clever attempt at trying to get around the limitations of the target system (e.g., not being able to set up python3 env there), but by the same token, I find little reason to believe it would (or should) work. 

You are essentially mixing the libraries from your base OS, possibly from RHEL, and the libraries that come with e.g., numpy (such as its own copy of openblas). I guess it could also be (subtle) incompatibility between numpy's openblas library and the hardware (as far as I understand, that's not the "commodity" x86/x86_64 CPU that's used there?), or something like that...

**Comment by Koushik667** [comment] 2020-12-07 15:57
> You are essentially mixing the libraries from your base OS, possibly from RHEL, and the libraries that come with e.g., numpy (such as its own copy of openblas)

So,If this is the case,then if i freeze the program in some other linux distribution ,will it run in target machine(RHEL)?

**Comment by rokm** [comment] 2020-12-07 16:30
For linux, I'd say there are no guarantees for cross-distribution compatibility (or even across different versions of the same distribution). It all boils down the compatibility between the libraries that are collected from the build system and the libraries on the target system (that were not collected from the build system but are (directly or indirectly) required by the frozen program). This is especially true when you use python packages with lots of external (shared library) dependencies. See #4985, for example.

But I think that's a general issue with binary-only software on linux...

From my experience, I'd recommend freezing on the same distribution as your target distribution, same as if you were building for example a C++ program. This way, you can control for most external factors...

**Comment by alsf2001** [comment] 2021-01-13 06:47
Is the cause of the problem found? I ran into the same problem

**Comment by Koushik667** [comment] 2021-01-13 09:38
No,the exact cause for this is not found.I am trying to install the required packages from source in the taeget machine..But finding it difficult to do due to old version linux in my target machine.

**Comment by rokm** [comment] 2021-03-20 16:17
Closing this due to insufficient information and inadequate tooling on the target machine to produce any insight into what the problem is. If you manage(d) to run python3 and numpy natively on the target machine, and/or have obtained any new information, feel free to re-open the issue.

**Closed by rokm** 2021-03-20 16:17 UTC

**Comment by minusplusminus** [comment] 2021-10-19 08:04
Same issue. Could be related to this issue, because numpy is part of deps: https://github.com/numpy/numpy/issues/18131#issuecomment-762235284 

I tested this on my Macbook m1 (aarch64) with `docker buildx build --platform linux/arm/aarch64 -f Dockerfile.aarch64 .` which worked. Deployed exactly same container on Jetson nano gives a segmentation fault :|  only when building pyinstaller exec

removing the `libopenblasp-r0-32ff4d91.3.13.so` file,  installing `apt libopenblas-dev` and simlinking like this:

`ln -s /usr/lib/aarch64-linux-gnu/libopenblas.so /usr/src/app/libopenblasp-r0-32ff4d91.3.13.so` solved my issue
