### ISSUE TITLE
Binary is being forked multiple time even after the main exit()

### ISSUE THREAD

**Issue by EKami** [pyinstaller/pyinstaller#3936] opened 2018-12-19 17:55 UTC
Hello,
I'm currently trying to use PyInstaller for my project to create a linux executable but I'm running into a very nasty issue.
Basically I have this spec file:
```
# -*- mode: python -*-

block_cipher = None

added_files = [] #[('output/train_data/', 'output/train_data/')]

a = Analysis(['./src/main.py'],
             binaries=[],
             datas=added_files,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True)
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='main')
```
That I use to generate my project. It's a project with a lot of dependencies including Tensorflow/sklearn/matplotlib etc...

The binary file is generated as I expect but when I run it with `./dist/main/main` **once** the process fork itself infinitely and I have to reboot my computer. 
Even if I add:
```
if __name__ == "__main__":
    exit(-1)
```
I get:
```
[6754] LOADER: Post-init sys.path is /home/ekami/workspace/remote/PW/dist/main/base_library.zip:/hom[0/1828]workspace/remote/PW/dist/main
[6754] LOADER: Setting sys.argv
[6754] LOADER: setting sys._MEIPASS
[6754] LOADER: importing modules from CArchive
[6754] LOADER: extracted struct
[6754] LOADER: callfunction returned...
[6754] LOADER: extracted pyimod01_os_path
[6754] LOADER: callfunction returned...
[6754] LOADER: extracted pyimod02_archive
[6754] LOADER: callfunction returned...
[6754] LOADER: extracted pyimod03_importers
[6754] LOADER: callfunction returned...
[6754] LOADER: Installing PYZ archive with Python modules.
[6754] LOADER: PYZ archive: PYZ-00.pyz
[6754] LOADER: Running pyiboot01_bootstrap.py
[6754] LOADER: Running pyi_rth_pkgres.py
[6754] LOADER: Running pyi_rth_multiprocessing.py
[6754] LOADER: Running pyi_rth_traitlets.py
[6754] LOADER: Running pyi_rth__tkinter.py
[6754] LOADER: Running pyi_rth_mplconfig.py
[6754] LOADER: Running pyi_rth_mpldata.py
[6754] LOADER: Running main.py
```
In loop. Any idea what is happening here? Thank you.

**Comment by htgoebel** [comment] 2019-01-02 13:50
The code you show does not include any multiprocessing, thus I doupt that this code would allow to reproduce the isse. So I'm closing this due to misleading information.

You say you are using tensorflow, thus #3907 might help you

**Closed by htgoebel** 2019-01-02 13:50 UTC
