### ISSUE TITLE
Basic single line print file fails to bundle

### ISSUE THREAD

**Issue by rwarren** [pyinstaller/pyinstaller#4102] opened 2019-03-04 20:39 UTC
In order to see how small a PyInstaller bundle can get, I just tried bundling a file with a single print statement in it. A fresh `venv` was used (on Win7 with Python 3.7.2), within which `pyinstaller` was pip installed.

I initially used the default pip version, but after reading through the bug reporting guidelines I ran with the latest dev version (see `pip freeze` output below), and with `--onedir` instead of `--onefile`. This made no difference. Note that `--debug` did not work at all for me.

The basic setup...

```
C:\pcode\udbs_unit_copy>python --version
Python 3.7.2

C:\pcode\udbs_unit_copy>pip freeze
altgraph==0.16.1
future==0.17.1
macholib==1.11
pefile==2018.8.8
PyInstaller==3.5.dev0+cb8d10af6
pywin32-ctypes==0.2.0

C:\pcode\udbs_unit_copy>echo print("hello!") > foo.py

C:\pcode\udbs_unit_copy>python foo.py
hello!
```

The failure:

```
(uuc) C:\pcode\udbs_unit_copy>pyinstaller --debug=all --onedir foo.py
89 INFO: PyInstaller: 3.5.dev0+cb8d10af6
90 INFO: Python: 3.7.2
90 INFO: Platform: Windows-7-6.1.7601-SP1
101 INFO: wrote C:\pcode\udbs_unit_copy\foo.spec
110 INFO: UPX is not available.
110 INFO: Extending PYTHONPATH with paths
['C:\\pcode\\udbs_unit_copy', 'C:\\pcode\\udbs_unit_copy']
110 INFO: checking Analysis
130 INFO: checking PYZ
141 INFO: checking PKG
150 INFO: Building PKG because PKG-00.toc is non existent
150 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "C:\Users\war12184\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\war12184\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\pcode\udbs_unit_copy\.venv\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\pcode\udbs_unit_copy\foo.spec", line 29, in <module>
    console=True )
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\building\api.py", line 430, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\building\api.py", line 196, in __init__
    self.__postinit__()
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\pcode\udbs_unit_copy\.venv\lib\site-packages\PyInstaller\building\api.py", line 273, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "C:\Users\war12184\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\Users\war12184\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by MyDataIsReady** [comment] 2019-04-18 08:40
Check this:
https://github.com/pyinstaller/pyinstaller/issues/4146#issuecomment-484405210

**Comment by htgoebel** [comment] 2019-08-07 16:00
Duplicate of #3942

**Closed by htgoebel** 2019-08-07 16:00 UTC
