### ISSUE TITLE
pyside and multiprocessing

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#543] opened 2014-10-18 14:17 UTC
**Original date**: 2012/04/05
**Original reporter**: *avraham seror <tovmeod AND gmail DOT  COOM >*

I have a program that uses pyside and multiprocessing, I managed to create an exe using the attached spec file.
I used the develop branch so I could use hiddenimports
when running the exe I get ImportError: cannot import name QtWebKit
I managed to make it work using the coolhandmook-pyinstaller-551ca1a fork
but then when trying to use the multiprocessing part it gives me EOFError
this happens even when using --onedir

I tried to make a simple example that fails, but then I stumbled on even more errors (WindowsError: [Error 6] The handle is invalid)

on the top of that if I use --onefile the webkit component can't load the imageformats plugins

I'm on windows 7 64, python 2.7

**Comment by matysek** [comment] 2015-01-01 13:09
I think this is caused by missing hooks for pyside. This is duplicate of #498.

**Closed by matysek** 2015-01-01 13:09 UTC
Labels: @high, develop
