### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by amarokmclion** [pyinstaller/pyinstaller#2558] opened 2017-04-12 10:01 UTC
Hi all,

I'm trying to pack an exe for the following simple script just to test if pyinstaller works with sympy lib:
from sympy import *

R1 = 60.162
R2 = 180.41
R0 = 49.073
X0 = 0.0386
R3 = 120.09
X3 = -111.376
V1 = 0.24624
V2 = 0.17885
V3 = 0.17539
Rs = Symbol('Rs', positive=True)
Xs = Symbol('Xs')
sol = solve([(V1**2/V2**2)-((R2+Rs+R0)**2+(Xs+X0)**2)/((R1+Rs+R0)**2+(Xs+X0)**2),(V1**2/V3**2)-((R3+Rs+R0)**2+(Xs+X0+X3)**2)/((R1+Rs+R0)**2+(Xs+X0)**2)])
print (sol)

I'm using:
4 INFO: PyInstaller: 3.3.dev0+bb9e52f
95 INFO: Python: 3.6.1
96 INFO: Platform: Windows-10-10.0.14393-SP0

I'm getting the recursion error from modulegraph that should have been fixed. This is the log i'm getting:
https://pastebin.com/6PW08zCT

p.s. I'm also getting the same error with python 3.5.3

**Comment by xoviat** [comment] 2017-04-13 16:41
```
Git clone https://GitHub.com/pyinstaller/pyinstaller.git
Git pull +refs/heads/pull/2428/merge
Pip install .
```

**Comment by xoviat** [comment] 2017-04-13 16:42
```
Git clone https://GitHub.com/pyinstaller/pyinstaller.git
CD pyinstaller
Git pull +refs/heads/pull/2428/merge
Pip install .
```

**Comment by amarokmclion** [comment] 2017-04-14 08:44
Hi xoviat,

when I'm trying your command in git bash I'm getting this error:

~\pyinstaller [develop ≡]> Git pull +refs/heads/pull/2428/merge
fatal: '+refs/heads/pull/2428/merge' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Thanks for your help.

**Comment by xoviat** [comment] 2017-04-14 13:40
Sorry, it's:

```
+refs/pull/2428/merge
```

**Comment by amarokmclion** [comment] 2017-04-14 16:02
Thanks! With your patch pyinstaller is working with my script.

**Comment by xoviat** [comment] 2017-04-14 16:26
@htgoebel To be perfectly candid, I think the patch should be applied sooner rather than later because even if the import order is not correct (which I believe it is), PyInstaller will support more cases with the patch than without it, and I think that's what we're trying to achieve. Also the merge rate has been glacial lately.

**Comment by adizhol** [comment] 2017-10-15 11:59
after I run
```
git clone https://GitHub.com/pyinstaller/pyinstaller.git
CD pyinstaller
git pull  origin+refs/pull/2428/merge
```
I get the following merge conflict message:
```Auto-merging PyInstaller/lib/modulegraph/modulegraph.py
CONFLICT (content): Merge conflict in PyInstaller/lib/modulegraph/modulegraph.py
Automatic merge failed; fix conflicts and then commit the result.
```
I cloned from "develop" branch

**Comment by bryab** [comment] 2017-10-24 16:28
I had the same issue, and merging this pull request fixed it as well.  Is there a reason this was not merged?

**Comment by htgoebel** [comment] 2017-11-12 10:38
Duplicate of #2426.

**Closed by htgoebel** 2017-11-12 10:38 UTC

**Comment by Beadsworth** [comment] 2020-02-05 22:57
Hello,

Just checking in to say this solution worked for me as well.

SymPy was the package that was giving me trouble.

**Comment by Addishiwot** [comment] 2020-07-20 09:00
the patch does not seem to be working. up on running the pull command, I have experienced the ff error

$ Git pull +refs/pull/2428/merge
fatal: '+refs/pull/2428/merge' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
