### ISSUE TITLE
current folder contents gets copied matplotlib mpl-data 

### ISSUE THREAD

**Issue by RubendeBruin** [pyinstaller/pyinstaller#5731] opened 2021-04-13 13:28 UTC
Apologies for this cripple bug report. Its an issue that just doesn't fit the template.

When compiling a project that makes use of matplotlib the contents of the current directory (cd) gets copied into dist/appname/matplotlib/mpl-data

That means that for example the ./build folder gets copied to 
./dist/appname/matplotlib/mpl-data/build

Pretty sure this is caused by:
```
94879 INFO: Loading module hook 'hook-matplotlib.py' from 'c:\\miniconda3\\envs\\grillex_deploy\\lib\\site-packages\\PyInstaller\\hooks'...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'matplotlib' has no attribute '_get_data_path'
```

**Comment by rokm** [comment] 2021-04-13 13:32
Duplicate of #5567, fixed by #5568. If you want to use You'll need to use `develop` branch until next PyInstaller release if you want to use `matplotlib` 3.4.x.

**Closed by rokm** 2021-04-13 13:32 UTC

**Comment by RubendeBruin** [comment] 2021-04-13 13:39
Ah, ok. Did already dive into the import hook and did not see any obvious errors there. The print statement did yield the correct path.
Thanks!

**Comment by rokm** [comment] 2021-04-13 13:44
Yeah, the hook was using a private function `_get_data_path` instead of public `get_data_path`, and the former was removed in matplotlib 3.4.0. So the hook effectively received an empty path, which corresponds to current working directory.
