### ISSUE TITLE
multi processing error under cmd 

### ISSUE THREAD

**Issue by ecamy** [pyinstaller/pyinstaller#3196] opened 2018-01-09 04:02 UTC
Hi, 
    I programme using multiprocessing of python, then publish into  .exe using  pyinstaller. No error during package. When I run it under cmd( dos windows), the response is as follows:

   List index out of range

   I am puzzle for this. Because I debug and run the program, it works well. Why error under cmd, please?

   I have three processes in my program,  one list for each process.

My Environment:
1. Windows8, 8Cores CPU, 8G Memory
2. Python3.4, Pyinstaller3.3.1

**Comment by htgoebel** [comment] 2018-01-09 09:47
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error and the traceback.

**Comment by ecamy** [comment] 2018-01-10 02:57
Hi, htgoebel ,
   I make a toy program as the file named test.zip for this issue, ,  If I delete these codes from my program, everything is well. 
[test.zip](https://github.com/pyinstaller/pyinstaller/files/1617299/test.zip)

  test.py  can work well when I use command line to compile it or implement basing on eclipse(see correct.jpg. When I package it into .exe using pyinstaller, still no error message.  When I run the exe file, my computer would crash. 
![correct](https://user-images.githubusercontent.com/23048635/34753279-09aa43e6-f5f2-11e7-9ff5-869cca068d68.jpg)
      My current program different from the above as the follows:
     1. The three processing call a function which can write Mariadb database.
     2. All the list cant be get from a common function
     It make the cmd windows stopping, not make a crash. I do this with dir or single mode, the former shows the error 5700 , the latter shows the error 1528 (see Derror.jpg and Ferror.jpg). The error line prompted is so strange(code.jpg).
![derror](https://user-images.githubusercontent.com/23048635/34753496-485e5702-f5f3-11e7-9d9c-c585b7f0e686.jpg)
![ferror](https://user-images.githubusercontent.com/23048635/34753502-4e5add1a-f5f3-11e7-9b3d-802fa43c8819.jpg)
![code](https://user-images.githubusercontent.com/23048635/34753564-ba9db902-f5f3-11e7-8f3b-23752c1783f5.jpg)
    I also try another tools named cxfreeze, the same error occurs like the above.  
   Even the example have the different prompts from my program, but I delete the above multi processing codes, all things is all normal. So I think my problem will be solved followed the example.
   Also thanks for your tools to package exe, it makes our work so convenient.

**Comment by htgoebel** [comment] 2018-01-12 22:38
I'm not going to open any archive for security reasons. Please paste the relevant information here, no picutures, but test. Thanks.

Beside this: If your computer crashes, - and also does then using cxfrezze -  I **strongly doubt** this is related to freezing and PyInstaller.

Please provide a **minimal* example and the traceback.

**Comment by ecamy** [comment] 2018-01-15 04:28
Hi,htgoebel,

These days I have tried to make another minimal example for you, but failed because of the complexity of my program. But I still think my program will work if test.py can run normally, because they are from my program directly.

I also want to try some methods to program if this problem can't be solved. Sorry for no deeper example for you.

**Comment by ecamy** [comment] 2018-01-15 11:17
Hi, @htgoebel ,
I see why "List index out of range", because I use the parameters sys.argv[1][2] etc. when I remove them, no errors like before, but still crushed(black screen).   
Additionally, there aren't any information under czfrezze, and No correct result generated, but computer can still work.

**Comment by htgoebel** [comment] 2018-01-15 21:17
So I'm closing this issue, since there at too less informations to help.

**Closed by htgoebel** 2018-01-15 21:17 UTC
Labels: need info, support
