### ISSUE TITLE
Error with --onefile when having both pywin32 / pypiwin32 installed

### ISSUE THREAD

**Issue by davidenkoization** [pyinstaller/pyinstaller#1488] opened 2015-09-15 07:03 UTC
I am using Python 3.4.3 with the Anaconda 2.3.0 (64 bit) release on a 64-bit Winsows 7 computer and PyInstaller 3.0.dev1 to create an executable out of my python script. If I choose the onefolder option everything runs smoothly as wanted. When I use the --onefile option the creation of my exe works but when I run it the program I get following message:

WARNING: file already exists but should not: C:\.....\Temp\\_MEIXXXXX\pywintypes34.dll

My program continues anyway, but when running a multiprocessing.pool it gets stuck and shows the warning above every few seconds with new _MEIXXXXX folders.

I think this error is connected to using pywin32 and pypiwin32 at the same time (see also here: https://github.com/pyinstaller/pyinstaller/issues/1447). If I deinstall pywin32 from my computer and try to run pyinstaller I get following error message:
  File "C:\....\.conda\envs\py34_\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 20, in <module>
   import pywintypes
ImportError: No module named 'pywintypes'

So I guess I need both pywin32 and pypiwin32?

And I found a workaround to get rid of the warning message by adding these lines to my spec file after the a=Analysis( .....) part:

for d in a.binaries:
    if 'pypiwin32_system32\\pywintypes34' in d[1]: 
        a.binaries.remove(d)
        break

There is no more error message, but the program still gets stuck as before. Any advice you can give me?

**Comment by codewarrior0** [comment] 2015-09-15 07:23
I don't have any experience with using `multiprocessing` when frozen, so I don't know if this info still applies for PyInstaller 3.0, but have you read the [Multiprocessing Recipe](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing) page on the Wiki?

**Comment by davidenkoization** [comment] 2015-09-15 07:45
thank  you, I will look into that and let you know if it solves my issues.

**Comment by giumas** [comment] 2015-09-23 03:16
On Win7 with Miniconda (by both using Python 2.7.10 32 bit and 3.4.3 64bit) and only if I use `--onefile`, I get the same type of warning: `WARNING: file already exists but should not: C:\Users\xxxx\AppData\Local\Temp\_MEI12345\pywintypes27.dll` and `WARNING: file already exists but should not: C:\Users\xxxx\AppData\Local\Temp\_MEI12345\pywintypes34.dll`. This happens with different applications that were working with older versions of `PyInstaller`.

In `out00-Analysis.toc`, one `pywintypesXX.dll` comes from the Miniconda's `site-packages\\win32`, the other from `C:\\Windows\\system32`. Should the analysis provide unique library or is this a required behavior? I guess that, following the @davidenkoization 's workaround, I should drop the system's lib. Is this correct?

**Comment by matysek** [comment] 2015-09-23 07:42
Yes, that is correct. Could you try uninstall the pywin32 package that you got from http://sourceforge.net/projects/pywin32/files/pywin32/?

I think this could solve your issue.

**Comment by matysek** [comment] 2015-09-23 08:09
@davidenkoization Could you try:
1. uninstall both - pywin32 and pypiwin32
2. pipinstall again pypiwin32

**Comment by davidenkoization** [comment] 2015-09-23 11:42
I tried your suggestion, now I only have pypiwin32 running. I still get the same error messages using the --onefile option. When using the --onedir flag everything works fine. I think it is an issue with the multiprocessing as codewarrior0 suggested. My program uses multiprocessing pools (i didn't write that part myself) and I am not sure how to implement the multiprocessing recipe to that problem. I am currently fine with the onedir solution and don't have the time to dig deeper solving my issues with the --onefile option. Thanks for your input though and making me aware of the multiprocessing recipe!

**Comment by matysek** [comment] 2015-09-23 12:22
@davidenkoization Do you have any code example you could share for reproduction?

**Comment by giumas** [comment] 2015-09-23 12:58
My system's `pywintypesXX.dll` comes from  http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32 by running the post-installation script execution (as suggested), not directly from http://sourceforge.net/projects/pywin32/files/pywin32/

@matysek : as you well know, it is not uncommon for Windows users to have wheels from `~gohlke` together with multiple Python installations. 

However, removing that installation solved the `WARNING` without the need of the @davidenkoization 's workaround.

**Comment by matysek** [comment] 2015-09-23 13:12
> However, removing that installation solved the WARNING without the need of the @davidenkoization 's workaround.

@giumas thanks for testing it. This is what I though.

**Comment by matysek** [comment] 2015-09-23 13:14
The solution is to uninstall system's pywin32 package and keep only pypiwin32 which is per Python installation. Closing.

**Comment by htgoebel** [comment] 2015-09-23 19:07
@tallforasmurf : I think, this is a note to be put into the docs?!
> The solution is to uninstall system's pywin32 package and keep only pypiwin32 which is per Python installation.

**Comment by tallforasmurf** [comment] 2015-09-24 22:18
Just to be clear, this problem arises when you already have pywin32 installed, and THEN install pypiwin32 ALSO?

What if you ONLY have pywin32 installed, for example because you had used an earlier version of PyInstaller which recommended pywin32?

If you follow our other recommendation and use a VENV, and install pypiwin32 in the VENV, is there then a problem with the system pywin32?

**Comment by matysek** [comment] 2015-09-25 13:10
How to reproduce:
1) install system-wide pywin32 package
2) create VENV, pip install pypiwin32
3) run this code with --onefile option
```python
import pywintypes
```
4) you will get messages like this:
```
16015 WARNING: One binary added with two internal names. C:\Windows\system32\pywintypes33.dll was placed at .\pywintypes33.dll previously.
...
LOADER: Extracting binaries
WARNING: file already exists but should not: C:\Users\martin\AppData\Local\Temp\_MEI12282\pywintypes33.dll
LOADER: Executing self as child
```

**Comment by matysek** [comment] 2015-09-25 13:23
@tallforasmurf It's weird that it still complains eve when I uninstalled system pywin32. `pywintypes.__file__` still  points to `c:\Windows\System32\pywintypes33.dll` even when this file no longer exists.  There might be any issue with some caching.

**Comment by matysek** [comment] 2015-09-25 13:26
> Just to be clear, this problem arises when you already have pywin32 installed, and THEN install pypiwin32 ALSO?
additional requirement is that your app has dependency on module `pywintypes`.
>
> What if you ONLY have pywin32 installed, for example because you had used an earlier version of PyInstaller which recommended pywin32?
>
pip install will install pypiwin32 so you have then both installed.

> If you follow our other recommendation and use a VENV, and install pypiwin32 in the VENV, is there then a problem with the system pywin32?

Yes, you have to uninstall the system pywin32.

**Comment by tallforasmurf** [comment] 2015-09-25 16:37
It is a "feature" of PyInstaller 3 that pip auto-installs pypiwin32 with it. But that new feature can create this problem for the user, no? So what to say in the doc? "Before you install PyInstaller 3 with pip, you should first uninstall pywin32" ?

**Comment by matysek** [comment] 2015-09-25 16:44
We could try modify `setup.py` to install `pypiwin32` only if `pywintypes` is not importable. Would that help?

**Comment by matysek** [comment] 2015-09-25 18:08
But still, the user might use virtualenv with ignoring 'global-site-packages' (this is the default virtualenv settings) and having system pywin32 then pypiwin32 get's installed. So we still need to get this fixed anyway.

I suggest this for resolving this issue:
* install pypiwin32 only if `pywintypes` is not importable (verify if that works)
* find out and fix why pyinstaller complains about having `pywintypes` twice.
```
16015 WARNING: One binary added with two internal names. C:\Windows\system32\pywintypes33.dll was placed at .\pywintypes33.dll previously.
...
LOADER: Extracting binaries
WARNING: file already exists but should not: C:\Users\martin\AppData\Local\Temp\_MEI12282\pywintypes33.dll
LOADER: Executing self as child
```
Then we do not need to document anything in the manual.

@codewarrior0 Do you have any suggestion where to start looking?

**Comment by matysek** [comment] 2015-09-25 19:06
@davidenkoization look at the multiprocessing recipe. I updated it so it should make your code working even with `--onefile` option: https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

See especially these line:
```python
# Second override 'Popen' class with our modified version.
forking.Popen = _Popen
```

**Comment by giumas** [comment] 2015-09-26 00:06
On Win7 x64 and Anaconda Python 2.7.10, I have started with a new&clean Python installation. 

After having installed `pyinstaller` (from the `python3` cd5d9ac72fbe9262c9b62ccee7c0a19ac84bd0ad), I get this warning::

* `28182 WARNING: One binary added with two internal names. C:\Users\xxxx\AppData\Local\yyyyy\py2\lib\site-packages\pypiwin32-219-py2.7-win32.egg\pywintypes27.dll was placed at .\pywintypes27.dll previously.`

When I ran the single-file application, I get 2 warnings:

* `WARNING: file already exists but should not: C:\Users\xxxx\AppData\Local\Temp\_MEI103442\pywintypes27.dll`

* `WARNING: file already exists but should not: C:\Users\xxxx\AppData\Local\Temp\_MEI103442\pythoncom27.dll`

I have double checked if `pywin32` was installed in some way, but it is not. The `conda list` give me:

* `pyinstaller               3.0.dev6+b7954b3           <pip>`
* `pypiwin32                 219                       <pip>`

**Comment by matysek** [comment] 2015-09-26 13:56
@giumas 
* Anaconda already contains  pywin32: http://docs.continuum.io/anaconda/pkg-docs
* I don't know if `conda list` will tell you that pywin32 is installed or not.
* uninstall pypiwin32
* then try run this code if you get `ImportError`
```
import pywintypes
```
* This confirms that installing pypiwin32 if pywin32 is not installed is the way to go.

**Comment by giumas** [comment] 2015-09-26 14:27
@matysek 

> * Anaconda already contains pywin32: http://docs.continuum.io/anaconda/pkg-docs

I am actually using Miniconda (http://conda.pydata.org/miniconda.html) to just have `conda` and the python installation.

> * uninstall pypiwin32
> * then try run this code if you get `ImportError`

I get: 

    Traceback (most recent call last):
      File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\Scripts\pyinstaller-script.py", line 5, in <module>
        from pkg_resources import load_entry_point
      File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\lib\site-packages\setuptools-18.3.2-py2.7.egg\pkg_resources\__init__.py", line 3084, in <module>

      File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\lib\site-packages\setuptools-18.3.2-py2.7.egg\pkg_resources\__init__.py", line 3070, in _call_aside

      File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\lib\site-packages\setuptools-18.3.2-py2.7.egg\pkg_resources\__init__.py", line 3097, in _initialize_master_working_set

      File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\lib\site-packages\setuptools-18.3.2-py2.7.egg\pkg_resources\__init__.py", line 651, in _build_master

      File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\lib\site-packages\setuptools-18.3.2-py2.7.egg\pkg_resources\__init__.py", line 952, in require

      File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\lib\site-packages\setuptools-18.3.2-py2.7.egg\pkg_resources\__init__.py", line 839, in resolve

    pkg_resources.DistributionNotFound: The 'pypiwin32' distribution was not found and is required by PyInstaller

After that, I have attempted to install `pywin32`, but it does not help.

**Comment by matysek** [comment] 2015-09-26 20:47
* @giumas Are you sure that even minconda does not have pywin32?
* What is the __file__ attribute of pywintypes module?
```
import pywintypes as p
print(p.__file__)
```

**Comment by giumas** [comment] 2015-09-26 21:30
Yes, I am sure. I have also double-checked with a system search for pywin* in the miniconda installation folder.

This is the `conda list` with a clean Miniconda installation:

    # packages in environment at C:\Users\yyyyyy\AppData\Local\Continuum\Miniconda:
    #
    conda                     3.16.0                   py27_0
    conda-env                 2.4.2                    py27_0
    menuinst                  1.0.4                    py27_0
    pycosat                   0.6.1                    py27_0
    pycrypto                  2.6.1                    py27_3
    python                    2.7.10                        0
    pyyaml                    3.11                     py27_1
    requests                  2.7.0                    py27_0
    
This is after `conda install pip`

    # packages in environment at C:\Users\yyyyyy\AppData\Local\Continuum\Miniconda:
    #
    conda                     3.17.0                   py27_0
    conda-env                 2.4.2                    py27_0
    menuinst                  1.0.4                    py27_0
    pip                       7.1.2                    py27_0
    pycosat                   0.6.1                    py27_0
    pycrypto                  2.6.1                    py27_3
    python                    2.7.10                        0
    pyyaml                    3.11                     py27_2
    requests                  2.7.0                    py27_0
    setuptools                18.3.2                   py27_0
    wheel                     0.26.0                   py27_1
    
Then, after `python setup.py install` with the last `python3` commit:

    # packages in environment at C:\Users\yyyyyy\AppData\Local\Continuum\Miniconda:
    #
    conda                     3.17.0                   py27_0
    conda-env                 2.4.2                    py27_0
    menuinst                  1.0.4                    py27_0
    pip                       7.1.2                    py27_0
    pycosat                   0.6.1                    py27_0
    pycrypto                  2.6.1                    py27_3
    pyinstaller               3.0.dev6+83d8ed5           <pip>
    pypiwin32                 219                       <pip>
    python                    2.7.10                        0
    pyyaml                    3.11                     py27_2
    requests                  2.7.0                    py27_0
    setuptools                18.3.2                   py27_0
    wheel                     0.26.0                   py27_1
    
Whe I run "pyinstaller --clean -y -F minimal.py", I get the warning + the required `print`:

* `WARNING: file already exists but should not: C:\Users\yyyyyy\AppData\Local\Temp\_MEI83362\pywintypes27.dll`
* `C:\Users\yyyyyy\AppData\Local\Temp\_MEI83362\pywintypes27.dll`

The only pywintypes27.dll available in `C:\Users\yyyyyy\AppData\Local\Continuum\Miniconda` is in `Lib\site-packages\pypiwin32-219-py2.7-win32.egg`.

I noticed that in the analysis file, the pywintypes27.dll is once listed as `BINARY` and another time as `DATA`:

* `('pywintypes27.dll', 'c:\\users\\yyyyyy\\appdata\\local\\continuum\\miniconda\\lib\\site-packages\\pypiwin32-219-py2.7-win32.egg\\pywintypes27.dll', 'DATA')`

* `('.\\pywintypes27.dll', 'C:\\Users\\yyyyyy\\AppData\\Local\\Continuum\\Miniconda\\lib\\site-packages\\pypiwin32-219-py2.7-win32.egg\\pywintypes27.dll', 'BINARY')`

Is this the issue?

**Comment by matysek** [comment] 2015-09-27 21:15
> I noticed that in the analysis file, the pywintypes27.dll is once listed as BINARY and another time as DATA:
> 
> ('pywintypes27.dll', 'c:\\users\\yyyyyy\\appdata\\local\\continuum\\miniconda\\lib\\site-packages\\pypiwin32-219-py2.7-win32.egg\\pywintypes27.dll', 'DATA')
> 
> ('.\\pywintypes27.dll', 'C:\\Users\\yyyyyy\\AppData\\Local\\Continuum\\Miniconda\\lib\\site-packages\\pypiwin32-219-py2.7-win32.egg\\pywintypes27.dll', 'BINARY')
> 
> Is this the issue?

@giumas yes, this is definitely an issue. It should be there only once, as `BINARY`. Thanks for debugging.

**Comment by matysek** [comment] 2015-09-29 11:18
I found out that Pyinstaller is anywhere not trimming some dots in paths. I got this output:
```
22421 WARNING: One binary added with two internal names.
22421 WARNING: ('pywintypes33.dll', 'C:\\Windows\\system32\\pywintypes33.dll', 'BINARY')
22421 WARNING: was placed previously at
22421 WARNING: ('.\\pywintypes33.dll', 'C:\\Windows\\system32\\pywintypes33.dll', 'BINARY')
```

**Comment by matysek** [comment] 2015-09-29 11:44
@giumas It should be fixed. The warning should be gone.
@tallforasmurf For documentation: having both system pywin32 and pypiwin32 should not matter. But pyinstaller does not install now pypiwin32 is pywin32 is already available.

**Closed by matysek** 2015-09-29 11:44 UTC
Labels: @medium, Windows

**Comment by giumas** [comment] 2015-09-29 12:27
@matysek, I can gladly confirm that the warning is gone!

**Comment by tallforasmurf** [comment] 2015-09-29 17:51
636e334
