### ISSUE TITLE
Error loading Python DLL (error code 1114)

### ISSUE THREAD

**Issue by xiaoguang-li** [pyinstaller/pyinstaller#2542] opened 2017-04-04 23:04 UTC
I'm experiencing a problem in which the built executable is working properly on some machines but not others. I'm able to narrow down the problem to something to do with multiprocessing, but am at a loss on how to debug further.

The program that I am trying to build is basically the code from https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing and I'm building the executable with the command:
`pyinstaller -F -d recipe_code.py`

When the executable fails to run on the problematic machine, the output is:

```
PS C:\test> .\test.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\test\test.exe
LOADER: homepath is C:\test
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\test\test.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\X~1\AppData\Local\Temp\_MEI22642
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is C:\test\test.exe
LOADER: homepath is C:\test
LOADER: _MEIPASS2 is C:\Users\X~1\AppData\Local\Temp\_MEI22642
LOADER: archivename is C:\test\test.exe
LOADER: SetDllDirectory(C:\Users\X~1\AppData\Local\Temp\_MEI22642)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\X~1\AppData\Local\Temp\_MEI22642\test.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\X~1\AppData\Local\Temp\_MEI22642\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\X~1\AppData\Local\Temp\_MEI22642\base_library.zip;C:\Users\X~1\AppData\L
ocal\Temp\_MEI22642
LOADER: sys.prefix is C:\Users\X~1\AppData\Local\Temp\_MEI22642
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename test.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\X~1\AppData\Local\Temp\_MEI22642\base_library.zip;C:\Users\X~1\AppData\
Local\Temp\_MEI22642
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running test.py
main
main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
PyInstaller Bootloader 3.x
LOADER: executable is C:\test\test.exe
LOADER: homepath is C:\test
LOADER: _MEIPASS2 is C:\Users\X~1\AppData\Local\Temp\_MEI22642
LOADER: archivename is C:\test\test.exe
LOADER: SetDllDirectory(C:\Users\X~1\AppData\Local\Temp\_MEI22642)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\X~1\AppData\Local\Temp\_MEI22642\test.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\X~1\AppData\Local\Temp\_MEI22642\python35.dll
Error loading Python DLL: C:\Users\X~1\AppData\Local\Temp\_MEI22642\python35.dll (error code 1114)
LOADER: Back to parent (RC: 0)
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\test\test.exe
```

The built executable works successfully on a Windows 10 PRO machine and 2 different Windows Server 2012 machines with different hardware.

The failing machine is running on Windows 7 Enterprise 64bit. Please let me know what kind of information would be helpful in debugging this. I've read the guideline on reporting bugs, but since the built executable works on some machines, I'm not sure if they are helpful in this case.

The machine that I used to build the executable is running on Windows Server 2012 with Python 3.5.2 and PyInstaller 3.2.1.

Thank you.

**Comment by xoviat** [comment] 2017-04-05 01:48
Duplicate #1566.

**Comment by htgoebel** [comment] 2017-04-05 07:28
@xoviat Not sure about this being a duplicate: The error number differs.

**Comment by xiaoguang-li** [comment] 2017-04-05 14:09
@xoviat I had indeed ran into some of the same issues that were repeated in #1566 earlier. I had installed the following 2 patches on the Windows 7 machine, but the error code that I reported happens even with those 2 patches installed.

https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows
https://www.microsoft.com/en-gb/download/details.aspx?id=48145

**Comment by xoviat** [comment] 2017-04-05 15:04
Well, maybe not then. The easiest way would probably be to build the executable on win7, and if that executable works, compare the results.

**Comment by xiaoguang-li** [comment] 2017-04-05 21:27
@xoviat I duplicated my setup on a Windows 7 virtual machine and confirmed that the built executable from this virtual machine runs fine on the Windows 7 machine that previously was failing. I can try to compare the built executable and hopefully help to find a fix. What kind of data and comparison would you like to see?

**Comment by xoviat** [comment] 2017-04-05 23:16
The executable should be the same. You're looking for the following:

Differences between the Python Dlls.
Differences between the libraries that the Dlls load. You can procmon the process and look after the Python Dlls is loaded to find that out.

Always debug in Onedir mode.

**Comment by altendky** [comment] 2017-07-11 15:07
I did a bit of a hacky comparison since I'm getting the same error for Windows 7.  [My project](/altendky/st) is being [built on AppVeyor](https://ci.appveyor.com/project/KyleAltendorf/st/build/v0.1.post176%20b84) and has installed fine for several people on Windows 10.  A Windows 7 install yesterday resulted in the 1114 error which I recreated in a fresh Windows 7 virtual machine.  I manually built just the PyInstaller part of my project (on AppVeyor it also builds a Qt IFW installer) and compared the two directories.  GitHub doesn't want me to upload the two 30MB zip files but I can share them elsewhere if desired.  The specific file that I had to copy from my win7 build into my AppVeyor build was `api-ms-win-core-synch-l1-2-0.dll` (There was also 1-1-0 but that didn't cause trouble).  The file existed in both cases but as with all the `api-*` files they were different.

[pyinstaller_issue_2542.zip](https://github.com/pyinstaller/pyinstaller/files/1139323/pyinstaller_issue_2542.zip)

**Comment by altendky** [comment] 2017-07-11 15:11
I'll note that I am using Python 3.6.1 and when I started with PyInstaller this was not supported in a release yet.  My builds are presently pegged to 964547cd92cabe28150d52c2ca809de74a5ddbaa.

**Comment by jeremysanders** [comment] 2017-08-19 07:02
I upgraded from pyinstaller 3.2.1 to the latest github version (https://github.com/pyinstaller/pyinstaller/commit/f0df2d2bb10babd4a8df4f2f5df7b8e05f999969).

This fixed the error code 1114 for me. It did break the detection of the PyQt5 plugins for me though.

**Comment by htgoebel** [comment] 2017-09-12 09:57
> The specific file that I had to copy from my win7 build into my AppVeyor build was api-ms-win-core-synch-l1-2-0.dll

So this is Duplicate of #1566

**Closed by htgoebel** 2017-09-12 09:57 UTC

**Comment by altendky** [comment] 2017-09-12 12:52
@htgoebel If #1566 covers building on Windows Server 2012 R2 ([AppVeyor](https://www.appveyor.com/docs/build-environment/#operating-system)) with Python 3.6 and deploying to Win 7 without getting any related warnings, then very possibly.  Also, the file (`api-ms-win-core-synch-l1-2-0.dll`) wasn't missing from the AppVeyor build, it was just different than the Win7 build whose copy makes the AppVeyor build work on Win7.

These are the only warnings I got in a build that needed to be 'patched' after install on Win7.

https://ci.appveyor.com/project/KyleAltendorf/st/build/v0.1.post200%20b108#L195
```
27439 WARNING: library canlib32 required via ctypes not found
27454 WARNING: library usb2can.dll required via ctypes not found
```

I started to try more recent versions than 964547cd92cabe28150d52c2ca809de74a5ddbaa but they failed in various ways that I haven't debugged yet.

I'm not challenging this being a duplicate, just want to make sure these points are clearly considered as they seemed a bit different than a quick read over #1566.

**Comment by htgoebel** [comment] 2017-09-12 14:44
@altendky `api-ms-win-core-synch-l1-2-0.dll` is part of the Universal CRT. Please read [Distributing Software that uses the Universal CRT](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/), numbers 1, 2, 3 and 6. Thus I'm quite confident it is a duplicate.

If you think it is not a duplicate, you need to provide more details and even a pull-request, since we do not have the time to investigate vague errors, esp. on Windows.

**Comment by altendky** [comment] 2017-09-12 21:14
@htgoebel just wanted to make those points directly.  Given that you are still confident, that's good enough for me.  Thanks for the time and tool.
