### ISSUE TITLE
[proposed area:bootloader platform:OS X] Mac OS X Malformed Info.plist

### ISSUE THREAD

**Issue by mwfong-csl** [pyinstaller/pyinstaller#5442] opened 2021-01-03 19:23 UTC
A Mac OS X application built with PyInstaller 4.1 `--onedir` and `--windowed` contains a malformed Info.plist.  When the application runs, `system.log` displays
```
1/3/21 9:34:56.244 AM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.<app>.<pid>) Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable
```

This is caused by the value of `CFBundleExecutable` having the prefix `MacOS/`, which is introduced by `PyInstaller/building/osx.py:BUNDLE.assemble ()`:
```
        # Key/values for a minimal Info.plist file
        info_plist_dict = {"CFBundleDisplayName": self.appname,
                           "CFBundleName": self.appname,
                             :
                             :
                           # Fix for #156 - 'MacOS' must be in the name - not sure why
                           "CFBundleExecutable": 'MacOS/%s' % os.path.basename(self.exename),
                             :
                             :
                           }
```
The `info_plist_dict` `CFBundleExecutable` entry should instead be
```
                           "CFBundleExecutable": os.path.basename(self.exename),
```
---
Non sequitur: `bootloader/src/pyi_utils.c:pyi_utils_create_child ()` has
```
    #if defined(__APPLE__) && defined(WINDOWED)

        /* if we are on a Mac, it passes a strange -psnxxx argument.  Filter it out. */
        if (strstr(argv[i], "-psn") == argv[i]) {
            /* skip */
        }
        else
    #endif
```
https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder explains this command line argument; it might be worthwhile to add this URL to the comment.

**Comment by mwfong-csl** [comment] 2021-01-06 02:14
I agree that there's mismatch between the ticket's description/title and its code mod, of which the latter does _not_ `fix doc icon on OS X.`  I, too, do not understand the rationale behind this mod.

**Comment by bwoodsend** [comment] 2021-01-06 02:31
I've found the [correct issue](https://github.com/pyinstaller/pyinstaller/issues/1061#issuecomment-59618120). On reading through it I'm really not convinced it was a good fix. I notice #4413 is a duplicate of this one and comes to the same conclusion. @BoboTiG, I see you're involved in 4413. Reverting 6b99e01 sound sensible to you?

**Comment by BoboTiG** [comment] 2021-01-06 10:57
@mwfong-csl could you share the `.app` that throws the error about "taint = missing executable"?

**Comment by mwfong-csl** [comment] 2021-01-06 20:46
@BoboTiG [Attached](https://github.com/pyinstaller/pyinstaller/files/5778088/FFView.zip) is a smaller (and publicly available) Mac app.  With the `console` application running, open and then quit `FFView`; `system.log` will show no errors.  Then replace `FFView.app/Contents/Info.plist` with `FFView.app/Contents/Info.plist.bad` and re-open `FFView`; `console` will display
```
[...] com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.FFView.<pid>) Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable
```
As I previously mentioned, the input `.spec` isn't the issue — the problem is `PyInstaller/building/osx.py:BUNDLE.assemble ()`'s  extraneous addition of `MacOS/` to `CFBundleExecutable`.

**Comment by BoboTiG** [comment] 2021-01-06 20:54
This is not what you told at the beginning. Here, you are manually deleting the Info.plist file (renaming it is the same from the OS POV). And then there will be an error, obviously.

I am not sure of the issue then, could you tell me more? I will be able to have a deeper look at the app tomorrow (French timezone).

**Comment by mwfong-csl** [comment] 2021-01-06 21:34
`Info.plist.bad` is equivalent to what `PyInstaller` is generating.  As noted above, I overcame this by patching `PyInstaller/building/osx.py:BUNDLE.assemble ()` to _not_ prepend `MacOS/` to `CFBundleExecutable` (see [here](https://github.com/pyinstaller/pyinstaller/files/5778273/osx-fixed.zip)).

**Comment by rokm** [comment] 2021-06-16 09:33
FWIW, I have not managed to reproduce the `Could not resolve origin of domain...` message. 

However, having `MacOS/` prefix in `CFBundleExecutable` does seem wrong, so I think we should revert 6b99e01. Whatever issue this is really masking (if it is still relevant at all; the original issue #1061 was reported with Qt4/PyQt), it should be brought out and properly dealt with.

**Comment by rokm** [comment] 2021-07-07 08:20
I've reproduced the `Could not resolve origin of domain...` message now. This seems to affect macOS 10.14 Mojave, but not later versions (perhaps later versions of macOS determine the basename of `CFBundleExecutable` instead of taking it as-is).

**Closed** 2021-07-07 10:54 UTC
