### ISSUE TITLE
The exe file doesnt execute or gives an error. It just gives this warning. 

### ISSUE THREAD

**Issue by Nee-DS** [pyinstaller/pyinstaller#7743] opened 2023-06-28 16:40 UTC
C:\Projects\FastApiBert_exe\dist>Predict_BERT.exe
[12152] WARNING: file already exists but should not: C:\Users\3592157\AppData\Local\Temp\1\_MEI121522\torch\_C.cp39-win_amd64.pyd
[12152] WARNING: file already exists but should not: C:\Users\3592157\AppData\Local\Temp\1\_MEI121522\torch\_C_flatbuffer.cp39-win_amd64.pyd
2023-06-28 09:38:03.111948: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-06-28 09:38:03.118536: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.

C:\Projects\FastApiBert_exe\dist>

**Comment by Nee-DS** [comment] 2023-06-28 16:42
Kindly let me know, what is missing. Thanks

**Comment by rokm** [comment] 2023-06-29 07:31
Have you ensured that source .py files for `transformers` are collected? PyInstaller does not collect those, but they are usually required by `torch` and `tensorflow` JIT compilation.

That's pretty much all we can say based on the (lack of) information you provided...

> [12152] WARNING: file already exists but should not: C:\Users\3592157\AppData\Local\Temp\1_MEI121522\torch_C.cp39-win_amd64.pyd
> [12152] WARNING: file already exists but should not: C:\Users\3592157\AppData\Local\Temp\1_MEI121522\torch_C_flatbuffer.cp39-win_amd64.pyd

What version of PyInstaller are you using? This sort of duplication should be fixed since v5.7.0...

**Comment by Nee-DS** [comment] 2023-06-29 17:28
**I updated the Pyinstaller to 5.12.0 and have Python 3.9.2

Here is the Spec file where I have collected transformer modules:**  

import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)
from PyInstaller.utils.hooks import copy_metadata


datas = []
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('requests')
datas += copy_metadata('sacremoses')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
datas += copy_metadata('importlib_metadata')
datas += copy_metadata('tensorflow')


block_cipher = None


a = Analysis(
    ['Predict_BERT.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=['bertopic'],
    hookspath=['extra-hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Predict_BERT',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='ico\\example.ico',
)

**I am still getting the error below**

2023-06-29 10:19:58.010102: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-06-29 10:19:58.017504: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
Traceback (most recent call last):
  File "Predict_BERT.py", line 34, in <module>
  File "joblib\numpy_pickle.py", line 648, in load
  File "joblib\numpy_pickle.py", line 577, in _unpickle
  File "pickle.py", line 1212, in load
  File "pickle.py", line 1537, in load_stack_global
  File "pickle.py", line 1579, in find_class
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "transformers\models\bert\modeling_bert.py", line 42, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "transformers\modeling_utils.py", line 41, in <module>
ImportError: cannot import name 'GenerationMixin' from 'transformers.generation' (C:\Users\3592157\AppData\Local\Temp\1\_MEI22202\transformers\generation\__init__.pyc)
[3816] Failed to execute script 'Predict_BERT' due to unhandled exception!

**Comment by bwoodsend** [comment] 2023-06-29 17:33
But what is your code doing? Can you give us a reproducible example? Without that you're on your own. The contents of a semiautomatically generated spec file tell us nothing other than that your environment is big and that you've ignored [Rok's advice](https://github.com/pyinstaller/pyinstaller/issues/7743#issuecomment-1612553531).

**Comment by Nee-DS** [comment] 2023-06-29 18:49
The Python code launches a FASTApi and uses the trained model in pickle file format to give the model result of the input data.

**Comment by bwoodsend** [comment] 2023-06-29 19:00
Ughh, forget it.

**Closed as not planned by bwoodsend** 2023-06-29 19:00 UTC
Labels: solution:not enough info

**Comment by Nee-DS** [comment] 2023-06-30 07:19
Hi, attached is the Python file I am trying to convert to exe. Could you consider reopening the issue? Thanks
[Predict_BERT.zip](https://github.com/pyinstaller/pyinstaller/files/11913970/Predict_BERT.zip)

**Comment by rokm** [comment] 2023-06-30 10:12
>  Could you consider reopening the issue?

This is a bug/issue tracker, not support forum. And you trying to package a complex deep learning framework without understanding how things work is your problem, not ours.

> Here is the Spec file where I have collected transformer modules:

You are not collecting `transformers` modules - you are collecting just metadata for various packages. 

But you probably should also explicitly collect `transformers` modules (see [`collect_submodules`](https://pyinstaller.org/en/stable/hooks.html#PyInstaller.utils.hooks.collect_submodules)), because there is a lot of lazy loading going on in `transformers`, which cannot be analyzed by our import analysis, and therefore such lazily-loaded modules end up missing.

**Comment by Nee-DS** [comment] 2023-07-12 23:35
I was finally successful in converting a complex deep-learning Python file including a pickle file to an exe with Pyinstaller.
Lesson learned: 

- Need a GPU to run this complex py file
- make sure to rap all Transformers models or any models having submodules

Thanks
