### ISSUE TITLE
two sets of Qt binaries on OSX [PySide]

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#714] opened 2014-10-18 14:38 UTC
**Original date**: 2013/05/01
**Original reporter**: *bootch AND nc DOT rr DOT  COOM *

I am using the dev version of Pyinstaller on Mac OSX (developing on Linux, also using Pyinstaller there.)

When my app runs and it needs QtSvg (is that a plugin?) I get many warnings "..you may have two sets of Qt binaries.."

I export DYLD_PRINT_LIBRARIES=1 and indeed, two sets of Qt binaries are loaded.

I have also tried the --windowed flag and that does not solve it.

I will assume it is not harmful.  (My program is crashing but I haven't explored where yet, and it may be unrelated.)

I am reporting this because a web search seems to indicate it should already be fixed, and there is one open StackOverflow question about  this.

**Comment by matysek** [comment] 2015-01-01 12:13
I think this is caused by missing hooks for pyside. This is duplicate of #299.

**Closed by matysek** 2015-01-01 12:13 UTC
Labels: OS X, support, v2.0
