### ISSUE TITLE
An error occurred while updating to version 4.1

### ISSUE THREAD

**Issue by designinlife** [pyinstaller/pyinstaller#5328] opened 2020-11-18 13:41 UTC
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: ```3.9.0```
* Platform: ```CentOS Linux release 7.6.1810 (Core)``` ```Kernel 4.4.177-1.el7.elrepo.x86_64```
* pip: ```20.2.4```
* setuptools: ```50.3.2```
* wheel: ```0.35.1```
* Did you also try this on another platform? Does it work there? (```No```)

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
pip install -U pyinstaller
Collecting pyinstaller
  Downloading pyinstaller-4.1.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 674 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/dgame/python39/bin/python3.9 /usr/local/dgame/python39/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpu4jrdunj
         cwd: /tmp/pip-install-12m2t8rh/pyinstaller
    Complete output (37 lines):
    running dist_info
    creating /tmp/pip-modern-metadata-05n8y2hg/pyinstaller.egg-info
    writing /tmp/pip-modern-metadata-05n8y2hg/pyinstaller.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-05n8y2hg/pyinstaller.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-modern-metadata-05n8y2hg/pyinstaller.egg-info/entry_points.txt
    writing requirements to /tmp/pip-modern-metadata-05n8y2hg/pyinstaller.egg-info/requires.txt
    writing top-level names to /tmp/pip-modern-metadata-05n8y2hg/pyinstaller.egg-info/top_level.txt
    Traceback (most recent call last):
      File "/usr/local/dgame/python39/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/dgame/python39/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/dgame/python39/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-bqbooyb3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-bqbooyb3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-bqbooyb3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 75, in <module>
        setup(
      File "/tmp/pip-build-env-bqbooyb3/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/dgame/python39/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/dgame/python39/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/dgame/python39/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-bqbooyb3/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/tmp/pip-build-env-bqbooyb3/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 290, in run
        writer = ep.resolve()
      File "/usr/local/dgame/python39/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2453, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ModuleNotFoundError: No module named 'pbr'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/dgame/python39/bin/python3.9 /usr/local/dgame/python39/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpu4jrdunj Check the logs for full command output.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment] 2020-11-18 17:43
You know, there's absolutely no point using the issue template if you're not going to fill it in...

Can we have your OS, Python version and versions of pip, setuptools and wheel please?

**Comment by designinlife** [comment] 2020-11-19 00:18
> You know, there's absolutely no point using the issue template if you're not going to fill it in...
> 
> Can we have your OS, Python version and versions of pip, setuptools and wheel please?

Sorry, information has been added!

**Comment by bwoodsend** [comment] 2020-11-19 10:01
I can't reproduce the issue. Just googling around it appears to be a general issue with pip. Just `git grep`-ing through PyInstaller's code I see there's no mention of pbr anywhere. Do you have this pbr installed? Is there an old .egg for it hiding in `sys.path`?

I don't think I've ever gleamed anything useful from looking at pip logs but could you also:
```shell
pip uninstall PyInstaller
pip install -v PyInstaller > log.txt 2>&1
```
then upload the `log.txt` file generated.

**Comment by BoboTiG** [comment] 2020-11-19 10:39
And maybe `pip install -U pip` would be useful too.

**Comment by bwoodsend** [comment] 2020-11-19 12:53
Speaking of pip actually you forgot to tell us your pip version...

**Comment by designinlife** [comment] 2020-11-19 13:57
> Speaking of pip actually you forgot to tell us your pip version...

* pip version: ```20.2.4```

**Comment by bwoodsend** [comment] 2020-11-19 15:42
Could you try temporarly uninstalling `pbr` - bit of a long shot?

**Comment by designinlife** [comment] 2020-11-19 15:44
Okay, let me try it and get back to you.

**Comment by designinlife** [comment] 2020-11-20 01:36
> Could you try temporarly uninstalling `pbr` - bit of a long shot?

After I uninstalled the pbr package, just reinstall PyInstaller!

**Comment by bwoodsend** [comment] 2020-11-20 08:48
Hmm, not sure what to make of that. It sounds like pbr is somehow preventing sdists from building although how it even gets itself involved is a mystery to me. I'll close this for now as it doesn't seem to be PyInstaller. If, on reinstalling pbr, you find other packages you can't install I suggest you raise an issue with pbr.

**Closed by bwoodsend** 2020-11-20 08:48 UTC

**Comment by designinlife** [comment] 2020-11-20 09:20
Okay, thanks!
