### ISSUE TITLE
ImportError: No module named 'setuptools._vendor'

### ISSUE THREAD

**Issue by djl197** [pyinstaller/pyinstaller#3806] opened 2018-10-15 09:16 UTC
I am having issues packaging my application.
I am building on a Centos Machine:
I have the latest setuptools (40.0.x) - I have installed six (similar to issues here #3507, #3523 )

However I am still getting the following error on packaging the application:
```[config container] [91m144 INFO: PyInstaller: 3.5.dev0+0b6f1ec6f
[config container] 144 INFO: Python: 3.4.6
[config container] [0m[91m145 INFO: Platform: Linux-4.4.0-134-generic-x86_64-with-centos-7.5.1804-Core
[config container] [0m[91m146 INFO: UPX is not available.
[config container] [0m[91m149 INFO: Extending PYTHONPATH with paths
[config container] ['/app/image/pyinstaller/build/app-name',
[config container]  '/opt/company_name/data-processing-config/lib/python3.4/site-packages',
[config container]  '/opt/company_name/data-processing-config/bin',
[config container]  '/opt/company_name/data-processing-config/lib/python3.4/site-packages']
[config container] 149 INFO: checking Analysis
[config container] 149 INFO: Building Analysis because Analysis-00.toc is non existent
[config container] 149 INFO: Initializing module dependency graph...
[config container] 151 INFO: Initializing module graph hooks...
[config container] 152 INFO: Analyzing base_library.zip ...
[config container] [0m[91m4034 INFO: running Analysis Analysis-00.toc
[config container] [0m[91m4044 INFO: Caching module hooks...
[config container] [0m[91m4047 INFO: Analyzing /app/image/pyinstaller/build/app-name/company.a.b.app-script.py
[config container] [0m[91m10874 INFO: Processing pre-find module path hook   site
[config container] [0m[91m10875 INFO: site: retargeting to fake-dir '/usr/lib/python3.4/site-packages/PyInstaller/fake-modules'
[config container] [0m[91m11056 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
[config container] [0m[91mTraceback (most recent call last):
[config container]   File "<string>", line 2, in <module>
[config container] ImportError: No module named 'setuptools._vendor'
[config container] entry_point= app-name = company.a.b.app:main
[config container]     entry_point.dist= app-name 10.1.0
[config container] Boom: entry_point.dist.location= /opt/company_name/data-processing-config/lib/python3.4/site-packages
[config container] creating script for entry point app-name console_scripts company.a.b.app
[config container] [91mTraceback (most recent call last):
[config container]   File "/usr/bin/pyinstaller", line 11, in <module>
[config container]     load_entry_point('PyInstaller==3.5.dev0+0b6f1ec6f', 'console_scripts', 'pyinstaller')()
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/__main__.py", line 111, in run
[config container]     run_build(pyi_config, spec_file, **vars(args))
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/__main__.py", line 63, in run_build
[config container]     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 838, in main
[config container]     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 784, in build
[config container]     exec(text, spec_namespace)
[config container]   File "<string>", line 116, in <module>
[config container]   File "<string>", line 112, in Entrypoint
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 241, in __init__
[config container]     self.__postinit__()
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
[config container]     self.assemble()
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 443, in assemble
[config container]     priority_scripts.append(self.graph.run_script(script))
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 201, in run_script
[config container]     self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1348, in run_script
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1422, in import_hook
[config container]     target_module = self._load_tail(target_package, target_module_partname)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1635, in _load_tail
[config container]     submodule = self._safe_import_module(head, mname, submodule)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1422, in import_hook
[config container]     target_module = self._load_tail(target_package, target_module_partname)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1635, in _load_tail
[config container]     submodule = self._safe_import_module(head, mname, submodule)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2417, in _safe_import_hook
[config container]     edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1438, in import_hook
[config container]     target_module, target_attr_names):
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1726, in _import_importable_package_submodules
[config container]     attr_name, submodule_name, package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1422, in import_hook
[config container]     target_module = self._load_tail(target_package, target_module_partname)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1635, in _load_tail
[config container]     submodule = self._safe_import_module(head, mname, submodule)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1421, in import_hook
[config container]     source_package, target_module_partname, level)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1573, in _find_head_package
[config container]     target_module_headname, target_package_name, source_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container] [0m[91m    self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1421, in import_hook
[config container]     source_package, target_module_partname, level)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1573, in _find_head_package
[config container]     target_module_headname, target_package_name, source_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2028, in _load_module
[config container]     m = self._load_package(fqname, pathname, packagepath)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2813, in _load_package
[config container]     self._load_module(fqname, fp, buf, stuff)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1422, in import_hook
[config container]     target_module = self._load_tail(target_package, target_module_partname)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1635, in _load_tail
[config container]     submodule = self._safe_import_module(head, mname, submodule)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2417, in _safe_import_hook
[config container]     edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1438, in import_hook
[config container]     target_module, target_attr_names):
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1726, in _import_importable_package_submodules
[config container]     attr_name, submodule_name, package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1421, in import_hook
[config container]     source_package, target_module_partname, level)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1573, in _find_head_package
[config container]     target_module_headname, target_package_name, source_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2028, in _load_module
[config container]     m = self._load_package(fqname, pathname, packagepath)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2813, in _load_package
[config container]     self._load_module(fqname, fp, buf, stuff)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1422, in import_hook
[config container]     target_module = self._load_tail(target_package, target_module_partname)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1635, in _load_tail
[config container]     submodule = self._safe_import_module(head, mname, submodule)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
[config container]     module_basename, module_name, parent_package)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1990, in _safe_import_module
[config container]     module_name, file_handle, pathname, metadata)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2082, in _load_module
[config container]     self._scan_code(m, co, co_ast)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2544, in _scan_code
[config container]     self._process_imports(module)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2743, in _process_imports
[config container]     target_module = self._safe_import_hook(*import_info, **kwargs)[0]
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2221, in _safe_import_hook
[config container]     target_attr_names=None, level=level, edge_attr=edge_attr)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1422, in import_hook
[config container]     target_module = self._load_tail(target_package, target_module_partname)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1635, in _load_tail
[config container]     submodule = self._safe_import_module(head, mname, submodule)[0m[91m
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/depend/analysis.py", line 260, in _safe_import_module
[config container]     hook_module.pre_safe_import_module(hook_api)
[config container]   File "/usr/lib/python3.4/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-setuptools.extern.six.moves.py", line 34, in pre_safe_import_module
[config container]     for real_module_name, six_module_name in real_to_six_module_name.items():
[config container] AttributeError: 'str' object has no attribute 'items'```

Any help, ideas or things to try would be really appreciated.

**Comment by htgoebel** [comment] 2018-10-16 07:19
The error message is 
```
AttributeError: 'str' object has no attribute 'items'```
```

Why did you title this issue with "ImportError: No module named 'setuptools._vendor'"

**Comment by djl197** [comment] 2018-10-16 08:03
> The error message is
> 
> ```
> AttributeError: 'str' object has no attribute 'items'```
> ```
> Why did you title this issue with "ImportError: No module named 'setuptools._vendor'"

The first error I could see in this output was from this hook
```Processing pre-safe import module hook   setuptools.extern.six.moves``` which appeared to give the ImportError.  I could see the hook had specific logic depending on the version of Setuptools and I was wondering if this was working as expected, or if something I had done was triggering the failure.

I believed - perhaps mistakenly that removing this error would resolve the later AttributeError.

**Comment by htgoebel** [comment] 2018-10-19 22:13
Thanks you very much for this report and pointing to originating error message. In the last months there have been several reports about the AttributeError, but nobody spotted the ImportError.

I just pushed a fix for this 0ffa574bf87e2e37b0df2a4e2d60cb616f9ff2f2, which not only solves the import error, but also terminated the program without the outer trace back. This should eas spotting the root cause much more easy.

**Closed by htgoebel** 2018-10-19 22:13 UTC

**Comment by djl197** [comment] 2018-10-24 13:14
The dev build has worked great and fixed by issues.  
I now have a single binary (which is distributed using setuptools) - Great work and much appreciated.
My containers can shrink a lot more now :-)

**Comment by adamtheturtle** [comment] 2019-04-10 10:01
Thank you for the fix @htgoebel . Is there any chance of a release soon which could contain this fix?
