### ISSUE TITLE
Pyinstaller on MacOs (bigsur) with pyqtwebengine (pyqt5)

### ISSUE THREAD

**Issue by Coincoin35** [pyinstaller/pyinstaller#7245] opened 2022-11-15 08:30 UTC
I'm trying to package into an app a python+pyqt5 code using the pyqtwebengine from pyqt5 (last one using python3.11) in a fresh and uptodate (using pip) virtualenv. The code works when run directly. It opens a window showing exclusively a pdf.

I run pynsintaller that creates an app.
# When launched, the app returns the following error: 
```
Qt WebEngine resources not found at . Trying parent directory...
Qt WebEngine resources not found at /var/folders/9w/qshd1vqn4yndchg_979rs4wh0000gn/T/_MEIcXtcqb/PyQt5/Qt5. Trying application directory...
Qt WebEngine resources not found at /Users/solsto/Desktop/GenAPoPop compilation. Trying fallback directory... The application MAY NOT work.
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /Users/solsto/Desktop/GenAPoPop compilation/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[1115/090340.526552:ERROR:icu_util.cc(251)] Couldn't mmap icu data file
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

# A potential issue?
Searching on the web about the error "ERROR:icu_util.cc(251)] Couldn't mmap icu data file", I found on homebrew git the following modification that seems to have to be applied to macos in a different way than for linux.
https://github.com/Homebrew/homebrew-core/issues/104008
The error would come from QT_FEATURE_webengine_system_icu=ON

The toy code to reproduce the error (a simple pdf viewr in a window to display a documentatation in a folder name "res" conatining "doc.pdf" as the documentation):
```python
import pathlib, os,time,sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QScrollArea,QApplication,QMainWindow,QFormLayout,QGridLayout,QHBoxLayout,QRadioButton,QCheckBox,QLineEdit,QWidget,QComboBox,QSlider,QRadioButton, QFrame,QFileDialog, QTextEdit, QPushButton, QLabel, QVBoxLayout,QFormLayout,QTabWidget,QToolTip, QMessageBox)
from PyQt5.QtCore import Qt,QDir,QUrl, QRunnable, QThreadPool, QObject, pyqtSignal, pyqtSlot
from PyQt5.QtWebEngineWidgets import QWebEngineSettings, QWebEngineView

print(os.path.dirname(os.path.abspath(__file__)))
print(os.path.abspath(os.getcwd()))
print(os.path.expanduser("~"))
print(os.path.dirname(os.path.abspath(sys.argv[0])))

global CHEMIN

CHEMIN1 = os.path.dirname(os.path.abspath(__file__))
CHEMIN2 = os.path.abspath(os.getcwd())
CHEMIN3 = os.path.expanduser("~")
CHEMIN4 =os.path.dirname(os.path.abspath(sys.argv[0]))


print("1",CHEMIN1)
print("2",CHEMIN2)
print("3",CHEMIN3)
print("4", CHEMIN4)

CHEMIN = CHEMIN1

class PDFWindow(QWidget):
    """
    This "window" is a QWidget. If it has no parent, it
    will appear as a free-floating window as we want.
    """
    def __init__(self):
        super().__init__()     
        layout = QVBoxLayout()
        self.setWindowTitle("PDF Viewer")
        self.setGeometry(0, 28, 1000, 750)
        self.webView = QWebEngineView()
        self.webView.settings().setAttribute(QWebEngineSettings.PluginsEnabled, True)
        self.webView.settings().setAttribute(QWebEngineSettings.PdfViewerEnabled, True)
        layout.addWidget(self.webView)
        self.setLayout(layout)
        a = pathlib.Path(CHEMIN)
        a = a / "res" / "doc.pdf"
        cheminloc = a.as_uri()
        self.webView.setUrl(QUrl( cheminloc   ))
 
    def url_changed(self):
        self.setWindowTitle(self.webView.title())
 
    def go_back(self):
        self.webView.back()



class MainWindow(QMainWindow):#QTabWidget):
   def __init__(self, parent = None):
      super().__init__()
      self.setGeometry(100,100, 1280,900)
      self.setWindowIcon(QtGui.QIcon("res/logo_s.png"))

      self.tabs = QTabWidget()
      self.tab1 = QWidget()
      self.scrollbar1 = QScrollArea(widgetResizable=True)
      self.scrollbar1.setWidget(self.tab1)

      self.windoc = None  # No external window yet.

      self.it1 = self.tabs.addTab(self.scrollbar1 ,"Presentation")
      self.setCentralWidget(self.tabs)
      self.setWindowTitle("test")
      self.couverture()
      
   def couverture(self):
      logo = QLabel()
      logo.setPixmap(QtGui.QPixmap(os.path.join(CHEMIN, 'res',"logo_s.png")))
      logo.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
      
      buttondoc = QPushButton('Read documentation')
      buttondoc .adjustSize()
      buttondoc.clicked.connect(self.show_new_window)

      layout = QFormLayout()
      layout.addWidget(logo)
      layout.addWidget(buttondoc)
      self.tab1.setLayout(layout)
      
   def show_new_window(self, checked):
      if self.windoc is None:
          self.windoc = PDFWindow()
          self.windoc.show()
      else:
          self.windoc.close()  # Close window.
          self.windoc = None  # Discard reference.


def main():
   app = QApplication(['', '--no-sandbox'])
   app.setStyle('Fusion')
   window = MainWindow()
   window.show()
   sys.exit(app.exec_())

if __name__ == '__main__':
   main()
```

Python package versions used that generated the error:
virtualenv                20.16.7
PyQt5                     5.15.7
PyQt5-sip                 12.11.0
PyQtWebEngine             5.15.6
pyinstaller               5.6.2
pyinstaller-hooks-contrib 2022.13

**Comment by rokm** [comment] 2022-11-15 08:35
QtWebEngine does not work with PyInstaller in `onefile` mode on macOS (see [here](https://github.com/pyinstaller/pyinstaller/blob/f6eea916adbaa205c57c04daaf7cfebfc3b21fe0/PyInstaller/utils/hooks/qt.py#L773-L797) for details) - you'll have to use `onedir` mode.

**Comment by rokm** [comment] 2022-11-15 10:05
I'm marking this as duplicate of #4361. It will be resolved once I get around to implementing symlink support and we can stop butchering those Qt .framework bundles.

**Closed as not planned** 2022-11-15 10:06 UTC
Labels: solution:duplicate
