### ISSUE TITLE
PyInstaller icon option doesn't work on Mac

### ISSUE THREAD

**Issue by taichi-suzuki-pckg** [pyinstaller/pyinstaller#4944] opened 2020-06-18 19:49 UTC
I ran the following command on my mac and created an .app file.

`pyinstaller --icon icon.icns --noconsole -n testApp main.py
`

However, the generated .app file does not show the icon.
icon.icns is specified as an icon file in info.plist.
The Content/Resouces folder contains icon.icns.

When I run the .app file, I see an icon on the Dock.

However, the icon is not reflected in the .app file itself. Why is this?
On Windows, when the .exe file was output by pyinstaller, the icon was reflected without problems.

I posted the same question on [StackOverflow ](https://stackoverflow.com/questions/62451711/pyinstaller-icon-option-doesnt-work-on-mac)with images.

**Comment by Legorooj** [comment] 2020-06-23 03:35
Not sure what the problem is here so I've started a bounty on the SO question. We don't have any macOS developers unfortunately.

**Comment by Legorooj** [comment] 2020-07-21 08:37
Oops I forgot to close this.

**Closed by Legorooj** 2020-07-21 08:37 UTC
Labels: kind:support, platform:OS X
