### ISSUE TITLE
Missing api-ms-win-crt-runtime-l1-1-0.dll 

### ISSUE THREAD

**Issue by ansonl** [pyinstaller/pyinstaller#1588] opened 2015-10-08 12:35 UTC
The Pyinstaller [feature](https://github.com/pyinstaller/pyinstaller/wiki/Features) page mentions
> Full automatic support for CRTs: no need to manually distribute MSVCR*.DLL, redist installers, manifests, or anything else; true one-file applications that work everywhere!

When I create an executable and run it on another computer with Windows 7, I get an error about a missing api-ms-win-crt-runtime-l1-1-0.dll . I don't have the rights to install the VC Redistributable to this computer. 
![image](https://cloud.githubusercontent.com/assets/546458/10366137/5277c1ca-6d96-11e5-80f6-968568ba7c5c.png)

I thought that the Pyinstaller feature page meant that the required DLLs would be included with the produced executable. Am I doing something wrong? Thanks. 

Th executable is being created with the command `pyinstaller --onefile --noconsole --clean file.py`.

**Comment by codewarrior0** [comment] 2015-10-08 12:48
OS version? Python version?

**Comment by ansonl** [comment] 2015-10-08 13:48
Both build and target computers are running Win7 SP1. Build computer has python 3.5.

Build cmd output is below:
```
C:\Users\m163876\Desktop>pyinstaller --onefile --noconsole --clean notes.py
171 INFO: PyInstaller: 3.0
171 INFO: Python: 3.5.0
171 INFO: Platform: Windows-7-6.1.7601-SP1
171 INFO: wrote C:\Users\m163876\Desktop\notes.spec
171 INFO: UPX is not available.
171 INFO: Removing temporary files and cleaning cache in C:\Users\m163876\AppDat
a\Roaming\pyinstaller
218 INFO: Extending PYTHONPATH with C:\Users\m163876\Desktop
218 INFO: checking Analysis
218 INFO: Building Analysis because out00-Analysis.toc is non existent
218 INFO: Initializing module dependency graph...
234 INFO: Initializing module graph hooks...
234 INFO: Analyzing base_library.zip ...
3247 INFO: running Analysis out00-Analysis.toc
4168 INFO: Analyzing C:\Users\m163876\Desktop\notes.py
5994 INFO: Looking for import hooks ...
6010 INFO: Processing hook   hook-_tkinter.py
6275 INFO: checking Tree
6275 INFO: Building Tree because out00-Tree.toc is non existent
6275 INFO: Building Tree out00-Tree.toc
6462 INFO: checking Tree
6462 INFO: Building Tree because out01-Tree.toc is non existent
6462 INFO: Building Tree out01-Tree.toc
6494 INFO: Processing hook   hook-encodings.py
6509 INFO: Processing hook   hook-xml.py
6556 INFO: Processing hook   hook-requests.py
6572 INFO: Processing hook   hook-pydoc.py
6572 INFO: Processing hook   hook-xml.sax.py
6619 INFO: Looking for ctypes DLLs
6634 INFO: Analyzing run-time hooks ...
6634 INFO: Including run-time hook 'pyi_rth__tkinter.py'
6650 INFO: Looking for dynamic libraries
8039 INFO: Looking for eggs
8039 INFO: Using Python library c:\users\m163876\appdata\local\programs\python\p
ython35-32\python35.dll
8039 INFO: Found binding redirects:
[]
8055 INFO: Warnings written to C:\Users\m163876\Desktop\build\notes\warnnotes.tx
t
8117 INFO: checking PYZ
8117 INFO: Building PYZ because out00-PYZ.toc is non existent
8117 INFO: Building PYZ (ZlibArchive) C:\Users\m163876\Desktop\build\notes\out00
-PYZ.pyz
8445 INFO: checking PKG
8445 INFO: Building PKG because out00-PKG.toc is non existent
8445 INFO: Building PKG (CArchive) out00-PKG.pkg
8570 INFO: Updating manifest in C:\Users\m163876\AppData\Roaming\pyinstaller\bin
cache00_py35_32bit\python35.dll
8570 INFO: Updating resource type 24 name 2 language 1033
9756 INFO: Updating manifest in C:\Users\m163876\AppData\Roaming\pyinstaller\bin
cache00_py35_32bit\tk86t.dll
9772 INFO: Updating resource type 24 name 1 language 1033
12301 INFO: Bootloader c:\users\m163876\appdata\local\programs\python\python35-3
2\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw.exe
12301 INFO: checking EXE
12301 INFO: Building EXE because out00-EXE.toc is non existent
12301 INFO: Building EXE from out00-EXE.toc
12395 INFO: Appending archive to EXE C:\Users\m163876\Desktop\dist\notes.exe
```

**Comment by ansonl** [comment] 2015-10-08 13:49
Currently installed pip packages
```
C:\Users\m163876\Desktop>pip list
olefile (0.42.1)
pip (7.1.2)
py2exe (0.9.2.2)
PyInstaller (3.0)
pypiwin32 (219)
PyRTF (0.45)
pyth (0.6.0)
requests (2.5.1)
setuptools (18.3.2)
```

**Comment by codewarrior0** [comment] 2015-10-08 14:37
This problem seems intractable for the moment. See https://github.com/pyinstaller/pyinstaller/issues/1566#issuecomment-146564554

As a workaround, you can recommend users on Windows Vista, 7, and 8 to install update `KB2999226` via Windows Update, or manually install the [VC 2015 Redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=48145)

**Comment by matysek** [comment] 2015-10-08 21:18
@ansonl Or preferably downgrade to Python 3.4 on the build computer if possible.

**Comment by matysek** [comment] 2015-10-09 11:29
Closing, as there were suggested some workarounds and it is duplicate of #1566.

**Closed by matysek** 2015-10-09 11:29 UTC
Labels: duplicate, support, v3.0, Windows

**Comment by beattroublemaker** [comment] 2017-08-25 08:02
Have you solve the problem?I met the same problem,it make me bad.
Can you help me?

**Comment by ryukinix** [comment] 2017-12-11 00:41
I have the same problem creating an application on Windows 10 and trying to execute on Windows 7.

**Comment by htgoebel** [comment] 2017-12-11 12:34
@ryukinix Please read the fine manual.
