### ISSUE TITLE
When you run the executable file, the process is still created.

### ISSUE THREAD

**Issue by djsc6511** [pyinstaller/pyinstaller#3713] opened 2018-09-04 07:24 UTC
- Environment
os : ubuntu
language : python 3.5

When you run the executable file, the process is still created.

kwon     18854  3963  0 16:03 pts/2    00:00:00 ./synthesizer
kwon     18855 18854 97 16:03 pts/2    00:00:22 ./synthesizer
kwon     18868 18855  0 16:03 pts/2    00:00:00 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -s -E -S -B -c from multiprocessing.semaphore_tracker import main;main(5)
kwon     18869 18868 18 16:03 pts/2    00:00:03 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -s -E -S -B -c from multiprocessing.semaphore_tracker import main;main(5)
kwon     18882 18869  0 16:03 pts/2    00:00:00 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -E -s -S -B -c from multiprocessing.semaphore_tracker import main;main(6)
kwon     18883 18882 22 16:03 pts/2    00:00:03 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -E -s -S -B -c from multiprocessing.semaphore_tracker import main;main(6)
kwon     18898 18883  0 16:03 pts/2    00:00:00 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -s -B -S -E -c from multiprocessing.semaphore_tracker import main;main(5)
kwon     18899 18898 27 16:03 pts/2    00:00:03 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -s -B -S -E -c from multiprocessing.semaphore_tracker import main;main(5)
kwon     20924 18899  0 16:03 pts/2    00:00:00 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -s -B -E -S -c from multiprocessing.semaphore_tracker import main;main(6)
kwon     20925 20924 39 16:03 pts/2    00:00:03 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -s -B -E -S -c from multiprocessing.semaphore_tracker import main;main(6)
kwon     20938 20925  0 16:03 pts/2    00:00:00 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -B -E -s -S -c from multiprocessing.semaphore_tracker import main;main(5)
kwon     20939 20938 58 16:03 pts/2    00:00:03 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -B -E -s -S -c from multiprocessing.semaphore_tracker import main;main(5)
kwon     20954 20939  0 16:03 pts/2    00:00:00 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -B -s -E -S -c from multiprocessing.semaphore_tracker import main;main(6)
kwon     20955 20954 99 16:03 pts/2    00:00:03 /home/kwon/realtime_p_tts/dist/synthesizer/synthesizer -B -s -E -S -c from multiprocessing.semaphore_tracker import main;main(6)

multiprocessing.freeze_support()    
I've added this phrase, but it still does. What should I do?

**Comment by htgoebel** [comment] 2018-09-04 15:42
I'm closing this since there is not even a basic description of an issue.
See [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Closed by htgoebel** 2018-09-04 15:42 UTC

**Comment by JerryVSTom** [comment] 2020-12-29 03:35
My code has also encountered this problem，what is the solution, please.
Environment:
python 3.7.9
pyinstaller 4.0
os Mips

This problem seems like scikit-learn modules caused，but I don't know what should I do.

**Comment by bwoodsend** [comment] 2020-12-29 10:11
@JerryVSTom If you fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md), then we can help you. Currently only you and @djsc6511 have any idea what the problem is.
