### ISSUE TITLE
QtNetwork: Missing OpenSSL 1.1 DLLs on 64bit Windows

### ISSUE THREAD

**Issue by The-Compiler** [pyinstaller/pyinstaller#4321] opened 2019-07-18 14:06 UTC
With these versions:

- PyInstaller 3.5 or develop branch
- Python 3.7.4 (64-bit)
- Windows 10
- PyQt5 5.12.3 (Qt 5.12.4) or 5.13.0 (Qt 5.13.0)

When trying to build this example:

```python
# workaround for #4293
import os, sys
if hasattr(sys, '_MEIPASS'):
    os.environ['PATH'] += os.pathsep + sys._MEIPASS

from PyQt5.QtNetwork import QSslSocket
print(QSslSocket.supportsSsl())
```

I get `False`.

This is due to a missing `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` in the `dist` directory. When I copy them over from `site-packages\PyQt5\bin`, everything works fine.

Those seem to be 64bit-specific. PyInstaller does copy the DLLs without the `-x64` suffix, and those work fine with a 32-bit Python.

**Comment by bjones1** [comment] 2019-08-02 00:09
@The-Compiler, thanks for finding the root cause. That was a big help in fixing it. I appreciate it. This is fixed in 47bd7f10de3b343270fd4d34b356f14617d5d3a1.

**Closed by bjones1** 2019-08-02 00:09 UTC
