### ISSUE TITLE
pyi_rth_multiprocessing: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by indera** [pyinstaller/pyinstaller#2949] opened 2017-10-30 22:33 UTC
PyInstaller==3.3 produces an error which did not happen in PyInstaller==3.2
Note: I used the instructions from https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing 

The error trace:
```
 pool = mp.Pool(processes=NUM_CPUS)
  File "multiprocessing\context.py", line 118, in Pool
  File "multiprocessing\pool.py", line 174, in __init__
  File "multiprocessing\pool.py", line 239, in _repopulate_pool
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 313, in _Popen
  File "run\hasher.py", line 31, in __init__
    super(_Popen, self).__init__(*args, **kw)
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 71, in __init__
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 71, in __init__
...
RecursionError: maximum recursion depth exceeded
```

**Comment by gandrein** [comment] 2017-11-06 14:42
I can confirm having the same issue with v3.3. Tried with v3.2.1 and did not have the recursion problem.

**Comment by InputError** [comment] 2017-11-08 05:11
Same problem with 3.3, on 3.2.1 all works right

**Comment by htgoebel** [comment] 2017-11-09 16:12
To track down the issue, please revert commit 711e9e77c93a979a63648ba05f725b30dbb7c3cc and report back whether this helped. Thanks,

**Comment by InputError** [comment] 2017-11-12 06:54
@htgoebel tested, not works, thanks a lot for your attention, very important bug for many users

**Comment by htgoebel** [comment] 2017-11-12 10:35
Okay, so at least me know, this bug is not caused by 711e9e77c93a979a63648ba05f725b30dbb7c3cc but a duplicate of #2426 :-)

As a work-around please add `import sys; sys.setrecursionlimit(10000)` near the top of your .spec-file.

**Comment by InputError** [comment] 2017-11-13 05:41
@htgoebel I've used [this way](https://github.com/pyinstaller/pyinstaller/issues/2142#issuecomment-239667955) to fix that, and got no results, same error still here

**Comment by htgoebel** [comment] 2017-11-13 09:56
Ups, this is my fault. *This* error occurs at **run-time**, while both reverting the one commit and setting the recursion-limit are for *build-time*.

Please provide a **minimal** example so I can try to reproduce this.

**Comment by htgoebel** [comment] 2017-11-13 10:01
I also need all the other required information: platform, Python version, etc.

**Comment by InputError** [comment] 2017-11-14 06:08
@htgoebel several times in a row I've tried to make simple example, but even can't make workable this simple code:
```python
from multiprocessing import Pool


def doubler(number):
    return number * 2


if __name__ == '__main__':
    numbers = [5, 10, 20]
    pool = Pool(processes=3)
    print(pool.map(doubler, numbers))
```

this code loads 100% of CPU/RAM/IO/disk and soon nothing works, even mouse cursor is not moving because all overloaded, I can't collect any logs because computer not able to handle this situation

platform:
`Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32`

**Comment by gandrein** [comment] 2017-11-14 16:04
I have tried the suggested approach on 3.3, 
> As a work-around please add import sys; sys.setrecursionlimit(10000) near the top of your .spec-file.
with same result. 

Platform: Ubuntu 14.04 (Dell Precision 7510), Python 3.4.3

**Comment by htgoebel** [comment] 2017-11-22 09:18
@indera I'm still waiting for more detailed information from you as the original poster: platform, Python version, etc. minimal example.
@InputError Thanks for the code, but 100% load is not related to *this* issue. This issue is about maximum recursion depth exceeded.

**Comment by InputError** [comment] 2017-11-24 05:44
@htgoebel yep, you are right, here is correct example:
```python
from concurrent.futures import ProcessPoolExecutor
from time import sleep
import os
import sys

# Module multiprocessing is organized differently in Python 3.4+
try:
    # Python 3.4+
    if sys.platform.startswith('win'):
        import multiprocessing.popen_spawn_win32 as forking
    else:
        import multiprocessing.popen_fork as forking
except ImportError:
    import multiprocessing.forking as forking

if sys.platform.startswith('win'):
    # First define a modified version of Popen.
    class _Popen(forking.Popen):
        def __init__(self, *args, **kw):
            if hasattr(sys, 'frozen'):
                # We have to set original _MEIPASS2 value from sys._MEIPASS
                # to get --onefile mode working.
                os.putenv('_MEIPASS2', sys._MEIPASS)
            try:
                super(_Popen, self).__init__(*args, **kw)
            finally:
                if hasattr(sys, 'frozen'):
                    # On some platforms (e.g. AIX) 'os.unsetenv()' is not
                    # available. In those cases we cannot delete the variable
                    # but only set it to the empty string. The bootloader
                    # can handle this case.
                    if hasattr(os, 'unsetenv'):
                        os.unsetenv('_MEIPASS2')
                    else:
                        os.putenv('_MEIPASS2', '')

    # Second override 'Popen' class with our modified version.
    forking.Popen = _Popen


def return_after_5_secs(message):
    print(message)
    return message


if __name__ == "__main__":
    pool = ProcessPoolExecutor(3)

    future = pool.submit(return_after_5_secs, ("hello"))
    print(future.done())
    sleep(5)
    print(future.done())

**Comment by htgoebel** [comment] 2017-11-24 13:59
Thanks for the example. This brought me an important point into mind: We added a run-time hook implementing this, thus the recipe should no longer be necessary. I did not really recognize this change since the commit-message only reads "Runtime hooks: Fix "spawn" multiprocessing on OSX." 

Please try if your example works for you if you remove the recipe's code from it.

**Comment by htgoebel** [comment] 2017-11-24 14:31
Beside this, as a work-around: In your code rename `_Popen` into e.b. `_PopenX`. This will make the code pass. This might point to another problem we have in PyInstaller.

**Comment by InputError** [comment] 2017-11-25 03:14
> Please try if your example works for you if you remove the recipe's code from it.

@htgoebel thanks a lot dear, now it works!

**Comment by htgoebel** [comment] 2017-11-25 09:06
@InputError You are welcome. Would you agree into this statement: "As of PyInstaller 3.3., Recipe-Multiprocessing is not longer required"?

**Comment by InputError** [comment] 2017-11-25 09:19
@htgoebel absolutely agreed. Thanks again for your help and especially for your speed, I appreciate that very strong, you are doing very kind things.

**Comment by htgoebel** [comment] 2017-11-26 10:35
@InputError Thanks. If you are working for a company, please consider some [project grant](http://www.pyinstaller.org/donate.html#sponsorship-and-project-grant).

**Comment by htgoebel** [comment] 2017-11-26 20:26
I taek https://github.com/pyinstaller/pyinstaller/issues/2949#issuecomment-346915478 as "solved".

**Closed by htgoebel** 2017-11-26 20:26 UTC
Labels: v3.3

**Comment by indera** [comment] 2017-11-29 22:01
@htgoebel Sorry I didn't have to respond to your request - I will try to remove the recipe code and report my results
