### ISSUE TITLE
Data Execution Prevention - To help protect your computer Windows has closed this program

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#722] opened 2014-10-18 14:39 UTC
**Original date**: 2013/05/24
**Original reporter**: *Bob the Hamster*

I am testing a game written in Python with Kivy, and packaged for Windows an Mac using Pyinstaller.

I was using PyInstaller2.0 but the packaged game would only work if I had run the game from source at least once since the last reboot.

I updated to the latest pyinstaller develop branch from git, and that solved the problem on my own computer (Windows 7)

Today a friend of mine tested on a Windows XP computer, and it fails saying: "Data Execution Prevention - To help protect your computer Windows has closed this program"

I will attach a screenshot he gave me.

**Comment by matysek** [comment] 2015-09-22 08:53
Closing since there not clear description for reproducing and there hasn't been reported anything similar.

**Closed by matysek** 2015-09-22 08:53 UTC
Labels: develop, not enough info, support, Windows
