### ISSUE TITLE
The platform. architecture () function was used and could not run.

### ISSUE THREAD

**Issue by 7369632** [pyinstaller/pyinstaller#4192] opened 2019-04-24 02:15 UTC
No errors were reported during packing.
Pyinstaller Version:3.4
Installation from:pip
Python:2.7.16 32bit

Code:
```
import platform
print(platform.architecture())
print("T")
print( "Hello World")
```

Running Error:
```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 25, in <m
odule>
  File "c:\users\windows7\appdata\local\temp\pip-install-lkpdky\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 395, in load_module
  File "os.py", line 400, in <module>
  File "c:\users\windows7\appdata\local\temp\pip-install-lkpdky\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 395, in load_module
  File "UserDict.py", line 116, in <module>
  File "c:\users\windows7\appdata\local\temp\pip-install-lkpdky\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 395, in load_module
  File "_abcoll.py", line 11, in <module>
  File "c:\users\windows7\appdata\local\temp\pip-install-lkpdky\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 395, in load_module
  File "abc.py", line 18, in <module>
  File "platform.py", line 1099, in architecture
  File "platform.py", line 1034, in _syscmd_file
  File "c:\users\windows7\appdata\local\temp\pip-install-lkpdky\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 395, in load_module
  File "subprocess.py", line 60, in <module>
  File "c:\users\windows7\appdata\local\temp\pip-install-lkpdky\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 395, in load_module
  File "threading.py", line 13, in <module>
  File "c:\users\windows7\appdata\local\temp\pip-install-lkpdky\pyinstaller\PyIn
staller\loader\pyimod03_importers.py", line 395, in load_module
  File "collections.py", line 18, in <module>
AttributeError: 'module' object has no attribute '__all__'
[5312] Failed to execute script pyiboot01_bootstrap
```

**Comment by 7369632** [comment] 2019-04-24 02:17
warn-abc.txt context:
```

This file lists modules PyInstaller was not able to find. This does not
necessarily mean this module is required for running you program. Python and
Python 3rd-party packages include a lot of conditional or optional module. For
example the module 'ntpath' only exists on Windows, whereas the module
'posixpath' only exists on Posix systems.

Types if import:
* top-level: imported at the top-level - look at these first
* conditional: imported within an if-statement
* delayed: imported from within a function
* optional: imported within a try-except-statement

IMPORTANT: Do NOT post this list to the issue-tracker. Use it as a basis for
           yourself tracking down the missing module. Thanks!

missing module named resource - imported by posix (top-level), D:\8-1Pack\ts\abc.py (top-level)
missing module named posix - imported by os (conditional, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named macresource - imported by MacOS (top-level), D:\8-1Pack\ts\abc.py (top-level)
missing module named MacOS - imported by platform (delayed, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named os2 - imported by os (conditional, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named _emx_link - imported by os (conditional), D:\8-1Pack\ts\abc.py (top-level)
missing module named ce - imported by os (conditional, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named riscos - imported by os (conditional, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named riscospath - imported by os (conditional), D:\8-1Pack\ts\abc.py (top-level)
missing module named riscosenviron - imported by os (conditional, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named winreg.OpenKeyEx - imported by winreg (delayed, optional), platform (delayed, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named winreg.QueryValueEx - imported by winreg (delayed, optional), platform (delayed, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named winreg.CloseKey - imported by winreg (delayed, optional), platform (delayed, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named winreg.HKEY_LOCAL_MACHINE - imported by winreg (delayed, optional), platform (delayed, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named gestalt - imported by platform (delayed, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named Carbon - imported by plistlib (delayed), D:\8-1Pack\ts\abc.py (top-level)
missing module named 'Carbon.Files' - imported by plistlib (delayed), D:\8-1Pack\ts\abc.py (top-level)
missing module named 'Carbon.File' - imported by plistlib (delayed), D:\8-1Pack\ts\abc.py (top-level)
missing module named _xmlplus - imported by xml (optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named _scproxy - imported by urllib (conditional)
missing module named EasyDialogs - imported by getpass (optional)
missing module named termios - imported by getpass (optional)
missing module named SOCKS - imported by ftplib (optional)
missing module named rourl2path - imported by urllib (conditional)
missing module named java - imported by platform (delayed), D:\8-1Pack\ts\abc.py (top-level)
missing module named 'java.lang' - imported by platform (delayed, optional), D:\8-1Pack\ts\abc.py (top-level), xml.sax._exceptions (conditional)
missing module named fcntl - imported by tempfile (optional), subprocess (conditional), D:\8-1Pack\ts\abc.py (top-level)
missing module named org - imported by pickle (optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named 'org.python' - imported by copy (optional), D:\8-1Pack\ts\abc.py (top-level), xml.sax (delayed, conditional)
missing module named pwd - imported by posixpath (delayed, conditional), D:\8-1Pack\ts\abc.py (top-level), getpass (delayed)
missing module named readline - imported by cmd (delayed, conditional, optional), pdb (delayed, optional), D:\8-1Pack\ts\abc.py (top-level)
missing module named vms_lib - imported by platform (delayed, conditional, optional), D:\8-1Pack\ts\abc.py (top-level)

```

**Comment by BoboTiG** [comment] 2021-01-13 18:55
I cannot reproduce with PyInstaller 4.2, moreover the problem is likely Python 2.7-only which is no more supported. Therefore I am closing the issue.

**Closed by BoboTiG** 2021-01-13 18:55 UTC
