### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by ivan9394** [pyinstaller/pyinstaller#4616] opened 2020-01-09 12:58 UTC
Sorry to submit such an easy issue, I do read the go wrong tips but still can't find the answer

here is my problem

when i use pyinstaller to package a simple py, i go to the question in the title

in the script(several lines of code)only import tkinter and pandas

when i remove 'import pandas'

the pyinstaller is ok! but with pandas, it use lots of time and finally give me
'RuntimeError: maximum recursion depth exceeded in comparison'

i know if i add
 '
import sys
 sys.setrecursionlimit(1000)
'
to the spec file, it can be packaged, however when execute the exe, there still import error.

so why? because pandas have share lots of libs modules?
my envi
760 INFO: PyInstaller: 3.5
760 INFO: Python: 3.6.4
760 INFO: Platform: Windows-10-10.0.16299-SP0

below is my code~ 
# coding: utf-8

# In[ ]:

import pandas as pd
import tkinter as tk
root = tk.Tk()
root.title('欢迎使用简易TGI')
df = pd.read_csv('data.csv')
tk.Label(root,text='字段1:').grid(row=0,column=0)
tk.Label(root,text='字段2 :').grid(row=1,column=0)
tk.Label(root,text='值字段 :').grid(row=2,column=0)
tk.Label(root,text='页字段(选填) :').grid(row=3,column=0)
v1 = tk.StringVar() 
v2 = tk.StringVar()
v3 = tk.StringVar()
v4 = tk.StringVar()
e1 = tk.Entry(root,textvariable=v1)       
e2 = tk.Entry(root,textvariable=v2)
e3 = tk.Entry(root,textvariable=v3)
e4 = tk.Entry(root,textvariable=v4)
e1.grid(row=0,column=1,padx=10,pady=5)      
e2.grid(row=1,column=1,padx=10,pady=5)
e3.grid(row=2,column=1,padx=10,pady=5)
e4.grid(row=3,column=1,padx=10,pady=5)
def TGI_process_single(data, key1, key2, value, gb_key = None):
    double_group = pd.DataFrame()
    if gb_key=='':
        double_group = data.groupby(by = [key1, key2])[value].sum() / data.groupby(by = [key1])[value].sum()/data.groupby(by = [key2])[value].sum() * data[value].sum()
        double_group = double_group.reset_index().pivot_table(index = [key1], columns = [key2], values = value)
    else:
        double_group = data.groupby(by = [gb_key, key1, key2])[value].sum() / data.groupby(by = [gb_key, key1])[value].sum() / data.groupby(by = [gb_key, key2])[value].sum() * data.groupby(by = gb_key)[value].sum()
        double_group = double_group.reset_index().pivot_table(index = [gb_key, key1], columns = [key2], values = value)
    return double_group
def show():
    t = TGI_process_single(df, e1.get(),e2.get(),e3.get(),e4.get())
    t.to_csv('./'+e1.get()+'_'+e2.get()+'_'+e3.get()+'_'+e4.get()+'.csv')

tk.Button(root,text='定',width=10,command=show).grid(row=4,column=0,sticky=tk.W,padx=10,pady=5) 
tk.Button(root,text='出',width=10,command=root.destroy).grid(row=4,column=1,sticky=tk.E,padx=10,pady=5)
root.mainloop()

**Comment by Legorooj** [comment] 2020-02-21 06:38
This appears to be a duplicate of #4406

**Closed** 2020-02-24 11:04 UTC

**Comment by kaflesudeep** [comment] 2020-07-19 23:35
Hi @ivan9394 , 
any update in your issue? Were you able to resolve it?
