### ISSUE TITLE
pyinstaller make a exe file which contain requests run failed on no requests' windows

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [pyinstaller/pyinstaller#2970] opened 2017-11-06 08:09 UTC
Help me, I just being crazy....
My Pyinstaller version is 3.2.1, Python 2.7.13 and I make a exe which contain requests. But it can not run on other's windows whose without requests.
So, which version should I try?

**Comment by htgoebel** [comment] 2017-11-06 10:21
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by Shaunchenzhaojin** [comment] 2017-11-06 11:02
# test.py
import requests
if __name__ == '__main__':
    r=requests.get('https://www.google.com')
    print r.text

just simple like this, I build a exe by pyinstaller 3.3, python 2.7.13 , requests 2.18.4.
>pyinstaller -F test.py
The exe what I get can run on my windows, it can not be running on whose windows does not contain a requests module . There raise a error: No Module named requests.

I hope you can test it and run it without a python environment. 
And I want to know is which version of pyinstaller、python and requests should I use.
Thanks a lots!

**Comment by Shaunchenzhaojin** [comment] 2017-11-07 09:29
I resolve this problem myself, thanks for your follow.

**Comment by tenuki** [comment] 2017-11-07 09:59
> I resolve this problem myself, thanks for your follow.
There is not a bug in pyinstaller or requests, I just did not --hidden-import moduel in my command

Can you close this, as it is not a problem?
Thanks.

**Closed** 2017-11-07 10:48 UTC
Labels: need info, support
