### ISSUE TITLE
not find QtWebEngineProcess

### ISSUE THREAD

**Issue by yeshoujquery** [pyinstaller/pyinstaller#2976] opened 2017-11-07 10:04 UTC
<img width="343" alt="wx20171107-180337 2x" src="https://user-images.githubusercontent.com/10823306/32487944-abff66d0-c370-11e7-970e-604c6a4fc991.png">

Effect after packing

pyinstaller -F --clean hello_world.py

**Comment by tenuki** [comment] 2017-11-07 10:09
> wx20171107-180337 2x
> Effect after packing

You'll get a better answer if you follow: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs . The more information you report, the better devs can do.

**Comment by yeshoujquery** [comment] 2017-11-07 10:11
Isn't that a problem?

**Comment by yeshoujquery** [comment] 2017-11-07 10:29
@tenuki

**Comment by tenuki** [comment] 2017-11-07 10:32
> Isn't that a problem?

Haven't said that.

**Comment by yeshoujquery** [comment] 2017-11-08 01:16
@tenuki  ？？？

**Comment by yeshoujquery** [comment] 2017-11-09 02:58
@nicoddemus

**Comment by yeshoujquery** [comment] 2017-11-09 02:58
@itszero

**Comment by nicoddemus** [comment] 2017-11-09 12:16
@yeshoujquery I believe @tenuki means that you should try the notes on that page, specially *Information we need* and *Before submitting a report*; your original post is light on information, IMHO.

**Comment by yeshoujquery** [comment] 2017-11-14 02:24
@tenuki  Is there a solution?

**Comment by tenuki** [comment] 2017-11-14 04:48
I'm sorry but I can't understand the report.

**Comment by yeshoujquery** [comment] 2017-11-15 01:33
Mac 10.12.6

pyinstaller version 3.4.dev

pyqt5.9

![1510709447191](https://user-images.githubusercontent.com/10823306/32813986-8f72784c-c972-11e7-966a-fc6a12a91693.jpg)

pyinstaller -F -w  hello_world.py

Execute after packaging 

![image](https://user-images.githubusercontent.com/10823306/32813988-93b0ce36-c972-11e7-81fd-666a25666e0f.png)

@tenuki Is the report detailed enough?

**Comment by yeshoujquery** [comment] 2017-11-22 09:31
@bryancort @giantas

**Comment by yeshoujquery** [comment] 2017-11-22 09:32
@tenuki

**Comment by nicoddemus** [comment] 2017-11-22 10:05
I could not reproduce the problem on Windows 10/Python 3.6, using PyInstaller 3.3 or the latest `master`:

```
C:\Users\bruno\tmp-pyinstaller-2976
λ w:\Miniconda\envs\py36\python.exe -m venv .env36

C:\Users\bruno\tmp-pyinstaller-2976
λ .env36\Scripts\activate
(.env36) C:\Users\bruno\tmp-pyinstaller-2976
λ pip install PyQt5 pyinstaller
Collecting PyQt5
  Downloading PyQt5-5.9.1-5.9.2-cp35.cp36.cp37-none-win_amd64.whl (77.4MB)
    100% |████████████████████████████████| 77.4MB 20kB/s
Collecting pyinstaller
  Downloading PyInstaller-3.3.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 326kB/s
Collecting sip<4.20,>=4.19.4 (from PyQt5)
  Downloading sip-4.19.5-cp36-none-win_amd64.whl (51kB)
    100% |████████████████████████████████| 51kB 3.2MB/s
Requirement already satisfied: setuptools in c:\users\bruno\tmp-pyinstaller-2976\.env36\lib\site-packages (from pyinstaller)
Collecting pefile>=2017.8.1 (from pyinstaller)
  Downloading pefile-2017.11.5.tar.gz (61kB)
    100% |████████████████████████████████| 71kB 4.1MB/s
Collecting macholib>=1.8 (from pyinstaller)
  Downloading macholib-1.8-py2.py3-none-any.whl
Collecting future (from pyinstaller)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.2MB/s
Collecting pypiwin32 (from pyinstaller)
  Downloading pypiwin32-220-cp36-none-win_amd64.whl (9.0MB)
    100% |████████████████████████████████| 9.0MB 176kB/s
Collecting altgraph>=0.13 (from macholib>=1.8->pyinstaller)
  Downloading altgraph-0.14-py2.py3-none-any.whl
Installing collected packages: sip, PyQt5, future, pefile, altgraph, macholib, pypiwin32, pyinstaller
  Running setup.py install for future ... done
  Running setup.py install for pefile ... done
  Running setup.py install for pyinstaller ... done
Successfully installed PyQt5-5.9.1 altgraph-0.14 future-0.16.0 macholib-1.8 pefile-2017.11.5 pyinstaller-3.3 pypiwin32-220 sip-4.19.5

(.env36) C:\Users\bruno\tmp-pyinstaller-2976
λ python hello_world.py

(.env36) C:\Users\bruno\tmp-pyinstaller-2976
λ pyinstaller -F -w hello_world.py
78 INFO: PyInstaller: 3.3
78 INFO: Python: 3.6.2
78 INFO: Platform: Windows-10-10.0.16299-SP0
80 INFO: wrote C:\Users\bruno\tmp-pyinstaller-2976\hello_world.spec
94 INFO: UPX is not available.
97 INFO: Extending PYTHONPATH with paths
['C:\\Users\\bruno\\tmp-pyinstaller-2976',
 'C:\\Users\\bruno\\tmp-pyinstaller-2976']
98 INFO: checking Analysis
98 INFO: Building Analysis because out00-Analysis.toc is non existent
98 INFO: Initializing module dependency graph...
101 INFO: Initializing module graph hooks...
103 INFO: Analyzing base_library.zip ...
2916 INFO: running Analysis out00-Analysis.toc
2919 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\bruno\tmp-pyinstaller-2976\.env36\scripts\python.exe
3488 INFO: Caching module hooks...
3493 INFO: Analyzing C:\Users\bruno\tmp-pyinstaller-2976\hello_world.py
3518 INFO: Loading module hooks...
3519 INFO: Loading module hook "hook-encodings.py"...
3596 INFO: Loading module hook "hook-pydoc.py"...
3597 INFO: Loading module hook "hook-PyQt5.py"...
3601 INFO: Loading module hook "hook-PyQt5.Qt.py"...
3602 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
3656 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
3966 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
4018 INFO: Loading module hook "hook-PyQt5.QtWebEngineWidgets.py"...
4093 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
4095 INFO: Loading module hook "hook-xml.py"...
4302 INFO: Loading module hook "hook-PyQt5.QtNetwork.py"...
4366 INFO: Looking for ctypes DLLs
4366 INFO: Analyzing run-time hooks ...
4368 INFO: Including run-time hook 'pyi_rth_qt5webengine.py'
4369 INFO: Including run-time hook 'pyi_rth_qt5.py'
4373 INFO: Looking for dynamic libraries
5368 INFO: Looking for eggs
5368 INFO: Using Python library c:\users\bruno\tmp-pyinstaller-2976\.env36\scripts\python36.dll
5368 INFO: Found binding redirects:
[]
5371 INFO: Warnings written to C:\Users\bruno\tmp-pyinstaller-2976\build\hello_world\warnhello_world.txt
5411 INFO: Graph cross-reference written to C:\Users\bruno\tmp-pyinstaller-2976\build\hello_world\xref-hello_world.html
5451 INFO: checking PYZ
5452 INFO: Building PYZ because out00-PYZ.toc is non existent
5452 INFO: Building PYZ (ZlibArchive) C:\Users\bruno\tmp-pyinstaller-2976\build\hello_world\out00-PYZ.pyz
5881 INFO: Building PYZ (ZlibArchive) C:\Users\bruno\tmp-pyinstaller-2976\build\hello_world\out00-PYZ.pyz completed successfully.
5888 INFO: checking PKG
5888 INFO: Building PKG because out00-PKG.toc is non existent
5888 INFO: Building PKG (CArchive) out00-PKG.pkg
5931 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\python36.dll
5932 INFO: Updating resource type 24 name 2 language 1033
6287 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_ssl.pyd
6288 INFO: Updating resource type 24 name 2 language 1033
6356 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\unicodedata.pyd
6357 INFO: Updating resource type 24 name 2 language 1033
6380 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\pyexpat.pyd
6381 INFO: Updating resource type 24 name 2 language 1033
6408 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_hashlib.pyd
6409 INFO: Updating resource type 24 name 2 language 1033
6455 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_bz2.pyd
6456 INFO: Updating resource type 24 name 2 language 1033
6475 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_lzma.pyd
6476 INFO: Updating resource type 24 name 2 language 1033
6498 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\_socket.pyd
6499 INFO: Updating resource type 24 name 2 language 1033
6516 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\select.pyd
6517 INFO: Updating resource type 24 name 2 language 1033
6579 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\sip.pyd
6580 INFO: Updating resource type 24 name 2 language 1033
6682 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5gui.dll
6682 INFO: Updating resource type 24 name 2 language 1033
6838 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5core.dll
6839 INFO: Updating resource type 24 name 2 language 1033
6953 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5svg.dll
6954 INFO: Updating resource type 24 name 2 language 1033
6983 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5network.dll
6983 INFO: Updating resource type 24 name 2 language 1033
7028 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5printsupport.dll
7029 INFO: Updating resource type 24 name 2 language 1033
7052 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5webenginewidgets.dll
7053 INFO: Updating resource type 24 name 2 language 1033
7075 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\python3.dll
7076 INFO: Updating resource type 24 name 2 language 1033
7118 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5widgets.dll
7119 INFO: Updating resource type 24 name 2 language 1033
7548 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5webenginecore.dll
7549 INFO: Updating resource type 24 name 2 language 1033
8492 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5webchannel.dll
8493 INFO: Updating resource type 24 name 2 language 1033
8524 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5quickwidgets.dll
8524 INFO: Updating resource type 24 name 2 language 1033
8563 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5quick.dll
8564 INFO: Updating resource type 24 name 2 language 1033
8645 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5positioning.dll
8646 INFO: Updating resource type 24 name 2 language 1033
8695 INFO: Updating manifest in C:\Users\bruno\AppData\Roaming\pyinstaller\bincache00_py36_64bit\qt5qml.dll
8696 INFO: Updating resource type 24 name 2 language 1033
24986 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
25000 INFO: Bootloader c:\users\bruno\tmp-pyinstaller-2976\.env36\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
25000 INFO: checking EXE
25000 INFO: Building EXE because out00-EXE.toc is non existent
25001 INFO: Building EXE from out00-EXE.toc
25001 INFO: Appending archive to EXE C:\Users\bruno\tmp-pyinstaller-2976\dist\hello_world.exe
25180 INFO: Building EXE from out00-EXE.toc completed successfully.

(.env36) C:\Users\bruno\tmp-pyinstaller-2976
λ dist\hello_world.exe
```

Here's the transcribed `hello_world.py` file:

```python
import sys
from PyQt5.QtCore import QUrl
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView

app = QApplication(sys.argv)
browser = QWebEngineView()
browser.load(QUrl('https://www.google.com'))
browser.show()
app.exec_()
``` 

@yeshoujquery in the future, please don't post screenshots of code or console output, copy/paste the text instead preferably using [Markdown syntax](https://guides.github.com/features/mastering-markdown) for code. It is not fun having to transcribe code from an image. :confused:

**Comment by xoviat** [comment] 2017-12-05 06:09
Actually from the reports, there appears to be a serious problem in the bootloader on OSX 10. Unfortunately this is going to take someone who knows how to use gdb on OSX.

**Comment by bjones1** [comment] 2018-01-31 22:43
I'm closing this, since #3233 should fix it -- see the [instructions](https://github.com/pyinstaller/pyinstaller/pull/3233#issuecomment-362094587) there.

**Closed by bjones1** 2018-01-31 22:43 UTC
