### ISSUE TITLE
SyntaxError in main script: encoding declaration in Unicode string

### ISSUE THREAD

**Issue by quiris11** [pyinstaller/pyinstaller#1976] opened 2016-05-05 06:56 UTC
I tried to build a windowed app from project: https://github.com/quiris11/ExtractCoverThumbs.

Pyinstaller 3.2 and the latest dev version crashes. Previous version 3.1.1 works fin. 

pyinstaller -Fn ExtractCoverThumbs_app  --windowed ~/github/ExtractCoverThumbs/gui.pyw

```
49 INFO: PyInstaller: 3.3.dev0+c178715
49 INFO: Python: 2.7.11
64 INFO: Platform: Darwin-15.4.0-x86_64-i386-64bit
67 INFO: wrote /Users/user/ExtractCoverThumbs_app.spec
106 INFO: UPX is not available.
118 INFO: Extending PYTHONPATH with paths
['/Users/user/github/ExtractCoverThumbs', '/Users/user']
132 INFO: checking Analysis
149 INFO: Building because /usr/local/lib/python2.7/site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py changed
150 INFO: Initializing module dependency graph...
152 INFO: Initializing module graph hooks...
230 INFO: running Analysis out00-Analysis.toc
243 INFO: Caching module hooks...
248 INFO: Analyzing /Users/user/github/ExtractCoverThumbs/gui.pyw
2940 INFO: Processing pre-find module path hook   distutils
6275 INFO: Loading module hooks...
6275 INFO: Loading module hook "hook-distutils.py"...
6277 INFO: Loading module hook "hook-PIL.py"...
6278 INFO: Excluding import 'FixTk'
6281 INFO: Excluding import 'Tkinter'
6284 INFO: Excluding import 'PyQt5'
6287 WARNING:   Removing import PIL.ImageQt from module PyQt5
6287 WARNING:   Removing import PIL.ImageQt from module PyQt5.qRgba
6287 WARNING:   Removing import PIL.ImageQt from module PyQt5.QPixmap
6287 WARNING:   Removing import PIL.ImageQt from module PyQt5.QImage
6288 INFO: Excluding import 'PySide'
6290 WARNING:   Removing import PIL.ImageQt from module PySide.QPixmap
6291 WARNING:   Removing import PIL.ImageQt from module PySide.qRgba
6291 WARNING:   Removing import PIL.ImageQt from module PySide
6291 WARNING:   Removing import PIL.ImageQt from module PySide.QImage
6291 INFO: Excluding import 'PyQt4'
6294 WARNING:   Removing import PIL.ImageQt from module PyQt4.qRgba
6294 WARNING:   Removing import PIL.ImageQt from module PyQt4
6294 WARNING:   Removing import PIL.ImageQt from module PyQt4.QImage
6294 WARNING:   Removing import PIL.ImageQt from module PyQt4.QPixmap
6294 INFO: Loading module hook "hook-lxml.etree.py"...
6309 INFO: Loading module hook "hook-httplib.py"...
6309 INFO: Loading module hook "hook-encodings.py"...
7027 INFO: Loading module hook "hook-_tkinter.py"...
7034 INFO: checking Tree
7045 INFO: checking Tree
7053 INFO: Loading module hook "hook-PIL.Image.py"...
7535 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
7537 INFO: Excluding import 'FixTk'
7539 INFO: Excluding import 'Tkinter'
7583 INFO: Looking for ctypes DLLs
7595 INFO: Analyzing run-time hooks ...
7606 INFO: Including run-time hook 'pyi_rth__tkinter.py'
7623 INFO: Looking for dynamic libraries
7867 INFO: Looking for eggs
7867 INFO: Using Python library /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Python
7884 INFO: Warnings written to /Users/user/build/ExtractCoverThumbs_app/warnExtractCoverThumbs_app.txt
8333 INFO: checking PYZ
8346 INFO: checking PKG
8354 INFO: Building because /usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod01_os_path.pyc changed
8354 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.3.dev0+c178715', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 189, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 274, in assemble
    pylib_name=pylib_name)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 329, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 370, in add
    code = get_code_object(nm, pathnm)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 545, in get_code_object
    co = _load_code(modname, filename)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 521, in _load_code
    assert loader and hasattr(loader, 'get_code')
AssertionError
```

**Comment by bjones1** [comment] 2016-05-08 04:10
@quiris11, I think I have a fix for this. Would you mind testing https://github.com/bjones1/pyinstaller/tree/noext_fix1 to see if that fixes it for you?

**Comment by quiris11** [comment] 2016-05-08 08:26
Your branch crashes differently:

pyinstaller -Fn ExtractCoverThumbs_app  --windowed ~/github/ExtractCoverThumbs/gui.pyw
```
80 INFO: PyInstaller: 3.2.dev0+5eb539a
80 INFO: Python: 2.7.11
89 INFO: Platform: Darwin-15.4.0-x86_64-i386-64bit
90 INFO: wrote /Users/quiris/ExtractCoverThumbs_app.spec
99 INFO: UPX is not available.
101 INFO: Extending PYTHONPATH with paths
['/Users/quiris/github/ExtractCoverThumbs', '/Users/quiris']
101 INFO: checking Analysis
102 INFO: Building Analysis because out00-Analysis.toc is non existent
102 INFO: Initializing module dependency graph...
105 INFO: Initializing module graph hooks...
179 INFO: running Analysis out00-Analysis.toc
192 INFO: Caching module hooks...
197 INFO: Analyzing /Users/quiris/github/ExtractCoverThumbs/gui.pyw
2808 INFO: Processing pre-find module path hook   distutils
6172 INFO: Loading module hooks...
6172 INFO: Loading module hook "hook-distutils.py"...
6174 INFO: Loading module hook "hook-PIL.py"...
6176 INFO: Excluding import 'FixTk'
6179 INFO: Excluding import 'Tinter'
6182 INFO: Excluding import 'PyQt5'
6185 WARNING:   Removing import PIL.ImageQt from module PyQt5
6185 WARNING:   Removing import PIL.ImageQt from module PyQt5.qRgba
6185 WARNING:   Removing import PIL.ImageQt from module PyQt5.QPixmap
6185 WARNING:   Removing import PIL.ImageQt from module PyQt5.QImage
6185 INFO: Excluding import 'PySide'
6188 WARNING:   Removing import PIL.ImageQt from module PySide.QPixmap
6188 WARNING:   Removing import PIL.ImageQt from module PySide.qRgba
6189 WARNING:   Removing import PIL.ImageQt from module PySide
6189 WARNING:   Removing import PIL.ImageQt from module PySide.QImage
6189 INFO: Excluding import 'PyQt4'
6192 WARNING:   Removing import PIL.ImageQt from module PyQt4.qRgba
6192 WARNING:   Removing import PIL.ImageQt from module PyQt4
6192 WARNING:   Removing import PIL.ImageQt from module PyQt4.QImage
6192 WARNING:   Removing import PIL.ImageQt from module PyQt4.QPixmap
6192 INFO: Loading module hook "hook-lxml.etree.py"...
6209 INFO: Loading module hook "hook-httplib.py"...
6210 INFO: Loading module hook "hook-encodings.py"...
6906 INFO: Loading module hook "hook-_tkinter.py"...
6914 INFO: checking Tree
6915 INFO: Building Tree because out00-Tree.toc is non existent
6915 INFO: Building Tree out00-Tree.toc
7045 INFO: checking Tree
7045 INFO: Building Tree because out01-Tree.toc is non existent
7045 INFO: Building Tree out01-Tree.toc
7096 INFO: Loading module hook "hook-PIL.Image.py"...
7587 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
7589 INFO: Excluding import 'FixTk'
7591 INFO: Excluding import 'Tinter'
7637 INFO: Looking for types DLLs
7645 INFO: Analyzing run-time hooks ...
7654 INFO: Including run-time hook 'pyi_rth__tkinter.py'
7671 INFO: Looking for dynamic libraries
7960 INFO: Looking for eggs
7960 INFO: Using Python library /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Python
7975 INFO: Warnings written to /Users/quiris/build/ExtractCoverThumbs_app/warnExtractCoverThumbs_app.txt
8414 INFO: checking PYZ
8415 INFO: Building PYZ because out00-PYZ.toc is non existent
8415 INFO: Building PYZ (ZlibArchive) /Users/quiris/build/ExtractCoverThumbs_app/out00-PYZ.pyz
9517 INFO: checking PKG
9517 INFO: Building PKG because out00-PKG.toc is non existent
9517 INFO: Building PKG (Archive) out00-PKG.pkg
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0+5eb539a', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(speckle, kw.get('distpath'), kw.get('work path'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 189, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 274, in assemble
    pylib_name=pylib_name)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 329, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 370, in add
    code = get_code_object(nm, pathnm)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 571, in get_code_object
    co = _load_code(modname, filename)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 548, in _load_code
    source = f.read()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 147: ordinal not in range(128)
```

**Comment by bjones1** [comment] 2016-05-08 11:27
Thanks for the quick testing. What encoding do you use for `gui.pyw`? Currently, my branch only supports ASCII encoding for Python 2.7.

**Comment by quiris11** [comment] 2016-05-08 14:44
utf-8

**Comment by bjones1** [comment] 2016-05-09 22:01
OK. I've pushed a fix -- would you mind testing again?

**Comment by quiris11** [comment] 2016-05-10 08:02
```
247 INFO: PyInstaller: 3.2.dev0+8dd1c9d
248 INFO: Python: 2.7.11
363 INFO: Platform: Darwin-15.4.0-x86_64-i386-64bit
364 INFO: wrote /Users/robert.blaut/ExtractCoverThumbs_app.spec
400 INFO: UPX is not available.
403 INFO: Extending PYTHONPATH with paths
['/Users/robert.blaut/github/ExtractCoverThumbs', '/Users/robert.blaut']
403 INFO: checking Analysis
403 INFO: Building Analysis because out00-Analysis.toc is non existent
404 INFO: Initializing module dependency graph...
406 INFO: Initializing module graph hooks...
499 INFO: running Analysis out00-Analysis.toc
513 INFO: Caching module hooks...
518 INFO: Analyzing /Users/robert.blaut/github/ExtractCoverThumbs/gui.pyw
3513 INFO: Processing pre-find module path hook   distutils
7259 INFO: Loading module hooks...
7259 INFO: Loading module hook "hook-distutils.py"...
7266 INFO: Loading module hook "hook-PIL.py"...
7270 INFO: Excluding import 'FixTk'
7276 INFO: Excluding import 'Tkinter'
7280 INFO: Excluding import 'PyQt5'
7287 WARNING:   Removing import PIL.ImageQt from module PyQt5
7288 WARNING:   Removing import PIL.ImageQt from module PyQt5.qRgba
7288 WARNING:   Removing import PIL.ImageQt from module PyQt5.QPixmap
7288 WARNING:   Removing import PIL.ImageQt from module PyQt5.QImage
7288 INFO: Excluding import 'PySide'
7291 WARNING:   Removing import PIL.ImageQt from module PySide.QPixmap
7292 WARNING:   Removing import PIL.ImageQt from module PySide.qRgba
7292 WARNING:   Removing import PIL.ImageQt from module PySide
7293 WARNING:   Removing import PIL.ImageQt from module PySide.QImage
7293 INFO: Excluding import 'PyQt4'
7322 WARNING:   Removing import PIL.ImageQt from module PyQt4.qRgba
7322 WARNING:   Removing import PIL.ImageQt from module PyQt4
7323 WARNING:   Removing import PIL.ImageQt from module PyQt4.QImage
7323 WARNING:   Removing import PIL.ImageQt from module PyQt4.QPixmap
7326 INFO: Loading module hook "hook-lxml.etree.py"...
7350 INFO: Loading module hook "hook-httplib.py"...
7351 INFO: Loading module hook "hook-encodings.py"...
8186 INFO: Loading module hook "hook-_tkinter.py"...
8195 INFO: checking Tree
8195 INFO: Building Tree because out00-Tree.toc is non existent
8195 INFO: Building Tree out00-Tree.toc
8345 INFO: checking Tree
8345 INFO: Building Tree because out01-Tree.toc is non existent
8345 INFO: Building Tree out01-Tree.toc
8423 INFO: Loading module hook "hook-PIL.Image.py"...
9010 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
9013 INFO: Excluding import 'FixTk'
9015 INFO: Excluding import 'Tkinter'
9074 INFO: Looking for ctypes DLLs
9086 INFO: Analyzing run-time hooks ...
9096 INFO: Including run-time hook 'pyi_rth__tkinter.py'
9132 INFO: Looking for dynamic libraries
9393 INFO: Looking for eggs
9393 INFO: Using Python library /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Python
9408 INFO: Warnings written to /Users/robert.blaut/build/ExtractCoverThumbs_app/warnExtractCoverThumbs_app.txt
9852 INFO: checking PYZ
9852 INFO: Building PYZ because out00-PYZ.toc is non existent
9853 INFO: Building PYZ (ZlibArchive) /Users/robert.blaut/build/ExtractCoverThumbs_app/out00-PYZ.pyz
10929 INFO: checking PKG
10929 INFO: Building PKG because out00-PKG.toc is non existent
10929 INFO: Building PKG (CArchive) out00-PKG.pkg
('Syntax error in ', '/Users/robert.blaut/github/ExtractCoverThumbs/gui.pyw')
('encoding declaration in Unicode string', ('/Users/robert.blaut/github/ExtractCoverThumbs/gui.pyw', 0, None, None))
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0+8dd1c9d', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 189, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 274, in assemble
    pylib_name=pylib_name)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 329, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/archive/writers.py", line 370, in add
    code = get_code_object(nm, pathnm)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 573, in get_code_object
    co = _load_code(modname, filename)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 551, in _load_code
    return compile(source, filename, 'exec')
  File "/Users/robert.blaut/github/ExtractCoverThumbs/gui.pyw", line 0
SyntaxError: encoding declaration in Unicode string
```

**Comment by htgoebel** [comment] 2016-05-10 08:14
> SyntaxError: encoding declaration in Unicode string

Okay, so the cause is: Since v3.2 we are compiling the main script, too. Obviously we missed some case when reading the script file.

**Comment by codewarrior0** [comment] 2016-05-10 08:32
> encoding declaration in Unicode string

Seems like the correct thing to do is not pass any encoding to the `open()` call and let the `compile()` call decode it according to the encoding declaration.

**Comment by codewarrior0** [comment] 2016-05-10 09:41
I checked out @bjones1 branch, added the coding marker to the arbitrarily-named test file to produce the most recent error, and then changed the `open()` call to read the file in binary mode. The error no longer occurs on Python 2, and as an added bonus, the same code works in Python 3.

I'll go ahead and merge his branch in so we can mark this fixed.

**Comment by codewarrior0** [comment] 2016-05-10 10:20
@bjones1 Apparently, .pyw files are Windows-specific. Windows has two variants of the Python script runner, and one of them does not open a new console window when launched from Explorer. .pyw files are associated with this runner by default. I couldn't reproduce the original error using a .pyw file since on Windows, the `pkg_util` and `find_module` will recognize it as a module.

**Closed** 2016-05-10 10:22 UTC
Labels: @medium, Unicode, v3.2

**Comment by bjones1** [comment] 2016-05-10 14:21
Thanks for the fixes! I didn't realized that `compile` handled PEP 263. That's a great improvement.

I'm unable to reproduce the failure -- I think I was testing incorrectly. Looking at the original failure from @quiris11 above, I see that it was produced using OS X with a `.pyw` file, which makes more sense.

**Comment by quiris11** [comment] 2016-05-10 17:21
I can confirm the the problem is fixed.

**Comment by jniemann66** [comment] 2016-06-03 04:03
I am still getting this problem on 64-bit windows. I had to revert back to pyinstaller 3.1.1, which works fine.

**Comment by titilambert** [comment] 2016-07-25 15:17
Same issue on debian 64bit sid with pyinstaller==3.2
