### ISSUE TITLE
Embedded manifest files in windows bootloaders

### ISSUE THREAD

**Issue by jahrain** [pyinstaller/pyinstaller#1106] opened 2014-12-04 16:03 UTC
I noticed some strange behavior when renaming a pyinstaller create EXE file on windows when using the onefile option. If renamed from the original name, it would not load the manifest file and thus cause all sorts of issues such as requiring UAC if the file had words like "patch", "install", or "update" in the file names. Also possible conflicts with loading different versions of the msvcrt libraries and so on.

I have a minor work-around for that will embed the manifest file in the bootloaders instead of relying on the manifest file living next to the unbundled executable. This but it requires modifying the bootloader exe files.

I would suggest a step that embeds the manifest into the bootloader.exe before it creates the final exe files.

Here is a gist of what I am currently doing as work around for this issue. https://gist.github.com/jahrain/36244ef62d4b13d6ba40

It would be better if something like this was done some time during the build process.

**Comment by codewarrior0** [comment] 2015-05-24 18:40
Manifests are embedded into the onefile exe as of 74a159f67e429687ffa6cdc0ade00ea1fd36684a from pull request #149.

However, I now have a different problem when renaming the onefile exe: A dialog box appears saying `An application has made an attempt to load the C runtime library incorrectly. Please contact the application's support team for more information.`. What this means is that the MSVCR90.DLL was loaded without an activation context present.

A traceback is also produced, which I'll omit because it is specific to my application, but it indicates that the dialog box appears while the `zmq` module is loading `libzmq.pyd` using `_ctypes.LoadLibrary`. I may investigate this further.

**Comment by codewarrior0** [comment] 2015-05-24 20:42
The above error is caused by the bootloader using the filename of its exe to derive the filename of the manifest to load using CreateActCtx. The error occurs because the application manifest is not found when the onefile exe is renamed.

A possible solution is to embed the real name of the manifest into the PYZ archive and have the bootloader, when in onefile mode, read it from the archive when calling CreateActCtx, instead of computing the manifest name from the exe name. 

OTOH, when in onedir mode, CreateActCtx is never called - we rely on Windows to find the manifest file whose name matches the exe's name, so the only thing to do for onedir mode is embed the manifest into the exe. I don't think being able to rename the onedir exe is as useful as it is for onefile, though.

**Comment by htgoebel** [comment] 2015-05-26 09:27
> A possible solution is to embed the real name of the manifest into the PYZ archive and have the bootloader, when in onefile mode, read it from the archive when calling CreateActCtx, instead of computing the manifest name from the exe name. 

Sounds reasonable. Is it enough to store it in the PYZ or do we need to write it to the magic?

**Comment by codewarrior0** [comment] 2015-05-26 11:59
Probably, but I'm not certain. I had the idea of putting it in the PYZ as something like an OPTION but I didn't look closely at what kind of things can be stored in the PYZ. All that needs to be stored is a filename relative to the extraction directory.

**Comment by htgoebel** [comment] 2015-05-26 12:54
PYZ already supports runtime options, which are currently only one letter options like "v" or "u". Most are boolean, only "W" contains some value. Accessing them is as easy as shown in https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/common/pyi_pythonlib.c#L134

It should be easily be extended to
a) either use these options for other options, too or
b) add another type (e.g. `c` like config)

I'm in favour for the first as it requires less changes. I propose calling the option `windows-uac-manifest-filename` (other suggestions are welcome).

What do you think?

**Comment by codewarrior0** [comment] 2015-05-26 14:23
Good. The OPTION type should be usable, then. Here's what I'll do:

- Change pyi_launch_initialize to take the archive_status as an argument instead of executable.
- Change pyi_launch_initialize to (inside the #elif WIN32) scan the TOC for an OPTION with name `windows-uac-manifest-filename`.
- Change CreateActContext to take a single argument: the path to the manifest file
- Make pyi_launch_initialize locate the manifest file using the new option and pass it to CreateActContext
- Change pyi_pylib_set_runtime_opts to check that the string length == 1 to skip options with longer names.

Thinking on it some more, it may be possible to simply use a fixed manifest name for onefile builds and eschew the new runtime option entirely. EXE is responsible for locating the manifest produced earlier by Analyze and adding it to its own TOC. (Analyze does not add the manifest it produces to its TOC.) If we take this route, this is all we would have to do:

- Change EXE to, when `exclude_binaries==True`, add the manifest file to its TOC using a predefined filename (e.g. `_PYI_ONEFILE.manifest`) instead of the original filename (which is computed from specnm).
- Change CreateActContext to locate `_PYI_ONEFILE.manifest` relative to workdir and remove its `thisfile` argument.

I can't think of any right now, but there might be a reason not to do this (related to multipackage, maybe?)

**Comment by codewarrior0** [comment] 2015-08-15 17:35
I'll work on the pyi-runtime-options next. I'll start with this one for the manifest filename. I think another one to disable ShortFileNames on Python 2.7 would be good to have, as that deviates from Python's default behavior and users may want to disable it. I also see a request for a background option on OS X.

Can you think of any other options?

**Comment by htgoebel** [comment] 2015-08-15 18:35
Maybe we should bring forward #1315 then.

**Comment by codewarrior0** [comment] 2015-08-22 13:36
Fixed in 28867f6dfe272f50e76458a7e10e552140c866b5

**Closed by codewarrior0** 2015-08-22 13:36 UTC
Labels: Windows
