### ISSUE TITLE
Problems with ctypes on windows (python 3.3)

### ISSUE THREAD

**Issue by never-eat-yellow-snow** [pyinstaller/pyinstaller#1280] opened 2015-05-23 17:15 UTC
First of all: Thanks for this fantastic SW! Use it on linux and windows and I love it!

I have a problem with the following code compiled on windows (python 3.3.5) using the experimental pyinstaller version from the .zip file:

```python
import ctypes

class SharedMemoryHelper(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('numItems', ctypes.c_int32),
    ]

if __name__ == "__main__":
    print("Hello World")
    buffer = b"\x00"*4
    shm = SharedMemoryHelper.from_buffer(buffer)
    print(shm.numItems)
    import sys
    sys.stdin.readline()
```

Compiling with the command

>python.exe \temp\pyinstaller-python3\pyinstaller.py --log-level=DEBUG --clean -y -c --onefile test_pyinstall.py

gives no warnings or errors, but when I run the .exe file, it gives the following error:

>test_pyinstall.exe
>Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "C:\temp\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", line 308, in load_module
>    exec(bytecode, module.__dict__)
>  File "C:\python33\lib\ctypes\__init__.py", line 7, in <module>
>    from _ctypes import Union, Structure, Array
>  File "C:\temp\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", line 478, in load_module
>    module = loader.load_module(fullname)
>ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

(german translation is: The specified procedure could not be found) 

The same happens for --onedir. Removing ctypes from the import fixes the issue, but unfortunately I need the ctype support.

**Comment by codewarrior0** [comment] 2015-05-25 00:59
I can't reproduce that error. (I get a different error related to passing a non-writable buffer to `from_buffer`.) 

The error message indicates that _ctypes.pyd was found and partially loaded, but one of the DLLs it (perhaps indirectly) depends on did not have a needed procedure. This is usually caused by a version mismatch. Can you reproduce the problem with a clean python install?

**Comment by never-eat-yellow-snow** [comment] 2015-05-25 06:52
Thanks for looking into this. 

I'll try to reproduce that - sorry for the bug in the original post, there's a missing bytearray wrapper around the buffer; so the traceback you're actually observing is the desired script behaviour :) I already had a look into this with process monitor, but it was not obvious to me which dll is missing...

**Comment by htgoebel** [comment] 2015-05-26 09:19
Closing as invalid, see https://github.com/pyinstaller/pyinstaller/issues/1280#issuecomment-105082933

**Closed by htgoebel** 2015-05-26 09:19 UTC
Labels: PY3

**Comment by codewarrior0** [comment] 2015-05-26 12:25
It's not the DLL itself which is missing (you would get "module not found" or similar instead) - it's one of the entry points exported from one of the dependency DLLs. Dependency Walker might be a better tool than Process Monitor for diagnosing this.

**Comment by never-eat-yellow-snow** [comment] 2015-05-26 17:17
I can't reproduce the original issue anymore. I don't know what happened; maybe a reboot, but it suddenly works now, without changing anything to the python environment.

Sorry for bothering you :)
