### ISSUE TITLE
Pyinstaller Executable not showing MessageBox for ctypes

### ISSUE THREAD

**Issue by pranky89** [pyinstaller/pyinstaller#3827] opened 2018-10-24 01:34 UTC
Hi i am trying to import the ctypes messagebox in my code and the .py file works fine but when i package that with pyinstaller doesn't matter i use --onefile or --onedir, it doesn't show the popup,

Here is my code:

```
from ctypes import *
windll.user32.MessageBoxA(0, 'wow man', "New Notification", 0x40000)
```

Here are the build logs:
```
C:\Users\pp\Python_Programs\>pyinstaller --clean --onefile check_prompt.py
89 INFO: PyInstaller: 3.4
89 INFO: Python: 2.7.15
90 INFO: Platform: Windows-10-10.0.16299
92 INFO: wrote C:\Users\pp\Python_Programs\check_prompt.spec
93 INFO: UPX is not available.
93 INFO: Removing temporary files and cleaning cache in C:\Users\pandep2\AppData\Roaming\pyinstaller
112 INFO: checking Analysis
112 INFO: Building Analysis because Analysis-00.toc is non existent
113 INFO: Initializing module dependency graph...
115 INFO: Initializing module graph hooks...
151 INFO: running Analysis Analysis-00.toc
165 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
276 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
276 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
276 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
290 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_acce041fe1dd7bc9.manifest
384 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9317_none ...
401 INFO: Found manifest C:\windows\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b.manifest
401 INFO: Searching for file msvcr90.dll
401 INFO: Found file C:\windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\msvcr90.dll
401 INFO: Searching for file msvcp90.dll
401 INFO: Found file C:\windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\msvcp90.dll
401 INFO: Searching for file msvcm90.dll
401 INFO: Found file C:\windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\msvcm90.dll
509 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
526 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
526 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
526 INFO: Found C:\windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_acce041fe1dd7bc9.manifest
526 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
587 INFO: Caching module hooks...
603 INFO: Analyzing C:\Users\pp\Python_Programs\check_prompt.py
1544 INFO: Loading module hooks...
1544 INFO: Loading module hook "hook-encodings.py"...
2050 INFO: Looking for ctypes DLLs
2052 INFO: Analyzing run-time hooks ...
2055 INFO: Looking for dynamic libraries
2098 INFO: Looking for eggs
2099 INFO: Using Python library C:\windows\system32\python27.dll
2100 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9317), publicKeyToken=u'1fc8b3b9a1e18e3b')]
2102 INFO: Warnings written to C:\Users\pp\Python_Programs\build\check_prompt\warn-check_prompt.txt
2228 INFO: Graph cross-reference written toC:\Users\pp\Python_Programs\build\check_prompt\xref-check_prompt.html
2253 INFO: checking PYZ
2253 INFO: Building PYZ because PYZ-00.toc is non existent
2254 INFO: Building PYZ (ZlibArchive) C:\Users\pp\Python_Programs\build\check_prompt\PYZ-00.pyz
2381 INFO: Building PYZ (ZlibArchive) C:\Users\pp\Python_Programs\build\check_prompt\PYZ-00.pyz completed successfully.
2472 INFO: checking PKG
2473 INFO: Building PKG because PKG-00.toc is non existent
2474 INFO: Building PKG (CArchive) PKG-00.pkg
2665 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
2667 INFO: Updating manifest in C:\Users\pandep2\AppData\Roaming\pyinstaller\bincache00_py27_64bit\python27.dll
2671 INFO: Updating resource type 24 name 2 language 1033
2961 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
3865 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
3873 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
3873 INFO: checking EXE
3876 INFO: Building EXE because EXE-00.toc is non existent
3878 INFO: Building EXE from EXE-00.toc
3878 INFO: Appending archive to EXE C:\Users\pp\Python_Programs\messaging_app\dist\check_prompt.exe
3888 INFO: Building EXE from EXE-00.toc completed successfully.
```

**Comment by taosean** [comment] 2018-12-05 06:47
Hi, I had almost the same issue as you did.
I was also using ctypes to call some WinAPI to implement some functions.

I was doing
```python
from ctypes import *

hMapObject = windll.kernel32.OpenFileMappingA(FILE_MAP_ALL_ACCESS, False, szName)
if hMapObject == 0:
    print 'Could not open file mapping object'
    raise windll.WindowsError()

pBuf = windll.kernel32.MapViewOfFile(hMapObject, FILE_MAP_ALL_ACCESS, 0, 0, 0)

print pBuf

if pBuf == 0:
    print 'Could not map view of file'
    windll.kernel32.GetLastError()
else:
    # read data from pBuf
```

The codes run successfully when it's launched in script. However, if I convert this .py file to .exe, the `pBuf`, which should be an address in memory, is always `0`.

Besides, I tried the codes of yours, and I have the same problem as you did. Popup shows when launched in script and nothing shows when launced in executable.

Does anybody know why this is the case and how to solve it?

Thanks!

**Comment by htgoebel** [comment] 2018-12-05 11:57
> the pBuf, which should be an address in memory, is always 0.

@taosean This is an unrelated issue. please open an issue ot its own

**Comment by taosean** [comment] 2018-12-06 01:36
@htgoebel I don't think this is an unrelated issue. What I was trying to say is that I have similar problems as @pranky89 . The codes run well if launched in script, but if I convert them to exe file using pyinstaller, it won't run as expected. I suppose it has something to do with ctypes? Any suggestions about ctypes when using pyinstaller?

**Comment by BoboTiG** [comment] 2021-01-13 18:52
I cannot reproduce with PyInstaller 4.2, moreover the problem is likely Python 2.7-only which is no more supported. Therefore I am closing the issue.

**Closed by BoboTiG** 2021-01-13 18:52 UTC
Labels: platform:Windows
