### ISSUE TITLE
explicit hiddenimports required for setuptools

### ISSUE THREAD

**Issue by mj-harvey** [pyinstaller/pyinstaller#2003] opened 2016-05-23 21:32 UTC
Linux 64b, Conda with Python 3.5.1 and setuptools 20.7.0. I get the runtime error:

ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

 In order to produce a working executable, I need to build with the explicit hiddenimports

    --hiddenimport pkg_resources._vendor.packaging 
    --hiddenimport pkg_resources._vendor.packaging.version 
    --hiddenimport pkg_resources._vendor.packaging.specifiers 
    --hiddenimport pkg_resources._vendor.packaging.requirements

**Comment by htgoebel** [comment] 2016-05-24 06:30
Ans which version of PyInstaller?

**Comment by mj-harvey** [comment] 2016-05-24 08:08
the current HEAD, 6d103e81cfd2ae48b4bc5ca0cca39c11647dbed8

I also tried the v3.2 tag revision.

On 24 May 2016 at 07:30, Hartmut Goebel <notifications@github.com> wrote:

> Ans which version of PyInstaller?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyinstaller/pyinstaller/issues/2003#issuecomment-221178303>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by bjones1** [comment] 2016-05-24 15:44
I *think* this is a duplicate of #1791 and #1773. I should have a fix available soon.

**Comment by bjones1** [comment] 2016-05-27 14:19
@mj-harvey, would you try my branch at https://github.com/bjones1/pyinstaller/tree/collect_submodules_rewrite to see if this fixes the bug for you?

**Comment by bjones1** [comment] 2016-05-27 18:48
This should be fixed by 08020fd185d23a9a316583adef82c5b94d10bd0e. Please test and reopen if not.

**Closed by bjones1** 2016-05-27 18:48 UTC
Labels: need info
