### ISSUE TITLE
No error message - get_python_library_path() returns None

### ISSUE THREAD

**Issue by irenatfh** [pyinstaller/pyinstaller#4079] opened 2019-02-19 20:23 UTC
I am using pyinstaller development version 3.5.dev0+42ab9dbb4, Python 3.6.8, and am on Linux. I have been unable to package an executable using the `--onefile` flag, and receive this error message:

```
91756 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "/home/ihwang/software/anaconda3/bin/pyinstaller", line 10, in <module>
    sys.exit(run())
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "CRSSANT.spec", line 29, in <module>
    console=True )
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 424, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 196, in __init__
    self.__postinit__()
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/ihwang/software/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 273, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "/home/ihwang/software/anaconda3/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

As suggested, to debug I used the `--onedir` option but am receiving the same error message. I'm not using any virtual environments, as seemed to be the case with issue #3942. I'm not sure if issue #3362 applies, but if this sounds like a static linking issue please let me know what other information I can provide/what else I can test!

**Comment by htgoebel** [comment] 2019-02-20 09:10
>    pylib_name = os.path.basename(bindepend.get_python_library_path())

Obviously the python lib was not found. I assume you are either using conda or a statically compiled python.

**Comment by htgoebel** [comment] 2019-02-20 09:11
Reopen. We should at least ensure there is a proper error message. So the question is why is there no error message?

**Comment by htgoebel** [comment] 2019-02-20 14:56
I'm very curios how the code can come to this point. If teh lib is not found, PyInstaller should already terminate in the Analysis() phase.

Are us using a custom spec-file?
Please try building with `--clean`

**Comment by ihwang** [comment] 2019-02-20 16:44
> Obviously the python lib was not found. I assume you are either using conda or a statically compiled python.

Yes, I am using Python through Anaconda! Is this an issue? Sorry if this is a known issue, I'm very inexperienced with PyInstaller. I got it to work a handful of times last year (also while using Anaconda and to my recollection no virtual environment), but then I must have done something to my core code that I'm packaging up that changed things.

> Are us using a custom spec-file?

Indeed I am, created using `pyi-makespec --onefile CRSSANT.py` so that I could add deal with some known hidden import issues (figured those out last year when I magically got PyInstaller to work).

> Please try building with `--clean`

Received the exact same error chunk, verbatim.

Thanks for your assistance and patience!

**Comment by ihwang** [comment] 2019-03-18 21:19
Just checking in. Any suggestions on getting PyInstaller to recognize the python lib for Python through Anaconda?

**Comment by utcke** [comment] 2019-03-21 15:32
Running into the very same error (under the same conditions: Anaconda, custom spec file).  Works nicely under Windows, fails with the above message under Linux.
I could only second ihwang here, if this is a known issue with a known solution it would be nice to get pointed into the correct direction.

**Comment by htgoebel** [comment] 2019-08-07 16:14
Duplicate of #3942

**Comment by sneakypete81** [comment] 2020-01-06 15:22
Scanning through #3942, it appears to be a Windows-only venv problem. This issue is Linux and without a venv - see the original report above. I don't think this is a duplicate.

As mentioned earlier: 

> We should at least ensure there is a proper error message.

I'm seeing the same error condition in a Linux venv without conda. Perhaps I should file a new issue?

**Comment by bwoodsend** [comment] 2022-06-13 23:20
There's now a proper error message for statically linked Python.

**Closed by bwoodsend** 2022-06-13 23:20 UTC
