### ISSUE TITLE
Non-valid Unicode in sys.argv (removing the ShortPathName workaround for Python 3)

### ISSUE THREAD

**Issue by hrwatahiki** [pyinstaller/pyinstaller#1323] opened 2015-07-04 18:33 UTC
I use win8 and python3.4.
I created 'D:\users\ pydun\日本語\pydun.exe'  using pyinstaller.
When I run the file , sys.argv [0] had a strange value. Type is str , but it does not seem to be a valid Unicode.

**Comment by codewarrior0** [comment] 2015-07-04 18:44
How strange is the value? Can you print `sys.argv[0]` and `repr(sys.argv[0])` for us?

**Comment by hrwatahiki** [comment] 2015-07-04 19:08
print(sys.argv[0]) output the following message.

UnicodeEncodeError: 'cp932' codec can't encode character '\xe6' in position 15:
illegal multibyte sequence.

repr(sys.arv[0]) output no message.

**Comment by codewarrior0** [comment] 2015-07-04 19:15
What about `print(repr(sys.argv[0]))`?

From reading the bootloader code, you SHOULD see an MS-DOS style filename with a bunch of `~1` like things in it. But then it goes and combines the MS-DOS form of the dirname with the UTF-8 form of the basename...

**Comment by hrwatahiki** [comment] 2015-07-04 19:23
I run 'D:\users\ pydun\日本語\pydun.exe'
pydun.py
```python
import sys

for s in sys.argv[0]:
    print(s)
```

output
```
D
:
\
u
s
e
r
s
\
p
y
d
u
n
\
Traceback (most recent call last):
  File "<string>", line 7, in <module>
UnicodeEncodeError: 'cp932' codec can't encode character '\xe6' in position 0: i
llegal multibyte sequence
```

`print(repr(sys.argv[0]))` output the following message.

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
UnicodeEncodeError: 'cp932' codec can't encode character '\xe6' in position 19:
illegal multibyte sequence
```

**Comment by codewarrior0** [comment] 2015-07-04 19:34
I think this is because the MS-DOS short file names are not allowed on your `D:\`. Can you move your program to `C:\testing\日本語\pydun.exe` and see if it does the same thing? If so, this may be related to #1224 

The MS-DOS filename thing is really just a workaround. The bootloader needs a lot of changes to fully support unicode filenames.

**Comment by codewarrior0** [comment] 2015-07-04 19:36
For now you may have to have a disclaimer that your app has to be in a folder with only English folder names.

**Comment by hrwatahiki** [comment] 2015-07-05 01:54
I moved my app to 'c:\testing\日本語\pydun.exe', But the same error occurs.
'c:\testing\jp\pydun.exe' works without error.

**Comment by hrwatahiki** [comment] 2015-07-05 06:34
I think MS-DOS filename is not the reason of this error. Because '日本語' is 6bytes and as same as shortname.

**Comment by codewarrior0** [comment] 2015-07-05 10:09
Hmm. 

Try `print(os.path.exists(sys.argv[0]))`.  If you get True, then argv[0] is correct - the only thing you can't do is print argv[0] because the console window doesn't support unicode. If you get False, then argv[0] is actually incorrect.

**Comment by hrwatahiki** [comment] 2015-07-05 15:10
I tried `print(os.path.exists(sys.argv[0]))` and I got False.

**Comment by codewarrior0** [comment] 2015-07-05 15:23
What you SHOULD be getting for the path is "c:\testing\6a7a~1\pydun.exe", which is an MS-DOS filename. If that's not the case, then either MS-DOS filenames are disabled for your system or your drive, or something is wrong in PyInstaller.

To find out if MS-DOS filenames are enabled, run these commands:

`fsutil behavior query disable8dot3` will show the system-wide setting.
`fsutil behavior query disable8dot3 c:` will show the setting for C:\
`fsutil behavior query disable8dot3 D:` will show the setting for D:\

This really needs to be changed in PyInstaller, though. It should not rely on MS-DOS filenames being available.

**Comment by hrwatahiki** [comment] 2015-07-05 15:46
I run these commands. (These are Japanese messages and translated ones are following.)

```
C:\WINDOWS\system32>fsutil behavior query disable8dot3
レジストリの状態は 2 です (ボリューム単位で設定します - 既定値)。
(Registry value is 2)

C:\WINDOWS\system32>fsutil behavior query disable8dot3 c:
ボリュームの状態は 0 です (8dot3 名の作成は有効です)。
(Volume value is 0 ( 8dot3 name is enable))
レジストリの状態は 2 です (ボリューム単位で設定します - 既定値)。
(Registry value is 2)

上の 2 つの設定に基づいて、8dot3 名の作成は c: で有効です

C:\WINDOWS\system32>fsutil behavior query disable8dot3 D:
ボリュームの状態は 1 です (8dot3 名の作成は無効です)。
(Volume value is 1 ( 8dot3 name is disable))
レジストリの状態は 2 です (ボリューム単位で設定します - 既定値)。
(Registry value is 2)

上の 2 つの設定に基づいて、8dot3 名の作成は D: で無効です

```

**Comment by codewarrior0** [comment] 2015-07-05 16:32
Oh, you may be right when you said this:

>I think MS-DOS filename is not the reason of this error. Because '日本語' is 6bytes and as same as shortname.

It looks like MS-DOS filenames are allowed to have characters from the legacy codepage (CP932 in your case). So you can get `c:\testing\日本語\pydun.exe` when you ask Windows for the MS-DOS filename. Actually, this part is working properly. This is the method PyInstaller uses to load stuff from the .exe archive.

Okay, I found the problem:

At `pyi-archive.c` line 451, we have this:

```
count = mbstowcs(archive_status->argv[0], archive_status->archivename, PATH_MAX-1);
```

The problem is that `archive_status->archivename` is UTF-8 encoded, not codepage-encoded. `mbstowcs` only converts from codepage encoding to UTF-16.

**Comment by htgoebel** [comment] 2015-07-05 17:58
@hrwatahiki Would be great, if you could submit a pull-request.

And for completes the error picture: Can you please, as codewarrier0 requested earlier:
```
print(repr(sys.argv[0]))
```
Thanks.

**Comment by codewarrior0** [comment] 2015-07-05 18:16
There's two ways to quick-fix this:

1. Replace `mstowcs` with `pyi_win32_utils_from_utf8`. This will get the ShortFileName used earlier for opening the archive.

2. Replace the entire call with `strncpy(archive_status->argv[0], __wargv, PATH_MAX-1)` to get the `wchar_t` form of argv originally given by Windows. 

I think 2 is better because it also fixes #1282, and there's even a TODO at the top of this function that says to change to the wchar_t form of argv.

**Comment by htgoebel** [comment] 2015-07-21 16:36
IMHO an even better solution would be to base main() on Python's Modules/python.c, see #1340.

**Comment by codewarrior0** [comment] 2015-07-28 22:50
I'm looking into this some more. According to [this answer on Experts Exchange](http://www.experts-exchange.com/Programming/Languages/CPP/Q_21995516.html), GetShortPathNameW is allowed to return the path name as-is if it is both 8.3 character or shorter *and* is representable with the current ANSI codepage. In my tests, I was unable to reproduce this, as it always returned an 8.3 filename for any file with non-ASCII characters, but the behavior might be different on Japanese systems.

The 8.3 filenames are actually made when file is created, the well before GetShortPathName is even called. You can check what the 8.3 name for a file is using the `dir /X` command.

Regardless, I'll be working on removing the ShortPathName workaround for Python 3 because it will not be needed as Py3 has full support for Unicode filenames.

**Comment by htgoebel** [comment] 2015-07-30 08:17
Please have a look on how Python does it, see #1340 (where you already commented :-)

**Comment by codewarrior0** [comment] 2015-07-30 08:39
I'll try to follow Python as much as possible. One of the problems Python 2.7 has is that it always uses the ANSI codepage-versions of argv, so the python.exe simply won't start up if it's in a folder that uses characters from outside the codepage. (Error is `Error loading Python DLL`.) Windows gives it some junk in `__argv` that isn't a usable filename. So for Python 2.7 we still should use ShortPathNames so we can at least start up in situations where Python can't.

Side note: I started making unit-tests to make sure the built exe can start up when the folder has different characters in it, but I ran into the problem where the `subprocess` module on Python 2.7 uses the ANSI APIs which made it impossible to even run the non-ANSI test... bluh. The test seems to work for Python 3.3 though.

**Comment by htgoebel** [comment] 2015-07-30 08:57
> so the python.exe simply won't start up if it's in a folder that uses characters from outside the codepage

IC. I did not know this.

> I started making unit-tests to make sure the built exe can start up when the folder has different characters

Great, this is exactly what we need :-)

**Comment by codewarrior0** [comment] 2015-08-01 00:13
Worked out the kinks in the new unit tests and I think I exposed a bug. When using the crazy folder name "ěščřžýáíé日本語", [Python 3.3 fails in Py_Initialize](https://travis-ci.org/codewarrior0/pyinstaller/jobs/73641457) saying the codecs module (from base_library.zip) can't be imported, but the paths in the bootloader's debug output are correct. This only happens in onedir - presumably the onefile build extracts its base_library.zip to a temp folder which doesn't have a crazy folder name.

I'm poring over the Python source code right now, desperately hoping that I'm not looking at a chicken-and-egg problem where the Python importer needs the codecs module in order to import the codecs module from a path that needs to be encoded using the codecs module before it can be passed to the filesystem functions.

**Comment by codewarrior0** [comment] 2015-08-01 01:20
Oh, good. The problem is just that mbstowcs is returning -1. That I know how to deal with.

**Comment by codewarrior0** [comment] 2015-08-01 02:34
Well, that was straightforward. mbstowcs was returning -1 because the LC_CTYPE is "C". All I had to do was call setlocale to set it to the current locale's encoding to have a working mbstowcs. I also restore the encoding to the default before running scripts to preserve the original Python behavior.

**Comment by htgoebel** [comment] 2015-08-01 12:56
> presumably the onefile build extracts its base_library.zip to a temp folder which doesn't have a crazy folder name.

This is correct (at least as long $TEMP does not point to a directory with non-ascii characters).

**Comment by htgoebel** [comment] 2015-08-01 12:58
> All I had to do was call setlocale to set it to the current locale's encoding to have a working mbstowcs

These are the tricks which I meant to be addressed by #1340.

**Comment by codewarrior0** [comment] 2015-08-01 23:36
Of course. Python restricts its use of setlocale and mbstowcs to only one or two places. One of them is in the actual main() in Program/python.c so it can pass only wchar_t to Py_Main. And for the most part, Py_Main doesn't use C strings (char or wchar_t) - it switches to Python stringobj/unicodeobj as soon as it can, and to call filesystem functions (fopen etc) it uses PyUnicode_FSEncode and all of the platform-safe fs functions in fileutils.c, We don't have that luxury as we need to use C strings to find and load the Python27.dll/.so and to set up the initial path before calling Py_Initialize. But we probably should just take an entire copy of fileutils.c since those functions are so useful (especially the Py_Decode/EncodeLocale added in Python 3.5).

I wanted to make sure that test passes and get the proper behavior from the bootloader before we get to doing #1340 so as to make sure we don't break anything. To follow what Python 3's main does, we'll have to convert almost all of the char * to wchar_t * in ARCHIVE_STATUS and all of our internal functions.

**Comment by codewarrior0** [comment] 2015-08-15 17:19
I am confident that this is fixed in the `python3` branch. I have a functional test that makes sure all paths on Python 3 are not ShortFileNames.

**Comment by htgoebel** [comment] 2015-09-05 16:15
So I'm closing this as fixed.

**Closed by htgoebel** 2015-09-05 16:15 UTC
Labels: PY3, Unicode
