### ISSUE TITLE
Missing python modules lead to non-functional executables

### ISSUE THREAD

**Issue by jenisys** [pyinstaller/pyinstaller#2469] opened 2017-02-20 21:21 UTC
PYINSTALLER-VERSION: 3.2.1, 3.3.dev0+g56bf488 (CURRENT-HEAD)
PLATFORM: macOS 10.11 with Python 2.7.13

**PRECONDITION:**
* Prepared ``*.spec`` exists to build an executable with pyinstaller (one-file mode)
* Not all Python requirements are installed on this computer (use case: checkout Git project on another computer)

When you run ``pyinstaller my_app.spec``, pyinstaller reports that the executable was successfully created. When you try to run the created executable, it fails to start (often with a missing module import error).

**EXPECTED BEHAVIOUR:**
* Pyinstaller should fail if it should build an executable and not all imports can be resolved
* Otherwise, there should be at least a ``--strict`` option or something similar that allows the user to ensure this

**Comment by jenisys** [comment] 2017-02-20 21:31
NOTE: If you put the essential modules for an executable into the ``hiddenimports`` list, you will an error for each missing module of the ``hiddenimports`` list, but the building of the executable is still successful: ``Building EXE from out00-EXE.toc completed successfully.``

**Comment by tallforasmurf** [comment] 2017-02-21 01:46
This is addressed in the docs, although admittedly not very obviously, see

http://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html?highlight=warnings#build-time-messages

Check the warnings file even for a successful build (for example, bundle a one-line 'hello world' program) and you will typically find many "missing module" messages.

For this reason, a `--strict` option would be useless, every run would fail.

**Comment by htgoebel** [comment] 2017-02-21 08:58
PyInstaller tries it's best to ensure all required packages are included. But many packages include conditional imports, which PyInstaller can never decide on.[*] Thus an `--strict` option would be useless, as tallforasmurf already wrote.

[*] Well, in theory this could be implement, but this would require a complete static source analysis of *all* modules, including deep knowledge of *every* module having condition imports. This is not feasible.

**Closed by htgoebel** 2017-02-21 08:58 UTC

**Comment by jenisys** [comment] 2017-02-22 19:57
Mmh, maybe I have higher expectations to a program like ``pyinstaller`` than you. If I build an executable, I want to know at build-time if it will work or not. I don't want to try it to see it is failing or not.

**Comment by jenisys** [comment] 2017-02-22 20:08
@tallforasmurf @htgoebel 
One final note. The documentation states that an exception is raised when Python libraries are missing at build time. This is not the behaviour that I observe. I have never seen an exception when the described problem occurs. Therefore, the documentation does not cover the observed behaviour that is described in the ticket. In addition, the primary module, that was used in a python script, was missing.

**Comment by htgoebel** [comment] 2017-02-23 14:16
Maybe I have a higher expectation to the build environment set up by the developer: It ought contain all required stuff. That's what the developer gets paid for.

> The documentation states that an exception is raised when Python libraries are missing at build time.

Where is it? I can't find the word "exception" in such context.

**Comment by jenisys** [comment] 2017-02-26 11:08
Sorry, using pyinstaller is a build step. Therefore, this build step should fail when it produces non-usable output (in this case the executable). This is currently not the case (and the last line regarding the successfully build executable clearly states the pyinstaller thinks that it has done a successful job).

My whole point is:
* succeed, but then it must be ensured the build artefact must be usable (currently not met)
* fail in a reliable way when the build executable (or directory) is not usable

Regarding the "exception", I was referring to the [build-time-python-errors](http://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html?highlight=warnings#build-time-python-errors) section. And clearly the "module not found" strategy in section "Build-time Messages" is suboptimal. It may be correct for optional python modules from the python standard-library, but not for all other python packages that enhance the python standard-library (installed under "site-packages/"). I am having a problem with the second case.

**Comment by jenisys** [comment] 2017-02-26 11:30
PROOF-OF-PROBLEM example (UNIX shell procedure, similar in Windows cmd shell):

```python
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# FILE: hello_problem.py
"""
Proof-of-problem example for pyinstaller behaviour when
* locally unknown modules are missing
* unknown modules are not bundled

PROCEDURE:

    $ pyi-makespec --onefile hello_problem.py
    $ pyinstaller hello_problem.spec  && echo PYINSTALLER-OK
    ...
    ... only INFO messages
    ...
    10357 INFO: Fixing EXE for code signing /Users/jens/se/_EXPLORE/pyftp_1/dist/hello_problem
    10367 INFO: Building EXE from out00-EXE.toc completed successfully.
    PYINSTALLER-OK

    # -- SHOW PROBLEM:
    $ dist/hello_problem
    Traceback (most recent call last):
    File "hello_problem.py", line 27, in <module>
      import unknown_module
    ImportError: No module named unknown_module
    Failed to execute script hello_problem

SEE ALSO:
* https://github.com/pyinstaller/pyinstaller/issues/2469
"""

from __future__ import print_function
import sys
import os

USE_UNKNOWN_MODULE = (os.environ.get("USE_UNKNOWN_MODULE", "yes") == "yes")
if USE_UNKNOWN_MODULE:
    import unknown_module

def hello(args=None):
    if args is None:
        args = sys.argv[1:]
    text = " ".join(args)
    print("Hello %s" % text)
    return 0

if __name__ == "__main__":
    sys.exit(hello())
```

**Comment by tallforasmurf** [comment] 2017-02-26 17:49
I copied your code (minus the from-future import as I'm using Py3, and MacOS) and bundled it. Here in full is the content of `build/uum/warnuum.txt`.

Not one of those except for the very final line is actually needed to execute the program. Not one. So at least acknowledge that the problem of deciding which of the "missing module" events is significant is at least, not trivial.

~~~~
[09:43 /Developer/PyInstallerWork] cat build/uum/warnuum.txt
missing module named _io.BufferedRWPair - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.BytesIO - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.UnsupportedOperation - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.open - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.BufferedWriter - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.BufferedRandom - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.BlockingIOError - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.IncrementalNewlineDecoder - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.StringIO - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.FileIO - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.TextIOWrapper - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.BufferedReader - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _io.DEFAULT_BUFFER_SIZE - imported by _io, io, /Developer/PyInstallerWork/uum.py
missing module named _datetime.__doc__ - imported by _datetime, datetime, /Developer/PyInstallerWork/uum.py
missing module named unicodedata.ucd_3_2_0 - imported by unicodedata, stringprep, encodings.idna, /Developer/PyInstallerWork/uum.py
missing module named 'org.python' - imported by pickle, /Developer/PyInstallerWork/uum.py, xml.sax
missing module named 'org.python'.imp - imported by 'org.python', xml.sax
missing module named 'org.python'.PyStringMap - imported by 'org.python', pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.load - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.loads - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.PicklingError - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.Pickler - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.dumps - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.Unpickler - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.UnpicklingError - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.PickleError - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _pickle.dump - imported by _pickle, pickle, /Developer/PyInstallerWork/uum.py
missing module named _opcode.stack_effect - imported by _opcode, opcode, /Developer/PyInstallerWork/uum.py
missing module named _imp.is_frozen_package - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.init_frozen - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.release_lock - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.lock_held - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.is_builtin - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.get_frozen_object - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.init_builtin - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.acquire_lock - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.is_frozen - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp._fix_co_filename - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
missing module named _imp.load_dynamic - imported by _imp, imp, /Developer/PyInstallerWork/uum.py
excluded module named _frozen_importlib - imported by importlib, /Developer/PyInstallerWork/uum.py
missing module named zipimport.zipimporter - imported by zipimport, pkgutil, /Developer/PyInstallerWork/uum.py
missing module named win32api - imported by platform, /Developer/PyInstallerWork/uum.py
missing module named win32api.RegQueryValueEx - imported by win32api, platform, /Developer/PyInstallerWork/uum.py
missing module named win32api.RegCloseKey - imported by win32api, platform, /Developer/PyInstallerWork/uum.py
missing module named win32api.RegOpenKeyEx - imported by win32api, platform, /Developer/PyInstallerWork/uum.py
missing module named win32api.GetVersionEx - imported by win32api, platform, /Developer/PyInstallerWork/uum.py
missing module named win32con - imported by platform, /Developer/PyInstallerWork/uum.py
missing module named win32con.VER_PLATFORM_WIN32_NT - imported by win32con, platform, /Developer/PyInstallerWork/uum.py
missing module named win32con.VER_NT_WORKSTATION - imported by win32con, platform, /Developer/PyInstallerWork/uum.py
missing module named win32con.VER_PLATFORM_WIN32_WINDOWS - imported by win32con, platform, /Developer/PyInstallerWork/uum.py
missing module named win32con.HKEY_LOCAL_MACHINE - imported by win32con, platform, /Developer/PyInstallerWork/uum.py
missing module named _scproxy._get_proxy_settings - imported by _scproxy, urllib.request
missing module named _scproxy._get_proxies - imported by _scproxy, urllib.request
missing module named 'java.lang'.Exception - imported by 'java.lang', xml.sax._exceptions
missing module named xml.parsers.expat.ParserCreate - imported by xml.parsers.expat, plistlib, /Developer/PyInstallerWork/uum.py
missing module named java - imported by platform, /Developer/PyInstallerWork/uum.py
missing module named java.System - imported by java, platform, /Developer/PyInstallerWork/uum.py
missing module named 'java.lang' - imported by platform, /Developer/PyInstallerWork/uum.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, /Developer/PyInstallerWork/uum.py
missing module named _ssl.OPENSSL_VERSION_INFO - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.OPENSSL_VERSION_NUMBER - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.OPENSSL_VERSION - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl._SSLContext - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.SSLWantWriteError - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.SSLZeroReturnError - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.SSLEOFError - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.SSLError - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.SSLWantReadError - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.SSLSyscallError - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.CERT_NONE - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.CERT_OPTIONAL - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.CERT_REQUIRED - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.VERIFY_CRL_CHECK_LEAF - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.VERIFY_X509_STRICT - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.VERIFY_DEFAULT - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.VERIFY_CRL_CHECK_CHAIN - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.nid2obj - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.txt2obj - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.RAND_status - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.RAND_add - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.RAND_pseudo_bytes - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.RAND_bytes - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.RAND_egd - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.HAS_NPN - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.HAS_ECDH - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.HAS_SNI - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl._OPENSSL_API_VERSION - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.PROTOCOL_SSLv2 - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.PROTOCOL_TLSv1_1 - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.PROTOCOL_TLSv1_2 - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.enum_certificates - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named _ssl.enum_crls - imported by _ssl, ssl, /Developer/PyInstallerWork/uum.py
missing module named winreg - imported by platform, mimetypes, /Developer/PyInstallerWork/uum.py, urllib.request
missing module named _hashlib.pbkdf2_hmac - imported by _hashlib, hashlib, /Developer/PyInstallerWork/uum.py
missing module named hashlib.sha512 - imported by hashlib, random, /Developer/PyInstallerWork/uum.py
missing module named _bz2.BZ2Decompressor - imported by _bz2, bz2, /Developer/PyInstallerWork/uum.py
missing module named _bz2.BZ2Compressor - imported by _bz2, bz2, /Developer/PyInstallerWork/uum.py
missing module named grp.getgrnam - imported by grp, shutil, /Developer/PyInstallerWork/uum.py
missing module named binascii.a2b_qp - imported by binascii, quopri, /Developer/PyInstallerWork/uum.py
missing module named binascii.b2a_qp - imported by binascii, quopri, /Developer/PyInstallerWork/uum.py
missing module named binascii.b2a_base64 - imported by binascii, email.base64mime, /Developer/PyInstallerWork/uum.py
missing module named binascii.a2b_base64 - imported by binascii, email.base64mime, /Developer/PyInstallerWork/uum.py
missing module named _lzma._decode_filter_properties - imported by _lzma, lzma, /Developer/PyInstallerWork/uum.py
missing module named _lzma._encode_filter_properties - imported by _lzma, lzma, /Developer/PyInstallerWork/uum.py
missing module named pwd.getpwnam - imported by pwd, shutil, /Developer/PyInstallerWork/uum.py
missing module named socket.AF_INET - imported by socket, ssl, /Developer/PyInstallerWork/uum.py
missing module named socket.SOCK_STREAM - imported by socket, ssl, /Developer/PyInstallerWork/uum.py
missing module named socket.SOL_SOCKET - imported by socket, ssl, /Developer/PyInstallerWork/uum.py
missing module named socket.SO_TYPE - imported by socket, ssl, /Developer/PyInstallerWork/uum.py
missing module named _struct._clearcache - imported by _struct, struct, /Developer/PyInstallerWork/uum.py
missing module named _struct.__doc__ - imported by _struct, struct, /Developer/PyInstallerWork/uum.py
missing module named struct.pack - imported by struct, pickle, /Developer/PyInstallerWork/uum.py
missing module named struct.unpack - imported by struct, pickle, /Developer/PyInstallerWork/uum.py
missing module named _weakref.ProxyType - imported by _weakref, weakref, /Developer/PyInstallerWork/uum.py
missing module named _weakref.getweakrefs - imported by _weakref, weakref, /Developer/PyInstallerWork/uum.py
missing module named _weakref.ref - imported by _weakref, _weakrefset, weakref, /Developer/PyInstallerWork/uum.py
missing module named _weakref.ReferenceType - imported by _weakref, weakref, /Developer/PyInstallerWork/uum.py
missing module named _weakref.proxy - imported by _weakref, weakref, collections, /Developer/PyInstallerWork/uum.py
missing module named _weakref.getweakrefcount - imported by _weakref, weakref, /Developer/PyInstallerWork/uum.py
missing module named _weakref.CallableProxyType - imported by _weakref, weakref, /Developer/PyInstallerWork/uum.py
missing module named org - imported by copy, /Developer/PyInstallerWork/uum.py
missing module named org.PyStringMap - imported by org, copy, /Developer/PyInstallerWork/uum.py
missing module named copy.deepcopy - imported by copy, email.generator, weakref, /Developer/PyInstallerWork/uum.py
missing module named errno.ENOENT - imported by errno, gettext, /Developer/PyInstallerWork/uum.py
missing module named posix._exit - imported by posix, os, /Developer/PyInstallerWork/uum.py
missing module named os.urandom - imported by os, random, /Developer/PyInstallerWork/uum.py
missing module named posix._have_functions - imported by posix, os, /Developer/PyInstallerWork/uum.py
missing module named nt - imported by shutil, os, ntpath, /Developer/PyInstallerWork/uum.py
missing module named nt._exit - imported by nt, os, /Developer/PyInstallerWork/uum.py
missing module named nt._getvolumepathname - imported by nt, ntpath, /Developer/PyInstallerWork/uum.py
missing module named nt._getfullpathname - imported by nt, ntpath, /Developer/PyInstallerWork/uum.py
missing module named nt._getfinalpathname - imported by nt, ntpath, /Developer/PyInstallerWork/uum.py
missing module named nt._isdir - imported by nt, ntpath, /Developer/PyInstallerWork/uum.py
missing module named nt._have_functions - imported by nt, os, /Developer/PyInstallerWork/uum.py
missing module named ce - imported by os, /Developer/PyInstallerWork/uum.py
missing module named ce._exit - imported by ce, os, /Developer/PyInstallerWork/uum.py
missing module named ce._have_functions - imported by ce, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.abspath - imported by posixpath, shutil, /Developer/PyInstallerWork/uum.py
missing module named posixpath.defpath - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.altsep - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.devnull - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.pathsep - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.curdir - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.extsep - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.sep - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named posixpath.pardir - imported by posixpath, os, /Developer/PyInstallerWork/uum.py
missing module named _warnings._defaultaction - imported by _warnings, warnings, /Developer/PyInstallerWork/uum.py
missing module named _warnings.warn_explicit - imported by _warnings, warnings, /Developer/PyInstallerWork/uum.py
missing module named _warnings._filters_mutated - imported by _warnings, warnings, /Developer/PyInstallerWork/uum.py
missing module named _warnings.filters - imported by _warnings, warnings, /Developer/PyInstallerWork/uum.py
missing module named _warnings.warn - imported by _warnings, warnings, /Developer/PyInstallerWork/uum.py
missing module named _warnings._onceregistry - imported by _warnings, warnings, /Developer/PyInstallerWork/uum.py
missing module named time.monotonic - imported by time, subprocess, threading, /Developer/PyInstallerWork/uum.py
missing module named time.time - imported by time, subprocess, threading, /Developer/PyInstallerWork/uum.py
missing module named itertools.tee - imported by itertools, heapq, /Developer/PyInstallerWork/uum.py
missing module named itertools.chain - imported by itertools, heapq, tokenize, collections, /Developer/PyInstallerWork/uum.py
missing module named itertools.repeat - imported by itertools, tokenize, collections, /Developer/PyInstallerWork/uum.py
missing module named itertools.starmap - imported by itertools, collections, /Developer/PyInstallerWork/uum.py
missing module named itertools.islice - imported by itertools, reprlib, heapq, threading, pickle, /Developer/PyInstallerWork/uum.py
missing module named itertools.count - imported by itertools, heapq, threading, /Developer/PyInstallerWork/uum.py
missing module named _collections.defaultdict - imported by _collections, collections, /Developer/PyInstallerWork/uum.py
missing module named _collections._count_elements - imported by _collections, collections, /Developer/PyInstallerWork/uum.py
missing module named _collections.deque - imported by _collections, collections, threading, /Developer/PyInstallerWork/uum.py
missing module named threading.current_thread - imported by threading, _threading_local, /Developer/PyInstallerWork/uum.py
missing module named threading.RLock - imported by threading, _threading_local, bz2, /Developer/PyInstallerWork/uum.py
missing module named msvcrt - imported by subprocess, /Developer/PyInstallerWork/uum.py, getpass
missing module named _winapi - imported by subprocess, /Developer/PyInstallerWork/uum.py
missing module named math.pi - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.exp - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.ceil - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.log - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.e - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.sin - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.cos - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.sqrt - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named math.acos - imported by math, random, /Developer/PyInstallerWork/uum.py
missing module named _dummy_thread.allocate_lock - imported by _dummy_thread, _strptime, /Developer/PyInstallerWork/uum.py
missing module named _dummy_threading - imported by dummy_threading, /Developer/PyInstallerWork/uum.py
missing module named _dummy_threading.__all__ - imported by _dummy_threading, dummy_threading, /Developer/PyInstallerWork/uum.py
missing module named dummy_threading.RLock - imported by dummy_threading, bz2, /Developer/PyInstallerWork/uum.py
missing module named _winapi.STD_ERROR_HANDLE - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named _winapi.STARTF_USESHOWWINDOW - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named _winapi.STARTF_USESTDHANDLES - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named _winapi.CREATE_NEW_PROCESS_GROUP - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named _winapi.SW_HIDE - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named _winapi.CREATE_NEW_CONSOLE - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named _winapi.STD_INPUT_HANDLE - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named _winapi.STD_OUTPUT_HANDLE - imported by _winapi, subprocess, /Developer/PyInstallerWork/uum.py
missing module named builtins.str - imported by builtins, locale, /Developer/PyInstallerWork/uum.py
missing module named builtins.abs - imported by builtins, operator, /Developer/PyInstallerWork/uum.py
missing module named _operator.__doc__ - imported by _operator, operator, /Developer/PyInstallerWork/uum.py
missing module named _sre.MAXREPEAT - imported by _sre, sre_constants, sre_parse, sre_compile, /Developer/PyInstallerWork/uum.py
missing module named _functools.reduce - imported by _functools, functools, /Developer/PyInstallerWork/uum.py
missing module named _thread.get_ident - imported by _thread, reprlib, /Developer/PyInstallerWork/uum.py
missing module named _thread.allocate_lock - imported by _thread, _strptime, /Developer/PyInstallerWork/uum.py
missing module named _thread.stack_size - imported by _thread, threading, /Developer/PyInstallerWork/uum.py
missing module named _thread._local - imported by _thread, threading, /Developer/PyInstallerWork/uum.py
missing module named _thread.RLock - imported by _thread, functools, /Developer/PyInstallerWork/uum.py
missing module named _functools.cmp_to_key - imported by _functools, functools, /Developer/PyInstallerWork/uum.py
missing module named _functools.partial - imported by _functools, functools, /Developer/PyInstallerWork/uum.py
missing module named sys.modules - imported by sys, dummy_threading, /Developer/PyInstallerWork/uum.py
missing module named sys.maxsize - imported by sys, pickle, /Developer/PyInstallerWork/uum.py
missing module named unknown_module - imported by /Developer/PyInstallerWork/uum.py
~~~~

**Comment by htgoebel** [comment] 2017-02-26 18:49
PyInstaller works as designed. If you don't loike PyInstaller's cureent behaviour either submit a pull-request fixing it or simply don't use it.

**Comment by htgoebel** [comment] 2017-02-26 18:51
Addendum: A simple work-around for your problem is a script checking if `warn*.txt` contains a `missing module` line and in this case, fail.

**Comment by jenisys** [comment] 2017-02-26 21:36
Interesting. Instead of repeating my extremely simple procedure how to repeat my observations, you did something and did not describe the details. My procedure shows no warnings for ``missing modules ...``. Instead of a low-level indirect import, that is not really used, one of my primary, first-level imports is not even noticed.

So I tried to repeat "your procedure that was not described in detail". I installed Python3.6 on my MAC in  a virtualenv and installed pyinstaller-3.2.1. When I now run pyinstaller step from above, I get the problem as described in #2394 that pyinstaller modulegraph is stumbling over its own feet. This happens even when I use ``pyinstaller --clean hello_problem.spec``. And it did not fiddle with python byte-code nor did I specify any ``hiddenimports`` .

BUT: I newer get your missing module messages from above. 

Maybe it would have been helpful for me that you used ``pyinstaller -d hello_problem.spec`` and inspected the warnings-file afterwards. But still, primary imports are different from low-level indirect imports of the standard-library (that might not be used). And having a warning file is good for diagnostics, but no help when the normal build never sees it and must reverify that it works. 

**MY RESUMEE:**
pyinstaller is slightly better that than a dumb archiver, but leaves much room to become a reliable executable/bundle builder.

**Comment by codewarrior0** [comment] 2017-02-26 21:51
@jenisys Here is the core problem.

PyInstaller finds modules to bundle through static analysis, not through execution. Given a package named `module1`, and an import statement of the form `from module1 import name1, name2`, it is impossible to determine through static analysis, with absolute certainty, whether `name1` and `name2` are names within the scope of `module1`, or sub-modules contained by the package `module1`. Thus, when the names do not refer to sub-modules, "missing module" warnings are emitted for `module1.name1` and `module1.name2`, which would fail the build. 

That is just the obvious case. Static analysis also does not detect when `import module1` has effects on the interpreter's module-importing machinery, such as adding a `sys.modules` or `sys.path_hooks` entry that would make `import module2` work at runtime but be completely invisible to our static analysis.

We can trivially reject the case where `module1` is not a package and emit no "missing module" warnings in that case, but in most other cases, failing the build because of a "missing module" warning would be a mistake.

**Comment by htgoebel** [comment] 2017-02-27 01:41
@jenisys If you don't like it, just don't use it.. But stop trolling.
