### ISSUE TITLE
 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll 

### ISSUE THREAD

**Issue by flydaxia** [pyinstaller/pyinstaller#2268] opened 2016-11-15 14:11 UTC
Hello!

I found below error message **"WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency"** on the packing process. After I saw the leading guide and i found that i could not install pyWin32 on my compute. But I also read leading guide if install pypiwin32 along with "pip install pyinstaller" then not necessary to install pyWin32.  

So.. I think the problem not locate on the pyWin32. I guess it was my platform problme. By the way, My system was win 10 and python 3.5.2....

Beside, i could complie my py document into exe use "C:\pyinstaller.exe -F C:\my_exe". But when i run the exe that the error msg freeback to me for third part module  'APScheduler' not found. But i am sure i could work for no module and another third part module 'Bs4'

**Error msessage as below:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\huangzhu\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\apscheduler\__init__.py", line 2, in <module>
  File "site-packages\pkg_resources\__init__.py", line 535, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 415, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 943, in require
  File "site-packages\pkg_resources\__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'APScheduler' distribution was not found and is required by the application
Failed to execute script test**

## Is there any one for help?? Thanks a lot inadvance.

**Comment by fleytman** [comment] 2016-11-24 11:57
WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll
See: https://github.com/pyinstaller/pyinstaller/issues/1566

**Comment by htgoebel** [comment] 2017-09-12 09:48
Duplicate of #1566

**Closed by htgoebel** 2017-09-12 09:48 UTC
