### ISSUE TITLE
_tkinter.TclError: Tix data files missing

### ISSUE THREAD

**Issue by georgemunteanu** [pyinstaller/pyinstaller#1660] opened 2015-11-07 23:21 UTC
How can I bypass: _tkinter.TclError: can't find package Tix ?

```
from Tkinter import *
import ttk
from Tix import *

def splashScreen():
    root = Tk()
    root.overrideredirect(True)
    # Add label
    L1 = Label(root, text="Loading application ... ")
    L1.pack( side = TOP)
    # Center the window
    w = 410 # width for the Tk root
    h = 200 # height for the Tk root
    # get screen width and height
    ws = root.winfo_screenwidth() # width of the screen
    hs = root.winfo_screenheight() # height of the screen
    # calculate x and y coordinates for the Tk root window
    x = (ws/2) - (w/2)
    y = (hs/2) - (h/2)
    # set the dimensions of the screen 
    # and where it is placed
    root.geometry('%dx%d+%d+%d' % (w, h, x, y))
    # Add progress bar
    w=Meter(root, fillcolor='#009eff')
    w.pack()
    w.wait_visibility()
    max=3000.0
    maxi=3001
    for i in range(0,maxi):
           v=i/max
           w.config(value=v)
           w.update()
    root.destroy()
    root.mainloop()
splashScreen()
```

On running the .exe file, the system returns:

```
Traceback (most recent call last):
  File "<string>", line 78, in <module>
  File "<string>", line 7, in splashScreen
  File "C:\Python27\lib\lib-tk\Tix.py", line 221, in __init__
    self.tk.eval('package require Tix')
_tkinter.TclError: can't find package Tix
Tool returned -1 
```

NOTE: I am using: python 2.7.10. I am using pyinstaller: 3.0
NOTE: When running the .py in python IDLE, the app. works fine.
NOTE: I have tried -onefile and one-dir options. The same result.
NOTE: As a workaround I will use the progressbarObj from ttk.

Edit 1:
I am using: tix8.4.3

**Comment by matysek** [comment] 2015-11-10 22:30
@georgemunteanu look at these links:
* https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong
* https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by georgemunteanu** [comment] 2015-11-13 12:33
Hi. I have tried with different code snippets that include Tix widgets. 


=======================================
import Tix
root = Tix.Tk()
box = Tix.ButtonBox(root, orientation=Tix.HORIZONTAL)
box.add('a', text='test', underline=0, width=5)
box.pack(side=Tix.BOTTOM, fill=Tix.X)
root.mainloop()
==================================
Output: I got the same message.

**Comment by matysek** [comment] 2015-11-26 20:14
@georgemunteanu Have you tried the 'develop' version?

**Comment by SuperWangKai** [comment] 2015-11-30 13:27
I got the exact same problem, and I'm sure that the **tix folder is not packed into the distribution**.
In my environement (Win10 + Python34), the lacking folder is **"C:\Python34\tcl\tix8.4.3"**, if I put this folder into the dist directory, **the problem fixed**.
Currently, just FYI. I made some hack to the "hook-_tkinter.py" so I can get an one file EXE (I don't know if there is some way to pack the seperated files into a big exe after appending the tix folder manually).

**Comment by matysek** [comment] 2015-12-19 23:55
Yes, I confirm that the `tix` directory is really not bundled.

**Comment by htgoebel** [comment] 2016-03-06 12:16
@SuperWangKai Could you please share your changes to `hook-_tkinter.py` - most preferable as an pull-request, but a patch/diff would be fine. too

**Comment by theoneshaffer** [comment] 2016-04-01 02:12
I just had this issue, and spent some time working with the hook_tkinter.py file.  I was able to get Tix to complile to a single EXE, and then take that file to a computer without python installed and run it successfully.

I hat to insert the following to the top of the hook file:

import os
import sys

from PyInstaller.compat import is_win, is_darwin, is_unix, is_venv, base_prefix
from PyInstaller.compat import modname_tkinter
from PyInstaller.depend.bindepend import selectImports, getImports
from PyInstaller.building.datastruct import Tree
from PyInstaller.utils.hooks import exec_statement, logger

from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('package')

datas = [
            (sys.prefix+'\\DLLs\\tix84*.dll', 'dlls'),
            (sys.prefix+'\\tcl\\tix8.4.3', '/tcl/tix8.4.3'),
            (sys.prefix+'\\tcl\\tix8.4.3\\bitmaps', '/tcl/tix8.4.3/bitmaps'),
            (sys.prefix+'\\tcl\\tix8.4.3\\pref', '/tcl/tix8.4.3/pref')
           ]
		   
I'm guessing the problem is that the latest version of Tix changed the naming convention of some files, and you need to explicitly instruct the program on how to find the DLLs and .tcls
Environment: Python 2.7.11 x64, + Windows 10 + Tix 8.4.3 + Tk 8.5.18 + Pyinstaller3.1.1

Command run: pyinstaller "Config Generator.py" -F -c --hidden-import=Tix

There's probably some extraneous code in both the command and the hook, but I've been at this for a day and a half, and barely understand python.  If anyone comes up with a more elegant solution, let me know.

**Comment by MyreMylar** [comment] 2016-10-11 10:32
Still having this issue today using Tix. Not tried any manual hacks to fix it, mostly because I was just curious to see if pyInstaller would work on a script rather than being desperate to make it work.

I'm using python 3.4 on windows 10 and just grabbed pyInstaller with pip and ran a standard 'pyInstaller script_name.py'. 

Good luck fixing it!

**Comment by Luke25361** [comment] 2017-02-11 01:48
Huge thanks to theoneshaffer for their comment! So happy that I've finally managed to compile my program.
I had to modify their addition to tkinter's hook file slightly as it was producing a few errors.
I had to remove (sys.prefix+'\DLLs\tix84*.dll', 'dlls') from the datas list, as this dll doesn't seem to exist in my python installation. I also had to make the strings raw as there were parts containing \t which were being read as horizontal tabs.
My modified version:
`from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('package')

datas = [
(sys.prefix+r'\tcl\tix8.4.3', r'/tcl/tix8.4.3'),
(sys.prefix+r'\tcl\tix8.4.3\bitmaps', r'/tcl/tix8.4.3/bitmaps'),
(sys.prefix+r'\tcl\tix8.4.3\pref', r'/tcl/tix8.4.3/pref')
]`

**Comment by tallforasmurf** [comment] 2017-02-11 07:11
It is a very small point, but: is it really necessary to use backslashes in these paths? If you used `os.path.join()` instead of concatenating to `sys.prefix` could you use forward slashes?

**Comment by htgoebel** [comment] 2017-08-20 09:28
Closed by #1660. Thanks to @xoviat for that patch.

**Closed by htgoebel** 2017-08-20 09:28 UTC
Labels: hooks, Windows

**Comment by hamanthgousik** [comment] 2019-02-28 08:07
> I got the exact same problem, and I'm sure that the **tix folder is not packed into the distribution**.
> In my environement (Win10 + Python34 + pyinstaller3.0), the lacking folder is **"C:\Python34\tcl\tix8.4.3"**, if I put this folder into the dist directory, **the problem fixed**.
> Temporarily, just FYI. I made some hack to the "hook-_tkinter.py" so I can get an one file EXE (I don't know if there is some way to pack the seperated files into a big exe after appending the tix folder manually).



> I got the exact same problem, and I'm sure that the **tix folder is not packed into the distribution**.
> In my environement (Win10 + Python34 + pyinstaller3.0), the lacking folder is **"C:\Python34\tcl\tix8.4.3"**, if I put this folder into the dist directory, **the problem fixed**.
> Temporarily, just FYI. I made some hack to the "hook-_tkinter.py" so I can get an one file EXE (I don't know if there is some way to pack the seperated files into a big exe after appending the tix folder manually).

thanks for your reply @SuperWangKai  **It Worked!!!!!!**

**Comment by Igor1306** [comment] 2020-08-27 03:26
> 
> 
> I got the exact same problem, and I'm sure that the **tix folder is not packed into the distribution**.
> In my environement (Win10 + Python34 + pyinstaller3.0), the lacking folder is **"C:\Python34\tcl\tix8.4.3"**, if I put this folder into the dist directory, **the problem fixed**.
> Temporarily, just FYI. I made some hack to the "hook-_tkinter.py" so I can get an one file EXE (I don't know if there is some way to pack the seperated files into a big exe after appending the tix folder manually).

Thank you so much, you've saved my time !
