### ISSUE TITLE
UAC not working in onefile again, migrate old UAC test

### ISSUE THREAD

**Issue by moden-py** [pyinstaller/pyinstaller#1729] opened 2015-12-16 22:22 UTC
I am not able to create one file executable with UAC.
Here is the project I am trying to add the UAC window - https://github.com/pywinauto/SWAPY
`python27 latest-pyinstaller\pyinstaller.py --uac-admin -F swapy-ob.py`
Single exe file does not ask for Admin rights.

With `-D` works fine, since the manifest placed near the exe.

I've tried Python 2.7.x 32/64bit, PyInstaller from the master/develop/pip - it did not help.
Test `pyinstaller\tests\old_suite\interactive\test_onefile_win32_uac_admin.py` passed but produced an exe file without UAC request.

``` python
# -*- mode: python -*-

block_cipher = None


a = Analysis(['swapy-ob.py'],
             pathex=['PATH\\swapy'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             win_no_prefer_redirects=None,
             win_private_assemblies=None,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='swapy-ob',
          debug=False,
          strip=None,
          upx=True,
          console=True , uac_admin=True)
```

PS: I've read previous related issues, #853, etc.

**Comment by matysek** [comment] 2015-12-17 18:12
Does UAC work with just simple helloworld app?

**Comment by matysek** [comment] 2015-12-17 18:14
@codewarrior0 Do you have an idea how could we test the old test `test_onefile_win32_uac_admin.py` in appveyor?

**Comment by matysek** [comment] 2015-12-17 18:15
Just test it as other interactive tests - check if it keeps running for a period of time - supposing that it's waiting for the user to permit admin access?

**Comment by moden-py** [comment] 2015-12-17 19:02
Does not work with simple helloworld.
I noticed a strange behavior, if I take the manifest file from `helloworld\build\helloworld\` and place it near the onefile exe - UAC does not work(both has the same name, I expect it would). But if rename the exe and the manifest from the original name to a some the same name - UAC works properly.
For instance to `helloworld1.exe` and `helloworld1.exe.manifest`.
Rename back to the original name - does not work.
It is strange. It looks like the exe has broken embedded manifest, and it start work only if I rename from the original name and place a new manifest. But ResHaker shows no embedded manifest in the onefile exe.

[helloworld.zip](https://github.com/pyinstaller/pyinstaller/files/65816/helloworld.zip)
```
PATH\pyinstaller>pyinstaller.py -F --uac-admin helloworld.py
174 INFO: PyInstaller: 3.0
175 INFO: Python: 2.7.10
176 INFO: Platform: Windows-7-6.1.7601-SP1
```

**Comment by matysek** [comment] 2015-12-17 19:26
And the latest `develop` works for you?

**Comment by moden-py** [comment] 2015-12-17 19:28
@matysek, I have one idea how to deal with UAC in the tests.
I've just checked when UAC window is open I cannot catch it ;-) but I still can deal with UAC's accompanying windows. On my Win7 when UAC starts i see two new windows with classes:
1. TaskSwitcherWnd - also happens when you switch by Ctrl-Alt.
2. IME (text - Default IME) - Input Method Editor, the language change window.

I may check the behavior on appveyor CI tomorrow.

```python
import time
import pywinauto

app = pywinauto.application.Application()

old_windows = set(pywinauto.findwindows.find_windows(top_level_only=False, visible_only=False))

while True:
    new_windows = set(pywinauto.findwindows.find_windows(top_level_only=False, visible_only=False))
    difference = new_windows.difference(old_windows)
    if difference:
        print 'New windows'
        for nwh in difference:
            nw = app.window_(handle=nwh)
            print nw.Texts()
            print nw.Class()
            time.sleep(1)
    else:
        pass
    old_windows = new_windows
    time.sleep(0.1)
```

**Comment by moden-py** [comment] 2015-12-17 19:40
@matysek 
>And the latest develop works for you?
Unfortunately no.
Have just update to SHA-1: 93d25e563e49f88f5977afd9b6e26cb34bfb5efa

**Comment by codewarrior0** [comment] 2015-12-18 02:18
> Do you have an idea how could we test the old test `test_onefile_win32_uac_admin.py` in appveyor?

I'll take a look at reviving this test.

I've got a hunch about what's happening here. It's a catch-22.  

UAC options in the manifest only take effect if it is automatically loaded by Windows. The manifest automatically loaded by Windows cannot specify the MSVCRT libs because the onefile app needs to extract them to a tempdir.  The MSVCRT libs must be specified in the manifest marked as "process default". Any manifest automatically loaded by Windows becomes the "process default". Thus, the onedir app does not include a manifest that will be automatically loaded, and instead explicitly loads it with the WinAPI while passing a flag that marks it as the "process default" manifest.

**Comment by berwynhoyt** [comment] 2016-01-13 04:19
Here is a very simple reproduction of the same symptom (i.e. UAC does not work with onefile):
```
pyi-makespec --onefile helloworld.py
pyinstaller --uac-admin helloworld.spec
```
Any helloworld.py will do. A useful one in this case might be:
```python
import ctypes
print ctypes.windll.shell32.IsUserAnAdmin()
```
I'm using pyinstaller version 3.1. What's going on? There doesn't seem to be any manifest embedded in helloworld.exe at all.

Any help appreciated.

**Comment by dnides** [comment] 2016-04-13 15:52
Any update on this issue?

**Comment by themaxx75** [comment] 2016-04-13 18:49
Also have the issue with onefile option. I can check the compiled exe with Sigcheck -m and it shows no manifest. It still works in folder mode.
I also tried using the --manifest but it seems to be simply ignored.

**Comment by pipoupiwam** [comment] 2016-04-26 12:58
Same issue here, the uac_admin=True works fine when used with the COLLECT, but permission is not asked when in onefile mode.

**Comment by thanhmssl10** [comment] 2016-05-02 02:30
I found a workaround although I don't know exactly why it worked :smile: 

If you use `pyinstaller --onefile --uac-admin my_app.py` It will create a .spec file without COLLECT right? So I will add this below that .spec file, build again with that .spec file and I get a my_app folder with an exe file and a manifest file :smiley: 

```
coll = COLLECT(exe,
               strip=False,
               upx=True,
               name='my_app'
)
```
p/s: Don't forget `uac_admin=True` in exe = EXE .... :smile:

**Comment by FalcoSK** [comment] 2016-06-15 09:17
The current solution is using develop version of pyinstaller. Works fine for me.

**Comment by HyperBaton** [comment] 2016-06-15 12:03
I've just tried the develop version (3.3.dev0+d25657e), but to no avail. No admin rights are asked when producing a onefile executable.

**Comment by FalcoSK** [comment] 2016-06-15 12:09
Strange, I'm fine with it. This is my spec file: 

`
# -*- mode: python -*-

block_cipher = None


a = Analysis(['connector_source.py'],
             pathex=['*path*'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='connector',
          debug=False,
          strip=False,
          upx=True,
          console=False , uac_admin=True, icon='icon.ico')
coll = COLLECT(exe,
               strip=False,
               upx=True,
               name='connector)
`

**Comment by lanzorg** [comment] 2016-08-28 14:04
I have the same issue with python 3.5 (x64) and latest windows.
Is there a working fix?

**Comment by lanzorg** [comment] 2016-09-06 21:11
I tried with almost any recent python2 and python3 releases on my win10 and nothing works!
Are you working on a fix?

**Comment by sfantu** [comment] 2016-09-12 00:38
I have the same issue on python 2.7 pyinstaller 3.1.1 on windows 7

**Comment by NiklasRosenstein** [comment] 2016-12-07 15:11
Had the same Problem on CPython 3.4 with PyInstaller 3.2. Installed the dev tip and it worked.

    pip uninstall PyInstaller
    pip install git+https://github.com/pyinstaller/pyinstaller.git@develop

**Comment by AshleyJackson** [comment] 2016-12-07 22:29
So I actually ended up finding a work around for this. On any new install, instead of installing the latest version, I just install 3.0 and UAC works fine.

________________________________

**Comment by thiolliere** [comment] 2017-06-08 12:19
@NiklasRosenstein I installed develop and it stll don't work

**Comment by AshleyJackson** [comment] 2017-06-09 08:55
Interestingly enough, I am still using Pyinstaller 3.0.

Haven't been bothered checking with latest releases.

This is with building in latest 2.7 and 3.6.

**Comment by alvassin** [comment] 2017-06-14 14:20
Does not work with win 8.1 and python 3.5 as 3.0, as develop version.

**Comment by stevielb** [comment] 2018-05-14 22:10
Hey there! Currently having this problem using windows 10, python 2.7.14, and pyinstaller version 3.3.1. Any update on when this will be fixed?

**Comment by FalcoSK** [comment] 2018-05-15 05:49
The solution ia very simple, your executable needs manifest file in its working directory. The manifest file is being generated by pyinstaller when generating executable. Search for it, place it to your executable and  enjoy.

**Comment by stevielb** [comment] 2018-05-16 23:27
Thanks @FalcoSK ! So does that mean that there isn't a way though to generate a truly one-file executable with UAC prompt? It would always need this manifest file?

**Comment by AshleyJackson** [comment] 2018-05-16 23:29
On a sidenote: I haven’t used Pyinstaller in a long time, however I would wager a bet that you could still use V 3.0, and still get a OneFile that doesn’t require a manifest file.

When I initially figured this out, I just gave up on newer versions.

**Comment by stevielb** [comment] 2018-05-17 00:16
Unfortunately version 3.0 doesn't have --add-data support. It looks like this was added in 3.2.1. However, I have the same uac admin bug on version 3.2.1

**Comment by stevielb** [comment] 2018-05-17 02:04
This SO post seems relevant: Someone shows how to edit pyinstaller source to accept an input manifest file. Could this code change be committed?

https://stackoverflow.com/questions/13964909/setting-uac-to-requireadministrator-using-pyinstaller-onefile-option-and-manifes

**Comment by FalcoSK** [comment] 2018-05-17 07:42
@stevielb To be honest, I have no much knowledge about manifest files in windows. However, I think it should be side by side with the application so OS knows the basic information how to handle the application. Therefore if it is bundled in the application itself it makes no sense if the application is not somehow standard and familiar for windows. I mean pyinstaller is some kind of very "raw" tool to create "fake" exe files. The exe file itself decompress its context and then just launch python with your python code. So it is not standard win32 application. So OS needs to know something like: "hey there, I am a non-standard garbage, just let me elevate to admin and do whatever I want". 

I used pyinstaller like a year ago for the last time, but I was fine with the manifest file as all my applications were bundled to installer (innosetup) and included also other files needed to run (configs, manifest, dlls, etc.). 

My innosetup config for example. In addition, not related to this topic, I always include msvcr100.dll to my application so it can decompress itself even if client doesn't have runtime files (often happens even in 2018)

`; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "xxxxxxxxxxx"
#define MyAppVersion "1.3"
#define MyAppPublisher "xxxxxxxxxxx"
#define MyAppExeName "connector.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{xxxxxxxxxxx}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\_temp
OutputBaseFilename=xxxxxxxxxxx
SetupIconFile=C:\_temp\main.ico
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\_temp\dist\connector.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\_temp\build\connector\connector.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\_temp\msvcr100.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

`

**Comment by stevielb** [comment] 2018-05-18 01:30
Hi @FalcoSK , Thanks for the tip and demonstration on how to use innosetup, and the tip on msvcr100.dll. That might be a really good way to go! I'll check in out and see if it could meet my project's needs.

To your point on the manifest, it is possible to embed the manifest file straight into the executable, which is what I was after. This can be done from the commandline using a windows tool called "mt". But in this case, it isn't the end result pyinstaller exe which needs the embedded manifest, it is the one which is launched after pyinstaller does it's unzipping of contents and kicks off process running the application Perhaps they actually are the same process. When I tried using mt to directly embed the manifest, it did not work.

**Comment by slw07g** [comment] 2018-06-22 16:25
I also was not able to successfully use my exe after using mt.exe to embed the manifest.

**Comment by htgoebel** [comment] 2018-07-09 07:54
Hello guys, I'm a bit disappointed: There seems to be (nearly) nobody understanding the cause of the issue and nobody seems to be willed to provide a pull-request. Instead there are rumors, links to hacks valid for a 5-year-outdated version, etc.

Is there no Windows developer out there able to solve this? Come on guys!

**Closed** 2019-02-27 12:08 UTC
Labels: Windows
