### ISSUE TITLE
Cannot find libpython when running from a symlink

### ISSUE THREAD

**Issue by vsalvino** [pyinstaller/pyinstaller#4674] opened 2020-02-08 19:46 UTC
## Description of the issue
Program built with PyInstaller 3.6 (or develop) cannot load libpython when run via a symlink on Linux. This same behavior works fine on programs build with PyInstaller 3.5

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7
* Platform: Debian 9 (GNU/Linux)
* Did you also try this on another platform? Does it work there? No, it was build on Debian 9 and run on the same system (on a different machine but exact same OS).

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

I have created an extremely simple 2 line program that illustrates this problem, which can be run with Docker. Copy the dockerfile below to `PyInstaller.dockerfile`:

```Dockerfile
FROM python:3.7-stretch

RUN set -eux ;\
    #
    # Make a python program
    echo "import sys\nprint(sys.version)" > myprogram.py ;\
    cat myprogram.py ;\
    #
    # Test our program
    python myprogram.py ;\
    #
    # Bundle with pyinstaller
    mkdir /dist/ ;\
    pip install pyinstaller==3.6.* ;\
    pyinstaller --version ;\
    pyinstaller myprogram.py \
        --name "myprogram" \
        --clean \
        --onedir \
        --noupx \
        --debug all \
        --distpath /dist/ \
    ;\
    ls -lh /dist/ ;\
    chmod -R 777 /dist/ ;\
    #
    # Run from output
    /dist/myprogram/myprogram ;\
    #
    # Run from symlink, see error.
    ln -sf /dist/myprogram/myprogram /usr/bin/ ;\
    myprogram ;
```
Then run the Dockerfile as so, and watch the output:
```
docker build -f PyInstaller.dockerfile .
```

### Stacktrace / full error message
First, link the executable:
```
sudo ln -sf /opt/pyinstaller-dir/myprogram /usr/bin/
```
Now, run the program from the symlink
```
$ myprogram
Error loading Python lib '/usr/bin/libpython3.7m.so.1.0': dlopen: /usr/bin/libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```
However, if you run the program directly, without a symlink, it works:

```
$ /opt/pyinstaller-dir/myprogram
Normal output, exit code 0.
```

The program does run correctly from the symlink when built with PyInstaller 3.5.

**Comment by Legorooj** [comment] 2020-02-08 22:20
Hmm this looks system specific, and if it didn't cause the error on an older version...

I know Linux as well as anybody who uses windows as their primary OS would, but this is a problem for @htgoebel

**Comment by troyready** [comment] 2020-02-21 07:01
Can confirm the same issue, getting the `Error loading Python lib '<symlinkdir>/libpython3.7m.so.1.0': dlopen: <symlinkdir>/libpython3.7m.so.1.0: cannot open shared object file: No such file or directory` on any linux system. Error does not appear to be occurring on macOS systems that we've tested.

**Comment by arielvb** [comment] 2020-03-27 16:29
I have the same issue, although using **Python 3.6** on CentOS 7. 

As mentioned, it works as expected when using PyInstaller 3.5.

**Comment by mancej** [comment] 2020-07-01 00:28
I am also experiencing this issue.

**Comment by xaviergmail** [comment] 2020-07-18 05:27
I also ran into this on both python 3.8 and 3.9 today

**Comment by Legorooj** [comment] 2020-07-18 11:52
@xaviergmail just so you know python 3.8 and 3.9 are unsupported as of this time. Support is coming for the first soon though, and 3.9 should be easier. There's fewer changes. (Unsupported=bug reports/support requests are not accepted yet. If you get it working, then great!)

**Comment by nirousseau** [comment] 2020-08-07 10:27
I am also facing this issue with **PyInstaller 3.6** with onedir bundling and symlinks. As mentioned by @arielvb , downgrading to **PyInstaller 3.5** did the trick.

**Comment by Legorooj** [comment] 2020-08-07 12:16
@bwoodsend can you `git bisect` to figure this one out?

**Comment by bwoodsend** [comment] 2020-08-07 14:28
Git bisect says be948cf0954707671aa499da17b10c86b6fa5e5c which is `rebuild bootloader` so it must be one of the bootloader commits before then. I'll retry but recompiling the bootloader each time. 

From playing with the error myself I'm pretty certain that @xaviergmail is correct.

**Comment by bwoodsend** [comment] 2020-08-07 15:16
I can confirm that ebcd49cc387cc599bf003a2b9d91e2643a5a65be is the breaking commit (as xavier predicted).

**Comment by bwoodsend** [comment] 2020-08-08 15:48
@Legorooj Can I get your thoughts on this?

It looks like fixing this would involve reverting [Bootloader: Ensure that symlinks to binaries do not get resolved. #3829 ](https://github.com/pyinstaller/pyinstaller/pull/3829). Unless we could somehow use both resolved and unresolved paths? I.e resolve the path to work out where `libpython3...` is but keep the original for everything else.

To be honest I don't understand the motivation for not resolving symlinks.

**Comment by xaviergmail** [comment] 2020-08-08 20:44
I personally use a private npm registry for lack of a better alternative (even though none of these packages actually use javascript) to install packages on certain machines. My use case for PyInstaller is to avoid the headache of having to maintain a second private package registry for my Python tools and to guarantee the same python environment at runtime. My tools are built with CI into a `dist` folder, and then published to the npm registry. 

My package.json makes use of the `bin` field to let npm install these binaries into PATH: `"bin": "./dist/project/resulting_binary"`. npm creates a symlink from `/usr/local/bin/resulting_binary-> ../lib/node_modules/@private/project/dist/project/resulting_binary` **(so it is a relative symlink)**

Quoting from #3829, it seems that this was done in order for the process name to report its original invocation
>As far as I understand; the current behavior is wrong: when doing execvp() we are passing the resolved argv[0]. This means that the name under /proc/self/status will be incorrect. 

I can understand the reasoning behind the original pull request. It seems to be standard behavior for the name to not be resolved. However, this functionality should not break invoking PyInstaller executables from symbolic links and a solution needs to be found.

<details>
<summary>I've created a basic C++ program to confirm the aforementioned behavior. Click to expand.</summary>
<p>

### C++ Code

```cpp
#include <iostream>
#include <fstream>

int main() {
    std::ifstream stat("/proc/self/status");
    std::string line;

    while (std::getline(stat, line))
    {
        if (line.find("Name") != std::string::npos)
            std::cout << line << std::endl;
    }


    return 0;
}
```

### Output
```
~/projects/pyinstallertest
❯ ll
total 32K
drwxr-xr-x  2 xavier xavier 4.0K Aug  8 12:55 .
drwxr-xr-x 41 xavier xavier 4.0K Aug  8 11:46 ..
-rwxr-xr-x  1 xavier xavier  18K Aug  8 12:55 a.out
lrwxrwxrwx  1 xavier xavier    5 Aug  8 12:55 b.out -> a.out
-rw-r--r--  1 xavier xavier  284 Aug  8 12:55 main.cpp

~/projects/pyinstallertest
❯ ./a.out && ./b.out
Name:	a.out
Name:	b.out

~/projects/pyinstallertest
❯ cd ..

~/projects
❯ /home/xavier/projects/pyinstallertest/a.out && /home/xavier/projects/pyinstallertest/b.out
Name:	a.out
Name:	b.out
```
</p>
</details

**Comment by Legorooj** [comment] 2020-08-09 06:11
I'll take a look at this more thoroughly in a few days. Chances are I'll just monkey-patch the old behaviour for `libpython`.

**Closed** 2020-12-02 10:58 UTC
Labels: @medium, Python:3.7, area:bootloader, bug, platform:Linux, pull-request wanted, state:verify

**Comment by vsalvino** [comment] 2020-12-02 16:34
Thanks for all the hard work @Legorooj, @rokm, and everyone getting this fixed!

Do you know with which version this will be released?

**Comment by bwoodsend** [comment] 2020-12-02 16:41
It'll be 4.2 which is probably going to be a while away. @Legorooj Perhaps once we've merged the rest of Rok's bootloader changes we could rebuild the bootloaders so everyone here can at least install from github?

**Comment by Legorooj** [comment] 2020-12-04 10:35
Yeah, I should be able to rebuild them shortly once I get my Linux PC up and running again.
