### ISSUE TITLE
Current method of adding conditional dependency on dis3 is broken

### ISSUE THREAD

**Issue by JonathonReinhart** [pyinstaller/pyinstaller#4268] opened 2019-06-11 17:33 UTC
# Problem

Currently (as of 3.4) PyInstaller's `setup.py` does this to include `dis3` only on Python 2:

https://github.com/pyinstaller/pyinstaller/blob/v3.4/setup.py#L31-L32

In this comment: https://github.com/pyinstaller/pyinstaller/issues/3731#issuecomment-420176317 

@htgoebel said:

> The wheel is broken, I removed it just a few minutes ago. Please install PyInstaller again using
>
>     pip install --force-reinstall --no-binary :all: pyinstaller
>
> This should install from source.

The problem goes further than wheels hosted on PyPI.  I just encountered a case in a Dockerfile where I essentially do:
```
pip3 install PyInstaller==3.4
pip2 install PyInstaller==3.4
```

When `pip3` runs, it builds a wheel (`PyInstaller-3.4-py2.py3-none-any.whl`) and caches it locally. The problem is that because it was built under Python 3, `PyInstaller-3.4.dist-info/metadata.json` does *not* include `dis3` in the `requires` block. Then when `pip2` runs, it uses the (broken) cached wheel.

This is likely the root cause of #3731 and #3789.

# Solutions

This is surprising, and difficult to track down. I think PyInstaller could take a more proactive approach to avoiding this by one of the following solutions:

### Forbid a wheel from being built
I'm not sure if this is even possible.

### Use PEP 508 Environment Markers
See https://github.com/JonathonReinhart/staticx/issues/45 where I dealt with a nearly identical problem.

The solution is simple, now that the tooling has been updated:
https://github.com/JonathonReinhart/staticx/blob/2dc7ce2d92c27cbdfca3c4a2f2467049582a4bf9/setup.py#L86

In the worst case, a Python 3 user running a really old version of pip will end up with `dis3` installed, which won't be used.

**Comment by htgoebel** [comment] 2019-08-07 14:54
Thanks for this detailed analysis. While this is absolutely correct, it does not hit the root cause - or there have been several root causes :-)

In PyInstaller 3.4 `setup.cfg` stated `[bdist_wheel] universal=1` - which was plain wrong since ther are different dependencies fpr Python 2 and Python 3. The current release does not include this any more, thus different wheel are generated for each version of Python (2.7, 3.5, 3.6, …).Thus I assume we can close this ticket.

Unfortunately I did not see this issue until now, otherwise I would have published a 3.4p1 release with setup.cfg fixes. Sorry for any inconvenence caused by this.

**Closed by htgoebel** 2019-08-07 14:54 UTC
