### ISSUE TITLE
os.makedirs error

### ISSUE THREAD

**Issue by SteveDoyle2** [pyinstaller/pyinstaller#1765] opened 2016-01-14 19:46 UTC
I was previously able to build my software using pyInstaller 3.0, but 3.1 does not work.  It seems like there was a simple bug regarding folder creation.  Please see the traceback for further information.

Note that I deleted the build and dist folders prior to running:

> > C:\Anaconda\Scripts\pyinstaller.exe pyNastranGUI.spec

What's also strange is I get a single file non-functional GUI, which is my last step.

Some system information:
 Windows 7 64 bit
 Anaconda Python 2.7.11; 64 bit

```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller', 'console_scripts', 'pyinstaller')()
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\building\build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\building\build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 61, in <module>
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\building\datastruct.py", line 183, in __postinit__
    self.assemble()
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\building\build_main.py", line 461, in assemble
    self.zipped_data.extend(deps_proc.make_zipped_data_toc())
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\building\toc_conversion.py", line 151, in make_zipped_data_toc

    tree = self.__collect_data_files_from_zip(dist.location)
  File "c:\nasa\m4\formats\git\pynastran\dev\pyinstaller-3.1\PyInstaller\building\toc_conversion.py", line 135, in __collect_data_files
_from_zip
    os.makedirs(workpath)
  File "C:\Anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\git\\pyNastran\\dev\\build\\pyNastranGUI\\docopt-0.6.2-py2.7.egg'
```

**Comment by htgoebel** [comment] 2016-01-17 15:08
Please provide a *minimal* example and a list of requirements, so be can try to reproduce it.

**Comment by SteveDoyle2** [comment] 2016-01-30 01:50
Here is a one line test script with a longer spec file and various pacakges per conda.  From what I can tell, it's the fault of docopt, but at one point, I also had setuptools throwing the same error.

[conda_list.txt](https://github.com/pyinstaller/pyinstaller/files/110619/conda_list.txt)
[spike_py.txt](https://github.com/pyinstaller/pyinstaller/files/110620/spike_py.txt)
[test_spec.txt](https://github.com/pyinstaller/pyinstaller/files/110621/test_spec.txt)
[spec_log.txt](https://github.com/pyinstaller/pyinstaller/files/110623/spec_log.txt)

``conda_list.txt`` is a list of the currently installed Python packages

``spike_py.txt`` should be renamed ``spike.py``

``test_spec.txt`` should be renamed ``test.spec``

``spec_log.txt`` is just the log file with the ``-d`` flag

**Comment by tshirtman** [comment] 2016-02-22 10:31
seems i'm hitting this with setuptools too, i was able to build in the same configuration before, but since i needed a recent version of pyinstaller, i'm using git version of it, and it stopped working some time between early january and now (was not working on the software in the mean time, so no CI test).

**Comment by Ailete619** [comment] 2016-06-16 06:46
Same situation here, but on Windows 10 64bits, on Anaconda 2.7 64bits, it chokes on setuptools 19.2 (which is also a downgrade or pyinstaller throws another error ...).

Works with pyinstaller 3.0, but throws the same error with 3.1 or 3.2, here is the complete dump for version 3.1 :

    You are using pip version 8.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    C:\Users\ailete\workspace\landema>pyinstaller.exe --onefile --windowed main.py
    92 INFO: PyInstaller: 3.1
    93 INFO: Python: 2.7.11
    95 INFO: Platform: Windows-10-10.0.10586
    98 INFO: wrote C:\Users\ailete\workspace\landema\main.spec
    105 INFO: UPX is not available.
    110 INFO: Extending PYTHONPATH with paths
    ['C:\\Users\\ailete\\workspace\\landema',
    'C:\\Users\\ailete\\workspace\\landema']
    115 INFO: checking Analysis
    123 INFO: Building because inputs changed
    126 INFO: Initializing module dependency graph...
    134 INFO: Initializing module graph hooks...
    310 INFO: running Analysis out00-Analysis.toc
    316 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\users\ailete\anaconda2\python.exe
    579 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
    586 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
    595 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_acd40623e1d81331.manifest
    843 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9177_none ...
    848 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3.manifest
    858 INFO: Searching for file msvcr90.dll
    859 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3\msvcr90.dll
    865 INFO: Searching for file msvcp90.dll
    866 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3\msvcp90.dll
    871 INFO: Searching for file msvcm90.dll
    873 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3\msvcm90.dll
    1212 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
    1221 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
    1230 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_acd40623e1d81331.manifest
    1238 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9177)
    1418 INFO: Analyzing C:\Users\ailete\workspace\landema\main.py
    9322 INFO: Processing pre-find module path hook   distutils
    9950 INFO: Processing pre-safe import module hook   _xmlplus
    16145 INFO: Processing pre-safe import module hook   six.moves
    19710 INFO: Looking for import hooks ...
    19720 INFO: Processing hook   hook-distutils.py
    19723 INFO: Processing hook   hook-sysconfig.py
    19728 INFO: Processing hook   hook-xml.py
    19985 INFO: Processing hook   hook-cryptography.py
    19994 INFO: Processing hook   hook-jinja2.py
    20031 INFO: Processing hook   hook-httplib.py
    20033 INFO: Processing hook   hook-paste.exceptions.reporter.py
    20039 INFO: Processing hook   hook-pytz.py
    20276 INFO: Processing hook   hook-encodings.py
    20937 INFO: Processing hook   hook-babel.py
    Traceback (most recent call last):
      File "c:\users\ailete\anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
      File "c:\users\ailete\anaconda2\lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\Users\ailete\Anaconda2\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\__main__.py", line 90, in run
         run_build(pyi_config, spec_file, **vars(args))
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
         build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
       File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
         exec(text, spec_namespace)
      File "<string>", line 16, in <module>
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
        self.__postinit__()
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
        self.assemble()
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 461, in assemble
    self.zipped_data.extend(deps_proc.make_zipped_data_toc())
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\building\toc_conversion.py", line 151, in make_zipped_data_toc
        tree = self.__collect_data_files_from_zip(dist.location)
      File "c:\users\ailete\anaconda2\lib\site-packages\PyInstaller\building\toc_conversion.py", line 135, in __collect_data_files_from_zip
        os.makedirs(workpath)
      File "c:\users\ailete\anaconda2\lib\os.py", line 157, in makedirs
        mkdir(name, mode)
    WindowsError: [Error 183] Impossible de crÚer un fichier dÚjÓ existant: 'C:\\Users\\ailete\\workspace\\landema\\build\\main\\setuptools-19.2-py2.7.egg'

**Comment by tshirtman** [comment] 2016-08-31 18:33
this seems to have been addressed in fa71f4420bd0b617f4f7d45a2d5c4fe2bbeeebb4 testing…

**Comment by jmason86** [comment] 2017-03-27 21:37
Same issue but my error log doesn't mention anything about setuptools. It completes to 

13870 INFO: moving BUNDLE data files to Resource directory

but the app crashes on launch. I've narrowed the code down to an os.makedirs call, just like the OP. 

I'm using pyinstaller version 3.2.1.

**Comment by jmason86** [comment] 2017-03-27 22:01
Looks like for me it's a permissions issue. If I run the app with sudo, it launches and remains open.

**Comment by htgoebel** [comment] 2017-03-28 08:38
@jmason86 Your issue is a *totally* different one: the *frozen* application fails. In the OP's case PyInstaller failed. Please file a new issue, providing *all* the information requested by the template. (But I doubt this has anything to to with PyInstaller.)

**Comment by htgoebel** [comment] 2017-03-28 08:40
@tshirtman @Ailete619 Is this still an issue with 3.2.1 or the current develoment snapshot?

**Comment by Ailete619** [comment] 2017-03-29 01:50
Sorry,  I did not retry recently, I found a combination of versions that works on some forum ... I don't have time to test that right now but once I get the chance I will try to test it and get back to you

**Comment by htgoebel** [comment] 2017-03-29 08:41
So I take this as "fixed".

**Closed by htgoebel** 2017-03-29 08:41 UTC
Labels: v3.1, works for me

**Comment by Kristey** [comment] 2017-07-14 00:59
I have the same problem
But I used  Python: 3.6.1

C:\Users\PyroChrisWiN\PycharmProjects\ShowSim_Blackyard_4_PyroledaF3\EXE>pyinstaller GUI.py
124 INFO: PyInstaller: 3.2.1
124 INFO: Python: 3.6.1
125 INFO: Platform: Windows-10-10.0.15063-SP0
130 INFO: wrote C:\Users\PyroChrisWiN\PycharmProjects\ShowSim_Blackyard_4_PyroledaF3\EXE\GUI.spec
132 INFO: UPX is not available.
135 INFO: Extending PYTHONPATH with paths
['C:\\Users\\PyroChrisWiN\\PycharmProjects\\ShowSim_Blackyard_4_PyroledaF3\\EXE',
 'C:\\Users\\PyroChrisWiN\\PycharmProjects\\ShowSim_Blackyard_4_PyroledaF3\\EXE']
136 INFO: checking Analysis
136 INFO: Building Analysis because out00-Analysis.toc is non existent
136 INFO: Initializing module dependency graph...
138 INFO: Initializing module graph hooks...
141 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\PyroChrisWiN\AppData\Local\Programs\Python\Python36-32\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\depend\analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "c:\users\pyrochriswin\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range

**Comment by htgoebel** [comment] 2017-07-31 08:22
> But I used Python: 3.6.1

PyInstaller 3.21. **does not** support Python 3.6
