### ISSUE TITLE
Use of pathlib in docs

### ISSUE THREAD

**Issue by dennisvang** [pyinstaller/pyinstaller#6613] opened 2022-02-22 09:47 UTC
**Is your feature request related to a problem? Please describe.**

The documentation for "runtime information" has two examples of `pathlib` usage with `__file__`, viz. [here](https://github.com/pyinstaller/pyinstaller/blame/develop/doc/runtime-information.rst#L74) and [here](https://github.com/pyinstaller/pyinstaller/blame/develop/doc/runtime-information.rst#L104).

These examples suggest the following `os.path` an `pathlib` implementations are equivalent:

```python
from os import path
bundle_dir = path.abspath(path.dirname(__file__))
path_to_dat = path.join(bundle_dir, 'other-file.dat')
```
equivalent to
```python
from pathlib import Path
bundle_dir = Path(__file__).parent
path_to_dat = Path.cwd() / bundle_dir / "other-file.dat"
```
and

```python
from os import path
path_to_dat = path.abspath(path.join(path.dirname(__file__), 'file.dat'))
```
equivalent to
```python
from pathlib import Path
path_to_dat = (Path.cwd() / __file__).with_name("file.dat")
```

I find these a bit confusing, due to the use of `Path.cwd()` in the `pathlib` examples.

**Describe the solution you'd like**

Couldn't both examples be replaced by the following `pathlib` implementation? Wouldn't that be more idiomatic?

Also see [correspondence-to-tools-in-the-os-module](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module) in the `pathlib` docs.

```python
from pathlib import Path
path_to_dat = Path(__file__).resolve().with_name("file.dat")  # or "other-file.dat"
```
I would be willing to write a PR.

**Comment by rokm** [comment] 2022-02-22 14:42
I suspect the `Path.cwd()` is there due to earlier python versions, where `__file__` could be a relative path depending on circumstances (in the unfrozen program).

For example, `__main__.__file__` is a relative path under python 3.7 and 3.8 if you run `python script.py` or `python ../script.py` (but even in this case, it is absolute from 3.9 on).

**Comment by rokm** [comment] 2022-02-22 14:42
But FWIW, those `Path.cwd()` do throw me off every time I see them...

**Comment by rokm** [comment] 2022-02-22 15:10
Now that I think about it, you're right - `Path.resolve()` solves the problem of potential relative path, so your proposed fix is indeed nicer to read.

**Comment by dennisvang** [comment] 2022-02-22 16:22
@rokm Thanks. I created a PR with the suggested modifications.

**Comment by bwoodsend** [comment] 2022-02-22 17:11
We had this conversation when we added that line [here](https://github.com/pyinstaller/pyinstaller/pull/5206#discussion_r497442959) where we unearthed that [Path().resolve() doesn't always do anything whereas Path().absolute()](https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/16) does and that `Path.absolute()` is an undocumented equivalent to the ugly and counterintuitive line `Path.cwd() / "relative/path"`. That's why the docs ended up using that. Now I can no longer reproduce the bug where `Path("x").resolve()` yields only `Path("x")` so presumably it's been fixed and the docs can switch to using `.resolve()` as you suggest.

**Comment by dennisvang** [comment] 2022-02-22 20:20
> We had this conversation when we added that line [here](https://github.com/pyinstaller/pyinstaller/pull/5206#discussion_r497442959) where we unearthed that [Path().resolve() doesn't always do anything whereas Path().absolute()](https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/16) does and that `Path.absolute()` is an undocumented equivalent to the ugly and counterintuitive line `Path.cwd() / "relative/path"`. That's why the docs ended up using that. Now I can no longer reproduce the bug where `Path("x").resolve()` yields only `Path("x")` so presumably it's been fixed and the docs can switch to using `.resolve()` as you suggest.

The discussion refers to [this bug (now closed)](https://bugs.python.org/issue38671) on Windows, where `resolve()` returns a relative path if the entry does not exist.

I can still reproduce this using `Path("x").resolve().is_absolute()` in Python 3.8.12 on Windows, but not in Python 3.9.9. 

However, I wonder, does it matter in the case of `Path(__file__).resolve()`? Can `__file__` ever contain a path to a "non-existent" entry?

**Comment by rokm** [comment] 2022-02-22 20:32
> However, I wonder, does it matter in the case of `Path(__file__).resolve()`? Can `__file__` ever contain a path to a "non-existent" entry?

In a frozen application, `__file__` tends to point to non-existing files (i.e., the .pyc files as they would be on disk if they were not, in fact, collected in the PYZ archive) - this is necessary precisely so that other resources can be still discovered. But on the other hand, in frozen application, `__file__` should be always absolute, so it probably does not matter.

**Comment by dennisvang** [comment] 2022-02-22 20:44
@rokm Ah, now I see. The [docs](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file) do indeed mention that `__file__` in a bundle will point to a `.pyc` file, but I did not realize that could/would be non-existing. Thanks for clarifying!

**Closed as completed** 2022-02-22 21:02 UTC
Labels: area:documentation
