### ISSUE TITLE
Matplotlib: maximum recursion depth exceeded / modulegraph

### ISSUE THREAD

**Issue by Luispain** [pyinstaller/pyinstaller#1289] opened 2015-06-06 09:38 UTC
Hello guys!

This is my what I'm using:

 - Python 3.4.3 windows distribution "Anaconda 2.2.0 (64-bit)".
 - Matplotlib version 1.4.3
 - Numpy version 1.6
 - Pyinstaller version 3.0.dev0-py3.4

When I try to make an executable of a python file that makes a matplotlib figure, it issues a "maximum recursion depth exceeded". The code I want to compile is:

    import matplotlib.pyplot as plt

    x = [0, 1, 2, 3, 4]
    y = [0, 1, 4, 9, 16]

    plt.plot(x, y)
    plt.show()

I compile it using:

    pyinstaller -F plottest.py

But I get the following error:

    ...
    File "C:\Anaconda3\lib\ast.py", line 245, in visit
      return visitor(node)
    File "C:\Anaconda3\lib\ast.py", line 255, in generic_visit
      self.visit(value)
    File "C:\Anaconda3\lib\ast.py", line 245, in visit
      return visitor(node)
    File "C:\Anaconda3\lib\ast.py", line 249, in generic_visit
      for field, value in iter_fields(node):
    RuntimeError: maximum recursion depth exceeded

Any help would be greately apreciated!

**Comment by htgoebel** [comment] 2015-06-22 10:37
In which part of PyInstaller is this happening? There should be some pyinstaller module in the traceback. Please also follow https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.

**Comment by htgoebel** [comment] 2015-06-22 10:38
BTW: There is no Pyinstaller version "3.0.dev0-py3.4".

**Comment by Godsmith** [comment] 2015-07-01 06:33
I have an identical setup and I get the same error when trying to import pandas. 

Python 3.4.3 windows distribution "Anaconda 2.2.0 (64-bit)" and pyinstaller===3.0dev-6a3dad3 (I got it from the python 3 branch yesterday).

pandas_test.py: 
   
    import pandas

    print("hello world")

Command:

    pyinstaller -F pandas_test.py

Output: http://pastebin.com/q66BfXH5


Thanks in advance!

**Comment by htgoebel** [comment] 2015-07-04 11:01
This is the relevant part of the stacktrace:
```
72971 INFO: Processing hook   hook-IPython.py
Traceback (most recent call last):
...
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\build.py", line 717, in assemble
    self.graph.import_hook(item, from_node)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 924, in import_hook
    m = self._load_tail(q, tail)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1029, in _load_tail
    result = self._import_module(head, mname, result)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1105, in _import_module
    m = self._load_module(fqname, fp, pathname, stuff)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1178, in _load_module
    self._scan_code(co, m)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1251, in _scan_code
    self._scan_ast(co, m)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1260, in _scan_ast
    visitor.visit(co)
  File "c:\Anaconda3\lib\ast.py", line 245, in visit
    return visitor(node)
  File "c:\Anaconda3\lib\ast.py", line 253, in generic_visit
    self.visit(item)
  File "c:\Anaconda3\lib\ast.py", line 245, in visit
    return visitor(node)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 629, in visit_Try
    self.generic_visit(node)
  File "c:\Anaconda3\lib\ast.py", line 253, in generic_visit
    self.visit(item)
  File "c:\Anaconda3\lib\ast.py", line 245, in visit
    return visitor(node)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 615, in visit_ImportFrom
    self._process_import(node.module or '', _ast_names(node.names), level)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 600, in _process_import
    fromlist=False,
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1193, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 923, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1007, in _find_head_package
    q = self._import_module(head, qname, parent)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1105, in _import_module
    m = self._load_module(fqname, fp, pathname, stuff)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1131, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1397, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1178, in _load_module
    self._scan_code(co, m)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1251, in _scan_code
    self._scan_ast(co, m)
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1260, in _scan_ast
    visitor.visit(co)
```
and then it is recursing.

**Comment by htgoebel** [comment] 2015-07-04 11:05
@Luispain @Godsmith Would you please be so kind and add some debugging like
``` 
   print(node.module or '', _ast_names(node.names), level, file=sys.stderr)
```
to just in front of this place:
  File "c:\Anaconda3\lib\site-packages\pyinstaller-3.0dev_6a3dad3-py3.4.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 615, in visit_ImportFrom
And report the results. Thanks.

**Comment by Luispain** [comment] 2015-07-04 12:53
@htgoebel Thank you for your reply. I made what you said and herein I show you the link of the last 1010 lines of the traceback:

http://pastebin.com/imLG6Ezz

btw, is there a way to copy the full traceback right from the beginning?

**Comment by htgoebel** [comment] 2015-07-05 17:49
@Luispain Thanks for your quick reply :-)
> btw, is there a way to copy the full traceback right from the beginning?

AFAIR one can change the number of lines the cmd-window remembers in the comd-winodw' properties (seach for some settings in the menu). Or you may redirect the whole output to a file. `pyinstaller -F pandas_test.py > log.txt 2>&1` should do the trick on windows, too.

I wonder why all the other calls to `visit_ImportFrom` are missing in the traceback.

As it looks, the error occurs when importing tornado.util. So could you try if it occurs with a simple program like this, too:
``` python
import tornado.util
print("hello world")
```

**Comment by Luispain** [comment] 2015-07-10 11:41
@htgoebel Thank you for the tip. I did exactly what you mention, and the result was succesful. It correctly compiled pandas_test.exe and showed "hello world". Here is  the stacktrace: http://pastebin.com/r2DfVH9w .

**Comment by htgoebel** [comment] 2015-07-17 09:10
Hmm, `tornado.util` seams not to cause the problem. We'll have to investigate this further.

**Comment by matysek** [comment] 2015-07-31 21:43
I tried to reproduce this with matplotlib on Win7, 32bit Python 3.4 with latest 'python3'. But it works for me. Unable to reproduce.

**Comment by Csega** [comment] 2015-08-02 19:15
I have the same problem with #1365 and it stayed the same as before by using the latest commit (this one: https://github.com/pyinstaller/pyinstaller/commit/4071aa974d8b83cdc82eece1e97eb66bbdca3a92). What should I do now?

**Comment by matysek** [comment] 2015-08-05 14:58
The recursion depth is probably a modulegraph issue that was fixed recently: https://bitbucket.org/ronaldoussoren/modulegraph/commits/d1ab16fbcc152811e29df3b7b645beda67062f2b

**Comment by htgoebel** [comment] 2015-08-10 15:12
This should now be fixed. Please test the current python3-branch and give us a note on your success.

**Comment by jonnojohnson** [comment] 2015-09-15 22:01
Just came across this issue I believe:
````
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.0.dev1', 'console_scripts', 'pyinstaller')()
  File "C:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\Anaconda\lib\site-packages\PyInstaller\__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 729, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 675, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 205, in __init__
    self.__postinit__()
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\datastruct.py", line 153, in __postinit__
    self.assemble()
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\build_main.py", line 424, in assemble
    imphook_object.update_dependencies(self.graph)
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\imphook.py", line 412, in update_dependencies
    self._process_hiddenimports(mod_graph)
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\imphook.py", line 281, in _process_hiddenimports
    self._process_one_hiddenimport(item, mod_graph)
  File "C:\Anaconda\lib\site-packages\PyInstaller\building\imphook.py", line 288, in _process_one_hiddenimport
    mod_graph.import_hook(item, caller=caller)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1021, in import_hook
    m = self._load_tail(q, tail)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1126, in _load_tail
    result = self._import_module(head, mname, result)
  File "C:\Anaconda\lib\site-packages\PyInstaller\depend\analysis.py", line 174, in _import_module
    partname, fqname, parent)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1292, in _import_module
    m = self._load_module(fqname, fp, pathname, stuff)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1365, in _load_module
    self._scan_code(co, m)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1532, in _scan_code
    self._scan_ast(co, m)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1541, in _scan_ast
    visitor.visit(co)
  File "C:\Anaconda\lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Anaconda\lib\ast.py", line 249, in generic_visit
    self.visit(item)
  File "C:\Anaconda\lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 687, in visit_TryExcept
    self.generic_visit(node)
  File "C:\Anaconda\lib\ast.py", line 249, in generic_visit
    self.visit(item)
  File "C:\Anaconda\lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 663, in visit_ImportFrom
    self._process_import(node.module or '', _ast_names(node.names), level)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 648, in _process_import
    fromlist=False,
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1389, in _safe_import_hook
    mods = self.import_hook(name, caller, level=level, attr=attr)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1020, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1111, in _find_head_package
    q = self._import_module(head, qname, parent)
  File "C:\Anaconda\lib\site-packages\PyInstaller\depend\analysis.py", line 174, in _import_module
    partname, fqname, parent)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1292, in _import_module
    m = self._load_module(fqname, fp, pathname, stuff)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1318, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1678, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1365, in _load_module
    self._scan_code(co, m)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1532, in _scan_code
    self._scan_ast(co, m)
  File "C:\Anaconda\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1541, in _scan_ast
    visitor.visit(co)
````

It then returns to the line:
````
File "C:\Anaconda\lib\ast.py", line 241, in visit
    return visitor(node)
````
then repeats.

Using:
Python 2.7.10 (64) on Win7
Pyinstaller 3.0.dev1 installed from zip on Github using pip today.
Matplotlib (1.4.3)

**Comment by codewarrior0** [comment] 2015-09-16 01:39
I can reproduce this with Anaconda 2.3.0 64-bit and the latest `python3` branch. I'll try to find out whether it's a deeply nested AST tree or whether it's a recursive loop.

**Comment by codewarrior0** [comment] 2015-09-16 01:49
ModuleGraph debug output indicates it is a deeply nested AST tree.

(ModuleGraph debug output is also slightly buggy. At some point it stops indenting the output and none of the output lines are indented.)

**Comment by codewarrior0** [comment] 2015-09-17 02:54
It seems the only solution is to change modulegraph to use no recursion when adding modules. Instead of having `_scan_code` indirectly call `_safe_import_hook` via visitor methods, it should instead push the imports it finds onto a queue to be processed outside of `_scan_code`. What I'm not sure of is the proper time to process this queue. 

My first attempt at this seems to be broken because I'm not processing the queue at all appropriate times, and hundreds of modules aren't being added to the graph. I'm calling `_process_all` at the end of `run_script` and `import_hook`, and I'm about to try calling it in `findNode` since that function is able to create new nodes (and by doing so queue more imports to be processed).

**Comment by htgoebel** [comment] 2015-09-17 09:11
> It seems the only solution is to change modulegraph to use no recursion when adding modules. Instead of having `_scan_code` indirectly call `_safe_import_hook` via visitor methods, it should instead push the imports it finds onto a queue to be processed outside of `_scan_code`. What I'm not sure of is the proper time to process this queue. 

In https://github.com/htgoebel/pyinstaller/commit/d832ad6425261e0d24bd76100b02fe515dfd7d7b I've implemented something like this (and more). But according to leycec's description about tree invariants (https://github.com/pyinstaller/pyinstaller/pull/1393#issuecomment-139492918), this very code *seams* to break the modulegraph invariant. But then again, if `_process_imports` in `_scan_code`, the invariant should be kept. Feel free to cannibalise https://github.com/htgoebel/pyinstaller/commit/d832ad6425261e0d24bd76100b02fe515dfd7d7b

**Comment by codewarrior0** [comment] 2015-09-18 04:47
Good point. Right now I'm just pushing lists of modules to be imported (as PendingImport tuples that include the parent module, the import name, and all the other options from Visitor) onto a stack, and then popping them off in an order that matches the previous traversal order. In order to make sure post-call hooks are only given a complete module, I could probably put the PendingImports onto the nodes themselves and then push the nodes onto the stack instead. Then, when processing a node, I'll pop individual PendingImports off of the node and push more nodes onto the stack as needed. When a node has no more PendingImports, the node can finally be popped off the stack, and then post-call hooks can be run.

**Comment by htgoebel** [comment] 2015-09-18 07:23
From https://github.com/pyinstaller/pyinstaller/pull/1393#issuecomment-139722879:
> Since `_load_module()` recursively calls `_scan_code()`, module graph recursion effectively "bottoms out" at `_load_module()`. [...]

So I assume it should by okay to collect all imports in order within `_scan_code` (and the other `_scan_*`-Methods) and process them prior to returning from `_scan_code`.

**Comment by codewarrior0** [comment] 2015-09-18 07:37
That's what I thought at first, but that just results in recursion. Processing an import will eventually call `_scan_code`. I was hoping there would be only a single point where I could process the pending imports, a place that wouldn't end up making recursive calls, but the best I could do was two. Those are the two places the clients of modulegraph can cause a module to be added: 

- The end of `run_script`
- The end of `import_hook` whenever no imports are pending (since `import_hook` can call itself recursively though `_process_all` -> `_safe_import_hook` -> `import_hook`)

**Comment by codewarrior0** [comment] 2015-09-18 07:54
Trying to pick apart the flow of control through `modulegraph` by reading the source can get kind of confusing, so let's do it visually. Lucky for me, I already have a call graph from the last time I ran PyInstaller under profiling, so let's use that:

![image](https://cloud.githubusercontent.com/assets/307683/9954633/557c3b1e-5d86-11e5-9cb1-358f3c304796.png)

I've cropped out all the parts that don't call modulegraph. 

Looking at it this way, it becomes obvious. The two places PyInstaller enters modulegraph are `run_script` and `import_hook`, and everything eventually recurses back to `import_hook`. There are two ways to get into `_scan_code`, and they are both `run_script` and `import_hook`.

**Comment by htgoebel** [comment] 2015-09-18 08:11
I gave it a try too, ending with one place. https://github.com/htgoebel/pyinstaller/commit/6f20fb9bd924a9475f382662772d857df2b3bbbb - but this fails terribly, too.

**Comment by codewarrior0** [comment] 2015-09-18 08:38
This is where I'm at now: https://github.com/codewarrior0/pyinstaller/commit/415c00fe47005705085da0b5a078b0b78017ee5b

Much better than my first attempt. It's passing all of the basic tests locally, and I'm waiting for [the Travis job] to finish so I can see if any of the other tests are broken. It still has the problem that there's no way to know that a particular module is completely imported and call a post-import_hook function. To do that I'll have to borrow your idea of storing the PendingImports on the module nodes themselves.

**Comment by htgoebel** [comment] 2015-09-18 09:19
> the problem that there's no way to know that a particular module is completely imported

So we are back to the modulgraph invariant :-(

**Comment by codewarrior0** [comment] 2015-09-21 07:53
I haven't yet found out why those few library tests are failing with my no-recursion patch... but what I did manage to do is get a list of all the chains leading back from each module to the method that caused it to be added to the graph. These are [the import chains for `test_helloworld`](https://gist.github.com/codewarrior0/d1389a422bfa3e26708f) without the patch.

**Comment by htgoebel** [comment] 2015-09-21 19:29
I think, I've found a reason: In [line 1148](https://github.com/pyinstaller/pyinstaller/blob/b5fe082b380f55dbdcc242cb5172dcb657b60f44/PyInstaller/lib/modulegraph/modulegraph.py#L1148), a module is not imported if it is already in `globalnames`. But `globalnames` is set in `_scan_bytecode_stores()`, which is called just after `_scan_ast()`, for each `from xxx import abc`. So we need to process the imports the modules *prior* to `_scan_bytecode_stores()`. Resp., since `_scan_bytecode()` (for byte-compiled modules) also collects the global names, we need to suspend the globals prior to process the imports.

I've done this at https://github.com/htgoebel/pyinstaller/commit/36baccf478b4d763935a2856ce3dc08f515f5df0. This looks good, except for `test_site_module_disabled` failing.

**Comment by htgoebel** [comment] 2015-09-21 20:22
According to #1507, this case is failing because `site` is included where it should not. So I'd assume, https://github.com/htgoebel/pyinstaller/commit/36baccf478b4d763935a2856ce3dc08f515f5df0 would solve the problem. But I'm delaying this change until the problem with `site` is solved.

**Comment by codewarrior0** [comment] 2015-09-22 13:59
With your patch, the `matplotlib` test case passes with Anaconda 2.3.0.

Hmm! It looks like your patch was more conservative than my attempt. I was trying to remove recursion from modulegraph entirely... whereas with your patch, modulegraph is still recursive, but you have separated the recursion into the AST trees from the recursion through import statements, by processing imports only after the AST tree visitor is done.

So with your approach, the recursion looks like this:

```
_import_module
_load_module
_scan_code
_process_import
_safe_import_hook
import_hook
_find_head_package
_import_module (loop)
```

Whereas before, the recursion could look like this:

```
_import_module
_load_module
_scan_code
_scan_ast
Visitor.visit
Visitor.generic_visit
Visitor.visit
Visitor.generic_visit
-- [plus *any number* of Visitor method calls] --
Visitor.visit_Import / Visitor.visit_ImportFrom
_process import
_safe_import_hook
import_hook
_find_head_package
_import_module (loop)
```

With your method, the allowable depth of recursion is only bounded by the length of import chains, rather than import chains *plus* AST tree depth. And that's fine by me.

**Comment by htgoebel** [comment] 2015-09-27 15:25
I rebased my changes into the current `develop` head (merged from `python3` just today). But again, this [fails for PYthon 2.7 and 3.4)[https://travis-ci.org/htgoebel/pyinstaller/builds/82421152]
See https://github.com/htgoebel/pyinstaller/tree/issue-1289-maximum-recursion-exeeded.

**Comment by htgoebel** [comment] 2015-09-27 20:33
I rebased my changes into the current `develop` head (re-introducing the `fake-site`-module) and the [results](https://travis-ci.org/htgoebel/pyinstaller/builds/82455332) look okay now. Since the maximum recursion depth exceeded erro never occurred here: Can you please test this branch with your sampled?! Thanks.
See https://github.com/htgoebel/pyinstaller/tree/issue-1289-maximum-recursion-exeeded.

**Comment by codewarrior0** [comment] 2015-09-27 20:52
> Can you please test this branch with your sampled?!

Yep, still passing. Looks like you did it! 

```
Rio@RIO-PC ~/Documents/src/pyinst1328 (issue-1289-maximum-recursion-exeeded)
$ /c/Anaconda-27-64/scripts/py.test -k test_matplotlib -x
============================= test session starts =============================
platform win32 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.3 -- c:\Anaconda-27-64\python.exe
rootdir: c:\Users\Rio\Documents\src\pyinst1328, inifile: setup.cfg
collected 234 items

tests/functional/test_libraries.py::test_matplotlib[onedir] PASSED
tests/functional/test_libraries.py::test_matplotlib[onefile] PASSED

================= 232 tests deselected by '-ktest_matplotlib' =================
================= 2 passed, 232 deselected in 675.47 seconds ==================
```

**Comment by htgoebel** [comment] 2015-09-28 08:59
> Yep, still passing. Looks like you did it! 

Okay, so I'll merge it later this day.

**Closed** 2015-09-29 09:47 UTC
Labels: modulegraph
