### ISSUE TITLE
UPX fails on Windows

### ISSUE THREAD

**Issue by pckroon** [pyinstaller/pyinstaller#2982] opened 2017-11-08 10:22 UTC
Hello,

I'm running Python 3.6.2 with pyinstaller 3.4.dev0+133d18156 on Windows Server 2012 using an Anaconda environment and I ran into trouble when I tried to use UPX. Without UPX everything works as expected.
I tried with UPX version 3.9.4 and 3.9.3; they give identical results. I'm fairly certain this is actually an UPX bug, but I'm not comfortable enough with binaries/dll's etc to trace this further and report it upstream. Please let me know if there's more things I can do to help.

Here's my minimal example:
```python
print('Hello world!')
```

```console
(X:\.conda\envs\py3.6) X:\My Desktop\UPLC data parser>pyinstaller hello.py --upx
-dir X:\upx394w -y --distpath C:\Users\<username>\AppData\Local\Temp\9\dist --debug
 --log-level DEBUG
300 INFO: PyInstaller: 3.4.dev0+133d18156
300 INFO: Python: 3.6.2
302 INFO: Platform: Windows-2012ServerR2-6.3.9600-SP0
306 INFO: wrote X:\My Desktop\UPLC data parser\hello.spec
307 DEBUG: Testing for UPX ...
415 INFO: UPX is available.
420 DEBUG: script: X:\My Desktop\UPLC data parser\hello.py
421 INFO: Extending PYTHONPATH with paths
['X:\\My Desktop\\UPLC data parser', 'X:\\My Desktop\\UPLC data parser']
422 INFO: checking Analysis
538 INFO: checking PYZ
605 INFO: checking PKG
613 INFO: Bootloader x:\.conda\envs\py3.6\lib\site-packages\PyInstaller\bootload
er\Windows-64bit\run_d.exe
614 INFO: checking EXE
625 INFO: checking COLLECT
630 INFO: Removing dir C:\Users\<username>\AppData\Local\Temp\9\dist\hello
675 INFO: Building COLLECT out00-COLLECT.toc
1258 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

(X:\.conda\envs\py3.6) X:\My Desktop\UPLC data parser>C:\Users\<username>\AppData\L
ocal\Temp\9\dist\hello\hello.exe
[10940] PyInstaller Bootloader 3.x
[10940] LOADER: executable is C:\Users\<username>\AppData\Local\Temp\9\dist\hello\h
ello.exe
[10940] LOADER: homepath is C:\Users\<username>\AppData\Local\Temp\9\dist\hello
[10940] LOADER: _MEIPASS2 is NULL
[10940] LOADER: archivename is C:\Users\<username>\AppData\Local\Temp\9\dist\hello\
hello.exe
[10940] LOADER: No need to extract files to run; setting extractionpath to homep
ath
[10940] LOADER: SetDllDirectory(C:\Users\<username>\AppData\Local\Temp\9\dist\hello
)
[10940] LOADER: Already in the child - running user's code.
[10940] LOADER: Python library: C:\Users\<username>\AppData\Local\Temp\9\dist\hello
\python36.dll
Error loading Python DLL 'C:\Users\<username>\AppData\Local\Temp\9\dist\hello\pytho
n36.dll'.
LoadLibrary:
```

**Comment by htgoebel** [comment] 2017-11-08 10:38
Duplicate of #2659

**Closed by htgoebel** 2017-11-08 10:38 UTC
