### ISSUE TITLE
global name error with keyring module

### ISSUE THREAD

**Issue by sonicnkt** [pyinstaller/pyinstaller#1672] opened 2015-11-13 12:17 UTC
i wrote a small python app to automatically login a user to specific service using the keyring module (for storing the password in the windows credential vault) and wxpython for a login gui if the date hasnt been stored yet or login didnt work. 

The script is working perfectly on a normal python install but i want to deploy this as standalone application.

Keyring doesnt seem to play nice with pyinstaller but i got my program to start atleast after adding a huge list of hidden imports:

```
'json', 
'json.decoder', 
'json.encoder', 
'json.scanner',
'keyring.backends.file',
'keyring.backends.Gnome',
'keyring.backends.Google',
'keyring.backends.keyczar',
'keyring.backends.kwallet',
'keyring.backends.multi',
'keyring.backends.OS_X',
'keyring.backends.pyfs',
'keyring.backends.SecretService',
'keyring.backends.Windows',
'keyring.backends._win_crypto',
'keyring.util.escape',
'keyring.util.XDG',
'keyring.credentials'
```

With those the program starts without any errors of missing modules but it still crashes when it tries to access the credential vault:

```
c:\PY\novell_login>dist\thread_test\thread_test.exe
Logging in User: test
Traceback (most recent call last):
  File "c:\PY\build\thread_test\out00-PYZ.pyz\wx._core", line 16766, in <lambda>
  File "<string>", line 119, in LongTaskDone
  File "c:\PY\build\thread_test\out00-PYZ.pyz\keyring.core", line 44, in set_password
  File "c:\PY\build\thread_test\out00-PYZ.pyz\keyring.backends.file", line 87, in set_password
  File "c:\PY\build\thread_test\out00-PYZ.pyz\keyring.backends.Windows", line 81, in encrypt
NameError: global name '_win_crypto' is not defined
```
I couldnt find anything related to this and created this issue. Hope someone can help me! Thanks!

**Comment by htgoebel** [comment] 2015-11-20 21:04
I assume, `keyring.backends._win_crypto` is a module, since you added it to `hiddenimports`. so it looks like the module is not frozen for any reason. Is this an extension-module?

**Comment by matysek** [comment] 2015-11-26 21:22
@sonicnkt Any simple code example to reproduce?

**Comment by sonicnkt** [comment] 2015-11-27 11:19
@matysek:
Here is a short code example, when it tries to store the password (keyring.set_password()) it crashes with the posted output above. Reading from the keyring (keyring.get_password) doesnt crash the programm but it also doesnt work. 

```python
# -*- encoding: utf-8 -*-
import keyring
from time import sleep

loginFile = 'login.conf'

def getUser():
	with open (loginFile, "r") as myfile:
		data=myfile.read().replace('\n', '')
	return data

def cmdlogin(user, pw):
	print 'Executing login cmd:'
	print 'login.exe /user:{} /pwd:{}'.format(user, pw)
	print 'Login success... shutting down!'
	sleep(5)

def getPW(user):
	password = keyring.get_password("mylogin", user)
	return password

def storeUser(user):
	with open(loginFile, "w") as text_file:
		text_file.write(user)

def storePW(user, pw):
	keyring.set_password("mylogin", user, pw)

if os.path.isfile(loginFile):
	user = getUser()
	pw = getPW(user)
	cmdlogin(user, pw)
else:
	user = raw_input('Username: ')
	pw = raw_input('Password: ')
	print 'Storing username and password in keyring!'
	storeUser(user)
	storePW(user, pw)
	print 'Logging in...'
	cmdlogin(user, pw)
```

**Comment by matysek** [comment] 2015-12-13 19:21
@sonicnkt could you either test with PyInstaller 3.0 or the `develop` version?

**Comment by sonicnkt** [comment] 2015-12-15 10:16
@matysek just tested it with pyinstaller 3.0 (upgrade through pip) and my small test example (above) works fine, even without all the hidden imports!
Gues this problem is solved!

**Comment by matysek** [comment] 2015-12-15 16:32
@sonicnkt could you please also try the `develop` version to confirm that there is no regression?

**Comment by sonicnkt** [comment] 2015-12-15 18:03
@matysek is it possible to install the develop version through pip with with "--pre" flag? 
Dont have access to my python system atm but will test it tomorrow.

**Comment by matysek** [comment] 2015-12-17 18:57
No, it is not. There is this pip command. It might require git client. Another option is to download it manually as zip archive.
```
pip install -e git://github.com/pyinstaller/pyinstaller.git#egg=PyInstaller
```

**Comment by htgoebel** [comment] 2016-01-25 18:39
Got no further info since one month now. I assume this is fixed. Closing.

**Closed by htgoebel** 2016-01-25 18:39 UTC
Labels: hooks, need info, support, Windows
