### ISSUE TITLE
Pyinstaller exe keeps opening itself

### ISSUE THREAD

**Issue by newTypeGeek** [pyinstaller/pyinstaller#4067] opened 2019-02-13 06:17 UTC
I have a face recognition app written in Python and tried to convert to an exe using `pyinstaller`. However, when the exe is executed, it keeps opening itself with more and more windows pop out.

Then I display the process and gives this result.

    $ ps
    PID    TTY    TIME    CMD
    ...    ...    ...     /path/to/main -B -s -S -E -c from multiprocessing.semaphore_tracker import main:main(8)
    ...    ...    ...     /path/to/main -B -s -S -E -c from multiprocessing.semaphore_tracker import main:main(8)
    ...    ...    ...     /path/to/main -B -s -S -E -c from multiprocessing.semaphore_tracker import main:main(7)
    ...    ...    ...     /path/to/main -B -s -S -E -c from multiprocessing.semaphore_tracker import main:main(7)
    ...    ...    ...     /path/to/main -B -s -S -E -c from multiprocessing.semaphore_tracker import main:main(8)

It turns out that one of the modules that I am using involves **threading**. So I try to add a line `multiprocessing.freeze_support()` in my main program. It can suppress the GUI window from keep duplicating, but the background processes as shown using the command `$ ps` are still keep duplicating.

In the following, I have some simple Python scripts to reproduce similar bug   

###  main1.py

    # main1.py
    # multiprocessing.freeze_support() is called BEFORE importing sklearn module
    import multiprocessing
    import tkinter as tk

    if __name__ == '__main__':
        print("Calling multiprocessing.freeze_support()")
        multiprocessing.freeze_support()
        print("Importing sklearn")
        import sklearn

        print("Starting Tkinter GUI")
        window = tk.Tk()
        window.title("Testing PyInstaller with sklearn")
        window.mainloop()

PyInstaller command and print out

    $  pyinstaller --onefile --windowed --clean --hidden-import sklearn.neighbors.typedefs --log-level ERROR main1.py
    Traceback (most recent call last):
       File "<string>", line 2, in <module>
    ModuleNotFoundError: No module named 'Crypto.Math'
    186021 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
    188231 ERROR: Can not find path ./libtbb.dylib (needed by /Users/user/anaconda3/lib/libmkl_tbb_thread.dylib)

Executing `./dist/main1` creates only one GUI window. And here are the related results

Console print out

    Calling multiprocessing.freeze_support()
    Importing sklearn
    Starting Tkinter GUI
    Calling multiprocessing.freeze_support()
    # now, no more print out

Running process (just two of them)

    PID TTY           TIME CMD
    1220 ttys000    0:07.96 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1223 ttys000    0:00.16 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)

**Summary of `main1.py` result**
While calling `multiprocessing.freeze_support()` BEFORE importing `sklearn` does not lead to infinite loop. But still, two processes forked. Why?

###  main2.py

    # main2.py
    # multiprocessing.freeze_support() is called AFTER importing sklearn module
    import multiprocessing
    import tkinter as tk
    import sklearn

    if __name__ == '__main__':
        print("sklearn is imported already")
        print("Calling multiprocessing.freeze_support()")
        multiprocessing.freeze_support()

        print("Starting Tkinter GUI")
        window = tk.Tk()
        window.title("Testing PyInstaller with sklearn")
        window.mainloop()

PyInstaller command and print out

    $  pyinstaller --onefile --windowed --clean --hidden-import sklearn.neighbors.typedefs --log-level ERROR main2.py
    Traceback (most recent call last):
       File "<string>", line 2, in <module>
    ModuleNotFoundError: No module named 'Crypto.Math'
    179871 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
    181860 ERROR: Can not find path ./libtbb.dylib (needed by /Users/user/anaconda3/lib/libmkl_tbb_thread.dylib)

Executing `./dist/main2` creates only one GUI window. And here are the related results

Console print out (it does not stop and keeps printing out!!!)

    Calling multiprocessing.freeze_support()
    Starting Tkinter GUI
    sklearn is imported already
    Calling multiprocessing.freeze_support()
    sklearn is imported already
    Calling multiprocessing.freeze_support()
    sklearn is imported already
    Calling multiprocessing.freeze_support()
    sklearn is imported already
    Calling multiprocessing.freeze_support()
    sklearn is imported already
    Calling multiprocessing.freeze_support()
    sklearn is imported already
    Calling multiprocessing.freeze_support()
    sklearn is imported already
    Calling multiprocessing.freeze_support()

Running process (more and more processes pop out!!!)

    PID TTY           TIME CMD
    1920 ttys000    0:08.32 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1927 ttys000    0:00.60 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1928 ttys000    0:07.92 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(8)
    1930 ttys000    0:00.46 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(8)
    1931 ttys000    0:08.23 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1933 ttys000    0:00.51 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1935 ttys000    0:08.55 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(8)
    1938 ttys000    0:00.58 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(8)
    1940 ttys000    0:08.20 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1942 ttys000    0:00.69 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1943 ttys000    0:08.49 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(8)
    1948 ttys000    0:00.49 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(8)
    1949 ttys000    0:08.01 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1951 ttys000    0:00.47 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(7)
    1952 ttys000    0:02.90 /Users/user/Documents/python_test/pyinstaller_test/sklearn_tkinter/dist/main2 -B -s -S -E -c from multiprocessing.semaphore_tracker import main;main(8)

**Summary of `main2.py` result**
Calling `multiprocessing.freeze_support()` AFTER importing `sklearn` does lead to infinite loop. One may suggest to call `multiprocessing.freeze_support()` before importing `sklearn` as shown in `main1.py` above. But in that case, the processes are still forked and don't know why. Even worse, how can I guarantee `multiprocessing.freeze_support()` before importing `sklearn` when I am having multiple python scripts with some scripts importing `sklearn` and the main script importing `multiprocessing`?

Version 
1. OS:                     macOS Mojave 10.14.2
2. PyInstaller:            3.4
3. Python:                 3.7.0 Clang 4.0.1 (tags/RELEASE_401/final) :: Anaconda, Inc on darwin
4. sklearn:                0.20.2
5. Tkinter:                8.6

**Comment by htgoebel** [comment] 2019-02-13 10:39
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by newTypeGeek** [comment] 2019-02-14 02:15
@htgoebel I have edited the post with examples provided. Thanks

**Comment by CliffMitchell** [comment] 2019-03-01 10:57
I think I have the same problem as I reported here: https://stackoverflow.com/questions/54942950/pyqt5-pyinstaller-app-opens-multiple-copies-in-endless-loop-on-osx

**Comment by BLKSerene** [comment] 2019-03-08 10:58
@newTypeGeek @CliffMitchell
I have the same problem when trying to package my program (my pinned repository) using the latest development version of PyInstaller on macOS 10.14.
After several days of troubleshooting, I finally found that the problem is the `joblib` library. Some denpendencies of my program import joblib somewhere in their code bases, so when I import these dependencies, the packaged program would result in an infinite loop of opening itself.

According to [this issue](https://github.com/scikit-learn/scikit-learn/issues/2114), `sklearn` also uses `joblib`, so I guess that where the problem is.

My solution is that if you don't need the multiprocessing features provided by `joblib`, simply exclude the `joblib` library in the spec file (or in command line) and carefully remove all import statements of joblib in all dependencies of your program (to avoid ImportError).

If you do need the `joblib` library, since I have little knowledge about multiprocessing, I have no idea how to fix this in `PyInstaller`...

I can confirm this problem by this:
`import joblib`
After the script containing only this line is frozen, it would cause an endless loop of opening itself. Note that this issue does not exist on Windows 10 (tested), so I suppose this issue concerns only macOS.

Simply import multiprocessing on macOS won't cause this problem.
`import multiprocessing`
So this must have something to do with the multiprocessing features provided by `joblib`.

And also note that the [doc](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) says that "Calling freeze_support() has no effect when invoked on any operating system other than Windows.", so this won't work on macOS.

Hope that my answer would be some help.

**Comment by CliffMitchell** [comment] 2019-03-08 11:23
Thanks @newTypeGeek, that's really helpful. I'll have a dig around and see if I can get rid of any calls to joblib and report back with how I get on.

**Comment by CliffMitchell** [comment] 2019-03-08 19:21
OK, I can confirm that running a 1-line script:
`import sklearn`
frozen with PyInstaller causes an infinite loop. Adding an exclusion:
`excludes=['sklearn.externals.joblib']`
fixes the problem. Unfortunately, but not surprisingly, adding this exclusion to my real app just stops it working. My app is a machine learning application and has to use sklearn so I have to find a way to stop sklearn loading joblib while still allowing machine learning!!
Anyway your help @newTypeGeek  is much appreciated and I now have a much clearer handle on where the problem lies. If I find a solution I'll make sure to report it back here.

**Comment by BLKSerene** [comment] 2019-03-09 04:25
@CliffMitchell Well, I suppose you are replying to me, not the author of this issue?

**Comment by CliffMitchell** [comment] 2019-03-09 10:11
Sorry @BLKSerene, yes I was replying to you. I have edited my replies.  Thanks for you help.

**Comment by letalvoj** [comment] 2019-05-16 09:56
Any progress or idea when did problem emerged? We've just got hit by this issue like 24h before a release 🤦‍♀️

**Comment by letalvoj** [comment] 2019-05-17 13:37
*Possible fix*, what helped us was to bump up scikit and revert joblib to these specific versions:
```
scikit-learn==0.21.1
joblib==0.11
```
Attribute goes to @tm-drtina 👍

**Comment by tbsexton** [comment] 2019-05-17 14:37
Confirming this works for #4110 ... would love to know the root cause here, but I'll share the fix anyway. Thanks a ton!

**Comment by mnboos** [comment] 2019-07-11 08:13
> 
> 
> _Possible fix_ related to [scikit-learn/scikit-learn#13531](https://github.com/scikit-learn/scikit-learn/pull/13531): What helped us was to bump up scikit and revert joblib to these specific versions:
> 
> ```
> scikit-learn==0.21.1
> joblib==0.11
> ```
> 
> Attribute goes to @tm-drtina 👍
> 
> Might also solve #4110 .

For me it was sufficient to only specify joblib and still use a newer scikit-learn

```
joblib==0.11
```

**Comment by letalvoj** [comment] 2019-07-11 08:25
> For me it was sufficient to only specify joblib and still use a newer scikit-learn
I should have been more clear. At the time of writing the `0.21.1` was the latest scikit-learn version. Since then nothing has changed much - only a bump in a minor version.

I changed the original comment to make it clear.

**Comment by htgoebel** [comment] 2019-08-10 12:05
Duplicate of #4110

**Closed by htgoebel** 2019-08-10 12:05 UTC
Labels: need info

**Comment by fabiopoiesi** [comment] 2019-09-23 07:52
Using joblib=00.11 solved the problem. For completeness I am using scikit-learn==0.21.3.

**Comment by jsl303** [comment] 2020-07-29 15:00
I'm not using sklearn nor joblib. However including this module that I wrote causes problem.
This module runs a shell command in the background until you kill.

```
import select
import shlex
import subprocess
from multiprocessing import Process, Value

def process(cmd, run):
	print('Command:',cmd)
	cmd = shlex.split(cmd)
	proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	poll = select.poll()
	poll.register(proc.stdout, select.POLLIN)
	while run.value > 0:
		if poll.poll(0):
			line = proc.stdout.readline().decode('utf-8')
			if line == '': break
			print(line[:-1])
	proc.kill()
	print('Killed', cmd)

class RunWhile:
	def __init__(self):
		self.run = Value('i', 0)
		self.proc = None

	def start(self, cmd):
		self.run.value = 1
		self.proc = Process(target=process, args=(cmd, self.run))
		self.proc.start()

	def stop(self):
		self.run.value = 0
		if self.proc:
			self.proc.join()
			self.proc.terminate()
```

If I import this and use like this, it opens the app over and over, creating many instances of the app running.
```
from RunWhile import RunWhile
if __name__ == '__main__':
	r = RunWhile()
```



If I just run the .py file without pyinstaller, it works fine.

**Comment by Seraphppy** [comment] 2020-08-19 23:42
bump

**Comment by Seraphppy** [comment] 2020-08-19 23:48
> I'm not using sklearn nor joblib. However including this module that I wrote causes problem.
> This module runs a shell command in the background until you kill.
> 
> ```
> import select
> import shlex
> import subprocess
> from multiprocessing import Process, Value
> 
> def process(cmd, run):
> 	print('Command:',cmd)
> 	cmd = shlex.split(cmd)
> 	proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> 	poll = select.poll()
> 	poll.register(proc.stdout, select.POLLIN)
> 	while run.value > 0:
> 		if poll.poll(0):
> 			line = proc.stdout.readline().decode('utf-8')
> 			if line == '': break
> 			print(line[:-1])
> 	proc.kill()
> 	print('Killed', cmd)
> 
> class RunWhile:
> 	def __init__(self):
> 		self.run = Value('i', 0)
> 		self.proc = None
> 
> 	def start(self, cmd):
> 		self.run.value = 1
> 		self.proc = Process(target=process, args=(cmd, self.run))
> 		self.proc.start()
> 
> 	def stop(self):
> 		self.run.value = 0
> 		if self.proc:
> 			self.proc.join()
> 			self.proc.terminate()
> ```
> 
> If I import this and use like this, it opens the app over and over, creating many instances of the app running.
> 
> ```
> from RunWhile import RunWhile
> if __name__ == '__main__':
> 	r = RunWhile()
> ```
> 
> If I just run the .py file without pyinstaller, it works fine.

Did you fix this?

**Comment by jsl303** [comment] 2020-08-20 03:39
I gave up using multiprocessing.Process, and used threading.Thread instead.

It works for my purpose, but if you really need 
multiprocessing.Process,I'm not sure how to fix it.
