### ISSUE TITLE
Fatal error:Failed to execute script main

### ISSUE THREAD

**Issue by BogdanShevchenkoo** [pyinstaller/pyinstaller#4045] opened 2019-02-04 23:09 UTC
I successfully package an app with kivy and run it. But in my project I also use python-docx-template, after package I am starting .exe file and getting "Fatal error:Failed to execute script main" inside kivy's window . Console print: File "site-packages\kivy\lang\parser.py" line 462, in execute_directives ModuleNotFoundError: no module named 'main'

How to fix it?

PyInstaller : 3.4
Windows 7 SP1
Python : 3.7.1

E:\WordPython\build>python -m PyInstaller paintapp.spec
69 INFO: PyInstaller: 3.4
69 INFO: Python: 3.7.1
70 INFO: Platform: Windows-7-6.1.7601-SP1
71 INFO: UPX is not available.
[INFO   ] [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_0.txt
110 INFO: [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_0.txt
[INFO   ] [Kivy        ] v1.10.1
110 INFO: [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
111 INFO: [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
113 INFO: Extending PYTHONPATH with paths
['E:\\WordPython\\build\\src', 'E:\\WordPython\\build']
113 INFO: checking Analysis
113 INFO: Building Analysis because Analysis-00.toc is non existent
113 INFO: Initializing module dependency graph...
116 INFO: Initializing module graph hooks...
117 INFO: Analyzing base_library.zip ...
3218 INFO: Analyzing hidden import '__init__'
3366 INFO: Analyzing hidden import 'data.__init__'
3367 ERROR: Hidden import 'data.__init__' not found
3367 INFO: Analyzing hidden import 'data.screens.__init__'
3368 ERROR: Hidden import 'data.screens.__init__' not found
3368 INFO: Analyzing hidden import 'data.screens.dbmanager'
3369 ERROR: Hidden import 'data.screens.dbmanager' not found
3369 INFO: Analyzing hidden import 'data.screens.db_kv.__init__'
3370 ERROR: Hidden import 'data.screens.db_kv.__init__' not found
3370 INFO: Analyzing hidden import 'data.screens.db_kv.backupsd'
3372 ERROR: Hidden import 'data.screens.db_kv.backupsd' not found
3372 INFO: running Analysis Analysis-00.toc
3374 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\Java\AppData\Local\Programs\Python\Python37-32\python.exe
4145 INFO: Caching module hooks...
4150 INFO: Analyzing src\main.py
5263 INFO: Processing pre-find module path hook   distutils
7316 INFO: Loading module hooks...
7316 INFO: Loading module hook "hook-distutils.py"...
7318 INFO: Loading module hook "hook-encodings.py"...
7407 INFO: Loading module hook "hook-jinja2.py"...
7424 INFO: Loading module hook "hook-kivy.py"...
[INFO   ] [Factory     ] 194 symbols loaded
7430 INFO: [Factory     ] 194 symbols loaded
[INFO   ] [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_1.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif
(img_pil, img_ffpyplayer ignored)
[INFO   ] [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_2.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
[INFO   ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif
(img_pil, img_ffpyplayer ignored)
[CRITICAL] [Camera      ] Unable to find any valuable Camera provider.
picamera - ModuleNotFoundError: No module named 'picamera'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\camera\camera_picamera.py", line 18, in <module>
    from picamera import PiCamera

gi - ModuleNotFoundError: No module named 'gi'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\camera\camera_gi.py", line 10, in <module>
    from gi.repository import Gst

opencv - ModuleNotFoundError: No module named 'cv2'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\camera\camera_opencv.py", line 45, in <module>
    import cv2

[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 388.13'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 660/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[CRITICAL] [Spelling    ] Unable to find any valuable Spelling provider.
enchant - ModuleNotFoundError: No module named 'enchant'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\spelling\spelling_enchant.py", line 6, in <module>
    import enchant

[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
10661 INFO: Excluding import 'twisted'
10665 INFO:   Removing import of twisted from module kivy.support
10667 INFO: Import to be excluded not found: '_tkinter'
10667 INFO: Import to be excluded not found: 'tkinter'
10668 INFO: Loading module hook "hook-lxml.etree.py"...
10668 INFO: Loading module hook "hook-pkg_resources.py"...
10912 INFO: Processing pre-safe import module hook   win32com
11253 INFO: Loading module hook "hook-pydoc.py"...
11254 INFO: Loading module hook "hook-pygments.py"...
12570 INFO: Loading module hook "hook-pythoncom.py"...
12803 INFO: Loading module hook "hook-pywintypes.py"...
13029 INFO: Loading module hook "hook-sysconfig.py"...
13030 INFO: Loading module hook "hook-win32com.py"...
13452 INFO: Loading module hook "hook-xml.dom.domreg.py"...
13453 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
13454 INFO: Loading module hook "hook-xml.py"...
13455 INFO: Loading module hook "hook-docutils.py"...
14882 INFO: Looking for ctypes DLLs
14932 INFO: Analyzing run-time hooks ...
14941 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
14945 INFO: Including run-time hook 'pyi_rth_pkgres.py'
14949 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
14951 INFO: Including run-time hook 'pyi_rth_kivy.py'
14952 INFO: Including run-time hook 'pyi_rth_gstreamer.py'
14970 INFO: Looking for dynamic libraries
15439 WARNING: lib not found: libgstreamer-1.0-0.dll dependency of C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lib\gstplayer\_gstplayer.cp37-win32.pyd
18008 INFO: Looking for eggs
18008 INFO: Using Python library C:\Users\Java\AppData\Local\Programs\Python\Python37-32\python37.dll
18008 INFO: Found binding redirects:
[]
18019 INFO: Warnings written to E:\WordPython\build\build\paintapp\warn-paintapp.txt
18195 INFO: Graph cross-reference written to E:\WordPython\build\build\paintapp\xref-paintapp.html
18251 INFO: checking Tree
18252 INFO: Building Tree because Tree-00.toc is non existent
18252 INFO: Building Tree Tree-00.toc
18256 INFO: checking PYZ
18256 INFO: Building PYZ because PYZ-00.toc is non existent
18257 INFO: Building PYZ (ZlibArchive) E:\WordPython\build\build\paintapp\PYZ-00.pyz
20328 INFO: Building PYZ (ZlibArchive) E:\WordPython\build\build\paintapp\PYZ-00.pyz completed successfully.
20368 INFO: checking PKG
20368 INFO: Building PKG because PKG-00.toc is non existent
20368 INFO: Building PKG (CArchive) PKG-00.pkg
20389 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
20391 INFO: Bootloader C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw.exe
20391 INFO: checking EXE
20391 INFO: Building EXE because EXE-00.toc is non existent
20391 INFO: Building EXE from EXE-00.toc
20392 INFO: Appending archive to EXE E:\WordPython\build\build\paintapp\sample.exe
20492 INFO: Building EXE from EXE-00.toc completed successfully.
20496 INFO: checking Tree
20496 INFO: Building Tree because Tree-01.toc is non existent
20496 INFO: Building Tree Tree-01.toc
20499 INFO: checking Tree
20499 INFO: Building Tree because Tree-02.toc is non existent
20499 INFO: Building Tree Tree-02.toc
20500 INFO: checking COLLECT
20501 INFO: Building COLLECT because COLLECT-00.toc is non existent
20501 INFO: Building COLLECT COLLECT-00.toc
21234 INFO: Building COLLECT COLLECT-00.toc completed successfully.

E:\WordPython\build>python -m PyInstaller paintapp.spec
71 INFO: PyInstaller: 3.4
71 INFO: Python: 3.7.1
72 INFO: Platform: Windows-7-6.1.7601-SP1
74 INFO: UPX is not available.
[INFO   ] [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_5.txt
95 INFO: [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_5.txt
[INFO   ] [Kivy        ] v1.10.1
94 INFO: [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
96 INFO: [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
98 INFO: Extending PYTHONPATH with paths
['E:\\WordPython\\build\\src', 'E:\\WordPython\\build']
98 INFO: checking Analysis
99 INFO: Building Analysis because Analysis-00.toc is non existent
99 INFO: Initializing module dependency graph...
101 INFO: Initializing module graph hooks...
103 INFO: Analyzing base_library.zip ...
3238 INFO: Analyzing hidden import '__init__'
3382 INFO: Analyzing hidden import 'data.__init__'
3383 ERROR: Hidden import 'data.__init__' not found
3383 INFO: Analyzing hidden import 'data.screens.__init__'
3384 ERROR: Hidden import 'data.screens.__init__' not found
3385 INFO: Analyzing hidden import 'data.screens.dbmanager'
3386 ERROR: Hidden import 'data.screens.dbmanager' not found
3386 INFO: Analyzing hidden import 'data.screens.db_kv.__init__'
3387 ERROR: Hidden import 'data.screens.db_kv.__init__' not found
3387 INFO: Analyzing hidden import 'data.screens.db_kv.backupsd'
3388 ERROR: Hidden import 'data.screens.db_kv.backupsd' not found
3388 INFO: running Analysis Analysis-00.toc
3390 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\Java\AppData\Local\Programs\Python\Python37-32\python.exe
4138 INFO: Caching module hooks...
4144 INFO: Analyzing src\main.py
5267 INFO: Processing pre-find module path hook   distutils
7342 INFO: Loading module hooks...
7343 INFO: Loading module hook "hook-distutils.py"...
7344 INFO: Loading module hook "hook-encodings.py"...
7427 INFO: Loading module hook "hook-jinja2.py"...
7444 INFO: Loading module hook "hook-kivy.py"...
[INFO   ] [Factory     ] 194 symbols loaded
7448 INFO: [Factory     ] 194 symbols loaded
[INFO   ] [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_6.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif
(img_pil, img_ffpyplayer ignored)
[INFO   ] [Logger      ] Record log in C:\Users\Java\.kivy\logs\kivy_19-02-05_7.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
[INFO   ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif
(img_pil, img_ffpyplayer ignored)
[CRITICAL] [Camera      ] Unable to find any valuable Camera provider.
picamera - ModuleNotFoundError: No module named 'picamera'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\camera\camera_picamera.py", line 18, in <module>
    from picamera import PiCamera

gi - ModuleNotFoundError: No module named 'gi'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\camera\camera_gi.py", line 10, in <module>
    from gi.repository import Gst

opencv - ModuleNotFoundError: No module named 'cv2'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\camera\camera_opencv.py", line 45, in <module>
    import cv2

[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 388.13'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 660/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[CRITICAL] [Spelling    ] Unable to find any valuable Spelling provider.
enchant - ModuleNotFoundError: No module named 'enchant'
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\spelling\spelling_enchant.py", line 6, in <module>
    import enchant

[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
10574 INFO: Excluding import 'twisted'
10578 INFO:   Removing import of twisted from module kivy.support
10580 INFO: Import to be excluded not found: 'tkinter'
10580 INFO: Import to be excluded not found: '_tkinter'
10580 INFO: Loading module hook "hook-lxml.etree.py"...
10581 INFO: Loading module hook "hook-pkg_resources.py"...
11089 INFO: Processing pre-safe import module hook   win32com
11185 INFO: Loading module hook "hook-pydoc.py"...
11186 INFO: Loading module hook "hook-pygments.py"...
12491 INFO: Loading module hook "hook-pythoncom.py"...
12725 INFO: Loading module hook "hook-pywintypes.py"...
12960 INFO: Loading module hook "hook-sysconfig.py"...
12961 INFO: Loading module hook "hook-win32com.py"...
13378 INFO: Loading module hook "hook-xml.dom.domreg.py"...
13378 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
13379 INFO: Loading module hook "hook-xml.py"...
13380 INFO: Loading module hook "hook-docutils.py"...
14818 INFO: Looking for ctypes DLLs
14871 INFO: Analyzing run-time hooks ...
14878 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
14882 INFO: Including run-time hook 'pyi_rth_pkgres.py'
14884 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
14887 INFO: Including run-time hook 'pyi_rth_kivy.py'
14888 INFO: Including run-time hook 'pyi_rth_gstreamer.py'
14910 INFO: Looking for dynamic libraries
15483 WARNING: lib not found: libgstreamer-1.0-0.dll dependency of C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lib\gstplayer\_gstplayer.cp37-win32.pyd
18170 INFO: Looking for eggs
18170 INFO: Using Python library C:\Users\Java\AppData\Local\Programs\Python\Python37-32\python37.dll
18170 INFO: Found binding redirects:
[]
18181 INFO: Warnings written to E:\WordPython\build\build\paintapp\warn-paintapp.txt
18365 INFO: Graph cross-reference written to E:\WordPython\build\build\paintapp\xref-paintapp.html
18462 INFO: checking Tree
18463 INFO: Building Tree because Tree-00.toc is non existent
18463 INFO: Building Tree Tree-00.toc
18467 INFO: checking PYZ
18467 INFO: Building PYZ because PYZ-00.toc is non existent
18467 INFO: Building PYZ (ZlibArchive) E:\WordPython\build\build\paintapp\PYZ-00.pyz
20547 INFO: Building PYZ (ZlibArchive) E:\WordPython\build\build\paintapp\PYZ-00.pyz completed successfully.
20589 INFO: checking PKG
20589 INFO: Building PKG because PKG-00.toc is non existent
20589 INFO: Building PKG (CArchive) PKG-00.pkg
20613 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
20615 INFO: Bootloader C:\Users\Java\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
20615 INFO: checking EXE
20616 INFO: Building EXE because EXE-00.toc is non existent
20616 INFO: Building EXE from EXE-00.toc
20616 INFO: Appending archive to EXE E:\WordPython\build\build\paintapp\sample.exe
20729 INFO: Building EXE from EXE-00.toc completed successfully.
20732 INFO: checking Tree
20732 INFO: Building Tree because Tree-01.toc is non existent
20732 INFO: Building Tree Tree-01.toc
20736 INFO: checking Tree
20736 INFO: Building Tree because Tree-02.toc is non existent
20736 INFO: Building Tree Tree-02.toc
20738 INFO: checking COLLECT
20738 INFO: Building COLLECT because COLLECT-00.toc is non existent
20739 INFO: Building COLLECT COLLECT-00.toc
21551 INFO: Building COLLECT COLLECT-00.toc completed successfully.

**Comment by htgoebel** [comment] 2019-02-05 12:38
You are taking about several, probably unrelated issues, additionally the traceback shows other issues. Fist of all our need to track this down to simple cases. see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. create *minimal* examples to reproduce the error.

I'm closing this, since mutile-issue tickats can't be worked on. Please open one ticket for each tipoic - after traking ti down, of course.

**Closed** 2020-08-14 15:53 UTC
