### ISSUE TITLE
Add import hook for PIL.ImageTk.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#877] opened 2014-10-18 14:55 UTC
**Original date**: 2014/03/27
**Original reporter**: *matttodaro AND gmail DOT  COOM *

I'm getting an error when running my script in the console. I've traced it to the **from PIL import ImageTk**. Not sure how to fix this.

```
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/matttodaro/Desktop/Board_Pitch/build/board_pitch_v3_copy copy/out00-PYZ.pyz/PIL.PngImagePlugin", line 40, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/matttodaro/Desktop/Board_Pitch/build/board_pitch_v3_copy copy/out00-PYZ.pyz/PIL.Image", line 44, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/matttodaro/Desktop/Board_Pitch/build/board_pitch_v3_copy copy/out00-PYZ.pyz/FixTk", line 74, in <module>
OSError: [Errno 20] Not a directory: '/var/folders/m2/xptcb98s4lj060skxt5j2x880000gn/T/_MEIyGdK4R/tcl'
```

**Comment by jacebrowning** [comment] 2016-09-16 20:53
I am still experiencing this on:

* OS X 10.11.6 
* Python 3.5.0
* PyInstaller 3.2

My relevant imports are:

```
import tkinter as tk
from tkinter import ttk

from PIL import Image, ImageTk
```

The application builds with warnings:

```
301 INFO: PyInstaller: 3.2
302 INFO: Python: 3.5.0
320 INFO: Platform: Darwin-15.6.0-x86_64-i386-64bit

...

10076 INFO: Excluding import 'tkinter'
10080 WARNING:   Removing import PIL.ImageTk from module tkinter
10082 INFO: Import to be excluded not found: 'FixTk'

...

30762 INFO: Building BUNDLE out00-BUNDLE.toc
31140 INFO: moving BUNDLE data files to Resource directory
```

And the application fails to launch:

```
Traceback (most recent call last):
  File "my_application.py", line 11, in <module>
    from PIL import Image, ImageTk
  File ".../env/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "Pillow-3.3.1-py3.5-macosx-10.11-x86_64.egg/PIL/Image.py", line 67, in <module>
  File ".../env/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "Pillow-3.3.1-py3.5-macosx-10.11-x86_64.egg/PIL/_imaging.py", line 7, in <module>
  File "Pillow-3.3.1-py3.5-macosx-10.11-x86_64.egg/PIL/_imaging.py", line 6, in __bootstrap__
  File "imp.py", line 342, in load_dynamic
ImportError: dlopen(/var/folders/8q/s7mvwl1n65v20g4fbdhqx6jh0000gn/T/_MEIhTGvQX/PIL/_imaging.cpython-35m-darwin.so, 2): image not found
```

**Comment by DiogoFerrari** [comment] 2017-05-28 21:15
I have the same problem here. It says it completed the process successfully when I run pyinstaller, but when I run the application I get

Failed to execute script <my-script>
Traceback (most recent call last):
  File "<my-script>.py", line 8, in <module>
  File ".../virtual-envs/py3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "tkinter/__init__.py", line 35, in <module>
  File ".../virtual-envs/py3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/path/to/my/application/<my-script>/_tkinter.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /path/to/my/application/<my-script>/_tkinter.so
  Reason: no suitable image found.  Did find:
	/path/to/my/application/<my-script>/Tcl: not a file
	/path/to/my/application/<my-script>/Tcl: not a file
`
Tcl and Tk are copied to the folder .../<my-script>/ correctly, but I get thar error.

**Comment by htgoebel** [comment] 2017-08-31 19:56
Pillow's PIL.ImageTk [imports Tkinter reps. tkinter](https://github.com/python-pillow/Pillow/blob/4.2.1/PIL/ImageTk.py#L30] since ([v1.0]((https://github.com/python-pillow/Pillow/blob/1.0/PIL/ImageTk.py#L28].

The comments above come down to:
1. directory `tcl` is missing
2. `ImportError: dlopen(…/PIL._imagingtk.so, 2): Library not loaded: @loader_path/Tcl` - again directory `Tcl` missing
3. `ImportError: dlopen(…/_MEIhTGvQX/PIL/_imaging.cpython-35m-darwin.so, 2): image not found` (using Pillow-3.3.1-py3.5)
4. `ImportError: dlopen(…<my-script>/_tkinter.so, 2): Library not loaded: @loader_path/Tcl` - again directory `Tcl` missing

So these are two errors:
1. Directory tcl missing
2. `_imaging.so` missing

**Comment by htgoebel** [comment] 2017-08-31 19:59
Re. 1.   Directory tcl missing: duplicate of  #1350
Re. 2. `_imaging.so` missing: duplicate of #869

**Comment by Legorooj** [comment] 2020-03-08 00:45
Stale

**Closed by Legorooj** 2020-03-08 00:45 UTC
Labels: @low, area:hooks, platform:OS X, pull-request wanted, version:2.1, version:3.2
