### ISSUE TITLE
helloworld on Mac OSX with PySide crashes without explicit "from PySide import QtCore, QtGui"

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#716] opened 2014-10-18 14:38 UTC
**Original date**: 2013/05/03
**Original reporter**: *bootch AND nc DOT rr DOT  COOM *

The attached file (small test case: hello world) builds in Pyinstaller but crashes on startup unless you uncomment the line "from PySide import QtCore, QtGui".
Note that the next line "from PySide.QtGui import QApplication...." should be sufficient??

Conditions:
OSX 10.7.5
latest dev version of Pyinstaller
PySide binary 1.1.1 from http://qt-project.org/wiki/PySide_Binaries_MacOSX
Qt 4.8.1 from same site

using no options to Pyinstaller ( directory, not --onefile)

**Comment by matysek** [comment] 2015-01-01 12:11
I think this is caused by missing hooks for pyside. This is duplicate of #299.

**Closed by matysek** 2015-01-01 12:11 UTC
Labels: develop, OS X
