### ISSUE TITLE
PyInstaller references original/compile path in errors output from the final exe 

### ISSUE THREAD

**Issue by ollierexx** [pyinstaller/pyinstaller#1724] opened 2015-12-15 09:37 UTC
Errors and tracebacks output by pyinstaller reference the original compile location. 
If the exe was compiled in the directory C:/work/project/example, tracebacks will reference this same location, even when run on other computers.

**Comment by codewarrior0** [comment] 2015-12-15 09:42
This is a duplicate of...  some other issue. Instead of hunting it down I'll just fix it like I've been meaning to do.

**Comment by ollierexx** [comment] 2015-12-15 10:53
Appologies, I did a search and could not find the issue.
Thanks!

**Comment by codewarrior0** [comment] 2015-12-15 11:25
Huh. This seems to work, but I think I'd better move the stripping code to PYZ instead of Analysis. The problem is, I need the `pathex` arg to Analysis in order to do the stripping properly.

**Comment by htgoebel** [comment] 2015-12-16 10:32
I admit, that using the modulegraph functionality here is tempting. But I'afraid, this (again) does not handle all cases. If the byte-code is not delivered by module-graph (eg. since the Analizes-cache is used (.toc-files)), the source is compiles elsewhere. And in this case, we do still get the original path.

The correct place to handle this is just before writing the byte-codt into the PYZ, as we already had (oatially working) in #1302.

And I would have appreciated a lot if you would not push such a long-standing issues within hours without giving others to time to review. We already have quite some tickets on this issue, so it's obvious, that this is not that simple to solve.

**Comment by codewarrior0** [comment] 2015-12-16 10:41
> If the byte-code is not delivered by module-graph (eg. since the Analizes-cache is used (.toc-files)), the source is compiles elsewhere. 

I caught on to that after reading #1302 again. On the upside, this modulegraph method does have the right code for scanning the code objects and replacing the filenames, so it can be copied into PYZ instead of used on modulegraph directly.

On the downside, PYZ still needs to be informed of pathex in order to strip filenames included from paths in pathex in addition to paths in sys.path.

Sorry for pushing so quickly. I was just a bit excited about getting this fixed, after seeing hundreds of tracebacks from users that had my own local paths in them. I figured a partial fix was better than none at all.

**Comment by codewarrior0** [comment] 2015-12-16 10:43
> PYZ still needs to be informed of pathex in order to strip filenames included from paths in pathex in addition to paths in sys.path.

Haha, never mind, this isn't a problem. pathex is exposed in CONF. This should be simple.

**Comment by codewarrior0** [comment] 2015-12-18 07:19
Fixed.

**Closed by codewarrior0** 2015-12-18 07:19 UTC
Labels: feature
