### ISSUE TITLE
OSX  10.11: Unable to build even simple script in El Capitan (missing 32bit bootloader)

### ISSUE THREAD

**Issue by machawk1** [pyinstaller/pyinstaller#1586] opened 2015-10-08 02:12 UTC
I am having fundamental issues with Pyinstaller 3.0 (installed with `pip`) after upgrading both from Pyinstaller 2.1 and from OS X 10.10.5 to OS X 10.11. I first completely uninstalled python via homebrew and removed all remnants of Pyinstaller per [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). A very basic program runs as expected.
```py
#!/usr/bin/env python
print "I'm a test"
```
```sh
$ python hello.py 
I'm a test
```

An error occurs when I try to create a binary from the script:
```sh
$ pyinstaller hello.py
23 INFO: PyInstaller: 3.0
23 INFO: Python: 2.7.10
29 INFO: Platform: Darwin-15.0.0-x86_64-i386-32bit
37 INFO: wrote /Users/machawk1/Desktop/hello.spec
43 INFO: UPX is not available.
44 INFO: Extending PYTHONPATH with /Users/machawk1/Desktop
44 INFO: checking Analysis
53 INFO: checking PYZ
57 INFO: checking PKG
57 INFO: Bootloader /Library/Python/2.7/site-packages/PyInstaller/bootloader/Darwin-32bit/run
57 INFO: checking EXE
58 INFO: Building EXE because out00-EXE.toc is non existent
58 INFO: Building EXE from out00-EXE.toc

Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. See <http://pythonhosted.org/PyInstaller/#building-the-bootloader>
for more details and instructions how to build the bootloader.
```

These instructions tell me to "cd into the distribution folder". Where is this? Are there really no precompiled bootloaders for OS X?

Environment details:
$ python --version
Python 2.7.10
$ pyinstaller --version
3.0

**Comment by codewarrior0** [comment] 2015-10-08 02:19
> 29 INFO: Platform: Darwin-15.0.0-x86_64-i386-32bit

Precompiled bootloaders for 32-bit Python are no longer included. 64-bit Python is supposed to be the default version on newer versions of OS X. I believe you can use this command (from `man python`) to set the default back to 64-bit:

`defaults write com.apple.versioner.python Prefer-32-Bit -bool no`

**Comment by machawk1** [comment] 2015-10-08 02:23
@codewarrior0 I ran the command to no avail.
```sh
$ defaults write com.apple.versioner.python Prefer-32-Bit -bool no
$ pyinstaller hello.py 
28 INFO: PyInstaller: 3.0
28 INFO: Python: 2.7.10
36 INFO: Platform: Darwin-15.0.0-x86_64-i386-32bit
36 INFO: wrote /Users/machawk1/Desktop/hello.spec
44 INFO: UPX is not available.
45 INFO: Extending PYTHONPATH with /Users/machawk1/Desktop
45 INFO: checking Analysis
53 INFO: checking PYZ
57 INFO: checking PKG
57 INFO: Bootloader /Library/Python/2.7/site-packages/PyInstaller/bootloader/Darwin-32bit/run
57 INFO: checking EXE
57 INFO: Building EXE because out00-EXE.toc is non existent
58 INFO: Building EXE from out00-EXE.toc

Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. See <http://pythonhosted.org/PyInstaller/#building-the-bootloader>
for more details and instructions how to build the bootloader.
```
I also opened a new terminal session and re-ran the above with the same result, just to verify there was not anything sticking to the session.

**Comment by machawk1** [comment] 2015-10-08 02:29
I noticed there is a directory at `/Library/Python/2.7/site-packages/PyInstaller/bootloader/Darwin-64bit` but nothing at `/Library/Python/2.7/site-packages/PyInstaller/bootloader/Darwin-32bit`. Is it possible to instruct Pyinstaller to use the 64-bit bootloader?

**Comment by codewarrior0** [comment] 2015-10-08 02:34
Yes, all it takes is to run the 64-bit version of Python. Maybe the `pyinstaller` script is sticking to the 32-bit Python, since it was installed using a 32-bit `pip`. Try running `python -c "import platform; print(platform.architecture())"` to verify that python is running as 64-bit, and then `pip uninstall -y pyinstaller; pip install pyinstaller` to reinstall PyInstaller.

**Comment by machawk1** [comment] 2015-10-08 02:46
`python -c "import platform; print(platform.architecture())"` was indicating 32-bit but another `defaults write com.apple.versioner.python Prefer-32-Bit -bool no` results in `('64bit', '')`. I am encountering a different error with the same program.

```sh
# Cleaning up previous attempts.
$ sudo rm -rf "/Users/machawk1/Library/Application Support/pyinstaller"
$ sudo rm -rf dist build hello.spec
# Trying pyinstaller again
$ pyinstaller hello.py 
21 INFO: PyInstaller: 3.0
21 INFO: Python: 2.7.10
26 INFO: Platform: Darwin-15.0.0-x86_64-i386-64bit
34 INFO: wrote /Users/machawk1/Desktop/hello.spec
35 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/bin/python

1041 INFO: UPX is not available.
1042 INFO: Extending PYTHONPATH with /Users/machawk1/Desktop
1043 INFO: checking Analysis
1043 INFO: Building Analysis because out00-Analysis.toc is non existent
1043 INFO: Initializing module dependency graph...
1045 INFO: Initializing module graph hooks...
1107 INFO: running Analysis out00-Analysis.toc
1112 INFO: Analyzing /Users/machawk1/Desktop/hello.py
1113 INFO: Looking for import hooks ...
1115 INFO: Processing hook   hook-encodings.py
3311 INFO: Looking for ctypes DLLs
3311 INFO: Analyzing run-time hooks ...
3317 INFO: Looking for dynamic libraries
3422 INFO: Looking for eggs
3422 INFO: Python library not in binary depedencies. Doing additional searching...
3425 INFO: Using Python library /System/Library/Frameworks/Python.framework/Versions/2.7/Python
3429 INFO: Warnings written to /Users/machawk1/Desktop/build/hello/warnhello.txt
3432 INFO: checking PYZ
3432 INFO: Building PYZ because out00-PYZ.toc is non existent
3432 INFO: Building PYZ (ZlibArchive) /Users/machawk1/Desktop/build/hello/out00-PYZ.pyz
3545 INFO: checking PKG
3546 INFO: Building PKG because out00-PKG.toc is non existent
3546 INFO: Building PKG (CArchive) out00-PKG.pkg
3554 INFO: Bootloader /Library/Python/2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
3554 INFO: checking EXE
3554 INFO: Building EXE because out00-EXE.toc is non existent
3554 INFO: Building EXE from out00-EXE.toc
3565 INFO: Appending archive to EXE /Users/machawk1/Desktop/build/hello/hello
3567 INFO: Fixing EXE for code signing /Users/machawk1/Desktop/build/hello/hello
3574 INFO: checking COLLECT
3574 INFO: Building COLLECT because out00-COLLECT.toc is non existent
3574 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/Library/Python/2.7/site-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/Library/Python/2.7/site-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/Library/Python/2.7/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Library/Python/2.7/site-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/building/api.py", line 653, in __init__
    self.__postinit__()
  File "/Library/Python/2.7/site-packages/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Library/Python/2.7/site-packages/PyInstaller/building/api.py", line 685, in assemble
    dist_nm=inm)
  File "/Library/Python/2.7/site-packages/PyInstaller/building/utils.py", line 242, in checkCache
    shutil.copy2(fnm, cachedfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/machawk1/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so'
```

**Comment by AcidWeb** [comment] 2015-10-08 07:03
I suggest you to use python2 from homebrew.

Additionally you should be aware that building your script on 10.11 make in incompatible with older OS X releases.

**Comment by matysek** [comment] 2015-10-08 08:42
@machawk1 Please try to use pyinstaller with option `--clean`.

**Comment by machawk1** [comment] 2015-10-08 13:32
@AcidWeb I thought I was but the paths read otherwise. Is there anything I can do to ensure my script's compatibility with older 64-bit versions of OS X? Is there a ticket I can follow for improving this backward compatibility? Now:
```sh
$ which python
/usr/local/bin/python
$ python --version
Python 2.7.10
```

@matysek In using the `--clean` option, I still get the error:
```sh
$ pyinstaller --clean hello.py 
20 INFO: PyInstaller: 3.0
20 INFO: Python: 2.7.10
35 INFO: Platform: Darwin-15.0.0-x86_64-i386-64bit
36 INFO: wrote /Users/machawk1/Desktop/hello.spec
36 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/bin/python

1047 INFO: UPX is not available.
1047 INFO: Removing temporary files and cleaning cache in /Users/machawk1/Library/Application Support/pyinstaller
1049 INFO: Extending PYTHONPATH with /Users/machawk1/Desktop
1050 INFO: checking Analysis
1050 INFO: Building Analysis because out00-Analysis.toc is non existent
1050 INFO: Initializing module dependency graph...
1052 INFO: Initializing module graph hooks...
1112 INFO: running Analysis out00-Analysis.toc
1118 INFO: Analyzing /Users/machawk1/Desktop/hello.py
1119 INFO: Looking for import hooks ...
1120 INFO: Processing hook   hook-encodings.py
3299 INFO: Looking for ctypes DLLs
3299 INFO: Analyzing run-time hooks ...
3306 INFO: Looking for dynamic libraries
3402 INFO: Looking for eggs
3402 INFO: Python library not in binary depedencies. Doing additional searching...
3405 INFO: Using Python library /System/Library/Frameworks/Python.framework/Versions/2.7/Python
3408 INFO: Warnings written to /Users/machawk1/Desktop/build/hello/warnhello.txt
3410 INFO: checking PYZ
3411 INFO: Building PYZ because out00-PYZ.toc is non existent
3411 INFO: Building PYZ (ZlibArchive) /Users/machawk1/Desktop/build/hello/out00-PYZ.pyz
3526 INFO: checking PKG
3527 INFO: Building PKG because out00-PKG.toc is non existent
3527 INFO: Building PKG (CArchive) out00-PKG.pkg
3536 INFO: Bootloader /Library/Python/2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
3536 INFO: checking EXE
3536 INFO: Building EXE because out00-EXE.toc is non existent
3536 INFO: Building EXE from out00-EXE.toc
3545 INFO: Appending archive to EXE /Users/machawk1/Desktop/build/hello/hello
3547 INFO: Fixing EXE for code signing /Users/machawk1/Desktop/build/hello/hello
3554 INFO: checking COLLECT
3554 INFO: Building COLLECT because out00-COLLECT.toc is non existent
WARNING: The output directory "/Users/machawk1/Desktop/dist/hello" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
11257 INFO: Removing dir /Users/machawk1/Desktop/dist/hello
11258 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/Library/Python/2.7/site-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/Library/Python/2.7/site-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/Library/Python/2.7/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Library/Python/2.7/site-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/building/api.py", line 653, in __init__
    self.__postinit__()
  File "/Library/Python/2.7/site-packages/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Library/Python/2.7/site-packages/PyInstaller/building/api.py", line 685, in assemble
    dist_nm=inm)
  File "/Library/Python/2.7/site-packages/PyInstaller/building/utils.py", line 242, in checkCache
    shutil.copy2(fnm, cachedfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/machawk1/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so'
```

**Comment by AcidWeb** [comment] 2015-10-08 13:37
Backward compatibility on OS X is somewhat complex.

Easy way: Compile everything on oldest OS X release you want to support.
Hard way: Experiment with MACOSX_DEPLOYMENT_TARGET. And make sure that everything that is packed in to executable was compiled when this system variable was set to oldest OS X version you want to support.

**Comment by machawk1** [comment] 2015-10-08 13:42
@AcidWeb, thanks for the info. I will refer back to your comment once I can get pyinstaller working again on El Capitan (this ticket).

**Comment by machawk1** [comment] 2015-10-08 16:04
For testing's sake, I `pip uninstall pyinstaller` then `pip install pyinstaller=2.1`, repeated the steps above with the `hello.py` and more complicated Python scripts with complete success. I would like to use the features in Pyinstaller 3.0 but will sticking with 2.1 ensure a greater degree of backward compatibility with older versions of OS X for now, @AcidWeb?

**Comment by AcidWeb** [comment] 2015-10-08 16:08
Version of Pyinstaller is not connected to backward compatibility. Any piece of code that is compiled on 10.11 without proper environment **might** fail on older OS X versions.

**Comment by matysek** [comment] 2015-10-08 21:30
@machawk1 Look at this wiki page. It contains some information about macports and how to achieve somme backwards compatibility: http://wiki.openlp.org/Testing:Mac_OS_X_Testing_Environment#Settings_for_Mac_OS_X_Compatibility

**Comment by matysek** [comment] 2015-10-08 21:32
@tallforasmurf Are there any information about OS X compatiblity in this discussion that is worth document in the manual?

**Comment by tallforasmurf** [comment] 2015-10-08 22:39
It looks as if something should be said about this. Right now the manual just says what the program says when it runs, "will only work on 10.6+". But before making any changes, some things are not clear.

* is it true the distributed 32-bit bootloader does not work in 10.11? What versions does it work in? Can it be upgraded or is it dead as of 10.11?

* do I get the impression that when bundling in 10.11, the "10.6+" message is not true for 64-bit apps? Should it be reworded or eliminated?

* PyInstaller 3.0 is still putting out the message about how to run 32-bit, but I thought this issue was exactly about 32-bit not working? Is it supposed to work now? If you do what PyInstaller says ("run Python as a 32-bit binary with...") in a 10.11 compile, will you get something that runs in 10.5?

* @machawk1 seems to say, using PyInstaller 2.1 in OSX10.11 produces a good app, while PyInstaller 3.0 does not, in the same 10.11 dev environment. Is this a new restriction, or an issue?

@AcidWeb I finally found the Apple doc for MACOSX_DEPLOYMENT_TARGET  (https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW129) however that same page has like 20 other vars that might also affect the output. Anyway I am not sure of the relevance of MACOSX_DEPLOYMENT_TARGET to the PyInstaller user. Is it not more relevant to the person compiling the bootloader? Or is that what you had in mind, compiling one's own custom bootloader?

**Comment by AcidWeb** [comment] 2015-10-09 04:38
@tallforasmurf - Remember that bootloader is not only compiled part. Python, C parts of Python extenstions etc.

Execute ``export DYLD_PRINT_LIBRARIES=1`` in console and start binary made by PyInstaller. You will see how many system libraries are used. If any part of frozen app expect to find any endpoint that exist only in 10.11 - application will fail. ``MACOSX_DEPLOYMENT_TARGET `` tell compiler to force backward compatibility.

I distribute simple Python3 application - Pillow, pyQT5, psutil and I'm forced to use old OS X (10.8 in my case) to create binary. As my attempts to create environment that will allow to compile backward compatible binary on 10.10 and .11 failed.

In this entire endeavor PyInstaller bootloader is the smallest problem.

IMHO message about 32 bit compatibility can be completely dropped. 32 bit OS X simply don't exist anymore.

**Comment by matysek** [comment] 2015-10-09 12:15
> IMHO message about 32 bit compatibility can be completely dropped. 32 bit OS X simply don't exist anymore.

I think we should drop this message then.

Summary what we should document:
* recommend using older OSX if app compatibility is needed. This should be the safest option.
* recommend using macports/homebrew and play with the `MACOSX_DEPLOYMENT_TARGET` and we could try to find some linkes to macport/homebrew doc that mentions this.

**Comment by AcidWeb** [comment] 2015-10-09 12:17
Relevant: https://github.com/Homebrew/homebrew/issues/16285

**Comment by tallforasmurf** [comment] 2015-10-09 18:13
@AcidWeb yes, highly relevant. What that says is, **anything you install with homebrew** will be built for the current system -- which would include Python itself and any .so's built by pip/setup. So if you use homebrew, any PyInstaller bundle is contaminated for use in an older system. This adds weight to the  recommendation, "build on the oldest system you need to support". That is a simple, clean solution, and with VMs so easy to deploy on modern hardware, it is no great hardship.

If that is to be our recommendation -- and I think it should be, and will change the doc to say this -- then the entire 3-line message `WARNING: You are running 64-bit Python... arch -i386 /usr/bin/python` should be deleted. It is not relevant to current systems. It would be relevant as a reminder, if you are deliberately building in an old Mac OS, say, Snow Leopard 10.6 where you had a choice of word length. But, if you are deliberately building in a back-level OS, you have already taken many steps to ensure compatibility and you should not need a run-time reminder.

However, I will put the `VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/bin/python` business in the manual (after I try it, because you know? that does not look like a valid command to me).

**Comment by tallforasmurf** [comment] 2015-10-09 19:59
Check the updated text under "Building Mac OS X App Bundles". If no problems I will close this.
https://github.com/pyinstaller/pyinstaller/blob/develop/doc/Manual.html

**Comment by AcidWeb** [comment] 2015-10-09 20:04
Changes are good but I think we derailed this issue a "little". I think that original problem is still not solved.

**Comment by matysek** [comment] 2015-10-09 21:13
* Original problem was about 32bit python and missing bootloader and it was clarified.
* For the another issue with permissions error there should be created a new ticket.
@tallforasmurf Please close this issue if you are fine with your doc updates.
@machawk1 If you'd like the `OSError: [Errno 1] Operation not permitted:` to be debugded please open a new issue with description how to reproduce it.

**Closed** 2015-10-10 01:33 UTC
Labels: documentation, OS X, PY2, v3.0

**Comment by machawk1** [comment] 2015-10-10 01:46
@matysek Is the original ticket's title, "Unable to build even simple script in El Capitan" solved? If one gets pyinstaller via pip on OS X 10.11, will they be able to compile a script to an OS X .app?

Can anyone else verify success with compiling scripts to binary with pyinstaller on OS X 10.11 (to mitigate any environment issues I have)? That was the purpose of this ticket.

**Comment by matysek** [comment] 2015-10-10 08:36
@machawk1 The original title was too vague and 'missing bootloader' was the first identified error. If there is another start a new ticket that will be dedicated just to that issue.

**Comment by JokerQyou** [comment] 2015-10-22 14:48
I'm experiencing the same problem here. PyInstaller breaks with `OSError: [Errno 1] Operation not permitted` on one of its `bincache` files. I think it's either file permission issue or `chflags` issue.
My environment is Mac OS X 10.11 with prebuilt Python 2.7.10, PyInstaller 3.0.

**Comment by matysek** [comment] 2015-10-22 16:22
@JokerQyou please open a new issue in that case.
