### ISSUE TITLE
python3.5.2 find a errors"lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\select.pyd'

### ISSUE THREAD

**Issue by jinjingcai2014** [pyinstaller/pyinstaller#2216] opened 2016-10-06 16:55 UTC
I just write Hello.py ,I try Hello.py convert to exe, But the exe file cann't be executable. I found "lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\select.pyd', so I need your help.  OS:   windows 10 , python version: 3.5.2  Thank you.

**Comment by jinjingcai2014** [comment] 2016-10-06 16:55
WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6479 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6550 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6622 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6702 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6778 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6850 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6921 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
6992 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
7063 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ssl.pyd
7292 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ctypes.pyd
7364 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ctypes.pyd
7436 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_ctypes.pyd
7581 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\pyexpat.pyd
7653 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\pyexpat.pyd
7724 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\pyexpat.pyd
7795 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\pyexpat.pyd
7867 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\pyexpat.pyd
8038 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8110 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8183 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8257 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8332 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8403 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8474 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8545 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8617 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_hashlib.pyd
8757 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_lzma.pyd
8827 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_lzma.pyd
9027 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_socket.pyd
9099 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_socket.pyd
9223 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\unicodedata.pyd
9296 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\unicodedata.pyd
9367 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\unicodedata.pyd
9501 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_bz2.pyd
9572 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_bz2.pyd
9643 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_bz2.pyd
9720 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_bz2.pyd
9792 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\_bz2.pyd
9907 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\soft\python3.5\DLLs\select.pyd

**Comment by jinjingcai2014** [comment] 2016-10-06 16:56
I also install VS2015

**Comment by ZGuangW** [comment] 2016-10-26 13:25
install Visual C++ Redistributable for Visual Studio 2015

**Comment by fleytman** [comment] 2016-10-28 08:29
see https://github.com/pyinstaller/pyinstaller/issues/1566

**Comment by htgoebel** [comment] 2017-09-12 10:01
Duplicate of #1566

**Closed by htgoebel** 2017-09-12 10:01 UTC

**Comment by Moriand** [comment] 2017-11-22 01:26
use dependency walker in your exe export
