### ISSUE TITLE
Mac OS X Lion crash: Symbol not found: _environ, Expected in: /usr/lib/libSystem.B.dylib

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#694] opened 2014-10-18 14:36 UTC
**Original date**: 2013/03/26
**Original reporter**: *ferraro DOT joseph AND gmail DOT  COOM *

Mac OS X 10.7.4 user getting the following crash report:

Error loading Python lib '/path/to/app/libpython2.7.dylib': dlopen(/path/to/app/libpython2.7.dylib, 10): Symbol not found: _environ
  Referenced from: /path/to/app/libpython2.7.dylib
  Expected in: /usr/lib/libSystem.B.dylib

App is frozen using --onedir and it working fine in 10.8.x

**Comment by matysek** [comment] 2015-07-30 12:13
Duplicate of #1191

**Closed by matysek** 2015-07-30 12:13 UTC
Labels: support, v2.0
