### ISSUE TITLE
Handle internal hiddenimports in the Entrypoint-recipe

### ISSUE THREAD

**Issue by nyyManni** [pyinstaller/pyinstaller#6088] opened 2021-08-03 10:48 UTC
The wiki guide  (https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Setuptools-Entry-Point) for using PyInstaller with pkg_resources entry points has an issue with hiddenimports within a package.

Suppose we have a project structured like this:
```
module
 |- main
 |- submodule1
 `- submodule2
```
, where the two submodules are imported from main, but with importlib instead of a direct import.

To make PyInstaller aware of the new submodules, one can provide `hiddenimports=['module.submodule1', 'module.submodule2']`, for the EntryPoint constructor. This causes an error in the `get_toplevel`-function, as those modules are not packages.

To fix this, we should catch `pkg_resources.DistributionNotFound` in `get_toplevel`, and return an empty list in those cases, or would there be a cleaner way of handling this?

**Comment by rokm** [comment] 2021-08-06 19:34
As far as I can see, `Entrypoint.get_toplevel()` is expecting to be passed *dist* names, not *package* or *submodule* names. The problem is that it is given `Analysis`-style `hiddenimports`, which contains either *packages* or *submodules*, but not *dist* names (although passing *dist* name to `Analysis` does not generate an error, only a warning about module not being found).

So while having `get_toplevel` return empty list on error would hide the problem, I think a better fix would to separate the two concepts by adding extra `hiddendists` argument to `Entrypoint()` for specifying the dist names that need to be looked up and resolved into top-level packages. 

Another improvement would be appending those resolved packages to `hiddenimports` before passing them to `Analysis`, instead of printing them at the end of generated "entry-point" script...

**Comment by nyyManni** [comment] 2021-11-29 11:59
What is the process in maintaining the wiki page?

I would gladly update the guide but wiki does not seem to have a pull-request -type contribution option, and I don't want to go directly edit the page (if it even lets me do that).

**Comment by bwoodsend** [comment] 2021-11-29 19:37
You really do just edit it. There is a revision history so it can be reverted if you accidentally butcher it.

**Closed** 2022-06-13 19:31 UTC
Labels: feature, triage
