### ISSUE TITLE
Cannot import module if source file has the same name (pyinstaller 3.2)

### ISSUE THREAD

**Issue by ma1co** [pyinstaller/pyinstaller#2049] opened 2016-06-14 21:19 UTC
How to reproduce:
* Create `test/__init__.py` with following content:
```python
print 'module'
```
* Create `test.py` (same name as module) with following content:
```python
import test
print 'main file'
```
* Run `pyinstaller test.py`
* Run the executable

With version 3.1.1, 'main file' is printed (correct behavior). With version 3.2 and later, the wrong file is executed, it prints 'module'.

I'm using Python 2.7 on Windows.

**Comment by stephenrauch** [comment] 2016-06-15 02:23
The wiki has a [nice page on how to report bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) so that the devs have the best chance of helping you. Having said that, this may be a duplicate of #1935.  That bug has been fixed on the development tip. From the wiki:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Please try latest development version and let us know if the bug is already fixed there. Simply use_

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   _to install the latest git version._

That may get you going.  Please report back...

**Comment by ma1co** [comment] 2016-06-15 11:29
Sry for the quick bug report, I was in a hurry. I just realized that the executable doesn't actually crash, it just runs the wrong file. I updated my previous post.

The bug is still present on the develop branch.

I ran git-bisect and I think the bug was introduced with 7933cbbe1fabb2150c74be95be49a3049b304aa4 (I can't really verify cause I can't compile the bootloader).

If I take the develop branch, but `PyInstaller/archive/writers.py` and `PyInstaller/bootloader` from 7933cbbe1fabb2150c74be95be49a3049b304aa4's parent, everything works again.

**Comment by ma1co** [comment] 2016-06-15 11:53
Ok, I found the problem: When `PyInstaller.archive.writers.CArchiveWriter.add()` adds the main file, it calls `PyInstaller.building.utils.get_code_object('test', 'test.py')`, which returns `<code object <module>, file "test/__init__.py">` (the wrong file!)

**Comment by htgoebel** [comment] 2016-06-15 13:26
This is not a bug of PyInstaller. Python does not permit having both a module and a package named `test`.

**Closed by htgoebel** 2016-06-15 13:26 UTC
Labels: invalid

**Comment by ma1co** [comment] 2016-06-15 14:21
You're probably right, it is ambiguous. I'll solve it by manually renaming the scripts in `a.scripts` after analysis. Thanks for the help.
