### ISSUE TITLE
Code-signed executables with Tk do not work

### ISSUE THREAD

**Issue by rasky** [pyinstaller/pyinstaller#171] opened 2014-10-18 13:34 UTC
**Original date**: 2010/04/01

PyInstaller projects using Tk support (Makespec --tk) are broken when using code-signing.

There are two possible fixes here, and both should be eventually done:

 - Remove the explicit support for Tk and rely on the new infrastructure of data files from hooks to package Tk data files.
 - Make CArchive compatible with code-signed executables, for users attempting runtime extraction of data.

**Comment by matysek** [comment] 2015-07-30 12:39
Duplicate of pull request #1075

**Closed by matysek** 2015-07-30 12:39 UTC
Labels: OS X
