### ISSUE TITLE
Setuptools 60.7.0 breaks the executable

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#6565] opened 2022-02-02 17:55 UTC
Building with setuptools==60.7.0 I get this error.
There is no `jaraco` module (seems like this is the author of `setuptools)
```
(simulator_venv) ➜  agent git:(feature/SB-22361-improve-socket-error-handling) ✗ dist/sbsimulator/sbsimulator
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 16, in <module>
  File "/Users/arossert/Shared/Bitbucket/agent/simulator_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 74, in <module>
    from pkg_resources.extern.jaraco.text import (
  File "/Users/arossert/Shared/Bitbucket/agent/simulator_venv/lib/python3.8/site-packages/pkg_resources/extern/__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "/Users/arossert/Shared/Bitbucket/agent/simulator_venv/lib/python3.8/site-packages/pkg_resources/extern/__init__.py", line 44, in load_module
    raise ImportError(
ImportError: The 'jaraco' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
[23421] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

PyInstaller: 4.8
OS: Linux/Mac (not tested on Windows)
Python: 3.8.10

**Comment by rokm** [comment] 2022-02-02 18:11
Duplicate of #6564. But let's keep both open for now in an attempt to avoid even more duplicates...

**Closed as completed** 2022-02-03 20:54 UTC
Labels: triage
