### ISSUE TITLE
Source a .sh file containing pyinstaller command can't work

### ISSUE THREAD

**Issue by Ell3nHsu** [pyinstaller/pyinstaller#5370] opened 2020-12-07 11:38 UTC
There is a customized module that imported in the file that is going to be packaged with PyInstaller. In order to make it work, I added a hooks-dir contained a hook file as [this issue](https://github.com/pyinstaller/pyinstaller/issues/4809) said. When I used the command `pyinstaller -F main.py --additional-hooks-dir=hooks` in console window, everything was fine. The file was packaged successfully and it worked well.
However, when I tried to use this command on console  `source build.sh`, (in the build.sh file, there was exactly the command I used in the console), it didn't work. The hooks dir couldn't be found. So I couldn't use the customized module when I executed the packaged file. 
this is the error info:
```
pkg_resources.DistributionNotFound: The 'customized-module-name' distribution was not found and is required by the application
```

Any suggestions would be really appreciated.

OS: Mac OS 10.14
Python: 3.9
PyInstaller: 4.1

**Comment by rokm** [comment] 2020-12-07 12:05
The error message means that metadata for your custom module is not packaged, which is probably the consequence of your hook not being found.

You should probably be specifying an absolute path to the `hooks` directory, otherwise its resolution will depend on the current working directory, which may not be what you assume it is. 

You could start with trying to hard-code the absolute path on the disk. If that turns out to work, and you want more flexibility, you could then try resolving the path to the build script file itself, and then anchor the path to `hooks` to that...

**Comment by rokm** [comment] 2020-12-07 12:21
Although now that I think about it, if this were a path/working directory issue, there would probably also be an issue with finding the `main.py` file...

Can you attach your build script here?

**Comment by Ell3nHsu** [comment] 2020-12-08 06:19
This is how I put those files.
```
- raw
  - api
    - ...
  - hooks
    - hook-custom_module_name.py
  - build.sh
  - main.py  
```
and this is the build script
```
echo '=============='
pyinstaller -F main.py --add-data="./api:." --additional-hooks-dir=/Users/kitty/Desktop/packaging/raw/hooks
echo '=============='
```

I have tried absolute path  and relevant path, but neither of them worked. It still couldn't find the hooks directory while packaging.
actually when I used this command directly on console window, it worked fine. Custom module was found and packaged.
```
pyinstaller -F main.py --add-data="./api:." --additional-hooks-dir=hooks
```

besides, there is another question. when I added `--clean` in the build script command, there was `pyinstaller: error: unrecognized arguments: --clean` coming out.

**Comment by rokm** [comment] 2020-12-08 13:03
I can't reproduce this issue - sourcing a build script here works as expected. 

I can't think of a reason why passing arguments from the script would behave differently than directly from console, unless there's a typo in the script... Does copying the `pyinstaller ...` line from the build script and pasting it into console work?

Can you attach your `build.sh` file (the version with `--clean` added)?  Do not copy & paste its content, but attach the file itself by drag&dropping it (you'll probably need to rename it to `build.txt` for github to accept it).

**Comment by Ell3nHsu** [comment] 2020-12-09 02:16
the build script is attached.
This is weird. I will test it on another mac pc and see if it works. will let you know the result. Thank you.
[build.txt](https://github.com/pyinstaller/pyinstaller/files/5663122/build.txt)

**Comment by rokm** [comment] 2020-12-09 09:49
It probably won't work on another mac, either.

Trying to source your script, I get:
```
: command not found
==============
: command not found
: No such file or directoryging/raw
: command not found
usage: pyinstaller [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME] [--add-data <SRC;DEST or SRC:DEST>] [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR] [--hidden-import MODULENAME] [--additional-hooks-dir HOOKSPATH] [--runtime-hook RUNTIME_HOOKS]
                   [--exclude-module EXCLUDES] [--key KEY] [-d {all,imports,bootloader,noarchive}] [-s] [--noupx] [--upx-exclude FILE] [-c] [-w] [-i <FILE.ico or FILE.exe,ID or FILE.icns>] [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE] [--uac-admin]
                   [--uac-uiaccess] [--win-private-assemblies] [--win-no-prefer-redirects] [--osx-bundle-identifier BUNDLE_IDENTIFIER] [--runtime-tmpdir PATH] [--bootloader-ignore-signals] [--distpath DIR] [--workpath WORKPATH] [-y] [--upx-dir UPX_DIR] [-a]
                   [--clean] [--log-level LEVEL]
                   scriptname [scriptname ...]
pyinstaller: error: unrecognized arguments: --clean
: command not found
: command not found
==============
```

See all those "empty" command not found lines? 

All these errors occur because the script is using CRLF (Windows) newlines instead of the LF ones. So I suspect that the CR character on the pyinstaller command line is messing up the last command-line argument; formerly, this was the path you gave to `--additional-hooks-dir`, and now it is the `--clean` command.

Try running `perl -pi -e 's/\r\n/\n/g' build.sh` to fix the newlines (or use your editor to do it for you). It should work afterwards.

**Comment by Ell3nHsu** [comment] 2020-12-09 10:30
Yes, you are right. After running the command to to fix the newlines problem, sourcing build script worked perfectly.
I created this script on a Windows computer because I firstly tested pyinstaller tool on Windows system. Then I just copied those files to Mac pc and forgot about the format issue.
Anyway, problem is solved. I really appreciate for your help. Have a nice day.

**Closed** 2020-12-09 11:01 UTC
Labels: kind:support
