### ISSUE TITLE
Could not find QtWebEngineProcess

### ISSUE THREAD

**Issue by train860** [pyinstaller/pyinstaller#2276] opened 2016-11-19 18:14 UTC
I use PyQt5.6 and the pyinstaller3.2 on mac os,but got "Could not find QtWebEngineProcess" error.I know that I need pack QtWebEngineProcess to my app,but how?

is there a way out?

**Comment by glennra** [comment] 2016-11-28 06:29
If you look inside the packaged app is the QWebEngineProcess.app in there? It should be in your.app/Contents/MacOS/ .

**Comment by train860** [comment] 2016-11-28 06:30
@glennra no，not there

**Comment by tallforasmurf** [comment] 2016-11-28 07:04
Look in your.app/Contents/Resources, at least a release or 2 back they would "deploy" the webengine framework there with the actual app buried in it.

**Comment by The-Compiler** [comment] 2017-02-19 13:30
With PyQt 5.8 from PyPI, I got some progress by doing some manual copying of things into the `.app`:

```
$ cp -r .venv/lib/python3.6/site-packages/PyQt5/Qt/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app qutebrowser.app/Contents/MacOS/
$ cp -r .venv/lib/python3.6/site-packages/PyQt5/Qt/lib/QtWebEngineCore.framework/Resources/* qutebrowser.app/Resources/
```

However, after that, I get constant renderer process crashes:

```
dyld: Library not loaded: @rpath/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Users/flo/qutebrowser/dist/qutebrowser.app/Contents/MacOS/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
```

cc @xoviat

**Comment by The-Compiler** [comment] 2017-02-19 14:03
Looking at `otool -l`, the rpath of `QtWebEngineProcess` is:

```
          cmd LC_RPATH
      cmdsize 48
         path @loader_path/../../../../../ (offset 12)
```

which is the base directory of the `.app`. This crazy linking seems to make it work for me:

```bash
for lib in Core WebEngineCore Quick Qml Network Gui WebChannel Positioning; do
    mkdir -p qutebrowser.app/Qt$lib.framework/Versions/5
    ln -s ../../../Contents/MacOS/Qt$lib qutebrowser.app/Qt$lib.framework/Versions/5/Qt$lib
done
```

but probably there's a more correct solution here :wink:

**Comment by xoviat** [comment] 2017-02-19 17:30
@The-Compiler Thanks for looking into this. 

I'm not familiar with any hook that runs a link command, but that may be required. The problem is that the the libs have not been copied when the hook is run.

**Comment by The-Compiler** [comment] 2017-02-19 18:38
I'm guessing PyInstaller does some `@rpath` adjustments to binaries though? The proper way to solve this (apart from the missing copying) would probably be to make `QtWebEngineProcess` search its libraries in the right place instead?

**Comment by xoviat** [comment] 2017-02-19 18:57
We handling rpath [here][1], but I'm not sure that it's ever adjusted. There is a note about macholib not handling `rpath` correctly...
[1]: https://github.com/pyinstaller/pyinstaller/blob/5a8cd80c3b259cadca477ede36f4259bf86c6d3b/PyInstaller/depend/bindepend.py#L651

**Comment by xoviat** [comment] 2017-02-19 19:04
It also appears that our MachO lib needs to be updated...

**Comment by xoviat** [comment] 2017-03-19 00:59
Duplicate #2421.

**Comment by thiagofmam** [comment] 2017-04-27 12:50
I solved adding the flag QT5DIR to environment

`QT5DIR=/Users/thiagomeneses/Qt/5.8/clang_64`

**Comment by xoviat** [comment] 2017-08-22 03:17
Closed in #6a9709d.

**Closed** 2017-08-22 06:29 UTC

**Comment by yeshoujquery** [comment] 2017-11-07 09:52
How did the problem close? No solution was found

**Comment by tallforasmurf** [comment] 2017-11-07 15:30
@thiagofmam said he "solved" it by setting an environment variable QT5DIR which pointed to -- it looks like -- his local Qt5 installation.

It is not clear if this is done before running PyInstaller? Or if it is done before running the bundled app? (If the latter, then it means the app has a dependency on the local Qt install...)

**Comment by keshavagrawal89** [comment] 2019-05-19 02:46
PyQt5==5.12.1
PyQtWebEngine==5.12.1

I m still getting the same error even on latest versions. Have also tried setting up QT5DIR to my venev site-packages/PyQt5 dir.

**Comment by jmercouris** [comment] 2019-07-22 12:25
Can you please stop closing this issue, it is most definitely still an issue.

As of today, Python36

`pyinstaller --onefile pyqt.py`

running `./pyqt.py` --> `Could not find QtWebEngineProcess` and the program crashes.

**Comment by ColtonGarelli** [comment] 2020-01-29 15:12
This problem is still not fixed.

**Comment by glennra** [comment] 2020-05-29 06:13
`PyInstaller/hooks/rthooks/pyi_rth_pyqt5webengine.py` is looking for it at: 

`my.app/Contents/MacOS/PyQt5/Qt/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app
`

but on my machine PyInstaller has put it here:

`my.app/Contents/MacOS/PyQt5/Qt/lib/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app`

Updating `PyInstaller/hooks/rthooks/pyi_rth_pyqt5webengine.py` to reflect the actual path fixed it for me. However I am using a version of Qt5.12 that I built myself and I understand that PyInstaller targets the wheel version so maybe that explains the difference?

**Comment by bjones1** [comment] 2020-05-29 16:52
Correct -- PyInstaller targets the wheel's layout. I don't see any easy way to support these custom build variants. Perhaps documentation of sort sort? The post above is reasonable descriptive, for example.

**Comment by glennra** [comment] 2020-05-31 08:42
It's not a "custom" build. It's the standard builds of Qt5 and PyQt5 using `configure -prefix $PWD/qtbase ...` for Qt5 and `python configure.py` for PyQt5.

Is there a way to test likely several locations to see where QtWebEngineProcess has ended up?

**Comment by bjones1** [comment] 2020-06-01 00:02
"Custom" only in the sense that "it doesn't follow the PyPI wheel format." PRs are welcome, but beware that it's a fairly complex topic.
