### ISSUE TITLE
Fix multi platform building issues.

### ISSUE THREAD

**Issue by AraHaan** [pyinstaller/pyinstaller#2186] opened 2016-09-12 01:20 UTC
The Current approach of writing the following files the current way is this:

if you build x86 and then build x64 the resulting x64 build will fail to load the Python DLL.

Solution: Separate folders for each target `x86`, and `x64` files of the following names in them.

> `base_library.zip`
> 
> `<scriptname>.exe.manifest`
> 
> `out00-Analysis.toc`
> 
> `out00-EXE.toc`
> 
> `out00-PKG.pkg`
> 
> `out00-PKG.toc`
> 
> `out00-PYZ.pyz`
> 
> `out00-PYZ.toc`
> 
> `warn<scriptname>.txt`

This will for sure fix this issue. Good thing I found this to point out for systems with both 32 and 64 bit python interpreters.

So I suggest putting them under `Build\<scriptname>\x86` for 32 bit and `Build\<scriptname>\x64` for 64 bit.

**Comment by htgoebel** [comment] 2016-09-12 07:41
Thanks for tracking this down. Obviously our algorithm to detect changes needs to be improved.
Could you please try to figure out what *exactly* are the differences between a "plain" x64 build an one after a x86 build. This would halp us tracking down where we do not detect a chance we should.

**Comment by AraHaan** [comment] 2016-09-12 09:03
Well for starters on the x64 ones it seems to confuse with the 32 bit python35.dll as the 64 bit one so as suck the reason why they need to be generating separate directories or they will have a start error. Alternatively if you made pyinstaller to clear the ``Build\<scriptname>`` folder after successful build that could work as well.

**Comment by htgoebel** [comment] 2016-09-12 09:33
> on the x64 ones it seems to confuse with the 32 bit python35.dll as the 64 bit one

Yes. and we need to figure out what *exactly* went wrong. And for this we need the *exact* diffs between the two builds.

Implementing a platform-specific directory would settle the symptoms, but not cure the cause. Doing a diff on `out00-Analysis.toc` should be a good starting point.

**Comment by AraHaan** [comment] 2016-09-12 20:52
yeah, hmm what file is to start with creating the directory/ dirs in question
I could impliment a little hack using ctypes on bits of the python interpreter like I do in my bot.

something like this:

```py
import ctypes

bits = ctypes.sizeof(ctypes.c_voidp)
if bits == 4:
    arch = 'x86'
elif bits == 8:
    arch = 'x64'
```

As you can see this can be helpful.

**Comment by htgoebel** [comment] 2016-09-13 12:29
I'm not going to implement platform-specific build directories! I want to *solve* teh problem, not work-around it.

Please do the following:
1. delete the build-directory
2. build with 64-bit
3. *move* the build-directory to a save place
4. build with 32-bit
5. *keep* the build-directory
6. build with 64-bit
7. create a diff between the directory moved away in step 3 and the new build-dir

**Comment by htgoebel** [comment] 2017-09-25 19:47
No more infos since 1 year. Closing.

**Closed by htgoebel** 2017-09-25 19:47 UTC
Labels: @medium
