### ISSUE TITLE
Could not convert .py to .exe because integer was recieved as Byte.

### ISSUE THREAD

**Issue by Lethiathan** [pyinstaller/pyinstaller#4509] opened 2019-10-30 12:39 UTC
Pyinstaller keeps on having problems with python 3.8 with the following modules (also displayed in the powershell snapshots):
runpy.py
api.py
datastruct.py
utils.py

For some reason it meantions an Integer being required, but was input as Bytes instead.

![image](https://user-images.githubusercontent.com/57180530/67858317-d4d09a00-fb10-11e9-9b60-4780e181d57b.png)
![image](https://user-images.githubusercontent.com/57180530/67858380-f6318600-fb10-11e9-84b2-918aa1b1897c.png)
_Had to do it with 2 snapshots because it was so big; they are meant to join as one image._

I keep on trying to convert my .py file to a .exe (windows executable) and i can't because it's having those errors. **Please can you help?**

**Comment by keck-in-space** [comment] 2019-10-30 20:11
Duplicate of https://github.com/pyinstaller/pyinstaller/issues/4265?

**Comment by Lethiathan** [comment] 2019-10-31 10:59
oh, ok. closed it now.

**Closed** 2019-10-31 10:59 UTC
