### ISSUE TITLE
webbrowser fails in packaged exe

### ISSUE THREAD

**Issue by wyz23x2** [pyinstaller/pyinstaller#4835] opened 2020-04-24 16:16 UTC
#### Hi, I wrote a program that uses ``webbrowser.open()``. However, "Failed to execute" pops up. That doesn't seem right.
- Used ``-w -F``
- Confirmed that no errors occurred before
- ``webbrowser`` works right when running .py
- Default browser is Opera
- Python version: 3.8.2
- PyInstaller version: 3.6
- Platform: Windows 10 1909 64-bit

**Comment by Legorooj** [comment] 2020-04-25 00:04
Can you try with python 3.7? 3.8 doesn't work properly - in the rare event you get it to build properly.

**Comment by wyz23x2** [comment] 2020-04-25 01:56
Well, the .py uses features like `:=` and `def func(a, b, /)`, so it's hard to do that.

**Comment by Legorooj** [comment] 2020-04-25 02:01
@wyz23x2 Unfortunately PyInstalle doesn't yet officially support python 3.8 - without bugs. You'll need to wait a version or 2. 

Does the following fail (In 3.8)?
```
import webbrowser
webbrowser.open('https://github.com/pyinstaller/pyinstaller')
```

Also, try building without `-w`, and run the file from a command prompt. You'll be able to see the traceback.

**Comment by wyz23x2** [comment] 2020-04-25 03:44
I will test it. Quite busy now.

**Comment by wyz23x2** [comment] 2020-04-25 08:38
Tested. The output is empty; it simply pops up "Failed to execute script ...".

**Comment by wyz23x2** [comment] 2020-04-25 08:42
> 3.8 doesn't work properly - in the rare event you get it to build properly.  

So when does it support 3.8? 3.8.0 has been released over half a year.

**Comment by Legorooj** [comment] 2020-04-25 12:07
@wyz23x2 planned for the next release (or the one after. We need to replace about half the codebase first).

**Comment by Legorooj** [comment] 2020-04-27 11:36
@wyz23x2 I'm going to close this issue; we can't help until python 3.8 is supported. I suggest you set a custom watch status on #4311 so you get notified when the issue is closed - support has been added.

If the issue persists after that, open a new issue.

**Closed by Legorooj** 2020-04-27 11:36 UTC

**Comment by johnthagen** [comment] 2021-11-01 11:52
Related to #3668
