### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources.extern' if setuptools 70.0.0

### ISSUE THREAD

**Issue by Mansitos** [pyinstaller/pyinstaller#8638] opened 2024-07-02 12:39 UTC
## Description of the issue
I encountered the message `ModuleNotFoundError: No module named 'pkg_resources.extern'` while running an exe build for my usual application. The strange thing was that the application requirements and code were exactly the same as the last time I built the application; time the exe ran without any problems. The only difference was that the environment was created from scratch. I noticed that in the old environment setuptools was at 69.2.0; in the new one at 70.0.0. By downgrading setuptools to 69.2.0 the exe works correctly again.

**Comment by rokm** [comment] 2024-07-02 12:49
Duplicate of https://github.com/pyinstaller/pyinstaller/issues/8554. You should update your PyInstaller installation, or (if you are intentionally using older version) add the problematic module to hiddenimports.

**Closed as not planned by rokm** 2024-07-02 12:49 UTC
Labels: solution:duplicate
