### ISSUE TITLE
pyinstaller does not collect pulp path when running without forcing get pulp path with spec file at linux ubuntu 20.04

### ISSUE THREAD

**Issue by LBeghini** [pyinstaller/pyinstaller#6567] opened 2022-02-03 01:38 UTC
## Description of the issue
I tried to generate an Linux executable, using the same options I used for my Mac and Windows executables:
```bash
pyinstaller --collect-data pulp --onefile --clean --noconfirm --noconsole app.py
```
> Simplified version for objectivity 

However, when I ran and test the program, one of my features wouldn't work. So I decided to run at the terminal to see if I could catch any errors, and I found:
```bash
unexpected EOF while parsing (<unknown>, line 1)
'NoneType' object has no attribute 'actualSolve'
```

Which is somewhat related to issue #6359, I believe.

To test what the problem could be, I created a spec file with:
```bash
pyi-makespec --collect-data pulp --onefile --noconsole app.py
```

and added the following to the file:

```spec
def get_pulp_path():
    import pulp
    return pulp.__path__[0]

a.datas += Tree(get_pulp_path(), prefix='pulp', excludes=["*.pyc"])
```

after running with PyInstaller, it worked perfectly. 

I don't know if I'm doing something wrong when collecting the data from pulp, or there's another way to solve this.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1``` and ```4.8```
* Version of Python: 3.9.5
* Platform: Ubuntu 20.04
* How you installed Python: apt 
* Did you also try this on another platform? Does it work there?
Yes, it worked on Windows 10 and MacOS High Sierra

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
I don't know how to make a minimal example, since I don't understand exactly what's going on. I tried to package [this pulp example](https://projects.coin-or.org/PuLP/browser/trunk/examples/WhiskasModel1.py?format=txt) also at Ubuntu but it worked with no errors.

### Stacktrace / full error message
```bash
unexpected EOF while parsing (<unknown>, line 1)
'NoneType' object has no attribute 'actualSolve'
```

**Comment by rokm** [comment] 2022-02-03 11:26
> I don't know how to make a minimal example, since I don't understand exactly what's going on. I tried to package [this pulp example](https://projects.coin-or.org/PuLP/browser/trunk/examples/WhiskasModel1.py?format=txt) also at Ubuntu but it worked with no errors.

Hmm... assuming this is about ModuleGraph, can you provide step-by-step instructions to reproduce the problem in there? 

The basic pulp examples seem to work fine on my Fedora linux box as well, and so does entering `χ(ℓ(G))/2 ≤ floor(μ₁(G))+1-π^2` into frozen version of ModuleGraph (which used to be problematic on Windows and macOS in previous issues).

**Comment by LBeghini** [comment] 2022-02-03 23:24
Hello! We were able to reproduce a minimal example for testing purposes.
```py
from simpleeval import simple_eval
import numpy
import grinpy as gp
import networkx as nx

def valid_bool_simple_eval(expression):
    g = nx.path_graph(2)
    names = {"G": g, "g": g}
    type_ex = type(simple_eval(expression, functions={'\u03bd': MatchingNumber.calculate}, names=names))
    return type_ex == numpy.bool or type_ex == numpy.bool_ or type_ex == bool


class MatchingNumber:
    name = "Matching number"
    code = '\u03bd'
    type = "number_structural"

    @staticmethod
    def calculate(graph):
        return gp.matching_number(graph)

if __name__ == '__main__':
    print(valid_bool_simple_eval('\u03bd(G)>1'))
```
> We called the file `test_matching_number.py`

Running this code on Linux Ubuntu 20.04, with the command:
```bash
pyinstaller --collect-data pulp --onefile --clean --noconfirm test_matching_number.py
```

When executed, it throws the error:
```bash
AttributeError: 'NoneType' object has no attribute 'actualSolve'
[29770] Failed to execute script 'test_matching_number' due to unhandled exception!
```

However, on Windows 10, it executes perfectly.
> I'll assume it works for MacOS as well.

Also, as said before, creating an spec file with:
```bash
pyinstaller --collect-data pulp --onefile test_matching_number.py
```

And adding the following to the file:
```spec
def get_pulp_path():
    import pulp
    return pulp.__path__[0]

a.datas += Tree(get_pulp_path(), prefix='pulp', excludes=["*.pyc"])
```

Made it work.

And on windows, if I remove the `--collect-data pulp` option, running with:
```bash
pyinstaller --onefile --clean --noconfirm test_matching_number.py
```
I got the exact same error as Linux:
```bash
AttributeError: 'NoneType' object has no attribute 'actualSolve'
[9220] Failed to execute script 'test_matching_number' due to unhandled exception!

```

**Comment by rokm** [comment] 2022-02-04 21:32
Turns out that I could not reproduce the problem on my main linux box because it had `cbc` executable installed on the system, so PuLP fell back to that. In a clean Ubuntu 20.04 VM, it indeed fails to set up default solver again.

That said, this looks like exactly the same issue as you had on macOS, and is solved by adding `os.normpath()` call [here](https://github.com/coin-or/pulp/blob/7b551d9233dc1a67bdb894f096ca6a5d0cfc3e94/pulp/apis/core.py#L186). In fact, installing PuLP from their git master (`pip install git+https://github.com/coin-or/pulp.git`) instead of latest release (`2.6.0`) solves the problem here, because I see your PR to add the `os.normpath` was merged.

**Comment by LBeghini** [comment] 2022-02-04 22:43
Hm, you're right. I assumed the changes were already on the latest version. Getting PuLP from their master branch made it work. Thank you for the attention!

**Closed as completed** 2022-02-04 22:43 UTC
Labels: triage
