### ISSUE TITLE
_pyi_pkgutil_iter_modules.py, TypeError: startswith first arg must be str or a tuple of str, not PurePosixPath

### ISSUE THREAD

**Issue by niall-byrne** [pyinstaller/pyinstaller#6061] opened 2021-07-26 18:35 UTC
## Description of the issue

Error thrown during execution of compiled bundle.

### Context information (for bug reports)

* Output of `pyinstaller --version`:  4.4
* Version of Python: 3.8.10
* Platform:  OS X
* How you installed Python: 
* Did you also try this on another platform? Does it work there?

No.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Reverting to 4.3 solved the issue.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

I needed to fix my build, reverting to 4.3 worked for me.

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

Full traceback can be viewed here, as well as complete details of the build and build.spec (in associated repository):
https://github.com/osx-provisioner/mac_maker/runs/3164302890

Cut and Paste as Requested:

  File "importlib/__init__.py", line 127, in import_module
Error: 7-26 17:48:29,274] - [mac_maker] - [ERROR] - AnsibleProcess: Forked process reports error.
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ansible/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ansible/_vendor/__init__.py", line 46, in <module>
  File "ansible/_vendor/__init__.py", line 30, in _ensure_vendored_path_entry
  File "ansible/_vendor/__init__.py", line 30, in <genexpr>
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
TypeError: startswith first arg must be str or a tuple of str, not PurePosixPath

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment] 2021-07-26 18:38
Duplicate of #6018, fixed in `develop` by #6019.

**Closed by rokm** 2021-07-26 18:38 UTC
Labels: triage
