### ISSUE TITLE
Strange behaviour of __debug__ in frozen code

### ISSUE THREAD

**Issue by eric957** [pyinstaller/pyinstaller#3378] opened 2018-03-08 12:30 UTC
Hello,
It seems that \_\_debug__ is not set correctly for me, and that it behaves inconsistently. It is only when used as the condition of an "if" block that it is correct.
Here is a transcript which describes the problem. Not all command outputs are given obviously.

    $ lsb_release -d; lscpu |head -1
    Description:        Ubuntu 14.04.5 LTS
    Architecture:          x86_64
    $ $PYTHON/bin/python3 -m venv $VENV
    $ source $VENV/bin/activate
    $ pip install --upgrade pip
    $ pip install pyinstaller
    $ python --version
    Python 3.6.4
    $ pyinstaller --version
    3.3.1
    $ cat > test.py << EOF
    #!/usr/bin/env python3

    print ('debug is',__debug__)
    print ('debug is', 'True' if __debug__ else 'False')
    if __debug__:
        print ('debug is True')
    else:
        print ('debug is False')
    EOF
    $ unset PYTHONOPTIMIZE 
    $ python -O -m PyInstaller -y test.py # freeze in optimized mode
    $ python test.py  # normal debug mode
    debug is True
    debug is True
    debug is True
    $ python -O test.py # optimized mode
    debug is False
    debug is False
    debug is False
    $ ./dist/test/test  # should behave as with python -O
    debug is True
    debug is True
    debug is False

I compiled Python myself, so I double-checked using the version of Python3 which comes with the distribution (version 3.4.3), the result is the same.

**Comment by htgoebel** [comment] 2018-03-13 21:18
Duplicate of #3379

**Closed by htgoebel** 2018-03-13 21:18 UTC
