### ISSUE TITLE
PyInstaller Error: Crypto.Cipher._raw_ecb not CryptoDemo

### ISSUE THREAD

**Issue by wcraig2012** [pyinstaller/pyinstaller#3067] opened 2017-12-04 07:56 UTC
Has anyone solved the problem "OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'", but not the CryptoDemo problem when using web3.py package?
I am in a quite hurry.
Thanks a lot.

**Comment by htgoebel** [comment] 2017-12-04 11:23
Duplicate of #1983

**Comment by htgoebel** [comment] 2017-12-04 11:24
This is a bug tracker, not a forum!

**Closed by htgoebel** 2017-12-04 11:23 UTC
