### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas._libs.tslibs.timedeltas'

### ISSUE THREAD

**Issue by dat8866** [pyinstaller/pyinstaller#3063] opened 2017-12-02 11:19 UTC
I'm a learner of python. and There is a problem on executing my script It shows "failed to execute script" while packing by pyinstaller due to ModuleNotFoundError: No module named 'pandas._libs.tslibs.timedeltas'.

How can I solve it?Appreciate for your help.
![pandas](https://user-images.githubusercontent.com/34075957/33514852-a6107244-d795-11e7-8ffe-bc699da7c3f4.jpg)

Ps.python 3.6/pyinstaller 3.4/Win 10

**Comment by htgoebel** [comment] 2017-12-02 11:42
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

Also do not post images, but text. Thanks.

**Comment by htgoebel** [comment] 2018-03-13 21:03
Duplicate of #2978

**Closed by htgoebel** 2018-03-13 21:03 UTC
Labels: support
