### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by Note-Liu** [pyinstaller/pyinstaller#6372] opened 2021-11-17 08:41 UTC
I used pyinstaller package labelme，and i have already installed opencv.
After packaged，when i execute it , i got the error：
ModuleNotFoundError: No module named 'cv2'
How to solve it ?

**Comment by sopheset111** [comment] 2021-11-17 08:49
You need to specify the path to the module CV2 with --paths, for example my path to cv2 is as follows --paths="C:\Users\User\AppData\Roaming\Python\Python310\site-packages\cv2"

**Comment by rokm** [comment] 2021-11-17 09:17
Duplicate of pyinstaller/pyinstaller-hooks-contrib#110. Since opencv-python 4.5.3.58, this applies also to wheels (and not only to built-from-source variant). So one work-around is to specify path to the extension (as mentioned above), and the other is to downgrade to 4.5.3.56.

**Closed as completed by rokm** 2021-11-17 09:17 UTC
Labels: solution:duplicate

**Comment by utsavDave97** [comment] 2021-11-17 19:42
Still same error.

command:

```
pyinstaller --onefile main.spec --paths="/Users/udave/Desktop/ocr_python/venv/lib/python3.9/site-packages/cv2" 
```

**Comment by bwoodsend** [comment] 2021-11-17 22:11
Well you're mixing up virtual environments or Python installations. Activate that venv then use `python -m PyInstaller main.spec`.

**Comment by rokm** [comment] 2021-11-17 22:17
Actually, `--paths` has no effect when you're building from .spec file. It affects only generation of .spec file when you run PyInstaller against .py script.

**Comment by bwoodsend** [comment] 2021-11-17 22:29
Same with `--onefile`.

**Comment by utsavDave97** [comment] 2021-11-17 22:57
> Well you're mixing up virtual environments or Python installations. Activate that venv then use `python -m PyInstaller main.spec`.

Activated the ```venv``` via following command:
```
source venv/bin/activate
```
Ran the following command:
```
python -m PyInstaller main.spec
```
Above command started with the following incase if you want to see my versions:
```
181 INFO: PyInstaller: 4.7
181 INFO: Python: 3.9.7
206 INFO: Platform: macOS-12.0.1-x86_64-i386-64bit
213 INFO: UPX is not available.
214 INFO: Extending PYTHONPATH with paths
['/Users/udave/Desktop/ocr_python']
```

Got the following error:

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "cv2/__init__.py", line 180, in <module>
  File "cv2/__init__.py", line 110, in bootstrap
  File "cv2/__init__.py", line 108, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
[13944] Failed to execute script 'main' due to unhandled exception!

Saving session...completed.
```

Also my ```hiddenimports``` contain the following:

```
hiddenimports=['tkinter','Pillow','boto3','requests','opencv-python','imutils'],
```

Also inside my ```venv/lib/python3.9/``` I have following for ```opencv```:

1. opencv_python_headless-4.5.4.58.dist-info
2. opencv_python-4.5.1.48.dist-info


Still no luck. Appreciate your prompt responses @bwoodsend @rokm

**Comment by bwoodsend** [comment] 2021-11-18 09:10
And what do you get if you run: 
```
source venv/bin/activate
python -c 'import cv2'
```

**Comment by utsavDave97** [comment] 2021-11-18 12:41
I get the following @bwoodsend 

```
(venv) MacBook-Pro :: ~/Desktop/ocr_python ‹master*› % python -c 'import cv2'                                                   
(venv) MacBook-Pro :: ~/Desktop/ocr_python ‹master*› %   
```

So, basically it did stop for 5-6 seconds and that was it

**Comment by rokm** [comment] 2021-11-18 12:52
Like I said, adding `--paths` to `PyInstaller` command has no effect when building from .spec. So you either need to regenerate the .spec by calling PyInstaller against your entry-point script and adding `--paths` argument, or edit your spec file and add the path to `pathex` argument of the `Analysis`. Or, downgrade opencv to the version that's known to still work with PyInstaller.

**Comment by Note-Liu** [comment] 2021-11-18 14:36
One more thing i want ask,
How do I load these warning files：

26258 WARNING: Cannot find libc10.so (needed by /opt/conda/lib/python3.6/site-packages/torchvision/_C.so)
26258 WARNING: Cannot find libtorch.so (needed by /opt/conda/lib/python3.6/site-packages/torchvision/_C.so)
26258 WARNING: Cannot find libtorch_cpu.so (needed by /opt/conda/lib/python3.6/site-packages/torchvision/_C.so)
26258 WARNING: Cannot find libtorch_python.so (needed by /opt/conda/lib/python3.6/site-packages/torchvision/_C.so)
26258 WARNING: Cannot find libc10_cuda.so (needed by /opt/conda/lib/python3.6/site-packages/torchvision/_C.so)
26258 WARNING: Cannot find libtorch_cuda.so (needed by /opt/conda/lib/python3.6/site-packages/torchvision/_C.so)
26965 WARNING: Cannot find libicudata.so.56 (needed by /opt/conda/lib/python3.6/site-packages/PyQt5/Qt5/plugins/imageformats/../../lib/libicuuc.so.56)
27081 WARNING: Cannot find libicuuc.so.56 (needed by /opt/conda/lib/python3.6/site-packages/PyQt5/Qt5/plugins/imageformats/../../lib/libicui18n.so.56)


like the first one:
26258 WARNING: Cannot find libc10.so (needed by /opt/conda/lib/python3.6/site-packages/torchvision/_C.so)

when i exec "find":
root@yolo:/yolov5//labelme# find  /  -name  libc10.so
/opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so

what should i do?
Thanks!

**Comment by rokm** [comment] 2021-11-18 15:37
@Note-Liu Do you see those files (e.g., `libc10.so`) collected in the application bundle? If they end up being collected despite the warnings and the application works, then ignore those warnings...

**Comment by Note-Liu** [comment] 2021-11-19 00:30
> @Note-Liu Do you see those files (e.g., `libc10.so`) collected in the application bundle? If they end up being collected despite the warnings and the application works, then ignore those warnings...

Got it! Thanks for your reply!

**Comment by utsavDave97** [comment] 2021-11-19 16:51
Alright so it is working now.

Thank you @rokm @bwoodsend . Really appreciate it.

Just some few questions:

1. How do I specify in ```.spec``` file to generate ```onefile``` output?
2. Inside ```.spec``` file what does ```target_arch``` does? Because I am trying to create a ```.exe``` file in Linux Ubuntu 20.04.3 and I do get files inside ```dist``` folder but not able to double click it and open the python GUI program.

**Comment by rokm** [comment] 2021-11-19 18:58
> 1. How do I specify in `.spec` file to generate onefile output?

This is determined by the contents of the .spec file, i.e., the options passed to the `EXE` object and presence/absence of `COLLECT` object. So in short, you do not simply switch between the two, but rather generate one or the other variant when you run pyinstaller against the source file. Or, you can generate both variants, manually merge them, and use an environment variable as a switch, as is done by some of our tests (see [here](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/specs/pyi_osx_aevent_handling_carbon.spec) for an example).

> 2. Inside .spec file what does `target_arch` does?

That's a macOS-specific option, and is documented [here](https://pyinstaller.readthedocs.io/en/stable/feature-notes.html?highlight=target_arch#macos-multi-arch-support).

> Because I am trying to create a `.exe` file in Linux Ubuntu 20.04.3 and I do get files inside dist folder but not able to double click it and open the python GUI program.

Sounds like you may want to read about PIE executables and their implications w.r.t. opening the programs by double clicking them in linux GUI... (spoiler: it doesn't work in most DEs, so if you require that functionality, you'll need to rebuild the PyInstaller bootloaders as non-PIE executables. Do a search on our issue tracker, it's been asked before).
