### ISSUE TITLE
TypeError: startswith first arg must be str or a tuple of str, not PurePosixPath

### ISSUE THREAD

**Issue by pankaj88gravity** [pyinstaller/pyinstaller#6047] opened 2021-07-21 20:55 UTC
```
import ocrmypdf
import sys
input_file = sys.argv[1]
output_file = sys.argv[2]
ocrmypdf.ocr(input_file, output_file, deskew=True)

```
I created an executable using "pyinstaller" but it's giving below error->

Traceback (most recent call last):
  File "converttotext.py", line 7, in <module>
    ocrmypdf.ocr(input_file, output_file, deskew=True)
  File "ocrmypdf/api.py", line 332, in ocr
  File "ocrmypdf/_plugin_manager.py", line 107, in get_plugin_manager
  File "ocrmypdf/_plugin_manager.py", line 45, in __init__
  File "ocrmypdf/_plugin_manager.py", line 70, in setup_plugins
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
TypeError: startswith first arg must be str or a tuple of str, not PurePosixPath
[23499] Failed to execute script 'converttotext' due to unhandled exception!

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.4```
* Version of Python: 3.6.9
* Platform: Ubuntu 18 64 bit
* How you installed Python: apt
* Did you also try this on another platform? Does it work there?  Didn't try anywhere else.

**Comment by rokm** [comment] 2021-07-21 21:08
Duplicate of #6018, fixed in `develop` by #6019.

**Closed by rokm** 2021-07-21 21:08 UTC
Labels: triage

**Comment by pankaj88gravity** [comment] 2021-07-21 21:24
pip install
https://github.com/rokm/pyinstaller/archive/refs/heads/fix-6018.zip

Collecting
https://github.com/rokm/pyinstaller/archive/refs/heads/fix-6018.zip
  ERROR: HTTP error 404 while getting
https://github.com/rokm/pyinstaller/archive/refs/heads/fix-6018.zip
ERROR: Could not install requirement
https://github.com/rokm/pyinstaller/archive/refs/heads/fix-6018.zip because
of HTTP error 404 Client Error: Not Found for url:
https://codeload.github.com/rokm/pyinstaller/zip/refs/heads/fix-6018 for
URL https://github.com/rokm/pyinstaller/archive/refs/heads/fix-6018.zip

**Comment by rokm** [comment] 2021-07-21 21:26
Yeah, that branch was deleted after the merge. You need to install `develop` branch:
```
pip install https://github.com/pyinstaller/pyinstaller/archive/refs/heads/develop.zip
```

**Comment by pankaj88gravity** [comment] 2021-07-21 21:37
Traceback (most recent call last):
  File "converttotext.py", line 7, in <module>
    ocrmypdf.ocr(input_file, output_file, deskew=True)
  File "ocrmypdf/api.py", line 339, in ocr
  File "ocrmypdf/_validation.py", line 271, in check_options
AttributeError: 'NoneType' object has no attribute 'languages'
[10767] Failed to execute script 'converttotext' due to unhandled exception!

**Comment by rokm** [comment] 2021-07-21 21:50
Try adding `--collect-submodules ocrmypdf --collect-data ocrmypdf` to your PyInstaller command.

**Comment by pankaj88gravity** [comment] 2021-07-22 09:57
It works!!

But when I ran the executable in a Laravel web app using Symfony process below error was seen in the console->

```
The program 'tesseract' could not be executed or was not found on your
system PATH.

[11805] Failed to execute script 'converttotext' due to unhandled exception!
Traceback (most recent call last):
  File "ocrmypdf/subprocess/__init__.py", line 296, in check_external_program
  File "ocrmypdf/_exec/tesseract.py", line 80, in version
  File "ocrmypdf/subprocess/__init__.py", line 168, in get_version
ocrmypdf.exceptions.MissingDependencyError: The program 'tesseract' did not report its version. Message was:
tesseract: /opt/lampp/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/liblept.so.5)
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.37 : libtiff 4.0.1 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
```

**Comment by rokm** [comment] 2021-07-22 11:12
What if you remove `libtiff.so.5` from your frozen application bundle? You probably did not bundle `tesseract` itself and are using system-installed version, but some of the libraries it is linked against (`libtiff`) were collected and are now causing conflict. (Or ideally, freeze on the same kind of distribution and version as your target one - then you'll have no such conflicts).

Although tesseract does seem to still work and report the version, and it is `ocrmypdf` that doesn't handle that extra warning message...

**Comment by pankaj88gravity** [comment] 2021-07-22 11:40
I used below command to create executable->
    pyinstaller converttotext.py --collect-submodules ocrmypdf
--collect-data ocrmypdf --onefile

How to bundle tesseract ?

**Comment by pankaj88gravity** [comment] 2021-07-22 11:48
> What if you remove `libtiff.so.5` from your frozen application bundle? You probably did not bundle `tesseract` itself and are using system-installed version, but some of the libraries it is linked against (`libtiff`) were collected and are now causing conflict. (Or ideally, freeze on the same kind of distribution and version as your target one - then you'll have no such conflicts).
> 
> Although tesseract does seem to still work and report the version, and it is `ocrmypdf` that doesn't handle that extra warning message...

I have updated the error message above. May be it will give more clear picture.

**Comment by rokm** [comment] 2021-07-22 11:49
> How to bundle tesseract ?

Use [--add-binaries](https://pyinstaller.readthedocs.io/en/latest/usage.html?highlight=add-data#cmdoption-add-binary) to collect system executable into your application bundle. You'll probably need to tell `ocrmypdf` to use the collected executable, too. And you might need to collect tesseract's data files using [--add-data](https://pyinstaller.readthedocs.io/en/latest/usage.html?highlight=add-data#cmdoption-add-data).

But this is beyond the scope of this issue tracker, and you might be better off using the system copy (provided you sort out conflicting shared library versions).

**Comment by rokm** [comment] 2021-07-22 11:49
> I have updated the error message above. May be it will give more clear picture.

My answer is still the same.

**Comment by pankaj88gravity** [comment] 2021-07-24 09:49
> What if you remove `libtiff.so.5` from your frozen application bundle? You probably did not bundle `tesseract` itself and are using system-installed version, but some of the libraries it is linked against (`libtiff`) were collected and are now causing conflict. (Or ideally, freeze on the same kind of distribution and version as your target one - then you'll have no such conflicts).
> 
> Although tesseract does seem to still work and report the version, and it is `ocrmypdf` that doesn't handle that extra warning message...

I have not added `libtiff.so.5` in the bundle. It may have been added by "pyinstaller".

How to remove it ?

**Comment by rokm** [comment] 2021-07-24 10:40
> I have not added libtiff.so.5 in the bundle. It may have been added by "pyinstaller".

Yes, that's what PyInstaller does based on dependecny analysis... (and it has no way of knowing that you'll be running your bundle on a different system where that might be an issue).

> How to remove it ?

`rm -f dist/<name>/libtiff.so.5`

Unless you're trying to make `onefile` bundle, in which case, you'll need to work with the .spec file and remove the corresponding entry from `a.binaries`. Or you could try removing `os.path.join(sys._MEIPASS, 'libtiff.so.5')` in your python program before importing `ocrmypdf`.
