### ISSUE TITLE
Symlinks and sys.argv[0]

### ISSUE THREAD

**Issue by prologic** [pyinstaller/pyinstaller#1208] opened 2015-03-12 08:20 UTC
If I package up a single file app ``pyinstaller -s -F bin/foo``

and have the following symlinked:

```
foo
bar -> foo
```

I don't seem to find a way to determine whther
the app was run from the symlinked ``bar`` at all.

``sys.argv[0]`` seems to always point to the real page.

Any ideas? I sthis a bug?

**Comment by htgoebel** [comment] 2015-03-17 11:27
Huh, I just discovered that my comment is missing :-( (Or has this be discussed on the mailing-list?

This is caused by Py_SetProgramName(), see https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/common/pyi_pythonlib.c#L216 and https://docs.python.org/3.4/c-api/init.html#c.Py_SetProgramName.

**Comment by prologic** [comment] 2015-03-17 11:50
We *should* fix this as it makes the use-case of symlinking multiple entrypoints to a single binary useless and unworkable.

**Comment by htgoebel** [comment] 2015-03-17 12:30
Of course we should fix this. The question for me is: What is the best way to fix it.

**Comment by prologic** [comment] 2015-03-17 12:33
Shouldn't set ``Py_SetProgramName()`` be called with the value of the first
argument in ``argv[]`` here? Which I assume for symlinked binaries is the
symlink? I'd have to test this theory with a simple C program but I'm
almost certain that's how busybox works :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by htgoebel** [comment] 2015-05-26 14:36
I did an analysis on this:

The root cause for this is: On Linux (and only on Linux) we are getting the executables name from `/proc/self/cmdline` (resp. using the pid, but this does not matter). This already has the (resolved, absolute) path to the executable. Any symbolic link is lost here.

On other platforms:
**win32**: Uses `GetModuleFileNameW`. [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683197%28v=vs.85%29.aspx) do not state whether symbolic links will be resolved
**OS X**: uses `_NSGetExecutablePath()` where the [dyld docs](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dyld.3.html) say: "Note that  _NSGetExecutablePath() will return "a path" to executable not a "real path" to the executable. That is, **the path may be a symbolic link** and not the real file." (emphasis by me)

**Possible solutions**

1. idea from http://www.lemoda.net/c/exe-path/: use [program_invocation_name](http://linux.die.net/man/3/program_invocation_name), which is the same as `argv[0]`. This has to be `absnormpath`ed, though, which is not implemented at the moment. Drawback: this is glibc-specific.

2. idea: use  `argv[0]`, which is passed to `pyi_path_executable` as parameter `appname` (which is currently unused).

Note1 : Using `/proc/[pid]/comm` is o no help, since it only contains the basename of the executable.

Note 2: http://www.lemoda.net/c/exe-path/ has information for other platforms, too. But  the second idea from above is generic anyway.

**Comment by htgoebel** [comment] 2015-05-26 18:18
@prologic This issue is on the python3-branch, isn't it?

**Comment by codewarrior0** [comment] 2015-08-25 02:20
I don't think this issue is on the python 3 branch, and I don't think it's related to SetProgramName either. [On the develop branch,](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/common/pyi_pythonlib.c#L236) `argv[0]` is explicitly modified and replaced with archivename. On the python3 branch, `argv` is passed to python without modification.

SetProgramName only changes `sys.executable` and `sys.path`, and we override `sys.path` anyway. [The documentation](https://docs.python.org/3.4/c-api/init.html#c.Py_SetProgramName) is a bit confusing. It says, 

>It tells the interpreter the value of the argv[0] argument to the main() function of the program (converted to wide characters)

This means it just informs the interpreter of what `argv[0]` was when the program started up so it can use that name to find the default search path. It doesn't mean that it changes the value of `sys.argv` - indeed, SetProgramName has no effect on `sys.argv` at all. 

--

I think this issue is already fixed on `python3` branch. But it helped to expose another problem: We don't have a reliable way of getting the full path to the exe (see #1436). We need to expand `pyi_path_executable` to use different methods for getting the full path (as listed on StackOverflow):

- readlink("/proc/self/exe", buf, bufsize) (Linux)
- readlink("/proc/curproc/file", buf, bufsize) (FreeBSD)
- readlink("/proc/self/path/a.out", buf, bufsize) (Solaris)

On Unixes without /proc (i.e. if above fails):
- If argv[0] starts with "/" (absolute path) this is the path.
- Otherwise if argv[0] contains "/" (relative path) append it to cwd (assuming it hasn't been changed yet).
- Otherwise search directories in $PATH for executable argv[0].

**Comment by codewarrior0** [comment] 2015-08-25 05:52
For the record, I think `sys.argv[0]` should be the name of the program as it was invoked. That is, it should be usable for the symlink purpose in this issue. So giving the unmodified argv to PySys_SetArgv is correct. 

On the other hand, `sys.executable` should be the real, absolute path to the program wherever it was installed. This will make it usable for the use-case in #1282

**Comment by htgoebel** [comment] 2015-08-25 19:09
@codewarrior0: I support  your latest proposal (https://github.com/pyinstaller/pyinstaller/issues/1208#issuecomment-134488847). This seam to be easier then what's been my idea: determine the path of the executable and the replace the basename by the basename of `argv[0]`.
Could you please take care of implementing this? Thanks!

**Comment by codewarrior0** [comment] 2015-08-26 04:40
>Could you please take care of implementing this? Thanks!

Done! d2e749f0d1fede80828c29837940a9269f596ebb 

Also added a test, `test_run_from_path_environ`: c0836464767c2a8cc2443d8b2e9a564e4b0fd6b5

Closing as this was already not an issue on `python3` branch, but another test for a symlinked exe would help confirm that.

**Closed by codewarrior0** 2015-08-26 04:40 UTC
Labels: @low, Linux
