### ISSUE TITLE
Executable throwing 14001

### ISSUE THREAD

**Issue by redraven984** [pyinstaller/pyinstaller#1673] opened 2015-11-13 16:57 UTC
So pyinstaller creates an executable but when you click on the executable it has the following error:

Error loading Python DLL: C:\User\....\appData\Local\Temp\_MEI74442\python27.dll

Looks like its creating a temporary folder with python.dll in it, but for some reason it cannot load it. Has anyone seen this before?

**Comment by tallforasmurf** [comment] 2015-11-13 18:11
Creating a temp folder is what the one-file program is supposed to do (http://pythonhosted.org/PyInstaller/#how-the-one-file-program-works). Obviously python27.dll should be included, but does it exist? See https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong for troubleshooting hints.

**Comment by redraven984** [comment] 2015-11-13 19:15
I just checked. Yes, python27.dll exists. The directory itself only exists for a few seconds and is deleted when the program crashes.

**Comment by redraven984** [comment] 2015-11-13 19:35
Thanks for your pointer. I cleared the pyinstaller temporary folder and I found that the root cause was actually that Tkinter is not included in the imports during compile. Im a little bit confused as to why this may be. Its called in my imports at the top of the script.

**Comment by tallforasmurf** [comment] 2015-11-13 20:17
Interesting. If you explicitly import it in your own code, it should be bundled. Check your warnings text file to see if it wasn't found. n.b. its name is "tkinter" in Python 2.7, "Tkinter" in Python 3.x.

**Comment by redraven984** [comment] 2015-11-13 20:47
Thats the interesting part. This is actually a GUI that uses Tkinter so its called right at the top:
import Tkinter as Tk and it runs inside Pycharm. 

The actual runtime error I am getting now is: ImportError: No module named FixTk

If I look at the warning file I get: 
"missing module named tkinter - imported by IPython.lib.clipboard, IPython.lib.inputhook, IPython.kernel.zmq.eventloops, PIL.ImageTk
missing module named tkinter.Tk - imported by tkinter, IPython.lib.clipboard, IPython.lib.inputhook, IPython.kernel.zmq.eventloops
missing module named tkinter.TclError - imported by tkinter, IPython.lib.clipboard"

Now I'm already doing a hidden-import for FileDialog, what is the syntax for multiple hidden imports? I could try this.

**Comment by tallforasmurf** [comment] 2015-11-13 21:20
You can write --hidden-import= more than once. Or modify the spec file.

**Comment by redraven984** [comment] 2015-11-16 17:56
I tried adding 2 hidden imports. While pyinstaller is compiling the executable I get the following error messages:

51859 INFO: Excluding import 'FixTk'
51865 WARNING:   Removing import 'FixTk
51865 INFO: Excluding import 'Tkinter'
51865 INFO: Excluding import 'PyQt5'
51867 INFO: Excluding import 'PySide'
51868 INFO: Excluding import 'PyQt4'

But FixTk and Tkinter actually exist in C:\Anaconda\Lib\lib-tk. Im sure I could find the other exclusions as well. 

Any ideas on what I could do?

**Comment by matysek** [comment] 2015-11-26 20:28
@redraven984 Please provide any simple code example that reproduces your issue.

**Comment by redraven984** [comment] 2015-12-01 20:56
So I wanted to create a simple script to show you the problem. I copied and pasted a very simple entry box from the web and it compiled just fine. 

My conclusion is that it must be something about the various packages I am loading thats causing the issue. Im not sure how to troubleshoot right now.

**Comment by redraven984** [comment] 2015-12-01 21:26
So I worked with the problem for some time again. I concluded that the issue is that one of the libraries I am importing is causing pyinstaller not to find Tkinter,FixTk,PyQt5,PySide,PyQt4. This seems to be a common problem because googling yields multiple hits on people posting about this problem.

Anyway, I commented out each library I am importing at the top of my script and then ran pyinstaller to see if the hooks would be excluded. In doing this I realized that the following 2 libraries are causing the issue:
Matplotlib and Seaborn

If the import statement includes these libraries that I find the error above the executable that generates graphics crashes. here is a sample script for you to run and try (you can replace seaborn with matplotlib and get the same effect):

import Tkinter as tk
import seaborn as sns

class SampleApp(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.entry = tk.Entry(self)
        self.button = tk.Button(self, text="Get", command=self.on_button)
        self.button.pack()
        self.entry.pack()

    def on_button(self):
        print(self.entry.get())

app = SampleApp()
app.mainloop()

Please let me know if you have any ideas on how to correct this.

**Comment by tallforasmurf** [comment] 2015-12-01 21:29
The hook for the PIL module explicitly excludes FixTk (https://github.com/pyinstaller/pyinstaller/blob/dd1c17e7874e7b066d44b9fe4eaca80cb1baf96f/PyInstaller/hooks/hook-PIL.py). I see PIL mentioned in the sixth comment down in this thread. Is that something you import? Or is it indirect through iPython? Anyway try adding it to your minimal test case.

**Comment by redraven984** [comment] 2015-12-01 21:37
PIL is not explicitly used. Also, I am using an IDE not ipython. Anyway, I added the PIL import:

import Tkinter as tk
import seaborn as sns
import PIL

class SampleApp(tk.Tk):
def init(self):
tk.Tk.init(self)
self.entry = tk.Entry(self)
self.button = tk.Button(self, text="Get", command=self.on_button)
self.button.pack()
self.entry.pack()

def on_button(self):
    print(self.entry.get())

app = SampleApp()
app.mainloop()

Same problem. The console output says FixTk not found and crashes.

**Comment by redraven984** [comment] 2015-12-01 21:43
Also pasted the fix from your link into my toy file and it did not help.

**Comment by tallforasmurf** [comment] 2015-12-02 16:10
> the following 2 libraries are causing the issue: Matplotlib and Seaborn
Good work diagnosing! Now, all hooks are off the hook (so to speak) for this problem. There is no seaborn hook and the matplotlib hook only adds some datas, it doesn't exclude or require any imports. I will try poking around in one of them but don't let that keep anyone else from looking, too!

**Comment by redraven984** [comment] 2015-12-02 16:33
Thanks! Let me know if I can do some other diagnostics too.

**Comment by tallforasmurf** [comment] 2015-12-02 19:30
OK I'm exploring this on Mac OS X. Your example program does execute there without error. However I note the following things.

1. seaborn relies on matplotlib. Since you report the problem with either, seaborn can be ignored.

2. matplotlib imports PIL and this is shown in the PyInstaller output.

3. PIL apparently has a complex import scheme because it generates all the following messages:

    15193 INFO: Processing hook   hook-PIL.py
    15199 INFO: Excluding import 'tkinter'
    15202 INFO: Import to be excluded not found: 'FixTk'
    15202 INFO: Excluding import 'PySide'
    15204 WARNING:   From PIL.ImageQt removing import PySide
    15204 WARNING:   From PIL.ImageQt removing import PySide.QImage
    15204 WARNING:   From PIL.ImageQt removing import PySide.qRgba
    15204 WARNING:   From PIL.ImageQt removing import PySide.QPixmap
    15205 INFO: Excluding import 'PyQt5'
    15207 WARNING:   From PIL.ImageQt removing import PyQt5.QtCore
    15207 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui.QImage
    15207 WARNING:   From PIL.ImageQt removing import PyQt5.QtCore.QIODevice
    15207 WARNING:   From PIL.ImageQt removing import PyQt5.QtCore.QBuffer
    15207 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui
    15208 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui.qRgba
    15208 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui.QPixmap
    15208 INFO: Excluding import 'PyQt4'
    15210 WARNING:   From PIL.ImageQt removing import PyQt4
    15210 WARNING:   From PIL.ImageQt removing import PyQt4.QImage
    15210 WARNING:   From PIL.ImageQt removing import PyQt4.qRgba
    15210 WARNING:   From PIL.ImageQt removing import PyQt4.QPixmap
    15211 INFO: Processing hook   hook-PyQt5.Qt.py
    15212 INFO: Processing hook   hook-PyQt5.QtWidgets.py
    15212 INFO: Processing hook   hook-distutils.py
    15213 INFO: Processing hook   hook-PIL.Image.py
    15394 INFO: Processing hook   hook-PIL.SpiderImagePlugin.py
    15405 INFO: Excluding import 'tkinter'
    15407 INFO: Import to be excluded not found: 'FixTk'

This complexity and the multiple attempts to exclude FixTk make me very suspicious this is the root of your problem. It looks bad to me that PyQt4 and PyQt5 are first excluded and then later the PyQt5 hook runs. Anyway, I speculate that if you replace `import matplotlib` with `import PIL` in your minimal example you will get a failure. If so, that will simplify things.

**Comment by redraven984** [comment] 2015-12-02 23:21
Interesting. Well in my example i already imported pil and it did cause a failure. How does this help?

**Comment by tallforasmurf** [comment] 2015-12-02 23:52
We can forget about the complexities of the giant modules matplotlib and seaborn. It's down to just an interaction between tkinter and PIL -- and the specifics of your installation. Python 2.7 on Windows what nn-bit? Installed Python how (e.g. via Anaconda or python.org standard install?)

**Comment by redraven984** [comment] 2015-12-03 00:34
Its windows 8.1 64 bit but anaconda 2.7 32 bit. Its the latest 32 bit anaconda. I actually switched from 64 bit anaconda to try to alleviate the problem.

**Comment by redraven984** [comment] 2015-12-03 15:12
Nat, another idea that comes to mind is the system paths. Is there something specific i should have in my pythonpath or system path?

**Comment by tallforasmurf** [comment] 2015-12-03 23:04
If the paths are correct at build time, so that everything imported is found, that's all you need. The pythonpath and sys.path at execution time are set up by the bootloader code to the locations only of the bundled stuff. (Otherwise it would be dependent on the local environment.)

I have set up a Win7 64-bit system with Python 2.7 and PIL and the dev version of PyInstaller. I bundled your minimal example both --onefile and --onedir and it runs, no problem. For reference, the example program is:

        import tkinter as tk
        import PIL
        class SampleApp(tk.Tk):
                def init(self):
                        #tk.Tk.init(self)
                        super().__init__()
                        self.entry = tk.Entry(self)
                        self.button = tk.Button(self, text="Get", command=self.on_button)
                        self.button.pack()
                        self.entry.pack()
                def on_button(self):
                        print(self.entry.get())
        app = SampleApp()
        app.mainloop()

The big difference from your setup would be: I used python.org's installer not Anaconda. And there is no PyQt4 or 5 installed. The key lines of the build read,

    375 INFO: Analyzing C:\Users\Administrator\Documents\PYIW
    1264 INFO: Looking for import hooks ...
    1264 INFO: Processing hook   hook-PIL.py
    1264 INFO: Excluding import 'FixTk'
    1264 INFO: Excluding import 'Tkinter'
    1264 INFO: Import to be excluded not found: 'PyQt5'
    1264 INFO: Import to be excluded not found: 'PySide'
    1264 INFO: Import to be excluded not found: 'PyQt4'
    1264 INFO: Processing hook   hook-encodings.py
    1529 INFO: Processing hook   hook-_tkinter.py

So at this point I am stuck. Hopefully one of the "real" developers can take a look.

**Comment by redraven984** [comment] 2015-12-04 02:05
Hmm thats interesting. Its excluding tkinter but it runs. Let me give it a try again in the morning. Its been crashing the console window lately and i havent caught the current error.

When you say the important stuff in the path/pythonpath, what do you mean?

**Comment by redraven984** [comment] 2015-12-04 19:08
I just ran the test case you posted. I captured the output and here it is:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\laftch~1\appdata\local\temp\pip-build-xdd4f5\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 363, in load_
module
  File "c:\anaconda2\lib\lib-tk\Tkinter.py", line 38, in <module>
    import FixTk
ImportError: No module named FixTk
Pyinstaller_problem returned -1

Here is the interesting part of this, if I import FixTk in PyCharm or in iPython it loads just fine. Furthermore, FixTk is in the same exact directory as Tkinter.py.

**Comment by htgoebel** [comment] 2016-02-12 20:12
@redraven984 Any news on this? Did you solve the problem? Did you try with PyInstaller 3.1.1?

**Comment by htgoebel** [comment] 2016-02-28 11:09
Closing this, since there are now news for nearly three months now.

**Closed by htgoebel** 2016-02-28 11:09 UTC
Labels: need info, PY2, support, Windows
