### ISSUE TITLE
Problem with decoding

### ISSUE THREAD

**Issue by Urrova** [pyinstaller/pyinstaller#3960] opened 2019-01-03 00:04 UTC
# Hello pyinstaller
I used this program in py project MixCryptor, and i have 2 problems
* Encoding problems (show an error when it load a "ñ") and in the original script dont do it.
* i compiled it with --noconsole, because it have a GUI. When i zip and unzip this program, the AntiVirus detect this like a "Trojan:Script/Cloxer.D!cl"
Why this happens?

**Comment by htgoebel** [comment] 2019-01-03 21:23
Re 1: Please try the most recent development head. Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

Re 2. : Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by htgoebel** [comment] 2019-01-30 12:43
No more information since a month. closing.

**Closed by htgoebel** 2019-01-30 12:43 UTC
Labels: need info, support
