### ISSUE TITLE
Pyinstaller is not installed.

### ISSUE THREAD

**Issue by Chang-Hee-Kim** [pyinstaller/pyinstaller#2044] opened 2016-06-13 04:08 UTC
I am trying to install pyinstaller on Windows 7 and Python 3.5.1. 
I already ran "python -m pip install --upgrade pip". but pyinstaller is not installed.
I don't know what is the problem.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

C:\Windows\system32>pip install pyinstaller
Collecting pyinstaller
  Using cached PyInstaller-3.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n35\lib\site-packages\setuptools-23.0.0-py3.5.egg (from pyinstaller)
Collecting pefile (from pyinstaller)
  Using cached pefile-2016.3.28.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\BERNAR~1\AppData\Local\Temp\pip-build-j25n96b3\pefile\setup
.py", line 57, in <module>
        pefile_version = _read_attr('__version__')
      File "C:\Users\BERNAR~1\AppData\Local\Temp\pip-build-j25n96b3\pefile\setup
.py", line 39, in _read_attr
        match = re.search(regex, f.read())
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 208687:
 illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\BERNAR~1
\AppData\Local\Temp\pip-build-j25n96b3\pefile\
```

**Comment by stephenrauch** [comment] 2016-06-13 11:32
The wiki has a [nice page on how to report bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) so that the devs have the best chance of helping you. Having said that, this appears to be a duplicate of #2019.  A workaround has been merged with #2025 and is on the development tip. From the wiki:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Please try latest development version and let us know if the bug is already fixed there. Simply use_

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   _to install the latest git version._

That may get you going.  Please report back...

**Comment by htgoebel** [comment] 2016-06-30 12:35
@stephenrauch Thanks for spotting this as duplicate :-)

**Closed by htgoebel** 2016-06-30 12:35 UTC
Labels: need info

**Comment by leewc6734** [comment] 2016-07-01 06:39
Yes, develop version can pass this error, and work well, thanks

**Comment by ParkJooIl** [comment] 2016-07-05 07:37
Yes , i have a same issue.
we can pass this error , thanks
my python info :
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
