### ISSUE TITLE
Pyinstaller 3.4 RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by yogevNisim** [pyinstaller/pyinstaller#3752] opened 2018-09-20 08:26 UTC
Hi, 

I'm using the latest version (the dev one) - before that i tried the stable version.
Using anaconda , python 3.6.5

I tried using the pyinstaller and got an error: 

> RecursionError: maximum recursion depth exceeded

I tried also the ` --log-level DEBUG > out.txt` and came out with an empy file. 
I'm on a windows 10 laptop. 

My packages are:
```
import utm as utm 
import pandas as pd 
import numpy as np
import os
```

**Comment by htgoebel** [comment] 2018-09-20 13:18
Argl, this issue hits us again and again. Fortunately I saw a talk about using data visualization for debugging a few days ago and a have an idea how we can approach this.

Please run PyInstaller with `--log-level=TRACE` and post the output in a gist. Please do not post it here, since it will become a huge amount of data, and do not put it into an archive, since I'm not opening archives for security reasons.

**Comment by yogevNisim** [comment] 2018-09-22 15:55
Hi, 
this is the Gist (hope i used it right - first time)
https://gist.github.com/yogevNisim/434838a937d189f66d95ef14ac01a6f0

My python is Python 3.6.5
Packages i'm using in my code:

import utm as utm
import pandas as pd
import numpy as np
import os

If needed any further information i'll be happy to help

**Comment by htgoebel** [comment] 2018-09-24 20:15
Thanks for taking your time. Unfortunately this log is incomplete: the beginning is missing.
Also this log shows a different error. It's no "recursion to deep", but a unicode decode error. Reason for this is that you passed a tar.gz file as script.
Please provide a new log.

**Comment by RaphaelMaschinsen** [comment] 2018-11-16 19:45
Hi, 
Im having the exact same issue with pyinstaller 3.4 and python 3.6.5 on osx 10.13.6 in a virtual environment created with venv. I get the Error only if import specific libraries like sympy. When i downgrade python to version 3.5.6 the error disappears. If i can be of any help i'll gladly send an error report or more information.

**Comment by htgoebel** [comment] 2019-08-29 16:37
Please help taming the  "RecursionError:maximum recursion depth exceeded" errors, I was not yet able to reproduce this on my system, thus you need to provide data so I can try to fix the issue.

Please follow https://github.com/pyinstaller/pyinstaller/issues/4406, which (hopefully) provide the required information. Thanks!

**Comment by Legorooj** [comment] 2020-04-22 12:00
Closing; duplicate of #4406. A fix is en-route, and we might as well only have *one* issue open tracking it.

**Closed by Legorooj** 2020-04-22 12:00 UTC
Labels: area:modulegraph, version:3.4
