### ISSUE TITLE
Need support lib ssh2-python 

### ISSUE THREAD

**Issue by harte2018** [pyinstaller/pyinstaller#3351] opened 2018-03-01 10:11 UTC
Please help to support lib ssh2-python also.
Attached the web of download: https://pypi.python.org/pypi/ssh2-python/0.10.0#downloads
There will have issue after include ssh2-python.   (agent.pxd file cannot recognized by Pyinstaller.)
``` or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

from session cimport Session
cimport c_ssh2


cdef object PyAgent(c_ssh2.LIBSSH2_AGENT *agent, Session session)


cdef class Agent:
    cdef c_ssh2.LIBSSH2_AGENT *_agent
    cdef Session _session


cdef int auth_identity(const char *username,
                       c_ssh2.LIBSSH2_AGENT *agent,
                       c_ssh2.libssh2_agent_publickey **identity,
                       c_ssh2.libssh2_agent_publickey *prev) nogil except -1

cdef void clear_agent(c_ssh2.LIBSSH2_AGENT *agent) nogil

cdef int agent_auth(char * _username,
                    c_ssh2.LIBSSH2_AGENT * agent) nogil except 1

cdef c_ssh2.LIBSSH2_AGENT * init_connect_agent(
    c_ssh2.LIBSSH2_SESSION *_session) nogil except NULL

cdef c_ssh2.LIBSSH2_AGENT * agent_init(
    c_ssh2.LIBSSH2_SESSION *_session) nogil except NULL
```

**Comment by htgoebel** [comment] 2018-03-01 11:26
Duplicate of #3344

**Closed by htgoebel** 2018-03-01 11:26 UTC
