### ISSUE TITLE
could not import ConfigParser

### ISSUE THREAD

**Issue by pqwer99** [pyinstaller/pyinstaller#1995] opened 2016-05-18 03:50 UTC
could not import ConfigParser

python2.7.11 win7-32bit

**Comment by htgoebel** [comment] 2016-05-18 11:47
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by stephenrauch** [comment] 2016-05-25 14:00
Is this a dupe of #1871?

**Comment by pqwer99** [comment] 2016-05-26 02:24
yes.
building:
WARNING: Attempted to add Python module twice with different upper/lowercases: ConfigParser
running:
ImportError: No module named ConfigParser

**Comment by stephenrauch** [comment] 2016-05-26 02:29
You might want to try the same test I suggested in #1871, namely:

_Changes for #1935 (specifically a680f74) likely resolves the upper/lower warning problem and may well have resolved the rest of this issue. To test you can copy the file referenced by a680f74 into the install directory._

**Comment by vmartins** [comment] 2016-06-20 13:47
I was the problem:
`ImportError: No module named SocketServer`

And I solved the problem using version 3.3.dev0+5841294

**Comment by bwlee** [comment] 2016-11-16 03:20
Also found this issue. 

We have  code like:
```
if sys.major_version == 3:
   from configparser import ConfigParser
else:
     from ConfigParser import ConfigParser
```
then pyinstaller got warning:

> 35908 INFO: Analyzing run-time hooks ...
35918 WARNING: Attempted to add Python module twice with different upper/lowerca
ses: ConfigParser

while running,  got error as below:
  ```
  ImportError: No module named ConfigParser
   Failed to execute script router
```

BTW, it is strange, this error not always happened,  some scripts can be packed to exe and can be executed successfully.

**Comment by notalentgeek** [comment] 2017-05-14 23:41
I have this problem as well. Any solutions?

**Comment by htgoebel** [comment] 2017-08-31 20:48
Duplicate of #1935

**Closed by htgoebel** 2017-08-31 20:48 UTC
Labels: need info
