### ISSUE TITLE
pyinstaller cmdline flags don't override config in .spec-file

### ISSUE THREAD

**Issue by toxeus** [pyinstaller/pyinstaller#3403] opened 2018-03-14 13:41 UTC
I recently needed to debug a project that uses pyinstaller and that wouldn't start. I was really puzzled when I added the `--debug` and `--console` flags but still didn't get any console with useful output. In the end, I figured out that the flags on the commandline didn't override the config in the `.spec`-file. This is unexpected behavior to me and if you agree then I'm willing to contribute a patch that makes the commandline flags override the config in the `.spec`-file.

I've tested this with the latest `develop` branch on Windows.

**Comment by tallforasmurf** [comment] 2018-03-14 14:28
This behavior is documented, last paragraph under [Using Spec Files](http://pyinstaller.readthedocs.io/en/stable/spec-files.html#), "Only the following command-line options have an effect when building from a spec file:"

**Comment by toxeus** [comment] 2018-03-15 05:00
Thanks to for the pointer to the docs. Since this behavior is documented I agree that it's not *unexpected behavior* as in *it's a bug* but rather *unexpected behavior* as in *it's counterintuitive*. I'm used to the following UX and I don't think I'm the only one.

```bash
# configure git to always output colored diffs
git config color.diff always
# override git's config and show diff without color
git diff --no-color
```

But maybe there are good reasons for pyinstaller to behave that way. I just wanted to report this because I've lost some time while figuring this out and felt that other users might do as well. Also, making it easy for a user to see debug output will probably spare the pyinstaller project a couple of non-relevant bug reports. 

The least we can do is to improve point 3 in [If Things Go Wrong](https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) because clearly removing `--windowed` is not sufficient at all.

**Comment by htgoebel** [comment] 2018-03-15 08:59
> The least we can do is to improve point 3 in If Things Go Wrong because clearly removing --windowed is not sufficient at all.

This is a wiki, feel free to add whatever improvement you find useful.

**Comment by htgoebel** [comment] 2018-03-15 09:01
Duplicate of #1110

**Closed by htgoebel** 2018-03-15 09:01 UTC

**Comment by toxeus** [comment] 2018-03-15 09:05
I know. But before I do that I wanted to know if you'd consider to fix the root of the UX problem rather than creating documents that guide the user through the UX problem.

**Comment by htgoebel** [comment] 2018-03-15 19:50
As you can see #1110 has low priority and "pull-request wanted". This means that *I* will not work on this anytime soon. Of course implementing #1110 would be a better solution than creating documentation.

**Comment by toxeus** [comment] 2018-03-16 03:23
Thanks Hartmut, that's all I wanted to know.
