### ISSUE TITLE
Incomplete flushing of output buffers under pyinstaller on Windows

### ISSUE THREAD

**Issue by camprevail** [pyinstaller/pyinstaller#4908] opened 2020-06-01 17:16 UTC
Discovered using Enlighten Progress Bar for python. https://github.com/Rockhopper-Technologies/enlighten. The developer thinks it might be an issue with pyinstaller.

Under pyinstaller, output buffers are mangled in a way where some escape codes are written in plain text to the screen at the end of the program

To Reproduce

Create script:
```
import time
import enlighten

manager = enlighten.get_manager()
ticks = manager.counter(total=100, desc='Ticks', unit='ticks')

for num in range(100):
    time.sleep(0.01)
    ticks.update()
    print(num)

manager.stop()
```
Build and run:
```
c:> pyinstaller.exe --hidden-import=jinxed.terminfo.vtwin10 --onefile test.py
c:> dist\test.exe
```
Environment (please complete the following information):

Enlighten Version: 1.5.2
OS and version: Windows 10
Console application: cmd
Special Conditions: Only when running under pyinstaller
Additional context

This may be triggered by something called by Manager.stop().
It does not appear to happen a simple test case in jinxed and does occur if Manager.stop() isn't called.
The output seems to be flushed to the screen after the program has terminated.

**Comment by Legorooj** [comment] 2020-06-08 07:09
I'm unable to reproduce - I need to add a few hooks to fix other issues but the output is identical both frozen and unfrozen for me.

**Comment by avylove** [comment] 2020-07-30 01:24
Sorry, I didn't comment sooner, but this wasn't linked to the issue in the Enlighten repo, so I didn't know about it.

I just retested this and the results are the same and consistent. Here is what I get with pyinstaller

![Screenshot from 2020-07-29 21-13-41](https://user-images.githubusercontent.com/16090444/88869396-851a1e80-d1c7-11ea-8b6c-c1852195f926.png)

And what I get on the same system without pyinstaller
![Screenshot from 2020-07-29 21-14-12](https://user-images.githubusercontent.com/16090444/88869411-94996780-d1c7-11ea-8df5-0f1d37602663.png)

From some testing, I think the issue is the buffers aren't cleared, even when flush() is called, before atexit is executed. Enlighten relies on Blessed, which relies on Jinxed. The way it is used, Jinxed will reset the terminal to the original mode through atexit. If I force the console into Virtual Terminal Processing mode before calling Enlighten, it works as expected because the original mode supports VT processing, but that will leave the terminal in a mode the user may not desire.

**Comment by Legorooj** [comment] 2020-07-31 08:32
Huh. I tried again and managed to reproduce this - and it's not entirely a PyInstaller issue I think:

Using Windows terminal:
![Command Prompt 31_07_2020 6_23_30 PM](https://user-images.githubusercontent.com/50370070/89016209-b166a400-d35b-11ea-8675-34841d0b0313.png)

But with traditional command prompt:
![Screenshot 31_07_2020 6_27_37 PM](https://user-images.githubusercontent.com/50370070/89016246-c5aaa100-d35b-11ea-94eb-a77787648996.png)

This is odd. Both of the above screenshots are of the frozen version, and just running `python light.py` in the second command prompt works. This does need more investigation. The first thing to find out is what's the difference between Windows terminal and standard command prompt - it should narrow down the exact error. I'll contact the Terminal developers, but in the meantime can @bwoodsend reproduce this as well?

**Comment by avylove** [comment] 2020-07-31 08:55
The difference is Windows Terminal supports virtual terminal sequences by default, but CMD requires support to be turned on. The Jinxed library handles that, but restores the console mode to its previous state with [atexit](https://docs.python.org/3/library/atexit.html). For some reason, when running under Pyinstaller, the buffers aren't flushed before atexit is triggered, so the final sequences are outputted after virtual terminal processing is disable.

**Comment by Legorooj** [comment] 2020-07-31 09:03
@avylove thanks - I'll examine the jinxed source code and look at the bootloader.

**Comment by avylove** [comment] 2020-07-31 09:21
Thanks! This is the section I'm referring to.

https://github.com/Rockhopper-Technologies/jinxed/blob/d465753c34fe0a2a97568b38f323e4b504826f50/jinxed/win32.py#L186-L196

**Comment by bwoodsend** [comment] 2020-07-31 10:57
@Legorooj @avylove Mine behaved quite a bit differently. Normally I use a console emulator `cmder` rather than Window's own `cmd` which behaved fine. Running from plain `cmd` gave a missing dll error:

```shell
E:\notebooks\pyi-issues\4908>dist\test.exe
Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 167, in __init__
  File "ctypes\__init__.py", line 344, in __init__
OSError: [WinError 126] The specified module could not be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    manager = enlighten.get_manager()
  File "enlighten\_manager.py", line 523, in get_manager
  File "enlighten\_manager.py", line 73, in __init__
  File "enlighten\_terminal.py", line 26, in __init__
  File "blessed\terminal.py", line 171, in __init__
  File "jinxed\win32.py", line 201, in get_term
  File "ansicon\__init__.py", line 52, in load
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 169, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'E:\\AppData\\Local\\
Temp\\_MEI104762\\ansicon\\ANSI64.dll'. Most probably this dynlib/dll was not fo
und when the application was frozen.
[3316] Failed to execute script test
```

Patching said error in the spec file by adding to the top:
```
from PyInstaller.utils.hooks import collect_dynamic_libs`
```
And in the `a = Analysis(...)` section:
```
binaries=collect_dynamic_libs('ansicon')
```

Now it works fine but I get a seemingly incomplete runtime warning in plain `cmd`:
```
setupterm(kind='ansicon'): Could not find terminal ansiconserWarning: Failed to
```

And in `cmder`:
```
E:\AppData\Local\Temp\_MEI90002\blessed\terminal.py:190: UserWarning: Failed to setupterm(kind='cygwin'): Could not
 find terminal cygwin.
```

But I also get these warnings outside PyInstaller so that's not our problem. :grinning: 

Could either of you try with the modifed spec file and see if that makes it any happier? If it does then I'll add/update a hook for `ansicon`.

**Comment by avylove** [comment] 2020-07-31 11:29
You only need ansicon for versions of Windows before 10.0.10586, after that virtual terminal processing is native. What version of Windows are you running?

**Comment by bwoodsend** [comment] 2020-07-31 11:38
Windows 8.0

**Comment by bwoodsend** [comment] 2020-07-31 11:40
Guessing that probably isn't the issue then...

**Comment by avylove** [comment] 2020-07-31 12:07
Yeah, it would be a different issue. For your use case you would need to add jinxed.terminfo.ansicon as a hidden import. (@Legorooj, I guess that should be added in the hook) I am curious if you see issues though. I wouldn't expect you'd see the same issue, but line wrapping is enabled on Win8 by Jinxed in the same way at virtual terminal processing is enable on Win10

**Comment by bwoodsend** [comment] 2020-07-31 18:44
Update: I copied the exe I made on my Windows 8 (which didn't have this issue) onto a borrowed Windows 10 and the issue is back. So the difference is in the runner, not the build. 

![test](https://user-images.githubusercontent.com/30940778/89066328-31453c00-d365-11ea-9a42-02cd829f6c87.png)

I'm not sure if this is likely to make a difference but I have fiddled with my `cmd` to get it to use `utf-8`. This involved setting the code-page and changing the font to one that actually has `utf-8` characters. I'll see if I can remember how to change it back... 

@avylove I wonder if we can intercept this at a lower level. You talk about switching console states - is there a `get_console_state()` method we can poll and chuck in some print statements with?

**Comment by avylove** [comment] 2020-07-31 20:12
The code will try to adjust for utf. If that was the issue we'd probably be seeing diamonds where the blocks are.
Yes, there is `jinxed.win32.get_console_mode()`. You could do something like this to see if virtual terminal processing is enabled.
```
from msvcrt import get_osfhandle
import sys
from jinxed.win32 import get_console_mode

filehandle = get_osfhandle(sys.__stdout__.fileno())
print(bool(get_console_mode(filehandle) & 4))
```

That said, the output at the bottom of the screenshots is unhandled terminal escape codes. It's handling them fine until `atexit` is called. So the question is why are they still in the buffer under pyinstaller and not run regularly.

I did find flushing both stderr and stdout at the end of the code seems to mitigate the issue.

```
import time
import sys
import enlighten

manager = enlighten.get_manager()
ticks = manager.counter(total=100, desc='Ticks', unit='ticks')

for num in range(100):
    time.sleep(0.01)
    ticks.update()
    print(num)

manager.stop()

sys.stdout.flush()
sys.stderr.flush()
```

So why is that needed under pyinstaller and not regularly?

**Comment by bwoodsend** [comment] 2020-07-31 21:43
I've hacked together something disgusting which shows **a** difference between Python's flushing and PyInstaller's flushing. Essentially I've hijacked `stdout` and `stderr` to write additional information on `write()` and `flush()`.

```python

import io, sys

old = sys.__stdout__

class FakeSTDOut(type(old)):
    def write(self, string):
        old.write("{}: {}".format(type(self).__name__, repr(string)))
        old.write("\n")

    def flush(self):
        old.write("Flushing " + type(self).__name__ + "\n")
        old.flush()

class FakeSTDErr(FakeSTDOut):
    pass

sys.stdout = sys.__stdout__ = FakeSTDOut(sys.__stdout__.buffer)
sys.stderr = sys.__stderr__ = FakeSTDErr(sys.__stderr__.buffer)

print("hello")
```

The output of which is (on both Windows 8 and 10):
```shell
λ python flush_test.py
FakeSTDOut: 'hello'
FakeSTDOut: '\n'
Flushing FakeSTDErr
Flushing FakeSTDOut
Flushing FakeSTDOut
Flushing FakeSTDOut

λ dist\flush_test\flush_test.exe
FakeSTDOut: 'hello'
FakeSTDOut: '\n'
Flushing FakeSTDOut
Flushing FakeSTDOut
```
(Without the `print("hello")` the `FakeSTDOut: ...`s disappear but flushing stays the same.)

So there appears to be extra flushing going on in regular Python which PyInstaller is not doing...

I've also verified that `atexit` works fine on PyInstaller and that calling `atexit._run_exitfuncs()` explicity doesn't fix anything. So that isn't the issue.

**Comment by avylove** [comment] 2020-07-31 22:51
Great work! It's a little different on my system for pyinstaller. Not sure why, but without print I get
```
Flushing FakeSTDOut
Flushing FakeSTDErr
Flushing FakeSTDOut
```
Which is one more flush than you're seeing, but still doesn't match native Python.

I replaced `print("hello")` in your test code with
```
import atexit
atexit.register(print, 'AT EXIT')
```
And I'm getting this:
```
> python3 test3.py
Flushing FakeSTDErr
Flushing FakeSTDOut
FakeSTDOut: 'AT EXIT'
FakeSTDOut: '\n'
Flushing FakeSTDOut
Flushing FakeSTDOut

> >dist\test3.exe
FakeSTDOut: 'ATEXIT'
FakeSTDOut: '\n'
Flushing FakeSTDOut
Flushing FakeSTDErr
Flushing FakeSTDOut
```

This clearly shows native python is flushing both buffers before atexit is called, but that is not happening under pyinstaller.

**Comment by Legorooj** [comment] 2020-08-02 08:08
Phew. After messing about for hours in the bootloader I think I might have a fix for this. I'll let you know tomorrow if it worked, and get you to test it.

**Comment by Legorooj** [comment] 2020-08-03 07:37
The atexit functions get called by https://github.com/pyinstaller/pyinstaller/blob/9ae90f8f2d954213fedb99ab02fe4b6a2129919a/bootloader/src/pyi_pythonlib.c#L693

I've fixed it by manually flushing the buffers on exit. Can you try using Legorooj@6361f9afeeaf0f3309 and seeing if this works? You'll need to recompile the bootloaders.

**Comment by avylove** [comment] 2020-08-03 10:58
Works for me! Ran into the long path issue in #4824 at first, but was able to get it to compile.

Thanks for your help on this!

**Comment by Legorooj** [comment] 2020-08-05 06:17
@bwoodsend does this work for you?

**Comment by Legorooj** [comment] 2020-08-05 06:23
Fix merged into the development branch in https://github.com/pyinstaller/pyinstaller/commit/d8e4621df273233ca379222e9a9425af0937fb3a.

**Closed by Legorooj** 2020-08-05 06:23 UTC
Labels: area:bootloader, platform:Windows, state:need info
