### ISSUE TITLE
Pyinstaller Failed execute script Error when quit app

### ISSUE THREAD

**Issue by KiYugadgeter** [pyinstaller/pyinstaller#3298] opened 2018-02-13 13:57 UTC
I am trying to make exe file with PyInstaller.

This program is auto stock order program from stock company website with selenium.
Also it use multiprocessing module

Failed execute script error raise when closing app in the case of --windowed build option is enable.
If it is not enable, it doesn't raise.

I have no idea how I do survey a causes of error because the error raise when --windowed option enable only.

How do I fix this error?

I using:
- Windows10 Home 1709
- Visual Studio 2017 Community
- Python 3.6.4
- Pyinstaller 3.3.1
- selenium 3.9.0

Following is warn file:
```
missing module named 'win32com.gen_py' - imported by win32com, c:\users\username\programming\pyworks\project\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_win32comgenpy.py
missing module named pyimod03_importers - imported by c:\users\username\programming\pyworks\project\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py
missing module named StringIO - imported by selenium.webdriver.remote.webelement, pkg_resources._vendor.six
missing module named 'pkg_resources.extern.pyparsing' - imported by pkg_resources._vendor.packaging.markers, pkg_resources._vendor.packaging.requirements
missing module named 'com.sun' - imported by pkg_resources._vendor.appdirs
missing module named com - imported by pkg_resources._vendor.appdirs
missing module named __builtin__ - imported by pkg_resources._vendor.pyparsing
missing module named ordereddict - imported by pkg_resources._vendor.pyparsing
missing module named __main__ - imported by pkg_resources
missing module named pkg_resources.extern.packaging - imported by pkg_resources.extern, pkg_resources
missing module named pkg_resources.extern.appdirs - imported by pkg_resources.extern, pkg_resources
missing module named 'pkg_resources.extern.six.moves' - imported by pkg_resources, pkg_resources._vendor.packaging.requirements
missing module named pkg_resources.extern.six - imported by pkg_resources.extern, pkg_resources
missing module named 'multiprocessing.forking' - imported by c:\users\username\programming\pyworks\project\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py
missing module named multiprocessing.get_context - imported by multiprocessing, multiprocessing.pool, multiprocessing.managers, multiprocessing.sharedctypes
missing module named multiprocessing.TimeoutError - imported by multiprocessing, multiprocessing.pool
missing module named multiprocessing.BufferTooShort - imported by multiprocessing, multiprocessing.connection
missing module named multiprocessing.AuthenticationError - imported by multiprocessing, multiprocessing.connection
missing module named multiprocessing.set_start_method - imported by multiprocessing, multiprocessing.spawn
missing module named multiprocessing.get_start_method - imported by multiprocessing, multiprocessing.spawn
missing module named resource - imported by posix, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named posix - imported by os, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named _posixsubprocess - imported by subprocess, multiprocessing.util, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named org - imported by pickle, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named readline - imported by cmd, code, pdb, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named _winreg - imported by platform, selenium.webdriver.firefox.firefox_binary, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py, pkg_resources._vendor.appdirs
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named 'java.lang' - imported by platform, xml.sax._exceptions, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named vms_lib - imported by platform, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named termios - imported by tty, getpass, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named grp - imported by shutil, tarfile, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named pwd - imported by posixpath, shutil, tarfile, http.server, webbrowser, netrc, getpass, distutils.util, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named _dummy_threading - imported by dummy_threading, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named 'org.python' - imported by copy, xml.sax, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named multiprocessing.freeze_support - imported by multiprocessing, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named multiprocessing.Manager - imported by multiprocessing, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named multiprocessing.Process - imported by multiprocessing, C:\Users\username\Programming\pyworks\project\src\getn225okasan.py
missing module named urllib2 - imported by selenium.webdriver.common.utils, selenium.webdriver.remote.remote_connection, selenium.webdriver.common.service
missing module named urlparse - imported by selenium.webdriver.remote.remote_connection
missing module named httplib - imported by selenium.webdriver.firefox.webdriver, selenium.webdriver.remote.remote_connection, selenium.webdriver.safari.webdriver, selenium.webdriver.blackberry.webdriver, selenium.webdriver.webkitgtk.webdriver
missing module named sets - imported by pytz.tzinfo
missing module named UserDict - imported by pytz.lazy
missing module named cStringIO - imported by selenium.webdriver.firefox.firefox_profile
missing module named copy_reg - imported by cStringIO
```

**Comment by htgoebel** [comment] 2018-03-15 22:28
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment] 2019-01-23 09:21
No new infos since several months, closing.

**Closed by htgoebel** 2019-01-23 09:21 UTC
Labels: not enough info
