### ISSUE TITLE
ImportError: No module named UserList

### ISSUE THREAD

**Issue by Neo23x0** [pyinstaller/pyinstaller#2327] opened 2016-12-20 18:22 UTC
Using ...
Python: 2.7.10
Arch: x86
Platform: Windows 7 
PyInstaller 3.2: current development snapshot (commit 483c819)

Module Versions (current - at least pip has no updates for them):
future (0.16.0)
pefile (2016.3.28)

The single file (-F) builds correctly, but I get the following error when running the executable.

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
  File "X:\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\thorcore.py", line 61, in <module>
  File "X:\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lib\checker.py", line 11, in <module>
  File "X:\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\peutils.py", line 14, in <module>
  File "site-packages\future\standard_library\__init__.py", line 457, in install_aliases
ImportError: No module named UserList
```

**Comment by htgoebel** [comment] 2016-12-20 19:30
I assume this is the same like #1871

**Comment by htgoebel** [comment] 2017-08-31 20:54
Duplicate of #1935

**Closed by htgoebel** 2017-08-31 20:54 UTC
Labels: Windows
