### ISSUE TITLE
zmq not working in python3 branch - libzmq not bundled properly

### ISSUE THREAD

**Issue by nexcvon** [pyinstaller/pyinstaller#1404] opened 2015-08-11 10:34 UTC
My PyInstaller Version:
https://github.com/pyinstaller/pyinstaller/tree/99227fb1b23283fd08314e132738563eb40ce5b6

My test script:
```
import zmq
print(zmq.__version__)
print(zmq.zmq_version())
```

Part of PyInstaller build log:
```
...
21937 INFO: Looking for dynamic libraries
23187 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\_device.pyd
23406 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\context.pyd
23734 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\utils.pyd
24250 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\_version.pyd
24484 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\error.pyd
24718 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\_poll.pyd
24937 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\socket.pyd
25625 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\backend\cython\message.pyd
26062 WARNING: lib not found: libzmq.pyd dependency of C:\Python34\lib\site-packages\zmq\devices\monitoredqueue.pyd
...
```

Traceback:
```
['dist\\test\\test.exe']
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyi_importers.py", line 309, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python34\lib\site-packages\zmq\__init__.py", line 66, in <module>
    from zmq import backend
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyi_importers.py", line 309, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python34\lib\site-packages\zmq\backend\__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "C:\Python34\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Python34\lib\site-packages\zmq\backend\__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "C:\Python34\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyi_importers.py", line 309, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python34\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyi_importers.py", line 479, in load_module
    module = loader.load_module(fullname)
ImportError: DLL load failed: The specified module could not be found.
```

Files in dist directory:
```
libsodium.pyd
zmq.backend.cython._device.pyd
zmq.backend.cython._poll.pyd
zmq.backend.cython._version.pyd
zmq.backend.cython.constants.pyd
zmq.backend.cython.context.pyd
zmq.backend.cython.error.pyd
zmq.backend.cython.message.pyd
zmq.backend.cython.socket.pyd
zmq.backend.cython.utils.pyd
zmq.devices.monitoredqueue.pyd
zmq.libzmq.pyd
```

If rename `zmq.libzmq.pyd` to `libzmq.pyd`, it works.

**Comment by matysek** [comment] 2015-08-14 07:14
@nexcvon What version of zmq do you use?

**Comment by matysek** [comment] 2015-08-14 08:35
I will try to reproduce that and add a test case from your example.

**Comment by matysek** [comment] 2015-08-14 12:57
* I'm able to reproduce this on linux.
* It's interesting that dynamic libraries ends with `.pyd`.
* To fix this PyInstaller should handle files `lib*.pyd` `lib*.so` as binary files.
  * I think having in hookutils a function like `collect_dylib` to collect libraries that are bundled with the package will be useful.

**Comment by matysek** [comment] 2015-08-14 13:37
> To fix this PyInstaller should handle files lib*.pyd lib*.so as binary files.

I found out that file `hook-zmq.py` already contains something like that. I will reuse that and generalize that.

**Comment by matysek** [comment] 2015-08-14 16:14
@nexcvon Could you test the latest `python3`? It should be fixed.

**Closed by matysek** 2015-08-14 16:14 UTC
Labels: PY3, Windows

**Comment by nexcvon** [comment] 2015-08-19 03:48
I tested. It works now.
But I found two `libsodium.pyd`: one in dist directory, another one in `zmq` subdirectory. Would this become a problem? I think one DLL should not be loaded multiple times.

**Comment by matysek** [comment] 2015-08-24 22:25
nexcvon, I don't think this is a  problem. It should be safe to remove `libsodium.pyd` from dist directory because pyzmq is looking for libsodium in `./dist/app_name/zmq/`.
