### ISSUE TITLE
No module named 'statsmodels.tsa.statespace._filters' 

### ISSUE THREAD

**Issue by digdig** [pyinstaller/pyinstaller#3921] opened 2018-12-11 15:58 UTC
In my source, I import statsmodels using `import statsmodels.api as sm`, using pyinstaller, I can generate the exe file, when run it: the following error occurs:

```
$ ./main.exe
[37648] Failed to execute script main
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "data.py", line 2, in <module>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "utils.py", line 6, in <module>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\statsmodels\api.py", line 7, in <module>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\statsmodels\regression\recursive_ls.py", line 16, in <modu                                                                                                                                                                                               le>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\statsmodels\tsa\statespace\mlemodel.py", line 18, in <modu                                                                                                                                                                                               le>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\statsmodels\tsa\statespace\simulation_smoother.py", line 1                                                                                                                                                                                               0, in <module>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\statsmodels\tsa\statespace\kalman_smoother.py", line 11, i                                                                                                                                                                                               n <module>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\statsmodels\tsa\statespace\representation.py", line 10, in                                                                                                                                                                                                <module>
  File "C:\Users\LM\AppData\Local\Programs\Python\Python36\lib\site-packages\PyI                                                                                                                                                                                               nstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\statsmodels\tsa\statespace\tools.py", line 207, in <module                                                                                                                                                                                               >
  File "site-packages\statsmodels\tsa\statespace\tools.py", line 59, in set_mode
  File "_kalman_filter.pyx", line 1, in init statsmodels.tsa.statespace._kalman_                                                                                                                                                                                               filter
ModuleNotFoundError: No module named 'statsmodels.tsa.statespace._filters'
```

I am using python 3.6 and my `statsmodels` and `pyinstaller` are both up to date

**Comment by obsidianm** [comment] 2018-12-26 09:48
@digdig The solution can be found in https://blog.csdn.net/mooncrystal123/article/details/83182224. 
Pyinstaller couldn't recognize pyd(Python Extension Module) files and modules such as statsmodels.tsa.statespace._kalman_filter would cause a mistake.

1. Creat 'hook-statsmodels.py' in the'\site-packages\PyInstaller\hooks' directory
2. The 'hook-statsmodels.py' code is shown as below:

```
hiddenimports=[
    #all your previous hidden imports
    'statsmodels.tsa.statespace._kalman_filter',
    'statsmodels.tsa.statespace._kalman_smoother',
    'statsmodels.tsa.statespace._representation',
    'statsmodels.tsa.statespace._simulation_smoother',
    'statsmodels.tsa.statespace._statespace',
    'statsmodels.tsa.statespace._tools',
    'statsmodels.tsa.statespace._filters._conventional',
    'statsmodels.tsa.statespace._filters._inversions',
    'statsmodels.tsa.statespace._filters._univariate',
    'statsmodels.tsa.statespace._smoothers._alternative',
    'statsmodels.tsa.statespace._smoothers._classical',
    'statsmodels.tsa.statespace._smoothers._conventional',
    'statsmodels.tsa.statespace._smoothers._univariate'
]
```
They're all pyd files in the \site-packages\statsmodels\tsa\statespace directory.

3. Run pyinstaller using the following command

`python pyinstaller.py -F -c mainfile.py --hidden-import=statsmodels.tsa.statespace._kalman_filter --hidden-import=statsmodels.tsa.statespace._kalman_smoother --hidden-import=statsmodels.tsa.statespace._representation --hidden-import=statsmodels.tsa.statespace._simulation_smoother --hidden-import=statsmodels.tsa.statespace._statespace --hidden-import=statsmodels.tsa.statespace._tools --hidden-import=statsmodels.tsa.statespace._filters._conventional --hidden-import=statsmodels.tsa.statespace._filters._inversions --hidden-import=statsmodels.tsa.statespace._filters._univariate --hidden-import=statsmodels.tsa.statespace._smoothers._alternative --hidden-import=statsmodels.tsa.statespace._smoothers._classical --hidden-import=statsmodels.tsa.statespace._smoothers._conventional --hidden-import=statsmodels.tsa.statespace._smoothers._univariate`

And this will work now. BTW, all module with pyd files will cause the same mistake. If you have other module with pyd files, do the same things.

**Comment by digdig** [comment] 2018-12-28 11:45
@obsidianm Thanks for the solution. But are you sure about that the pyd files can't compile using pyinstaller? I tried a very simple program, the structure is like this:

in `add.py`:
```
def addition(a, b):
    return a+b
```

in `hello.py`:

```
# coding:utf-8
import add
def hello():
    print("Hello world")
    print("5 add 6 is %d" % add.addition(5, 6))
    input("<press ENTER to quit>")


if __name__ == "__main__":
    hello()
```

The `index.py` is the entry file, which is:

```
import hello

if __name__ == "__main__":
    hello.hello()
```

Compile is with cython and obtain the pyd files: `hello.pyd` and `add.pyd`, together copy it with `index.py`, and using `pyinstaller -F index.py`, the resulting exe file can run without trouble, you may test it.

**Comment by husnuye** [comment] 2019-01-04 13:39
@obsidianm Thanks for posting a hook that solved the problem for me :)

**Comment by htgoebel** [comment] 2019-01-05 11:38
Duplicate of #2183

**Closed by htgoebel** 2019-01-05 11:38 UTC

**Comment by pipete40** [comment] 2019-07-31 15:18
Update for Statsmodels 0.10
           
  hiddenimports=[
		    #all your previous hidden imports
		    'statsmodels.tsa.statespace._kalman_initialization',
		    'statsmodels.tsa.statespace._kalman_filter',
 		    'statsmodels.tsa.statespace._kalman_smoother',
 		    'statsmodels.tsa.statespace._representation',
    		    'statsmodels.tsa.statespace._simulation_smoother',
    		    'statsmodels.tsa.statespace._statespace',
    		    'statsmodels.tsa.statespace._tools',
    		    'statsmodels.tsa.statespace._filters._conventional',
  		    'statsmodels.tsa.statespace._filters._inversions',
    		    'statsmodels.tsa.statespace._filters._univariate',
		    'statsmodels.tsa.statespace._filters._univariate_diffuse',
    		    'statsmodels.tsa.statespace._smoothers._alternative',
		    'statsmodels.tsa.statespace._smoothers._classical',
    		    'statsmodels.tsa.statespace._smoothers._conventional',
   		    'statsmodels.tsa.statespace._smoothers._univariate',
 		    'statsmodels.tsa.statespace._smoothers._univariate_diffuse'],

**Comment by htgoebel** [comment] 2019-08-11 16:48
@pipete40 Please see #2183 and provide a pull-request.
