### ISSUE TITLE
PyInstaller 3.0 cannot find required imports from .egg files

### ISSUE THREAD

**Issue by JokerQyou** [pyinstaller/pyinstaller#1607] opened 2015-10-16 12:13 UTC
Let's say I have a main script named `main.py`, and I want to package that into a `.exe` executable. I've specified hidden imports in `main.spec`

```python
a = Analysis(['main.py'],
             pathex=['.'],
             hiddenimports=['pyoauth2', 'edo_client', 'PyPDF2', 'cStringIO', ],
             hookspath=None,
             runtime_hooks=None)
```

The packages `pyoauth2` and `edo_client` are installed in `.egg` files, named `edo_client-0.9.3-py2.7.egg` and `py_oauth2-0.0.10-py2.7.egg`. (They are installed using `pip` or directly from `python setup.py install`)

And PyInstaller cannot find these two packages. Here is part of the beginning of the build output:

```log
255 INFO: PyInstaller: 3.0
256 INFO: Python: 2.7.10
256 INFO: Platform: Windows-8-6.2.9200
283 INFO: UPX is not available.
286 INFO: Removing temporary files and cleaning cache in C:\Users\Joker Qyou\AppData\Roaming\pyinstaller
395 INFO: Extending PYTHONPATH with D:\Work\DO
396 INFO: checking Analysis
398 INFO: Building Analysis because out00-Analysis.toc is non existent
398 INFO: Initializing module dependency graph...
404 INFO: Initializing module graph hooks...
406 INFO: Analyzing hidden import 'pyoauth2'
412 ERROR: Hidden import 'pyoauth2' not found
413 INFO: Analyzing hidden import 'edo_client'
419 ERROR: Hidden import 'edo_client' not found
421 INFO: Analyzing hidden import 'PyPDF2'
4954 INFO: running Analysis out00-Analysis.toc
4960 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by C:\Python27\python.exe
```

The build procedure will continue, and the executable will output following content upon running if I build it with `console=True`.

```log
PyInstaller Bootloader 3.x                                                     
LOADER: executable is C:\Program Files (x86)\EDOAssistent\edo_assistent.exe    
LOADER: homepath is C:\Program Files (x86)\EDOAssistent                        
LOADER: _MEIPASS2 is NULL                                                      
LOADER: archivename is C:\Program Files (x86)\EDOAssistent\edo_assistent.exe   
LOADER: No need to extract files to run; setting extractionpath to homepath    
LOADER: SetDllDirectory(C:\Program Files (x86)\EDOAssistent)                   
LOADER: Already in the child - running user's code.                            
LOADER: Python library: C:\Program Files (x86)\EDOAssistent\python27.dll       
LOADER: Loaded functions from Python library.                                  
LOADER: Manipulating environment (sys.path, sys.prefix)                        
LOADER: sys.prefix is C:\Program Files (x86)\EDOAssistent                      
LOADER: Setting runtime options                                                
LOADER: Initializing python                                                    
LOADER: Overriding Python's sys.path                                           
LOADER: Post-init sys.path is C:\Program Files (x86)\EDOAssistent              
LOADER: Setting sys.argv                                                       
LOADER: setting sys._MEIPASS                                                   
LOADER: importing modules from CArchive                                        
LOADER: extracted struct                                                       
LOADER: callfunction returned...                                               
LOADER: extracted pyimod01_os_path                                             
LOADER: callfunction returned...                                               
LOADER: extracted pyimod02_archive                                             
LOADER: callfunction returned...                                               
LOADER: extracted pyimod03_importers                                           
LOADER: callfunction returned...                                               
LOADER: Installing PYZ archive with Python modules.                            
LOADER: PYZ archive: out00-PYZ.pyz                                             
LOADER: Running pyiboot01_bootstrap.py                                         
LOADER: Running pyi_rth_win32comgenpy.py                                       
LOADER: Running pyi_rth__tkinter.py                                            
LOADER: Running pyi_rth_qt4plugins.py                                          
Qt: Untested Windows version 10.0 detected!                                    
LOADER: Running pyi_rth_pkgres.py                                              
LOADER: Running main.py                                                        
Traceback (most recent call last):                                             
  File "<string>", line 4, in <module>                                         
ImportError: No module named edo_client                                        
main returned -1                                                               
LOADER: OK.                                                                    
LOADER: Cleaning up Python interpreter.                                        
```

The above log clearly indicates that the modules are not there. I can verify that by using `pyi-archive_viewer` to get a list of contained packages inside the `out00-PYZ.pyz` file too.

If I unpackage these two packages into folders named `pyoauth2` and `edo_client` and put them in the folder specified by `pathex` option, this problem would not occur.

I'm using `Python 2.7.10 32bit` on `Windows 10 pro 64bit`, and this problem occurs after I upgraded PyInstaller via `pip install --upgrade pyinstaller`. The reason for this upgrade is to support `gevent 1.1`.

**Comment by matysek** [comment] 2015-10-16 12:54
This looks like a duplicate of #1581

**Comment by JokerQyou** [comment] 2015-10-16 13:37
Yes I think this is a duplicate.

**Comment by matysek** [comment] 2015-10-16 14:31
This is duplicate of #1581.

**Closed by matysek** 2015-10-16 14:31 UTC
Labels: duplicate, PY2, support, v3.0, Windows
