### ISSUE TITLE
GraphError: Invalid nodes matplotlib.backends.qt_compat -> PyQt4.QtCore ( broken excludedimports  )

### ISSUE THREAD

**Issue by goyodiaz** [pyinstaller/pyinstaller#1593] opened 2015-10-09 09:52 UTC
I am getting this error when trying to package a script using matplotlib.

Microsoft Windows [Versión 6.1.7601]
Python 2.7.9
PyInstaller 3.0 (also 3.1.dev0 installed using pip on 2015-10-09)
Matplotlib 1.4.3

The script is as simple as it goes:
```python
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt

plt.plot([1, 2, 3])
plt.savefig('pitest.png')
```

The error:
```
> pyinstaller pitest.py
[long output skipped]
[long stacktrace skipped]
PyInstaller.lib.altgraph.GraphError: Invalid nodes matplotlib.backends.qt_compat -> PyQt4.QtCore
```
Full output and the script:
https://gist.github.com/goyodiaz/5bdbc1461c01a79f8b08

**Comment by matysek** [comment] 2015-10-09 11:09
@goyodiaz This looks similar to #1584 .

**Comment by matysek** [comment] 2015-10-09 11:15
@goyodiaz Could you try the same as mentioned in #1584?
```
Does it work when you comment out line starting with `excludedimports` in files `\PyInstaller\hooks\hook-PIL.py` and `hook-PIL.SpiderImagePlugin.py`?
```

**Comment by goyodiaz** [comment] 2015-10-09 12:28
Thanks, @matysek. I will be unable to try until monday. I will report back then.

**Comment by chrisb1989** [comment] 2015-10-14 07:59
I have the same issue. did you figure this out?

**Comment by matysek** [comment] 2015-10-14 08:30
> Does it work when you comment out line starting with `excludedimports`

@goyodiaz Does this workaround work for your usecase?

**Comment by goyodiaz** [comment] 2015-10-14 13:21
Apologies for the delay. The suggested workaround worked.

Actually editing just hook-PIL.py was enough for the package to build and run (in the same computer). I did not have to touch hook-PIL.SpiderImagePlugin.py.

**Comment by matysek** [comment] 2015-10-14 20:07
Closing. Duplicate of #1584

**Closed by matysek** 2015-10-14 20:07 UTC
Labels: duplicate, hooks, v3.0, Windows
