### ISSUE TITLE
can not us upx

### ISSUE THREAD

**Issue by sechacking** [pyinstaller/pyinstaller#1496] opened 2015-09-17 08:21 UTC
hi,

so,first i have upx

[root@ops bincache01_py27]# whereis upx
upx: /usr/bin/upx /usr/share/man/man1/upx.1.gz
[root@ops-pdc-02 bincache01_py27]# upx -v
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..

Commands:
  -1     compress faster                   -9    compress better
  -d     decompress                        -l    list compressed file
  -t     test compressed file              -V    display version number
  -h     give more help                    -L    display software license
Options:
  -q     be quiet                          -v    be verbose
  -oFILE write output to 'FILE'
  -f     force compression of suspicious files
  -k     keep backup files
file..   executables to (de)compress

Type 'upx --help' for more detailed help.

UPX comes with ABSOLUTELY NO WARRANTY; for details visit http://upx.sf.net

and i use pyinstall

12 INFO: wrote /tmp/upx/software_port_script.spec
35 INFO: UPX is available.
60 INFO: Processing hook hook-os
176 INFO: Processing hook hook-time
179 INFO: Processing hook hook-cPickle
259 INFO: Processing hook hook-_sre
390 INFO: Processing hook hook-cStringIO
519 INFO: Processing hook hook-encodings
537 INFO: Processing hook hook-codecs
1084 INFO: Extending PYTHONPATH with /tmp/upx
1084 INFO: checking Analysis
1084 INFO: building Analysis because out00-Analysis.toc non existent
1084 INFO: running Analysis out00-Analysis.toc
1128 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller/loader/_pyi_bootstrap.py
1154 INFO: Processing hook hook-os
1178 INFO: Processing hook hook-site
1204 INFO: Processing hook hook-encodings
1383 INFO: Processing hook hook-time
1387 INFO: Processing hook hook-cPickle
1507 INFO: Processing hook hook-_sre
1700 INFO: Processing hook hook-cStringIO
1876 INFO: Processing hook hook-codecs
2312 INFO: Processing hook hook-pydoc
2449 INFO: Processing hook hook-email
2508 INFO: Processing hook hook-httplib
2545 INFO: Processing hook hook-email.message
2601 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py
2646 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_archive.py
2690 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_carchive.py
2734 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_os_path.py
2737 INFO: Analyzing software_port_script.py
2955 INFO: Processing hook hook-xml
3004 INFO: Processing hook hook-xml.sax
3048 INFO: Processing hook hook-pyexpat
3115 INFO: Hidden import 'codecs' has been found otherwise
3115 INFO: Hidden import 'encodings' has been found otherwise
3115 INFO: Looking for run-time hooks
3887 INFO: Using Python library /usr/local/lib/libpython2.7.so.1.0
3927 INFO: Warnings written to /tmp/upx/build/software_port_script/warnsoftware_port_script.txt
3940 INFO: checking PYZ
3940 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
3941 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
5312 INFO: checking PKG
5312 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
5312 INFO: building PKG (CArchive) out00-PKG.pkg
12706 INFO: checking EXE
12707 INFO: rebuilding out00-EXE.toc because software_port_script missing
12707 INFO: building EXE from out00-EXE.toc
12708 INFO: Executing - upx --best -q /.local/share/pyinstaller/bincache01_py27/run
12870 INFO: Appending archive to EXE /tmp/upx/dist/software_port_script

and i use  /.local/share/pyinstaller/bincache01_py27/run

Cannot open self /.local/share/pyinstaller/bincache01_py27/run or archive /.local/share/pyinstaller/bincache01_py27/run.pkg

**Comment by codewarrior0** [comment] 2015-09-17 08:26
The executable produced by pyinstaller is in `./dist`. It is not in `bincache01_py27`.

`cd` to the folder containing your `software_port_script.py` and start over.

**Comment by sechacking** [comment] 2015-09-17 08:47
@codewarrior0 thanks,i konw the script is in dist,i mean is upx file in bincache01_py27?

**Comment by sechacking** [comment] 2015-09-17 08:48
@codewarrior0  in dist,the script seem like not upx....so i don't konw what wrong

**Comment by codewarrior0** [comment] 2015-09-17 08:56
The executable in `dist` should be compressed with UPX.

You can compare the sizes by running pyinstaller once normally, and then running it again with the `--noupx` option.

**Comment by sechacking** [comment] 2015-09-17 10:22
@codewarrior0  thank you,i want upx my script,but pyinstall seems like not work....see my question

**Comment by codewarrior0** [comment] 2015-09-17 10:28
The executable in `dist` will already be compressed with UPX. You don't need to do anything else.

Closing as I don't see what the problem is.

**Closed by codewarrior0** 2015-09-17 10:28 UTC
Labels: support
