### ISSUE TITLE
pkg_resources runtime magic ( pkg_resources.get_distribution )

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#183] opened 2014-10-18 13:35 UTC
**Original date**: 2010/05/04
**Original reporter**: *drakkan <lists AND svrinformatica DOT it>*

Pyinstaller is unable to add the new paths imported using pkg_resources:

http://groups.google.com/group/pyinstaller/browse_thread/thread/0e66585401cb4f48

**Comment by htgoebel** [comment] 2015-09-03 09:07
This could be solved using the mechanisms I just added (see https://github.com/pyinstaller/pyinstaller/issues/1362#issuecomment-137385595). The issue is that all Distributions store their meta-data in the `EGG-INFO` sub-directory. We need to find a way to distinguish the distribution, maybe by adding another directory-level. But where to get this level-name from?

**Comment by htgoebel** [comment] 2015-12-06 10:18
May be solved by #1701. Todo: verify it.

**Comment by htgoebel** [comment] 2015-12-22 17:50
I revised this issue:

1. This issue is *not* about pkg_resources runtime magic! It is just about the way pygst is adding it's concrete, versioned implementation to sys.path. pygst never used pkg_resources, see [original commit of `pygst.py`](http://cgit.freedesktop.org/gstreamer/gst-python/commit/pygst.py.in?id=f3ec338b76d5568b4c66afc66b60950097a3549d). Only Giovanni said, this is about pkg_resources runtime magic in the last post of the mailinglist-thread (see first comment).

2. In addition, pygst never ever did support parallel installation of different versions. Check the [history of pygst.py](http://cgit.freedesktop.org/gstreamer/gst-python/log/pygst.py.in) (which is not that long).

3. The concrete, versioned implementation was always added to sys.path using a `.pth` file. This was removed when pygst switched to using `gi` (glib introspection), see [this commit](http://cgit.freedesktop.org/gstreamer/gst-python/commit/Makefile.am?id=a4b7a67f84766be7f793c3da06f95b53da73433e)

4. There already is a `hook-gst._gst.py` (see issue #725) which is triggered when the usual pattern (see comments above) is used.

**Conclusion:** @fhoech This never ever has been a real issue. It's just been a tempest in a teapot (Sturm im Wasserglas).  Argl!

Closing as invalid.

**Closed by htgoebel** 2015-12-22 17:50 UTC
Labels: @low, feature, PY3, verify

**Comment by bjones1** [comment] 2015-12-22 17:55
Wow. I'm impressed by the digging to did to untangle this knot. Well done!

**Comment by xdesai** [comment] 2018-06-04 17:57
I know this is an ancient issue, but I came here from bullet 2 onhttps://github.com/pyinstaller/pyinstaller/wiki/FAQ#misc

I see this task is marked as closed invalid. Does that mean that PyInstaller does not have issues with pkg_resources like the wiki suggests?
