### ISSUE TITLE
PySide2 5.15 hook fails to import shiboken2 dll

### ISSUE THREAD

**Issue by provinzio** [pyinstaller/pyinstaller#4913] opened 2020-06-02 09:39 UTC
## Description of the issue

I updated my package `PySide2` from 4.15.2.1 to 5.15.

I do not have any problems starting the frozen software on my computer, but my clients recieved `Failed to start __main__.py` with the error `ImportError: DLL load failed while importing shiboken2: The specified module was not found.`

I patched back to PySide2 4.15.2.1 to avoid the error and have not debugged this further so far.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.8.2
* Platform: Windows (german language setting)

### Stacktrace / full error message

Here is the log from a powershell startup.

```
.\Program.exe : PySide2/__init__.py: Unable to import shiboken2 from 
C:\Users\USERNAME\AppData\Local\Temp\_MEI75682\base_library.zip, C:\Users\USERNAME\AppData\Local\Temp\_MEI75682
In Zeile:1 Zeichen:1
+ .\Program.exe 2>&1 | tee cmdlog.txt
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (PySide2/__init_...\Temp\_MEI75682:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
    import my_program.config.log  # pylint: disable=unused-import
  File "d:\workspace\my_program\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "my_program\config\log.py", line 21, in <module>
  File "d:\workspace\my_program\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "my_program\utility\explorer.py", line 11, in <module>
  File "d:\workspace\my_program\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "lib\site-packages\PySide2\__init__.py", line 88, in <module>
  File "lib\site-packages\PySide2\__init__.py", line 54, in _setupQtDirectories
  File "d:\workspace\my_program\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "lib\site-packages\shiboken2\__init__.py", line 27, in <module>
ImportError: DLL load failed while importing shiboken2: Das angegebene Modul wurde nicht gefunden.
```

**Comment by alexdelorenzo** [comment] 2020-06-09 22:48
Latest PySide2/Shiboken2 on PyPI don't have Qt statically compiled in, the last version that does is `PySide2==5.14.2`, that might be the source of your issue, or not.

**Comment by karolyi** [comment] 2020-06-16 16:03
It was my issue too. See the crosslinked issue above.

**Comment by bjonnh** [comment] 2020-07-17 22:07
I only have this problem with UPX=True.

I tried to exclude shiboken and MSVCP dlls from UPX, but it doesn't change anything.

**Comment by harry-jame-potter** [comment] 2020-08-27 13:15
I had the same issue and I don't know where is wrong.

**Comment by maicol07** [comment] 2020-09-04 14:54
Same issue...

**Comment by MikeBusuttil** [comment] 2020-12-02 18:25
Had the same issue, upgrading Python from 3.6 to 3.9 fixed it for me

**Comment by rokm** [comment] 2020-12-21 12:31
Hmm, I cannot reproduce the original issue. Neither with PyInstaller `3.6` nor with `develop`.

However, I do recall that during summer, I was also having issues with `PySide2` `5.15.0` due to a missing DLL. And, similarly, I cannot reproduce it anymore, even if I try to match the `PyInstaller` and `PySide2` version I was using back then (the `MSVCP140_1.DLL` that was causing issues in my case is properly collected now). 

So perhaps this was intermittent issue with PySide2 builds that are fixed now on their side?

Or, based on comment by @MikeBusuttil, this could be a mismatch between the version of `vcruntime140.dll` that we collect from python installation, and other VC runtime DLLs, which are collected from PySide2. And consequently the system-wide absence/presence of VC runtime DLLs on the target system...

@provinzio if you are still experiencing this issue, please provide updated details for the latest version of PyInstaller.

------------

The follow-up comments (@bjonnh, @maicol07) are using UPX, which the original report does not mention, so this may be a separate issue; because with UPX-related "corruption", I get 
```
ImportError: DLL load failed while importing shiboken2: The parameter is incorrect.
```

instead of

```
ImportError: DLL load failed while importing shiboken2: The specified module was not found.
```

(which I get if I intentionally remove, e.g., `vcruntime140_1.dll`, from non-UPX version)

Applying UPX on DLLs that have control flow guard enabled renders them unusable. In the case of PySide2, such DLLs are `MSVCP140.dll` and `VCRUNTIME140.dll`, which must be excluded. (Since #5382, this will be done automatically).

However, using UPX with PySide2/PyQt5 is still problematic, because compressing the Qt5 plugins seems to render them unusable as well (this time, [because compression changes the magic pattern that Qt plugin system is using to identify plugins](https://github.com/upx/upx/issues/107#issuecomment-377641179)).

So you'll still need to manually exclude all Qt5 plugins from UPX compression - perhaps we should come up with a way for hooks to specify that (some) DLLs should be excluded from UPX?

**Comment by rokm** [comment] 2021-02-02 13:11
I'm closing this as I cannot reproduce the problem (anymore) on any of my test configurations. 

If you're still experiencing this issue with the latest version of PyInstaller, please open a new issue with updated details.

**Closed by rokm** 2021-02-02 13:11 UTC
Labels: area:hooks, area:hooks/PySide
