### ISSUE TITLE
Pyinstaller creates executable with UAC when freezing 32bit python script from 32 bit python 3.7.2 on 64bit windows 10

### ISSUE THREAD

**Issue by utibeokodi** [pyinstaller/pyinstaller#4992] opened 2020-07-10 23:22 UTC
Pyinstaller creates executable with UAC when freezing 32bit python script from 32 bit python 3.7.2 on 64bit windows 10 even when --uac-admin is not used and when trying to disable the UAC using the spec file it doesn't work

**Comment by Legorooj** [comment] 2020-07-11 05:59
@utibeokodi this is theoretically impossible with the way PyInstaller is programmed. Can you provide a minimal reproducible example?

**Comment by utibeokodi** [comment] 2020-07-11 11:00
@legorooj to reproduce the problem download 32 bit python 3.7.2 on 64 bit windows 10, then freeze any python script  with --noconsole, --onefile

**Comment by Legorooj** [comment] 2020-07-13 02:41
@utibeokodi I'm unable to reproduce this using python 3.7.3 32-bit and PyInstaller 4.0dev on 64-bit Windows 10.

**Comment by utibeokodi** [comment] 2020-07-13 10:09
@Legorooj I got the problem with pyinstaller 3.6 the pypi version

**Comment by Legorooj** [comment] 2020-07-13 10:11
@utibeokodi please try the development version.

**Comment by utibeokodi** [comment] 2020-07-13 21:29
Okay I will, Please what is the link for the latest development version.

**Comment by utibeokodi** [comment] 2020-07-13 22:25
@Legorooj I just tried the latest dev version and it works.
Thanks a lot.

**Comment by utibeokodi** [comment] 2020-07-13 23:38
I tried it again on different python scripts named updater.py and windowsinstaller.py and it still creates the exe with UAC as before

**Comment by utibeokodi** [comment] 2020-07-13 23:49
@Legorooj  I have narrowed down the problem, pyinstaller automatically freezes any script that has "updater" or "installer" in its names, we need an option to disable this feature for users that don't want to freeze there installers to UAC mode

**Comment by Legorooj** [comment] 2020-07-13 23:53
@utibeokodi let me look into that... Thanks for narrowing the problem.

**Comment by utibeokodi** [comment] 2020-07-14 00:58
You are welcome, Thanks for the help

**Comment by Legorooj** [comment] 2020-07-14 07:04
@utibeokodi still unable to reproduce this with `installer.py`, `updater.py`, using `--onefile --windowed`. For the contents of the scripts I used:
```python
import tkinter
from tkinter import ttk

root = tkinter.Tk()

msg = ttk.Label(root, text='It\'s working just fine.')

msg.grid()

root.mainloop()

```

I'm going to ask if @bwoodsend or @bjones1 can reproduce this and if not, I'm going to have to close this until we have a second person get this same issue.

**Comment by bwoodsend** [comment] 2020-07-14 08:14
Likewise, it works no problem for me.

**Comment by bwoodsend** [comment] 2020-07-14 08:56
Apologies, I didn't read the whole thread. Using `installer` or `updater` in the name does cause it to prompt for Admin privileges on running. 

- Build `updater.py` to `updater.exe` - asks for UAC
- Renaming the `updater.exe` -> `up-dater.exe` - no UAC
- Build `hello.py` to `hello.exe` - no UAC
- Rename `hello.exe` to `hello-updater.exe` - UAC is back.

- `gcc -m32 -o hello.exe hello.c` - no UAC
- `gcc -m32 -o hello-updater.exe hello.c` - asks for UAC
- `i386-win32-tcc -o hello.exe hello.c` - asks for UAC
- `i386-win32-tcc -o hello-updater.exe hello.c` - asks for UAC

TCC is just another C compiler. The `-m32` for GCC means use 32-bit and `i386-win32-tcc` is a 32-bit compiler. So I'm fairly certain this is just a weird Windows thing and out of our control.

**Comment by utibeokodi** [comment] 2020-07-14 10:03
@bwoodsend That is probably true

**Comment by Legorooj** [comment] 2020-07-14 22:14
@utibeokodi I managed to find out something else which we can fix.

**Comment by Legorooj** [comment] 2020-07-14 22:16
@bwoodsend thanks for that - I couldn't (and can't) reproduce this for some reason, but I've figured out a way to "fix" this. Will commit a fix for people to try out on my fork and if it works I'll merge it into develop.

**Comment by Legorooj** [comment] 2020-07-15 08:15
Right. I've commited a fix in legorooj/pyinstaller@f30819d1526ecca. If you could try that out and see if it works that'd be great. (`pip install -U https://github.com/legorooj/pyinstaller/archive/fix-auto-admin.zip`)

The cause of this issue is that in Windows Vista UAC was added. Because manifests hadn't existed before that, UAC was programmed to assume that 32-bit executable files with no manifest were old, and it would run - now very old and inaccurate - heuristics on the file metadata to figure out if the executable needed admin permission to run. These heuristics included scanning for patterns in the filename. This bit wasn't particularly heuristic; it was just a plain old membership test. Words like `installer`, `updater`, and other names associated with files which would normally need administrator permissions to run. If the heuristics thought it needed admin priveledges, then the user would be prompted as above.

I hope I've fixed this by setting a manifest key called `requestedExecutionLevel` to `asInvoked` whenever not building with `--uac-admin`, and caused the manifest to be embedded in the onefile executable if running 32-bit python.

**Comment by bwoodsend** [comment] 2020-07-15 10:07
That didn't change it but I've found something that did. [This answer](https://superuser.com/a/369694) outlines the issue. UAC escalation is can be defined in the manifest but defaults to the keyword based approach we're seeing. [This](https://archive.fo/H7kuL#selection-1089.1-1089.8) shows how to specify *requires UAC* in the manifest but obviously we want the opposite. I've manually edited my manifest to look like below. The magic is happening in the `<ms_asmv2:trustInfo ... >` block at the bottom.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="updater" processorArchitecture="x86" type="win32" version="1.0.0.0"/>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity language="*" name="Microsoft.Windows.Common-Controls" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" type="win32" version="6.0.0.0"/>
      <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"/>
    </dependentAssembly>
  </dependency>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
  <ms_asmv2:trustInfo xmlns:ms_asmv2="urn:schemas-microsoft-com:asm.v2">
    <ms_asmv2:security>
      <ms_asmv2:requestedPrivileges>
        <ms_asmv2:requestedExecutionLevel
          level="asInvoker"
          uiAccess="false"/>
        </ms_asmv2:requestedPrivileges>
       </ms_asmv2:security>
  </ms_asmv2:trustInfo>
</assembly>
```

I'm not sure what the `ms_asmv2:` prefixes are about. I tried stripping them to look like below and it still works without UAC. 

```
...
  <trustInfo xmlns:ms_asmv2="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel
          level="asInvoker"
          uiAccess="false"/>
        </requestedPrivileges>
       </security>
  </trustInfo>
...
```

@utibeokodi Could you try both as well and see what happens if you do them?

**Comment by utibeokodi** [comment] 2020-07-15 11:42
@bwoodsend @Legorooj I will try them out

**Comment by Legorooj** [comment] 2020-07-16 08:35
Whoops had the fix wrong. Could you try Legorooj/pyinstaller@aab37caf1f instead? I had the name as `asInvoked` first commit it should have been `asInvoker`.

**Comment by bwoodsend** [comment] 2020-07-16 14:31
@Legorooj That's sorted it.

**Closed** 2020-07-17 00:21 UTC
Labels: solution:works for me, state:need info, state:verify

**Comment by htgoebel** [comment] 2020-07-19 09:34
Huj, this was a tricky one :-) Thnaks for fixing
