### ISSUE TITLE
pyinstaller Error: Invalid hidden import numpy.pyinstaller.hook-numpy 

### ISSUE THREAD

**Issue by arcontechnologies** [pyinstaller/pyinstaller#8614] opened 2024-06-22 19:22 UTC
## Description of the issue
When running pyinstaller at certain point it raises an error :
pyinstaller Error: Invalid hidden import numpy.pyinstaller.hook-numpy 
this occur with the versions :

```
pyinstaller==6.8.0
pyinstaller-hooks-contrib==2024.7
```

When downgrading to versions :

```
pyinstaller==6.7.0
pyinstaller-hooks-contrib==2024.6
```

there error disappear. 

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.8.0```
* Version of Python:  `3.11`
* Platform: `Windows 11`
* How you installed Python: `pyenv`
* Did you also try this on another platform? Does it work there?
`No`

**Comment by rokm** [comment] 2024-06-22 19:29
In a sense, this is a duplicate of https://github.com/pyinstaller/pyinstaller/issues/8591, which has been taken care of by https://github.com/pyinstaller/pyinstaller/pull/8601.

But `numpy._pyinstaller.hook-numpy` should not be collected in the first place, unless you are explicitly collecting all `numpy` modules via `collect_submodules` or `collect_all`. Is that the case?

**Comment by arcontechnologies** [comment] 2024-06-22 22:31
Indeed, I'm using collect_all.

**Comment by rokm** [comment] 2024-06-22 22:38
> Indeed, I'm using collect_all.

Then that explains why `numpy._pyinstaller.hook-numpy` is being collected. 

Be aware that since the hook uses PyInstaller's hook utility functions, this pulls "main" `PyInstaller` code (i.e., the build-side code) into your frozen application, and since this code is licensed under GPLv2, your frozen application also becomes subject to GPLv2. (That's assuming that you aren't explicitly excluding PyInstaller code via `--exclude PyInstaller`).

**Comment by arcontechnologies** [comment] 2024-06-23 08:11
You're right. I didn't exclude it. But (maybe is somewhere in docs), I'm assuming that I have to "collect_all" should contains only those present in the requirements.txt and excluding for instance those that aren't need to run my app.
But what about hidden_imports : Because where the only way to get my app running was to put everything (pip freeze list) and then with try/error remove unnecessaries. 
What is the best way to handle this (I'm newbie) ? Maybe the way I'm doing it is wrong ?

**Comment by rokm** [comment] 2024-06-23 10:13
You should not be using `collect_all` at all, unless you fully understand what it actually does. 

> But what about hidden_imports : Because where the only way to get my app running was to put everything (pip freeze list) and then with try/error remove unnecessaries.

You keep adding missing modules to hidden imports, until you've covered them all.

Of course, you can also spam `collect_submodules` (or even worse, `collect_all`) for everything and call it a day, but then don't be surprised if you end up with bloated frozen application (especially if you aren't building in a minimal virtual environment).

But at the very least, you should avoid doing `collect_submodules` / `collect_all` for packages that already have hooks, unless you have a good reason to do so; since those hooks are usually more fine-grained. Such as is the case with the existing `numpy` hook (unless you run into problems with `numpy.f2py` or `numpy.distutils`, as discussed in https://github.com/orgs/pyinstaller/discussions/8613).

**Closed as not planned by rokm** 2024-06-23 10:13 UTC
Labels: triage
