### ISSUE TITLE
Crash during bundling related to PYC header manipulation

### ISSUE THREAD

**Issue by kkava** [pyinstaller/pyinstaller#4295] opened 2019-06-30 18:41 UTC
Summary: Crash occurs while bundling on Windows 10 due to PYC header fudging code:
https://github.com/pyinstaller/pyinstaller/blob/5d872d3ee5cc4d963dcf695ac6638bc9b974a2ff/PyInstaller/building/utils.py#L691

Sources:
[Synk.zip](https://github.com/pyinstaller/pyinstaller/files/3343202/Synk.zip)

C:\Dev\Synk>pyinstaller Synk.py -F --log-level DEBUG > out.txt
38 INFO: PyInstaller: 3.5.dev0+5d872d3ee
38 INFO: Python: 3.7.0a2
39 INFO: Platform: Windows-10-10.0.17763-SP0
41 INFO: wrote C:\Dev\Synk\Synk.spec
41 DEBUG: Testing for UPX ...
42 INFO: UPX is not available.
43 DEBUG: script: C:\Dev\Synk\Synk.py
43 INFO: Extending PYTHONPATH with paths
['C:\\Dev\\Synk', 'C:\\Dev\\Synk']
43 INFO: checking Analysis
55 INFO: checking PYZ
64 INFO: checking PKG
64 INFO: Building PKG because PKG-00.toc is non existent
65 INFO: Building PKG (CArchive) PKG-00.pkg
202 WARNING: One binary added with two internal names.
202 WARNING: ('libGLESv2.dll',
 'C:\\python\\python37-64\\lib\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')
203 WARNING: was placed previously at
203 WARNING: ('PyQt5\\Qt\\bin\\libGLESv2.dll',
 'C:\\python\\python37-64\\lib\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')
Traceback (most recent call last):
  File "c:\python\python37-64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python37-64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python\python37-64\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\python\python37-64\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python\python37-64\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python\python37-64\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python\python37-64\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Dev\Synk\Synk.spec", line 33, in <module>
    console=True )
  File "c:\python\python37-64\lib\site-packages\PyInstaller\building\api.py", line 435, in __init__
    upx_exclude=self.upx_exclude
  File "c:\python\python37-64\lib\site-packages\PyInstaller\building\api.py", line 197, in __init__
    self.__postinit__()
  File "c:\python\python37-64\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\python\python37-64\lib\site-packages\PyInstaller\building\api.py", line 284, in assemble
    pylib_name=pylib_name)
  File "c:\python\python37-64\lib\site-packages\PyInstaller\archive\writers.py", line 334, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "c:\python\python37-64\lib\site-packages\PyInstaller\archive\writers.py", line 61, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "c:\python\python37-64\lib\site-packages\PyInstaller\archive\writers.py", line 86, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "c:\python\python37-64\lib\site-packages\PyInstaller\archive\writers.py", line 406, in add
    buf = fake_pyc_timestamp(buf)
  File "c:\python\python37-64\lib\site-packages\PyInstaller\building\utils.py", line 691, in fake_pyc_timestamp
    buf[4:8] = struct.pack(">I", flags ^ 2)
TypeError: 'bytes' object does not support item assignment

C:\Dev\Synk>
C:\Dev\Synk>python --version
Python 3.7.0a2
C:\Dev\Synk>pip show pyinstaller
Name: PyInstaller
Version: 3.5.dev0+5d872d3ee
Summary: PyInstaller bundles a Python application and all its dependencies into a single package.
Home-page: http://www.pyinstaller.org
Author: Giovanni Bajo, Hartmut Goebel, David Vierra, David Cortesi, Martin Zibricky
Author-email: pyinstaller@googlegroups.com
License: GPL license with a special exception which allows to use PyInstaller to build and distribute non-free programs (including commercial ones)
Location: c:\python\python37-64\lib\site-packages
Requires: pywin32-ctypes, altgraph, pefile, setuptools
Required-by:

**Comment by htgoebel** [comment] 2019-08-07 09:52
Thanks for reporting. I'm curious this error did not occur earlier. Looks like our test-quite doe not cover enough code.

**Comment by htgoebel** [comment] 2019-08-07 13:43
I checked and this relevant branch is covered by the test-suite.
I've just seen this:
>  Python 3.7.0a2

Please use an actual Python release, not a alpha version.

Since I assume the alphversion is the cause, I'm closing this as invalid. Please report if this happens with a actual release, too.

**Closed by htgoebel** 2019-08-07 13:43 UTC

**Comment by kkava** [comment] 2019-08-08 17:05
Thank you, it works with Python v3.7.4. I did not realize I had an alpha version installed.
