### ISSUE TITLE
Grabbing the GUI executable

### ISSUE THREAD

**Issue by jeffgroversr** [pyinstaller/pyinstaller#2886] opened 2017-09-29 19:40 UTC
Once I install PyInstaller (windows 32/python 3.6) how do I grab the GUI executable to launch the GUI>

**Comment by nejch** [comment] 2017-10-01 18:46
Do you mean you have your own GUI application/script you want to package with PyInstaller?
You can read the official documentation [here](https://pyinstaller.readthedocs.io/en/stable/usage.html).

In the command prompt, navigate to the folder where your script is located, and type (assuming your script is `myscript.py`):
`pyinstaller myscript.py`

If your script has a GUI, you will likely want to use the `--windowed` option, e.g.:
`pyinstaller --windowed myscript.py`

The executable will be in the `dist` subfolder in the script folder, e.g. `dist\myscript\myscript.exe` (or `dist\myscript.exe` if using the `--onefile` option).

PyInstaller itself does not currently use a GUI afaik, if that's what you meant.

**Comment by htgoebel** [comment] 2017-12-02 15:38
No clarification about what the issue is. Closing.

**Closed by htgoebel** 2017-12-02 15:38 UTC
Labels: need info, support
