### ISSUE TITLE
DllDirectory is not accessible at runtime

### ISSUE THREAD

**Issue by alongere** [pyinstaller/pyinstaller#7594] opened 2023-04-25 12:44 UTC
## Description of the issue

At execution, the standard DllDirectory is not accessible anymore. It seems to be changed for the tmp dir into which the app is extracted. Subprocess launch by the app don't have access to the standard DllDirectory neither.
We are mandatory to use absolute path instead of relative path (from our current working dir) as we normally do.

## Possible root of the issue

Line 257 from pyi_main.c the function "SetDllDirectoryW()" is used. I thinks this is the root of the issue. Using AddDllDirectory() instead should solve the issue.
Maybe SetDllDirectoryW is still use because pyinstaller still supports windows xp (in which AddDllDirectory is not implemented) but in this case maybe a simple if statement can do the job.

https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectoryw
https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.7.0``` *Issue is still here in the main.*
* Version of Python: 3.8.8
* Platform: Windows 11 / Windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? **Yes.** Does it work there? **Same issue.**

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

**Comment by rokm** [comment] 2023-04-25 19:11
This looks like a duplicate of #3795, and if you're affected, you can try undoing the effect of `SetDllDirectoryW` by calling equivalent of `SetDllDirectoryW(NULL)` via `ctypes`, as suggested in https://github.com/pyinstaller/pyinstaller/issues/3795#issuecomment-449746134 (and documented in [subprocess wiki page](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess#windows-dll-loading-order)).

**Closed as not planned** 2023-09-11 20:36 UTC
Labels: triage
