### ISSUE TITLE
Unable to load any of {libcudnn_engines_precompiled.so.9.1.0, libcudnn_engines_precompiled.so.9.1, libcudnn_engines_precompiled.so.9, libcudnn_engines_precompiled.so}

### ISSUE THREAD

**Issue by programmeddeath1** [pyinstaller/pyinstaller#8758] opened 2024-08-25 10:16 UTC
When I am compiling my pyinstaller app and running the camera stream through a luxonis camera it fails with 

```
main.py:3640: DeprecationWarning: LEFT is deprecated, use CAM_B or address camera by name  instead.
  monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
main.py:3642: DeprecationWarning: RIGHT is deprecated, use CAM_C or address camera by name  instead.
  monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)
Unable to load any of {libcudnn_engines_precompiled.so.9.1.0, libcudnn_engines_precompiled.so.9.1, libcudnn_engines_precompiled.so.9, libcudnn_engines_precompiled.so}
Error with luxonis run - CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_NOT_INITIALIZED
Killing Existing
```
When i try with a normal camera it fails as below - 

```
  File "main.py", line 4315, in run
    detections = self.model.track(frame,persist=True,tracker=f'{process_config_path}botsort.yaml',conf=CONFIDENCE_THRESHOLD,classes=SEND_CLASSES,device=0,verbose=False)[0]   
  File "ultralytics/engine/model.py", line 610, in track
  File "ultralytics/engine/model.py", line 563, in predict
  File "ultralytics/engine/predictor.py", line 168, in __call__
  File "torch/utils/_contextlib.py", line 36, in generator_context
  File "ultralytics/engine/predictor.py", line 234, in stream_inference
  File "ultralytics/nn/autobackend.py", line 639, in warmup
  File "ultralytics/nn/autobackend.py", line 456, in forward
  File "torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
  File "torch/nn/modules/module.py", line 1562, in _call_impl
  File "ultralytics/nn/tasks.py", line 102, in forward
  File "ultralytics/nn/tasks.py", line 120, in predict
  File "ultralytics/nn/tasks.py", line 141, in _predict_once
  File "torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
  File "torch/nn/modules/module.py", line 1562, in _call_impl
  File "ultralytics/nn/modules/conv.py", line 54, in forward_fuse
  File "torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
  File "torch/nn/modules/module.py", line 1562, in _call_impl
  File "torch/nn/modules/conv.py", line 458, in forward
  File "torch/nn/modules/conv.py", line 454, in _conv_forward
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_NOT_INITIALIZED
Stack trace (most recent call last) in thread 3467:
#11   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#10   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f663312684f, in 
#9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f6633094ac2, in 
#8    Object "/home/greenpi/app/greenox-delta-gui/dist/blueoyster/_internal/libQt5Core.so.5", at 0x7f6630cccc88, in 
#7    Object "/home/greenpi/app/greenox-delta-gui/dist/blueoyster/_internal/libQt5Core.so.5", at 0x7f6630ccac4d, in QThread::started(QThread::QPrivateSignal)
#6    Object "/home/greenpi/app/greenox-delta-gui/dist/blueoyster/_internal/libQt5Core.so.5", at 0x7f6630ef14e4, in 
#5    Object "/home/greenpi/app/greenox-delta-gui/dist/blueoyster/_internal/PyQt5/QtCore.abi3.so", at 0x7f663141b5ec, in 
#4    Object "/home/greenpi/app/greenox-delta-gui/dist/blueoyster/_internal/PyQt5/QtCore.abi3.so", at 0x7f66312c1416, in 
#3    Object "/home/greenpi/app/greenox-delta-gui/dist/blueoyster/_internal/libQt5Core.so.5", at 0x7f6630c90ba2, in QMessageLogger::fatal(char const*, ...) const
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f66330287f2, in abort
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f6633042475, in raise
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f66330969fc, in pthread_kill
Aborted (Signal sent by tkill() 2844 1000)
Aborted (core dumped)
```
The spec file is 
```
# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs, copy_metadata

# Add ROS paths
ros_paths = [

    '/home/greenpi/noetic_ws/devel_isolated/lib/python3/dist-packages',
    '/home/greenpi/noetic_ws/install_isolated/lib/python3/dist-packages',
    '/home/greenpi/app/greenox-delta-planner/devel/lib/python3/dist-packages',
]

# Extend the Python path
#sys.path.extend(ros_paths)

# Collect data files for pygraphviz
datas = collect_data_files('torch')
datas = collect_data_files('pygraphviz')
datas = collect_data_files('ultralytics')
#datas += collect_data_files('boxmot')
#datas += collect_data_files('matplotlib', subdir='mpl-data')

# Additional binaries for Graphviz
graphviz_binaries = [
    ('/usr/bin/neato', 'graphviz/bin'),
    ('/usr/bin/dot', 'graphviz/bin'),
    ('/usr/bin/fdp', 'graphviz/bin'),
    ('/usr/bin/sfdp', 'graphviz/bin'),
    ('/usr/bin/twopi', 'graphviz/bin'),
    ('/usr/bin/circo', 'graphviz/bin'),
]

graphviz_binaries += collect_dynamic_libs('torch')
#binaries.extend(graphviz_binaries)

# Collect metadata for python imports
datas += copy_metadata('torch')
datas += copy_metadata('norfair')
#datas += copy_metadata('boxmot')
datas += copy_metadata('depthai')
#datas += copy_metadata('matplotlib')
datas += copy_metadata('ultralytics')

# Include additional data files
datas += [
    ('config/delta_robot.rviz', 'config'),
    ('config/delta_robot.rviz', 'config'),
    ('images/camera.png', 'images'),
    ('images/connections.png', 'images'),
    ('images/control-centre.png', 'images'),
    ('images/green-light.png', 'images'),
    ('images/home.png', 'images'),
    ('images/red-light.png', 'images'),
    ('images/screen3.png', 'images'),
    ('images/settings.png', 'images'),
    ('images/load_spinner.gif','images'),
    ('images/greenox_logo_web.png','images'),
    ('lib/libmk_api.so', 'lib'),
    ('lib/librga.so', 'lib'),
    ('lib/librknnrt.so', 'lib'),
    ('lib/librockchip_mpp.so', 'lib'),
    ('libraries/calc.py', 'libraries'),
    ('libraries/__init__.py', 'libraries'),
    ('model/bus.jpg', 'model'),
    ('model/coco_80_labels_list.txt', 'model'),
    ('model/RK3588/greenox_v5_small_640.json', 'model/RK3588'),
    ('model/RK3588/greenox_v5_small_640.rknn', 'model/RK3588'),
    ('models/greenox_generic.pt', 'models'),
    ('static/one.ui', 'static'),
    ('static/two.ui', 'static'),
    ('static/three.ui', 'static'),
    ('static/four.ui', 'static'),
    ('executor.py', '.'),
    ('rknn_yolov5_demo', '.'),
    ('rknn_yolov5_demo_dynamichome', '.'),
    ('runmodel_server.sh', '.'),
    ('image.jpg', '.'),
    ('testing/kitkat_trid_video_stream.mp4', 'testing'),
    ('config/workspace.json', 'config'),
    ('config/botsort.yaml', 'config'),
    ('config/camera_detection.yaml', 'config'),
    ('config/config.myviz', 'config'),
    ('config/config.yaml', 'config'),
    ('config/log_config.yaml', 'config'),
    ('config/speed_limits.csv', 'config'),
]


a = Analysis(
    ['main.py'],
    pathex=ros_paths + sys.path,
    binaries=graphviz_binaries,
    datas=datas,
    hiddenimports=[
        'roslib',
        'rospy',
        'std_msgs',
        'geometry_msgs',
        'sensor_msgs',
        'norfair',
#        'boxmot',
        'ultralytics',
        'torch',
        #'matplotlib',  # Ensure matplotlib is included
        #'mpl_toolkits.mplot3d'  # Ensure mpl_toolkits.mplot3d is included
    ],
    #hookspath=['.'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    #excludes=['PySide2'],
    excludes=['PySide2', 'lz4'],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='blueoyster',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='blueoyster',
)
```
The app runs normally if I run it as python3 main.py. Is there anything additional that needs to be added to enable the CUDA engine to work or for the ap to use the CUDA runtime?

**Comment by rokm** [comment] 2024-08-25 10:37
> Is there anything additional that needs to be added to enable the CUDA engine to work or for the ap to use the CUDA runtime?

> `Unable to load any of {libcudnn_engines_precompiled.so.9.1.0, libcudnn_engines_precompiled.so.9.1, libcudnn_engines_precompiled.so.9, libcudnn_engines_precompiled.so}`

Is `libcudnn_engines_precompiled.so.9` file collected (should be in `dist/<name>/_internal/nvidia/cudnn/lib`)?

**Comment by ThomasScottWhite** [comment] 2024-08-25 21:09
I am currently having a similar problem to this, libcudnn_engines_precompiled.so.9 is collected

**Comment by rokm** [comment] 2024-08-25 21:13
> I am currently having a similar problem to this, libcudnn_engines_precompiled.so.9 is collected

Can you provide a minimal reproducer?

**Comment by rokm** [comment] 2024-08-25 21:14
> > I am currently having a similar problem to this, libcudnn_engines_precompiled.so.9 is collected
> 
> Can you provide a minimal reproducer?

But before that, maybe go into top-level application directory `dist/<name>/_internal`, and remove all symlinks that point to `dist/<name>/_internal/nvidia/*/lib/*`, and see if that helps.

**Comment by NevermindNilas** [comment] 2024-08-25 21:37
I also reproduced this error, I can confirm that at least `libcudnn_engines_precompiled.so.9` is present in the _internal folder.

In my own situation I was using pytorch 2.4.0 + torchvision 1.19.0 cu124.
A downgrade to pytorch 2.3.1, torchvision 1.18.1 and cu121 has for now fixed it so there's that.

>But before that, maybe go into top-level application directory dist/<name>/_internal, and remove all symlinks that point to dist/<name>/_internal/nvidia/*/lib/*, and see if that helps.

would something like this work?

`find . -type l -lname '*/nvidia/*/lib/*' -exec rm {} \;`

**Comment by rokm** [comment] 2024-08-26 09:43
I think I've managed to reproduce this with basic `ultralytics` YOLO example. 

It seems that symlinks are indeed the problem (because `libcudnn_engines_precompiled.so.*` is searched for in locations relative to `libcudnn_graph.so.9`, without fully resolving its path). So removing the `libcudnn_graph.so.9` symlink from `_internal` directory should do the trick as a temporary work-around.

Manually symlinking all other cu* libs (i.e., the ones that are dynamically loaded) to `_internal` directory might also work, but I think the proper solution here is to add a mechanism for hooks to tell PyInstaller's binary dependency analysis to not generate symlinks for certain lib files / locations.

**Comment by programmeddeath1** [comment] 2024-08-26 16:59
Removing the symlink for libcudnn_graph.so.9 from _internal works!

Also it works for torch 2.3.1 with cuda 12.1.

And latest torch with cuda 11.8.

**Comment by rokm** [comment] 2024-08-28 17:39
This should work out of the box with next release of both PyInstaller and pyinstaller-hooks-contrib (which will suppress the creation of problematic symbolic links).

**Closed as completed by rokm** 2024-08-28 17:39 UTC
Labels: bug

**Comment by paulleem** [comment] 2024-09-03 16:55
> I think I've managed to reproduce this with basic `ultralytics` YOLO example.
> 
> It seems that symlinks are indeed the problem (because `libcudnn_engines_precompiled.so.*` is searched for in locations relative to `libcudnn_graph.so.9`, without fully resolving its path). So removing the `libcudnn_graph.so.9` symlink from `_internal` directory should do the trick as a temporary work-around.
> 
> Manually symlinking all other cu* libs (i.e., the ones that are dynamically loaded) to `_internal` directory might also work, but I think the proper solution here is to add a mechanism for hooks to tell PyInstaller's binary dependency analysis to not generate symlinks for certain lib files / locations.

How do I 'remove a symlink'? I don't quite get the idea of what symlinks are at the first place btw....
Oh, I also use the terminal flag method, not the .spec way.

**Comment by rokm** [comment] 2024-09-04 09:55
> How do I 'remove a symlink'? 

Same way as you would remove a file. Go into application's top level directory (assuming you are using onedir build) and remove the `libcudnn_graph.so.9` in there. 

If you happen to be using onefile, then you can programmatically remove `os.path.join(sys._MEIPASS, libcudnn_graph.so.9)` at the start of your program. 

Or switch to using .spec and remove `libcudnn_graph.so.9` entry from `datas` list before it is passed to `EXE`/`COLLECT`.

Or wait for next release of `PyInstaller` and `pyinstaller-hooks-contrib`.

**Comment by paulleem** [comment] 2024-09-04 21:24
> > How do I 'remove a symlink'?
> 
> Same way as you would remove a file. Go into application's top level directory (assuming you are using onedir build) and remove the `libcudnn_graph.so.9` in there.
> 
> If you happen to be using onefile, then you can programmatically remove `os.path.join(sys._MEIPASS, libcudnn_graph.so.9)` at the start of your program.
> 
> Or switch to using .spec and remove `libcudnn_graph.so.9` entry from `datas` list before it is passed to `EXE`/`COLLECT`.
> 
> Or wait for next release of `PyInstaller` and `pyinstaller-hooks-contrib`.

You saved my day! Thanks!
