### ISSUE TITLE
include winpcap DLLd

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4370] opened 2019-08-11 09:06 UTC
I'm trying to build a windows application using [pcapy](https://pypi.org/project/pcapy/) module and it needs the [winpcap](https://www.winpcap.org/) DLLs to execute.

When running on the target machine that `winpcap` is not installed i'm getting this error:
```ImportError: DLL load failed: The specified module could not be found.```

Is it possible to tell PyInstaller to include the `winpcap` DLLs without installing it on the target machine?

I can add a hook if needed.

PyInstaller: 3.5
Python: 2.7.16 / 3.7.4
OS: Windows

**Comment by htgoebel** [comment] 2019-08-11 16:47
Please see pyinstaller/pyinstaller-hooks-contrib#512

Duplicate of pyinstaller/pyinstaller-hooks-contrib#512

**Closed by htgoebel** 2019-08-11 16:47 UTC
