### ISSUE TITLE
Unable to install pyinstaller==4.2 on python 3.9.7 ModuleNotFoundError: 'PyInstaller' is not a package

### ISSUE THREAD

**Issue by marcinjrojek** [pyinstaller/pyinstaller#6723] opened 2022-04-04 19:17 UTC
Unable to install pyinstaller==4.3 using `python 3.9.7`

Platform: `Windows 10 Home US`
Python installed from python.org/downloads (python-3.9.7-amd64.exe)
I did not try on other platform

```
pip 21.3.1
setuptools 60.2.0
wheel 0.37.1
```
### Stacktrace / full error message
```

Collecting pyinstaller==4.3
  Using cached pyinstaller-4.3.tar.gz (3.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\UserA\PycharmProjects\projectA\venv\Scripts\python.exe' 'C:\Users\UserA\PycharmProjects\projectA\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\UserA\AppData\Local\Temp\tmpowt415hx'
       cwd: C:\Users\UserA\AppData\Local\Temp\pip-install-1xio3m3q\pyinstaller_30263fc9f3fc412a90577d9479d6721e
  Complete output (44 lines):
  Traceback (most recent call last):
    File "C:\Users\UserA\PycharmProjects\projectA\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Users\UserA\PycharmProjects\projectA\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\UserA\PycharmProjects\projectA\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 75, in <module>
      setup(
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 122, in setup
      dist.parse_config_files()
    File "C:\Users\UserA\PycharmProjects\projectA\venv\lib\site-packages\_virtualenv.py", line 21, in parse_config_files
      result = old_parse_config_files(self, *args, **kwargs)
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\dist.py", line 850, in parse_config_files
      setupcfg.parse_configuration(
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 167, in parse_configuration
      meta.parse()
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 446, in parse
      section_parser_method(section_options)
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in parse_section
      self[name] = value
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 238, in __setitem__
      value = parser(value)
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 552, in _parse_version
      return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 372, in _parse_attr
      return expand.read_attr(attr_desc, package_dir, root_dir)
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
      module = _load_spec(spec, module_name)
    File "C:\Users\UserA\AppData\Local\Temp\pip-build-env-a_xz7bq9\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
      spec.loader.exec_module(module)  # type: ignore
    File "<frozen importlib._bootstrap_external>", line 850, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "C:\Users\UserA\AppData\Local\Temp\pip-install-1xio3m3q\pyinstaller_30263fc9f3fc412a90577d9479d6721e\PyInstaller.py", line 16, in <module>
      from PyInstaller.__main__ import run
  ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b6/27/a006fcadba0db30819c968eb8decb4937cda398ca7a44d8874172cdc228a/pyinstaller-4.3.tar.gz#sha256=5ecf8bbc230d7298a796e52bb745b95eee12878d141f1645612c99246ecd23f2 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\Users\UserA\PycharmProjects\projectA\venv\Scripts\python.exe' 'C:\Users\UserA\PycharmProjects\projectA\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\UserA\AppData\Local\Temp\tmpowt415hx' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyinstaller==4.3 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.9, 4.10)
ERROR: No matching distribution found for pyinstaller==4.3
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\UserA\PycharmProjects\projectA\venv\Scripts\python.exe -m pip install --upgrade pip' command.

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b6/27/a006fcadba0db30819c968eb8decb4937cda398ca7a44d8874172cdc228a/pyinstaller-4.3.tar.gz#sha256=5ecf8bbc230d7298a796e52bb745b95eee12878d141f1645612c99246ecd23f2 (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\Users\UserA\PycharmProjects\a\venv\Scripts\python.exe' 'C:\Users\UserA\PycharmProjects\a\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\UserA\AppData\Local\Temp\tmpowt415hx' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyinstaller==4.3 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.9, 4.10)
ERROR: No matching distribution found for pyinstaller==4.3
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\UserA\PycharmProjects\a\venv\Scripts\python.exe -m pip install --upgrade pip' command.

```

**Comment by bwoodsend** [comment] 2022-04-04 20:25
Duplicate of #6704

**Closed as completed by bwoodsend** 2022-04-04 20:25 UTC
Labels: solution:duplicate
