### ISSUE TITLE
WARNING:failed to remove temporary directory: C:\users\x\AppData\Local\Temp_NNNNN

### ISSUE THREAD

**Issue by scosman** [pyinstaller/pyinstaller#8866] opened 2024-11-06 17:20 UTC
## Description of the issue

The issue is an alert showing `WARNING:failed to remove temporary directory: C:\users\x\AppData\Local\Temp_NNNNN` when a Windows exe with a splash and one-file is exited.

This issue was previously [reportedly](https://github.com/pyinstaller/pyinstaller/issues/8701) and [fixed](https://github.com/pyinstaller/pyinstaller/pull/8733). 

However, I'm still seeing it in pyinstaller 6.11, which was supposed to have the fix according to the [changelog](https://pyinstaller.org/en/v6.11.0/CHANGES.html#id1).

The full build log is available [here](https://github.com/Kiln-AI/Kiln/actions/runs/11707325715/job/32606443543), showing the pyinstaller version is up to date. The generated exe is attached [here](https://github.com/Kiln-AI/Kiln/actions/runs/11707325715).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.0```
* Version of Python: 3.12
* Platform: Windows
* How you installed Python: Github `actions/setup-python@v5` @3.12
* Did you also try this on another platform? Does it work there?: Only repos on windows, but was always Windows only

The full build log is available [here](https://github.com/Kiln-AI/Kiln/actions/runs/11707325715/job/32606443543)

The generated exe is attached [here](https://github.com/Kiln-AI/Kiln/actions/runs/11707325715)

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ x ] start with clean installation
  * [ ] use the latest development version (used 6.11)
  * [ x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ x ] Package your program in **--onedir mode**
  * [ d ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

Let me know if you need minimal program, or if the linked repo with exact program is okay.

**Comment by bwoodsend** [comment] 2024-11-06 17:29
> when a Windows exe with a slash and one-file is exited.

What do you mean by with a slash?

**Comment by scosman** [comment] 2024-11-06 17:38
Splash, sorry. Updated

**Comment by rokm** [comment] 2024-11-06 17:40
> Splash, sorry. Updated

Does it work without splash?

Also, how do you shut down the linked executable without setting up a provider?

**Comment by bwoodsend** [comment] 2024-11-06 17:41
> Let me know if you need minimal program, or if the linked repo with exact program is okay.

It would certainly help. Particular it would be good if you can eliminate uv.

**Comment by rokm** [comment] 2024-11-06 17:42
If I kill the child process using Task Manager, the temporary directory ends up being removed without issues. So I suspect this is not related to splash screen.

**Comment by scosman** [comment] 2024-11-06 17:48
Yeah, I just mentioned splash as the last bug was related to splash. I can try without splash, and without UV. However I have UV setup to use system python (`uv venv --python 3.12 --python-preference only-system`) for a pretty typical build (not UV binaries).

I'm exiting by calling `destroy()` on the tk, which causes it's main loop to end, and python main to end.

**Comment by scosman** [comment] 2024-11-06 17:50
Oh, and I'm quitting via taskbar icon -> Quit (for how to trigger the process I mention above)

**Comment by rokm** [comment] 2024-11-06 17:52
> Oh, and I'm quitting via taskbar icon -> Quit (for how to trigger the process I mention above)

Thanks, I managed to overlook the taskbar icon.

**Comment by rokm** [comment] 2024-11-06 17:54
Hmm, so exiting via taskbar icon also seems to work OK on my test system.

Can you create a console-enabled build (i.e., without `--noconsole` or `--windowed` flag) and with added `--debug bootloader`. Then run the program from command prompt, and exit it as you would otherwise. If it fails to remove temporary directory, it will print names of offending files. Please paste the whole generated debug log, so we can see what's going on there.

**Comment by scosman** [comment] 2024-11-06 18:00
Interesting. I am running in VMWare -- should have mentioned sooner. 

That build with debug bootloader is running now: https://github.com/Kiln-AI/Kiln/actions/runs/11709230952

I'm still getting the error exiting from task manager FYI.

<img width="416" alt="Screenshot 2024-11-06 at 12 58 31 PM" src="https://github.com/user-attachments/assets/27596076-5e43-45d3-b979-334865d4c66f">

Also: Thank you for the super responsive help!

**Comment by scosman** [comment] 2024-11-06 18:10
Errors pretty in line with the alert [truncated, but many more errors of the same type]:

<img width="1062" alt="Screenshot 2024-11-06 at 1 09 32 PM" src="https://github.com/user-attachments/assets/18c0ce8c-5348-4cff-861f-8fea797493fb">

**Comment by rokm** [comment] 2024-11-06 18:12
Can you copy & paste the whole run log? From the program start to the last message?

**Comment by rokm** [comment] 2024-11-06 18:21
Maybe two more things:

1. If you take your original (windowed / noconsole) application, and when the "failed to remove temporary dialog" pops up, *do not* close it, but wait a bit (e.g., fifteen seconds), then open the indicated path in Windows Explorer, and try to remove the (remaining) files manually. Does that work - can you remove the files? (Keep the warning dialog open throughout all this).

2. What state is the application in when you exit it? Do you have any provider configured, or is this at the "Select provider" setup screen? (I.e., is locking perhaps triggered by something that happens past the setup stage and that's why I cannot reproduce it?).

**Comment by scosman** [comment] 2024-11-06 18:51
Log here: [log.txt](https://github.com/user-attachments/files/17651614/log.txt)

Case 1: deleting the path with the windowed app in error state. I manually removed the directory and it worked fine without any error and without any elevated permissions (I'm not a Windows person though, used `rm -r` in powershell).

Case 2: Same issue repos if I manually blow away app state and have a fresh install on the welcome screen. Remove ~/.kiln_ai to remove all user data.

**Comment by scosman** [comment] 2024-11-06 19:00
Other context: I'm running a FastAPI server in a thread. It properly shuts down on process end, but I'm wondering if there's a race, and it's still using TempDir when pyinstaller is trying to cleanup.

**Comment by rokm** [comment] 2024-11-06 19:02
Thanks! Based on the provided information, I think this is again a timing/race issue (similar to #8837) - for some reason someone (the OS?) is keeping the files locked after the application process exits and when the parent process is trying to perform cleanup. But it is definitely not the parent process (because otherwise you wouldn't be able to remove them manually); plus, we can see that in the second attempt (after we try to force-eject any bundled DLLs from the parent process, which turns out to be a no-op in this case), there are fewer problematic files (e.g., `charset_normalizer\md.cp312-win_amd64.pyd` is not an issue anymore).

I have a WIP branch that adds a retry loop (multiple attempts with 1-second delays in between): https://github.com/rokm/pyinstaller/tree/refs/heads/stress-testing

But if you want to test it, you need to recompile the bootloader. You could do this manually (checkout the repo, build bootloader, install PyInstaller from checkout - like we do in our CI pipelines; see [here](https://github.com/pyinstaller/pyinstaller/blob/34cc28539c7f79c5f5f2537ddee7a8218410d024/.github/workflows/ci.yml#L148-L162)). Or you can set `PYINSTALLER_COMPILE_BOOTLOADER` environment variable before running pip-install on the remote, e.g.:

```
set PYINSTALLER_COMPILE_BOOTLOADER=1
pip install https://github.com/rokm/pyinstaller/archive/refs/heads/stress-testing.zip
``` 

(assuming command prompt; PS has a different syntax for setting environment variables).

**Comment by scosman** [comment] 2024-11-06 19:37
With that package I'm still seeing errors in the log, and the folder remains.

Build [here](https://github.com/Kiln-AI/Kiln/actions/runs/11710469899/job/32616823939).

**Comment by rokm** [comment] 2024-11-06 19:38
Can you paste the full log again?

**Comment by scosman** [comment] 2024-11-06 19:40
Log: [log2.txt](https://github.com/user-attachments/files/17652197/log2.txt)

And [build log](https://github.com/Kiln-AI/Kiln/actions/runs/11710469899/job/32616823939)

Just making sure you saw earlier note that this is VMWare running windows?

**Comment by rokm** [comment] 2024-11-06 19:41
> Just making sure you saw earlier note that this is VMWare running windows?

Yeah. I run my test Windows 10 and 11 systems in VirtualBox; so virtualization might or might not be at play here.

**Comment by rokm** [comment] 2024-11-06 19:47
Hmm, that run-time log does not seem to include the extra verbosity from the WIP branch (seems to be the original bootloader for some reason).

**Comment by rokm** [comment] 2024-11-06 19:50
Can you try

```
pip uninstall pyinstaller
set PYINSTALLER_COMPILE_BOOTLOADER=1
pip install https://github.com/rokm/pyinstaller/archive/refs/heads/stress-testing.zip
```

(or ensure that pyinstaller is *not* installed prior to this step, i.e., remove it from dependencies).

**Comment by Chimiscuilo123** [comment] 2024-11-06 23:18
I just came for the same thing, I already did everything related and I still have the error

**Comment by scosman** [comment] 2024-11-07 00:32
That one worked!

Build [log](https://github.com/Kiln-AI/Kiln/actions/runs/11714120141)

Run log: [log3.txt](https://github.com/user-attachments/files/17654475/log3.txt)

```
[PYI-13160:DEBUG] LOADER: waiting 1000 milliseconds before trying to remove temporary directory again...
[PYI-13160:DEBUG] LOADER: trying to remove temporary directory (attempt 1 / 10)...
[PYI-13160:DEBUG] LOADER: removal succeeded.
[PYI-13160:DEBUG] LOADER: mitigation succeeded.
[PYI-13160:DEBUG] LOADER: temporary directory C:\Users\delro\AppData\Local\Temp\_MEI131602 was successfully removed.
[PYI-13160:DEBUG] LOADER: end of process reached!
```

**Comment by rokm** [comment] 2024-11-07 17:00
@scosman Thanks for testing and confirming that it works!

@Chimiscuilo123 Can you also check if using PyInstaller branch from my previous comment fixes the issue for you? If not, please post the run-time log of a console-enabled build with added `--debug bootloader` so we can see what files are affected in your case.

**Comment by akshah94** [comment] 2024-11-09 15:34
@rokm I'm facing the same error even after uninstalling and reinstalling pyinstaller from your branch as per your previous comment. I have attached the run log below.

Please let me know if there's anything I'm doing wrong or if there's any workaround. Thanks for the help

[run-log.txt](https://github.com/user-attachments/files/17688468/run-log.txt)

**Comment by rokm** [comment] 2024-11-09 15:39
@akshah94 You are still using the stock bootloader. Either you failed to really install my branch (you need to explicitly remove previous PyInstaller version, because their version numbers match), or you did not rebuild the bootloader. If you were using the modified bootloader, you would see "mitigation" appear in the run log, as is the case with `log3.txt` in https://github.com/pyinstaller/pyinstaller/issues/8866#issuecomment-2461080742.

**Closed as completed** 2024-11-10 12:46 UTC
Labels: triage

**Comment by akshah94** [comment] 2024-11-11 05:54
Okay I installed it again via the new release and it's working fine. Thanks @rokm
