### ISSUE TITLE
Mac: generated executable throws "Error loading Python lib" for any program

### ISSUE THREAD

**Issue by arosiclair** [pyinstaller/pyinstaller#5062] opened 2020-08-06 20:16 UTC
## Description of the issue
The generated Mac executable for any program even a basic basic "Hello, World" script does not execute correctly. Using --onedir, --onefile, and --noupx does not remedy this issue.

## Context information (for bug reports)

* Output of `pyinstaller --version`: **```PyInstaller: 4.0.dev0``` (same issue in 3.6 release)**
* Version of Python: **3.7.7**
* Platform:  **OS X Mojave (10.14.6)**
* Did you also try this on another platform? Does it work there? **Windows is working**
  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
**A bash script that will generate this issue:**
```
# make a test folder
rm -rf mac-test
mkdir mac-test
cd mac-test/

# create a virtual environment and install pyinstaller
python3 -m venv .venv
source .venv/bin/activate
python --version
pip --version
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
pyinstaller --version

# build a hello, mac program
echo "print('hello, mac')" > main.py
pyinstaller main.py --onedir --noupx

# run the executable
./dist/main/main
```

### Stacktrace / full error message

**The executable error:**
```
[9742] Error loading Python lib '/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python': dlopen: dlopen(/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python, 10): no suitable image found.  Did find:
        /Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python: code signature invalid for '/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python'
```

**The full log from the above script**
```
Python 3.7.7
pip 19.2.3 from /Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/pip (python 3.7)
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Using cached https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting macholib>=1.8; sys_platform == "darwin" (from pyinstaller==4.0.dev0)
  Using cached https://files.pythonhosted.org/packages/3c/e1/c12f8d6af5d745ce88f270aeb243cb2bd6d8186320e5122df87fded29e4e/macholib-1.14-py2.py3-none-any.whl
Collecting altgraph (from pyinstaller==4.0.dev0)
  Using cached https://files.pythonhosted.org/packages/ee/3d/bfca21174b162f6ce674953f1b7a640c1498357fa6184776029557c25399/altgraph-0.17-py2.py3-none-any.whl
Collecting pyinstaller-hooks-contrib>=2020.6 (from pyinstaller==4.0.dev0)
  Using cached https://files.pythonhosted.org/packages/28/47/ba60fc1e96e47391dc547f74b31daf28daa3ad3b8bfc3dedced5acbf48bd/pyinstaller_hooks_contrib-2020.6-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.venv/lib/python3.7/site-packages (from pyinstaller==4.0.dev0) (41.2.0)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... done
  Created wheel for pyinstaller: filename=pyinstaller-4.0.dev0-cp37-none-any.whl size=2812826 sha256=777fbddaf34fe73d053a1eca5b6e606e9f6e6310d5be0f451a57623f4c839f2b
  Stored in directory: /private/var/folders/mm/lv7xny1n2nq8f2jw_8zz58qmkkgczp/T/pip-ephem-wheel-cache-10aawko1/wheels/1e/5b/0a/b7b241e8886f8f6d4c41177dd91cdb275f0cda6cd9dde93269
Successfully built pyinstaller
Installing collected packages: altgraph, macholib, pyinstaller-hooks-contrib, pyinstaller
Successfully installed altgraph-0.17 macholib-1.14 pyinstaller-4.0.dev0 pyinstaller-hooks-contrib-2020.6
WARNING: You are using pip version 19.2.3, however version 20.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
4.0.dev0
42 INFO: PyInstaller: 4.0.dev0
42 INFO: Python: 3.7.7
49 INFO: Platform: Darwin-18.7.0-x86_64-i386-64bit
50 INFO: wrote /Users/andrewr/Projects/pyinstaller-poc/mac-test/main.spec
53 INFO: UPX is not available.
55 INFO: Extending PYTHONPATH with paths
['/Users/andrewr/Projects/pyinstaller-poc/mac-test',
 '/Users/andrewr/Projects/pyinstaller-poc/mac-test']
60 INFO: checking Analysis
60 INFO: Building Analysis because Analysis-00.toc is non existent
60 INFO: Initializing module dependency graph...
61 INFO: Caching module graph hooks...
68 INFO: Analyzing base_library.zip ...
1761 INFO: Processing pre-find module path hook distutils from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1762 INFO: distutils: retargeting to non-venv dir '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7'
2784 INFO: Caching module dependency graph...
2874 INFO: running Analysis Analysis-00.toc
2880 INFO: Analyzing /Users/andrewr/Projects/pyinstaller-poc/mac-test/main.py
2881 INFO: Processing module hooks...
2882 INFO: Loading module hook 'hook-encodings.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2951 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2966 INFO: Loading module hook 'hook-xml.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
3187 INFO: Loading module hook 'hook-distutils.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
3198 INFO: Looking for ctypes DLLs
3198 INFO: Analyzing run-time hooks ...
3206 INFO: Looking for dynamic libraries
3271 INFO: Looking for eggs
3271 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.7/Python
3273 INFO: Warnings written to /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/warn-main.txt
3294 INFO: Graph cross-reference written to /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/xref-main.html
3308 INFO: checking PYZ
3308 INFO: Building PYZ because PYZ-00.toc is non existent
3308 INFO: Building PYZ (ZlibArchive) /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/PYZ-00.pyz
3594 INFO: Building PYZ (ZlibArchive) /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/PYZ-00.pyz completed successfully.
3599 INFO: checking PKG
3599 INFO: Building PKG because PKG-00.toc is non existent
3599 INFO: Building PKG (CArchive) PKG-00.pkg
3605 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
3606 INFO: Bootloader /Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
3606 INFO: checking EXE
3606 INFO: Building EXE because EXE-00.toc is non existent
3606 INFO: Building EXE from EXE-00.toc
3606 INFO: Appending archive to EXE /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/main
3608 INFO: Fixing EXE for code signing /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/main
3611 INFO: Building EXE from EXE-00.toc completed successfully.
3612 INFO: checking COLLECT
3612 INFO: Building COLLECT because COLLECT-00.toc is non existent
3613 INFO: Building COLLECT COLLECT-00.toc
4086 INFO: Building COLLECT COLLECT-00.toc completed successfully.
[10077] Error loading Python lib '/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python': dlopen: dlopen(/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python, 10): no suitable image found.  Did find:
        /Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python: code signature invalid for '/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python'
```

**Comment by Legorooj** [comment] 2020-08-06 23:02
@reritom @amifunny can you take a look at this?

**Comment by reritom** [comment] 2020-08-07 06:55
@Legorooj I can have a look over the coming days

**Comment by reritom** [comment] 2020-08-08 14:12
From my first look, I haven't managed to recreate your problem so far.
Some differences are:
- I'm on Darwin-19.5, while you are Darwin-18.7
- distutils: retargeting to non-venv dir "..." target different sources.
```
Python 3.7.7
pip 19.2.3 from /Users/tom/projects/mac-test/.venv/lib/python3.7/site-packages/pip (python 3.7)
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Using cached https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: setuptools in ./.venv/lib/python3.7/site-packages (from pyinstaller==4.0.dev0) (41.2.0)
Collecting altgraph (from pyinstaller==4.0.dev0)
  Using cached https://files.pythonhosted.org/packages/ee/3d/bfca21174b162f6ce674953f1b7a640c1498357fa6184776029557c25399/altgraph-0.17-py2.py3-none-any.whl
Collecting macholib>=1.8; sys_platform == "darwin" (from pyinstaller==4.0.dev0)
  Using cached https://files.pythonhosted.org/packages/3c/e1/c12f8d6af5d745ce88f270aeb243cb2bd6d8186320e5122df87fded29e4e/macholib-1.14-py2.py3-none-any.whl
Collecting pyinstaller-hooks-contrib>=2020.6 (from pyinstaller==4.0.dev0)
  Using cached https://files.pythonhosted.org/packages/28/47/ba60fc1e96e47391dc547f74b31daf28daa3ad3b8bfc3dedced5acbf48bd/pyinstaller_hooks_contrib-2020.6-py2.py3-none-any.whl
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517): started
  Building wheel for pyinstaller (PEP 517): finished with status 'done'
  Created wheel for pyinstaller: filename=pyinstaller-4.0.dev0-cp37-none-any.whl size=2804844 sha256=aee3894e318492a864cba027eb8225048051bdd241b0ecba27ad6a728e80a395
  Stored in directory: /private/var/folders/rn/3xcs8df13mjb58n4fzsddndh0000gn/T/pip-ephem-wheel-cache-w7n86ykq/wheels/1e/5b/0a/b7b241e8886f8f6d4c41177dd91cdb275f0cda6cd9dde93269
Successfully built pyinstaller
Installing collected packages: altgraph, macholib, pyinstaller-hooks-contrib, pyinstaller
Successfully installed altgraph-0.17 macholib-1.14 pyinstaller-4.0.dev0 pyinstaller-hooks-contrib-2020.6
4.0.dev0
166 INFO: PyInstaller: 4.0.dev0
166 INFO: Python: 3.7.7
178 INFO: Platform: Darwin-19.5.0-x86_64-i386-64bit
179 INFO: wrote /Users/tom/projects/mac-test/main.spec
184 INFO: UPX is not available.
186 INFO: Extending PYTHONPATH with paths
['/Users/tom/projects/mac-test', '/Users/tom/projects/mac-test']
196 INFO: checking Analysis
196 INFO: Building Analysis because Analysis-00.toc is non existent
196 INFO: Initializing module dependency graph...
199 INFO: Caching module graph hooks...
228 INFO: Analyzing base_library.zip ...
4373 INFO: Processing pre-find module path hook distutils from '/Users/tom/projects/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
4376 INFO: distutils: retargeting to non-venv dir '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7'
7325 INFO: Caching module dependency graph...
7757 INFO: running Analysis Analysis-00.toc
7778 INFO: Analyzing /Users/tom/projects/mac-test/main.py
7782 INFO: Processing module hooks...
7784 INFO: Loading module hook 'hook-encodings.py' from '/Users/tom/projects/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
7923 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/tom/projects/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
7940 INFO: Loading module hook 'hook-xml.py' from '/Users/tom/projects/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
8455 INFO: Loading module hook 'hook-distutils.py' from '/Users/tom/projects/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
8514 INFO: Looking for ctypes DLLs
8515 INFO: Analyzing run-time hooks ...
8542 INFO: Looking for dynamic libraries
8806 INFO: Looking for eggs
8806 INFO: Using Python library /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Python
8810 INFO: Warnings written to /Users/tom/projects/mac-test/build/main/warn-main.txt
8862 INFO: Graph cross-reference written to /Users/tom/projects/mac-test/build/main/xref-main.html
8900 INFO: checking PYZ
8900 INFO: Building PYZ because PYZ-00.toc is non existent
8900 INFO: Building PYZ (ZlibArchive) /Users/tom/projects/mac-test/build/main/PYZ-00.pyz
9726 INFO: Building PYZ (ZlibArchive) /Users/tom/projects/mac-test/build/main/PYZ-00.pyz completed successfully.
9744 INFO: checking PKG
9744 INFO: Building PKG because PKG-00.toc is non existent
9746 INFO: Building PKG (CArchive) PKG-00.pkg
9795 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
9797 INFO: Bootloader /Users/tom/projects/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
9798 INFO: checking EXE
9798 INFO: Building EXE because EXE-00.toc is non existent
9799 INFO: Building EXE from EXE-00.toc
9800 INFO: Appending archive to EXE /Users/tom/projects/mac-test/build/main/main
9806 INFO: Fixing EXE for code signing /Users/tom/projects/mac-test/build/main/main
9816 INFO: Building EXE from EXE-00.toc completed successfully.
9818 INFO: checking COLLECT
9818 INFO: Building COLLECT because COLLECT-00.toc is non existent
9819 INFO: Building COLLECT COLLECT-00.toc
10994 INFO: Building COLLECT COLLECT-00.toc completed successfully.
hello, mac
```
I will continue to look into it.

**Comment by reritom** [comment] 2020-08-08 15:15
This might be a code signing related issue https://stackoverflow.com/questions/42133980/ios-code-signature-invalid-required-code-signature-missing

**Comment by Legorooj** [comment] 2020-08-16 23:00
@arosiclair pinging

**Comment by arosiclair** [comment] 2020-08-18 18:48
Upgraded to Catalina macOS 10.15.6 but running the excutable still produces the same error:

```
Python 3.7.7
pip 19.2.3 from /Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/pip (python 3.7)
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Using cached https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting altgraph (from pyinstaller==4.1.dev0)
  Using cached https://files.pythonhosted.org/packages/ee/3d/bfca21174b162f6ce674953f1b7a640c1498357fa6184776029557c25399/altgraph-0.17-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.venv/lib/python3.7/site-packages (from pyinstaller==4.1.dev0) (41.2.0)
Collecting pyinstaller-hooks-contrib>=2020.6 (from pyinstaller==4.1.dev0)
  Using cached https://files.pythonhosted.org/packages/22/7a/5dedbe4bc1d5f3f3cf8a3e67abe9896f2a6b6b67f749cba73d9f427320ea/pyinstaller_hooks_contrib-2020.7-py2.py3-none-any.whl
Collecting macholib>=1.8; sys_platform == "darwin" (from pyinstaller==4.1.dev0)
  Using cached https://files.pythonhosted.org/packages/3c/e1/c12f8d6af5d745ce88f270aeb243cb2bd6d8186320e5122df87fded29e4e/macholib-1.14-py2.py3-none-any.whl
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... done
  Created wheel for pyinstaller: filename=pyinstaller-4.1.dev0-cp37-none-any.whl size=2789485 sha256=17b10b0e897a285211a5fed604c769764d737347c53f63beac293e1b2dfa3740
  Stored in directory: /private/var/folders/mm/lv7xny1n2nq8f2jw_8zz58qmkkgczp/T/pip-ephem-wheel-cache-qbsx3wkb/wheels/1e/5b/0a/b7b241e8886f8f6d4c41177dd91cdb275f0cda6cd9dde93269
Successfully built pyinstaller
Installing collected packages: altgraph, pyinstaller-hooks-contrib, macholib, pyinstaller
Successfully installed altgraph-0.17 macholib-1.14 pyinstaller-4.1.dev0 pyinstaller-hooks-contrib-2020.7
WARNING: You are using pip version 19.2.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
4.1.dev0
39 INFO: PyInstaller: 4.1.dev0
39 INFO: Python: 3.7.7
47 INFO: Platform: Darwin-19.6.0-x86_64-i386-64bit
48 INFO: wrote /Users/andrewr/Projects/pyinstaller-poc/mac-test/main.spec
52 INFO: UPX is not available.
54 INFO: Extending PYTHONPATH with paths
['/Users/andrewr/Projects/pyinstaller-poc/mac-test',
 '/Users/andrewr/Projects/pyinstaller-poc/mac-test']
61 INFO: checking Analysis
61 INFO: Building Analysis because Analysis-00.toc is non existent
61 INFO: Initializing module dependency graph...
63 INFO: Caching module graph hooks...
72 INFO: Analyzing base_library.zip ...
1575 INFO: Processing pre-find module path hook distutils from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1575 INFO: distutils: retargeting to non-venv dir '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7'
2504 INFO: Caching module dependency graph...
2584 INFO: running Analysis Analysis-00.toc
2591 INFO: Analyzing /Users/andrewr/Projects/pyinstaller-poc/mac-test/main.py
2593 INFO: Processing module hooks...
2594 INFO: Loading module hook 'hook-encodings.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2677 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2693 INFO: Loading module hook 'hook-xml.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2937 INFO: Loading module hook 'hook-distutils.py' from '/Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2948 INFO: Looking for ctypes DLLs
2948 INFO: Analyzing run-time hooks ...
2954 INFO: Looking for dynamic libraries
3037 INFO: Looking for eggs
3037 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.7/Python
3039 INFO: Warnings written to /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/warn-main.txt
3062 INFO: Graph cross-reference written to /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/xref-main.html
3077 INFO: checking PYZ
3077 INFO: Building PYZ because PYZ-00.toc is non existent
3077 INFO: Building PYZ (ZlibArchive) /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/PYZ-00.pyz
3377 INFO: Building PYZ (ZlibArchive) /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/PYZ-00.pyz completed successfully.
3381 INFO: checking PKG
3381 INFO: Building PKG because PKG-00.toc is non existent
3381 INFO: Building PKG (CArchive) PKG-00.pkg
3387 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
3388 INFO: Bootloader /Users/andrewr/Projects/pyinstaller-poc/mac-test/.venv/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
3388 INFO: checking EXE
3388 INFO: Building EXE because EXE-00.toc is non existent
3388 INFO: Building EXE from EXE-00.toc
3389 INFO: Appending archive to EXE /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/main
3390 INFO: Fixing EXE for code signing /Users/andrewr/Projects/pyinstaller-poc/mac-test/build/main/main
3392 INFO: Building EXE from EXE-00.toc completed successfully.
3394 INFO: checking COLLECT
3394 INFO: Building COLLECT because COLLECT-00.toc is non existent
3395 INFO: Building COLLECT COLLECT-00.toc
3860 INFO: Building COLLECT COLLECT-00.toc completed successfully.
[2904] Error loading Python lib '/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python': dlopen: dlopen(/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python, 10): no suitable image found.  Did find:
        /Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python: code signature invalid for '/Users/andrewr/Projects/pyinstaller-poc/mac-test/dist/main/Python'
```
Not familiar with code signing but this is the error the CLI reports for the binary in question:

```
codesign --verify --verbose mac-test/dist/main/Python 
mac-test/dist/main/Python: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
```

**Comment by reritom** [comment] 2020-08-18 20:27
To me this seems to resemble this open issue https://github.com/pyinstaller/pyinstaller/issues/2439

**Comment by Legorooj** [comment] 2020-08-19 00:38
Try adding the `--deep` option - that can help sometimes.

**Comment by vsalvino** [comment] 2020-08-31 03:38
I am also hitting this issue. I have traced it down to the fact that executables built in onefile mode with Python 3.7.6 work correctly, but built with any higher version of Python (3.7.7, 3.7.8, 3.7.9) does not work and throws the invalid code signature error. I have confirmed this by building with multiple version on a mac with OS 10.15.6

Found this thread which was very helpful: http://pyinstaller.47505.x6.nabble.com/Help-needed-Error-loading-Python-lib-td2872.html#a2873

**Comment by rokm** [comment] 2020-08-31 12:18
From 3.7.7 on and from 3.8.2 on, the macOS installer packages from python.org are compatible with Gatekeeper requirements regarding code signing.

The `Python` library file is now signed, and moving it invalidates the signature, e.g.:

```
$ codesign --verify --verbose dist/hello/Python 
dist/hello/Python: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
```
This in turn causes the `Error loading Python lib`.

A possible work-around may be removing the signature from `Python` library file.
```
$ codesign --remove-signature dist/hello/Python
```
This seems to do the trick for a `onedir` application. Perhaps the signature needs to be stripped from `Python` before/while creating the bundle as well.

**Comment by martinet101** [comment] 2020-09-12 18:46
I just downgraded from python3.7.7 to python3.7.6. I don't know the reason, but i guess this happens because python developers added something like full Gatekeeper notarization for macOS (on the changelog https://www.python.org/downloads/release/python-379/) It says `As of 3.7.7, macOS installer packages are now compatible with the full Gatekeeper notarization requirements of macOS 10.15 Catalina including code signing`
I guess that because on windows and on ubuntu PyInstaller and Python 3.7.7-3.7.9 are working fine.

**Comment by nicozanf** [comment] 2020-12-06 23:10
I can confirm this behaviour and the workaround.
My app was working fine with Python 3.7.4 and PyInstaller 3.9/4.0. Now I've found that it gives that error if compiled with Python 3.8.6 and PyInstaller 4.1/4.1dev on MacOs 10.12.6 or 10.15.4. But after running on it:

`$ sudo codesign --remove-signature Python`
  
it works fine again (without having to sign anything)!

**Closed** 2021-01-11 18:13 UTC
Labels: platform:OS X

**Comment by dsoegijono** [comment] 2021-01-21 05:51
I still have this issue even after downgrading to python 3.7.6, on MacOS 11.1

**Comment by rokm** [comment] 2021-01-21 10:33
@dsoegijono If you take a closer look at your error message, you'll see that it's a different issue. You are using python that was build with minimum macOS version set to 11.1, so the Python shared library collected from that will not load on any earlier version of macOS.

I suppose you are using a custom python build, because official python.org builds have minimum version still set to 10.9 (even the new macos11 variant of python 3.9.1).

**Comment by dsoegijono** [comment] 2021-01-21 11:00
Thanks @rokm would it be better if I create a separate issue then

> I suppose you are using a custom python build, because official python.org builds have minimum version still set to 10.9 (even the new macos11 variant of python 3.9.1).

I installed via `pyenv`

**Comment by rokm** [comment] 2021-01-21 12:29
That `pyenv` command seems to build python from source, and the minimum target macOS version is probably the default that comes from your OS version and/or installed XCode version.

I've no idea how much you can influence it from `pyenv`, though - I imagine that for `pyenv` and `brew`, cross-version compatibility is not really a concern, as you are always building/installing the version that matches the local OS version. (As a side note, the 3.9.1 python bottles in homebrew seem to have minimum version set to their corresponding bottle name, as well). It does mean that PyInstaller-frozen programs built with that version of python won't work on older macOS versions, though.

So either you'll need to switch to python version that's backwards compatible (like python.org builds), or use an older version of macOS as your build system.

**Comment by BoboTiG** [comment] 2021-01-21 12:49
Maybe setting the envar `MACOSX_DEPLOYMENT_TARGET` could influence how `pyenv` builds Python.

**Comment by dofamin-1** [comment] 2022-09-22 05:35
Hi there

I have a similar problem, but not the same. 
My executable (--onefile) is working fine but after signing it I started getting this error message:

`[61623] Error loading Python lib '/var/folders/1_/nz8m7dbx24d9_4bkng58vlqw0000gn/T/_MEIXqq3is/Python': dlopen: dlopen(/var/folders/1_/nz8m7dbx24d9_4bkng58vlqw0000gn/T/_MEIXqq3is/Python, 0x000A): tried: '/var/folders/1_/nz8m7dbx24d9_4bkng58vlqw0000gn/T/_MEIXqq3is/Python' (code signature in <D264938F-83FF-32D7-A48C-32BE5E18DEE9> '/private/var/folders/1_/nz8m7dbx24d9_4bkng58vlqw0000gn/T/_MEIXqq3is/Python' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/private/var/folders/1_/nz8m7dbx24d9_4bkng58vlqw0000gn/T/_MEIXqq3is/Python' (code signature in <D264938F-83FF-32D7-A48C-32BE5E18DEE9> '/private/var/folders/1_/nz8m7dbx24d9_4bkng58vlqw0000gn/T/_MEIXqq3is/Python' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))`

Has anyone else come across this problem too?
Will be glad for any feedback.

**Comment by rokm** [comment] 2022-09-22 09:27
Manually signing `onefile` binaries post-hoc with `codesign` is unlikely to work, because it signs only the executable itself. It does not (and cannot) sign the embedded binaries, like the python shared library in your error message. You can try to enable signing with your codesign identity during the build with [--codesign-identity](https://pyinstaller.org/en/stable/usage.html#cmdoption-codesign-identity); if that does not help, you'll have to switch to `onedir` build.

**Comment by dofamin-1** [comment] 2022-09-22 10:52
Thank you for quick response @rokm !
Well if I decide to switch to `onedir` build, how should I `codesign` that folder (which contains all stuff created by PyInstaller (with `--onedir` option)).
 Note: I am signing using the command line (Not with XCode)

**Comment by rokm** [comment] 2022-09-22 13:25
You can (re)sign problematic files one by one, you can try listing them based on extension (`.dylib` and `.so`), you could read `build/<name>/Analysis-00.toc` to obtain list of `BINARY` and `EXTENSION` entries. I don't imagine any of these approaches to be 100% successful, though, so you'll still be in for some manual work.

Depending on your application type (i.e., if it is not pure CLI program), you could instead try generating .app bundle and sign that recursively using `codesign --force --deep ...`.
