### ISSUE TITLE
zipimport.ZipImportError: can't find module 'encodings'

### ISSUE THREAD

**Issue by 2424004764** [pyinstaller/pyinstaller#3699] opened 2018-08-28 06:48 UTC
i use it pyinstaller compile error 
zipimport.ZipImportError: can't find module 'encodings'

complete error info:
Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x00004a7c (most recent call first):

**Comment by htgoebel** [comment] 2018-08-28 08:59
Duplicate of #3642

**Closed by htgoebel** 2018-08-28 08:59 UTC
