### ISSUE TITLE
TypeError: Unable to convert function return value to a Python type! The signature was () -> handle

### ISSUE THREAD

**Issue by skabirgithub** [pyinstaller/pyinstaller#8002] opened 2023-10-12 12:09 UTC
When I run the .exe I am getting this error.
File "tensorflow\python\framework\dtypes.py", line 37, in
TypeError: Unable to convert function return value to a Python type! The signature was
() -> handle

I have a hook file named hook-tensorflow.py:..................
from PyInstaller.utils.hooks import collect_all
def hook(hook_api):
packages = [
'tensorflow',
'tensorflow_core',
'astor'
]
for package in packages:
datas, binaries, hiddenimports = collect_all(package)
hook_api.add_datas(datas)
hook_api.add_binaries(binaries)
hook_api.add_imports(*hiddenimports)

**Comment by rokm** [comment] 2023-10-12 12:12
Duplicate of #8001 (and of #7961).

**Closed as not planned** 2023-10-12 12:12 UTC
Labels: solution:duplicate
