### ISSUE TITLE
Add a version of `datas` that places files outside the `contents_directory`

### ISSUE THREAD

**Issue by TeamSpen210** [pyinstaller/pyinstaller#8019] opened 2023-10-19 04:07 UTC
**Is your feature request related to a problem? Please describe.**
The new `contents_directory` option is quite nice for hiding the necessary internal files for an application, but there are also some files which should be exposed to the user (readme, translation files). Currently I've been using the `datas` option to copy all these files, letting me generate the final distribution in one go. But `datas` [refuses to allow](https://github.com/pyinstaller/pyinstaller/blob/c683012d0d26efc5681bde27b85a0b1fcee48cc4/PyInstaller/building/api.py#L1113) `../` paths, so it can no longer be used for this purpose.

**Describe the solution you'd like**
An additional attribute (perhaps `dist_datas`?) which behaves the same as `datas`, but ignores `contents_directory` if set. Alternatively, allowing the regular `datas` TOC to copy up to the app directory root with `../` (but not further).

**Describe alternatives you've considered**
In the original PR @bwoodsend [mentioned](https://github.com/pyinstaller/pyinstaller/pull/7713#issuecomment-1603238962) this, but suggested using `cp` or `shutil.copy` in the spec file. However, `datas` offers a bunch of nice features like glob support and auto-folder-copying. Additionally, if the `-y` parameter is passed, `COLLECT()` will remove the folder, preventing spec files from writing there.

**Comment by rokm** [comment] 2023-10-19 08:33
Duplicate of #7951. As far as I'm concerned, the answer is still no; if you have files that cannot be (re)located to `sys._MEIPASS`, then you should manage them yourself in post-processing (either within the spec, or the script/workflow that calls PyInstaller).

**Closed as not planned** 2023-10-19 08:35 UTC
Labels: feature, solution:duplicate

**Comment by bwoodsend** [comment] 2023-10-19 09:29
> However, datas offers a bunch of nice features like glob support and auto-folder-copying.

`shutil.copytree()` does whole directories. Globs can be done with a comprehension loop (`[shutil.copy(file, "dist/yourapp") for file in glob.glob("some/directory/*.png")]`).

> Additionally, if the -y parameter is passed, COLLECT() will remove the folder, preventing spec files from writing there.

Not if you put the copy code after the `COLLECT()` block in your spec file.
