### ISSUE TITLE
Symbol not found: _clock_getres

### ISSUE THREAD

**Issue by gitexel** [pyinstaller/pyinstaller#3419] opened 2018-03-22 13:17 UTC
```
/Volumes/myapp/myapp.app/Contents/MacOS/myapp ; exit;
[31034] Error loading Python lib 
dlopen(/Volumes/myapp/myapp.app/Contents/MacOS/Python, 10): Symbol not found: _clock_getres
  Referenced from: /Volumes/myapp/myapp.app/Contents/MacOS/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Volumes/myapp/myapp.app/Contents/MacOS/Python
logout

```

**Comment by abulka** [comment] 2018-03-23 07:19
You might be encountering the same issue I had #3418

**Comment by htgoebel** [comment] 2018-03-23 08:37
Based on the excessive (NOT!) information you gave, I assume this is a Duplicate of #1191 . 

@gitexel Next time please provide more information. Just pasting an error message is ignorant!

**Closed** 2018-03-28 03:06 UTC
Labels: duplicate
