### ISSUE TITLE
Issue with django Celery

### ISSUE THREAD

**Issue by pyarun** [pyinstaller/pyinstaller#3138] opened 2017-12-19 12:49 UTC
#### Checklist
- Using latest develop branch.
- Using virtualenv, onedir mode and `upx=False`

#### Enviornment:
PyInstaller: 3.4.dev0+ab8fd9753  
Python: 2.7.6  
Platform: Linux-4.4.0-75-generic-x86_64-with-Ubuntu-14.04-trusty  
celery==4.1.0  
Django==1.11

#### Issue
build process fails as it is not able to import Celery.
Tracekback

```
27915 INFO: Loading module hook "hook-django.py"...
27916 INFO: Django root directory /home/user/Workspace/testapp/mydjapp/mydjapp
Traceback (most recent call last):
  File "/home/user/.virtualenvs/tester/local/lib/python2.7/site-packages/PyInstaller/utils/hooks/subproc/django_import_finder.py", line 27, in <module>
    django.setup()
  File "/home/user/.virtualenvs/tester/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/user/.virtualenvs/tester/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/user/.virtualenvs/tester/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/.virtualenvs/tester/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/Workspace/testapp/mydjapp/mydjapp/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/user/Workspace/testapp/mydjapp/mydjapp/celery.py", line 3, in <module>
    from celery import Celery
  File "/home/user/Workspace/testapp/mydjapp/mydjapp/celery.py", line 3, in <module>
    from celery import Celery
ImportError: cannot import name Celery
28597 INFO: Collecting Django migration scripts.

```

I am struggling writing a hook which can resolve this issue. whatever hook i tried is being analyzed after `hook-django.py`. So i am not sure it will work at all.

Here is the complete [code](https://github.com/pyarun/pyinstaller-test-app)

**Comment by xoviat** [comment] 2017-12-20 19:38
See gh-2441.

**Comment by htgoebel** [comment] 2017-12-22 17:51
Duplicate of #1717

**Closed by htgoebel** 2017-12-22 17:51 UTC
