### ISSUE TITLE
1-line Exe crashes with pyi_rth_qt5plugins.py missing from somewhere?

### ISSUE THREAD

**Issue by FruitfulApproach** [pyinstaller/pyinstaller#2455] opened 2017-02-12 00:19 UTC
I have tried everything in the "If Things Go Wrong" guide except for the archive viewer suggestion.

**Fails with minimal Qt5 App:**
```
import sys
from PyQt5.QtWidgets import QApplication

if __name__ == '__main__':
        app = QApplication(sys.argv)
        
        sys.exit(app.exec_())    
```

**I try building with something like:**
pyinstaller -nAppName --onedir --debug main.py

**It seems to build fine, but here's the output:**
> debug main.py
> 2299 INFO: PyInstaller: 3.3.dev0+11f2e7b
> 2300 INFO: Python: 3.5.2
> 2303 INFO: Platform: Windows-8.1-6.3.9600-SP0
> 2309 INFO: wrote c:\MyProjects\StackOverflowQuestions\PyInstaller\MinimalApp\MinimalApp.spec
> 2317 INFO: UPX is not available.
> 2323 INFO: Extending PYTHONPATH with paths
> ['c:\\MyProjects\\StackOverflowQuestions\\PyInstaller\\MinimalApp',
>  'c:\\MyProjects\\StackOverflowQuestions\\PyInstaller\\MinimalApp']
> 2324 INFO: checking Analysis
> 2482 INFO: checking PYZ
> 2580 INFO: checking PKG
> 2584 INFO: Building because c:\MyProjects\StackOverflowQuestions\PyInstaller\MinimalApp\build\MinimalApp\MinimalA
> 2585 INFO: Building PKG (CArchive) out00-PKG.pkg
> 2922 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
> 2930 INFO: Bootloader c:\python35\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run_d.exe
> 2931 INFO: checking EXE
> 2936 INFO: Building because manifest changed
> 2937 INFO: Building EXE from out00-EXE.toc
> 2939 INFO: Appending archive to EXE c:\MyProjects\StackOverflowQuestions\PyInstaller\MinimalApp\build\MinimalApp\
> 6335 INFO: Building EXE from out00-EXE.toc completed successfully.
> 6374 INFO: checking COLLECT
> WARNING: The output directory "c:\MyProjects\StackOverflowQuestions\PyInstaller\MinimalApp\dist\MinimalApp" and A
> )y
> 11793 INFO: Removing dir c:\MyProjects\StackOverflowQuestions\PyInstaller\MinimalApp\dist\MinimalApp
> 12007 INFO: Building COLLECT out00-COLLECT.toc
> 22526 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

**Upon running:**
> ...
> LOADER: Installing PYZ archive with Python modules.
> LOADER: PYZ archive: out00-PYZ.pyz
> LOADER: Running pyiboot01_bootstrap.py
> LOADER: Running pyi_rth_qt5.py
> LOADER: Running pyi_rth_qt5plugins.py
> Traceback (most recent call last):
>   File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 46, in <module>
>   File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 573, in load_module
>     module = loader.load_module(fullname)
> ImportError: DLL load failed: The specified procedure could not be found.
> Failed to execute script pyi_rth_qt5plugins
> LOADER: OK.

**More Info:**

- Win 7 64-bit
- python 3.5.2
- PyQt 5.7.1
- I don't use venv or conda.

**Comment by xoviat** [comment] 2017-02-12 02:40
Can you apply #2403?

```
git clone https://github.com/pyinstaller/pyinstaller.git
cd pyinstaller
git pull origin +refs/pull/2403/merge
pip install --force-reinstall .
```

Note: executables generated with unmerged pull requests may be unstable and should not be distributed to users without prior verification.

**Comment by FruitfulApproach** [comment] 2017-02-12 16:41
@xoviat That seems to have worked.

**Comment by FruitfulApproach** [comment] 2017-02-12 23:07
Do I close this issue.  I would like to refer to it later.

Thanks.

**Comment by xoviat** [comment] 2017-02-13 00:50
It's a duplicate of #2241, but this has better discussion (I can tell other people duplicate of this issue) so ideally #2241 would be closed and this would remain open.

**Comment by bjones1** [comment] 2019-04-29 21:57
This should be fixed now.

**Closed by bjones1** 2019-04-29 21:57 UTC

**Comment by enjoysmath** [comment] 2019-04-29 22:00
Thanks.  I don't even know what I was working on 2 years ago.  I have used pyinstaller successfully recently except I have to copy my desktop dev directory, before running pyinstaller on it, to the drive root or the created EXE crashes.

All in all I am very happy with pyinstaller and want to integrate it into this app creation IDE I'm making called **Watermelon**.
