### ISSUE TITLE
Failed KMeans sklearn import

### ISSUE THREAD

**Issue by zonnalobo** [pyinstaller/pyinstaller#6035] opened 2021-07-19 09:38 UTC
I compile my script using PyInstaller 4.4 on Red Hat Enterprise 7.7. On that script, there is a line that I unpickle kmeans function from scikit-learn and it success to compile but failed when running on that unpickle line.

So, I build a simple script, named tes.py contain only 3 lines, like this:
```
import pickle
from sklearn.cluster import KMeans
model_kmeans = pickle.load(open('model.sav', 'rb'))
```
it fails also when running. The error is in line 2 as below:
```
File "tes.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/cluster/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/cluster/_spectral.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/neighbors/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/neighbors/_nca.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/decomposition/__init__.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/decomposition/_sparse_pca.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/linear_model/__init__.py", line 24, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/linear_model/_logistic.py", line 24, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/svm/__init__.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/svm/_classes.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/svm/_base.py", line 8, in <module>
ImportError: /home/sonna/apps/dist/tes/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/sonna/apps/dist/tes/sklearn/svm/_libsvm.cpython-38-x86_64-linux-gnu.so)
[125720] Failed to execute script 'tes' due to unhandled exception!
```

I try to build a new environment and compile the script on that but provide the same error on the same line but different message error:

 ```
File "tes.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/cluster/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/cluster/_spectral.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/neighbors/__init__.py", line 6, in <module>
  File "sklearn/neighbors/_ball_tree.pyx", line 1, in init sklearn.neighbors._ball_tree
  File "sklearn/neighbors/_dist_metrics.pyx", line 52, in init sklearn.neighbors._dist_metrics
ModuleNotFoundError: No module named 'sklearn.neighbors._typedefs'
[116263] Failed to execute script 'tes' due to unhandled exception!
```

Is there any solution for this?

**Comment by rokm** [comment] 2021-07-19 09:44
> ImportError: /home/sonna/apps/dist/tes/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/sonna/apps/dist/tes/sklearn/svm/_libsvm.cpython-38-x86_64-linux-gnu.so)

This one means that `sklearn`'s extensions were built against newer glibc than the one that was collected from the build system. But I doubt that's PyInstaller-specific problem, and you probably cannot import sklearn.svm on your RHEL 7.x system in python interpreter, either.

> ModuleNotFoundError: No module named 'sklearn.neighbors._typedefs'

You should be able to work around this one by adding `sklearn.neighbors._typedefs` to `hiddenimports`.

**Comment by zonnalobo** [comment] 2021-07-19 10:11
Hi @rokm, thanks for the responds.
Actually, on the compile command I had added `sklearn` to `hiddenimports`, and now I also added all your suggestion like below:
`hiddenimports=['sklearn','sklearn.neighbors._typedefs','sklearn.svm']`
however, nothing change on the first case, I also had implemented the suggestion  on 
[this](https://github.com/gridsync/gridsync/commit/8996e425c79ee36acbd25cce43603531b99ae298) but it keeps provide the same error message.
For the second case: the error message change to:
```
 File "tes.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/cluster/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/cluster/_spectral.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/neighbors/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/neighbors/_nca.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/decomposition/__init__.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/decomposition/_sparse_pca.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sklearn/linear_model/__init__.py", line 20, in <module>
  File "sklearn/linear_model/_sgd_fast.pyx", line 1, in init sklearn.linear_model._sgd_fast
ModuleNotFoundError: No module named 'sklearn.utils._weight_vector'
[42343] Failed to execute script 'tes' due to unhandled exception!
```

**Comment by rokm** [comment] 2021-07-19 10:18
>  however, nothing change on the first case, I also had implemented the suggestion on
> [this](https://github.com/gridsync/gridsync/commit/8996e425c79ee36acbd25cce43603531b99ae298) but it keeps provide the same error message.

You can try removing the collected libstdc++.so.6 from the dist bundle (/home/sonna/apps/dist/tes/libstdc++.so.6); then the target system's copy should be used, which may or may not be sufficiently new (if that's the same or another RHEL 7x system, it probably won't be).

What version of scikit-learn are you using and how did you install it?

> ModuleNotFoundError: No module named 'sklearn.utils._weight_vector'

Add `sklearn.utils._weight_vector` to `hiddenimports` (and any other module-not-found you may encounter as well). 

I see the hooks are subtly failing to collect those hidden imports due to incorrect version checks; will fix those, but in the mean time, use `hiddenimports`.

**Comment by zonnalobo** [comment] 2021-07-19 10:29
> You can try removing the collected libstdc++.so.6 from the dist bundle (/home/sonna/apps/dist/tes/libstdc++.so.6); then the target system's copy should be used, which may or may not be sufficiently new (if that's the same or another RHEL 7x system, it probably won't be).

So there is no solution for this issue for this moment?



> What version of scikit-learn are you using and how did you install it?

I use `scikit-learn 0.24.2` installed by `pip install scikit-learn`

**Comment by rokm** [comment] 2021-07-19 10:45
> So there is no solution for this issue for this moment?

This is a problem with your build environment; you somehow ended up with scikit that was compiled against newer libraries than your RHEL 7 system supports.

In your second environment, you managed to avoid that problem (but you need to work around the missing hiddenimports).

**Comment by rokm** [comment] 2021-07-19 10:46
Or are you getting the same error with the second environment, now that you sorted out all missing imports?

**Comment by zonnalobo** [comment] 2021-07-19 11:18
> This is a problem with your build environment; you somehow ended up with scikit that was compiled against newer libraries than your RHEL 7 system supports.
> 
> In your second environment, you managed to avoid that problem (but you need to work around the missing hiddenimports).

Ok, I got it.
The issue only for case 2.

**Comment by zonnalobo** [comment] 2021-07-19 11:56
> ImportError: /home/sonna/apps/dist/tes/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/sonna/apps/dist/tes/sklearn/svm/_libsvm.cpython-38-x86_64-linux-gnu.so)
> [125720] Failed to execute script 'tes' due to unhandled exception!

Hi @rokm, I don't understand why pyinstaller force use to add some module that we don't use before compiling. For this issue, I try to install `glibc` and `gridsync` and compile the script again. When I try to run the result, it works now. I don't know which module or their dependency module that solve the issue, because no information on the previous error message, but this one can make us crazy to find the solution. Same case with this [one](https://github.com/pyinstaller/pyinstaller/issues/6005).

**Comment by rokm** [comment] 2021-07-19 12:50
> Hi @rokm, I don't understand why pyinstaller force use to add some module that we don't use before compiling.

PyInstaller doesn't force anything here; it's `scikit-learn` that's importing its subpackages and submodules. 

The import chain, as indicated in backtrace, was: your program -> sklearn.cluster -> sklearn.cluster._spectral -> sklearn.neighbors -> sklearn.neighbors._nca -> sklearn.decomposition -> sklearn.decomposition._sparse_pca -> sklearn.linear_model -> sklearn.linear_model._logistic.py -> sklearn.svm -> sklearn.svm._classes -> sklearn.svm._base -> sklearn.svm._libsvm extension (which failed to load due to libstdc++ incompatibility).

> When I try to run the result, it works now. I don't know which module or their dependency module that solve the issue, because no information on the previous error message.

Most likely, you installed "proper" version of scikit-learn now (the manylinux2010 wheel, which works on RHEL7). If you still have the old (faulty) environment, try activating it and run`pip freeze` in it, to see what version of scikit-learn was installed there.

> Something like this can drive us crazy in finding the solution. Same case with this [one](https://github.com/pyinstaller/pyinstaller/issues/6005).

Sure, but what do you expect us to do? We (the developers) cannot guess all the possible nuances in which you can mess up your environment, much less it can be done within the PyInstaller itself...

I notice that you opened the linked issue as well - if you are using Anaconda, you should mention that up front, because that opens up whole bunch of additional failure modes. So if this is an anaconda environment, then the problem is likely that for some reason, the system libstdc++ took precedence over Anaconda's one (which could be due to bug in PyInstaller, or could be due to incorrectly set LD_LIBRARY_PATH).

**Comment by zonnalobo** [comment] 2021-07-19 13:11
> The import chain, as indicated in backtrace, was: your program -> sklearn.cluster -> sklearn.cluster._spectral -> sklearn.neighbors -> sklearn.neighbors._nca -> sklearn.decomposition -> sklearn.decomposition._sparse_pca -> sklearn.linear_model -> sklearn.linear_model._logistic.py -> sklearn.svm -> sklearn.svm._classes -> sklearn.svm._base -> sklearn.svm._libsvm extension (which failed to load due to libstdc++ incompatibility).

I understand the situation but something that confuse me is when I tried to check to `Anaconda3/lib` when I compiled and result failed, I found `libstdc++.so`,`libstdc++.so.6`, and `libstdc++.so.6.0.28` which the first two are shortcuts to the third. And the script are working with command `python tes.py`. The error was not appear. However, after we compiled, the error message was shown and needed those added modules to solve it. That means that, we don't need them when running in system, but we need them for running the compiling.
Notes: after fixing the issue, no changing in `libstdc++.so`,`libstdc++.so.6`, and `libstdc++.so.6.0.28`.


> I notice that you opened the linked issue as well - if you are using Anaconda, you should mention that up front, because that opens up whole bunch of additional failure modes. So if this is an anaconda environment, then the problem is likely that for some reason, the system libstdc++ took precedence over Anaconda's one when shared libraries were collected by PyInstaller (which could be due to bug in PyInstaller, or could be due to incorrectly set LD_LIBRARY_PATH, or mixing anaconda and pip packages).

I thought it is different issue because the error message is different and running for different script. Also the previous script doesn't contains `scikit-learn`. Just realize both are the same after find the solution.

**Comment by zonnalobo** [comment] 2021-07-19 13:22
> Notes: after fixing the issue, no changing in `libstdc++.so`,`libstdc++.so.6`, and `libstdc++.so.6.0.28`.

When I try to add some command to delete `libstdc++.so.6` to `tes.spech`, it success to delete. That means Pyinstaller was doing great job to add the file to the compiling. But seems like failed to connect it with `sklearn.svm` and need another module to make it connect.

**Comment by rokm** [comment] 2021-07-19 13:24
Can you compute md5 or sha256hash on Anaconda's `libstdc++.so`, the one in `/usr/lib64` and the one that ended up in application's dist folder to see which one was actually collected?

**Comment by zonnalobo** [comment] 2021-07-19 13:47
I cannot find any folder name `lib64` in Anaconda3 or Compiling folder. (Actually, when I delete `libstdc++.so.6` using command in `tes.spech`, the error change from `ImportError: dist/tes/libstdc++.so.6` to `ImportError: dist/tes/lib64/libstdc++.so.6`)
So, I calculate the md5sum for any `libstdc++.so.6`:
`Anaconda3/lib/libstdc++.so`  or `libstdc++.so.6` or `libstdc++.so.6.0.28` is `2b684ffef8f6e633189fb85f6fbe848c`
Also the same result for `dist/tes/libstdc++.so` or `libstdc++.so.6.0.28`.
However, the score for `dist/tes/libstdc++.so` is `b64fdb2dfd894a80651aea3a8d46fe2a`.

Note: The calculation using files in success compiling result.

**Comment by rokm** [comment] 2021-07-19 14:03
So the `dist/tes/libstdc++.so.6`  did not come from your Anaconda installation, but probably from your base system (`/usr/lib64/libstdc++.so.6`).

**Comment by zonnalobo** [comment] 2021-07-19 14:30
I try to find any file name `libstdc++.so.6` on `/usr/*` exclude in `/dist/*` but found no one the same with in `dist/tes/libstdc++.so.6`. All found files come from Anaconda folder. I also cannot find any folder name `lib64`.
Also I found that in my all compile folders from any scripts have the same file with `dist/tes/libstdc++.so.6` but all previous script not using `sklearn` so perhaps this is why they are running well.

I also don't understand where this file comes.
![tes](https://user-images.githubusercontent.com/42733716/126175123-247611d3-0a7b-4d81-9678-6e476b23f221.jpg)

**Comment by rokm** [comment] 2021-07-19 15:05
I guess the only way to solve the mystery then is to open either `Analysis-00.toc` or `COLLECT-00.toc` in your `build/<name>` directory and find the entry for `libstdc++.so.6`.

**Comment by rokm** [comment] 2021-07-20 19:03
I'll be closing this as non-reproducible.

There was a legit issue with our `scikit-learn` hooks that resulted in hiddenimports not being correctly handled when dummy `sklearn` distribution is installed. That's fixed in the contrib repository, and should work correctly after next version of pyinstaller-contrib-hooks is released.

As for the other (original) issue with `libstdc++.so.6`. Since now we know this was Anaconda installation, the original environment probably had `scikit-learn` installed via anaconda, and its extensions were linked against `libstdc++.so.6` from Anaconda installation (which is newer than the version that comes with base RHEL7). However, for an unknown reason, the RHEL7-version of library (from `/usr/lib64`) ended up collected instead of Anaconda one, resulting in missing symbols errors. I have not been able to reproduce this - it works as expected on my test (clean) Anaconda environment and collects only Anaconda libraries.

The problem was then worked around by creating new environment and installing `scikit-learn` via `pip`, which installed `manylinux2010` that is compatible with RHEL7 `libstdc++.so.6`, so it did not matter anymore which version was collected.

There was also a debate about PyInstaller pulling in some modules that are not required; yesterday I thought this was referring to python modules, but if the comment was instead targeting `libstdc++.so.6`, then the situation is as follows: sure, you can remove the file from your application bundle, and it will still work on your system. But if you try to run it on a system that does not libstdc++.so.6 installed for whatever reason (or has even older version), it will not work. This would have been more obvious with original Anaconda-provided `scikit-learn` and its `libstdc++.so.6`, because if the library were removed, the bundle would run within Anaconda environment but not outside of it (i.e., on the underlying RHEL7 system, or on another RHEL7 system).

**Closed by rokm** 2021-07-20 19:03 UTC
Labels: triage

**Comment by zonnalobo** [comment] 2021-07-22 04:25
Thanks for you answer.
Here is I attach the `Analysis-00.toc` and `COLLECT-00.toc` files. Hope it can helps.  
[Analysis-00.zip](https://github.com/pyinstaller/pyinstaller/files/6859950/Analysis-00.zip)

**Comment by rokm** [comment] 2021-07-22 06:22
It confirms that you're ending up with system copy of libstdc++.so.6:
>   ('libstdc++.so.6', '/lib64/libstdc++.so.6', 'BINARY'),

Can you re-run pyinstaller with `--log-level DEBUG` and pipe the whole output to a file, and attach that file here? Maybe that will contain some hints about what's going on.

**Comment by zonnalobo** [comment] 2021-07-23 02:50
Yes, I found two line sources in `Analysis-00.toc`  but only the first one found in `COLLECT-00.toc`.
[build.zip](https://github.com/pyinstaller/pyinstaller/files/6866335/build.zip)

```
('libstdc++.so.6', '/lib64/libstdc++.so.6', 'BINARY'),
('libstdc++.so.6', '/home/usr/anaconda3/lib/libstdc++.so.6', 'DATA'),
```
