### ISSUE TITLE
PyInstaller v4.0 '--key' Creates a project of several GB in size! 

### ISSUE THREAD

**Issue by Salim9304** [pyinstaller/pyinstaller#4932] opened 2020-06-14 12:26 UTC
1) pip3 install https://github.com/pyinstaller/pyinstaller/tarball/develop
2) pip3 install pyinstaller[encryption]
3) PyInstaller -F... --key=password...

A project is created that is 10 times larger (Linux) instead of 130Mb, the binary is **1.5Gb**

I tried disabling the '--key' option, but the project compiles with the same invalid size of 1.5GB.

UPD
Rolled back to version pyinstaller 3.6. Program size during compilation normal: 120Mb

**Comment by Legorooj** [comment] 2020-06-14 23:38
@Salim9304 `pip3 install pyinstaller[encryption]` doesn't actually work yet. Can you `pip3 install tinyaes` and build again, but adding the `--clean` option?

**Comment by Salim9304** [comment] 2020-06-15 06:53
--clean option was enabled in both cases.
With or without encryption, Pyinstaller v4.0 builds the project for a long time, and Gb output.

**Comment by Legorooj** [comment] 2020-06-15 07:00
@Salim9304 would it be possible to send me the code for this project so I can try to reproduce? Or is it proprietary?

**Comment by Salim9304** [comment] 2020-06-15 07:13
> Or is it proprietary

**Comment by Legorooj** [comment] 2020-06-15 09:58
@Salim9304 can you create a minimal reproducible example for me?

**Comment by Salim9304** [comment] 2020-06-15 10:20
Yes, I'll think about what you can think of, but it probably won't be that fast.

**Comment by Legorooj** [comment] 2020-06-15 11:55
@Salim9304 I'll try and reproduce this myself though I think this is a more niche bug.

**Comment by Salim9304** [comment] 2020-06-15 19:59
@Legorooj I found a 100% error, specifically what exactly in pyinstaller v 4.0 causes a bug with a size in GB
1) pip3 install https://github.com/pyinstaller/pyinstaller/tarball/develop
2) python3 -m PyInstaller --clean -F project.py 

**Error reproducing example**
$ cat project.py
```
from playsound import playsound #importing this [module] https://github.com/TaylorSMarks/playsound) gives fantastic GB size and long build
print("test")
```


-----------
![0](https://user-images.githubusercontent.com/61138725/84700165-620b1680-af5b-11ea-948c-9499c3cc95d4.png)

**pyinstaller v3.6 has no problem with this module**

**Comment by Legorooj** [comment] 2020-06-16 00:19
@Salim9304 I'll try to reproduce and fix this.

**Comment by htgoebel** [comment] 2020-07-19 13:09
@Salim9304 "playsound" sounds like some binary data being included, which can not be compresses after encryption. Please search for any differences in the build directory.

**Comment by Legorooj** [comment] 2020-07-21 07:39
@htgoebel `playsound` is actually a single python file that wraps the respective builtin sound provider for that platform.

@Salim9304 I've been unable to reproduce:
```
(venv) D:\PyInstaller-Issues>dir dist
 Volume in drive D is DATA
 Volume Serial Number is 76A8-75AB

 Directory of D:\PyInstaller-Issues\dist

21/07/2020  05:34 PM    <DIR>          .
21/07/2020  05:34 PM    <DIR>          ..
21/07/2020  05:21 PM         8,266,013 test.exe
21/07/2020  05:31 PM         8,333,764 test1.exe
               2 File(s)     16,599,777 bytes
               2 Dir(s)  193,533,849,600 bytes free
```
The only difference between `test.exe` and `test1.exe` is that `test1`'s source includes the `import playsound` line at the top of the script. I'm running the bleeding edge PyInstaller 4.0 with rebuilt bootloaders, and the script I used was:
```python
import tkinter
from tkinter import ttk
import playsound  # This line isn't here in test.exe's source

root = tkinter.Tk()

msg = ttk.Label(root, text='It\'s working just fine.')

msg.grid()

root.mainloop()
```
@bwoodsend can you try to reproduce? If you can't, please close the issue because until we have a replication of some kind we can't do anything.

**Comment by bwoodsend** [comment] 2020-07-21 13:55
@Legorooj  No luck - my build is 6MB.

@Salim9304 If I had to guess, there's probably an `import` in `playsound` to another large library that Legorooj and I don't have installed but you do. If this is the case then PyInstaller will include said large library for you but ignore it for us - and this can happen recursively to yield enormous builds. Could you share your `xref` file with us? It should be under `build/project/xref-project.html`. Looking at mine I can see PyInstaller wanted to include `gi.repository`, `AppKit`, `Foundation` and `gi` but couldn't due to my not having them. Any of these could be the culprit.

Alternatively if you could build in `onedir` mode then just look inside to see what the new big files are when you include or omit the `import playsound`.

**Comment by Salim9304** [comment] 2020-07-21 22:06
> @htgoebel `playsound` is actually a single python file that wraps the respective builtin sound provider for that platform.
> 
> @Salim9304 I've been unable to reproduce:
> 
> ```
> (venv) D:\PyInstaller-Issues>dir dist
>  Volume in drive D is DATA
>  Volume Serial Number is 76A8-75AB
> 
>  Directory of D:\PyInstaller-Issues\dist
> 
> 21/07/2020  05:34 PM    <DIR>          .
> 21/07/2020  05:34 PM    <DIR>          ..
> 21/07/2020  05:21 PM         8,266,013 test.exe
> 21/07/2020  05:31 PM         8,333,764 test1.exe
>                2 File(s)     16,599,777 bytes
>                2 Dir(s)  193,533,849,600 bytes free
> ```
> 
> The only difference between `test.exe` and `test1.exe` is that `test1`'s source includes the `import playsound` line at the top of the script. I'm running the bleeding edge PyInstaller 4.0 with rebuilt bootloaders, and the script I used was:
> 
> ```python
> import tkinter
> from tkinter import ttk
> import playsound  # This line isn't here in test.exe's source
> 
> root = tkinter.Tk()
> 
> msg = ttk.Label(root, text='It\'s working just fine.')
> 
> msg.grid()
> 
> root.mainloop()
> ```
> 
> @bwoodsend can you try to reproduce? If you can't, please close the issue because until we have a replication of some kind we can't do anything.
Why are you trying to reproduce this issue on windows OS?  If this problem occurs on Linux?

from playsound import playsound
no import playsound.

Yes, playsound is trying to pick up gi.repos.. I don't have it either, and therefore a pass.  I'll see what has grown in size again.  Patience please.

**Comment by Legorooj** [comment] 2020-07-21 22:46
Damn. I don't have access to a Linux box at the moment... And docker isn't working 🤦. @bwoodsend or @htgoebel? You both either have docker working or run Linux.

**Comment by bwoodsend** [comment] 2020-07-21 23:03
Ughh whoopy. Yeah I'll try it on Linux.

**Comment by bwoodsend** [comment] 2020-07-22 00:11
Managed to reproduce on Ubuntu19. It's included `gi` which is making it huge. Working out why `gi` makes it huge now.

**Comment by bwoodsend** [comment] 2020-07-22 00:59
In [hook-gi.repository.GtkSource.py](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-gi.repository.GtkSource.py) the following lines collect the entire of my `/usr/share/` folder:

```
from PyInstaller.utils.hooks import collect_glib_share_files, get_gi_typelibs

datas += collect_glib_share_files('gtksourceview-3.0')
```

Still digging...

**Comment by Salim9304** [comment] 2020-07-22 05:47
**OS GNU/Linux (Kali) steps**

1) pip3 install https://github.com/pyinstaller/pyinstaller/tarball/develop

2) python3 -m PyInstaller --version
4.0.dev0

3) cat 1.py _#let's read the whole project: 1.py_
from playsound import playsound _#importing this [module] https://github.com/TaylorSMarks/playsound) gives fantastic GB size and long build_
print("test")

4) python3 -m PyInstaller --clean project.py
python3 -m PyInstaller --clean 1.py 
72 INFO: PyInstaller: 4.0.dev0
72 INFO: Python: 3.7.5
74 INFO: Platform: Linux-5.3.0-kali2-amd64-x86_64-with-debian-kali-rolling
74 INFO: wrote /home/Salim9304/test/1.spec
105 INFO: UPX is available.
106 INFO: Removing temporary files and cleaning cache in /home/Salim9304/.cache/pyinstaller
107 INFO: Extending PYTHONPATH with paths
['/home/Salim9304/test', '/home/Salim9304/test']
137 INFO: checking Analysis
137 INFO: Building Analysis because Analysis-00.toc is non existent
137 INFO: Initializing module dependency graph...
139 INFO: Caching module graph hooks...
148 INFO: Analyzing base_library.zip ...
3351 INFO: Caching module dependency graph...
3429 INFO: running Analysis Analysis-00.toc
3474 INFO: Analyzing /home/Salim9304/test/1.py
3922 INFO: Processing pre-safe import module hook gi.repository.Gst from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gst.py'.
3924 INFO: Processing module hooks...
3925 INFO: Loading module hook 'hook-gi.repository.Gst.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
11684 INFO: Processing pre-safe import module hook gi.repository.GObject from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GObject.py'.
11685 INFO: Processing pre-safe import module hook gi.repository.GModule from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GModule.py'.
11686 INFO: Processing pre-safe import module hook gi.repository.GLib from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GLib.py'.
11687 INFO: Processing pre-safe import module hook gi.repository.Gio from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gio.py'.
11698 INFO: Loading module hook 'hook-encodings.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
11776 INFO: Loading module hook 'hook-gi.repository.GModule.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
11919 INFO: Loading module hook 'hook-gi.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
11955 INFO: Loading module hook 'hook-gi.repository.GLib.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
12287 INFO: Loading module hook 'hook-xml.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
12381 INFO: Loading module hook 'hook-gi.repository.GObject.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
12521 WARNING: Hidden import "gi._gobject" not found!
12522 INFO: Loading module hook 'hook-gi.repository.Gio.py' from '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
13547 INFO: Looking for ctypes DLLs
13549 INFO: Analyzing run-time hooks ...
13552 INFO: Including run-time hook '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gstreamer.py'
13553 INFO: Including run-time hook '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gio.py'
13554 INFO: Including run-time hook '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_glib.py'
13555 INFO: Including run-time hook '/home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gi.py'
13560 INFO: Looking for dynamic libraries
19012 INFO: Looking for eggs
19013 INFO: Python library not in binary dependencies. Doing additional searching...
19051 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
19055 INFO: Warnings written to /home/Salim9304/test/build/1/warn-1.txt
19075 INFO: Graph cross-reference written to /home/Salim9304/test/build/1/xref-1.html
23520 INFO: checking PYZ
23520 INFO: Building PYZ because PYZ-00.toc is non existent
23520 INFO: Building PYZ (ZlibArchive) /home/Salim9304/test/build/1/PYZ-00.pyz
23845 INFO: Building PYZ (ZlibArchive) /home/Salim9304/test/build/1/PYZ-00.pyz completed successfully.
23848 INFO: checking PKG
23848 INFO: Building PKG because PKG-00.toc is non existent
23848 INFO: Building PKG (CArchive) PKG-00.pkg
23900 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
23901 INFO: Bootloader /home/Salim9304/.local/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
23902 INFO: checking EXE
23902 INFO: Building EXE because EXE-00.toc is non existent
23902 INFO: Building EXE from EXE-00.toc
23903 INFO: Appending archive to ELF section in EXE /home/Salim9304/test/build/1/1
23921 INFO: Building EXE from EXE-00.toc completed successfully.
24226 INFO: checking COLLECT
24226 INFO: Building COLLECT because COLLECT-00.toc is non existent
24227 INFO: Building COLLECT COLLECT-00.toc
260272 INFO: Building COLLECT COLLECT-00.toc completed successfully.

5) du -shc _#size in the given directory (only project 1.py)_
### 3,1G

6) ls
1.py  1.spec  build  dist  project.spec  pycache

7) tree -hpDa dist/ _#file size and number_
**14701 directories, 181333 files**

8) ls -shaR ./* | sort -h _#display the largest files at the end of the list_
...
6,4M ext_server_python.x64.dll
6,9M kernel-x86_64-pc-linux-gnu-avx2.bc
6,9M kernel-x86_64-pc-linux-gnu-avx_fma4.bc
6,9M kernel-x86_64-pc-linux-gnu-sse41.bc
7,0M kernel-x86_64-pc-linux-gnu-GENERIC.bc
7,0M kernel-x86_64-pc-linux-gnu-sse2.bc
7,0M kernel-x86_64-pc-linux-gnu-ssse3.bc
7,0M plotly.js
7,1M kernel-x86_64-pc-linux-gnu-avx.bc
7,1M kernel-x86_64-pc-linux-gnu-avx_f16c.bc
7,2M kernel-x86_64-pc-linux-gnu-avx512.bc
7,2M latin1.chr
7,2M latin1.chr
7,8M GeoIPv6.dat
8,0M kali-blue-matrix.png
 8,4M gshhsmeta_h.dat
8,9M nokogiri-1.10.7.gem
8,9M utf8.chr
8,9M utf8.chr
  11M gshhsmeta_f.dat
 12M metasploit-payloads-1.3.83.gem
  13M UScounties.shp
 14M libavcodec.so.58
  15M gshhs_h.dat
 15M IpToCountry.csv
 16M libx265.so.179
  18M rivers_f.dat
 22M metasploit_payloads-mettle-0.5.16.gem
 24M Analysis-00.toc
 24M COLLECT-00.toc
 26M libicudata.so.63
 51M rockyou.txt.gz
  81M gshhs_f.dat

**Comment by Legorooj** [comment] 2020-07-22 07:40
@Salim9304 hang on a second. You're not using the `--key` option in your latest example. It had been my understanding that that was the problem?

**Comment by Salim9304** [comment] 2020-07-22 08:50
> @Salim9304 hang on a second. You're not using the `--key` option in your latest example. It had been my understanding that that was the problem?

I originally thought the problem was due to "--key".  But later I started digging.  And I found that the problem arises solely from the "playsound" module.

Option "--key" or without option, the result is the same: the size is huge and the error is exclusively in pyinstaller v4.0 due to the "playsound" module

**Comment by Salim9304** [comment] 2020-07-22 09:02
I have two lines of code in my project (1.py), module import and print.  But look, pyinstaller v4.0 pulls all files in a row from the system, even the dictionary: rockyou.txt.gz. 
🙄

There is nothing like this in pyinstallet v3.6!

**Closed** 2020-08-08 03:22 UTC
Labels: bug, state:verify
