### ISSUE TITLE
3.2:  _MEIxxxxxx folder is not removed if the program is killed sig term

### ISSUE THREAD

**Issue by edwardcallahan** [pyinstaller/pyinstaller#2379] opened 2017-01-12 23:29 UTC
Observed with Pyinstaller 3.2 on Ubuntu 16 and CentOS7
Test fails to run at all (seg fault) on 3.3.dev0+c778285

Steps to reproduce
* Example code (below) is used to create long running process. Save as test.py
* `pyinstaller --onefile test.py`
* run `dist/test`
* `kill <pid>` of above process

Actual:  _MEIxxxxxx folder remains
Expected: _MEIxxxxxx folder removed

Example app
```
#! python
import sys

ans = True

while ans:
    question = input("Ask the magic 8 ball a question: (press enter to quit) ")
    
    answers = 1
    
    if question == "":
        sys.exit()
    
    elif answers == 1:
        print ("It is certain")
```

**Comment by codewarrior0** [comment] 2017-01-12 23:32
The built app will launch two processes. If you kill the child process, the parent will clean up the temp folder. It looks like you killed the parent process instead.

**Comment by huntc** [comment] 2017-01-12 23:34
Should the parent not propagate SIGTERM to its children? SIGTERM indicates a graceful termination.

**Comment by codewarrior0** [comment] 2017-01-12 23:42
[I think that's what this code here does.](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_utils.c#L798)

**Comment by codewarrior0** [comment] 2017-01-12 23:43
[Here, the SIGTERM is sent back to the parent](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_utils.c#L825) which means it kills itself before it gets a chance to clean up.

**Comment by huntc** [comment] 2017-01-12 23:45
Thanks for the diagnosis. So, what do you recommend should be done? Clearly not cleaning up on a SIGTERM isn't good. We're seeing the tmp folder be littered with these folders as our program is reasonably receiving SIGTERM.

**Comment by edwardcallahan** [comment] 2017-01-12 23:46
It doesn't matter which process I kill, 
Example, killing 28574 or 28575 leaves the folder. 
Their parent is my shell
```
0 S centos   28574 28144  1  80   0 -  2473 wait   23:42 pts/0    00:00:00 /home/centos/dist/test
0 S centos   28575 28574  0  80   0 - 33778 n_tty_ 23:42 pts/0    00:00:00 /home/centos/dist/test
0 R centos   28577 28448  0  80   0 - 28162 -      23:42 pts/1    00:00:00 grep --color=auto test

[centos@10 ~]$ ps -efl | grep 28144
0 S centos   28144 28143  0  80   0 - 28846 wait   23:15 pts/0    00:00:00 -bash
0 S centos   28574 28144  0  80   0 -  2473 wait   23:42 pts/0    00:00:00 /home/centos/dist/test
0 S centos   28580 28448  0  80   0 - 28163 pipe_w 23:42 pts/1    00:00:00 grep --color=auto 28144
```

**Comment by htgoebel** [comment] 2017-01-13 09:17
> the SIGTERM is sent back to the parent which means it kills itself before it gets a chance to clean up.

This was introduced in 7e808948ab (it's been in a different file at that time), based on issue #489. Your comment sounds like this needs to be refined.

**Comment by huntc** [comment] 2017-02-27 19:37
Any progress guys? This is quite an important problem as /tmp can fill easily and cause system issues... Thanks.

**Comment by WhoAteDaCake** [comment] 2018-10-31 14:21
This is still happening and can lead to up do 280mb entries in /tmp

**Comment by htgoebel** [comment] 2018-11-01 10:37
@WhoAteDaCake You did not state the version of PyInstaller you used for testing. Please try the most resent version of PyInstaller. Please be more careful when posting comments, as such mistakes cost the rare spare time of us volunteers. Thanks.

**Comment by WhoAteDaCake** [comment] 2018-11-05 10:14
@htgoebel My apologies. But it seems to still happen on version 3.4. Ubuntu 18.04 and Windows 10

**Comment by ToskaVex** [comment] 2019-01-16 08:41
To add to this, this is reproducible on Windows as well when you're using the console for your program.
If you close a window using the exit button at the top of the window, a MEI folder is left behind.
Even if you use atexit or try and catch the SIGTERM using win32api:

https://stackoverflow.com/questions/5180440/how-to-capture-a-command-prompt-window-close-event-in-python

Neither will work. I have found that closing a program that is graphical, like Tkinter, or QT, works properly and the MEI folder is removed.

Using: Python 3.7, Pyinstaller 3.4
Steps to reproduce: Make a simple onefile build of pyinstaller that uses the Windows console. Close this window with the window "X". Look and see the "_MEI" folder has been left behind. Running the program again simply creates another "_MEI" folder.

**Comment by clragon** [comment] 2019-02-20 19:21
This is still a problem to this day, on the newest version of pyinstaller. 

I would love if there could be any progress in this, because as mentioned above, filling up the temp folder can lead to issues and is a waste of space.

**Comment by ToskaVex** [comment] 2019-02-22 03:17
@clragon @huntc In the meantime if you'd like you can write an arbitrary function that's called on program start that iterates through the temp folder- checks for "_MEI" in a folder name, checks that the folder isn't in sys._MEIPASS, then uses shutil.rmtree() to wipe the folder out. It's hacky, but it works...

**Comment by clragon** [comment] 2019-02-26 16:13
@ToskaVex I guess that would work but only if the program doing this doesn't get killed either.
Not so clean, too, because then we have to include that in every project. 

Would just be nice if this issue could be fixed.

**Comment by dogod621** [comment] 2019-04-11 06:31
Every time I run my exe that is create by pyinstaller...
It create a new _MEI dir and use 700mb, and did not clean those file after process exit.... 


![MEI](https://user-images.githubusercontent.com/6807005/55935471-4d036b00-5c66-11e9-99ed-bfa2d5e08ea3.jpg)

**Comment by onais** [comment] 2019-08-29 07:58
I'm struggling with the same problem, in Manjaro its even more annoying since /tmp sits in RAM so after i launch the app several times it eats up all of my RAM.  

#905 and #902 suggests close button might not be handled correctly, can anyone share some thoughts about how can I work around the problem?

**Comment by eeriks** [comment] 2020-01-17 15:40
> @clragon @huntc In the meantime if you'd like you can write an arbitrary function that's called on program start that iterates through the temp folder- checks for "_MEI" in a folder name, checks that the folder isn't in sys._MEIPASS, then uses shutil.rmtree() to wipe the folder out. It's hacky, but it works for me currently...

Also won't work when running multiple processes made with pyinstaller as the newest will kill the rest.

-----

Also having this issue:
- Ubuntu 18.04.3 LTS
- Python 3.7.2, 
- PyInstaller==3.6

**Comment by clragon** [comment] 2020-02-17 21:50
Looks like this will never get fixed since the entire project got discontinued.

**Comment by VessToska** [comment] 2020-03-15 20:05
@clragon Do you have a source on that...? I'm not seeing any news in that regard, not sure what I'm missing here.

**Comment by clragon** [comment] 2020-03-15 20:43
@VessToska 
cant remember how I got to that conclution, but it seems like they are currently on a donation model, and not meeting their planned support. 

I wouldnt assume this issue here to be fixed. ever.

**Comment by Wlodarski** [comment] 2020-03-31 13:35
> > @clragon @huntc In the meantime if you'd like you can write an arbitrary function that's called on program start that iterates through the temp folder- checks for "_MEI" in a folder name, checks that the folder isn't in sys._MEIPASS, then uses shutil.rmtree() to wipe the folder out. It's hacky, but it works for me currently...
> 
> Also won't work when running multiple processes made with pyinstaller as the newest will kill the rest.

You won't interfere with concurrent pyinstaller instances if you leave read only folders alone.

```python

def cleanup_mei():
    """
    Rudimentary workaround for https://github.com/pyinstaller/pyinstaller/issues/2379
    """
    import sys
    import os
    from shutil import rmtree

    mei_bundle = getattr(sys, "_MEIPASS", False)

    if mei_bundle:
        dir_mei, current_mei = mei_bundle.split("_MEI")
        for file in os.listdir(dir_mei):
            if file.startswith("_MEI") and not file.endswith(current_mei):
                try:
                    rmtree(os.path.join(dir_mei, file))
                except PermissionError:  # mainly to allow simultaneous pyinstaller instances
                    pass

```
Of course, ideally, we want this issue solved from within pyinstaller rather than applying hacks on every app that runs under pyinstaller. This is only a short term workaround.

**Comment by RiccardoManfrin** [comment] 2020-06-03 20:29
Just for the records, `docker-compose 1.25.5 build 8a1c60f6` uses an affected version of pyinstaller.. which means that stopping containers with docker-compose stop can easily lead to leaked `_MEI` folders

**Comment by Pilonetto** [comment] 2020-11-05 17:10
> > > @clragon @huntc In the meantime if you'd like you can write an arbitrary function that's called on program start that iterates through the temp folder- checks for "_MEI" in a folder name, checks that the folder isn't in sys._MEIPASS, then uses shutil.rmtree() to wipe the folder out. It's hacky, but it works for me currently...
> > 
> > 
> > Also won't work when running multiple processes made with pyinstaller as the newest will kill the rest.
> 
> You won't interfere with concurrent pyinstaller instances if you leave read only folders alone.
> 
> ```python
> def cleanup_mei():
>     """
>     Rudimentary workaround for https://github.com/pyinstaller/pyinstaller/issues/2379
>     """
>     import sys
>     import os
>     from shutil import rmtree
> 
>     mei_bundle = getattr(sys, "_MEIPASS", False)
> 
>     if mei_bundle:
>         dir_mei, current_mei = mei_bundle.split("_MEI")
>         for file in os.listdir(dir_mei):
>             if file.startswith("_MEI") and not file.endswith(current_mei):
>                 try:
>                     rmtree(os.path.join(dir_mei, file))
>                 except PermissionError:  # mainly to allow simultaneous pyinstaller instances
>                     pass
> ```
> 
> Of course, ideally, we want this issue solved from within pyinstaller rather than applying hacks on every app that runs under pyinstaller. This is only a short term workaround.

Call `cleanup_mei()` in my main.py or .spec file?

**Comment by Kalp-S** [comment] 2021-01-20 22:39
Hello, I seem to be having the same issue with docker-compose version 1.24, does anyone know if this issue has been addressed in newer versions of docker? Is it worth the upgrade?

**Comment by Dariusz1989** [comment] 2021-01-31 14:03
Hey
Having the same issue on windows.
Is there a way where we could specify the name of the watcher-process & its icon? 
If users see 1 app with the same name hell kill both, breaking the clean up. Perhaps if I could give it a different name/icon then user won't see the process and killing just the app properly trigger the parent process to clean up.

Hints/ideas?

**Comment by AdrienLF** [comment] 2021-03-05 16:47
Same issue on mac, this is a shame :(

**Comment by izenk** [comment] 2021-03-31 09:15
Faced same problem
Ubuntu 18.04.5 LTS
docker-compose version 1.27.4, build 40524192
Almost after every cycle of docker-compose stop/down start/up -d new folder _MEI* appears in /tmp.
Noticed that when monitoring alerted about low disk space. tmp was about 5GB

**Comment by johnesau** [comment] 2021-06-14 20:18
This issue still happens in Windows. C:\User\Appdata\Local\Temp folder grows to 80+ GB with hundreds of thousands of folders over a period of years in 24/7 environment. Don't know exactly which version of PyInstaller was used to compile this executable but the work was done circa May 2019.

**Comment by anborg** [comment] 2021-06-22 21:36
@johnesau , use this hack in your startup script,  until a fix is available.

![image](https://user-images.githubusercontent.com/56970398/123002719-3990d600-d380-11eb-8c0c-06eb704aa628.png)

**Comment by RSR-YAMAKOSHI-NOBUHIKO** [comment] 2021-08-20 04:57
使用中のフォルダは消さずに、削除コマンドでフォルダの中身も影響ないように処理する必要あり

**Comment by Akascape** [comment] 2022-06-22 14:35
This is a huge issue, I don't know why it is not fixed yet. It leaves so much temp if the window is crashed or closed with cmd.

I tried runtime-tmpdir but the same happens with that also, but with this the temp is created in one place within the exe folder which can be removed by the user easily if noticed. Beside this nothing will work without hacks, the one dir is so messy for the end user (only good with installers).

I hope someday it will be fixed :)

**Comment by Akascape** [comment] 2022-06-23 16:33
@legorooj I have an idea to fix this.
First it will create the temp "_MEIxxxxxx" dir. Everything will work the same.
(It will be better if pyinstaller makes a specified folder with the application name inside temp and extracts the '_MEI' there only.)

Then suppose if the app is crashed and it leaves the temp there, then in the next boot it will search if any folder is present in the temp folder and delete all those if exists. But deleting will be more specific. **First it will try to delete one file from the  _MEI folder that can be python.dll or any specific file that runs along the program. If that specific file gets deleted then remove the whole dir.** If it can't delete that specific file it means one instance is still running and hence the folder will not be removed. By this instances will be safe and leftover/crashed stuff will be removed.

This can be done with a hook file also but will be good if pyinstaller implement something like this.
What you guys think?

**Comment by Legorooj** [comment] 2022-07-02 09:01
@Akascape that's worth considering as a temporary fix. @rokm @bwoodsend thoughts? I

**Comment by rokm** [comment] 2022-07-02 09:23
That's a hard no from me. It might work on Windows where a loaded DLL ends up locked and cannot be removed, but other OSes have no such constraints.

**Comment by rokm** [comment] 2022-07-02 11:06
Also note that this issue is about linux (well, the POSIX codepath). As noted in https://github.com/pyinstaller/pyinstaller/issues/2379#issuecomment-272396574, 7e808948ab8af3e30066cfccf91d8fb552655f35 introduced re-raising the signal from the child process:
https://github.com/pyinstaller/pyinstaller/blob/4b9fd01d7dc5a0aae3ba7c100437547915464f0e/bootloader/src/pyi_utils.c#L1113-L1118
This is performed immediately after the child exits, which is too soon; it terminates the parent process before it has a chance to clean up the temporary directory. Storing the signal information and performing the re-raise after the cleanup (i.e., [here](https://github.com/pyinstaller/pyinstaller/blob/4b9fd01d7dc5a0aae3ba7c100437547915464f0e/bootloader/src/pyi_main.c#L416)) should fix this particular problem.

The temporary directory being left behind on Windows when user closes their application's console window is a different issue, tracked under feature request #6591.

**Comment by bwoodsend** [comment] 2022-07-02 12:51
> @Akascape that's worth considering as a temporary fix. @rokm @bwoodsend thoughts? I

Likewise, that's a hard no from me. Just looking at the Windows side, it would have to be a DLL file since no other file is expected to be loaded from start to finish but even that isn't safe because gcc has started producing DLLs that don't leave the file open and UPX loads DLLs into memory on startup then closes the file so both of those cases would slip through.

**Closed** 2022-07-11 09:07 UTC
Labels: @high, bug

**Comment by Akascape** [comment] 2022-07-11 12:21
@rokm I got the notification of this issue as closed, I think the temp folder issue is fixed. 
When will we get the release for this?

Thanks...

**Comment by rokm** [comment] 2022-07-11 18:06
> @rokm I got the notification of this issue as closed, I think the temp folder issue is fixed. When will we get the release for this?
> 
> Thanks...

Considering the last release was just couple of days ago, I wouldn't expect a new one within a month... in the meantime, you can use the `develop` branch, but in this case, don't forget to rebuild the bootloader.

**Comment by bwoodsend** [comment] 2022-07-11 18:19
e.g. Using:
```bash
PYINSTALLER_COMPILE_BOOTLOADER=1 pip install https://github.com/pyinstaller/pyinstaller/archive/refs/heads/develop.zip
```
