### ISSUE TITLE
Failed to execute script pyi_rth_multiprocessing

### ISSUE THREAD

**Issue by aleksaa01** [pyinstaller/pyinstaller#4066] opened 2019-02-12 17:20 UTC
I tried to build my side project called "QGmailer"(It's on my github). But I get "Failed to execute script pyi_rth_multiprocessing" error. This happens both on Windows 7 and on Windows 10(not that I tried any other OS). I am using Python 3.6.8 and Pyinstaller 3.4. This project was originally written in PyQt5(which was working just fine with pyinstaller), but because they dropped support for QWebEngine I had to switch to **PySide2**.

Calling pyinstaller without --windowed, and using cmd to run the executable yields this error:

```
D:\Executables\QGmailer\dist\QGmailer>QGmailer.exe
Exception: [Errno 2] No such file or directory: 'D:\\support\\signature\\loader.
py'
Traceback (most recent call last):
  File "pyscript", line 23, in bootstrap
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\support\\signature\
\loader.py'
AttributeError: module 'signature_loader' has no attribute 'pyside_type_init'
SystemError: could not initialize part 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py"
, line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\projects\qgmailer\venv\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\projects\qgmailer\venv\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing\context.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\projects\qgmailer\venv\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "multiprocessing\process.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\projects\qgmailer\venv\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "signal.py", line 45, in <module>
  File "D:\Python36\lib\functools.py", line 61, in update_wrapper
    value = getattr(wrapped, attr)
SystemError: <method-wrapper '__get__' of getset_descriptor object at 0x00000000
0012D708> returned a result with an error set
[3188] Failed to execute script pyi_rth_multiprocessing
```

**Comment by htgoebel** [comment] 2019-02-13 09:34
Duplicate of #4040

**Closed by htgoebel** 2019-02-13 09:34 UTC

**Comment by AhmedElmanawy** [comment] 2019-07-01 02:16
It is the same problem (Failed to execute script pyi_rth_multiprocessing), and the solution doesn't work with me.
