### ISSUE TITLE
windows 10 problem

### ISSUE THREAD

**Issue by dibifirst** [pyinstaller/pyinstaller#2312] opened 2016-12-13 12:53 UTC
I have received bad reply probably because the question haven't been understood.
I tell you that the problem is due that when I running my  .exe program and the program perform the self.quit (I have try even with other exit types) windows give me one error saying that program ended abnornamally. This not happen under windows 7. The only strange thing is what i have highlight in my previous message. My environment is windows 10 64 python 3.5.2.

**Comment by dibifirst** [comment] 2016-12-13 19:13
pls help me !!!

**Comment by dibifirst** [comment] 2016-12-14 14:38
I submit more information:
import sys
import csv
import os
import time
import datetime
import locale
import subprocess
import win32print
import win32ui
import win32con
import tkinter
from tkinter import *
from tkinter import ttk
from tkinter import filedialog
from tkinter.filedialog import asksaveasfilename
from tkinter.filedialog import askopenfilename
class MainWindow(Frame):
    def __init__(self, parent):
        Frame.__init__(self, parent)   
        self.parent = parent        
        self.buildUI()
    def buildUI(self):          
# window title
        self.parent.title("Employee Working hours check")
# window config
        self.parent.minsize(width=1024, height=320)
        self.parent.grid_columnconfigure(9, weight=1)
        self.parent.rowconfigure(12, weight=1)
        self.parent.geometry("1024x480")
 # menu bar (Settings, About, Exit)
        self.menubar = Menu(self.parent)
        self.filemenu = Menu(self.menubar, tearoff=0)
        self.menubar.add_cascade(label="File", menu=self.filemenu)
        self.filemenu.add_command(label="Settings")
        self.filemenu.add_command(label="About")
        self.filemenu.add_separator()
        self.filemenu.add_command(label="Exit", command=self.quit)        
        self.parent.config(menu=self.menubar)

practically when I press exit, winodes give em error thta program end abnormally and looking for solution... This not happen running th eprogram under IDLE Python. 
Any idea ?

**Comment by htgoebel** [comment] 2016-12-16 09:54
Please provide a *minimal* example and the *exact* error message. Try running from console (cmd window) and use `--onedir`.

**Comment by dibifirst** [comment] 2016-12-16 12:07
thank you for your reply.I have try to compile with --onedir, but thr result is olways the same. Seems that the problem is import of win32 libraries, that if I remove it working normally. Anyway i attach the copy of the screen. Sorry it is in italian, but the windows error say: "testwin.exe has stapped working. Windows: it is a problem that prevents proper operation of the program" I have compile the prortam with: "pyinstaller.exe --onefile --icon=count.ico testwin.py"
![image](https://cloud.githubusercontent.com/assets/24414707/21262211/660589a6-c390-11e6-9c37-ea0d989e65b9.png)

**Comment by dibifirst** [comment] 2016-12-16 12:17
after compila with --onedir under cmd the program give the same error. The result of the comile dir is:
![image](https://cloud.githubusercontent.com/assets/24414707/21262509/ed574a9c-c391-11e6-80eb-703d1f888694.png)

**Comment by dibifirst** [comment] 2016-12-17 16:30
I made new installation on other PC with windows10 and the problem is always the same (Crash when i press Quit button) Really I don't know what I can do. I try even to use cx_freeze tools and in ths case I receive back the error on TCL_LIBRARY. So windows 10 and Python 3.5.2 seem that not survive together. Anyway here is the list of my pip environmet for your better understand. 
![image](https://cloud.githubusercontent.com/assets/24414707/21288250/3229d9b8-c47e-11e6-9cd4-f65ef0a414aa.png)
What is strange is that using idle interpeter everythink working properly. Really I hope that somebody can help me on the matter as soon as possible.

**Comment by tallforasmurf** [comment] 2016-12-17 17:00
It is very common that a program will work correctly when running from idle or from the command line (you open a command window and enter `python testwin.py`) -- and then it will fail when bundled as an app. This is a clear sign that something is not being included in the app.

Understand that PyInstaller and cxFreeze and py2exe are not "compilers" (they do not convert your python source into machine code). They collect a bundle (*raccogliere un fascio*, grazie Google translate) by finding all the python code modules, all the library .dll files, and a copy of the Python interpreter itself, and puttin all in one file or folder.

How does this *fascio* run? It starts in the PyInstaller "boot loader" which loads the Python interpreter from the bundle, tells it "for any import, look here in this bundle, no other place", and tells it to run your source program. The most common reason for a failure then is that some piece was left out of the bundle. But which piece?

This is why @htgoebel  told you to use `--onedir`. You can easily look in the folder and see exactly what files were collected. That tells you what *was* collected, but not what was left out. That is in the messages in the file `build\testwin\warntestwin.txt` where you will find probably many warnings about "module not found".

Something else to ask: that dialog box, "testwin.exe ha smesso..." -- it does not look like a normal Windows error dialog. What is that icon in the corner? Is that dialog coming from Tcl perhaps?

**Comment by dibifirst** [comment] 2016-12-17 17:00
[testwin.txt](https://github.com/pyinstaller/pyinstaller/files/658944/testwin.txt)
herewith is the copy semplified of the program i use for your prompt understanding.

**Comment by htgoebel** [comment] 2016-12-17 17:06
@dibifirst I asked for a *minimal* example. Please strip down your code to the bare minimum where the error occurs. We are all volunteers and if you are too lazy to strip down you program, why should we spend time trying to find the cause?

**Comment by dibifirst** [comment] 2016-12-17 17:10
I sorry to bother you, really. I don't know what i have to do...

**Comment by tallforasmurf** [comment] 2016-12-17 17:24
I have no way to test, but (only guessing), make comments of all lines from `# menu bar (Settings, About, Exit)`  through `# prepare`. That should give you nothing but an empty window. Bundle it, start it, click the red [X] to make it quit, does it fail? If not, add back just one piece at a time until it does fail.

**Comment by dibifirst** [comment] 2016-12-17 17:40
thank Nat for you suggestion. . The problem is the "command=self.quit", on any program exit.

**Comment by dibifirst** [comment] 2016-12-17 23:36
as suggested by tallforasmurf,  I put a comment on every single line and found the lines that stop me leaving from the program. The lines are:
import win32print
import win32ui
import win32con
What I have to do?

**Comment by tallforasmurf** [comment] 2016-12-18 01:58
Thank you for doing this.

So if your program imports any of these, that error message appears when the program ends, yes?

Also you have looked at the `build\warn*.txt` file? And does it say any of these were not found?

These names are, I believe, parts of the pywin32 package. It is required by PyInstaller and supposedly automatically installed with PyInstaller if you did not have it already.

Anybody who actually knows Windows want to help out here? I can think of all sorts of possibilities, like -- wrong version of pywin32 for Win10? Installed in the wrong place?

**Comment by dibifirst** [comment] 2016-12-18 10:41
really thank for your suggestion. I confirm that if I import modules, the program not end, but print normally. If I  omitted them the program end normally. So Ivhope that somebody can help me in this matter, that probably are related to windows 10, because on windows 7 working without any problem. Moreover for you prompt inforamtion I attach the build\warn*.txt.
[warntestwin.txt](https://github.com/pyinstaller/pyinstaller/files/659360/warntestwin.txt)

**Comment by stephenrauch** [comment] 2016-12-18 15:11
These are the win32 bindings.  Lot of magic can be had through them.  Did I read you right?  This program, with nothing more included, fails to exit on windows 10 after being frozen:

```python
import win32print
import win32ui
import win32con
```
Or is there more included?  If there is more included, start taking out the other lines.  This should allow you to see what is interacting with what.

Also, what is the error message when windows exits?

**Comment by tallforasmurf** [comment] 2016-12-18 16:23
The message is in a screen grab above,

> testwin.exe ha smesso di funzionare
Windows: si è verificato un problema che impedisce il funzionamento corretto del programma. Se è disponibile una soluzione, verra chìuso il programma e inviata una notifica automatica."

which Google translate with my help renders as, 

> testwin.exe stopped working
Windows: it is a problem that prevents proper operation of the program. If a solution is available, Windows will close the program and notify you automatically.

But the message box (see above) does not look to me like a proper Windows dialog. I can't make out the icon in the corner, is it Tkinter's?

**Comment by dibifirst** [comment] 2016-12-18 18:38
the program open two windows: the first is for Tkinter, the second one is cmd.exe. But the error is on close and I don't understand over. The only sure think is that when I remark these imports libraries, the program close normally. So I think is something related Win32 libraries (expecially Win32UI) that still generate some warning during running of Pyinstaller. This not happen on win 7, but only on Win 10.

**Comment by stephenrauch** [comment] 2016-12-18 19:05
I would look suspiciously at the cmd window.  They are notoriously odd. Do you close it before terminating the program?

**Comment by stephenrauch** [comment] 2016-12-19 01:08
@dibifirst , you should look in the event logger and post anything related.

You should also start removing other stuff besides win32 stuff to find potential interactions.

**Comment by htgoebel** [comment] 2017-08-01 08:55
@dibifirst Any news on this? Oherwise I'd close the issue.

**Comment by htgoebel** [comment] 2017-12-02 15:10
No news, closing.

**Closed by htgoebel** 2017-12-02 15:10 UTC
Labels: need info, Windows
