### ISSUE TITLE
Using pycryptodome with pyinstaller's byte code encryption

### ISSUE THREAD

**Issue by iMHLv2** [pyinstaller/pyinstaller#3093] opened 2017-12-09 16:03 UTC
I've seen a lot of issues here related to using pyinstaller to freeze binaries that import pycryptodome, but it doesn't seem like pyinstaller's own use of the library is correct, with respect to the byte code encryption feature. 

Environment: 

* Windows 10 x64 with Python 3.6.3
* Pyinstaller dd7aefc2ed20a178f04b2dbb2a9dcbcf9dc8bad6
* Pycryptodome 3.4.7

Pyinstaller's `pyz_crypto.py` and `pymod02_archive.py` both reference `Crypto.Cipher.AES` which would either require pycrypto (no longer supported) or the `pycryptodome` package with the `Crypto` namespace....not the `pycryptodomex` package with `Cryptodome` namespace, however the pyinstaller hook is only for `Cryptodome`. 

Regardless of the namespace, both of the aforementioned pyinstaller files do `assert type(key) is str` which will raise on python3 because all inputs to pycryptodome (the `key`, `data`, and `iv`) must all be `bytes` and not `str`). 

After changing the assertion to `assert type(key) in [str, bytes]` I was able to produce an exe with encrypted byte code, but it failed to run (`Failed to execute script pyiboot001_bootstrap`). It seems `pymod02_archive.Cipher._import_asesmod()` is unable to import the library in order to decrypt the byte code. 

I've tried various combinations of changing pyinstaller's references from `Crypto.Cipher.AES` to `Cryptodome.Cipher.AES` and also making similar changes in the pyinstaller hook file for Cryptodome, but so far I haven't been able to find a working method.

**Comment by htgoebel** [comment] 2017-12-11 12:40
Thanks fro you analyzis. The crypto feature is currently not working, see #2365.

The requirement for byte-encryption is a commercial one (free software does not require byte-encryption since the cod is available anyway). So if you want this to be fixed, either submit a pull-request or drop ma an email an we'll arrange a commercial agreement.

**Comment by htgoebel** [comment] 2017-12-11 12:41
Duplicate of #2365

**Closed by htgoebel** 2017-12-11 12:40 UTC
