### ISSUE TITLE
Operation not permitted error when using MAC OS X 10.11.1

### ISSUE THREAD

**Issue by roco1** [pyinstaller/pyinstaller#1650] opened 2015-11-01 10:46 UTC
I'm getting an "Operation not permitted" error when using MAC OS X El Capitan (10.11.1):

```
35 INFO: PyInstaller: 3.0
35 INFO: Python: 2.7.10
40 INFO: Platform: Darwin-15.0.0-x86_64-i386-64bit
41 INFO: wrote /Users/rbc/Transporter/MainShare/Projects/bouncer/Bouncer.spec
41 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/bin/python

1052 INFO: UPX is not available.
1053 INFO: Extending PYTHONPATH with /Users/rbc/Transporter/MainShare/Projects/bouncer
1053 INFO: checking Analysis
1054 INFO: Building Analysis because out00-Analysis.toc is non existent
1054 INFO: Initializing module dependency graph...
1056 INFO: Initializing module graph hooks...
1107 INFO: running Analysis out00-Analysis.toc
1114 INFO: Analyzing /Users/rbc/Transporter/MainShare/Projects/bouncer/bouncer.py
6689 INFO: Processing pre-find module path hook   distutils
9150 INFO: Looking for import hooks ...
9152 INFO: Processing hook   hook-distutils.py
9152 INFO: Processing hook   hook-sysconfig.py
9153 INFO: Processing hook   hook-xml.py
9214 INFO: Processing hook   hook-httplib.py
9215 INFO: Processing hook   hook-encodings.py
9685 INFO: Processing hook   hook-xml.sax.py
9706 INFO: checking Tree
9706 INFO: Building Tree because out00-Tree.toc is non existent
9706 INFO: Building Tree out00-Tree.toc
9709 INFO: Looking for ctypes DLLs
9728 INFO: Analyzing run-time hooks ...
9733 INFO: Including run-time hook 'pyi_rth_pkgres.py'
9745 INFO: Looking for dynamic libraries
9946 INFO: Looking for eggs
9947 INFO: Python library not in binary depedencies. Doing additional searching...
9949 INFO: Using Python library /System/Library/Frameworks/Python.framework/Versions/2.7/Python
9956 INFO: Warnings written to /Users/rbc/Transporter/MainShare/Projects/bouncer/build/Bouncer/warnBouncer.txt
9960 INFO: checking PYZ
9960 INFO: Building PYZ because out00-PYZ.toc is non existent
9960 INFO: Building PYZ (ZlibArchive) /Users/rbc/Transporter/MainShare/Projects/bouncer/build/Bouncer/out00-PYZ.pyz
10422 INFO: checking PKG
10422 INFO: Building PKG because out00-PKG.toc is non existent
10422 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/building/api.py", line 431, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/building/api.py", line 233, in __init__
    self.__postinit__()
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/building/api.py", line 295, in assemble
    dist_nm=inm)
  File "/Users/rbc/Library/Python/2.7/lib/python/site-packages/PyInstaller-3.0-py2.7.egg/PyInstaller/building/utils.py", line 242, in checkCache
    shutil.copy2(fnm, cachedfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/rbc/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so'
```

I'm guessing this is because of System Integrity Protection in El Capitan - shutil.copy2 calls copystat, which attempts to use os.chflags to set flags on the destination file to match the source.  I'm guessing that the source file it's trying to copy into the cache has the new "restricted" flag - and the attempt to set that flag using os.chflags raised an exception with the "Operation not permitted" error.  copystat explicitly ignores a couple of errors ("EOPNOTSUPP" and "ENOTSUP"), but not this one.

I think this is similar to the problem mentioned right at the end of issue #1586, but I couldn't see another new issue raised to report it.

**Comment by roco1** [comment] 2015-11-01 11:00
I've tried this again, with SIP disabled (csrutil disable), and I was still only able to avoid this error by running as root (using sudo).  When I enabled SIP again (csrutil enable), I'm now seeing the same behaviour - when I run as root, it works fine.
So, I only see "Operation not supported" when not running as root.  I'm not sure if this is expected behaviour, but I'm now thinking it's not directly connected to SIP.

**Comment by JokerQyou** [comment] 2015-11-02 10:17
While it seems like this could be avoid by running pyinstaller as `root` user, I think this is not the expected behaviour -- you cannot just run everything as `root`. What if there's a misspell in the script, thus running as `root` deleted all your important files?

I also tried the latest pyinstaller from `develop` branch and this is not yet fixed, I have the error log as follows:

```log
16095 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/Users/joker/Works/edo/assistent/test/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.1.dev0+1183c04', 'console_scripts', 'pyinstaller')()
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/build_main.py", line 738, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 55, in <module>
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/api.py", line 444, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/api.py", line 235, in __init__
    self.__postinit__()
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/api.py", line 298, in assemble
    dist_nm=inm)
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/utils.py", line 242, in checkCache
    shutil.copy2(fnm, cachedfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/joker/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so'
```

**Comment by matysek** [comment] 2015-11-04 08:54
@JokerQyou What are the symptoms?
* Does this happen only for the builtin Python in OS X?
* What code? Just even helloworld?
* What are the permissions of file `/Users/joker/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so`?
```
ls -l /Users/joker/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so
```
* This is on my mac. Is it similar?
```
% ls -lah Library/Application\ Support/pyinstaller/bincache00_py27_64bit/_struct.so
-rwxr-xr-x  1 user  staff    32K Sep 23 16:07 Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so
```
* Does it work when you manually changes permissions of that file?
*
Maybe the fix would be that pyintaller should just set proper file permissions.

**Comment by da4e** [comment] 2015-11-07 07:26
You can fix this by edit the utils.py.
sudo vim /usr/local/lib/python2.7/site-packages/PyInstaller/building/utils.py
move to line 242, change 
```
    shutil.copy2(fnm, cachedfile)
```
to
```
    try:
        shutil.copy2(fnm, cachedfile)
    except:
        shutil.copy(fnm, cachedfile)
```

**Comment by JokerQyou** [comment] 2015-11-07 08:10
@matysek Here are the details:

* I can confirm this happens for the builtin Python in OS X; but I have not installed Python from Homebrew (and don't want to), so I don't know about Homebrew Python.
* Yes pyinstaller will fail even on helloworld code, like the code attached later.
* The permission of the file is:
```bash
$ ls -l "/Users/joker/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so"
-rwxr-xr-x  1 joker  staff  84352 10 18 07:39 /Users/joker/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so
```
* I did not understand this question. What permission should I change to?

Even this code fails:

```python
# coding: utf-8
import sys

print sys.argv or 'Hello world'
```

Full log:

```log
$ pyinstaller hi.py
107 INFO: PyInstaller: 3.1.dev0+1183c04
107 INFO: Python: 2.7.10
119 INFO: Platform: Darwin-15.0.0-x86_64-i386-64bit
120 INFO: wrote /Users/joker/Works/test/hi.spec
134 INFO: UPX is not available.
135 INFO: Extending PYTHONPATH with /Users/joker/Works/test
136 INFO: checking Analysis
136 INFO: Building Analysis because out00-Analysis.toc is non existent
136 INFO: Initializing module dependency graph...
144 INFO: Initializing module graph hooks...
210 INFO: running Analysis out00-Analysis.toc
219 INFO: Analyzing /Users/joker/Works/test/hi.py
219 INFO: Looking for import hooks ...
225 INFO: Processing hook   hook-encodings.py
2126 INFO: Looking for ctypes DLLs
2126 INFO: Analyzing run-time hooks ...
2130 INFO: Looking for dynamic libraries
2251 INFO: Looking for eggs
2251 INFO: Python library not in binary depedencies. Doing additional searching...
2253 INFO: Using Python library /Users/joker/Works/test/test/bin/../.Python
2256 INFO: Warnings written to /Users/joker/Works/test/build/hi/warnhi.txt
2315 INFO: checking PYZ
2315 INFO: Building PYZ because out00-PYZ.toc is non existent
2316 INFO: Building PYZ (ZlibArchive) /Users/joker/Works/test/build/hi/out00-PYZ.pyz
2451 INFO: checking PKG
2451 INFO: Building PKG because out00-PKG.toc is non existent
2451 INFO: Building PKG (CArchive) out00-PKG.pkg
2462 INFO: Bootloader /Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/bootloader/Darwin-64bit/run
2463 INFO: checking EXE
2463 INFO: Building EXE because out00-EXE.toc is non existent
2463 INFO: Building EXE from out00-EXE.toc
2473 INFO: Appending archive to EXE /Users/joker/Works/test/build/hi/hi
2475 INFO: Fixing EXE for code signing /Users/joker/Works/test/build/hi/hi
2483 INFO: checking COLLECT
2485 INFO: Building COLLECT because out00-COLLECT.toc is non existent
2486 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
  File "/Users/joker/Works/test/test/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.1.dev0+1183c04', 'console_scripts', 'pyinstaller')()
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/build_main.py", line 738, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/api.py", line 672, in __init__
    self.__postinit__()
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/api.py", line 704, in assemble
    dist_nm=inm)
  File "/Users/joker/Works/test/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/utils.py", line 242, in checkCache
    shutil.copy2(fnm, cachedfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/joker/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so'
```

**Comment by f418** [comment] 2015-11-07 08:27
you can change utils.py
sudo vim /Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+1183c04-py2.7.egg/PyInstaller/building/utils.py
change line 242
```
        shutil.copy2(fnm, cachedfile)
```
to 
```
    try:
        shutil.copy2(fnm, cachedfile)
    except:
        shutil.copy(fnm, cachedfile)
```

**Comment by JokerQyou** [comment] 2015-11-24 02:54
@f418 I just tried your suggestion, and it seems like there's more than one place we need to change from `copy2` to `copy`, here is the new output:

```log
26600 INFO: Building BUNDLE out00-BUNDLE.toc
26647 INFO: moving BUNDLE data files to Resource directory
Traceback (most recent call last):
  File "/Users/joker/Works/edo/assistent/test/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.1.dev0+e3dcf94.mod', 'console_scripts', 'pyinstaller')()
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+e3dcf94.mod-py2.7.egg/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+e3dcf94.mod-py2.7.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+e3dcf94.mod-py2.7.egg/PyInstaller/building/build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+e3dcf94.mod-py2.7.egg/PyInstaller/building/build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 85, in <module>
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+e3dcf94.mod-py2.7.egg/PyInstaller/building/osx.py", line 85, in __init__
    self.__postinit__()
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+e3dcf94.mod-py2.7.egg/PyInstaller/building/datastruct.py", line 163, in __postinit__
    self.assemble()
  File "/Users/joker/Works/edo/assistent/test/lib/python2.7/site-packages/PyInstaller-3.1.dev0+e3dcf94.mod-py2.7.egg/PyInstaller/building/osx.py", line 195, in assemble
    shutil.copy2(fnm, tofnm)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/joker/Works/edo/assistent/dist/EdoAssistent.app/Contents/Resources/tcl/msgs/hi.msg'
```

**Comment by JokerQyou** [comment] 2015-11-24 02:59
More detailed information:

I'm running pyinstaller within a virtualenv environment, thus I think everything in it is readable by me (which is the user running pyinstaller). The only exception being this virtualenv has access to python packages installed system-wide (this was because I installed PyQt in system python path). Pyinstaller was installed within the virtualenv.

**Comment by matysek** [comment] 2015-11-30 21:02
* It looks like copy files with preserving the permissions is cause of this issue:
  * `shutil.copy` works but `shutil.copy2` does not.
* I think it is a better idea to preserve file permissions.
* This issue looks like related to any file system permissions in recent OS X El Capitano.

We need figure out what kind of permission is causing that. My guess is this:
  * PyInstaller needs to modify the binary files in the `bincache` folder.
  * Any permissions prevents modifying a file (probably `stat.UF_IMMUTABLE`)

**Comment by matysek** [comment] 2015-12-01 10:09
@JokerQyou could you post here the output  from the following commands when applied on file `/Users/joker/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so` without using `shutil.copy` workaround?
* `GetFileInfo`
* and
```python
import os
print(os.stat('_struct.so'))
```

**Comment by matysek** [comment] 2015-12-02 17:14
I upgraded my OS X to El Capitano and this issue is there.

**Comment by matysek** [comment] 2015-12-02 21:43
@JokerQyou It should be fixed:
I did an analysis and found out that just using `shutil.copy()` everywhere should be safe - preserve just permission bits and not file flags. Messing with OS X file flags is not a good idea.

**Closed by matysek** 2015-12-02 21:43 UTC
Labels: @medium, OS X, PY2

**Comment by JokerQyou** [comment] 2015-12-03 02:51
Sorry I was unable to respond with more information you need :( , I was kind of busy. I'll test the latest code once I get time.

**Comment by dougn** [comment] 2016-02-02 03:50
I am still running into this problem w/ PyInstaller 3.1.1
`Mon Feb  1 22:46:00 EST 2016
32 INFO: PyInstaller: 3.1.1
32 INFO: Python: 2.7.5
39 INFO: Platform: Darwin-12.4.0-x86_64-i386-64bit
40 INFO: wrote /Volumes/Data/local/dnapoleone/devtools/p4m/imglx/p4m.spec
47 INFO: UPX is not available.
47 INFO: Removing temporary files and cleaning cache in /home/dnapoleone/Library/Application Support/pyinstaller
56 INFO: Extending PYTHONPATH with paths
['/Volumes/Data/local/dnapoleone/devtools/p4m/builtsrc/imglx',
 '/Volumes/Data/local/dnapoleone/devtools/p4m/imglx']
56 INFO: checking Analysis
56 INFO: Building Analysis because out00-Analysis.toc is non existent
56 INFO: Initializing module dependency graph...
59 INFO: Initializing module graph hooks...
108 INFO: running Analysis out00-Analysis.toc
121 INFO: Analyzing /Volumes/Data/local/dnapoleone/devtools/p4m/builtsrc/imglx/p4m.py
2740 INFO: Processing pre-find module path hook   distutils
2746 INFO: distutils: retargeting to non-venv dir '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils'
4211 INFO: Processing pre-safe import module hook   _xmlplus
4256 INFO: Looking for import hooks ...
4259 INFO: Processing hook   hook-distutils.py
4275 INFO: Processing hook   hook-xml.py
4355 INFO: Processing hook   hook-httplib.py
4355 INFO: Processing hook   hook-pydoc.py
4357 INFO: Excluding import 'Tkinter'
4358 WARNING:   From pydoc removing import Tkinter
4358 INFO: Processing hook   hook-encodings.py
4811 INFO: Processing hook   hook-_tkinter.py
4820 INFO: checking Tree
4820 INFO: Building Tree because out00-Tree.toc is non existent
4820 INFO: Building Tree out00-Tree.toc
4935 INFO: checking Tree
4935 INFO: Building Tree because out01-Tree.toc is non existent
4935 INFO: Building Tree out01-Tree.toc
4979 INFO: Processing hook   hook-p4mlib.py
5004 INFO: Looking for ctypes DLLs
5096 INFO: Analyzing run-time hooks ...
5115 INFO: Looking for dynamic libraries
5347 INFO: Looking for eggs
5348 INFO: Using Python library /Volumes/Data/local/dnapoleone/devtools/alien/foo.env/bin/../.Python
5359 INFO: Warnings written to /Volumes/Data/local/dnapoleone/devtools/p4m/imglx/p4m/warnp4m.txt
5548 INFO: checking PYZ
5548 INFO: Building PYZ because out00-PYZ.toc is non existent
5549 INFO: Building PYZ (ZlibArchive) /Volumes/Data/local/dnapoleone/devtools/p4m/imglx/p4m/out00-PYZ.pyz
6080 INFO: checking PKG
6080 INFO: Building PKG because out00-PKG.toc is non existent
6080 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/bin/pyinstaller", line 14, in <module>
    sys.exit(run())
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/building/api.py", line 489, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/building/api.py", line 280, in __init__
    self.__postinit__()
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 183, in __postinit__
    self.assemble()
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/building/api.py", line 343, in assemble
    dist_nm=inm)
  File "/Volumes/Data/local/dnapoleone/devtools/make.inc/imglx/DevTools_imglx.env/lib/python2.7/site-packages/PyInstaller/building/utils.py", line 252, in checkCache
    os.chflags(cachedfile, 0)
OSError: [Errno 45] Operation not supported: '/home/dnapoleone/Library/Application Support/pyinstaller/bincache00_py27_64bit/_struct.so'
`

**Comment by htgoebel** [comment] 2016-02-02 10:10
@dougn Please open a *new* issue. This one was scheduled for 3.1 and is **closed**, so nobody will have an eye on it.
