### ISSUE TITLE
Help: Default system icon

### ISSUE THREAD

**Issue by xp4xbox** [pyinstaller/pyinstaller#3021] opened 2017-11-20 23:59 UTC
Is there a way to use the default system icon for the .exe?

**Comment by htgoebel** [comment] 2017-12-02 14:59
What is the "default system icon"?
Possible duplicate of #2995.

**Comment by xp4xbox** [comment] 2017-12-03 17:48
I mean, when there is no icon, and window gives the .exe icon which varies depending on the windows version.

**Comment by htgoebel** [comment] 2017-12-03 18:06
The .exe generated by PyInstaller always has an icon. You can replace the icon by using `--icon` and providing a proper .ico file. I don't understand what you mean.

**Comment by xp4xbox** [comment] 2017-12-03 18:10
For example, if you use py2exe to generate an icon, it will give the program no icon, which means that windows automatically gives it an icon that is registered to a .exe file.

**Comment by htgoebel** [comment] 2017-12-03 18:13
This is not supported. PyInstaller always includes an icon. If you want this to be changed, please implement #870 and plus an option `--icon=NONE`.

**Closed by htgoebel** 2017-12-03 18:13 UTC
Labels: support, Windows

**Comment by xp4xbox** [comment] 2017-12-05 21:59
I guess i will just use resource hacker for the time being
