### ISSUE TITLE
error with skimage

### ISSUE THREAD

**Issue by masklu** [pyinstaller/pyinstaller#3055] opened 2017-11-30 05:42 UTC
`import sys
import threading
import time
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from skimage import io, measure, color, transform

####################################################################
def main():
    app = QApplication(sys.argv)
    w = MyWindow()
    w.show()
    sys.exit(app.exec_())

####################################################################
class MyWindow(QWidget):
    def __init__(self, *args):
        QWidget.__init__(self, *args)

        # create table
        self.list_data = ["1", "2", "3", "4"]
        self.lm = MyListModel(self.list_data, self)

        self.lv = QListView()
        self.lv.setModel(self.lm)

        # layout
        layout = QVBoxLayout()
        layout.addWidget(self.lv)
        self.setLayout(layout)
        self.i = 5
        mt = threading.Thread(target=self.updatethread, name="mt")
        mt.daemon = True
        mt.start()
    def updatethread(self):
        while True:
            print(self.i)
            self.list_data.append(str(self.i))
            self.i += 1
            self.lv.setModel(MyListModel(self.list_data, self))
            self.lv.update()

            time.sleep(0.5)
            self.lv.scrollToBottom()

####################################################################
class MyListModel(QAbstractListModel):
    def __init__(self, datain, parent=None, *args):
        """ datain: a list where each item is a row
        """
        QAbstractListModel.__init__(self, parent, *args)
        self.listdata = datain

    def rowCount(self, parent=QModelIndex()):
        return len(self.listdata)

    def data(self, index, role):
        if index.isValid() and role == Qt.DisplayRole:
            return QVariant(self.listdata[index.row()])
        else:
            return QVariant()

####################################################################
if __name__ == "__main__":
    main()
`
 if i import skimge like "from skimage import io, measure, color, transform"

and use command 

"pyinstaller -w -p C:\Python35\Lib\site-packages laser.py" 

will fail

  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2202, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1416, in import_hook
    source_package, target_module_partname, level)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1568, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\python35\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1979, in _safe_import_module
    module_partname, search_dirs, parent_module)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2853, in _find_module
    return self._find_module_path(fullname, name, path)
  File "c:\python35\lib\site-packages\PyInstaller\depend\analysis.py", line 315, in _find_module_path
    fullname, module_name, search_dirs)
  File "c:\python35\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2934, in _find_module_path
    module_name)
  File "<frozen importlib._bootstrap_external>", line 1237, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 60, in _path_join
RecursionError: maximum recursion depth exceeded

if i remove "from skimage import io, measure, color, transform" will be ok
Windows 10 , Python3.5.4, pyinstaller 3.3, skimage 0.13.1
how to solve  this problem?
 Thanks

**Comment by htgoebel** [comment] 2017-11-30 12:05
Duplicate of #2919

**Comment by htgoebel** [comment] 2017-11-30 12:06
Additional, this code is **far** from being a Minimal example.

**Closed by htgoebel** 2017-11-30 12:05 UTC
Labels: duplicate

**Comment by masklu** [comment] 2017-12-01 01:59
@htgoebel  i got the same error on Python 3.5.3

**Comment by htgoebel** [comment] 2017-12-01 09:57
@masklu Nevertheless this is a duplicate..

**Comment by masklu** [comment] 2017-12-01 09:59
@htgoebel I try on three computer got the same error ,change Python version can't solve

**Comment by htgoebel** [comment] 2017-12-01 10:15
@masklu Nevertheless this is a duplicate.
