### ISSUE TITLE
enhancement : put all other files (except executable) in one folder

### ISSUE THREAD

**Issue by jcyrss** [pyinstaller/pyinstaller#3606] opened 2018-06-29 06:26 UTC
After using PyInstaller to create an executable, many files are created and stored in the dist folder, along with the executable. It may take a long time for a user to find where the executable file is.  

For example:
![image](https://user-images.githubusercontent.com/10496014/42076595-5f9f8e5a-7ba8-11e8-8088-42eb3ebce95e.png)

Can all other files except the executable be placed in another different folder?

I don't want to use the --onefile option to bundle everything into one executable. The --onefile flag will make pyinstaller to compresses the file, and every time we run the executable it takes a very long time to uncompress.

**Comment by htgoebel** [comment] 2018-06-29 10:56
Duplicate of  #2702, youa re invited to work on that :-)

**Closed by htgoebel** 2018-06-29 10:56 UTC
Labels: feature
