### ISSUE TITLE
--key= option fails

### ISSUE THREAD

**Issue by Berserker66** [pyinstaller/pyinstaller#3524] opened 2018-05-18 06:51 UTC
Version: Develop.zip, and latest stable from pip
Python: 3.6.5, 64Bit
Latest pip pycryptdome
Getting:

```
450 INFO: Building PYZ (ZlibArchive) D:\Projects\HonorarPlus\build\main\PYZ-00.pyz
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+1033a8770', 'console_scripts', 'pyinstaller')()
  File "c:\program files\python36\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\program files\python36\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 814, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 760, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\api.py", line 133, in assemble
    pyz = ZlibArchiveWriter(self.name, toc, code_dict=self.code_dict, cipher=self.cipher)
  File "c:\program files\python36\lib\site-packages\PyInstaller\archive\writers.py", line 184, in __init__
    super(ZlibArchiveWriter, self).__init__(archive_path, logical_toc)
  File "c:\program files\python36\lib\site-packages\PyInstaller\archive\writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "c:\program files\python36\lib\site-packages\PyInstaller\archive\writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "c:\program files\python36\lib\site-packages\PyInstaller\archive\writers.py", line 213, in add
    obj = self.cipher.encrypt(obj)
  File "c:\program files\python36\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 58, in encrypt
    return iv + self.__create_cipher(iv).encrypt(data)
  File "c:\program files\python36\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 64, in __create_cipher
    return self._aesmod.new(self.key, self._aesmod.MODE_CFB, iv)
  File "c:\program files\python36\lib\site-packages\Crypto\Cipher\AES.py", line 200, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\Crypto\Cipher\__init__.py", line 55, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "c:\program files\python36\lib\site-packages\Crypto\Cipher\_mode_cfb.py", line 230, in _create_cfb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "c:\program files\python36\lib\site-packages\Crypto\Cipher\AES.py", line 100, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "c:\program files\python36\lib\site-packages\Crypto\Util\_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
```

with command pyinstaller main.py --noupx --key=MS88JtoxN4G1E29k

noupx is in there as it would break on VCRUNTIME140.dll and that was a recommended "fix". Adding the key option makes it break yet again.

**Comment by htgoebel** [comment] 2018-05-28 17:14
Duplicate of #3531

**Closed by htgoebel** 2018-05-28 17:14 UTC
