### ISSUE TITLE
“getfullnameof” function for loop wrong indent？

### ISSUE THREAD

**Issue by genyez** [pyinstaller/pyinstaller#4174] opened 2019-04-15 09:37 UTC
HI～
Is line85～line88 has an extra indent？
I can't see the necessity of the indent. 
I apologise for the inconvenience if my question is silly...
@htgoebel 

https://github.com/pyinstaller/pyinstaller/blob/b54a15d72e81e39cde0811d2b7442b09e658801d/PyInstaller/depend/bindepend.py#L80-L89

**Comment by htgoebel** [comment] 2019-08-07 15:37
Thansk for reporting, this was fixed in #4285 

Duplicate of #4285

**Closed by htgoebel** 2019-08-07 15:37 UTC
